// Week 2 — generated by tools/build_weeks.js from content/n8n/src/w02.js. Edit the source, not this file.
JOURNEY.week({
 "track": "n8n",
 "n": 2,
 "month": 1,
 "level": {
  "ar": "مبتدئ",
  "en": "Beginner"
 },
 "title": {
  "ar": "الطرفية وGit وJSON للي بيأتمت",
  "en": "Terminal, Git and JSON for automators"
 },
 "goal": {
  "ar": "تشتغل من الطرفية براحتك (PowerShell أو Bash)، وتشغّل n8n وتحدّثه منها، وتحفظ الـ workflows في Git، وتقرا وتكتب JSON من غير أخطاء، وتختبر APIs بـ curl.",
  "en": "Work comfortably in the terminal (PowerShell or Bash), run and update n8n from it, keep your workflows in Git, read and write JSON without errors, and test APIs with curl."
 },
 "days": [
  {
   "d": 1,
   "title": {
    "ar": "الطرفية: تتحرك وتشغّل",
    "en": "The terminal: moving around and running things"
   },
   "goal": {
    "ar": "تتنقل بين الفولدرات، وتعمل وتمسح ملفات، وتشغّل n8n وأوامر بأمان.",
    "en": "Move between folders, create and delete files, and run n8n and other commands safely."
   },
   "learn": [
    {
     "h": {
      "ar": "الأوامر الأساسية",
      "en": "The basic commands"
     },
     "p": {
      "ar": "`pwd` انت فين، `ls` (أو `dir`) إيه اللي هنا، `cd folder` ادخل، `cd ..` ارجع، `mkdir` اعمل فولدر، `cat file` اقرا ملف. نفس الفكرة في PowerShell وBash مع اختلافات بسيطة.",
      "en": "`pwd` where you are, `ls` (or `dir`) what is here, `cd folder` go in, `cd ..` go up, `mkdir` make a folder, `cat file` read a file. The same ideas work in PowerShell and Bash with small differences."
     },
     "ex": "mkdir n8n-projects\ncd n8n-projects\nls\ncat notes.txt"
    },
    {
     "h": {
      "ar": "تشغيل n8n من الطرفية",
      "en": "Running n8n from the terminal"
     },
     "p": {
      "ar": "`npx n8n` بيشغّل آخر نسخة من غير تثبيت دايم، و`npm install -g n8n` بيثبّتها. الطرفية لازم تفضل مفتوحة، و`Ctrl+C` بيوقف n8n.",
      "en": "`npx n8n` runs the latest version without a permanent install, and `npm install -g n8n` installs it. The terminal must stay open; `Ctrl+C` stops n8n."
     },
     "ex": "node -v        # check Node.js is installed\nnpx n8n        # start n8n on http://localhost:5678\nCtrl+C         # stop it"
    },
    {
     "h": {
      "ar": "متغيّرات البيئة",
      "en": "Environment variables"
     },
     "p": {
      "ar": "n8n بيتظبط بمتغيّرات بيئة. في PowerShell: `$env:GENERIC_TIMEZONE=\"Africa/Cairo\"`، وفي Bash: `export GENERIC_TIMEZONE=Africa/Cairo`، وبعدين شغّل n8n في نفس الطرفية.",
      "en": "n8n is configured with environment variables. In PowerShell: `$env:GENERIC_TIMEZONE=\"Africa/Cairo\"`; in Bash: `export GENERIC_TIMEZONE=Africa/Cairo`; then start n8n in the same terminal."
     },
     "ex": "$env:GENERIC_TIMEZONE = \"Africa/Cairo\"   # PowerShell\nexport GENERIC_TIMEZONE=Africa/Cairo     # Bash\nnpx n8n"
    }
   ],
   "practice": [
    {
     "ar": "اعمل فولدر `n8n-projects` وجواه 3 فولدرات، وادخل واطلع منهم بالأوامر بس.",
     "en": "Create an `n8n-projects` folder with 3 folders inside, and move in and out of them using commands only."
    },
    {
     "ar": "اتأكد إن Node.js متثبت (`node -v`) وشغّل n8n بـ `npx n8n` ووقّفه بـ Ctrl+C.",
     "en": "Check Node.js is installed (`node -v`), start n8n with `npx n8n` and stop it with Ctrl+C."
    },
    {
     "ar": "ظبّط `GENERIC_TIMEZONE` على توقيتك وشغّل n8n، واتأكد إن `{{ $now }}` بيطلع الساعة الصح.",
     "en": "Set `GENERIC_TIMEZONE` to your timezone, start n8n and check that `{{ $now }}` shows the right time."
    },
    {
     "ar": "اكتب ملف `commands.md` فيه 10 أوامر وجنب كل واحد بيعمل إيه.",
     "en": "Write a `commands.md` file with 10 commands and what each one does."
    }
   ],
   "code": [
    {
     "u": {
      "ar": "أوامر مكافئة",
      "en": "Equivalent commands"
     },
     "p": "Task            PowerShell            Bash\nlist files      Get-ChildItem (ls)    ls -la\nread a file     Get-Content f.txt     cat f.txt\nset a variable  $env:X=\"1\"            export X=1\nclear screen    cls                   clear"
    }
   ],
   "words": [
    {
     "t": "terminal",
     "m": {
      "ar": "الطرفية — نافذة تنفيذ الأوامر",
      "en": "The window where you run commands"
     },
     "ex": "PS C:\\Users\\me> "
    },
    {
     "t": "environment variable",
     "m": {
      "ar": "متغيّر إعداد خارج الكود",
      "en": "A setting kept outside the code"
     },
     "ex": "GENERIC_TIMEZONE=Africa/Cairo"
    },
    {
     "t": "npx",
     "m": {
      "ar": "بيشغّل حزمة npm من غير ما تثبتها دايمًا",
      "en": "runs an npm package without installing it permanently"
     },
     "ex": "npx n8n"
    },
    {
     "t": "path",
     "m": {
      "ar": "مسار ملف أو فولدر على الجهاز",
      "en": "the location of a file or folder on the computer"
     },
     "ex": "C:\\Users\\me\\n8n-projects"
    },
    {
     "t": "working directory",
     "m": {
      "ar": "الفولدر اللي الطرفية واقفة فيه دلوقتي",
      "en": "the folder the terminal is currently in"
     },
     "ex": "pwd shows the working directory."
    }
   ],
   "read": [
    {
     "t": "PowerShell 101 (Microsoft Learn)",
     "url": "https://learn.microsoft.com/en-us/powershell/scripting/learn/ps101/00-introduction",
     "what": {
      "ar": "الفصول 1–3.",
      "en": "Chapters 1–3."
     }
    },
    {
     "t": "explainshell",
     "url": "https://explainshell.com/",
     "what": {
      "ar": "الزق فيه 3 أوامر Bash بتستخدمها وشوف كل جزء بيعمل إيه.",
      "en": "Paste 3 Bash commands you use and see what each part does."
     }
    }
   ],
   "challenge": {
    "ar": "اكتب سكربت صغير (`start-n8n.ps1` أو `start-n8n.sh`) بيظبط التوقيت ويشغّل n8n، وشغّله.",
    "en": "Write a small script (`start-n8n.ps1` or `start-n8n.sh`) that sets the timezone and starts n8n, and run it."
   },
   "quiz": [
    {
     "q": {
      "ar": "`cd ..` بيعمل إيه؟",
      "en": "What does `cd ..` do?"
     },
     "o": [
      {
       "ar": "يرجع فولدر لفوق",
       "en": "goes up one folder"
      },
      {
       "ar": "يمسح الفولدر",
       "en": "deletes the folder"
      },
      {
       "ar": "يعرض الملفات",
       "en": "lists the files"
      }
     ],
     "a": 0,
     "why": {
      "ar": "`..` = الفولدر الأب.",
      "en": "`..` = the parent folder."
     }
    },
    {
     "q": {
      "ar": "إزاي توقف n8n اللي شغال في الطرفية؟",
      "en": "How do you stop n8n running in the terminal?"
     },
     "o": [
      "Ctrl+C",
      "Ctrl+S",
      {
       "ar": "تقفل المتصفح",
       "en": "close the browser"
      }
     ],
     "a": 0,
     "why": {
      "ar": "Ctrl+C بيوقف البرنامج الشغال.",
      "en": "Ctrl+C stops the running program."
     }
    },
    {
     "q": {
      "ar": "في Bash، تعمل متغيّر بيئة بـ:",
      "en": "In Bash you set an environment variable with:"
     },
     "o": [
      "export X=1",
      "$env:X=\"1\"",
      "set-var X 1"
     ],
     "a": 0,
     "why": {
      "ar": "`$env:` ده PowerShell.",
      "en": "`$env:` is PowerShell."
     }
    }
   ],
   "minutes": 120
  },
  {
   "d": 2,
   "title": {
    "ar": "JSON بإيدك",
    "en": "JSON by hand"
   },
   "goal": {
    "ar": "تكتب JSON صحيح، وتلاقي الغلط فيه، وتفهم الفرق بين object وarray، وإزاي n8n بيشوفه.",
    "en": "Write valid JSON, find mistakes in it, understand objects vs. arrays, and see how n8n reads it."
   },
   "learn": [
    {
     "h": {
      "ar": "قواعد JSON",
      "en": "JSON rules"
     },
     "p": {
      "ar": "المفاتيح والنصوص بين علامات تنصيص مزدوجة \"، مفيش فاصلة بعد آخر عنصر، والقيم: string أو number أو true/false أو null أو object {} أو array [].",
      "en": "Keys and strings use double quotes \", no comma after the last item, and values are a string, number, true/false, null, an object {} or an array []."
     },
     "ex": "{\n  \"name\": \"Ali\",\n  \"age\": 30,\n  \"active\": true,\n  \"tags\": [\"vip\", \"cairo\"],\n  \"address\": { \"city\": \"Cairo\" }\n}"
    },
    {
     "h": {
      "ar": "أشهر 4 أخطاء",
      "en": "The four most common mistakes"
     },
     "p": {
      "ar": "فاصلة زيادة في الآخر، علامات تنصيص مفردة '، مفتاح من غير تنصيص، وتعليقات // (JSON مفيهوش تعليقات).",
      "en": "A trailing comma, single quotes ', a key without quotes, and // comments (JSON has no comments)."
     },
     "ex": "✗ { name: 'Ali', }\n✓ { \"name\": \"Ali\" }"
    },
    {
     "h": {
      "ar": "JSON جوه n8n",
      "en": "JSON inside n8n"
     },
     "p": {
      "ar": "كل item في n8n هو object، والبيانات كلها array من items. تقدر تلزق JSON في Code node أو Edit Fields (JSON mode) أو في Pin Data.",
      "en": "Every n8n item is an object, and the data is an array of items. You can paste JSON into a Code node, Edit Fields (JSON mode) or Pin Data."
     },
     "ex": "[\n  { \"json\": { \"name\": \"Ali\" } },\n  { \"json\": { \"name\": \"Sara\" } }\n]"
    }
   ],
   "practice": [
    {
     "ar": "اكتب بإيدك JSON لعميل فيه اسم وإيميل وقايمة طلبات (كل طلب object).",
     "en": "Write JSON by hand for a customer with a name, an email and a list of orders (each order an object)."
    },
    {
     "ar": "صلّح 5 JSON غلط (هتلاقيهم في قسم «انسخ واستخدم») واتأكد بـ JSONLint.",
     "en": "Fix 5 broken JSON snippets (in \"Copy and use\") and check them with JSONLint."
    },
    {
     "ar": "الزق الـ JSON بتاعك في Edit Fields بـ JSON mode، وشوفه في Table وJSON وSchema.",
     "en": "Paste your JSON into Edit Fields in JSON mode, and view it as Table, JSON and Schema."
    },
    {
     "ar": "اقرا بـ Expression قيمة جوه nested object: `{{ $json.address.city }}` وقيمة من array: `{{ $json.tags[0] }}`.",
     "en": "Read a nested value with an expression: `{{ $json.address.city }}`, and one from an array: `{{ $json.tags[0] }}`."
    }
   ],
   "code": [
    {
     "u": {
      "ar": "JSON فيه أخطاء تصلحها",
      "en": "Broken JSON to fix"
     },
     "p": "{ \"name\": \"Ali\", }\n{ 'city': 'Cairo' }\n{ age: 30 }\n{ \"items\": [1, 2, 3,] }\n{ \"ok\": True }"
    }
   ],
   "words": [
    {
     "t": "array / object",
     "m": {
      "ar": "مصفوفة (قايمة) / كائن (مجموعة حقول)",
      "en": "Array (a list) / object (a group of fields)"
     },
     "ex": "[1,2,3]  /  { \"a\": 1 }"
    },
    {
     "t": "key / value",
     "m": {
      "ar": "مفتاح / قيمة",
      "en": "Key / value"
     },
     "ex": "\"city\": \"Cairo\""
    },
    {
     "t": "JSON validator",
     "m": {
      "ar": "أداة بتقولك الـ JSON صح ولا فيه غلط وفين",
      "en": "a tool that tells you whether JSON is valid and where the error is"
     },
     "ex": "Paste it into JSONLint before using it."
    },
    {
     "t": "trailing comma",
     "m": {
      "ar": "فاصلة زيادة بعد آخر عنصر، بتبوّظ JSON",
      "en": "an extra comma after the last item; it breaks JSON"
     },
     "ex": "[1, 2, 3,]  ← trailing comma"
    },
    {
     "t": "JSON schema (shape)",
     "m": {
      "ar": "شكل البيانات: المفاتيح وأنواعها",
      "en": "the shape of the data: the keys and their types"
     },
     "ex": "The Schema view shows the shape of each item."
    }
   ],
   "read": [
    {
     "t": "JSON.org",
     "url": "https://www.json.org/json-en.html",
     "what": {
      "ar": "الرسومات بس (5 دقايق)، وهتفهم ليه JSON بيرفض فاصلة زيادة.",
      "en": "Just the diagrams (5 minutes) — you'll see why JSON rejects a trailing comma."
     }
    },
    {
     "t": "JSONLint",
     "url": "https://jsonlint.com/",
     "what": {
      "ar": "الصق أي JSON مش شغال وشوف السطر اللي فيه المشكلة.",
      "en": "Paste any broken JSON and see the line with the problem."
     }
    }
   ],
   "challenge": {
    "ar": "خد response حقيقي من أي API عام (JSONPlaceholder مثلًا)، واكتب لكل حقل مهم الـ Expression اللي يقراه في n8n.",
    "en": "Take a real response from any public API (JSONPlaceholder, for example) and write the n8n expression that reads each important field."
   },
   "quiz": [
    {
     "q": {
      "ar": "أنهي JSON صحيح؟",
      "en": "Which JSON is valid?"
     },
     "o": [
      "{ \"a\": 1, }",
      "{ \"a\": 1 }",
      "{ 'a': 1 }"
     ],
     "a": 1,
     "why": {
      "ar": "من غير فاصلة زيادة وبعلامات تنصيص مزدوجة.",
      "en": "No trailing comma, and double quotes."
     }
    },
    {
     "q": {
      "ar": "إزاي تقرا أول tag في `{\"tags\":[\"vip\",\"new\"]}`؟",
      "en": "How do you read the first tag in `{\"tags\":[\"vip\",\"new\"]}`?"
     },
     "o": [
      "{{ $json.tags[0] }}",
      "{{ $json.tags[1] }}",
      "{{ $json.tags.first }}"
     ],
     "a": 0,
     "why": {
      "ar": "الـ array بيبدأ من 0.",
      "en": "Arrays start at 0."
     }
    },
    {
     "q": {
      "ar": "JSON بيسمح بالتعليقات؟",
      "en": "Does JSON allow comments?"
     },
     "o": [
      {
       "ar": "لأ",
       "en": "No"
      },
      {
       "ar": "أيوه بـ //",
       "en": "Yes, with //"
      },
      {
       "ar": "أيوه بـ #",
       "en": "Yes, with #"
      }
     ],
     "a": 0,
     "why": {
      "ar": "JSON مفيهوش تعليقات خالص.",
      "en": "JSON has no comments at all."
     }
    }
   ],
   "minutes": 120
  },
  {
   "d": 3,
   "title": {
    "ar": "Git للـ workflows",
    "en": "Git for workflows"
   },
   "goal": {
    "ar": "تعمل repo للـ workflows بتاعتك، وتحفظ كل workflow كملف JSON، وتعمل commit وpush.",
    "en": "Create a repo for your workflows, save each workflow as a JSON file, and commit and push."
   },
   "learn": [
    {
     "h": {
      "ar": "ليه Git مع n8n",
      "en": "Why Git with n8n"
     },
     "p": {
      "ar": "عشان ترجع لنسخة قديمة لو حاجة باظت، وتعرف مين غيّر إيه، وتنقل workflows بين أجهزة. كل workflow بيتصدّر كملف JSON (Download) ويتحط في Git.",
      "en": "To go back to an old version when something breaks, see who changed what, and move workflows between machines. Each workflow exports as a JSON file (Download) that goes into Git."
     },
     "ex": "workflows/\n  lead-alert.json\n  daily-report.json\nREADME.md"
    },
    {
     "h": {
      "ar": "الدورة الأساسية",
      "en": "The basic cycle"
     },
     "p": {
      "ar": "`git init` مرة واحدة، وبعدين كل مرة: `git add` ← `git commit -m \"…\"` ← `git push`. و`git status` بيقولك إيه اللي اتغيّر، و`git log --oneline` التاريخ.",
      "en": "`git init` once, then every time: `git add` → `git commit -m \"…\"` → `git push`. `git status` shows what changed and `git log --oneline` shows the history."
     },
     "ex": "git init\ngit add workflows/lead-alert.json\ngit commit -m \"Add lead alert workflow\"\ngit push"
    },
    {
     "h": {
      "ar": "متحطش أسرار في Git",
      "en": "Keep secrets out of Git"
     },
     "p": {
      "ar": "ملف الـ workflow مفيهوش الـ credentials نفسها (بيشاور عليها بالاسم)، بس ممكن يكون فيه URLs أو IDs حساسة. وملفات زي `.env` لازم في `.gitignore`.",
      "en": "An exported workflow doesn't contain the credentials themselves (it points to them by name), but it may hold sensitive URLs or IDs. Files like `.env` must go into `.gitignore`."
     },
     "ex": "# .gitignore\n.env\n*.sqlite\nnode_modules/"
    }
   ],
   "practice": [
    {
     "ar": "اعمل repo اسمه `my-n8n-workflows` على GitHub ونزّله على جهازك.",
     "en": "Create a repo called `my-n8n-workflows` on GitHub and clone it."
    },
    {
     "ar": "صدّر 2 workflows من n8n (Download) وحطهم في فولدر `workflows/` واعمل commit.",
     "en": "Export 2 workflows from n8n (Download), put them in a `workflows/` folder and commit."
    },
    {
     "ar": "غيّر حاجة في workflow وصدّره تاني، وشوف الفرق بـ `git diff`.",
     "en": "Change something in a workflow, export it again, and look at the difference with `git diff`."
    },
    {
     "ar": "اعمل `.gitignore` فيه `.env` واتأكد بـ `git status` إن الملف مش ظاهر.",
     "en": "Create a `.gitignore` with `.env` and check with `git status` that the file is not listed."
    }
   ],
   "words": [
    {
     "t": "repository",
     "m": {
      "ar": "مستودع الكود",
      "en": "A code repository"
     },
     "ex": "github.com/you/n8n-journey"
    },
    {
     "t": "commit",
     "m": {
      "ar": "حفظ نسخة من التعديلات",
      "en": "Saving a snapshot of your changes"
     },
     "ex": "git commit -m \"Add lead workflow\""
    },
    {
     "t": "push / pull / clone",
     "m": {
      "ar": "رفع / سحب / نسخ مستودع",
      "en": "Upload / download / copy a repository"
     },
     "ex": "git push origin main"
    },
    {
     "t": ".gitignore",
     "m": {
      "ar": "ملف بيحدد إيه اللي Git يتجاهله",
      "en": "A file that tells Git what to ignore"
     },
     "ex": ".env\nnode_modules/"
    },
    {
     "t": "git diff",
     "m": {
      "ar": "بيعرض الفرق بين نسختين من الملفات",
      "en": "shows the difference between two versions of files"
     },
     "ex": "git diff workflows/lead-alert.json"
    }
   ],
   "read": [
    {
     "t": "Pro Git",
     "url": "https://git-scm.com/book/en/v2",
     "what": {
      "ar": "الفصول 1–3 (Getting Started، Basics، Branching) في الأسبوع 1 من الخطة.",
      "en": "Chapters 1–3 (Getting Started, Basics, Branching) in week 1 of the plan."
     }
    },
    {
     "t": "Oh Shit, Git!?!",
     "url": "https://ohshitgit.com/",
     "what": {
      "ar": "اقراها مرة، وارجعلها وقت المشكلة.",
      "en": "Read it once, and come back when something goes wrong."
     }
    }
   ],
   "challenge": {
    "ar": "اعمل README للـ repo فيه جدول: اسم كل workflow، وبيعمل إيه، والـ trigger بتاعه، والـ credentials اللي محتاجها.",
    "en": "Write a README for the repo with a table: each workflow's name, what it does, its trigger and the credentials it needs."
   },
   "quiz": [
    {
     "q": {
      "ar": "الترتيب الصح:",
      "en": "The correct order:"
     },
     "o": [
      "commit → add → push",
      "add → commit → push",
      "push → add → commit"
     ],
     "a": 1,
     "why": {
      "ar": "تجهّز، تسجّل، ترفع.",
      "en": "Stage, record, upload."
     }
    },
    {
     "q": {
      "ar": "ملف الـ workflow المتصدّر فيه الباسوردات؟",
      "en": "Does an exported workflow contain the passwords?"
     },
     "o": [
      {
       "ar": "لأ، بيشاور على الـ credential بالاسم",
       "en": "No, it refers to the credential by name"
      },
      {
       "ar": "أيوه دايمًا",
       "en": "Yes, always"
      },
      {
       "ar": "أيوه مشفّرة",
       "en": "Yes, encrypted"
      }
     ],
     "a": 0,
     "why": {
      "ar": "الـ credentials بتفضل جوه n8n.",
      "en": "Credentials stay inside n8n."
     }
    },
    {
     "q": {
      "ar": "`.gitignore` بيعمل إيه؟",
      "en": "What does `.gitignore` do?"
     },
     "o": [
      {
       "ar": "بيقول لـ Git يتجاهل ملفات معينة",
       "en": "tells Git to ignore certain files"
      },
      {
       "ar": "بيمسح الملفات",
       "en": "deletes files"
      },
      {
       "ar": "بيخبي الـ repo",
       "en": "hides the repo"
      }
     ],
     "a": 0,
     "why": {
      "ar": "زي .env وnode_modules.",
      "en": "Like .env and node_modules."
     }
    }
   ],
   "minutes": 120
  },
  {
   "d": 4,
   "title": {
    "ar": "curl واختبار الـ APIs",
    "en": "curl and testing APIs"
   },
   "goal": {
    "ar": "تبعت طلبات HTTP من الطرفية بـ curl، وتستورد أمر curl في HTTP Request node.",
    "en": "Send HTTP requests from the terminal with curl, and import a curl command into the HTTP Request node."
   },
   "learn": [
    {
     "h": {
      "ar": "curl في سطر",
      "en": "curl in one line"
     },
     "p": {
      "ar": "`curl URL` = GET. `-X POST` نوع الطلب، `-H` header، `-d` body. وعلى Windows استخدم `curl.exe` عشان PowerShell عنده alias اسمه curl بيعمل حاجة تانية.",
      "en": "`curl URL` = GET. `-X POST` sets the method, `-H` a header, `-d` the body. On Windows use `curl.exe`, because PowerShell has a different command aliased as curl."
     },
     "ex": "curl.exe https://jsonplaceholder.typicode.com/users/1\ncurl.exe -X POST https://httpbin.org/post -H \"Content-Type: application/json\" -d \"{\\\"name\\\":\\\"Ali\\\"}\""
    },
    {
     "h": {
      "ar": "Import cURL",
      "en": "Import cURL"
     },
     "p": {
      "ar": "في HTTP Request node فيه زرار Import cURL: الزق أي أمر curl من التوثيق وهو بيملى الـ method والـ URL والـ headers والـ body لوحده.",
      "en": "The HTTP Request node has an Import cURL button: paste any curl command from API docs and it fills in the method, URL, headers and body for you."
     },
     "ex": "Docs: curl -H \"Authorization: Bearer TOKEN\" https://api.example.com/me\n→ HTTP Request: GET, URL, header Authorization"
    },
    {
     "h": {
      "ar": "اقرا الرد",
      "en": "Reading the response"
     },
     "p": {
      "ar": "`curl -i` بيعرض الـ status code والـ headers. والـ status أول حاجة تبصلها: 2xx تمام، 4xx غلط منك، 5xx غلط من السيرفر.",
      "en": "`curl -i` shows the status code and headers. The status is the first thing to check: 2xx is fine, 4xx is your mistake, 5xx is the server's."
     },
     "ex": "HTTP/1.1 200 OK\nContent-Type: application/json"
    }
   ],
   "practice": [
    {
     "ar": "اعمل GET بـ curl لـ JSONPlaceholder وشوف الرد.",
     "en": "Make a GET request to JSONPlaceholder with curl and read the response."
    },
    {
     "ar": "اعمل POST لـ httpbin بـ body JSON وشوف إنه رجّعلك البيانات.",
     "en": "POST a JSON body to httpbin and see it echo your data back."
    },
    {
     "ar": "خد أمر curl من توثيق أي API واعمله Import في HTTP Request node.",
     "en": "Take a curl command from any API's docs and import it into an HTTP Request node."
    },
    {
     "ar": "اعمل Webhook (Test URL) في n8n وابعتله طلب بـ curl.",
     "en": "Create a Webhook (test URL) in n8n and send it a request with curl."
    }
   ],
   "words": [
    {
     "t": "Accept header",
     "m": {
      "ar": "header بيقول للسيرفر انت عايز الرد بأنهي شكل",
      "en": "a header telling the server which response format you want"
     },
     "ex": "Accept: application/json"
    },
    {
     "t": "-d (data)",
     "m": {
      "ar": "في curl: الـ body اللي هيتبعت",
      "en": "in curl: the body to send"
     },
     "ex": "curl.exe -d \"{\\\"a\\\":1}\" …"
    },
    {
     "t": "-i (include)",
     "m": {
      "ar": "في curl: اعرض الـ status والـ headers مع الرد",
      "en": "in curl: show the status and headers with the response"
     },
     "ex": "curl.exe -i https://httpbin.org/get"
    },
    {
     "t": "echo endpoint",
     "m": {
      "ar": "endpoint بيرجّعلك نفس اللي بعته، مفيد للتجربة",
      "en": "an endpoint that sends back what you sent; useful for testing"
     },
     "ex": "httpbin.org/post echoes your request."
    },
    {
     "t": "status line",
     "m": {
      "ar": "أول سطر في الرد فيه الـ status code",
      "en": "the first line of a response, with the status code"
     },
     "ex": "HTTP/1.1 404 Not Found"
    }
   ],
   "read": [
    {
     "t": "Everything curl",
     "url": "https://everything.curl.dev/",
     "what": {
      "ar": "HTTP with curl ← Method و Post و Headers.",
      "en": "HTTP with curl → Method, Post and Headers."
     }
    },
    {
     "t": "httpbin",
     "url": "https://httpbin.org/",
     "what": {
      "ar": "جرّب /get و/post و/status/404 بـ curl.",
      "en": "Try /get, /post and /status/404 with curl."
     }
    }
   ],
   "challenge": {
    "ar": "اعمل workflow فيه Webhook بيستقبل POST ويرد بنفس البيانات + وقت الاستلام، واختبره بـ 3 أوامر curl مختلفة.",
    "en": "Build a workflow whose Webhook receives a POST and replies with the same data plus the time it arrived, and test it with 3 different curl commands."
   },
   "quiz": [
    {
     "q": {
      "ar": "على Windows PowerShell تكتب:",
      "en": "In Windows PowerShell you type:"
     },
     "o": [
      "curl.exe",
      "curl-win",
      "wget.ps"
     ],
     "a": 0,
     "why": {
      "ar": "عشان curl لوحدها alias لأمر تاني.",
      "en": "Because curl alone is an alias for another command."
     }
    },
    {
     "q": {
      "ar": "`-H` في curl بيضيف:",
      "en": "`-H` in curl adds:"
     },
     "o": [
      "a header",
      "a host",
      "a hash"
     ],
     "a": 0,
     "why": {
      "ar": "H = header.",
      "en": "H = header."
     }
    },
    {
     "q": {
      "ar": "Import cURL في n8n بيعمل إيه؟",
      "en": "What does Import cURL in n8n do?"
     },
     "o": [
      {
       "ar": "يملى إعدادات HTTP Request من أمر curl",
       "en": "fills HTTP Request settings from a curl command"
      },
      {
       "ar": "يثبّت curl",
       "en": "installs curl"
      },
      {
       "ar": "يمسح الـ headers",
       "en": "removes headers"
      }
     ],
     "a": 0,
     "why": {
      "ar": "بيوفر وقت ويقلل الأخطاء.",
      "en": "It saves time and avoids mistakes."
     }
    }
   ],
   "minutes": 120
  },
  {
   "d": 5,
   "title": {
    "ar": "تنظيم شغلك",
    "en": "Organising your work"
   },
   "goal": {
    "ar": "تنظّم الـ workflows بأسماء وtags وsticky notes، وتستخدم الـ templates والـ canvas صح.",
    "en": "Organise workflows with names, tags and sticky notes, and use templates and the canvas well."
   },
   "learn": [
    {
     "h": {
      "ar": "التسمية",
      "en": "Naming"
     },
     "p": {
      "ar": "اسم الـ workflow = بيعمل إيه: «Leads → Sheet + Telegram alert». واسم كل node = دوره: «Get new leads» مش «HTTP Request3».",
      "en": "A workflow name says what it does: \"Leads → Sheet + Telegram alert\". Each node name says its role: \"Get new leads\", not \"HTTP Request3\"."
     },
     "ex": "Workflow: Daily sales report → Email\nNodes: Every day 8am · Get yesterday's orders · Sum totals · Send report"
    },
    {
     "h": {
      "ar": "tags وsticky notes",
      "en": "Tags and sticky notes"
     },
     "p": {
      "ar": "tags بتجمّع الـ workflows (client-x، reports، prod). والـ sticky note على الـ canvas بتشرح الجزء المعقد: ليه، ومحتاج إيه، ولو وقع تعمل إيه.",
      "en": "Tags group workflows (client-x, reports, prod). A sticky note on the canvas explains a tricky part: why, what it needs, and what to do if it fails."
     },
     "ex": "Sticky note: \"This sheet must have columns name, email, phone. Owner: Mahmoud.\""
    },
    {
     "h": {
      "ar": "الـ templates",
      "en": "Templates"
     },
     "p": {
      "ar": "مكتبة n8n فيها آلاف الـ templates. خد واحد قريب من اللي عايزه، وافهمه node node، وبعدين عدّله. متشغلوش على بيانات حقيقية قبل ما تفهمه.",
      "en": "n8n's library has thousands of templates. Take one close to what you need, understand it node by node, then adapt it. Don't run it on real data before you understand it."
     },
     "ex": "n8n.io/workflows → search \"telegram google sheets\""
    }
   ],
   "practice": [
    {
     "ar": "غيّر أسماء كل الـ workflows والـ nodes عندك بالقاعدة.",
     "en": "Rename all your workflows and nodes with the rule."
    },
    {
     "ar": "ضيف tags لكل workflow (نوعه والعميل والحالة).",
     "en": "Add tags to every workflow (type, client and status)."
    },
    {
     "ar": "حط sticky note في أعقد workflow عندك تشرح 3 حاجات.",
     "en": "Add a sticky note to your most complex workflow explaining 3 things."
    },
    {
     "ar": "استورد template من مكتبة n8n واكتب شرح كل node في جملة.",
     "en": "Import a template from the n8n library and explain each node in one sentence."
    }
   ],
   "words": [
    {
     "t": "canvas",
     "m": {
      "ar": "لوحة الرسم اللي بتبني عليها الـ Workflow",
      "en": "The board where you build the workflow"
     },
     "ex": {
      "ar": "المساحة اللي بتسحب فيها النودات وتوصلها",
      "en": "The area where you drag nodes and connect them"
     }
    },
    {
     "t": "sticky note",
     "m": {
      "ar": "ملاحظة لاصقة على الـ canvas للتوثيق",
      "en": "A sticky note on the canvas for documentation"
     },
     "ex": "Shift+S → \"This part cleans phone numbers\""
    },
    {
     "t": "tags",
     "m": {
      "ar": "تصنيف الـ Workflows عشان تلاقيها",
      "en": "Labels for workflows so you can find them"
     },
     "ex": "sales · finance · production"
    },
    {
     "t": "template",
     "m": {
      "ar": "قالب — Workflow جاهز من مكتبة n8n",
      "en": "A ready-made workflow from the n8n library"
     },
     "ex": "n8n.io/workflows → Use workflow"
    },
    {
     "t": "connection",
     "m": {
      "ar": "وصلة بين نودين بتنقل البيانات",
      "en": "A link between two nodes that carries data"
     },
     "ex": {
      "ar": "Get Rows ──▶ Filter (سهم بين نودين)",
      "en": "Get Rows ──▶ Filter (an arrow between two nodes)"
     }
    }
   ],
   "read": [
    {
     "t": "n8n Workflow Templates",
     "url": "https://n8n.io/workflows/",
     "what": {
      "ar": "كل يوم: افتح Template واحد في نفس موضوع اليوم، واستورده، واقرا كل نود فيه.",
      "en": "Every day: open one template on the day's topic, import it, and read every node in it."
     }
    },
    {
     "t": "n8n Docs: Keyboard shortcuts",
     "url": "https://docs.n8n.io/keyboard-shortcuts/",
     "what": {
      "ar": "اطبعها أو احفظ أول 10.",
      "en": "Print them, or memorise the first 10."
     }
    }
   ],
   "challenge": {
    "ar": "اعمل «workflow index»: workflow واحد فيه sticky notes بتشرح كل workflows عندك ولينكاتها، وحفظه في Git.",
    "en": "Build a \"workflow index\": one workflow whose sticky notes explain all your workflows with links to them, and save it in Git."
   },
   "quiz": [
    {
     "q": {
      "ar": "أحسن اسم node:",
      "en": "The best node name:"
     },
     "o": [
      "HTTP Request3",
      "Get new orders from Shopify",
      "node"
     ],
     "a": 1,
     "why": {
      "ar": "بيقول دوره.",
      "en": "It states its role."
     }
    },
    {
     "q": {
      "ar": "sticky note بتستخدم لـ:",
      "en": "A sticky note is used to:"
     },
     "o": [
      {
       "ar": "شرح جزء من الـ workflow على الـ canvas",
       "en": "explain part of the workflow on the canvas"
      },
      {
       "ar": "تشغيل الـ workflow",
       "en": "run the workflow"
      },
      {
       "ar": "حفظ الباسوردات",
       "en": "store passwords"
      }
     ],
     "a": 0,
     "why": {
      "ar": "توثيق جوه الـ canvas.",
      "en": "Documentation on the canvas."
     }
    },
    {
     "q": {
      "ar": "قبل ما تشغّل template على بيانات حقيقية:",
      "en": "Before running a template on real data:"
     },
     "o": [
      {
       "ar": "افهمه node node",
       "en": "understand it node by node"
      },
      {
       "ar": "شغّله على طول",
       "en": "run it right away"
      },
      {
       "ar": "امسح الـ nodes",
       "en": "delete the nodes"
      }
     ],
     "a": 0,
     "why": {
      "ar": "عشان متبوّظش بيانات.",
      "en": "So you don't damage data."
     }
    }
   ],
   "minutes": 120
  },
  {
   "d": 6,
   "title": {
    "ar": "مراجعة الأسبوع والاختبار",
    "en": "Week review and test"
   },
   "goal": {
    "ar": "راجع الخمس أيام، وسلّم مشروع الأسبوع، وخد الاختبار الأسبوعي. الأسبوع 3 بيفتح لما تجيب 70% أو أكتر.",
    "en": "Review the five days, hand in the weekly project, and take the weekly test. Week 3 opens when you score 70% or more."
   },
   "review": [
    {
     "ar": "أوامر الطرفية، وتشغيل n8n، ومتغيّرات البيئة.",
     "en": "Terminal commands, running n8n, and environment variables."
    },
    {
     "ar": "JSON: علامات تنصيص مزدوجة، من غير فاصلة زيادة، object وarray.",
     "en": "JSON: double quotes, no trailing comma, objects and arrays."
    },
    {
     "ar": "Git: add ← commit ← push، و.gitignore للأسرار.",
     "en": "Git: add → commit → push, and .gitignore for secrets."
    },
    {
     "ar": "curl وImport cURL وقراءة الـ status.",
     "en": "curl, Import cURL and reading the status."
    },
    {
     "ar": "التسمية والـ tags والـ sticky notes والـ templates.",
     "en": "Naming, tags, sticky notes and templates."
    }
   ],
   "project": {
    "ar": "اعمل repo «my-n8n-workflows» كامل: فيه 3 workflows متصدّرة بأسماء واضحة، وREADME بجدول الـ workflows، و.gitignore، وسكربت يشغّل n8n بالتوقيت الصح، وملف `api-tests.md` فيه 5 أوامر curl جربتها على الـ Webhooks بتاعتك.",
    "en": "Build a complete \"my-n8n-workflows\" repo: 3 exported workflows with clear names, a README with a workflow table, a .gitignore, a script that starts n8n with the right timezone, and an `api-tests.md` file with 5 curl commands you ran against your webhooks."
   },
   "test": [
    {
     "q": {
      "ar": "`pwd` بيعرض:",
      "en": "`pwd` shows:"
     },
     "o": [
      {
       "ar": "الفولدر الحالي",
       "en": "the current folder"
      },
      {
       "ar": "الباسورد",
       "en": "the password"
      },
      {
       "ar": "الملفات",
       "en": "the files"
      }
     ],
     "a": 0,
     "why": {
      "ar": "print working directory.",
      "en": "print working directory."
     }
    },
    {
     "q": {
      "ar": "`npx n8n` بيعمل:",
      "en": "`npx n8n`:"
     },
     "o": [
      {
       "ar": "يشغّل n8n من غير تثبيت دايم",
       "en": "runs n8n without a permanent install"
      },
      {
       "ar": "يمسح n8n",
       "en": "removes n8n"
      },
      {
       "ar": "يحدّث Node",
       "en": "updates Node"
      }
     ],
     "a": 0,
     "why": {
      "ar": "npx بيشغّل حزمة مباشرة.",
      "en": "npx runs a package directly."
     }
    },
    {
     "q": {
      "ar": "أنهي JSON صحيح؟",
      "en": "Which JSON is valid?"
     },
     "o": [
      "{ \"ok\": true }",
      "{ \"ok\": True }",
      "{ ok: true }"
     ],
     "a": 0,
     "why": {
      "ar": "true بحروف صغيرة والمفتاح بين \"\".",
      "en": "Lowercase true and a quoted key."
     }
    },
    {
     "q": {
      "ar": "في `{\"user\":{\"email\":\"a@b.c\"}}` الإيميل بيتقري:",
      "en": "In `{\"user\":{\"email\":\"a@b.c\"}}` the email is read with:"
     },
     "o": [
      "{{ $json.user.email }}",
      "{{ $json.email }}",
      "{{ $json[user] }}"
     ],
     "a": 0,
     "why": {
      "ar": "nested: user ثم email.",
      "en": "Nested: user, then email."
     }
    },
    {
     "q": {
      "ar": "`git status` بيقولك:",
      "en": "`git status` tells you:"
     },
     "o": [
      {
       "ar": "إيه اللي اتغيّر ولسه متسجّلش",
       "en": "what changed and isn't committed yet"
      },
      {
       "ar": "سرعة النت",
       "en": "internet speed"
      },
      {
       "ar": "الباسورد",
       "en": "the password"
      }
     ],
     "a": 0,
     "why": {
      "ar": "حالة الـ repo.",
      "en": "The state of the repo."
     }
    },
    {
     "q": {
      "ar": "فين تحط `.env`؟",
      "en": "Where should `.env` go?"
     },
     "o": [
      {
       "ar": "في .gitignore",
       "en": "in .gitignore"
      },
      {
       "ar": "في README",
       "en": "in the README"
      },
      {
       "ar": "في commit",
       "en": "in a commit"
      }
     ],
     "a": 0,
     "why": {
      "ar": "فيه أسرار.",
      "en": "It holds secrets."
     }
    },
    {
     "q": {
      "ar": "`curl -X POST` معناها:",
      "en": "`curl -X POST` means:"
     },
     "o": [
      {
       "ar": "ابعت طلب POST",
       "en": "send a POST request"
      },
      {
       "ar": "امسح",
       "en": "delete"
      },
      {
       "ar": "اطبع",
       "en": "print"
      }
     ],
     "a": 0,
     "why": {
      "ar": "-X = method.",
      "en": "-X = method."
     }
    },
    {
     "q": {
      "ar": "500 Internal Server Error معناها:",
      "en": "500 Internal Server Error means:"
     },
     "o": [
      {
       "ar": "مشكلة في السيرفر",
       "en": "a problem on the server"
      },
      {
       "ar": "الـ URL غلط",
       "en": "the URL is wrong"
      },
      {
       "ar": "مفيش صلاحية",
       "en": "no permission"
      }
     ],
     "a": 0,
     "why": {
      "ar": "5xx = السيرفر.",
      "en": "5xx = the server."
     }
    },
    {
     "q": {
      "ar": "أحسن اسم workflow:",
      "en": "The best workflow name:"
     },
     "o": [
      "My workflow 7",
      "New invoices → Telegram alert",
      "test"
     ],
     "a": 1,
     "why": {
      "ar": "بيقول بيعمل إيه.",
      "en": "It says what it does."
     }
    },
    {
     "q": {
      "ar": "tags في n8n بتفيد في:",
      "en": "Tags in n8n help to:"
     },
     "o": [
      {
       "ar": "تجميع وتصنيف الـ workflows",
       "en": "group and filter workflows"
      },
      {
       "ar": "تسريع التشغيل",
       "en": "speed up runs"
      },
      {
       "ar": "الأمان",
       "en": "security"
      }
     ],
     "a": 0,
     "why": {
      "ar": "تنظيم.",
      "en": "Organisation."
     }
    },
    {
     "q": {
      "ar": "Download في n8n بيصدّر الـ workflow كـ:",
      "en": "Download in n8n exports the workflow as:"
     },
     "o": [
      "JSON",
      "PDF",
      "CSV"
     ],
     "a": 0,
     "why": {
      "ar": "ملف JSON تحطه في Git.",
      "en": "A JSON file you can put in Git."
     }
    },
    {
     "q": {
      "ar": "`GENERIC_TIMEZONE` بيأثر على:",
      "en": "`GENERIC_TIMEZONE` affects:"
     },
     "o": [
      {
       "ar": "التوقيت في Schedule و$now",
       "en": "the time used by Schedule and $now"
      },
      {
       "ar": "لغة n8n",
       "en": "n8n's language"
      },
      {
       "ar": "البورت",
       "en": "the port"
      }
     ],
     "a": 0,
     "why": {
      "ar": "عشان المواعيد تبقى صح.",
      "en": "So schedules run at the right time."
     }
    }
   ],
   "minutes": 120
  }
 ]
});
