// Week 14 — generated by tools/build_weeks.js from content/n8n/src/w14.js. Edit the source, not this file.
JOURNEY.week({
 "track": "n8n",
 "n": 14,
 "month": 4,
 "level": {
  "ar": "متوسط",
  "en": "Intermediate"
 },
 "title": {
  "ar": "الملفات: CSV وExcel وPDF",
  "en": "Files: CSV, Excel and PDF"
 },
 "goal": {
  "ar": "تتعامل مع أي ملف يوصلك: تقرا وتكتب CSV وExcel من غير مشاكل encoding أو تواريخ، وتطلّع نص من PDF (حتى المصوّر)، وتعمل PDF من HTML، وتخزّن الملفات في Drive أو S3 أو FTP.",
  "en": "Handle any file you receive: read and write CSV and Excel without encoding or date problems, extract text from PDFs (even scanned ones), generate PDFs from HTML, and store files in Drive, S3 or FTP."
 },
 "days": [
  {
   "d": 1,
   "title": {
    "ar": "الملفات في n8n",
    "en": "Files in n8n"
   },
   "goal": {
    "ar": "تفهم إزاي n8n بيمسك الملفات، وتقرا وتكتب من الديسك.",
    "en": "Understand how n8n holds files, and read and write from disk."
   },
   "learn": [
    {
     "h": {
      "ar": "binary = ملف",
      "en": "Binary = a file"
     },
     "p": {
      "ar": "الملف في n8n بيبقى جوه الـ item تحت binary، وليه اسم (data غالبًا)، وfileName، وmimeType، وfileExtension، وحجم. الـ json بتاعه ممكن يكون فاضي.",
      "en": "In n8n a file lives on the item under binary, with a name (usually data), fileName, mimeType, fileExtension and size. Its json can be empty."
     },
     "ex": "binary.data: { fileName: \"sales.csv\", mimeType: \"text/csv\", fileSize: \"12 kB\" }"
    },
    {
     "h": {
      "ar": "الديسك",
      "en": "The disk"
     },
     "p": {
      "ar": "على n8n self-hosted: Read/Write Files from Disk بيقرا ويكتب ملفات على السيرفر. على n8n Cloud مفيش ديسك تكتب عليه؛ استخدم Drive أو S3.",
      "en": "On self-hosted n8n: Read/Write Files from Disk reads and writes files on the server. On n8n Cloud there's no disk to write to; use Drive or S3."
     },
     "ex": "Read Files from Disk: /data/inbox/*.csv"
    },
    {
     "h": {
      "ar": "الذاكرة",
      "en": "Memory"
     },
     "p": {
      "ar": "الملفات الكبيرة بتاكل الذاكرة. على السيرفر اضبط N8N_DEFAULT_BINARY_DATA_MODE=filesystem عشان الملفات تتخزن على الديسك مش في الذاكرة.",
      "en": "Large files eat memory. On a server set N8N_DEFAULT_BINARY_DATA_MODE=filesystem so files are stored on disk, not in memory."
     },
     "ex": "N8N_DEFAULT_BINARY_DATA_MODE=filesystem"
    }
   ],
   "practice": [
    {
     "ar": "نزّل ملف بـ HTTP Request (Response Format: File) وشوف الـ binary.",
     "en": "Download a file with HTTP Request (Response Format: File) and inspect the binary."
    },
    {
     "ar": "غيّر اسم الـ binary property من data لـ report وتعامل معاه.",
     "en": "Rename the binary property from data to report and work with it."
    },
    {
     "ar": "لو self-hosted: اقرا ملفات فولدر بـ Read Files from Disk.",
     "en": "If self-hosted: read a folder's files with Read Files from Disk."
    },
    {
     "ar": "اكتب ملف نص على الديسك واتأكد إنه اتعمل.",
     "en": "Write a text file to disk and confirm it exists."
    }
   ],
   "words": [
    {
     "t": "Read/Write Files from Disk",
     "m": {
      "ar": "node بتقرا وتكتب ملفات على السيرفر (self-hosted)",
      "en": "a node that reads and writes files on the server (self-hosted)"
     },
     "ex": "Write to /data/out/report.csv"
    },
    {
     "t": "MIME type",
     "m": {
      "ar": "نوع الملف الرسمي زي text/csv",
      "en": "a file's official type, such as text/csv"
     },
     "ex": "application/pdf"
    },
    {
     "t": "fileName",
     "m": {
      "ar": "اسم الملف جوه binary",
      "en": "the file name inside binary"
     },
     "ex": "sales-2026-09.csv"
    },
    {
     "t": "binary data mode",
     "m": {
      "ar": "مكان تخزين الملفات: ذاكرة أو ديسك",
      "en": "where files are stored: memory or disk"
     },
     "ex": "filesystem for large files"
    },
    {
     "t": "Response Format: File",
     "m": {
      "ar": "خيار HTTP Request ينزّل الرد كملف",
      "en": "an HTTP Request option that saves the response as a file"
     },
     "ex": "Download a PDF invoice."
    }
   ],
   "read": [
    {
     "t": "n8n Docs: Environment variables",
     "url": "https://docs.n8n.io/hosting/configuration/environment-variables/",
     "what": {
      "ar": "Deployment و Executions و Timezone. الباقي مرجع وقت الحاجة.",
      "en": "Deployment, Executions and Timezone. The rest is reference for when you need it."
     }
    },
    {
     "t": "n8n Docs: Data structure",
     "url": "https://docs.n8n.io/data/data-structure/",
     "what": {
      "ar": "الصفحة كلها (10 دقايق). قارن الأمثلة باللي بتشوفه في Output بتاعك.",
      "en": "The whole page (10 minutes). Compare the examples with what you see in your own output."
     }
    }
   ],
   "challenge": {
    "ar": "اعمل workflow بينزّل 3 ملفات مختلفة (CSV وPDF وصورة) من URLs، ويسميهم بتاريخ النهارده، ويبعتهم على Telegram.",
    "en": "Build a workflow that downloads 3 different files (a CSV, a PDF and an image) from URLs, names them with today's date, and sends them on Telegram."
   },
   "quiz": [
    {
     "q": {
      "ar": "الملف في الـ item بيبقى تحت:",
      "en": "A file on an item lives under:"
     },
     "o": [
      "binary",
      "json",
      "headers"
     ],
     "a": 0,
     "why": {
      "ar": "binary.data غالبًا.",
      "en": "Usually binary.data."
     }
    },
    {
     "q": {
      "ar": "على n8n Cloud تخزّن الملفات في:",
      "en": "On n8n Cloud store files in:"
     },
     "o": [
      {
       "ar": "Drive أو S3",
       "en": "Drive or S3"
      },
      {
       "ar": "الديسك",
       "en": "the disk"
      },
      {
       "ar": "الذاكرة للأبد",
       "en": "memory forever"
      }
     ],
     "a": 0,
     "why": {
      "ar": "مفيش ديسك.",
      "en": "There's no disk."
     }
    },
    {
     "q": {
      "ar": "ملفات كبيرة بتوقع السيرفر:",
      "en": "Large files crash the server:"
     },
     "o": [
      "binary data mode = filesystem",
      "more Wait",
      "smaller sheet"
     ],
     "a": 0,
     "why": {
      "ar": "على الديسك مش الذاكرة.",
      "en": "On disk, not in memory."
     }
    }
   ],
   "minutes": 120
  },
  {
   "d": 2,
   "title": {
    "ar": "CSV من غير مشاكل",
    "en": "CSV without trouble"
   },
   "goal": {
    "ar": "تقرا وتكتب CSV صح: الفاصل، والـ encoding، والعلامات، والأمان.",
    "en": "Read and write CSV correctly: delimiter, encoding, quotes and safety."
   },
   "learn": [
    {
     "h": {
      "ar": "الفاصل والـ encoding",
      "en": "Delimiter and encoding"
     },
     "p": {
      "ar": "Excel في بلاد كتير بيستخدم ; مش ,. والعربي محتاج UTF-8، وExcel بيفتحه صح لو فيه BOM. في Extract From File حدد الـ delimiter والـ encoding.",
      "en": "Excel in many countries uses ; instead of ,. Arabic needs UTF-8, and Excel opens it correctly only with a BOM. In Extract From File, set the delimiter and encoding."
     },
     "ex": "Convert to File (CSV) → Options: Include BOM (for Excel + Arabic)"
    },
    {
     "h": {
      "ar": "العلامات والفواصل جوه القيم",
      "en": "Quotes and commas inside values"
     },
     "p": {
      "ar": "قيمة فيها فاصلة لازم تبقى بين \"\": \"Cairo, Egypt\". والـ tools الجاهزة بتعمل ده لوحدها؛ متعملش CSV بـ join يدوي.",
      "en": "A value containing a comma must be in quotes: \"Cairo, Egypt\". The built-in tools do this; don't build CSV with a manual join."
     },
     "ex": "name,address\nAli,\"Cairo, Egypt\""
    },
    {
     "h": {
      "ar": "CSV injection",
      "en": "CSV injection"
     },
     "p": {
      "ar": "قيمة بتبدأ بـ = أو + أو - أو @ ممكن Excel ينفّذها كمعادلة. لو البيانات من مستخدمين، حط ' قبلها أو امنعها.",
      "en": "A value starting with =, +, - or @ may be executed by Excel as a formula. If the data comes from users, prefix it with ' or block it."
     },
     "ex": "=HYPERLINK(\"http://evil\") → '=HYPERLINK(…)"
    }
   ],
   "practice": [
    {
     "ar": "اقرا CSV بفاصل ; وCSV عربي UTF-8.",
     "en": "Read a CSV with ; as the delimiter and an Arabic UTF-8 CSV."
    },
    {
     "ar": "اكتب CSV فيه عربي وافتحه في Excel بـ BOM ومن غيره.",
     "en": "Write a CSV containing Arabic and open it in Excel with and without a BOM."
    },
    {
     "ar": "اكتب CSV فيه قيمة بفاصلة واتأكد إنه سليم.",
     "en": "Write a CSV with a value containing a comma and check it is valid."
    },
    {
     "ar": "اعمل خطوة بتحمي من CSV injection.",
     "en": "Add a step that protects against CSV injection."
    }
   ],
   "words": [
    {
     "t": "UTF-8 BOM",
     "m": {
      "ar": "علامة في أول الملف بتخلي Excel يقرا UTF-8 صح",
      "en": "a marker at the start of a file that makes Excel read UTF-8 correctly"
     },
     "ex": "Include BOM for Arabic CSVs."
    },
    {
     "t": "quoted field",
     "m": {
      "ar": "قيمة بين علامات تنصيص عشان فيها فاصلة",
      "en": "a value in quotes because it contains a comma"
     },
     "ex": "\"Cairo, Egypt\""
    },
    {
     "t": "CSV injection",
     "m": {
      "ar": "قيمة بتتنفّذ كمعادلة لما تتفتح في Excel",
      "en": "a value executed as a formula when opened in Excel"
     },
     "ex": "Values starting with ="
    },
    {
     "t": "delimiter (, ;)",
     "m": {
      "ar": "العلامة اللي بتفصل الأعمدة",
      "en": "the character that separates columns"
     },
     "ex": "European Excel uses ;"
    },
    {
     "t": "row count check",
     "m": {
      "ar": "تتأكد إن عدد الصفوف منطقي بعد القراءة",
      "en": "checking the number of rows makes sense after reading"
     },
     "ex": "Expected ~500, got 3 → alert"
    }
   ],
   "read": [
    {
     "t": "n8n Docs: Data transformation functions",
     "url": "https://docs.n8n.io/code/builtin/data-transformation-functions/",
     "what": {
      "ar": "Strings و Arrays الأول، والباقي مرجع.",
      "en": "Strings and Arrays first; the rest is reference."
     }
    },
    {
     "t": "Real Python",
     "url": "https://realpython.com/",
     "what": {
      "ar": "دوّر على «Reading and Writing CSV Files» واقرا الجزء عن الـ quoting.",
      "en": "Search for \"Reading and Writing CSV Files\" and read the quoting part."
     }
    }
   ],
   "challenge": {
    "ar": "اعمل «CSV importer» بيستقبل ملف من فورم، ويتأكد من الأعمدة المطلوبة وعدد الصفوف، ويرفض الملف لو فيه مشاكل برسالة واضحة، ويدخّل الصح في Postgres.",
    "en": "Build a \"CSV importer\" that takes a file from a form, checks required columns and the row count, rejects bad files with a clear message, and loads good ones into Postgres."
   },
   "quiz": [
    {
     "q": {
      "ar": "العربي في CSV باين علامات غريبة في Excel:",
      "en": "Arabic in a CSV looks garbled in Excel:"
     },
     "o": [
      "UTF-8 with BOM",
      "more commas",
      "a PDF"
     ],
     "a": 0,
     "why": {
      "ar": "Excel محتاج BOM.",
      "en": "Excel needs a BOM."
     }
    },
    {
     "q": {
      "ar": "قيمة \"Cairo, Egypt\" في CSV:",
      "en": "The value Cairo, Egypt in a CSV:"
     },
     "o": [
      {
       "ar": "لازم بين \"\"",
       "en": "must be quoted"
      },
      {
       "ar": "عادي من غير",
       "en": "is fine unquoted"
      },
      {
       "ar": "ممنوعة",
       "en": "is forbidden"
      }
     ],
     "a": 0,
     "why": {
      "ar": "فيها فاصلة.",
      "en": "It contains a comma."
     }
    },
    {
     "q": {
      "ar": "قيمة بتبدأ بـ = من مستخدم:",
      "en": "A user value starting with =:"
     },
     "o": [
      {
       "ar": "خطر CSV injection",
       "en": "a CSV injection risk"
      },
      {
       "ar": "عادي",
       "en": "fine"
      },
      {
       "ar": "أرقام",
       "en": "a number"
      }
     ],
     "a": 0,
     "why": {
      "ar": "معادلة.",
      "en": "A formula."
     }
    }
   ],
   "minutes": 120
  },
  {
   "d": 3,
   "title": {
    "ar": "Excel",
    "en": "Excel"
   },
   "goal": {
    "ar": "تقرا وتكتب XLSX: الـ sheets، والتواريخ، والأعمدة.",
    "en": "Read and write XLSX: sheets, dates and columns."
   },
   "learn": [
    {
     "h": {
      "ar": "قراءة XLSX",
      "en": "Reading XLSX"
     },
     "p": {
      "ar": "Extract From File ← XLSX: اختار اسم الـ sheet، وهل أول صف عناوين، والـ range لو محتاج جزء. وكل صف بيبقى item.",
      "en": "Extract From File → XLSX: choose the sheet name, whether the first row is headers, and a range if you need part of it. Each row becomes an item."
     },
     "ex": "Sheet: \"Sales 2026\"   Range: A1:F500   Header row: on"
    },
    {
     "h": {
      "ar": "التواريخ في Excel",
      "en": "Dates in Excel"
     },
     "p": {
      "ar": "Excel بيخزن التاريخ كرقم (عدد الأيام من 1900): 45930 مثلًا. حوّله: `DateTime.fromObject({year:1899,month:12,day:30}).plus({days: n})`، أو فعّل خيار قراءة التواريخ لو موجود.",
      "en": "Excel stores a date as a number (days since 1900), e.g. 45930. Convert it: `DateTime.fromObject({year:1899,month:12,day:30}).plus({days: n})`, or enable the read-dates option when available."
     },
     "ex": "45930 → 2025-09-30"
    },
    {
     "h": {
      "ar": "كتابة XLSX",
      "en": "Writing XLSX"
     },
     "p": {
      "ar": "Convert to File ← XLSX بيعمل ملف من الـ items، واسم الـ sheet تختاره. للتنسيق المتقدم (ألوان، معادلات) استخدم Microsoft Excel 365 node أو Google Sheets.",
      "en": "Convert to File → XLSX builds a file from the items, with a sheet name you choose. For advanced formatting (colours, formulas) use the Microsoft Excel 365 node or Google Sheets."
     },
     "ex": "Items → Convert to File (XLSX, sheet \"Report\") → Gmail attachment"
    }
   ],
   "practice": [
    {
     "ar": "اقرا Excel فيه 2 sheets واختار واحدة.",
     "en": "Read an Excel file with 2 sheets and choose one."
    },
    {
     "ar": "حوّل تواريخ Excel الرقمية لتواريخ ISO.",
     "en": "Convert Excel number dates into ISO dates."
    },
    {
     "ar": "اكتب تقرير XLSX وابعته بالإيميل.",
     "en": "Write an XLSX report and send it by email."
    },
    {
     "ar": "قارن Excel file بـ Google Sheets لنفس التقرير.",
     "en": "Compare an Excel file with Google Sheets for the same report."
    }
   ],
   "words": [
    {
     "t": "XLSX",
     "m": {
      "ar": "صيغة ملفات Excel الحديثة",
      "en": "the modern Excel file format"
     },
     "ex": "report.xlsx"
    },
    {
     "t": "sheet name (Excel)",
     "m": {
      "ar": "اسم التبويب جوه ملف Excel",
      "en": "the name of a tab inside an Excel file"
     },
     "ex": "Sheet: \"Sales 2026\""
    },
    {
     "t": "Excel date serial",
     "m": {
      "ar": "رقم Excel بيمثل تاريخ (أيام من 1900)",
      "en": "Excel's number for a date (days since 1900)"
     },
     "ex": "45930"
    },
    {
     "t": "range (A1:F500)",
     "m": {
      "ar": "جزء من الجدول بتحدده بالخانات",
      "en": "a part of the sheet defined by cells"
     },
     "ex": "A1:F500"
    },
    {
     "t": "Microsoft Excel 365 node",
     "m": {
      "ar": "node بتشتغل على ملفات Excel أونلاين",
      "en": "a node that works with online Excel files"
     },
     "ex": "Append rows to a OneDrive workbook."
    }
   ],
   "read": [
    {
     "t": {
      "ar": "n8n Docs: Luxon (التواريخ)",
      "en": "n8n Docs: Luxon (dates)"
     },
     "url": "https://docs.n8n.io/code/cookbook/luxon/",
     "what": {
      "ar": "الصفحة كلها، وجرّب كل مثال في Edit Fields.",
      "en": "The whole page, and try every example in Edit Fields."
     }
    }
   ],
   "challenge": {
    "ar": "اعمل «Excel to database»: كل يوم ملف Excel بيوصل على الإيميل، يتقري، التواريخ تتصلّح، البيانات تتحقق وتدخل Postgres، وملخص بالأعداد.",
    "en": "Build \"Excel to database\": each day an Excel file arrives by email; it is read, dates fixed, data validated and loaded into Postgres, with a summary of counts."
   },
   "quiz": [
    {
     "q": {
      "ar": "تاريخ طلع 45930:",
      "en": "A date came out as 45930:"
     },
     "o": [
      {
       "ar": "رقم Excel التسلسلي، حوّله",
       "en": "an Excel serial; convert it"
      },
      {
       "ar": "صح كده",
       "en": "correct as is"
      },
      {
       "ar": "خطأ",
       "en": "an error"
      }
     ],
     "a": 0,
     "why": {
      "ar": "أيام من 1900.",
      "en": "Days since 1900."
     }
    },
    {
     "q": {
      "ar": "تقرا sheet معينة من XLSX:",
      "en": "Read a specific sheet from XLSX:"
     },
     "o": [
      {
       "ar": "تحدد sheet name",
       "en": "set the sheet name"
      },
      {
       "ar": "مستحيل",
       "en": "impossible"
      },
      {
       "ar": "Code بس",
       "en": "only with Code"
      }
     ],
     "a": 0,
     "why": {
      "ar": "خيار في Extract From File.",
      "en": "An option in Extract From File."
     }
    },
    {
     "q": {
      "ar": "تقرير XLSX من items:",
      "en": "An XLSX report from items:"
     },
     "o": [
      "Convert to File (XLSX)",
      "Extract From File",
      "Wait"
     ],
     "a": 0,
     "why": {
      "ar": "تحويل لملف.",
      "en": "Convert to a file."
     }
    }
   ],
   "minutes": 120
  },
  {
   "d": 4,
   "title": {
    "ar": "PDF",
    "en": "PDF"
   },
   "goal": {
    "ar": "تطلّع نص من PDF، وتعرف تتعامل مع المصوّر، وتعمل PDF من HTML.",
    "en": "Extract text from PDFs, handle scanned ones, and generate PDFs from HTML."
   },
   "learn": [
    {
     "h": {
      "ar": "النص من PDF",
      "en": "Text from a PDF"
     },
     "p": {
      "ar": "Extract From File ← PDF بيطلّع النص لو الـ PDF فيه text layer (اتعمل من برنامج). وبعدين regex أو AI يطلّع الحقول.",
      "en": "Extract From File → PDF pulls out the text if the PDF has a text layer (made by software). Then regex or AI extracts the fields."
     },
     "ex": "PDF → text → /Total:\\s*([\\d,.]+)/ → amount"
    },
    {
     "h": {
      "ar": "PDF مصوّر",
      "en": "Scanned PDFs"
     },
     "p": {
      "ar": "لو الـ PDF صورة (scan)، النص هيطلع فاضي. محتاج OCR: خدمة OCR أو موديل AI بيقرا الصور. اتأكد: لو النص فاضي أو قليل جدًا، ودّيه لـ OCR.",
      "en": "If the PDF is an image (a scan), the text comes out empty. You need OCR: an OCR service or an AI model that reads images. Check: if the text is empty or very short, send it to OCR."
     },
     "ex": "IF text.length < 50 → OCR branch"
    },
    {
     "h": {
      "ar": "عمل PDF",
      "en": "Making PDFs"
     },
     "p": {
      "ar": "أسهل طريقة: تعمل HTML (فاتورة مثلًا) وتبعته لخدمة HTML→PDF (زي Gotenberg اللي تشغّلها في Docker، أو API خارجي). وترجع ملف PDF تبعته.",
      "en": "The easiest way: build HTML (an invoice, say) and send it to an HTML→PDF service (such as Gotenberg running in Docker, or an external API). You get back a PDF file to send."
     },
     "ex": "HTML (invoice) → HTTP Request (Gotenberg, form-data) → PDF → Gmail"
    }
   ],
   "practice": [
    {
     "ar": "طلّع نص من PDF فاتورة واستخرج الإجمالي بـ regex.",
     "en": "Extract text from an invoice PDF and pull the total with regex."
    },
    {
     "ar": "جرّب PDF مصوّر وشوف النص فاضي.",
     "en": "Try a scanned PDF and see the empty text."
    },
    {
     "ar": "اعمل IF بيوجّه الـ PDFs المصوّرة لفرع OCR.",
     "en": "Add an IF that routes scanned PDFs to an OCR branch."
    },
    {
     "ar": "اعمل فاتورة HTML وحوّلها PDF (بخدمة أو Gotenberg).",
     "en": "Build an HTML invoice and turn it into a PDF (with a service or Gotenberg)."
    }
   ],
   "words": [
    {
     "t": "text layer",
     "m": {
      "ar": "النص الحقيقي جوه PDF اللي ينفع يتنسخ",
      "en": "the real, copyable text inside a PDF"
     },
     "ex": "Scans have no text layer."
    },
    {
     "t": "OCR",
     "m": {
      "ar": "قراءة النص من صورة",
      "en": "reading text from an image"
     },
     "ex": "Send scans to an OCR service."
    },
    {
     "t": "HTML to PDF",
     "m": {
      "ar": "تحويل صفحة HTML لملف PDF",
      "en": "turning an HTML page into a PDF file"
     },
     "ex": "Invoices, reports"
    },
    {
     "t": "Gotenberg",
     "m": {
      "ar": "خدمة مفتوحة المصدر بتحوّل HTML ومستندات لـ PDF",
      "en": "an open-source service that converts HTML and documents to PDF"
     },
     "ex": "Run it with Docker."
    },
    {
     "t": "scanned document",
     "m": {
      "ar": "مستند متصوّر كصورة مش نص",
      "en": "a document captured as an image, not text"
     },
     "ex": "Needs OCR."
    }
   ],
   "read": [
    {
     "t": "Gotenberg",
     "url": "https://gotenberg.dev/",
     "what": {
      "ar": "اقرا صفحة Chromium module (HTML → PDF).",
      "en": "Read the Chromium module page (HTML → PDF)."
     }
    },
    {
     "t": "n8n Docs: Data transformation functions",
     "url": "https://docs.n8n.io/code/builtin/data-transformation-functions/",
     "what": {
      "ar": "Strings و Arrays الأول، والباقي مرجع.",
      "en": "Strings and Arrays first; the rest is reference."
     }
    }
   ],
   "challenge": {
    "ar": "اعمل «invoice generator»: order من Postgres ← فاتورة HTML بتصميم بسيط ← PDF ← إيميل للعميل ← نسخة في Drive.",
    "en": "Build an \"invoice generator\": an order from Postgres → a simple HTML invoice → PDF → email to the customer → a copy in Drive."
   },
   "quiz": [
    {
     "q": {
      "ar": "PDF مصوّر نصه طلع فاضي:",
      "en": "A scanned PDF's text is empty:"
     },
     "o": [
      "OCR",
      "more regex",
      "Convert to File"
     ],
     "a": 0,
     "why": {
      "ar": "مفيش text layer.",
      "en": "No text layer."
     }
    },
    {
     "q": {
      "ar": "أسهل طريقة تعمل فاتورة PDF:",
      "en": "The easiest way to make a PDF invoice:"
     },
     "o": [
      {
       "ar": "HTML ← خدمة HTML→PDF",
       "en": "HTML → an HTML-to-PDF service"
      },
      {
       "ar": "ترسمها باليد",
       "en": "draw it by hand"
      },
      {
       "ar": "CSV",
       "en": "CSV"
      }
     ],
     "a": 0,
     "why": {
      "ar": "HTML مرن.",
      "en": "HTML is flexible."
     }
    },
    {
     "q": {
      "ar": "تطلّع الإجمالي من نص الفاتورة:",
      "en": "Pull the total from invoice text:"
     },
     "o": [
      "regex or AI",
      "Wait",
      "Merge"
     ],
     "a": 0,
     "why": {
      "ar": "استخراج.",
      "en": "Extraction."
     }
    }
   ],
   "minutes": 120
  },
  {
   "d": 5,
   "title": {
    "ar": "التخزين السحابي",
    "en": "Cloud storage"
   },
   "goal": {
    "ar": "ترفع وتنزّل وتنظّم ملفات في Google Drive وS3 وFTP.",
    "en": "Upload, download and organise files in Google Drive, S3 and FTP."
   },
   "learn": [
    {
     "h": {
      "ar": "Google Drive",
      "en": "Google Drive"
     },
     "p": {
      "ar": "Google Drive node: Upload وDownload وSearch وCreate Folder وShare. كل فولدر ليه ID في اللينك. نظّم بفولدرات بالسنة/الشهر.",
      "en": "The Google Drive node: Upload, Download, Search, Create Folder and Share. Each folder has an ID in its URL. Organise by year/month folders."
     },
     "ex": "Invoices/2026/09/INV-1042.pdf"
    },
    {
     "h": {
      "ar": "S3 وobject storage",
      "en": "S3 and object storage"
     },
     "p": {
      "ar": "S3 (أو أي خدمة متوافقة زي R2 وMinIO) بتخزن ملفات بـ bucket وkey. رخيصة وكويسة للأرشيف والنسخ. والـ presigned URL لينك مؤقت لملف خاص.",
      "en": "S3 (or any compatible service such as R2 or MinIO) stores files by bucket and key. Cheap and good for archives and backups. A presigned URL is a temporary link to a private file."
     },
     "ex": "bucket: my-backups   key: n8n/2026-09-28.sql"
    },
    {
     "h": {
      "ar": "FTP وSFTP",
      "en": "FTP and SFTP"
     },
     "p": {
      "ar": "شركات كتير لسه بتبعت ملفات على FTP. استخدم SFTP (مشفّر) لو متاح. n8n عنده FTP node بيعمل List وDownload وUpload.",
      "en": "Many companies still exchange files over FTP. Use SFTP (encrypted) when available. n8n's FTP node can List, Download and Upload."
     },
     "ex": "Every hour: SFTP list /outbox → download new → process → move to /done"
    }
   ],
   "practice": [
    {
     "ar": "ارفع ملف على Drive في فولدر بالتاريخ.",
     "en": "Upload a file to Drive into a date-based folder."
    },
    {
     "ar": "دوّر على ملفات في Drive بالاسم ونزّلها.",
     "en": "Search Drive for files by name and download them."
    },
    {
     "ar": "لو عندك S3/R2: ارفع ملف واعمل presigned URL.",
     "en": "If you have S3/R2: upload a file and create a presigned URL."
    },
    {
     "ar": "اعمل مسار «inbox → processed» للملفات بحيث متتعالجش مرتين.",
     "en": "Build an \"inbox → processed\" flow for files so none is processed twice."
    }
   ],
   "words": [
    {
     "t": "Google Drive node",
     "m": {
      "ar": "node لرفع وتنزيل وتنظيم ملفات Drive",
      "en": "a node to upload, download and organise Drive files"
     },
     "ex": "Upload to folder \"Invoices\""
    },
    {
     "t": "folder ID",
     "m": {
      "ar": "الكود اللي بيحدد فولدر في Drive",
      "en": "the code identifying a Drive folder"
     },
     "ex": "drive.google.com/drive/folders/<ID>"
    },
    {
     "t": "S3 bucket",
     "m": {
      "ar": "حاوية ملفات في object storage",
      "en": "a container for files in object storage"
     },
     "ex": "my-backups"
    },
    {
     "t": "presigned URL",
     "m": {
      "ar": "لينك مؤقت لملف خاص",
      "en": "a temporary link to a private file"
     },
     "ex": "Valid for 1 hour."
    },
    {
     "t": "SFTP",
     "m": {
      "ar": "نقل ملفات مشفّر عن طريق SSH",
      "en": "encrypted file transfer over SSH"
     },
     "ex": "Prefer SFTP to plain FTP."
    }
   ],
   "read": [
    {
     "t": "n8n Docs: Credentials",
     "url": "https://docs.n8n.io/credentials/",
     "what": {
      "ar": "اقرا صفحات Google Drive وS3 وFTP credentials.",
      "en": "Read the Google Drive, S3 and FTP credential pages."
     }
    }
   ],
   "challenge": {
    "ar": "اعمل «document archive»: أي مرفق PDF على label معيّن يتحفظ في Drive (سنة/شهر) باسم منظم، ونسخة في S3 لو متاح، وسجل في Postgres فيه اللينك.",
    "en": "Build a \"document archive\": every PDF attachment with a given label is saved in Drive (year/month) with an orderly name, copied to S3 if available, and logged in Postgres with its link."
   },
   "quiz": [
    {
     "q": {
      "ar": "لينك مؤقت لملف خاص في S3:",
      "en": "A temporary link to a private S3 file:"
     },
     "o": [
      "presigned URL",
      "public bucket",
      "FTP"
     ],
     "a": 0,
     "why": {
      "ar": "بينتهي.",
      "en": "It expires."
     }
    },
    {
     "q": {
      "ar": "بدل FTP العادي:",
      "en": "Instead of plain FTP:"
     },
     "o": [
      "SFTP",
      "HTTP",
      "Telegram"
     ],
     "a": 0,
     "why": {
      "ar": "مشفّر.",
      "en": "Encrypted."
     }
    },
    {
     "q": {
      "ar": "عشان ملف متتعالجش مرتين:",
      "en": "So a file isn't processed twice:"
     },
     "o": [
      {
       "ar": "انقله لفولدر processed",
       "en": "move it to a processed folder"
      },
      {
       "ar": "اقراه تاني",
       "en": "read it again"
      },
      {
       "ar": "Wait",
       "en": "Wait"
      }
     ],
     "a": 0,
     "why": {
      "ar": "inbox → processed.",
      "en": "inbox → processed."
     }
    }
   ],
   "minutes": 120
  },
  {
   "d": 6,
   "title": {
    "ar": "مراجعة الأسبوع والاختبار",
    "en": "Week review and test"
   },
   "goal": {
    "ar": "راجع الخمس أيام، وسلّم مشروع الأسبوع، وخد الاختبار الأسبوعي. الأسبوع 15 بيفتح لما تجيب 70% أو أكتر.",
    "en": "Review the five days, hand in the weekly project, and take the weekly test. Week 15 opens when you score 70% or more."
   },
   "review": [
    {
     "ar": "binary وfileName وmimeType، والديسك، وfilesystem mode.",
     "en": "binary, fileName and mimeType, the disk, and filesystem mode."
    },
    {
     "ar": "CSV: delimiter، UTF-8 BOM، quoted fields، CSV injection.",
     "en": "CSV: delimiter, UTF-8 BOM, quoted fields, CSV injection."
    },
    {
     "ar": "Excel: sheet name، range، تواريخ Excel.",
     "en": "Excel: sheet name, range, Excel dates."
    },
    {
     "ar": "PDF: text layer، OCR، HTML→PDF.",
     "en": "PDF: text layer, OCR, HTML→PDF."
    },
    {
     "ar": "Drive وS3 وSFTP وinbox → processed.",
     "en": "Drive, S3, SFTP and inbox → processed."
    }
   ],
   "project": {
    "ar": "ابني «document processing pipeline»: ملفات (CSV وExcel وPDF) بتوصل على الإيميل أو فولدر Drive، كل نوع يتقري صح (encoding، تواريخ، OCR للمصوّر)، البيانات تتحقق وتدخل Postgres، الملف الأصلي يتأرشف بـ اسم منظم، وتقرير يومي XLSX يتبعت بالإيميل.",
    "en": "Build a \"document processing pipeline\": files (CSV, Excel and PDF) arrive by email or in a Drive folder; each type is read correctly (encoding, dates, OCR for scans); data is validated and loaded into Postgres; the original is archived with an orderly name; and a daily XLSX report is emailed."
   },
   "test": [
    {
     "q": {
      "ar": "اسم الـ binary property الافتراضي غالبًا:",
      "en": "The default binary property name is usually:"
     },
     "o": [
      "data",
      "file0",
      "binary"
     ],
     "a": 0,
     "why": {
      "ar": "binary.data.",
      "en": "binary.data."
     }
    },
    {
     "q": {
      "ar": "ملفات كبيرة على السيرفر:",
      "en": "Large files on a server:"
     },
     "o": [
      "N8N_DEFAULT_BINARY_DATA_MODE=filesystem",
      "GENERIC_TIMEZONE",
      "WEBHOOK_URL"
     ],
     "a": 0,
     "why": {
      "ar": "الديسك.",
      "en": "The disk."
     }
    },
    {
     "q": {
      "ar": "CSV أوروبي أعمدته متلزقة:",
      "en": "A European CSV's columns are stuck together:"
     },
     "o": [
      {
       "ar": "غيّر الـ delimiter لـ ;",
       "en": "set the delimiter to ;"
      },
      {
       "ar": "امسح الملف",
       "en": "delete the file"
      },
      {
       "ar": "PDF",
       "en": "use PDF"
      }
     ],
     "a": 0,
     "why": {
      "ar": "فاصل مختلف.",
      "en": "A different separator."
     }
    },
    {
     "q": {
      "ar": "عربي مكسّر في Excel:",
      "en": "Broken Arabic in Excel:"
     },
     "o": [
      "UTF-8 BOM",
      "more columns",
      "XML"
     ],
     "a": 0,
     "why": {
      "ar": "Excel.",
      "en": "Excel."
     }
    },
    {
     "q": {
      "ar": "CSV injection بتبدأ بـ:",
      "en": "CSV injection starts with:"
     },
     "o": [
      "= + - @",
      "a letter",
      "a space"
     ],
     "a": 0,
     "why": {
      "ar": "معادلة.",
      "en": "A formula."
     }
    },
    {
     "q": {
      "ar": "Excel date serial هو:",
      "en": "An Excel date serial is:"
     },
     "o": [
      {
       "ar": "رقم أيام من 1900",
       "en": "a count of days since 1900"
      },
      {
       "ar": "نص",
       "en": "text"
      },
      {
       "ar": "خطأ",
       "en": "an error"
      }
     ],
     "a": 0,
     "why": {
      "ar": "حوّله.",
      "en": "Convert it."
     }
    },
    {
     "q": {
      "ar": "تقرأ جزء A1:F500 من Excel:",
      "en": "Read part A1:F500 of an Excel file:"
     },
     "o": [
      "range",
      "delimiter",
      "BOM"
     ],
     "a": 0,
     "why": {
      "ar": "نطاق.",
      "en": "A range."
     }
    },
    {
     "q": {
      "ar": "نص PDF فاضي:",
      "en": "Empty PDF text:"
     },
     "o": [
      {
       "ar": "غالبًا مصوّر ← OCR",
       "en": "probably a scan → OCR"
      },
      {
       "ar": "الـ PDF سليم",
       "en": "the PDF is fine"
      },
      {
       "ar": "امسحه",
       "en": "delete it"
      }
     ],
     "a": 0,
     "why": {
      "ar": "مفيش text layer.",
      "en": "No text layer."
     }
    },
    {
     "q": {
      "ar": "Gotenberg بيعمل:",
      "en": "Gotenberg:"
     },
     "o": [
      {
       "ar": "HTML → PDF",
       "en": "HTML → PDF"
      },
      {
       "ar": "OCR بس",
       "en": "only OCR"
      },
      {
       "ar": "إيميل",
       "en": "email"
      }
     ],
     "a": 0,
     "why": {
      "ar": "تحويل مستندات.",
      "en": "Document conversion."
     }
    },
    {
     "q": {
      "ar": "folder ID في Drive موجود في:",
      "en": "A Drive folder ID is in:"
     },
     "o": [
      {
       "ar": "لينك الفولدر",
       "en": "the folder URL"
      },
      {
       "ar": "اسم الفولدر",
       "en": "the folder name"
      },
      {
       "ar": "الـ credential",
       "en": "the credential"
      }
     ],
     "a": 0,
     "why": {
      "ar": "بعد folders/.",
      "en": "After folders/."
     }
    },
    {
     "q": {
      "ar": "presigned URL:",
      "en": "A presigned URL:"
     },
     "o": [
      {
       "ar": "لينك مؤقت لملف خاص",
       "en": "a temporary link to a private file"
      },
      {
       "ar": "باسورد",
       "en": "a password"
      },
      {
       "ar": "bucket عام",
       "en": "a public bucket"
      }
     ],
     "a": 0,
     "why": {
      "ar": "بينتهي.",
      "en": "It expires."
     }
    },
    {
     "q": {
      "ar": "على n8n Cloud مفيش:",
      "en": "On n8n Cloud there is no:"
     },
     "o": [
      {
       "ar": "ديسك تكتب عليه ملفات",
       "en": "disk to write files to"
      },
      {
       "ar": "Webhook",
       "en": "Webhook"
      },
      {
       "ar": "Code",
       "en": "Code"
      }
     ],
     "a": 0,
     "why": {
      "ar": "استخدم Drive/S3.",
      "en": "Use Drive/S3."
     }
    }
   ],
   "minutes": 120
  }
 ]
});
