// English week 1 — the intensive hour (weeks 1–12 are 3 hours a day): pronunciation, listening, speaking and
// writing drills on the day's topic. Merged into the week by tools/build_weeks.js.
const B = (ar, en) => ({ ar, en });
const L = (h, p, ex) => ({ h, p, ex });
const W = (t, ar, en, ex) => ({ t, m: B(ar, en), ex });
const Q = (q, o, a, why) => ({ q, o, a, why });
module.exports = { days: [
  { learn: [L(B('نطق كلمات الأخطاء', 'Saying error words'),
      B('هتقول الكلمات دي في كل مكالمة دعم. النبر (الجزء الأعلى صوتًا) بالحروف الكبيرة: ex**CEP**tion، **TRACE**back، **SYN**tax، at**TRIB**ute، inden**TA**tion، **VAL**ue. والـ e في آخر كلمات زي **value** و**type** مش بتتنطق. قول كل كلمة 3 مرات بصوت عالي.',
        'You will say these words in every support call. The stress (the loudest part) is in capitals: ex**CEP**tion, **TRACE**back, **SYN**tax, at**TRIB**ute, inden**TA**tion, **VAL**ue. The final e in words like **value** and **type** is silent. Say each word 3 times aloud.'),
      'exCEPtion · TRACEback · SYNtax · atTRIButeError · indenTAtion\n"I got a KEY error on LINE twelve."')],
    practice: [B('سجّل صوتك وانت بتقرا 3 رسايل خطأ كاملة، واسمعها وقارنها بنطق قاموس Cambridge.', 'Record yourself reading 3 full error messages, then compare with the pronunciation in the Cambridge dictionary.'),
      B('اشرح خطأ واحد بصوت عالي في 3 جمل: إيه الخطأ، في أنهي سطر، وإيه السبب.', 'Explain one error aloud in 3 sentences: what the error is, on which line, and what caused it.')],
    words: [W('word stress', 'الجزء من الكلمة اللي بيتقال أعلى وأطول', 'the part of a word said louder and longer', 'The word stress in exception is on CEP.'),
      W('silent letter', 'حرف مكتوب ومش بيتنطق', 'a letter that is written but not pronounced', 'The e in type is a silent letter.')],
    quiz: [Q(B('النبر في كلمة exception على:', 'The stress in exception is on:'), ['ex', 'cep', 'tion'], 1, B('ex-CEP-tion.', 'ex-CEP-tion.'))] },
  { learn: [L(B('Skimming وscanning في التوثيق', 'Skimming and scanning docs'),
      B('مش لازم تقرا صفحة التوثيق كلها. **Skimming**: تمر بسرعة على العناوين وأول سطر في كل فقرة عشان تعرف الصفحة عن إيه (دقيقة). **Scanning**: تدوّر على حاجة محددة (اسم parameter، رقم) بعينك أو بـ Ctrl+F. اعمل skim الأول، وبعدين scan للي محتاجه، وبعدين اقرا الجزء ده بس بالتفصيل.',
        'You do not need to read a whole docs page. **Skimming**: quickly go over the headings and the first line of each paragraph to know what the page is about (one minute). **Scanning**: look for one specific thing (a parameter name, a number) with your eyes or Ctrl+F. Skim first, then scan for what you need, then read only that part closely.'),
      '1. Skim (60 s): headings → "Authentication", "Rate limits", "Errors"\n2. Scan: Ctrl+F "limit" → "100 requests per minute"\n3. Read closely: just the Rate limits section')],
    practice: [B('افتح صفحة توثيق جديدة عليك، اعمل skim دقيقة واحدة، واكتب في 2 جمل الصفحة عن إيه.', 'Open a docs page new to you, skim it for one minute, and write in 2 sentences what it is about.'),
      B('اعمل scan لـ 3 معلومات محددة (حد الطلبات، نوع المصادقة، مثال طلب) وقيس وقتك.', 'Scan for 3 specific facts (the rate limit, the auth type, a request example) and time yourself.')],
    words: [W('skim', 'تقرا بسرعة عشان تعرف الفكرة العامة', 'to read quickly to get the general idea', 'Skim the page before you read it closely.'),
      W('scan', 'تدوّر بعينك على معلومة محددة', 'to look quickly for one specific piece of information', 'Scan the table for the error code.')],
    quiz: [Q(B('عايز تعرف رقم حد الطلبات بس. تعمل:', 'You only need the rate limit number. You:'), ['scan', 'skim', 'read every word'], 0, B('بتدوّر على معلومة محددة.', 'You look for one specific fact.'))] },
  { learn: [L(B('قراءة الرموز بصوت عالي', 'Reading symbols aloud'),
      B('في مكالمة أو pair programming هتحتاج تقول الكود: `_` underscore، `-` hyphen أو dash، `()` parentheses، `[]` square brackets، `{}` curly braces، `.` dot، `/` slash، `\\` backslash، `=` equals، `==` double equals، `!` exclamation mark (أو bang)، `#` hash.',
        'In a call or pair programming you will need to say code aloud: `_` underscore, `-` hyphen or dash, `()` parentheses, `[]` square brackets, `{}` curly braces, `.` dot, `/` slash, `\\` backslash, `=` equals, `==` double equals, `!` exclamation mark (or bang), `#` hash.'),
      'user_id      → "user underscore id"\ndata["name"] → "data, square bracket, quote, name, quote, close bracket"\napi/v2/users → "api slash v two slash users"')],
    practice: [B('اقرا بصوت عالي 5 أسطر كود من مشروعك، كل رمز باسمه.', 'Read 5 lines of code from your project aloud, naming every symbol.'),
      B('املي على صاحبك (أو سجّل لنفسك) رابط API طويل، وخلّيه يكتبه من صوتك بس.', 'Dictate a long API URL to a friend (or record it), and have them write it from your voice only.')],
    words: [W('underscore', 'الشرطة السفلية _', 'the low line character _', 'Snake case uses an underscore between words.'),
      W('curly braces', 'الأقواس { }', 'the { } characters', 'A JSON object is inside curly braces.')],
    quiz: [Q(B('`[]` اسمها:', '`[]` are called:'), ['square brackets', 'curly braces', 'parentheses'], 0, B('الـ {} curly، والـ () parentheses.', '{} are curly braces; () are parentheses.'))] },
  { learn: [L(B('صيغة الأمر في الكتابة التقنية', 'The imperative in technical writing'),
      B('الـ commit messages والخطوات في الـ README بتتكتب بصيغة **الأمر**: فعل في الأول من غير to ومن غير فاعل: `Add login form`، `Fix date bug`، `Run npm install`. مش `Added` ولا `Adding` ولا `I added`. اختبار سهل: الجملة لازم تكمّل «If applied, this commit will …».',
        'Commit messages and README steps use the **imperative**: a verb first, with no to and no subject: `Add login form`, `Fix date bug`, `Run npm install`. Not `Added`, `Adding` or `I added`. An easy test: the sentence must complete «If applied, this commit will …».'),
      '✗ Added validation to the form\n✗ Adding validation\n✓ Add validation to the signup form\n"If applied, this commit will add validation to the signup form." ✓')],
    practice: [B('حوّل آخر 10 commits ليك لصيغة الأمر.', 'Rewrite your last 10 commit messages in the imperative.'),
      B('اكتب 6 خطوات تثبيت لمشروع بصيغة الأمر (Install، Copy، Set، Run…).', 'Write 6 install steps for a project in the imperative (Install, Copy, Set, Run…).')],
    words: [W('imperative mood', 'صيغة الأمر: فعل في الأول من غير فاعل', 'the command form: a verb first with no subject', 'Write commit messages in the imperative mood.'),
      W('paraphrase', 'تقول نفس المعنى بكلام تاني', 'to say the same meaning in other words', 'Paraphrase the error for the client.')],
    quiz: [Q(B('أحسن commit message:', 'The best commit message:'), ['Fix timezone bug in reminders', 'Fixed the bug', 'Fixing stuff'], 0, B('أمر + تفاصيل.', 'Imperative + detail.'))] },
  { learn: [L(B('طلبات مهذبة بدرجات', 'Polite requests by degree'),
      B('الطلب كل ما يبقى أكبر أو الشخص أبعد، الصيغة بتبقى أطول وألطف: `Can you send the file?` (زميل) ← `Could you send the file?` ← `Would you mind sending the file?` (بعدها -ing) ← `I was wondering if you could send the file.` (عميل جديد أو طلب كبير). وزوّد `please` و`when you get a chance`.',
        'The bigger the request or the more distant the person, the longer and softer the form: `Can you send the file?` (a colleague) → `Could you send the file?` → `Would you mind sending the file?` (-ing after it) → `I was wondering if you could send the file.` (a new client or a big ask). Add `please` and `when you get a chance`.'),
      'Can you check this?                       (teammate)\nCould you check this when you get a chance? (manager)\nWould you mind checking the access rights?  (client)\nI was wondering if you could extend the deadline. (big ask)')],
    practice: [B('اكتب نفس الطلب (تمديد الميعاد) بالـ 4 درجات.', 'Write the same request (extending a deadline) at the 4 levels.'),
      B('قول كل واحدة بصوت عالي بنبرة نازلة في الآخر (مش سؤال حاد).', 'Say each aloud with a falling tone at the end (not a sharp question).')],
    words: [W('polite request', 'طلب بصيغة مهذبة', 'a request made in a courteous way', 'Would you mind… is a polite request.'),
      W('touch base', 'تتواصل بسرعة عشان تطمن على حاجة', 'to make brief contact to check on something', 'Let’s touch base on Thursday.')],
    quiz: [Q(B('بعد `Would you mind` الفعل:', 'After `Would you mind` the verb is:'), ['sending', 'send', 'to send'], 0, B('mind + -ing.', 'mind + -ing.'))] },
  { review: [B('⚡ نطق كلمات الأخطاء، وskimming وscanning، وأسماء الرموز.', '⚡ Saying error words, skimming and scanning, and the names of symbols.'),
      B('⚡ صيغة الأمر في الـ commits، والطلبات المهذبة بدرجاتها: سجّل نفسك وانت بتشرح خطأ وتطلب مساعدة.', '⚡ The imperative in commits, and polite requests by degree: record yourself explaining an error and asking for help.')] }
] };
