// English week 2 — the intensive hour (weeks 1–12 are 3 hours a day): pronunciation, listening, speaking and
// writing drills on the day's topic. Merged into the week by tools/build_weeks.js.
const B = (ar, en) => ({ ar, en });
const L = (h, p, ex) => ({ h, p, ex });
const W = (t, ar, en, ex) => ({ t, m: B(ar, en), ex });
const Q = (q, o, a, why) => ({ q, o, a, why });
module.exports = { days: [
  { learn: [L(B('نبر الجملة', 'Sentence stress'),
      B('في الإنجليزي مش كل الكلمات بتتقال بنفس القوة. **كلمات المحتوى** (أسماء، أفعال، صفات، أرقام) بتتقال أعلى وأوضح، و**كلمات الربط** (a، the، to، of، is) بتتقال بسرعة وخفيف. لو قلت كل كلمة بنفس القوة، كلامك هيبان آلي وصعب يتفهم.',
        'In English not every word gets the same force. **Content words** (nouns, verbs, adjectives, numbers) are louder and clearer, and **function words** (a, the, to, of, is) are quick and light. If you give every word the same force, you sound robotic and are harder to follow.'),
      'The SCRIPT SENDS an EMAIL to the CLIENT every MORNING.\nI NEED to UPDATE the DATABASE beFORE the DEMO.')],
    practice: [B('علّم كلمات المحتوى في 5 جمل من شغلك وقولها بصوت عالي مع النبر.', 'Mark the content words in 5 sentences about your work and say them aloud with the stress.'),
      B('اسمع جملة من فيديو تقني وكررها بنفس الإيقاع (shadowing) 5 مرات.', 'Listen to one sentence from a tech video and repeat it with the same rhythm (shadowing) 5 times.')],
    words: [W('sentence stress', 'الكلمات اللي بتتقال أقوى في الجملة', 'the words said more strongly in a sentence', 'Sentence stress falls on the key words.'),
      W('shadowing', 'تكرر كلام متحدث وراه على طول بنفس الإيقاع', 'repeating a speaker right after them with the same rhythm', 'Shadowing improves your rhythm fast.')],
    quiz: [Q(B('في «The script sends an email» الكلمة اللي مش بتتنبر:', 'In «The script sends an email» the unstressed word is:'), ['an', 'script', 'email'], 0, B('كلمات الربط خفيفة.', 'Function words are light.'))] },
  { learn: [L(B('الأشكال الضعيفة: is وare وthere', 'Weak forms: is, are and there'),
      B('في الكلام الطبيعي `there are` بتتقال «ðə-rə» و`it is` بتبقى «its». و`to` بتبقى «tə» و`and` بتبقى «ən». ده سبب إنك بتفهم المكتوب ومش بتفهم المسموع. اتعلّم تسمعها، ومش لازم تقولها كده من أول يوم.',
        'In natural speech `there are` sounds like «ðə-rə» and `it is` becomes «its». `to` becomes «tə» and `and` becomes «ən». This is why you understand written English but not spoken English. Learn to hear them; you do not have to say them that way from day one.'),
      'written:  There are two errors in the log.\nspoken:   ðə-rə TWO ERRors in the LOG.\nwritten:  I want to check it and fix it.\nspoken:   I WANT tə CHECK it ən FIX it.')],
    practice: [B('اسمع دقيقتين من فيديو شرح، واكتب كل `there is/are` و`to` اللي سمعتها.', 'Listen to two minutes of a tutorial video and write every `there is/are` and `to` you hear.'),
      B('اعمل dictation: اسمع 3 جمل واكتبها، وبعدين قارن بالـ subtitles.', 'Do a dictation: listen to 3 sentences, write them, then compare with the subtitles.')],
    words: [W('weak form', 'نطق خفيف ومختصر لكلمة ربط', 'a light, short way to say a function word', 'The weak form of to sounds like tə.'),
      W('linking sound', 'وصل آخر كلمة بأول اللي بعدها في الكلام', 'joining the end of one word to the next in speech', 'In "check it" there is a linking sound: che-kit.')],
    quiz: [Q(B('ليه بتفهم المكتوب أكتر من المسموع؟', 'Why do you understand written English better than spoken?'), ['weak forms and linking', 'spelling', 'grammar'], 0, B('الكلمات الصغيرة بتتقال مختصرة.', 'Small words are said in short forms.'))] },
  { learn: [L(B('أسماء بتتعد وأسماء مبتتعدش', 'Countable and uncountable nouns'),
      B('في التقنية كلمات كتير **مبتتعدش**: `data`، `information`، `software`، `feedback`، `advice`، `code`، `equipment`. يعني من غير a ومن غير s: `some feedback` مش `a feedback` ولا `feedbacks`. ولو عايز تعدّها: `a piece of feedback`، `two lines of code`، `a software tool`.',
        'Many tech words are **uncountable**: `data`, `information`, `software`, `feedback`, `advice`, `code`, `equipment`. So no a and no s: `some feedback`, not `a feedback` or `feedbacks`. To count them: `a piece of feedback`, `two lines of code`, `a software tool`.'),
      '✗ Thanks for the feedbacks.      ✓ Thanks for the feedback.\n✗ I wrote a code.                ✓ I wrote some code / a script.\n✗ Can you give me an advice?     ✓ Can you give me some advice?')],
    practice: [B('صلّح 8 جمل فيها الأخطاء دي (اكتبها بنفسك الأول).', 'Fix 8 sentences with these mistakes (write them yourself first).'),
      B('دوّر في إيميلاتك القديمة بالإنجليزي على `feedbacks` أو `informations` أو `a code`.', 'Search your old English emails for `feedbacks`, `informations` or `a code`.')],
    words: [W('uncountable', 'اسم مبيتعدش ومالوش جمع (data، advice)', 'a noun you cannot count, with no plural (data, advice)', 'Feedback is uncountable.'),
      W('countable noun', 'اسم بيتعد وليه جمع (file، bug)', 'a noun you can count, with a plural (file, bug)', 'Bug is a countable noun: one bug, two bugs.')],
    quiz: [Q(B('الصح:', 'Correct:'), ['Thanks for your feedback.', 'Thanks for your feedbacks.', 'Thanks for a feedback.'], 0, B('feedback مبيتعدش.', 'feedback is uncountable.'))] },
  { learn: [L(B('نغمة السؤال', 'Question intonation'),
      B('سؤال **yes/no** صوتك بيطلع لفوق في آخره ↗: `Is the server running?` ↗. سؤال **wh-** (what, where, why) صوتك بينزل ↘: `Where is the log file?` ↘. لو طلّعت صوتك في كل سؤال، هتبان مش متأكد؛ ولو نزّلته في yes/no، هيبان كأنه أمر.',
        'In a **yes/no** question your voice goes up at the end ↗: `Is the server running?` ↗. In a **wh-** question (what, where, why) it goes down ↘: `Where is the log file?` ↘. Rising on every question sounds unsure; falling on yes/no can sound like an order.'),
      'Did you restart it? ↗\nWhat did the logs say? ↘\nCan you share your screen? ↗\nWhy did the build fail? ↘')],
    practice: [B('اكتب 5 أسئلة yes/no و5 wh- عن مشكلة تقنية، وقولهم بالنغمة الصح وسجّل.', 'Write 5 yes/no and 5 wh- questions about a tech problem, say them with the right tone and record them.'),
      B('في فيديو مقابلة أو اجتماع، علّم النغمة في 5 أسئلة سمعتها.', 'In an interview or meeting video, mark the tone of 5 questions you hear.')],
    words: [W('intonation', 'طلوع ونزول الصوت في الكلام', 'the rise and fall of the voice in speech', 'Your intonation shows it is a question.'),
      W('rising tone', 'الصوت بيطلع لفوق في الآخر', 'the voice going up at the end', 'Yes/no questions usually have a rising tone.')],
    quiz: [Q(B('«Where is the config file?» الصوت في الآخر:', '«Where is the config file?» — at the end the voice:'), ['falls', 'rises', 'stays flat'], 0, B('أسئلة wh- بتنزل.', 'Wh- questions fall.'))] },
  { learn: [L(B('ممنوع ومش لازم: must not وdon\'t have to', 'Forbidden vs not needed: must not and don\'t have to'),
      B('فرق خطير في التوثيق: `You must not commit the .env file` = **ممنوع**. `You don\'t have to restart the server` = **مش لازم** (براحتك). وكمان `should not` = يُفضّل لأ، و`cannot` = مش ممكن تقنيًا. لو خلطتهم، ممكن تفهم التحذير على إنه اختيار.',
        'A critical difference in docs: `You must not commit the .env file` = **forbidden**. `You don\'t have to restart the server` = **not necessary** (your choice). Also `should not` = better not, and `cannot` = technically impossible. Mix them up and a warning may look like an option.'),
      'You must not share your API key.        → forbidden\nYou don\'t have to install Docker.       → optional\nYou should not edit generated files.     → advice\nYou cannot delete the default workspace. → impossible')],
    practice: [B('دوّر في توثيق أداة تستخدمها على 5 جمل فيها must أو should أو don\'t have to وصنّفها.', 'Find 5 sentences with must, should or don\'t have to in a tool’s docs and classify them.'),
      B('اكتب 6 قواعد لمشروعك (2 ممنوع، 2 نصيحة، 2 اختياري).', 'Write 6 rules for your project (2 forbidden, 2 advice, 2 optional).')],
    words: [W('prohibition', 'منع صريح لحاجة', 'a clear rule that something is not allowed', 'Must not expresses a prohibition.'),
      W('falling tone', 'الصوت بينزل في الآخر', 'the voice going down at the end', 'Statements end with a falling tone.')],
    quiz: [Q(B('«You don\'t have to log in» معناها:', '«You don\'t have to log in» means:'), ['logging in is optional', 'logging in is forbidden', 'logging in is impossible'], 0, B('مش لازم، بس مسموح.', 'Not needed, but allowed.'))] },
  { review: [B('⚡ نبر الجملة، والأشكال الضعيفة، والـ shadowing.', '⚡ Sentence stress, weak forms and shadowing.'),
      B('⚡ الأسماء اللي مبتتعدش، ونغمة الأسئلة، وmust not مقابل don\'t have to: سجّل دقيقة بتشرح فيها قواعد مشروعك.', '⚡ Uncountable nouns, question tones, and must not vs don\'t have to: record one minute explaining your project rules.')] }
] };
