// English week 3 — the intensive hour (weeks 1–12 are 3 hours a day): pronunciation, listening, speaking and
// writing drills on the day's topic. Merged into the week by tools/build_weeks.js.
const B = (ar, en) => ({ ar, en });
const L = (h, p, ex) => ({ h, p, ex });
const W = (t, ar, en, ex) => ({ t, m: B(ar, en), ex });
const Q = (q, o, a, why) => ({ q, o, a, why });
module.exports = { days: [
  { learn: [L(B('نطق الـ s: /s/ و/z/ و/ɪz/', 'Saying the s: /s/, /z/ and /ɪz/'),
      B('الـ s في `returns` و`checks` و`fixes` مش بتتنطق زي بعض: بعد صوت مكتوم (p, t, k, f) بتبقى **/s/**: checks، gets. بعد صوت مجهور أو حرف علة بتبقى **/z/**: returns، runs، saves. وبعد s, z, sh, ch, x بتبقى مقطع زيادة **/ɪz/**: fixes، pushes، caches.',
        'The s in `returns`, `checks` and `fixes` is not said the same way: after a voiceless sound (p, t, k, f) it is **/s/**: checks, gets. After a voiced sound or a vowel it is **/z/**: returns, runs, saves. After s, z, sh, ch, x it adds a syllable **/ɪz/**: fixes, pushes, caches.'),
      '/s/  checks · gets · stops · writes\n/z/  returns · runs · saves · calls\n/ɪz/ fixes · pushes · caches · uses')],
    practice: [B('صنّف 15 فعل من شغلك للتلات مجموعات وقولهم بصوت عالي.', 'Sort 15 verbs from your work into the three groups and say them aloud.'),
      B('اقرا وصف 3 دوال من توثيق (The function returns…) مع نطق الـ s الصح.', 'Read the description of 3 functions from docs (The function returns…) with the right s sound.')],
    words: [W('third person', 'he وshe وit (والاسم المفرد)', 'he, she, it (and singular nouns)', 'Add s for the third person: it runs.'),
      W('minimal pair', 'كلمتين بيفرق بينهم صوت واحد', 'two words that differ by one sound', 'ship and sheep are a minimal pair.')],
    quiz: [Q(B('الـ s في `fixes` بتتنطق:', 'The s in `fixes` sounds like:'), ['/ɪz/', '/s/', '/z/'], 0, B('بعد x بتزود مقطع.', 'After x it adds a syllable.'))] },
  { learn: [L(B('قول الوقت والتواريخ', 'Saying times and dates'),
      B('الوقت: `9:00` nine o\'clock، `9:15` nine fifteen أو quarter past nine، `9:30` nine thirty أو half past nine، `9:45` nine forty-five أو quarter to ten. التاريخ: `March 5` يتقال March the fifth (أمريكي: March fifth). و`at` للساعة، `on` لليوم، `in` للشهر والسنة.',
        'Time: `9:00` nine o\'clock, `9:15` nine fifteen or quarter past nine, `9:30` nine thirty or half past nine, `9:45` nine forty-five or quarter to ten. Dates: `March 5` is said March the fifth (US: March fifth). Use `at` for times, `on` for days, `in` for months and years.'),
      'The job runs at 7:30 on Mondays in March.\n→ "at seven thirty, on Mondays, in March"\nThe meeting is on June 3rd at quarter past two.')],
    practice: [B('قول مواعيد 5 cron jobs عندك بالإنجليزي كاملة (اليوم والساعة).', 'Say the schedule of 5 of your cron jobs in full English (day and time).'),
      B('اكتب 5 جمل بـ at وon وin عن مواعيد شغلك.', 'Write 5 sentences with at, on and in about your work schedule.')],
    words: [W('o\'clock', 'الساعة بالظبط من غير دقايق', 'an exact hour with no minutes', 'The backup runs at six o\'clock.'),
      W('quarter past', 'وربع (بعد الساعة بـ 15 دقيقة)', '15 minutes after the hour', 'We meet at quarter past ten.')],
    quiz: [Q(B('الصح:', 'Correct:'), ['on Monday at 9', 'in Monday at 9', 'at Monday on 9'], 0, B('on لليوم، at للساعة.', 'on for days, at for times.'))] },
  { learn: [L(B('نطق -ed: /t/ و/d/ و/ɪd/', 'Saying -ed: /t/, /d/ and /ɪd/'),
      B('زي الـ s: بعد صوت مكتوم الـ ed بتبقى **/t/**: fixed، pushed، checked. بعد صوت مجهور **/d/**: saved، called، deployed. وبعد t أو d بس بتبقى مقطع زيادة **/ɪd/**: started، updated، added. غلطة شائعة: تقول «fix-ed» بمقطعين.',
        'Like the s: after a voiceless sound -ed is **/t/**: fixed, pushed, checked. After a voiced sound **/d/**: saved, called, deployed. Only after t or d does it add a syllable **/ɪd/**: started, updated, added. A common mistake: saying «fix-ed» with two syllables.'),
      '/t/  fixed · pushed · checked · stopped\n/d/  saved · called · deployed · logged\n/ɪd/ started · updated · added · tested')],
    practice: [B('اقرا آخر 10 commits ليك بصيغة الماضي (Fixed، Added…) بالنطق الصح.', 'Read your last 10 commits in the past tense (Fixed, Added…) with the right ending.'),
      B('احكي بصوت عالي إيه اللي عملته امبارح في 6 جمل ماضي.', 'Say aloud what you did yesterday in 6 past-tense sentences.')],
    words: [W('regular verb', 'فعل ماضيه بيتعمل بـ -ed', 'a verb whose past is made with -ed', 'deploy is a regular verb: deployed.'),
      W('past ending', 'النهاية اللي بتضيفها للفعل في الماضي', 'the ending you add to a verb for the past', 'The past ending in fixed sounds like /t/.')],
    quiz: [Q(B('أنهي فعل الـ ed فيه مقطع زيادة؟', 'Which verb adds a syllable with -ed?'), ['updated', 'fixed', 'called'], 0, B('بعد t أو d بس.', 'Only after t or d.'))] },
  { learn: [L(B('كلام الخطط والتقدير', 'Talking about plans and estimates'),
      B('في اجتماع التخطيط: `going to` للي اتقرر (`We\'re going to migrate in May`)، و`will` للتوقع أو قرار دلوقتي (`It will probably take two days`، `I\'ll check`). ولما مش متأكد، خفّف كلامك (hedge): `probably`، `should be done by Friday`، `I expect`، `if nothing breaks`.',
        'In a planning meeting: `going to` for what is decided (`We\'re going to migrate in May`), and `will` for predictions or decisions made now (`It will probably take two days`, `I\'ll check`). When unsure, hedge: `probably`, `should be done by Friday`, `I expect`, `if nothing breaks`.'),
      'We\'re going to move the bot to the new server next week.\nIt should take about two days, if the API keys are ready.\nI\'ll send you an update on Thursday.')],
    practice: [B('اكتب خطة أسبوعك الجاي في 5 جمل بـ going to و3 تقديرات بـ will مع hedge.', 'Write next week’s plan in 5 going to sentences and 3 will estimates with hedging.'),
      B('قولها كأنك في اجتماع، وسجّل.', 'Say it as if in a meeting, and record it.')],
    words: [W('roadmap', 'خطة بالمراحل الجاية ومواعيدها', 'a plan of the coming stages and their dates', 'The roadmap shows the next three months.'),
      W('hedge', 'تخفّف كلامك عشان متوعدش بحاجة مش متأكد منها', 'to soften what you say so you do not promise what you are unsure of', 'Hedge your estimate with "probably".')],
    quiz: [Q(B('قرار اتاخد قبل الاجتماع:', 'A decision made before the meeting:'), ['We\'re going to switch to Postgres.', 'We\'ll switch to Postgres, I think.', 'We switch to Postgres yesterday.'], 0, B('going to للي اتقرر.', 'going to for decided plans.'))] },
  { learn: [L(B('تحديث الـ stand-up', 'The stand-up update'),
      B('3 أسئلة، دقيقة واحدة: **Yesterday** (ماضي): `I finished the webhook.` **Today** (مستقبل/مستمر): `I\'m working on the error alerts.` **Blockers**: `I\'m blocked by the missing API key.` قلّل كلمات الحشو (um، like، so basically) وقف ثانية بدلها.',
        'Three questions, one minute: **Yesterday** (past): `I finished the webhook.` **Today** (future/continuous): `I\'m working on the error alerts.` **Blockers**: `I\'m blocked by the missing API key.` Cut filler words (um, like, so basically) and pause for a second instead.'),
      'Yesterday I finished the booking webhook and tested it with curl.\nToday I\'m adding the Telegram alerts.\nI\'m blocked on the Gmail access — could someone share it?')],
    practice: [B('سجّل stand-up كل يوم الأسبوع ده (دقيقة)، واسمعه وعدّ كلمات الحشو.', 'Record a one-minute stand-up every day this week, listen back and count the filler words.'),
      B('اكتب نفس الـ stand-up في رسالة Slack من 3 سطور.', 'Write the same stand-up as a 3-line Slack message.')],
    words: [W('stand-up', 'اجتماع يومي قصير كل واحد بيقول عمل إيه', 'a short daily meeting where each person says what they did', 'Keep your stand-up under one minute.'),
      W('filler words', 'كلمات حشو زي um وlike', 'empty words like um and like', 'Pause instead of using filler words.')],
    quiz: [Q(B('في الـ stand-up «النهارده» غالبًا بزمن:', 'In a stand-up, «today» usually uses:'), ['I\'m working on…', 'I worked on…', 'I have work on…'], 0, B('شغل جاري.', 'Work in progress.'))] },
  { review: [B('⚡ نطق -s و-ed، والوقت والتواريخ مع at/on/in.', '⚡ Saying -s and -ed, and times and dates with at/on/in.'),
      B('⚡ going to وwill والـ hedging، والـ stand-up في دقيقة: سجّل stand-up حقيقي وقيّمه.', '⚡ going to, will and hedging, and a one-minute stand-up: record a real stand-up and assess it.')] }
] };
