// English week 4 — the intensive hour (weeks 1–12 are 3 hours a day): pronunciation, listening, speaking and
// writing drills on the day's topic. Merged into the week by tools/build_weeks.js.
const B = (ar, en) => ({ ar, en });
const L = (h, p, ex) => ({ h, p, ex });
const W = (t, ar, en, ex) => ({ t, m: B(ar, en), ex });
const Q = (q, o, a, why) => ({ q, o, a, why });
module.exports = { days: [
  { learn: [L(B('العمليات الحسابية بصوت عالي', 'Operators aloud'),
      B('`a + b` a plus b، `a - b` a minus b، `a * b` a times b، `a / b` a divided by b، `a % b` a modulo b (أو a mod b)، `a ** 2` a squared، `a > b` a is greater than b، `a <= b` a is less than or equal to b، `!=` is not equal to. و`x = 5` بتتقال x equals five أو set x to five.',
        '`a + b` a plus b, `a - b` a minus b, `a * b` a times b, `a / b` a divided by b, `a % b` a modulo b (or a mod b), `a ** 2` a squared, `a > b` a is greater than b, `a <= b` a is less than or equal to b, `!=` is not equal to. And `x = 5` is said x equals five or set x to five.'),
      'total = price * qty * 1.14\n→ "total equals price times quantity times one point one four"\nif n % 2 == 0\n→ "if n mod two is equal to zero"')],
    practice: [B('اقرا 6 سطور حساب أو شروط من كودك بصوت عالي.', 'Read 6 lines of maths or conditions from your code aloud.'),
      B('اكتب بالكلام (من غير رموز) معادلة حساب الضريبة والخصم في مشروعك.', 'Write in words (no symbols) the tax and discount formula in your project.')],
    words: [W('equals sign', 'علامة =', 'the = symbol', 'Put spaces around the equals sign.'),
      W('modulo', 'باقي القسمة (%)', 'the remainder after division (%)', '10 modulo 3 is 1.')],
    quiz: [Q(B('`a <= b` بتتقال:', '`a <= b` is said:'), ['a is less than or equal to b', 'a is smaller b', 'a arrow b'], 0, B('less than or equal to.', 'less than or equal to.'))] },
  { learn: [L(B('وصف الـ data structures في الكلام', 'Describing data structures in speech'),
      B('`{"name": "Sara"}` an object with a key `name` and the value `Sara` (key-value pair). `[1, 2, 3]` a list (array) of three numbers. `users[0]` the first user (index zero). `user["address"]["city"]` the city inside the user’s address. استخدم inside وnested وfirst/last بدل ما تقرا الرموز.',
        '`{"name": "Sara"}` an object with a key `name` and the value `Sara` (a key-value pair). `[1, 2, 3]` a list (array) of three numbers. `users[0]` the first user (index zero). `user["address"]["city"]` the city inside the user’s address. Use inside, nested and first/last instead of reading the symbols.'),
      '"The response is a list of orders. Each order is an object\n with an id, a total, and a nested customer object\n that holds the name and phone."')],
    practice: [B('خُد رد API حقيقي ووصفه بالكلام في 4 جمل كأنك بتشرحه لزميل في مكالمة.', 'Take a real API response and describe it in 4 sentences as if explaining it to a colleague on a call.'),
      B('اكتب كلمات مركّبة بالـ hyphen صح: `read-only`، `well-known`، `built-in`، `real-time`.', 'Write hyphenated words correctly: `read-only`, `well-known`, `built-in`, `real-time`.')],
    words: [W('key-value pair', 'مفتاح وقيمته في object', 'a key and its value in an object', '"name": "Sara" is a key-value pair.'),
      W('hyphen', 'الشرطة القصيرة اللي بتربط كلمتين', 'the short dash that joins two words', 'Write read-only with a hyphen.')],
    quiz: [Q(B('`users[0]` بتتقال:', '`users[0]` is said:'), ['the first user', 'the zero users', 'users zero bracket'], 0, B('index 0 = الأول.', 'Index 0 = the first.'))] },
  { learn: [L(B('الاستماع بالقطع (chunks)', 'Listening in chunks'),
      B('متحاولش تفهم كل كلمة في فيديو شرح. اسمع **قطع**: `for each item in the list` قطعة واحدة، `if it\'s not empty` قطعة. وقّف الفيديو بعد كل جملة، وقول القطع اللي فهمتها. ولو كلمة صعبة، اطلب منهم يتهجّوها: `Could you spell that out?`',
        'Do not try to catch every word in a tutorial. Listen for **chunks**: `for each item in the list` is one chunk, `if it\'s not empty` another. Pause after each sentence and say the chunks you caught. If a word is hard, ask them to spell it: `Could you spell that out?`'),
      'chunks: [for each order] [in the list] [we check] [if the total] [is above a hundred]\n"Sorry, could you spell that out? Is it c-a-c-h-e?"')],
    practice: [B('اسمع 3 دقايق من فيديو عن loops، وقّف كل جملة واكتب القطع.', 'Listen to 3 minutes of a video about loops, pause each sentence and write the chunks.'),
      B('اتهجّى بصوت عالي: `queue`، `cache`، `schema`، `async`.', 'Spell aloud: `queue`, `cache`, `schema`, `async`.')],
    words: [W('chunking', 'تقسيم الكلام لقطع بتتفهم مرة واحدة', 'splitting speech into pieces you understand at once', 'Chunking makes fast speech easier.'),
      W('spell out', 'تقول حروف الكلمة حرف حرف', 'to say the letters of a word one by one', 'Could you spell out the password policy name?')],
    quiz: [Q(B('مفهمتش اسم أداة في مكالمة. تقول:', 'You missed a tool’s name on a call. You say:'), ['Could you spell that out?', 'Repeat.', 'What?'], 0, B('مهذب وواضح.', 'Polite and clear.'))] },
  { learn: [L(B('الكلمات اللي بتيجي مع بعض (collocations)', 'Words that go together (collocations)'),
      B('في الإنجليزي فيه أفعال معيّنة مع أسماء معيّنة: `create an instance` (مش make)، `call a method`، `raise an exception`، `pass an argument`، `run a test`، `make a request`، `do research`. الترجمة الحرفية من العربي بتطلّع حاجة مفهومة بس غريبة. واحذر الـ false friends زي `actual` (= حقيقي، مش «حالي»).',
        'English pairs certain verbs with certain nouns: `create an instance` (not make), `call a method`, `raise an exception`, `pass an argument`, `run a test`, `make a request`, `do research`. Translating word by word from Arabic gives something understandable but odd. And beware of false friends like `actual` (= real, not «current»).'),
      '✓ raise an exception   ✗ throw up an exception\n✓ run the tests        ✗ play the tests\n✓ make a request       ✗ do a request\nactual = real (the actual result) · current = now')],
    practice: [B('اعمل جدول بـ 15 collocation من التوثيق اللي بتقراه.', 'Make a table of 15 collocations from the docs you read.'),
      B('اكتب 5 جمل عن كود OOP بالـ collocations الصح.', 'Write 5 sentences about OOP code with the right collocations.')],
    words: [W('collocation', 'كلمتين بيجوا مع بعض عادةً', 'two words that usually go together', 'raise an exception is a collocation.'),
      W('false friend', 'كلمة شبه كلمة في لغتك بس معناها مختلف', 'a word that looks like one in your language but means something else', 'actual is a false friend for many learners.')],
    quiz: [Q(B('الصح:', 'Correct:'), ['raise an exception', 'make an exception error', 'do an exception'], 0, B('raise/throw an exception.', 'raise/throw an exception.'))] },
  { learn: [L(B('تلخيص خطأ في اجتماع', 'Summarising an error in a meeting'),
      B('في اجتماع حد بيسألك «إيه اللي حصل؟». اتكلم بصوت واضح (speak up) وبترتيب: **What** (`The sync failed at 3 a.m.`)، **Why** (`because the API token expired`)، **Impact** (`40 orders weren\'t copied`)، **Fix** (`I renewed it and re-ran the job`)، **Next** (`I\'ve added an alert for expiring tokens`).',
        'In a meeting someone asks «what happened?». Speak up clearly and in order: **What** (`The sync failed at 3 a.m.`), **Why** (`because the API token expired`), **Impact** (`40 orders weren\'t copied`), **Fix** (`I renewed it and re-ran the job`), **Next** (`I\'ve added an alert for expiring tokens`).'),
      'What → Why → Impact → Fix → Next\n"The sync failed at 3 a.m. because the token expired. Forty orders weren\'t copied.\n I renewed the token and re-ran the job, and I\'ve added an alert."')],
    practice: [B('اختار 3 أخطاء حصلت معاك ولخّص كل واحد بالترتيب ده في 30 ثانية.', 'Pick 3 errors you had and summarise each in this order in 30 seconds.'),
      B('اكتب نفس الملخص كرسالة لعميل، أقل من 60 كلمة.', 'Write the same summary as a message to a client, under 60 words.')],
    words: [W('speak up', 'تتكلم بصوت أعلى وأوضح', 'to talk louder and more clearly', 'Please speak up, the call is noisy.'),
      W('summarise', 'تقول الأهم في كلام قليل', 'to give the main points in a few words', 'Summarise the incident in three sentences.')],
    quiz: [Q(B('الترتيب الأوضح لشرح عطل:', 'The clearest order to explain a failure:'), ['what, why, impact, fix, next', 'fix, why, what', 'next, impact, what'], 0, B('من الحدث للخطوة الجاية.', 'From the event to the next step.'))] },
  { review: [B('⚡ العمليات والـ data structures بالكلام، والاستماع بالقطع.', '⚡ Operators and data structures in speech, and listening in chunks.'),
      B('⚡ الـ collocations والـ false friends، وتلخيص عطل بالترتيب: سجّل شرح لعطل من مشروع الشهر.', '⚡ Collocations, false friends, and summarising a failure in order: record an explanation of a failure in your month project.')] }
] };
