// English week 5 — the intensive hour (weeks 1–12 are 3 hours a day): pronunciation, listening, speaking and
// writing drills on the day's topic. Merged into the week by tools/build_weeks.js.
const B = (ar, en) => ({ ar, en });
const L = (h, p, ex) => ({ h, p, ex });
const W = (t, ar, en, ex) => ({ t, m: B(ar, en), ex });
const Q = (q, o, a, why) => ({ q, o, a, why });
module.exports = { days: [
  { learn: [L(B('علامات الطريق في التوثيق', 'Signposts in docs'),
      B('الكتّاب بيحطوا كلمات بتقولك الجزء الجاي إيه: `Note:` معلومة جانبية، `Warning:`/`Caution:` خطر، `Tip:` نصيحة، `For example`، `In other words` (هيعيد الشرح أبسط)، `However` (عكس اللي قبله — اقرا كويس)، `Prerequisites` (لازم يكون عندك قبل ما تبدأ). لو بتعمل skim، وقّف عند Warning وHowever دايمًا.',
        'Writers use words that tell you what is coming: `Note:` side information, `Warning:`/`Caution:` danger, `Tip:` advice, `For example`, `In other words` (a simpler restatement), `However` (the opposite of what came before — read carefully), `Prerequisites` (what you need before you start). When skimming, always stop at Warning and However.'),
      'Note: the token is valid for one hour.\nWarning: deleting a workspace cannot be undone.\nThe API is free. However, it is limited to 100 calls a day.')],
    practice: [B('في صفحة توثيق، لوّن كل الـ signposts وصنّفها (معلومة، خطر، نصيحة، عكس).', 'In a docs page, highlight every signpost and classify it (info, danger, advice, contrast).'),
      B('اكتب فقرة توثيق قصيرة لـ workflow عندك فيها Note وWarning وHowever.', 'Write a short docs paragraph for one of your workflows using Note, Warning and However.')],
    words: [W('signpost', 'كلمة بتقول للقارئ الجزء الجاي نوعه إيه', 'a word that tells the reader what kind of part comes next', 'However is a signpost for contrast.'),
      W('overview', 'نظرة عامة سريعة على موضوع', 'a short general description of a topic', 'Start with the overview page.')],
    quiz: [Q(B('«However» في التوثيق معناها:', '«However» in docs signals:'), ['a contrast — read carefully', 'an example', 'the end of the page'], 0, B('اللي جاي عكس اللي فات.', 'What follows contrasts with what came before.'))] },
  { learn: [L(B('اشرح request وresponse بالكلام', 'Explaining a request and response in words'),
      B('لما تشرح API لحد: `You send a POST request to /orders with a JSON body. The body must include the name and phone.` و`If it works, you get back a 201 with the new order id. If the phone is wrong, you get a 422.` الأفعال المهمة: send، include، return، get back، respond with.',
        'When explaining an API to someone: `You send a POST request to /orders with a JSON body. The body must include the name and phone.` and `If it works, you get back a 201 with the new order id. If the phone is wrong, you get a 422.` Key verbs: send, include, return, get back, respond with.'),
      '"First you send a GET request to /users with your key in the header.\n The API returns a list of users, twenty per page.\n To get the next page, you add page=2."')],
    practice: [B('اعمل walkthrough صوتي لـ endpoint في 60 ثانية: الطلب، المدخلات، الرد، والأخطاء.', 'Record a 60-second spoken walkthrough of one endpoint: request, inputs, response and errors.'),
      B('اكتب نفس الشرح في 5 جمل مكتوبة.', 'Write the same explanation in 5 sentences.')],
    words: [W('walkthrough', 'شرح خطوة بخطوة وانت بتعمل الحاجة', 'a step-by-step explanation while doing something', 'I’ll give you a quick walkthrough of the API.'),
      W('sample request', 'مثال جاهز لطلب تقدر تجرّبه', 'a ready example of a request you can try', 'Copy the sample request into Postman.')],
    quiz: [Q(B('«you get back a 201» معناها:', '«you get back a 201» means:'), ['the API returns status 201', 'you return to page 201', 'you send 201 requests'], 0, B('get back = يرجعلك.', 'get back = receive in reply.'))] },
  { learn: [L(B('أفعال الصلاحيات', 'Permission verbs'),
      B('في صفحات المصادقة: `grant` (يدّي صلاحية)، `revoke` (يسحبها)، `expire` (تنتهي)، `rotate` (تغيّر المفتاح بانتظام)، `authorize` (يسمح لتطبيق)، `scope` (حدود الصلاحية). جملة شائعة: `Tokens expire after 60 minutes; you can revoke a token at any time.`',
        'On auth pages: `grant` (give access), `revoke` (take it back), `expire` (end), `rotate` (change a key regularly), `authorize` (allow an app), `scope` (the limits of access). A common sentence: `Tokens expire after 60 minutes; you can revoke a token at any time.`'),
      'The admin can grant read access to the sheet.\nIf a key leaks, revoke it and create a new one.\nWe rotate the keys every 90 days.')],
    practice: [B('اقرا صفحة authentication لخدمة واحدة وطلّع كل أفعال الصلاحيات فيها.', 'Read one service’s authentication page and list every permission verb in it.'),
      B('اكتب سياسة مفاتيح لمشروعك في 4 جمل بالأفعال دي.', 'Write a key policy for your project in 4 sentences using these verbs.')],
    words: [W('grant', 'تدّي صلاحية رسميًا', 'to give access officially', 'Grant the bot read access only.'),
      W('revoke', 'تسحب صلاحية أو مفتاح', 'to take back access or a key', 'Revoke the old token today.')],
    quiz: [Q(B('المفتاح اتسرّب. أول حاجة:', 'A key leaked. First:'), ['revoke it', 'grant it', 'rotate the docs'], 0, B('اسحبه فورًا.', 'Take it back at once.'))] },
  { learn: [L(B('لغة الحدود والأرقام', 'The language of limits and numbers'),
      B('`up to 100 items per request` (لحد 100)، `at most`/`no more than` (أقصى)، `at least` (أقل حاجة)، `a cap of 1,000 calls a day` (سقف)، `quota` (الحصة)، `exceed the limit` (تعدّي الحد)، `throttled` (اتبطّأت). والأرقام: `1,000` one thousand، `1.5` one point five، `10%` ten percent.',
        '`up to 100 items per request`, `at most`/`no more than` (maximum), `at least` (minimum), `a cap of 1,000 calls a day`, `quota` (your allowance), `exceed the limit`, `throttled` (slowed down). Numbers: `1,000` one thousand, `1.5` one point five, `10%` ten percent.'),
      'Each request returns up to 100 records.\nThe free plan has a quota of 1,000 calls a day.\nIf you exceed the limit, you get a 429 and must wait.')],
    practice: [B('اقرا صفحة rate limits لـ API واكتبها بكلامك في 3 جمل.', 'Read an API’s rate limits page and rewrite it in your own words in 3 sentences.'),
      B('قول بصوت عالي 10 أرقام من التوثيق (فيها كسور ونسب وآلاف).', 'Say aloud 10 numbers from docs (with decimals, percentages and thousands).')],
    words: [W('cap', 'حد أقصى ثابت', 'a fixed upper limit', 'There is a cap of 50 emails per hour.'),
      W('quota', 'الحصة المسموحة ليك في فترة', 'the amount you are allowed in a period', 'You used 80% of your monthly quota.')],
    quiz: [Q(B('«up to 100» معناها:', '«up to 100» means:'), ['100 or fewer', 'exactly 100', 'more than 100'], 0, B('لحد 100.', 'At most 100.'))] },
  { learn: [L(B('اتبع دليل تثبيت', 'Following a setup guide'),
      B('أدلة التثبيت ليها نمط: `Prerequisites` (اللي لازم يكون عندك)، خطوات بصيغة الأمر، `Make sure…`/`Ensure…` (اتأكد)، `Optionally…` (اختياري)، `Replace X with your…` (حط قيمتك)، و`Troubleshooting` في الآخر للمشاكل الشائعة. اقرا الـ prerequisites قبل أي حاجة — أغلب المشاكل من هناك.',
        'Setup guides follow a pattern: `Prerequisites` (what you need), imperative steps, `Make sure…`/`Ensure…`, `Optionally…`, `Replace X with your…` (put your own value), and `Troubleshooting` at the end for common problems. Read the prerequisites before anything — most problems start there.'),
      'Prerequisites: Node.js 20 or later.\n1. Clone the repo.  2. Replace YOUR_KEY with your API key.\n3. Make sure port 5678 is free.\nTroubleshooting: "EADDRINUSE" means the port is taken.')],
    practice: [B('اتبع دليل تثبيت أداة جديدة بالإنجليزي، واكتب أي جملة وقفتك ومعناها.', 'Follow an English setup guide for a new tool, and write down any sentence that stopped you and its meaning.'),
      B('اكتب قسم Troubleshooting لمشروعك فيه 3 مشاكل وحلولها.', 'Write a Troubleshooting section for your project with 3 problems and fixes.')],
    words: [W('prerequisite', 'حاجة لازم تكون موجودة قبل ما تبدأ', 'something you need before you start', 'Docker is a prerequisite for this guide.'),
      W('troubleshoot', 'تدوّر على سبب مشكلة وتحلها خطوة بخطوة', 'to find and fix the cause of a problem step by step', 'Troubleshoot the install with the logs.')],
    quiz: [Q(B('«Replace YOUR_KEY with your key» معناها:', '«Replace YOUR_KEY with your key» means:'), ['put your own key there', 'delete your key', 'keep YOUR_KEY'], 0, B('بدّل الكلمة بقيمتك.', 'Swap the word for your value.'))] },
  { review: [B('⚡ الـ signposts، وشرح request/response بالكلام، وأفعال الصلاحيات.', '⚡ Signposts, explaining request/response in words, and permission verbs.'),
      B('⚡ لغة الحدود والأرقام، وأدلة التثبيت: اكتب README قصير لـ API من مشروعك.', '⚡ The language of limits and numbers, and setup guides: write a short README for an API in your project.')] }
] };
