// English week 6 — the intensive hour (weeks 1–12 are 3 hours a day): pronunciation, listening, speaking and
// writing drills on the day's topic. Merged into the week by tools/build_weeks.js.
const B = (ar, en) => ({ ar, en });
const L = (h, p, ex) => ({ h, p, ex });
const W = (t, ar, en, ex) => ({ t, m: B(ar, en), ex });
const Q = (q, o, a, why) => ({ q, o, a, why });
module.exports = { days: [
  { learn: [L(B('أسماء الـ boolean', 'Naming booleans'),
      B('المتغيّر اللي قيمته true/false اسمه لازم يبان كسؤال إجابته أيوه أو لأ: `isActive`، `hasAccess`، `canEdit`، `shouldRetry`، `wasSent`. مش `active` (صفة ولا أمر؟) ولا `flag`. والدالة اللي بتجيب قيمة تبدأ بـ get (getter): `getUser()`.',
        'A variable holding true/false should read like a yes/no question: `isActive`, `hasAccess`, `canEdit`, `shouldRetry`, `wasSent`. Not `active` (an adjective or a command?) or `flag`. And a function that fetches a value starts with get (a getter): `getUser()`.'),
      '✗ active, flag, check, paid\n✓ isActive, hasPaid, canRefund, shouldNotify\nif (user.isActive && order.hasPaid) { … }   // reads like English')],
    practice: [B('غيّر أسماء كل الـ booleans في كود عندك للنمط ده.', 'Rename every boolean in some code of yours to this pattern.'),
      B('اقرا شرط if عندك بصوت عالي كجملة إنجليزي: لو مبتتقراش، الاسم محتاج تحسين.', 'Read an if condition of yours aloud as an English sentence: if it does not read well, the name needs work.')],
    words: [W('getter', 'دالة بترجّع قيمة', 'a function that returns a value', 'getUser is a getter.'),
      W('boolean name', 'اسم متغيّر true/false بيبدأ بـ is/has/can', 'a true/false variable name starting with is/has/can', 'hasAccess is a clear boolean name.')],
    quiz: [Q(B('أحسن اسم:', 'The best name:'), ['isExpired', 'expire', 'flag2'], 0, B('سؤال إجابته yes/no.', 'A yes/no question.'))] },
  { learn: [L(B('نصوص للمستخدم: placeholder ورسائل', 'Text for users: placeholders and messages'),
      B('النصوص اللي المستخدم بيشوفها لازم تكون بسيطة ومهذبة: `Enter your email` (placeholder text)، `Something went wrong. Please try again.`، `Saved!`. وفي الكود، الحروف الخاصة جوه النص محتاجة **escape**: `"She said \\"hi\\""` أو `\'It\\\'s\'` أو `\\n` لسطر جديد.',
        'Text users see should be simple and polite: `Enter your email` (placeholder text), `Something went wrong. Please try again.`, `Saved!`. In code, special characters inside a string need **escaping**: `"She said \\"hi\\""` or `\'It\\\'s\'` or `\\n` for a new line.'),
      'placeholder: "e.g. sara@example.com"\nerror: "We couldn\'t save your booking. Please try again."\ncode:  msg = "Line one\\nLine two"')],
    practice: [B('اكتب 8 رسايل للمستخدم لبوت أو فورم (نجاح، خطأ، تحميل، فاضي).', 'Write 8 user messages for a bot or form (success, error, loading, empty).'),
      B('اكتب 3 نصوص فيها تنصيص جوه تنصيص وطلّعهم في Code node من غير أخطاء.', 'Write 3 strings with quotes inside quotes and output them from a Code node without errors.')],
    words: [W('placeholder text', 'نص رمادي جوه الخانة بيوضح تكتب إيه', 'grey hint text inside a field showing what to type', 'The placeholder text says "e.g. 010…".'),
      W('escape', 'تحط \\ قبل حرف خاص عشان يتكتب زي ما هو', 'to put \\ before a special character so it is taken literally', 'Escape the quote inside the string.')],
    quiz: [Q(B('رسالة خطأ مناسبة للمستخدم:', 'A good error message for users:'), ['We couldn\'t send the code. Please try again.', 'Error 0x8004 null ref', 'You failed.'], 0, B('بسيطة ومهذبة وفيها الخطوة الجاية.', 'Simple, polite, with the next step.'))] },
  { learn: [L(B('شرح خوارزمية بالكلام', 'Explaining an algorithm aloud'),
      B('استخدم كلمات ترتيب: `First…`، `Then…`، `For each…`، `If…, otherwise…`، `Finally…`. وابدأ بالخلاصة في جملة: `In a nutshell, it finds duplicate customers by phone.` وبعدين التفاصيل step by step. ده بيفرق جدًا في المقابلات التقنية.',
        'Use sequence words: `First…`, `Then…`, `For each…`, `If…, otherwise…`, `Finally…`. Start with the gist in one sentence: `In a nutshell, it finds duplicate customers by phone.` Then the details step by step. This matters a lot in technical interviews.'),
      '"In a nutshell, it removes duplicate customers.\n First, it cleans every phone number. Then, for each customer,\n it checks if we have seen that number. If so, it skips it; otherwise it keeps it.\n Finally, it returns the unique list."')],
    practice: [B('اشرح بصوت عالي 3 دوال من كودك بالترتيب ده (دقيقة لكل واحدة).', 'Explain 3 functions from your code aloud in this order (one minute each).'),
      B('اكتب شرح خوارزمية ترتيب بسيطة في 5 جمل.', 'Write an explanation of a simple sorting algorithm in 5 sentences.')],
    words: [W('step by step', 'خطوة خطوة بالترتيب', 'one step at a time, in order', 'Walk me through it step by step.'),
      W('in a nutshell', 'باختصار شديد', 'in very few words', 'In a nutshell, it syncs orders to a sheet.')],
    quiz: [Q(B('أحسن بداية لشرح خوارزمية:', 'The best start when explaining an algorithm:'), ['the gist in one sentence', 'the first line of code', 'the variable names'], 0, B('الخلاصة الأول وبعدين التفاصيل.', 'The gist first, then details.'))] },
  { learn: [L(B('تعليق بيقول «ليه»', 'Comments that say «why»'),
      B('التعليق الكويس بيشرح **السبب** (rationale) أو **تحذير** (caveat)، مش بيعيد الكود. كلمات مفيدة: `because`، `so that`، `otherwise`، `Note that…`، `This is a workaround for…`، `TODO:`. والـ docstring بيقول: الدالة بتعمل إيه، المدخلات، اللي بترجّعه، والأخطاء.',
        'A good comment explains the **rationale** or a **caveat**; it does not repeat the code. Useful words: `because`, `so that`, `otherwise`, `Note that…`, `This is a workaround for…`, `TODO:`. A docstring says what the function does, its inputs, what it returns, and its errors.'),
      '✗ # add 1 to i\n✓ # Sheets rows start at 2 because row 1 holds the headers.\n✓ # Caveat: the API returns dates in UTC, so convert before comparing.')],
    practice: [B('راجع 10 تعليقات في كودك: امسح اللي بيعيد الكود، واكتب «ليه» بدلها.', 'Review 10 comments in your code: delete those that repeat the code and write the «why» instead.'),
      B('اكتب docstring كامل لدالة واحدة.', 'Write a full docstring for one function.')],
    words: [W('rationale', 'السبب ورا قرار', 'the reason behind a decision', 'The comment explains the rationale.'),
      W('caveat', 'تحذير أو استثناء لازم تاخد بالك منه', 'a warning or exception to keep in mind', 'One caveat: it only works for Egyptian numbers.')],
    quiz: [Q(B('أفيد تعليق:', 'The most useful comment:'), ['# UTC dates, so convert before comparing', '# loop over items', '# set x'], 0, B('بيقول ليه.', 'It says why.'))] },
  { learn: [L(B('وصف ملفات البيانات', 'Describing data files'),
      B('`a comma-separated file (CSV) with a header row`، `tab-separated`، `UTF-8 encoded`، `one record per line`، `the first column holds the id`، `dates are in ISO format`، `empty cells mean "unknown"`. لما تبعت ملف لحد، اكتب الوصف ده في رسالة أو README جنبه.',
        '`a comma-separated file (CSV) with a header row`, `tab-separated`, `UTF-8 encoded`, `one record per line`, `the first column holds the id`, `dates are in ISO format`, `empty cells mean "unknown"`. When you send someone a file, write this description in a message or a README next to it.'),
      '"orders.csv is a comma-separated, UTF-8 file with a header row.\n Each line is one order. Dates are ISO (YYYY-MM-DD) and totals are in EGP.\n An empty phone cell means the customer didn\'t give one."')],
    practice: [B('اكتب وصف 4 جمل لملف بيانات بتستخدمه.', 'Write a 4-sentence description of a data file you use.'),
      B('اشرح بصوت عالي الفرق بين CSV وJSON لعميل مش تقني.', 'Explain aloud the difference between CSV and JSON to a non-technical client.')],
    words: [W('comma-separated', 'القيم مفصولة بفواصل', 'with values divided by commas', 'Export a comma-separated file.'),
      W('tab-separated', 'القيم مفصولة بـ tab', 'with values divided by tabs', 'Tab-separated files open well in Excel.')],
    quiz: [Q(B('«one record per line» معناها:', '«one record per line» means:'), ['each line is one item', 'one line in the file', 'one column'], 0, B('سطر = سجل.', 'Line = record.'))] },
  { review: [B('⚡ أسماء الـ boolean، ونصوص المستخدم والـ escape، وشرح خوارزمية.', '⚡ Boolean names, user text and escaping, and explaining an algorithm.'),
      B('⚡ تعليقات «ليه»، ووصف ملفات البيانات: راجع مشروعك ونضّف الأسماء والتعليقات.', '⚡ «Why» comments, and describing data files: review your project and clean up names and comments.')] }
] };
