// English week 7 — the intensive hour (weeks 1–12 are 3 hours a day): pronunciation, listening, speaking and
// writing drills on the day's topic. Merged into the week by tools/build_weeks.js.
const B = (ar, en) => ({ ar, en });
const L = (h, p, ex) => ({ h, p, ex });
const W = (t, ar, en, ex) => ({ t, m: B(ar, en), ex });
const Q = (q, o, a, why) => ({ q, o, a, why });
module.exports = { days: [
  { learn: [L(B('أشهر 20 past participle في الشغل', 'The 20 most used past participles at work'),
      B('محتاجهم للـ present perfect والـ passive: done، made، written، sent، built، run، set، found، given، taken، seen، broken، chosen، shown، known، begun، forgotten، hidden، thrown، understood. وفي الكلام بنختصر: `I\'ve`، `she\'s`، `we haven\'t`.',
        'You need them for the present perfect and the passive: done, made, written, sent, built, run, set, found, given, taken, seen, broken, chosen, shown, known, begun, forgotten, hidden, thrown, understood. In speech we contract: `I\'ve`, `she\'s`, `we haven\'t`.'),
      'I\'ve sent the invoice.  She\'s written the docs.\nWe haven\'t found the bug yet.  The build is broken.')],
    practice: [B('اعمل بطاقات للـ 20 (فعل ← ماضي ← past participle) وراجعها بالمراجعة المتباعدة.', 'Make cards for the 20 (verb → past → past participle) and review them with spaced repetition.'),
      B('قول 10 جمل I\'ve … عن شغلك الأسبوع ده بالاختصار.', 'Say 10 I\'ve … sentences about your work this week, contracted.')],
    words: [W('past participle', 'التصريف التالت للفعل (done، written)', 'the third form of a verb (done, written)', 'written is the past participle of write.'),
      W('contracted form', 'الشكل المختصر زي I\'ve وhasn\'t', 'the short form like I\'ve and hasn\'t', 'Use the contracted form in speech.')],
    quiz: [Q(B('الصح:', 'Correct:'), ['I\'ve written the tests.', 'I\'ve wrote the tests.', 'I\'ve write the tests.'], 0, B('have + past participle.', 'have + past participle.'))] },
  { learn: [L(B('كلمات الوقت مع كل زمن', 'Time words with each tense'),
      B('كلمات بتختار الزمن عنك: **ماضي بسيط** مع وقت خلص: `yesterday`، `last week`، `in May`، `two days ago`. **present perfect** مع وقت لسه مفتوح: `so far`، `lately`، `recently`، `this week`، `since Monday`، `ever`، `yet`. `I fixed it yesterday` بس `I\'ve fixed three bugs so far`.',
        'Some words choose the tense for you: **past simple** with finished time: `yesterday`, `last week`, `in May`, `two days ago`. **Present perfect** with time still open: `so far`, `lately`, `recently`, `this week`, `since Monday`, `ever`, `yet`. `I fixed it yesterday` but `I\'ve fixed three bugs so far`.'),
      'I deployed it two days ago.        (finished time → past)\nWe\'ve had three outages this month. (open time → present perfect)\nHave you used n8n lately?')],
    practice: [B('اكتب 6 جمل نصهم بكلمات وقت مقفول ونصهم مفتوح.', 'Write 6 sentences, half with finished time words and half with open ones.'),
      B('اسمع اجتماع أو بودكاست تقني ولاحظ 5 جمل present perfect.', 'Listen to a tech meeting or podcast and notice 5 present perfect sentences.')],
    words: [W('so far', 'لحد دلوقتي', 'up to now', 'So far we\'ve migrated 40 workflows.'),
      W('lately', 'الفترة الأخيرة', 'in the recent period', 'Have you had any errors lately?')],
    quiz: [Q(B('الصح:', 'Correct:'), ['I\'ve finished two tasks so far.', 'I finished two tasks so far.', 'I\'ve finished two tasks yesterday.'], 0, B('so far = وقت مفتوح.', 'so far = open time.'))] },
  { learn: [L(B('for وsince', 'for and since'),
      B('مع الـ present perfect (continuous): `for` + **مدة** (`for two hours`، `for three weeks`). `since` + **نقطة بداية** (`since 9 a.m.`، `since Monday`، `since we moved to Docker`). غلطة عربي شائعة: `I am working here since 2024` ← الصح `I have been working here since 2024`.',
        'With the present perfect (continuous): `for` + **a length of time** (`for two hours`, `for three weeks`). `since` + **a starting point** (`since 9 a.m.`, `since Monday`, `since we moved to Docker`). A common mistake for Arabic speakers: `I am working here since 2024` → correct: `I have been working here since 2024`.'),
      'The server has been down for twenty minutes.\nI\'ve been working on this bug since lunch.\n✗ I am learning n8n since March. ✓ I have been learning n8n since March.')],
    practice: [B('اكتب 8 جمل عن حاجات شغالة دلوقتي بـ for وsince.', 'Write 8 sentences about ongoing things with for and since.'),
      B('عرّف نفسك في مقابلة: من إمتى بتتعلم/بتشتغل في كل حاجة.', 'Introduce yourself as in an interview: how long you have been learning/working on each thing.')],
    words: [W('ongoing', 'لسه شغال ومخلصش', 'still happening, not finished', 'The migration is ongoing.'),
      W('starting point', 'الوقت اللي حاجة بدأت فيه', 'the time something began', 'since needs a starting point.')],
    quiz: [Q(B('«… since three hours» غلط لأن:', '«… since three hours» is wrong because:'), ['three hours is a length → use for', 'since needs -ing', 'hours is uncountable'], 0, B('مدة = for.', 'A length = for.'))] },
  { learn: [L(B('just وrecently وby now', 'just, recently and by now'),
      B('`just` = حالًا، من شوية صغيرة: `I\'ve just pushed the fix.` `recently` = في الفترة القريبة: `We\'ve recently moved to n8n Cloud.` `by now` = المفروض يكون حصل: `The email should have arrived by now.` ومكان just وalready بين have والفعل.',
        '`just` = a moment ago: `I\'ve just pushed the fix.` `recently` = in the near past: `We\'ve recently moved to n8n Cloud.` `by now` = it should have happened: `The email should have arrived by now.` just and already go between have and the verb.'),
      'I\'ve just restarted the server — try again now.\nWe\'ve recently added Telegram alerts.\nThe backup should have finished by now. Let me check.')],
    practice: [B('اكتب 5 رسايل Slack قصيرة فيها just وrecently وby now.', 'Write 5 short Slack messages using just, recently and by now.'),
      B('قولها بصوت عالي بالاختصار (I\'ve just…).', 'Say them aloud contracted (I\'ve just…).')],
    words: [W('recently', 'من فترة قريبة', 'not long ago', 'We\'ve recently updated the API.'),
      W('by now', 'لحد اللحظة دي (المفروض)', 'before this moment (as expected)', 'It should be done by now.')],
    quiz: [Q(B('مكان just الصح:', 'Where just goes:'), ['I\'ve just sent it.', 'I\'ve sent just it.', 'Just I\'ve sent it.'], 0, B('بين have والفعل.', 'Between have and the verb.'))] },
  { learn: [L(B('تقرير التقدم الأسبوعي', 'The weekly progress report'),
      B('هيكل بسيط: **Status** (`on track` / `at risk` / `behind schedule`)، **Done** (present perfect: `We\'ve finished…`)، **In progress** (`We\'re working on…`)، **Next** (`Next week we\'ll…`)، **Risks/needs** (`We need … by Thursday`). جمل قصيرة، أرقام، ومن غير مبالغة.',
        'A simple structure: **Status** (`on track` / `at risk` / `behind schedule`), **Done** (present perfect: `We\'ve finished…`), **In progress** (`We\'re working on…`), **Next** (`Next week we\'ll…`), **Risks/needs** (`We need … by Thursday`). Short sentences, numbers, no exaggeration.'),
      'Status: on track.\nDone: We\'ve connected the shop to the sheet and tested 50 orders.\nIn progress: We\'re building the invoice emails.\nNext: We\'ll add WhatsApp alerts.  Needs: the WhatsApp API access by Thursday.')],
    practice: [B('اكتب تقرير تقدم لمشروع الشهر بالهيكل ده.', 'Write a progress report for the month project with this structure.'),
      B('قوله في دقيقة كأنك في مكالمة مع عميل.', 'Say it in one minute as if on a call with a client.')],
    words: [W('on track', 'ماشي حسب الخطة', 'going according to plan', 'The project is on track for May.'),
      W('behind schedule', 'متأخر عن الخطة', 'later than planned', 'We\'re two days behind schedule.')],
    quiz: [Q(B('في الجزء «Done» تستخدم:', 'In the «Done» part you use:'), ['We\'ve finished…', 'We will finish…', 'We finishing…'], 0, B('present perfect للنتيجة.', 'present perfect for results.'))] },
  { review: [B('⚡ الـ past participles، وكلمات الوقت مع كل زمن، وfor وsince.', '⚡ Past participles, time words with each tense, and for and since.'),
      B('⚡ just وrecently وby now، وتقرير التقدم: ابعت تقرير حقيقي عن أسبوعك.', '⚡ just, recently and by now, and the progress report: send a real report about your week.')] }
] };
