// English week 9 — the intensive hour (weeks 1–12 are 3 hours a day): pronunciation, listening, speaking and
// writing drills on the day's topic. Merged into the week by tools/build_weeks.js.
const B = (ar, en) => ({ ar, en });
const L = (h, p, ex) => ({ h, p, ex });
const W = (t, ar, en, ex) => ({ t, m: B(ar, en), ex });
const Q = (q, o, a, why) => ({ q, o, a, why });
module.exports = { days: [
  { learn: [L(B('أوامر Git بالكلام', 'Git commands in speech'),
      B('في المكالمات بنقول: `pull the latest changes`، `create a branch off main`، `push your branch`، `open a PR`، `rebase onto main` (تحط تغييراتك فوق آخر main)، `squash the commits` (تجمعهم في واحد)، `resolve the merge conflict`، `revert the commit` (تلغيه بـ commit عكسه).',
        'On calls we say: `pull the latest changes`, `create a branch off main`, `push your branch`, `open a PR`, `rebase onto main` (put your changes on top of the latest main), `squash the commits` (combine them into one), `resolve the merge conflict`, `revert the commit` (undo it with an opposite commit).'),
      '"Could you rebase onto main and squash your commits before I merge?"\n"There\'s a merge conflict in config.json — I\'ll resolve it."')],
    practice: [B('اكتب 8 جمل بالأفعال دي عن مواقف حقيقية في Git.', 'Write 8 sentences with these verbs about real Git situations.'),
      B('اشرح لصاحبك بصوت عالي الفرق بين merge وrebase في 30 ثانية.', 'Explain aloud to a friend the difference between merge and rebase in 30 seconds.')],
    words: [W('rebase', 'تنقل تغييراتك فوق آخر نسخة من فرع تاني', 'to move your changes on top of the latest version of another branch', 'Rebase onto main before you open the PR.'),
      W('squash', 'تجمع كذا commit في commit واحد', 'to combine several commits into one', 'Squash the fix-up commits.')],
    quiz: [Q(B('«squash the commits» معناها:', '«squash the commits» means:'), ['combine them into one', 'delete them', 'push them'], 0, B('commit واحد نضيف.', 'One clean commit.'))] },
  { learn: [L(B('جسم الـ commit: ليه مش إيه', 'The commit body: why, not what'),
      B('السطر الأول (أقل من 50 حرف، أمر) بيقول **إيه**. الجسم بعد سطر فاضي بيقول **ليه** وأي تأثير: `Users on mobile could not submit the form because…`. استخدم `so that`، `because`، `previously…, now…`. والـ diff بيقول إيه اللي اتغير بالتفصيل، فمتعيدوش.',
        'The first line (under 50 characters, imperative) says **what**. The body, after a blank line, says **why** and any impact: `Users on mobile could not submit the form because…`. Use `so that`, `because`, `previously…, now…`. The diff already shows the details, so do not repeat it.'),
      'Fix booking form on mobile\n\nPreviously the submit button was hidden behind the keyboard on small\nscreens, so users could not book. Now the form scrolls the button into\nview when the keyboard opens.')],
    practice: [B('اكتب جسم commit لآخر 3 تغييرات مهمة عملتها، كل واحد 2–3 سطور.', 'Write a commit body for your last 3 important changes, 2–3 lines each.'),
      B('اقرا commits في مشروع مفتوح المصدر كبير ولاحظ إزاي بيكتبوا الجسم.', 'Read commits in a big open-source project and notice how they write the body.')],
    words: [W('commit body', 'الجزء بعد السطر الأول اللي بيشرح ليه', 'the part after the first line that explains why', 'Explain the reason in the commit body.'),
      W('previously', 'قبل كده', 'before now', 'Previously the job ran twice.')],
    quiz: [Q(B('جسم الـ commit المفروض يشرح:', 'The commit body should explain:'), ['why the change was made', 'every line changed', 'your name'], 0, B('الـ diff بيوري إيه.', 'The diff shows what.'))] },
  { learn: [L(B('لغة مراجعة الكود', 'Code review language'),
      B('المراجعة باحترام: اسأل بدل ما تأمر (`What do you think about…?`، `Could we…?`)، قول السبب، وفرّق بين المهم والذوق: `nit:` (nitpick، حاجة صغيرة اختيارية)، `blocking:` (لازم قبل الدمج). والرد على المراجعة: `Good catch, fixed.`، `I kept it because…`، `Done in 3f2a1c.`',
        'Review with respect: ask rather than order (`What do you think about…?`, `Could we…?`), give the reason, and separate what matters from taste: `nit:` (a nitpick, small and optional), `blocking:` (must be fixed before merging). Replying to a review: `Good catch, fixed.`, `I kept it because…`, `Done in 3f2a1c.`'),
      'nit: maybe rename `d` to `dueDate` for clarity?\nblocking: this logs the API key — could we mask it?\nReply: Good catch, fixed in 3f2a1c. I kept the loop because the list is tiny.')],
    practice: [B('راجع PR (حقيقي أو كود قديم ليك) واكتب 5 تعليقات: 3 nit و2 blocking.', 'Review a PR (real or your old code) and write 5 comments: 3 nits and 2 blocking.'),
      B('اكتب 3 ردود مهذبة على تعليقات مراجعة، واحد منهم بتختلف فيه.', 'Write 3 polite replies to review comments, one of them disagreeing.')],
    words: [W('nitpick', 'ملاحظة صغيرة جدًا مش ضرورية', 'a very small, optional remark', 'This is just a nitpick, feel free to ignore it.'),
      W('reviewer', 'الشخص اللي بيراجع الكود', 'the person who reviews the code', 'Add two reviewers to the PR.')],
    quiz: [Q(B('تعليق «nit:» معناه:', 'A «nit:» comment means:'), ['small and optional', 'must fix before merging', 'the code is broken'], 0, B('nitpick.', 'A nitpick.'))] },
  { learn: [L(B('حالات الـ PR', 'The states of a PR'),
      B('`draft PR` (لسه بشتغل، مش جاهز للمراجعة)، `ready for review`، `changes requested` (المراجع طلب تعديلات)، `approved`، `merged`، `closed`. وجمل: `I\'ve marked it ready for review.` `I\'ve addressed all comments.` `Could you take another look?`',
        '`draft PR` (still working, not ready for review), `ready for review`, `changes requested` (the reviewer asked for changes), `approved`, `merged`, `closed`. Phrases: `I\'ve marked it ready for review.` `I\'ve addressed all comments.` `Could you take another look?`'),
      'Draft → Ready for review → Changes requested → (fixes) → Approved → Merged\n"I\'ve addressed all your comments — could you take another look?"')],
    practice: [B('افتح draft PR في مشروعك على GitHub، وحوّله لـ ready، واكتب رسالة للمراجع.', 'Open a draft PR in your project on GitHub, mark it ready, and write a message to the reviewer.'),
      B('اكتب 4 رسايل لكل مرحلة من مراحل الـ PR.', 'Write 4 messages, one for each stage of a PR.')],
    words: [W('draft pr', 'PR لسه مش جاهز للمراجعة', 'a PR not yet ready for review', 'Open a draft PR to share early work.'),
      W('requested changes', 'تعديلات المراجع طلبها قبل الموافقة', 'edits a reviewer asked for before approving', 'I\'ve made the requested changes.')],
    quiz: [Q(B('«I\'ve addressed all comments» معناها:', '«I\'ve addressed all comments» means:'), ['I\'ve handled every comment', 'I\'ve read the address', 'I\'ve deleted the comments'], 0, B('address = تتعامل مع.', 'address = deal with.'))] },
  { learn: [L(B('وصف الاختبارات في الـ PR', 'Describing tests in a PR'),
      B('قسم **How to test** بيوفّر وقت المراجع: الخطوات بصيغة الأمر، والنتيجة المتوقعة. وقول اللي عملته: `I added unit tests for…`، `Test coverage went from 60% to 75%.`، `I tested it manually with…`، `Not tested: …` (بصراحة).',
        'A **How to test** section saves the reviewer time: imperative steps and the expected result. And say what you did: `I added unit tests for…`, `Test coverage went from 60% to 75%.`, `I tested it manually with…`, `Not tested: …` (honestly).'),
      '## How to test\n1. Run `npm test`. All 48 tests should pass.\n2. Send a booking with an invalid phone. You should get a 422.\nNot tested: the WhatsApp channel (no test account yet).')],
    practice: [B('اكتب قسم How to test لـ PR من مشروعك.', 'Write a How to test section for a PR in your project.'),
      B('قيس الـ coverage لو أداتك بتدعمها، واكتب جملة عنها.', 'Measure coverage if your tool supports it, and write a sentence about it.')],
    words: [W('test coverage', 'نسبة الكود اللي الاختبارات بتغطيه', 'the share of the code the tests run', 'Test coverage is now 75%.'),
      W('manually', 'بإيدك مش آليًا', 'by hand, not automatically', 'I tested the email manually.')],
    quiz: [Q(B('«Not tested: …» في الـ PR:', '«Not tested: …» in a PR is:'), ['honest and helpful', 'a mistake to hide', 'not allowed'], 0, B('المراجع يعرف المخاطرة.', 'The reviewer knows the risk.'))] },
  { review: [B('⚡ أوامر Git بالكلام، وجسم الـ commit، ولغة المراجعة.', '⚡ Git commands in speech, the commit body, and review language.'),
      B('⚡ حالات الـ PR، وقسم How to test: افتح PR كامل في مشروعك بالإنجليزي.', '⚡ PR states and the How to test section: open a complete PR in English in your project.')] }
] };
