// English week 10 — the intensive hour (weeks 1–12 are 3 hours a day): pronunciation, listening, speaking and
// writing drills on the day's topic. Merged into the week by tools/build_weeks.js.
const B = (ar, en) => ({ ar, en });
const L = (h, p, ex) => ({ h, p, ex });
const W = (t, ar, en, ex) => ({ t, m: B(ar, en), ex });
const Q = (q, o, a, why) => ({ q, o, a, why });
module.exports = { days: [
  { learn: [L(B('العناوين والـ badges في الـ README', 'Headings and badges in a README'),
      B('العناوين بتبدأ بكلمة واضحة ومن غير نقطة في الآخر: `Installation`، `Usage`، `Configuration`. الأمريكان بيكتبوا Title Case (`Getting Started`) وكتير من المشاريع الحديثة Sentence case (`Getting started`) — اختار واحد والتزم. والـ badges (صور صغيرة فوق) بتقول حالة الاختبارات والرخصة والإصدار.',
        'Headings start with a clear word and have no full stop: `Installation`, `Usage`, `Configuration`. Some write Title Case (`Getting Started`) and many modern projects use Sentence case (`Getting started`) — pick one and stick to it. Badges (small images at the top) show the test status, licence and version.'),
      '# Booking Bot\n![tests](badge.svg) ![license: MIT](badge2.svg)\n## Getting started\n## Usage\n## Configuration')],
    practice: [B('راجع عناوين README مشروعك ووحّد شكلها.', 'Review your README headings and make their style consistent.'),
      B('ضيف badge لحالة الاختبارات من GitHub Actions.', 'Add a badge for the test status from GitHub Actions.')],
    words: [W('badge', 'صورة صغيرة في الـ README بتعرض حالة', 'a small image in a README showing a status', 'The badge shows the tests are passing.'),
      W('heading', 'عنوان قسم', 'a section title', 'Use a heading for each section.')],
    quiz: [Q(B('العنوان الصح:', 'The correct heading:'), ['## Installation', '## installation.', '## INSTALLATION!!'], 0, B('كلمة واضحة ومن غير نقطة.', 'A clear word, no full stop.'))] },
  { learn: [L(B('علامات الترقيم في الكتابة التقنية', 'Punctuation in technical writing'),
      B('`:` قبل قايمة أو مثال (`You need three things:`). `;` بين جملتين مرتبطين (`The job failed; we retried it.`). الـ em dash `—` لتوضيح جانبي. الـ Oxford comma قبل and في قايمة: `Sheets, Gmail, and Telegram` (بتمنع اللبس). ومتحطش مسافة قبل `:` أو `?` (غلطة شائعة من العربي والفرنساوي).',
        '`:` before a list or example (`You need three things:`). `;` between two linked sentences (`The job failed; we retried it.`). The em dash `—` for a side note. The Oxford comma before and in a list: `Sheets, Gmail, and Telegram` (it avoids confusion). And no space before `:` or `?` (a common habit from Arabic and French).'),
      '✗ You need : Node , Docker and n8n .\n✓ You need: Node, Docker, and n8n.\n✓ The API is free — but it is limited to 100 calls a day.')],
    practice: [B('صلّح الترقيم في 3 فقرات كتبتها قبل كده بالإنجليزي.', 'Fix the punctuation in 3 paragraphs you wrote in English before.'),
      B('اكتب فقرة فيها : و; و— صح.', 'Write a paragraph that uses :, ; and — correctly.')],
    words: [W('semicolon', 'العلامة ; بين جملتين مرتبطين', 'the ; mark between two linked sentences', 'Use a semicolon to join the two ideas.'),
      W('oxford comma', 'الفاصلة قبل and في آخر قايمة', 'the comma before and at the end of a list', 'With the Oxford comma: red, white, and blue.')],
    quiz: [Q(B('الصح:', 'Correct:'), ['Install it: npm install.', 'Install it : npm install .', 'Install it ;npm install'], 0, B('من غير مسافة قبل :.', 'No space before :.'))] },
  { learn: [L(B('أمثلة الاستخدام: inline وcode blocks', 'Usage examples: inline and code blocks'),
      B('اسم ملف أو أمر جوه جملة يتكتب **inline code** بعلامة `` ` `` واحدة: «Edit `config.json`». الأمر الكامل أو الكود يتحط في block بتلات علامات ومعاه اسم اللغة. وقبل كل block جملة بتقول هيعمل إيه، وبعده النتيجة المتوقعة.',
        'A file name or command inside a sentence goes in **inline code** with one backtick: «Edit `config.json`». A full command or code goes in a block with three backticks and the language name. Before each block, a sentence says what it does; after it, the expected result.'),
      'Start the server in development mode:\n```bash\nnpm run dev\n```\nYou should see `Listening on port 5678`.')],
    practice: [B('اكتب قسم Usage لمشروعك فيه 3 أمثلة بالشكل ده (جملة، block، نتيجة).', 'Write a Usage section for your project with 3 examples in this form (sentence, block, result).'),
      B('راجع الـ README: أي اسم ملف أو أمر مش في inline code؟', 'Review the README: any file name or command not in inline code?')],
    words: [W('inline code', 'كود صغير جوه الجملة بين علامتين `', 'short code inside a sentence between backticks', 'Put file names in inline code.'),
      W('expected output', 'النتيجة اللي المفروض تظهر', 'the result that should appear', 'Show the expected output after each command.')],
    quiz: [Q(B('بعد الأمر في الـ README كويس تكتب:', 'After a command in a README it helps to write:'), ['the expected output', 'your phone number', 'nothing'], 0, B('القارئ يتأكد إنه نجح.', 'The reader can check it worked.'))] },
  { learn: [L(B('شيل الكلام الزيادة', 'Cut the extra words'),
      B('عبارات طويلة ليها بديل قصير: `in order to` ← `to`، `at this point in time` ← `now`، `due to the fact that` ← `because`، `is able to` ← `can`، `make a decision` ← `decide`، `it is important to note that` ← (امسحها). والكلام المكرر (redundant): `past history`، `end result`، `free gift`.',
        'Long phrases have short versions: `in order to` → `to`, `at this point in time` → `now`, `due to the fact that` → `because`, `is able to` → `can`, `make a decision` → `decide`, `it is important to note that` → (delete it). And redundant pairs: `past history`, `end result`, `free gift`.'),
      '✗ In order to be able to run the bot, it is important to note that you need a token.\n✓ To run the bot, you need a token.')],
    practice: [B('اختصر 3 فقرات من التوثيق بتاعك 30% من غير ما يضيع معنى.', 'Shorten 3 paragraphs of your docs by 30% without losing meaning.'),
      B('اعمل قايمة شخصية بـ 10 عبارات طويلة بتكتبها وبدايلها.', 'Make a personal list of 10 long phrases you tend to write and their short versions.')],
    words: [W('redundant', 'زيادة مالهاش لازمة لأنها متكررة', 'unnecessary because it repeats something', '"Past history" is redundant.'),
      W('plain language', 'كلام بسيط واضح من غير تعقيد', 'simple, clear words with no complexity', 'Write the guide in plain language.')],
    quiz: [Q(B('أقصر بديل لـ «due to the fact that»:', 'The shortest version of «due to the fact that»:'), ['because', 'owing to the fact that', 'in view of the fact'], 0, B('كلمة واحدة.', 'One word.'))] },
  { learn: [L(B('alt text والتعليقات على الصور', 'Alt text and captions'),
      B('كل صورة في التوثيق ليها **alt text** (للي بيستخدموا قارئ شاشة ولو الصورة ماظهرتش): يوصف المعلومة مش الشكل — `Workflow: Webhook → IF → Google Sheets` أحسن من `screenshot`. والـ caption تحت الصورة بيقول القارئ يبص على إيه: `The red arrow shows the error output.`',
        'Every image in docs needs **alt text** (for screen-reader users and when the image fails to load): describe the information, not the look — `Workflow: Webhook → IF → Google Sheets` beats `screenshot`. A caption under the image tells readers what to look at: `The red arrow shows the error output.`'),
      '![Workflow: Webhook → Validate → Google Sheets → Telegram alert](flow.png)\n*The error output (bottom) sends a Telegram alert.*')],
    practice: [B('اكتب alt text وcaption لكل صورة في الـ README بتاعك.', 'Write alt text and a caption for every image in your README.'),
      B('اقفل الصور في المتصفح واقرا الـ README: لسه مفهوم؟', 'Turn off images in your browser and read the README: is it still clear?')],
    words: [W('alt text', 'وصف نصي للصورة', 'a text description of an image', 'Write alt text for every screenshot.'),
      W('caption', 'سطر تحت الصورة بيشرحها', 'a line under an image explaining it', 'The caption points to the red arrow.')],
    quiz: [Q(B('أحسن alt text:', 'The best alt text:'), ['Webhook → IF → Google Sheets workflow', 'image1.png', 'screenshot'], 0, B('بيوصف المعلومة.', 'It describes the information.'))] },
  { review: [B('⚡ العناوين والـ badges، والترقيم، وinline code والـ blocks.', '⚡ Headings and badges, punctuation, and inline code and blocks.'),
      B('⚡ شيل الكلام الزيادة، وalt text والـ captions: أعد كتابة README مشروعك كله.', '⚡ Cutting extra words, alt text and captions: rewrite your project’s whole README.')] }
] };
