// English week 11 — the intensive hour (weeks 1–12 are 3 hours a day): pronunciation, listening, speaking and
// writing drills on the day's topic. Merged into the week by tools/build_weeks.js.
const B = (ar, en) => ({ ar, en });
const L = (h, p, ex) => ({ h, p, ex });
const W = (t, ar, en, ex) => ({ t, m: B(ar, en), ex });
const Q = (q, o, a, why) => ({ q, o, a, why });
module.exports = { days: [
  { learn: [L(B('خطوات إعادة المشكلة', 'Repro steps'),
      B('الـ **repro steps** أهم جزء في بلاغ الخطأ: خطوات مرقّمة، كل خطوة فعل أمر واحد، بالقيم الحقيقية، من حالة بداية واضحة. `1. Log in as a viewer. 2. Open Settings. 3. Click Export.` وفي الآخر: `Reproducible: always / 3 out of 5 times`.',
        '**Repro steps** are the most important part of a bug report: numbered steps, one imperative action each, with real values, from a clear starting state. `1. Log in as a viewer. 2. Open Settings. 3. Click Export.` And at the end: `Reproducible: always / 3 out of 5 times`.'),
      'Starting state: a new workflow, n8n 1.x, Chrome.\n1. Add a Webhook node.\n2. Set the path to "orders/:id".\n3. Send GET /webhook/orders/12.\nReproducible: always.')],
    practice: [B('اكتب repro steps لمشكلة حصلتلك، وادّيها لحد يجرّبها من غير ما تشرح.', 'Write repro steps for a problem you had, and give them to someone to try without explaining.'),
      B('حوّل وصف مشكلة طويل (فقرة) لخطوات مرقّمة.', 'Turn a long problem description (a paragraph) into numbered steps.')],
    words: [W('repro steps', 'خطوات بتعيد المشكلة', 'steps that make the problem happen again', 'Add clear repro steps to the issue.'),
      W('reproducible', 'تقدر تخليها تحصل تاني', 'possible to make happen again', 'The bug is reproducible every time.')],
    quiz: [Q(B('خطوة repro كويسة:', 'A good repro step:'), ['Click Export.', 'Then I clicked some buttons and it broke.', 'Export.'], 0, B('فعل أمر واحد واضح.', 'One clear imperative action.'))] },
  { learn: [L(B('وصف البيئة والـ logs', 'Describing the environment and logs'),
      B('`Environment`: نظام التشغيل والإصدار، المتصفح، إصدار الأداة (`n8n 1.70, self-hosted in Docker`). والـ logs: الصق **جزء** مهم بس في code block، مش 500 سطر: `Relevant log lines:`. وامسح أي سر قبل ما تلصق (`[REDACTED]`).',
        '`Environment`: OS and version, browser, tool version (`n8n 1.70, self-hosted in Docker`). For logs, paste only the **relevant part** in a code block, not 500 lines: `Relevant log lines:`. Remove any secret before pasting (`[REDACTED]`).'),
      'Environment: Windows 11, Chrome 130, n8n 1.70 (Docker).\nRelevant log lines:\n```\nERROR 401 Unauthorized — token [REDACTED] expired\n```')],
    practice: [B('اكتب قسم Environment لجهازك وأدواتك.', 'Write an Environment section for your machine and tools.'),
      B('خُد log طويل واختار منه أهم 5 سطور، وامسح أي سر.', 'Take a long log, pick the 5 most relevant lines, and remove any secret.')],
    words: [W('redacted', 'جزء اتشال عشان سري', 'removed because it is secret', 'The API key is redacted in the log.'),
      W('relevant', 'ليه علاقة مباشرة بالموضوع', 'directly connected to the topic', 'Paste only the relevant lines.')],
    quiz: [Q(B('في الـ log فيه API key. تعمل:', 'The log contains an API key. You:'), ['replace it with [REDACTED]', 'paste it as is', 'delete the whole log'], 0, B('متنشرش أسرار.', 'Never publish secrets.'))] },
  { learn: [L(B('المتوقع مقابل اللي حصل', 'Expected versus actual'),
      B('جزئين منفصلين وواضحين: **Expected behaviour**: `The sheet should get one new row.` **Actual behaviour**: `The sheet gets two identical rows.` استخدم `should` في المتوقع والمضارع البسيط أو الماضي في اللي حصل. ولو فيه **workaround** مؤقت، اكتبه.',
        'Two separate, clear parts: **Expected behaviour**: `The sheet should get one new row.` **Actual behaviour**: `The sheet gets two identical rows.` Use `should` for expected and present or past simple for actual. If there is a temporary **workaround**, write it.'),
      'Expected: one confirmation email per booking.\nActual: two emails are sent when the user double-clicks Book.\nWorkaround: disable the button after the first click.')],
    practice: [B('اكتب expected/actual لـ 3 مشاكل في مشروعاتك.', 'Write expected/actual for 3 problems in your projects.'),
      B('اقرا 5 issues على GitHub لأداة بتستخدمها وشوف إزاي كاتبين الجزئين دول.', 'Read 5 GitHub issues for a tool you use and see how they write these two parts.')],
    words: [W('expected behaviour', 'اللي المفروض يحصل', 'what should happen', 'Describe the expected behaviour first.'),
      W('actual behaviour', 'اللي حصل فعلًا', 'what really happens', 'The actual behaviour is two emails.')],
    quiz: [Q(B('في «Expected» تستخدم غالبًا:', 'In «Expected» you usually use:'), ['should', 'did', 'was being'], 0, B('اللي المفروض يحصل.', 'What should happen.'))] },
  { learn: [L(B('الخطورة والتكرار', 'Severity and frequency'),
      B('`Severity`: `critical` (البيانات بتضيع أو النظام واقف)، `major`، `minor`، `cosmetic` (شكل بس). و`regression`: حاجة كانت شغالة وبطلت بعد تحديث — `This is a regression since v1.4.` والتكرار: `always`، `intermittent` (أحيانًا)، `flaky` للاختبارات اللي بتنجح وتفشل من غير سبب واضح.',
        '`Severity`: `critical` (data loss or the system is down), `major`, `minor`, `cosmetic` (looks only). A `regression` is something that used to work and broke after an update — `This is a regression since v1.4.` Frequency: `always`, `intermittent` (sometimes), and `flaky` for tests that pass and fail for no clear reason.'),
      'Severity: major — bookings are duplicated.\nFrequency: intermittent (about 1 in 10).\nRegression: worked in v1.3, broken since v1.4.')],
    practice: [B('صنّف 6 مشاكل (حقيقية أو متخيّلة) بالخطورة والتكرار.', 'Classify 6 problems (real or imagined) by severity and frequency.'),
      B('اكتب جملة regression لمشكلة ظهرت بعد تحديث.', 'Write a regression sentence for a problem that appeared after an update.')],
    words: [W('regression', 'حاجة كانت شغالة وبطّلت بعد تغيير', 'something that worked and broke after a change', 'The date bug is a regression.'),
      W('intermittent', 'بيحصل أحيانًا مش دايمًا', 'happening sometimes, not always', 'The timeout is intermittent.')],
    quiz: [Q(B('الزرار لونه غلط بس شغال:', 'The button has the wrong colour but works:'), ['cosmetic', 'critical', 'regression'], 0, B('شكل بس.', 'Looks only.'))] },
  { learn: [L(B('اشرح السبب الجذري', 'Explaining the root cause'),
      B('بعد ما تحل المشكلة، اكتب السبب الحقيقي مش العرَض: `The root cause was that the webhook was retried after a timeout, and we did not check the event id.` وبعدين `To prevent this, we…`. أداة «5 whys»: اسأل «ليه؟» لحد ما توصل لحاجة تقدر تصلّحها.',
        'After you fix it, write the real cause, not the symptom: `The root cause was that the webhook was retried after a timeout, and we did not check the event id.` Then `To prevent this, we…`. The «5 whys» tool: keep asking «why?» until you reach something you can fix.'),
      'Symptom: duplicate bookings.\nWhy? The webhook ran twice. Why? The service retried after 10 s.\nWhy? We replied after 15 s. → Root cause: slow reply + no duplicate check.\nFix: reply immediately and dedupe by event id.')],
    practice: [B('طبّق 5 whys على آخر عطل عندك واكتب السبب الجذري في جملتين.', 'Apply 5 whys to your last failure and write the root cause in two sentences.'),
      B('اكتب closing comment لـ issue: السبب والحل وإزاي اتأكدت.', 'Write a closing comment for an issue: the cause, the fix and how you checked.')],
    words: [W('root cause', 'السبب الحقيقي الأساسي للمشكلة', 'the real, underlying cause of a problem', 'We found the root cause in the retry logic.'),
      W('symptom', 'العلامة اللي بتشوفها مش السبب', 'the sign you see, not the cause', 'Duplicate rows were only a symptom.')],
    quiz: [Q(B('«duplicate rows» في المثال ده:', '«duplicate rows» in this example is:'), ['the symptom', 'the root cause', 'the fix'], 0, B('اللي بتشوفه.', 'What you see.'))] },
  { review: [B('⚡ repro steps، والبيئة والـ logs من غير أسرار، وexpected/actual.', '⚡ Repro steps, environment and logs without secrets, and expected/actual.'),
      B('⚡ الخطورة والتكرار والـ regression، والسبب الجذري: اكتب بلاغ خطأ كامل لأداة مفتوحة المصدر (من غير ما تبعته لو مش حقيقي).', '⚡ Severity, frequency and regressions, and root causes: write a complete bug report for an open-source tool (do not send it unless it is real).')] }
] };
