// English week 12 — the intensive hour (weeks 1–12 are 3 hours a day): pronunciation, listening, speaking and
// writing drills on the day's topic. Merged into the week by tools/build_weeks.js.
const B = (ar, en) => ({ ar, en });
const L = (h, p, ex) => ({ h, p, ex });
const W = (t, ar, en, ex) => ({ t, m: B(ar, en), ex });
const Q = (q, o, a, why) => ({ q, o, a, why });
module.exports = { days: [
  { learn: [L(B('التحية والختام حسب العلاقة', 'Greetings and closings by relationship'),
      B('**رسمي/أول مرة**: `Dear Ms Hassan,` … `Kind regards,` **شغل عادي**: `Hi Sara,` … `Best,` أو `Thanks,` **ودّي جدًا**: `Hey Omar,` … `Cheers,` ولو مش عارف الاسم: `Hello,` أو `Hi there,` (مش `Dear Sir/Madam` إلا في الرسمي جدًا). والـ CC للي محتاج يعرف، والـ BCC للقوايم عشان العناوين متظهرش لبعض.',
        '**Formal/first contact**: `Dear Ms Hassan,` … `Kind regards,` **Normal work**: `Hi Sara,` … `Best,` or `Thanks,` **Very friendly**: `Hey Omar,` … `Cheers,` If you do not know the name: `Hello,` or `Hi there,` (`Dear Sir/Madam` only when very formal). CC people who need to know, and BCC mailing lists so addresses stay hidden from each other.'),
      'Dear Mr Adel,            → Kind regards,\nHi Sara,                 → Best, / Thanks,\nHey team,                → Cheers,\nBCC: the 40 customers (so they don\'t see each other\'s emails)')],
    practice: [B('اكتب أول وآخر سطر لـ 5 إيميلات لأشخاص مختلفين (عميل جديد، مدير، زميل، فريق، شركة).', 'Write the first and last line of 5 emails to different people (new client, manager, colleague, team, company).'),
      B('قرر لـ 3 مواقف: To ولا CC ولا BCC؟', 'Decide for 3 situations: To, CC or BCC?')],
    words: [W('greeting', 'جملة التحية في أول الرسالة', 'the hello line at the start of a message', 'Use the person’s name in the greeting.'),
      W('bcc', 'نسخة مخفية: المستلمين مش بيشوفوا بعض', 'blind copy: recipients cannot see each other', 'Put the customer list in BCC.')],
    quiz: [Q(B('إيميل لـ 50 عميل مع بعض:', 'An email to 50 customers at once:'), ['put them in BCC', 'put them in CC', 'put them in To'], 0, B('عشان الخصوصية.', 'For privacy.'))] },
  { learn: [L(B('المتابعة ورد الغياب', 'Follow-ups and out-of-office replies'),
      B('متابعة لطيفة: `Just following up on my email from Monday about…` أو `I wanted to check if you had a chance to look at…` (مش `Did you see my email??`). ولو هتغيب، رد آلي: `I\'m out of office until 12 May with limited access to email. For urgent issues, please contact…`',
        'A kind follow-up: `Just following up on my email from Monday about…` or `I wanted to check if you had a chance to look at…` (not `Did you see my email??`). If you will be away, an automatic reply: `I\'m out of office until 12 May with limited access to email. For urgent issues, please contact…`'),
      'Hi Sara,\nJust following up on the proposal I sent on Monday.\nWould Thursday work for a short call?\nBest,\nAhmed')],
    practice: [B('اكتب متابعتين: واحدة بعد 3 أيام وواحدة بعد أسبوع (أخف وأقصر).', 'Write two follow-ups: one after 3 days and one after a week (lighter and shorter).'),
      B('اكتب رد out-of-office ليك وحطه في أداة إيميلك (من غير ما تفعّله).', 'Write your out-of-office reply and save it in your email tool (without turning it on).')],
    words: [W('out of office', 'بعيد عن الشغل لفترة (رد آلي)', 'away from work for a while (an auto-reply)', 'I\'ll set an out of office reply.'),
      W('following up', 'بتتابع على حاجة قلتها قبل كده', 'checking on something you raised before', 'Just following up on the invoice.')],
    quiz: [Q(B('أهذب متابعة:', 'The politest follow-up:'), ['Just following up on my email about the invoice.', 'Why didn\'t you answer?', 'Answer me please!!'], 0, B('هادية ومحددة.', 'Calm and specific.'))] },
  { learn: [L(B('الاعتذار والاختلاف بأدب', 'Apologising and disagreeing politely'),
      B('**اعتذار مهني**: اعترف، صلّح، امنع التكرار — `I\'m sorry for the delay. The report is attached, and I\'ve set a reminder so it doesn\'t happen again.` (مش اعتذار مبالغ فيه). **اختلاف**: `I see your point, but…`، `I\'m not sure that will work because…`، `Could we consider…?` ولو حاجة خارج صلاحيتك: `I\'ll escalate this to…`',
        '**A professional apology**: admit, fix, prevent — `I\'m sorry for the delay. The report is attached, and I\'ve set a reminder so it doesn\'t happen again.` (not an over-the-top apology). **Disagreeing**: `I see your point, but…`, `I\'m not sure that will work because…`, `Could we consider…?` And when something is above your authority: `I\'ll escalate this to…`'),
      'I see your point about adding more fields, but it would slow the form down.\nCould we consider adding them on a second page instead?\nIf we can\'t agree, I\'ll escalate it to the project manager.')],
    practice: [B('اكتب اعتذار عن تأخير تسليم بالتلات خطوات.', 'Write an apology for a late delivery using the three steps.'),
      B('اكتب رد بتختلف فيه مع عميل على طلب، وتقترح بديل.', 'Write a reply disagreeing with a client’s request and suggesting an alternative.')],
    words: [W('apology', 'اعتذار', 'a statement saying you are sorry', 'Keep the apology short and sincere.'),
      W('escalate', 'ترفع الموضوع لحد صلاحيته أعلى', 'to pass an issue to someone with more authority', 'Escalate it if the client is still unhappy.')],
    quiz: [Q(B('أحسن اعتذار مهني:', 'The best professional apology:'), ['Sorry for the delay — here it is, and I\'ve added a reminder.', 'I am extremely terribly sorry, forgive me.', 'Not my fault.'], 0, B('اعتراف + حل + منع تكرار.', 'Admit + fix + prevent.'))] },
  { learn: [L(B('الـ small talk في أول الاجتماع', 'Small talk at the start of a meeting'),
      B('أول دقيقة في مكالمة شغل فيها كلام خفيف: `How\'s your week going?`، `Did you have a good weekend?`، `Busy week?`. ردود قصيرة وترجع السؤال: `Pretty busy, but good, thanks. How about you?` وبعدين انتقل للشغل: `Shall we get started?`',
        'The first minute of a work call has light chat: `How\'s your week going?`, `Did you have a good weekend?`, `Busy week?`. Give short answers and return the question: `Pretty busy, but good, thanks. How about you?` Then move to work: `Shall we get started?`'),
      'A: How\'s your week going?\nB: Pretty busy, but good, thanks. How about yours?\nA: Same here! Shall we get started?')],
    practice: [B('اتدرّب على 5 بدايات مكالمات مع ردود، وسجّلهم بنغمة طبيعية.', 'Practise 5 call openings with replies, and record them in a natural tone.'),
      B('اكتب 3 جمل انتقال من الكلام الخفيف للشغل.', 'Write 3 phrases that move from small talk to work.')],
    words: [W('small talk', 'كلام خفيف قبل الشغل', 'light chat before the real topic', 'A little small talk makes calls friendlier.'),
      W('pleasantries', 'عبارات المجاملة العادية', 'polite everyday remarks', 'After the pleasantries, we discussed the budget.')],
    quiz: [Q(B('«How\'s your week going?» أنسب رد:', 'The best reply to «How\'s your week going?»:'), ['Pretty good, thanks. How about you?', 'My week is a period of seven days.', 'No.'], 0, B('قصير وترجّع السؤال.', 'Short, and return the question.'))] },
  { learn: [L(B('لغة المكالمات', 'Call language'),
      B('`Can you hear me okay?`، `You\'re breaking up.` (صوتك بيقطع)، `Sorry, could you say that again?`، `You\'re on mute.`، `Hold on a second, let me check.`، `Let me share my screen.`، `I\'ll send a summary after the call.` ولو مفهمتش: `Just to confirm, you mean…?`',
        '`Can you hear me okay?`, `You\'re breaking up.` (your sound keeps cutting), `Sorry, could you say that again?`, `You\'re on mute.`, `Hold on a second, let me check.`, `Let me share my screen.`, `I\'ll send a summary after the call.` If you did not understand: `Just to confirm, you mean…?`'),
      '"Sorry, you\'re breaking up — could you say that again?"\n"Hold on a second, let me check the logs."\n"Just to confirm: you need the report every Monday at nine?"')],
    practice: [B('اعمل role-play لمكالمة دعم 5 دقايق (مع صاحبك أو AI) واستخدم 6 جمل من دول.', 'Role-play a 5-minute support call (with a friend or an AI) using 6 of these phrases.'),
      B('اكتب إيميل ملخص بعد المكالمة: اللي اتفقنا عليه والخطوات الجاية.', 'Write a summary email after the call: what we agreed and the next steps.')],
    words: [W('hold on', 'استنى لحظة', 'wait a moment', 'Hold on, I\'m opening the file.'),
      W('breaking up', 'الصوت بيقطع في المكالمة', 'the sound keeps cutting out on a call', 'Sorry, you\'re breaking up.')],
    quiz: [Q(B('عشان تتأكد إنك فهمت صح:', 'To check you understood correctly:'), ['Just to confirm, you mean…?', 'What?', 'OK whatever.'], 0, B('بتعيد بكلامك.', 'Repeat it in your words.'))] },
  { review: [B('⚡ التحية والختام وCC/BCC، والمتابعة ورد الغياب.', '⚡ Greetings, closings and CC/BCC, follow-ups and out-of-office replies.'),
      B('⚡ الاعتذار والاختلاف والتصعيد، والـ small talk ولغة المكالمات: اعمل مكالمة تجريبية كاملة وابعت إيميل ملخص.', '⚡ Apologising, disagreeing and escalating, small talk and call language: do a full practice call and send a summary email.')] }
] };
