// Generated by tools/build_sw.js from tools/sw.template.js — do not edit.
/* The offline app. Pages are network-first (fresh when online, cached copy when offline); versioned
 * assets (?v=…) are cache-first since a new release changes their URL. Only this site's own files are
 * cached: accounts (Supabase), CDNs and other sites always go to the network. */
var VERSION = '202610041';
var CACHE = 'site-' + VERSION;
var FILES = [
 "./",
 "assets/css/site.css?v=202610041",
 "assets/favicon.svg",
 "assets/icons/icon-192.png",
 "assets/icons/icon-512.png",
 "assets/js/account.js?v=202610041",
 "assets/js/common-en.js?v=202610041",
 "assets/js/config.js?v=202610041",
 "assets/js/i18n.js?v=202610041",
 "assets/js/sections.js?v=202610041",
 "assets/js/site.js?v=202610041",
 "assets/js/ui.js?v=202610041",
 "assets/js/vendor/supabase.js?v=202610041",
 "assets/logo.svg",
 "content/pages.js?v=202610041",
 "english.html",
 "index.html",
 "js.html",
 "lab.html",
 "manifest.webmanifest",
 "n8n.html",
 "prompts.html",
 "python.html",
 "review.html",
 "run.html",
 "sheets.html",
 "speak.html"
];   // the shared shell, kept on install
var LAZY = [
 "assets/data/deck.js?v=202610041",
 "assets/data/search-index.js?v=202610041",
 "assets/js/code-app.js?v=202610041",
 "assets/js/english-app.js?v=202610041",
 "assets/js/english-data.js?v=202610041",
 "assets/js/english-en.js?v=202610041",
 "assets/js/journey.js?v=202610041",
 "assets/js/lab-expr.js?v=202610041",
 "assets/js/lab.js?v=202610041",
 "assets/js/n8n-app.js?v=202610041",
 "assets/js/n8n-data.js?v=202610041",
 "assets/js/n8n-en.js?v=202610041",
 "assets/js/prompts.js?v=202610041",
 "assets/js/pyrun.js?v=202610041",
 "assets/js/review.js?v=202610041",
 "assets/js/runhost.js?v=202610041",
 "assets/js/sandbox.js?v=202610041",
 "assets/js/speak.js?v=202610041",
 "assets/js/vendor/ts-fsrs.umd.js?v=202610041",
 "content/english/outline.js?v=202610041",
 "content/english/terms.js?v=202610041",
 "content/js/outline.js?v=202610041",
 "content/js/terms.js?v=202610041",
 "content/library/english.js?v=202610041",
 "content/library/js.js?v=202610041",
 "content/library/n8n.js?v=202610041",
 "content/library/python.js?v=202610041",
 "content/n8n/outline.js?v=202610041",
 "content/n8n/terms.js?v=202610041",
 "content/python/outline.js?v=202610041",
 "content/python/terms.js?v=202610041",
 "content/sections/js-ref.js?v=202610041",
 "content/sections/js.js?v=202610041",
 "content/sections/lab.js?v=202610041",
 "content/sections/prompts-automation.js?v=202610041",
 "content/sections/prompts-business.js?v=202610041",
 "content/sections/prompts-code.js?v=202610041",
 "content/sections/prompts-course.js?v=202610041",
 "content/sections/prompts-data.js?v=202610041",
 "content/sections/prompts-english.js?v=202610041",
 "content/sections/prompts.js?v=202610041",
 "content/sections/python-ref.js?v=202610041",
 "content/sections/python.js?v=202610041",
 "content/sections/review.js?v=202610041",
 "content/sections/sheets.js?v=202610041",
 "content/sections/speak.js?v=202610041"
];     // page data and scripts: kept when used, or all at once on «Download for offline»

self.addEventListener('install', function(e){
  e.waitUntil(caches.open(CACHE).then(function(c){ return c.addAll(FILES); }).then(function(){ return self.skipWaiting(); }));
});
self.addEventListener('activate', function(e){
  e.waitUntil(caches.keys().then(function(keys){
    return Promise.all(keys.filter(function(k){ return /^site-/.test(k) && k !== CACHE; }).map(function(k){ return caches.delete(k); }));
  }).then(function(){ return self.clients.claim(); }));
});
function put(req, res){
  if(res && res.ok && res.type === 'basic'){ var copy = res.clone(); caches.open(CACHE).then(function(c){ c.put(req, copy); }); }
  return res;
}
self.addEventListener('fetch', function(e){
  var req = e.request;
  if(req.method !== 'GET') return;
  var url = new URL(req.url);
  if(url.origin !== self.location.origin) return;
  if(req.mode === 'navigate' || /\.html$|\/$/.test(url.pathname)){
    e.respondWith(fetch(req).then(function(res){ return put(req, res); }).catch(function(){
      return caches.match(req, { ignoreSearch: true }).then(function(r){ return r || caches.match('index.html'); });
    }));
    return;
  }
  e.respondWith(caches.match(req).then(function(hit){
    return hit || fetch(req).then(function(res){ return put(req, res); });
  }));
});
// the review page asks for the whole site to be kept offline: every page's files plus the week files it sends
self.addEventListener('message', function(e){
  if(!e.data || e.data.type !== 'cache-all' || !e.data.urls) return;
  // only this site's own files (relative paths), never another origin
  var asked = [].concat(e.data.urls).filter(function(u){ return typeof u === 'string' && /^[\w-]+(\/[\w.-]+)*(\?v=\w+)?$/.test(u); });
  var urls = LAZY.concat(asked), done = 0, port = e.ports && e.ports[0];
  caches.open(CACHE).then(function(c){
    return Promise.all(urls.map(function(u){
      return c.match(u).then(function(hit){ return hit || c.add(u); }).catch(function(){}).then(function(){ done++; if(port) port.postMessage({ done: done, total: urls.length }); });
    }));
  }).then(function(){ if(port) port.postMessage({ done: urls.length, total: urls.length, end: true }); });
});
