// Week 14 — generated by tools/build_weeks.js from content/js/src/w14.js. Edit the source, not this file.
JOURNEY.week({
 "track": "js",
 "n": 14,
 "month": 4,
 "level": {
  "ar": "متوسط",
  "en": "Intermediate"
 },
 "title": {
  "ar": "fetch والـ APIs",
  "en": "fetch and APIs"
 },
 "goal": {
  "ar": "تكلّم أي API من جافاسكريبت: تجيب وتبعت JSON، وتفهم الـ status والـ headers والمصادقة والـ CORS، وتبني عميل API صغير بيتعامل مع الأخطاء والمهلة والحدود والصفحات — زي ما n8n بيعمل جوه HTTP Request node.",
  "en": "Talk to any API from JavaScript: get and send JSON, understand status codes, headers, auth and CORS, and build a small API client that handles errors, timeouts, limits and pages — just like n8n does inside the HTTP Request node."
 },
 "days": [
  {
   "d": 1,
   "title": {
    "ar": "fetch: أول طلب",
    "en": "fetch: the first request"
   },
   "goal": {
    "ar": "تجيب بيانات من API وتتأكد إن الرد سليم.",
    "en": "Get data from an API and check the reply is sound."
   },
   "learn": [
    {
     "h": {
      "ar": "الطلب والرد",
      "en": "Request and response"
     },
     "p": {
      "ar": "الـ **rest api** بيدّيك **endpoint** (رابط) لكل نوع بيانات: `/users/1`، `/orders?status=paid`. `fetch(url)` بيرجّع Promise بـ **Response** فيه `status` و`headers`، والجسم بتقراه بخطوة تانية: `await res.json()` (أو `.text()`). يعني خطوتين await.",
      "en": "A **rest api** gives you an **endpoint** (a URL) for each kind of data: `/users/1`, `/orders?status=paid`. `fetch(url)` returns a promise of a **Response** with `status` and `headers`, and you read the body in a second step: `await res.json()` (or `.text()`). So: two awaits."
     },
     "ex": "(async () => {\n  try {\n    const res = await fetch(\"https://jsonplaceholder.typicode.com/users/1\");\n    console.log(\"status\", res.status, res.headers.get(\"content-type\"));\n    const user = await res.json();\n    console.log(user.name, \"·\", user.email, \"·\", user.address.city);\n  } catch (err) {\n    console.log(\"failed:\", err.message);\n  }\n})();",
     "run": "js"
    },
    {
     "h": {
      "ar": "fetch مبيفشلش على 404!",
      "en": "fetch does not fail on 404!"
     },
     "p": {
      "ar": "أهم فخ: fetch بيرفض (reject) بس لو **مفيش رد خالص** (**network error**: مفيش نت، DNS، CORS). لو السيرفر رد 404 أو 500، fetch **بينجح** عادي! لازم تفحص `res.ok` (يعني status من 200 لـ 299) بنفسك وترمي خطأ.",
      "en": "The biggest trap: fetch rejects only when there is **no reply at all** (a **network error**: no internet, DNS, CORS). If the server answers 404 or 500, fetch **succeeds** as normal! You must check `res.ok` (status 200–299) yourself and throw."
     },
     "ex": "(async () => {\n  try {\n    const res = await fetch(\"https://jsonplaceholder.typicode.com/users/9999\");\n    console.log(\"fetch resolved anyway; status\", res.status, \"ok?\", res.ok);\n    if (!res.ok) throw new Error(`HTTP ${res.status} for /users/9999`);\n  } catch (err) {\n    console.log(\"failed:\", err.message);\n  }\n})();",
     "run": "js"
    },
    {
     "h": {
      "ar": "الأكواد اللي هتقابلها",
      "en": "The codes you will meet"
     },
     "p": {
      "ar": "**http status**: 2xx نجاح (200 تمام، 201 اتعمل، 204 مفيش جسم)؛ 3xx تحويل؛ 4xx غلطتك (400 بيانات غلط، 401 مش مسجّل، 403 ممنوع، 404 مش موجود، 409 تعارض، 422 تحقق فشل، 429 كتير قوي)؛ 5xx غلطة السيرفر (500، 502، 503). أول رقم بيقولك تعيد المحاولة ولا تصلّح طلبك.",
      "en": "**http status** codes: 2xx success (200 OK, 201 created, 204 no body); 3xx redirect; 4xx your mistake (400 bad data, 401 not signed in, 403 forbidden, 404 not found, 409 conflict, 422 validation failed, 429 too many); 5xx the server’s mistake (500, 502, 503). The first digit tells you whether to retry or fix your request."
     },
     "ex": "const advice = status =>\n  status < 300 ? \"use the data\" :\n  status === 429 || status >= 500 ? \"wait and retry\" :\n  status === 401 ? \"refresh the token\" :\n  \"fix the request (do not retry)\";\n[200, 201, 400, 401, 404, 422, 429, 503].forEach(s => console.log(s, \"→\", advice(s)));",
     "run": "js"
    }
   ],
   "practice": [
    {
     "ar": "هات /posts?userId=1 واطبع عناوين البوستات.",
     "en": "Get /posts?userId=1 and print the post titles."
    },
    {
     "ar": "اطلب رابط غلط وتأكد إن res.ok بيمسكه.",
     "en": "Request a wrong URL and make sure res.ok catches it."
    },
    {
     "ar": "افصل النت وشوف شكل الـ network error.",
     "en": "Turn off the internet and see what a network error looks like."
    },
    {
     "ar": "افتح Network في DevTools وشوف الطلب والـ headers.",
     "en": "Open Network in DevTools and look at the request and headers."
    }
   ],
   "words": [
    {
     "t": "rest api",
     "m": {
      "ar": "API بروابط لكل مورد وأفعال HTTP",
      "en": "an API with a URL per resource and HTTP verbs"
     },
     "ex": "The shop exposes a REST API."
    },
    {
     "t": "endpoint",
     "m": {
      "ar": "رابط محدد في الـ API",
      "en": "a specific URL in an API"
     },
     "ex": "The /orders endpoint lists orders."
    },
    {
     "t": "res.ok",
     "m": {
      "ar": "true لو الـ status من 200 لـ 299",
      "en": "true when the status is 200–299"
     },
     "ex": "Always check res.ok after fetch."
    },
    {
     "t": "response.json",
     "m": {
      "ar": "قراءة جسم الرد كـ JSON",
      "en": "reading the reply body as JSON"
     },
     "ex": "await response.json() returns an object."
    },
    {
     "t": "network error",
     "m": {
      "ar": "مفيش رد خالص من السيرفر",
      "en": "no reply from the server at all"
     },
     "ex": "fetch rejects only on a network error."
    },
    {
     "t": "http status",
     "m": {
      "ar": "رقم بيوصف نتيجة الطلب",
      "en": "a number describing the request result"
     },
     "ex": "Log the HTTP status with every failure."
    }
   ],
   "read": [
    {
     "t": "MDN: Using the Fetch API",
     "url": "https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch",
     "what": {
      "ar": "اقرا Making a request وChecking response status.",
      "en": "Read Making a request and Checking response status."
     }
    },
    {
     "t": "MDN: HTTP response status codes",
     "url": "https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status",
     "what": {
      "ar": "لف على الأكواد الشائعة.",
      "en": "Skim the common codes."
     }
    }
   ],
   "challenge": {
    "ar": "اعمل صفحة بتجيب 10 مستخدمين من JSONPlaceholder وتعرضهم في جدول (اسم، مدينة، شركة)، بمؤشر تحميل، ورسالة واضحة لو حصل خطأ شبكة أو status غلط.",
    "en": "Build a page that loads 10 users from JSONPlaceholder and shows them in a table (name, city, company), with a loading indicator and a clear message on a network error or a bad status."
   },
   "quiz": [
    {
     "q": {
      "ar": "السيرفر رد 404، fetch:",
      "en": "The server replied 404; fetch:"
     },
     "o": [
      {
       "ar": "بينجح وres.ok = false",
       "en": "resolves with res.ok = false"
      },
      {
       "ar": "بيرمي خطأ",
       "en": "throws"
      },
      {
       "ar": "بيرجع null",
       "en": "returns null"
      }
     ],
     "a": 0,
     "why": {
      "ar": "افحص res.ok.",
      "en": "Check res.ok."
     }
    },
    {
     "q": {
      "ar": "قراءة الجسم JSON:",
      "en": "Reading a JSON body:"
     },
     "o": [
      "await res.json()",
      "res.body",
      "JSON.parse(res)"
     ],
     "a": 0,
     "why": {
      "ar": "خطوة تانية.",
      "en": "A second step."
     }
    },
    {
     "q": {
      "ar": "401 معناها:",
      "en": "401 means:"
     },
     "o": [
      {
       "ar": "مش مسجّل/توكن غلط",
       "en": "not signed in / bad token"
      },
      {
       "ar": "السيرفر واقع",
       "en": "the server is down"
      },
      {
       "ar": "تمام",
       "en": "OK"
      }
     ],
     "a": 0,
     "why": {
      "ar": "مصادقة.",
      "en": "Authentication."
     }
    }
   ],
   "minutes": 120
  },
  {
   "d": 2,
   "title": {
    "ar": "إرسال البيانات",
    "en": "Sending data"
   },
   "goal": {
    "ar": "تبعت JSON وفورمز وparameters بالشكل الصح.",
    "en": "Send JSON, forms and parameters the right way."
   },
   "learn": [
    {
     "h": {
      "ar": "POST بـ JSON",
      "en": "POST with JSON"
     },
     "p": {
      "ar": "**post request** بيبعت بيانات: `method: \"POST\"`، وheader `Content-Type: application/json`، والجسم `JSON.stringify(data)`. ده بالظبط اللي بتعمله لما تبعت لـ webhook بتاع n8n. الرد غالبًا 201 ومعاه الكائن الجديد بـ id.",
      "en": "A **post request** sends data: `method: \"POST\"`, the header `Content-Type: application/json`, and the body `JSON.stringify(data)`. This is exactly what you do when sending to an n8n webhook. The reply is usually 201 with the new object and its id."
     },
     "ex": "(async () => {\n  try {\n    const res = await fetch(\"https://jsonplaceholder.typicode.com/posts\", {\n      method: \"POST\",\n      headers: { \"Content-Type\": \"application/json\" },\n      body: JSON.stringify({ title: \"New order #101\", body: \"2 notebooks\", userId: 7 }),\n    });\n    console.log(\"status\", res.status);           // 201 created\n    console.log(await res.json());               // the saved object with an id\n  } catch (err) { console.log(\"failed:\", err.message); }\n})();",
     "run": "js"
    },
    {
     "h": {
      "ar": "الـ query string",
      "en": "The query string"
     },
     "p": {
      "ar": "الفلاتر والبحث والصفحات بتتبعت في **query string** (`?status=paid&limit=20`). متركّبهاش بإيدك بـ `+` — النص العربي والمسافات والرموز لازم تتشفّر. **URLSearchParams** بيعمل ده صح، و`new URL()` بيبني الرابط كامل.",
      "en": "Filters, search and pages go in the **query string** (`?status=paid&limit=20`). Do not build it by hand with `+` — Arabic text, spaces and symbols must be encoded. **URLSearchParams** does this right, and `new URL()` builds the whole link."
     },
     "ex": "const url = new URL(\"https://dummyjson.com/products/search\");\nurl.search = new URLSearchParams({ q: \"phone case\", limit: 3, select: \"title,price\" });\nconsole.log(url.href);\nconsole.log(new URLSearchParams({ city: \"القاهرة\", note: \"a&b=c\" }).toString());\nconst back = new URL(\"https://x.test/?status=paid&page=2\").searchParams;\nconsole.log(back.get(\"status\"), Number(back.get(\"page\")) + 1);",
     "run": "js"
    },
    {
     "h": {
      "ar": "PUT وPATCH وDELETE",
      "en": "PUT, PATCH and DELETE"
     },
     "p": {
      "ar": "**put** = استبدل الكائن كله، **patch** = عدّل حقول بس، و**delete request** = امسح. PUT وDELETE **idempotent**: تكرارهم بنفس النتيجة؛ POST لأ (مرتين = طلبين). وللفورمز بملفات: `FormData` من غير Content-Type (المتصفح بيحطه بالـ boundary).",
      "en": "A **put** replaces the whole object, a **patch** changes some fields, and a **delete request** removes it. PUT and DELETE are **idempotent**: repeating them gives the same result; POST is not (twice = two orders). For forms with files: `FormData` without a Content-Type (the browser sets it with the boundary)."
     },
     "ex": "await fetch(`${BASE}/orders/101`, { method: \"PATCH\", headers: JSON_HEADERS, body: JSON.stringify({ status: \"shipped\" }) });\nawait fetch(`${BASE}/orders/101`, { method: \"DELETE\" });\n\nconst form = new FormData();\nform.append(\"orderId\", \"101\");\nform.append(\"invoice\", fileInput.files[0]);        // a file from <input type=\"file\">\nawait fetch(`${BASE}/invoices`, { method: \"POST\", body: form });   // no Content-Type header here",
     "lang": "js"
    }
   ],
   "practice": [
    {
     "ar": "ابعت POST لـ JSONPlaceholder واطبع الـ id.",
     "en": "Send a POST to JSONPlaceholder and print the id."
    },
    {
     "ar": "ابني رابط بحث فيه نص عربي بـ URLSearchParams.",
     "en": "Build a search URL with Arabic text using URLSearchParams."
    },
    {
     "ar": "اعمل PATCH لتغيير عنوان بوست.",
     "en": "Send a PATCH changing a post’s title."
    },
    {
     "ar": "ابعت فورم صغير لـ webhook n8n تجريبي.",
     "en": "Send a small form to a test n8n webhook."
    }
   ],
   "words": [
    {
     "t": "post request",
     "m": {
      "ar": "طلب بيبعت بيانات جديدة",
      "en": "a request sending new data"
     },
     "ex": "The form makes a POST request."
    },
    {
     "t": "content-type",
     "m": {
      "ar": "header بيقول نوع الجسم",
      "en": "a header saying the body’s type"
     },
     "ex": "Set Content-Type to application/json."
    },
    {
     "t": "query string",
     "m": {
      "ar": "الجزء بعد ? في الرابط",
      "en": "the part after ? in a URL"
     },
     "ex": "Put the filters in the query string."
    },
    {
     "t": "urlsearchparams",
     "m": {
      "ar": "أداة لبناء وقراءة الـ query string",
      "en": "a tool to build and read query strings"
     },
     "ex": "URLSearchParams encodes Arabic safely."
    },
    {
     "t": "put",
     "m": {
      "ar": "استبدال كائن كامل",
      "en": "replacing a whole object"
     },
     "ex": "PUT sends the full record."
    },
    {
     "t": "patch",
     "m": {
      "ar": "تعديل حقول محددة",
      "en": "changing some fields"
     },
     "ex": "PATCH only the status field."
    },
    {
     "t": "idempotent",
     "m": {
      "ar": "تكراره بيدّي نفس النتيجة",
      "en": "repeating it gives the same result"
     },
     "ex": "DELETE is idempotent; POST is not."
    }
   ],
   "read": [
    {
     "t": "MDN: URLSearchParams",
     "url": "https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams",
     "what": {
      "ar": "اقرا الأمثلة.",
      "en": "Read the examples."
     }
    },
    {
     "t": "JSONPlaceholder",
     "url": "https://jsonplaceholder.typicode.com/",
     "what": {
      "ar": "اقرا Guide: كل الأفعال.",
      "en": "Read the Guide: every verb."
     }
    }
   ],
   "challenge": {
    "ar": "اعمل فورم «طلب جديد» بيبعت JSON لـ JSONPlaceholder (أو webhook n8n)، يعطّل الزرار أثناء الإرسال، ويعرض رقم الطلب من الرد أو رسالة الخطأ.",
    "en": "Build a «new order» form that sends JSON to JSONPlaceholder (or an n8n webhook), disables the button while sending, and shows the order id from the reply or the error."
   },
   "quiz": [
    {
     "q": {
      "ar": "إرسال JSON محتاج:",
      "en": "Sending JSON needs:"
     },
     "o": [
      {
       "ar": "Content-Type وJSON.stringify",
       "en": "Content-Type and JSON.stringify"
      },
      {
       "ar": "كائن مباشرة",
       "en": "the object directly"
      },
      {
       "ar": "GET",
       "en": "GET"
      }
     ],
     "a": 0,
     "why": {
      "ar": "الجسم نص.",
      "en": "The body is text."
     }
    },
    {
     "q": {
      "ar": "نص عربي في رابط:",
      "en": "Arabic text in a URL:"
     },
     "o": [
      "URLSearchParams",
      {
       "ar": "+ عادي",
       "en": "plain +"
      },
      {
       "ar": "مينفعش",
       "en": "impossible"
      }
     ],
     "a": 0,
     "why": {
      "ar": "تشفير صح.",
      "en": "Correct encoding."
     }
    },
    {
     "q": {
      "ar": "مين مش idempotent؟",
      "en": "Which is not idempotent?"
     },
     "o": [
      "POST",
      "PUT",
      "DELETE"
     ],
     "a": 0,
     "why": {
      "ar": "مرتين = طلبين.",
      "en": "Twice = two orders."
     }
    }
   ],
   "minutes": 120
  },
  {
   "d": 3,
   "title": {
    "ar": "الـ headers والمصادقة والـ CORS",
    "en": "Headers, auth and CORS"
   },
   "goal": {
    "ar": "تبعت مفاتيح بأمان وتفهم أخطاء CORS.",
    "en": "Send keys safely and understand CORS errors."
   },
   "learn": [
    {
     "h": {
      "ar": "الـ headers والتوكن",
      "en": "Headers and tokens"
     },
     "p": {
      "ar": "الـ **request header** بيحمل معلومات عن الطلب: نوعه، لغته، والمصادقة. أشهرها `Authorization: Bearer <token>` (**bearer token**) أو `X-API-Key`. والـ **response header** بيرجّع معلومات زي `Retry-After` و`X-RateLimit-Remaining`.",
      "en": "A **request header** carries information about the request: its type, language and auth. The most common: `Authorization: Bearer <token>` (a **bearer token**) or `X-API-Key`. A **response header** returns information such as `Retry-After` and `X-RateLimit-Remaining`."
     },
     "ex": "(async () => {\n  try {\n    const res = await fetch(\"https://httpbin.org/headers\", {\n      headers: { Authorization: \"Bearer demo-token-not-real\", \"Accept-Language\": \"ar\" },\n    });\n    const { headers } = await res.json();          // httpbin echoes what it received\n    console.log(headers.Authorization, \"|\", headers[\"Accept-Language\"]);\n  } catch (err) { console.log(\"failed:\", err.message); }\n})();",
     "run": "js"
    },
    {
     "h": {
      "ar": "المفاتيح مكانها السيرفر",
      "en": "Keys belong on the server"
     },
     "p": {
      "ar": "أي **api key** في كود المتصفح **مكشوف** — أي حد يفتح DevTools ياخده. القاعدة: المفاتيح السرية في السيرفر أو n8n بس، والمتصفح يكلّم **proxy** بتاعك (webhook n8n أو API صغير) وهو اللي يضيف المفتاح. المفاتيح العامة (زي Supabase anon مع RLS) استثناء متصمم لكده.",
      "en": "Any **api key** in browser code is **exposed** — anyone opening DevTools can take it. The rule: secret keys live only on the server or in n8n, and the browser calls your **proxy** (an n8n webhook or a small API) which adds the key. Public keys (like Supabase anon with RLS) are an exception designed for this."
     },
     "ex": "browser ──POST /webhook/quote {product}──▶ n8n (holds the OpenAI/CRM key) ──▶ provider API\n        ◀────────── {price, text} ──────────────┘\n// the browser never sees the secret key",
     "lang": "text"
    },
    {
     "h": {
      "ar": "الـ CORS",
      "en": "CORS"
     },
     "p": {
      "ar": "المتصفح بيمنع صفحة على `site-a` تقرا رد من `api-b` إلا لو `api-b` قال إنه موافق بـ header `Access-Control-Allow-Origin`. ده **cors**. لو الطلب مش بسيط (JSON، headers خاصة) المتصفح بيبعت **preflight** (OPTIONS) الأول. الخطأ ده في المتصفح بس — نفس الطلب من Node أو n8n بيشتغل. والحل في السيرفر مش في الـ fetch.",
      "en": "The browser stops a page on `site-a` from reading a reply from `api-b` unless `api-b` says it agrees with the `Access-Control-Allow-Origin` header. That is **cors**. If the request is not simple (JSON, custom headers) the browser first sends a **preflight** (OPTIONS). The error happens only in browsers — the same request from Node or n8n works. The fix is on the server, not in fetch."
     },
     "ex": "// in the console: \"blocked by CORS policy: No 'Access-Control-Allow-Origin' header\"\n// ✗ mode: \"no-cors\" does not fix it — you get an empty, unreadable reply\n// ✓ the API (or your proxy) answers with:\n//   Access-Control-Allow-Origin: https://my-site.example\n//   Access-Control-Allow-Headers: Content-Type, Authorization",
     "lang": "js"
    }
   ],
   "practice": [
    {
     "ar": "ابعت header مخصوص لـ httpbin واتأكد إنه وصل.",
     "en": "Send a custom header to httpbin and confirm it arrived."
    },
    {
     "ar": "دوّر في كود قديم عندك على مفتاح في الواجهة وانقله لـ n8n.",
     "en": "Find a key in your old front-end code and move it to n8n."
    },
    {
     "ar": "اعمل طلب لـ API مش بيدعم CORS وشوف الخطأ في الكونسول.",
     "en": "Call an API without CORS support and read the console error."
    },
    {
     "ar": "شوف طلب preflight في Network.",
     "en": "Find a preflight request in the Network tab."
    }
   ],
   "words": [
    {
     "t": "request header",
     "m": {
      "ar": "معلومة مبعوتة مع الطلب",
      "en": "information sent with a request"
     },
     "ex": "Add the token as a request header."
    },
    {
     "t": "response header",
     "m": {
      "ar": "معلومة راجعة مع الرد",
      "en": "information returned with a reply"
     },
     "ex": "Read the Retry-After response header."
    },
    {
     "t": "bearer token",
     "m": {
      "ar": "توكن بيتبعت في Authorization",
      "en": "a token sent in Authorization"
     },
     "ex": "Send the bearer token on each call."
    },
    {
     "t": "api key",
     "m": {
      "ar": "مفتاح سري للدخول على API",
      "en": "a secret key for an API"
     },
     "ex": "Never ship an API key to the browser."
    },
    {
     "t": "proxy",
     "m": {
      "ar": "وسيط بيبعت الطلب بالنيابة عنك",
      "en": "a middleman sending the request for you"
     },
     "ex": "n8n acts as a proxy for the AI API."
    },
    {
     "t": "cors",
     "m": {
      "ar": "قواعد المتصفح للطلبات بين المواقع",
      "en": "browser rules for cross-site requests"
     },
     "ex": "The API must allow CORS for our site."
    },
    {
     "t": "preflight",
     "m": {
      "ar": "طلب OPTIONS قبل الطلب الحقيقي",
      "en": "an OPTIONS request before the real one"
     },
     "ex": "JSON requests trigger a preflight."
    }
   ],
   "read": [
    {
     "t": "MDN: Cross-Origin Resource Sharing (CORS)",
     "url": "https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/CORS",
     "what": {
      "ar": "اقرا Simple requests وPreflighted requests.",
      "en": "Read Simple requests and Preflighted requests."
     }
    },
    {
     "t": "MDN: HTTP overview",
     "url": "https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Overview",
     "what": {
      "ar": "اقرا HTTP messages.",
      "en": "Read HTTP messages."
     }
    }
   ],
   "challenge": {
    "ar": "اعمل workflow n8n بـ webhook بيستقبل سؤال من صفحتك، ويضيف المفتاح السري، ويكلّم API، ويرجّع الرد — مع CORS مضبوط لموقعك بس. الصفحة نفسها من غير أي مفتاح.",
    "en": "Build an n8n workflow with a webhook that receives a question from your page, adds the secret key, calls an API and returns the reply — with CORS set for your site only. The page itself holds no key."
   },
   "quiz": [
    {
     "q": {
      "ar": "مفتاح API سري في كود الصفحة:",
      "en": "A secret API key in page code:"
     },
     "o": [
      {
       "ar": "مكشوف لأي حد",
       "en": "is exposed to anyone"
      },
      {
       "ar": "آمن لو مخفي",
       "en": "is safe if hidden"
      },
      {
       "ar": "آمن بعد التصغير",
       "en": "is safe once minified"
      }
     ],
     "a": 0,
     "why": {
      "ar": "proxy.",
      "en": "Use a proxy."
     }
    },
    {
     "q": {
      "ar": "خطأ CORS بيتحل في:",
      "en": "A CORS error is fixed in:"
     },
     "o": [
      {
       "ar": "السيرفر",
       "en": "the server"
      },
      {
       "ar": "fetch بـ no-cors",
       "en": "fetch with no-cors"
      },
      {
       "ar": "CSS",
       "en": "CSS"
      }
     ],
     "a": 0,
     "why": {
      "ar": "Allow-Origin.",
      "en": "Allow-Origin."
     }
    },
    {
     "q": {
      "ar": "نفس الطلب من n8n:",
      "en": "The same request from n8n:"
     },
     "o": [
      {
       "ar": "مفيش CORS",
       "en": "has no CORS"
      },
      {
       "ar": "بيفشل برضه",
       "en": "fails too"
      },
      {
       "ar": "أبطأ",
       "en": "is slower"
      }
     ],
     "a": 0,
     "why": {
      "ar": "CORS في المتصفح بس.",
      "en": "CORS is browser-only."
     }
    }
   ],
   "minutes": 120
  },
  {
   "d": 4,
   "title": {
    "ar": "عميل API متين",
    "en": "A robust API client"
   },
   "goal": {
    "ar": "دالة واحدة لكل طلباتك بالأخطاء والمهلة والحدود.",
    "en": "One function for all your requests with errors, timeouts and limits."
   },
   "learn": [
    {
     "h": {
      "ar": "wrapper واحد",
      "en": "One wrapper"
     },
     "p": {
      "ar": "بدل ما تكرر نفس السطور في كل طلب، اعمل **api client** صغير: **base url**، headers ثابتة، مهلة، فحص `res.ok`، وقراءة JSON — وخطأ مخصوص **HttpError** فيه الـ status والجسم عشان اللي فوق يقرر.",
      "en": "Instead of repeating the same lines in every request, write a small **api client**: a **base url**, fixed headers, a timeout, a `res.ok` check and JSON reading — and a custom **HttpError** holding the status and body so the caller can decide."
     },
     "ex": "class HttpError extends Error {\n  constructor(status, body) { super(`HTTP ${status}`); this.status = status; this.body = body; }\n}\nfunction createClient(base, { token, timeout = 8000 } = {}) {\n  return async function api(path, { method = \"GET\", body, query } = {}) {\n    const url = new URL(path, base);\n    if (query) url.search = new URLSearchParams(query);\n    const res = await fetch(url, {\n      method,\n      headers: { Accept: \"application/json\", ...(body && { \"Content-Type\": \"application/json\" }), ...(token && { Authorization: `Bearer ${token}` }) },\n      body: body && JSON.stringify(body),\n      signal: AbortSignal.timeout(timeout),\n    });\n    const data = res.status === 204 ? null : await res.json().catch(() => null);\n    if (!res.ok) throw new HttpError(res.status, data);\n    return data;\n  };\n}\nconst api = createClient(\"https://dummyjson.com/\");\napi(\"products\", { query: { limit: 2, select: \"title,price\" } })\n  .then(d => console.log(d.products))\n  .then(() => api(\"products/999999\"))\n  .catch(e => console.log(\"failed:\", e.message, e.status));",
     "run": "js"
    },
    {
     "h": {
      "ar": "احترام Retry-After",
      "en": "Respecting Retry-After"
     },
     "p": {
      "ar": "لما الـ API يرد **429** (كتير قوي) غالبًا بيقولك تستنى قد إيه في header **retry-after** (ثواني). العميل الكويس بيستنى المدة دي بالظبط ويعيد، بحد أقصى. المثال ده بـ fetch وهمي عشان تشوف السلوك من غير ما تضغط على API حقيقي:",
      "en": "When an API answers **429** (too many) it often says how long to wait in the **retry-after** header (seconds). A good client waits exactly that long and retries, up to a limit. This example uses a fake fetch so you can see the behaviour without hammering a real API:"
     },
     "ex": "const sleep = ms => new Promise(r => setTimeout(r, ms));\nlet hits = 0;\n// a stand-in for fetch: the first two calls are rate limited\nconst fakeFetch = async () => (++hits <= 2)\n  ? { status: 429, headers: new Map([[\"Retry-After\", \"0.1\"]]) }\n  : { status: 200, headers: new Map(), json: async () => ({ saved: true, hits }) };\n\nasync function fetchWithRetry(doFetch, tries = 4) {\n  for (let i = 1; i <= tries; i++) {\n    const res = await doFetch();\n    if (res.status !== 429 && res.status < 500) return res;\n    const wait = Number(res.headers.get(\"Retry-After\") ?? 2 ** i) * 1000;\n    console.log(`got ${res.status}, waiting ${wait} ms (try ${i})`);\n    await sleep(wait);\n  }\n  throw new Error(\"still limited after \" + tries + \" tries\");\n}\nfetchWithRetry(fakeFetch).then(r => r.json()).then(console.log);",
     "run": "js"
    },
    {
     "h": {
      "ar": "كاش بسيط",
      "en": "A simple cache"
     },
     "p": {
      "ar": "لو بتطلب نفس البيانات كتير (أسعار العملة، قايمة المنتجات)، خزّنها مؤقتًا بـ **ttl** (مدة صلاحية). أقل طلبات = أسرع وأبعد عن الحدود. وخزّن الـ **Promise** نفسه مش النتيجة، عشان طلبين في نفس اللحظة يستخدموا طلب واحد.",
      "en": "If you ask for the same data often (exchange rates, the product list), keep it in a **cache** with a **ttl** (time to live). Fewer requests = faster and further from limits. Store the **promise** itself, not the result, so two calls at the same moment share one request."
     },
     "ex": "const sleep = ms => new Promise(r => setTimeout(r, ms));\nlet realCalls = 0;\nconst getRates = async () => { realCalls++; await sleep(50); return { USD: 48.5 }; };\nfunction cached(fn, ttlMs) {\n  let entry = null;\n  return () => {\n    if (entry && Date.now() - entry.at < ttlMs) return entry.promise;\n    entry = { at: Date.now(), promise: fn().catch(e => { entry = null; throw e; }) };\n    return entry.promise;\n  };\n}\nconst rates = cached(getRates, 60_000);\nPromise.all([rates(), rates(), rates()]).then(r => console.log(r[0], \"real calls:\", realCalls));",
     "run": "js"
    }
   ],
   "practice": [
    {
     "ar": "استخدم createClient مع JSONPlaceholder لـ GET وPOST.",
     "en": "Use createClient with JSONPlaceholder for GET and POST."
    },
    {
     "ar": "خلّي fakeFetch يرجّع 429 خمس مرات وشوف الاستسلام.",
     "en": "Make fakeFetch return 429 five times and watch it give up."
    },
    {
     "ar": "ضيف للعميل retry للـ 429 والـ 5xx.",
     "en": "Add retries for 429 and 5xx to the client."
    },
    {
     "ar": "جرّب الكاش بـ ttl ثانية واحدة.",
     "en": "Try the cache with a one-second TTL."
    }
   ],
   "words": [
    {
     "t": "api client",
     "m": {
      "ar": "كود موحّد لكل طلبات API",
      "en": "shared code for all API requests"
     },
     "ex": "The API client adds the token."
    },
    {
     "t": "base url",
     "m": {
      "ar": "أول الرابط المشترك لكل الطلبات",
      "en": "the common start of every request URL"
     },
     "ex": "Change the base URL for staging."
    },
    {
     "t": "httperror",
     "m": {
      "ar": "خطأ مخصوص فيه الـ status",
      "en": "a custom error holding the status"
     },
     "ex": "Catch HttpError and check status."
    },
    {
     "t": "retry-after",
     "m": {
      "ar": "header بيقول تستنى قد إيه",
      "en": "a header saying how long to wait"
     },
     "ex": "Wait for Retry-After seconds."
    },
    {
     "t": "cache",
     "m": {
      "ar": "تخزين مؤقت لنتايج متكررة",
      "en": "temporary storage of repeated results"
     },
     "ex": "The cache cut requests by 90%."
    },
    {
     "t": "ttl",
     "m": {
      "ar": "مدة صلاحية الكاش",
      "en": "how long a cached value stays valid"
     },
     "ex": "Use a TTL of one minute for rates."
    }
   ],
   "read": [
    {
     "t": "MDN: Retry-After",
     "url": "https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Retry-After",
     "what": {
      "ar": "اقرا الصيغتين.",
      "en": "Read both formats."
     }
    },
    {
     "t": "MDN: AbortSignal.timeout()",
     "url": "https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal/timeout_static",
     "what": {
      "ar": "اقرا المثال.",
      "en": "Read the example."
     }
    }
   ],
   "challenge": {
    "ar": "حوّل createClient لموديول كامل: retry للـ 429/5xx باحترام Retry-After، مهلة، HttpError، كاش اختياري للـ GET، ولوج لكل طلب (الطريقة، الرابط، الـ status، الوقت).",
    "en": "Turn createClient into a full module: retries for 429/5xx respecting Retry-After, a timeout, HttpError, an optional GET cache, and a log line per request (method, URL, status, time)."
   },
   "quiz": [
    {
     "q": {
      "ar": "429 مع Retry-After: 30",
      "en": "429 with Retry-After: 30"
     },
     "o": [
      {
       "ar": "استنى 30 ثانية وأعد",
       "en": "wait 30 seconds and retry"
      },
      {
       "ar": "أعد فورًا",
       "en": "retry at once"
      },
      {
       "ar": "استسلم",
       "en": "give up"
      }
     ],
     "a": 0,
     "why": {
      "ar": "احترم السيرفر.",
      "en": "Respect the server."
     }
    },
    {
     "q": {
      "ar": "ليه نخزّن الـ Promise في الكاش؟",
      "en": "Why cache the promise?"
     },
     "o": [
      {
       "ar": "طلبين مع بعض = طلب واحد",
       "en": "two calls at once share one request"
      },
      {
       "ar": "أصغر",
       "en": "it is smaller"
      },
      {
       "ar": "أسهل في الطباعة",
       "en": "easier to print"
      }
     ],
     "a": 0,
     "why": {
      "ar": "مفيش تكرار.",
      "en": "No duplicates."
     }
    },
    {
     "q": {
      "ar": "HttpError فايدته:",
      "en": "HttpError helps by:"
     },
     "o": [
      {
       "ar": "اللي فوق يقرر حسب الـ status",
       "en": "letting the caller decide by status"
      },
      {
       "ar": "يخفي الخطأ",
       "en": "hiding the error"
      },
      {
       "ar": "يسرّع",
       "en": "speeding up"
      }
     ],
     "a": 0,
     "why": {
      "ar": "معلومة كاملة.",
      "en": "Full information."
     }
    }
   ],
   "minutes": 120
  },
  {
   "d": 5,
   "title": {
    "ar": "الصفحات وتشكيل البيانات",
    "en": "Pages and shaping data"
   },
   "goal": {
    "ar": "تجيب كل البيانات صفحة صفحة وتحوّلها لشكلك.",
    "en": "Fetch all the data page by page and shape it your way."
   },
   "learn": [
    {
     "h": {
      "ar": "skip وlimit",
      "en": "skip and limit"
     },
     "p": {
      "ar": "أغلب الـ APIs مش بترجّع كل حاجة مرة واحدة: **limit** = كام عنصر في الصفحة، و**offset** (أو skip) = تبدأ منين. لف لحد ما الصفحة ترجع أقل من الـ limit أو توصل للـ total. ودايمًا حط حد أقصى للصفحات عشان متلفش للأبد.",
      "en": "Most APIs do not return everything at once: **limit** = how many per page, and **offset** (or skip) = where to start. Loop until a page comes back shorter than the limit or you reach the total. And always cap the pages so you never loop forever."
     },
     "ex": "async function* allProducts(limit = 30, maxPages = 10) {\n  for (let page = 0, skip = 0; page < maxPages; page++, skip += limit) {\n    const res = await fetch(`https://dummyjson.com/products?limit=${limit}&skip=${skip}&select=title,price,category`);\n    if (!res.ok) throw new Error(`HTTP ${res.status}`);\n    const { products, total } = await res.json();\n    yield products;\n    if (skip + products.length >= total) return;\n  }\n}\n(async () => {\n  try {\n    let count = 0, pages = 0;\n    for await (const batch of allProducts(50)) { count += batch.length; pages++; }\n    console.log(`${count} products in ${pages} pages`);\n  } catch (e) { console.log(\"failed:\", e.message); }\n})();",
     "run": "js"
    },
    {
     "h": {
      "ar": "شكل البيانات بتاعك",
      "en": "Your own data shape"
     },
     "p": {
      "ar": "رد الـ API بشكله هو، مش بشكلك. اعمل دالة تحويل واحدة (mapper) بتطلّع الحقول اللي محتاجها بأسماءك، وتنضّف الأنواع (أرقام، تواريخ)، وتحط قيم افتراضية. باقي الكود يتعامل مع شكلك بس — ولو الـ API اتغير، بتعدّل مكان واحد.",
      "en": "An API reply has its shape, not yours. Write one mapping function that takes the fields you need under your names, cleans the types (numbers, dates) and sets defaults. The rest of the code deals only with your shape — and if the API changes, you edit one place."
     },
     "ex": "const raw = [\n  { id: 1, title: \"Phone Case\", price: \"12.50\", category: \"accessories\", meta: { createdAt: \"2026-09-01T10:00:00Z\" } },\n  { id: 2, title: \"Charger\", price: 20, category: null, meta: {} },\n];\nconst toProduct = p => ({\n  sku: `P-${String(p.id).padStart(4, \"0\")}`,\n  name: p.title.trim(),\n  priceUsd: Number(p.price) || 0,\n  category: p.category ?? \"uncategorised\",\n  addedOn: p.meta?.createdAt?.slice(0, 10) ?? null,\n});\nconsole.log(raw.map(toProduct));",
     "run": "js"
    },
    {
     "h": {
      "ar": "الإجماليات والعرض",
      "en": "Totals and display"
     },
     "p": {
      "ar": "بعد ما البيانات بقت بشكلك، التجميع سهل بـ reduce وgroupBy، والعرض بـ Intl. وده نفس اللي هتعمله في Code node بتاع n8n: تجيب، تحوّل، تجمّع، وتبعت للخطوة اللي بعدها.",
      "en": "Once the data has your shape, totals are easy with reduce and grouping, and display with Intl. This is exactly what you will do in the n8n Code node: fetch, transform, aggregate and pass to the next step."
     },
     "ex": "const products = [\n  { name: \"Case\", category: \"accessories\", priceUsd: 12.5 },\n  { name: \"Charger\", category: \"accessories\", priceUsd: 20 },\n  { name: \"Laptop\", category: \"laptops\", priceUsd: 899 },\n];\nconst byCat = Object.groupBy(products, p => p.category);\nconst usd = new Intl.NumberFormat(\"en-US\", { style: \"currency\", currency: \"USD\" });\nfor (const [cat, list] of Object.entries(byCat)) {\n  const total = list.reduce((s, p) => s + p.priceUsd, 0);\n  console.log(cat.padEnd(12), list.length, usd.format(total));\n}",
     "run": "js"
    }
   ],
   "practice": [
    {
     "ar": "هات كل المنتجات من DummyJSON بصفحات 25.",
     "en": "Fetch every DummyJSON product in pages of 25."
    },
    {
     "ar": "اكتب toProduct لـ API تاني تختاره.",
     "en": "Write toProduct for another API of your choice."
    },
    {
     "ar": "اجمع المنتجات حسب الفئة واطبع المتوسط.",
     "en": "Group products by category and print the average."
    },
    {
     "ar": "ضيف حد أقصى للصفحات وجرّب يوصله.",
     "en": "Add a page cap and try reaching it."
    }
   ],
   "words": [
    {
     "t": "limit",
     "m": {
      "ar": "عدد العناصر في الصفحة",
      "en": "how many items per page"
     },
     "ex": "Ask for limit=50."
    },
    {
     "t": "offset",
     "m": {
      "ar": "تبدأ من عنصر رقم كام",
      "en": "which item to start from"
     },
     "ex": "Increase the offset by the page size."
    },
    {
     "t": "mapper",
     "m": {
      "ar": "دالة بتحوّل شكل بيانات لشكل تاني",
      "en": "a function turning one data shape into another"
     },
     "ex": "The mapper renames the API fields."
    },
    {
     "t": "object.groupby",
     "m": {
      "ar": "تقسيم عناصر لمجموعات بمفتاح",
      "en": "splitting items into groups by a key"
     },
     "ex": "Object.groupBy splits orders by city."
    },
    {
     "t": "intl.numberformat",
     "m": {
      "ar": "تنسيق الأرقام والعملات حسب اللغة",
      "en": "formatting numbers and currencies by locale"
     },
     "ex": "Intl.NumberFormat shows EGP correctly."
    }
   ],
   "read": [
    {
     "t": "DummyJSON",
     "url": "https://dummyjson.com/",
     "what": {
      "ar": "اقرا Products: limit وskip وselect.",
      "en": "Read Products: limit, skip and select."
     }
    },
    {
     "t": "MDN: Object.groupBy()",
     "url": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/groupBy",
     "what": {
      "ar": "اقرا المثال.",
      "en": "Read the example."
     }
    }
   ],
   "challenge": {
    "ar": "اعمل «كتالوج حي»: يجيب كل منتجات DummyJSON بالصفحات، يحوّلها بـ toProduct، يعرضها في جدول بفلتر فئة وبحث، ويعرض إجمالي وعدد كل فئة.",
    "en": "Build a «live catalogue»: fetch all DummyJSON products by pages, map them with toProduct, show them in a table with a category filter and search, and show each category’s count and total."
   },
   "quiz": [
    {
     "q": {
      "ar": "آخر صفحة لما:",
      "en": "The last page is when:"
     },
     "o": [
      {
       "ar": "العناصر أقل من الـ limit أو وصلت للـ total",
       "en": "items are fewer than the limit or you reach the total"
      },
      {
       "ar": "أول 404",
       "en": "the first 404"
      },
      {
       "ar": "بعد 3 صفحات دايمًا",
       "en": "always after 3 pages"
      }
     ],
     "a": 0,
     "why": {
      "ar": "وحط حد أقصى.",
      "en": "And cap it."
     }
    },
    {
     "q": {
      "ar": "mapper واحد فايدته:",
      "en": "One mapper helps because:"
     },
     "o": [
      {
       "ar": "تغيير الـ API = تعديل مكان واحد",
       "en": "an API change = one edit"
      },
      {
       "ar": "أسرع شبكة",
       "en": "faster network"
      },
      {
       "ar": "مفيش فايدة",
       "en": "no benefit"
      }
     ],
     "a": 0,
     "why": {
      "ar": "عزل.",
      "en": "Isolation."
     }
    },
    {
     "q": {
      "ar": "تنسيق عملة:",
      "en": "Formatting a currency:"
     },
     "o": [
      "Intl.NumberFormat",
      "toUpperCase",
      "parseInt"
     ],
     "a": 0,
     "why": {
      "ar": "حسب اللغة.",
      "en": "By locale."
     }
    }
   ],
   "minutes": 120
  },
  {
   "d": 6,
   "title": {
    "ar": "مراجعة الأسبوع ومشروعه",
    "en": "Week review and project"
   },
   "goal": {
    "ar": "لوحة بيانات حية من APIs حقيقية.",
    "en": "A live dashboard from real APIs."
   },
   "review": [
    {
     "ar": "fetch خطوتين، وres.ok، والـ network error مقابل الـ status.",
     "en": "fetch in two steps, res.ok, and network errors vs status codes."
    },
    {
     "ar": "POST بـ JSON، وURLSearchParams، وPUT/PATCH/DELETE، وFormData.",
     "en": "POST with JSON, URLSearchParams, PUT/PATCH/DELETE and FormData."
    },
    {
     "ar": "الـ headers والتوكن، والمفاتيح في السيرفر، والـ CORS.",
     "en": "Headers and tokens, keys on the server, and CORS."
    },
    {
     "ar": "عميل API بـ HttpError ومهلة وRetry-After وكاش.",
     "en": "An API client with HttpError, a timeout, Retry-After and a cache."
    },
    {
     "ar": "الصفحات بـ limit/offset، والـ mapper، والتجميع.",
     "en": "Pages with limit/offset, the mapper and aggregation."
    }
   ],
   "project": {
    "ar": "ابني «لوحة متجر حية»: عميل API واحد (createClient) بيجيب المنتجات والمستخدمين والسلال من DummyJSON بالصفحات والتوازي المحدود، يحوّلهم لشكلك، ويعرض: إجمالي المبيعات، أكتر 5 منتجات، المبيعات حسب الفئة، وجدول بحث. مع مؤشر تحميل، ورسائل أخطاء واضحة، وكاش 5 دقايق، وزرار «ابعت ملخص» بيعمل POST لـ webhook n8n.",
    "en": "Build a «live shop board»: one API client (createClient) fetching products, users and carts from DummyJSON with pages and limited concurrency, mapping them to your shape, and showing: total sales, the top 5 products, sales by category and a searchable table. With a loading indicator, clear error messages, a 5-minute cache and a «send summary» button that POSTs to an n8n webhook."
   },
   "test": [
    {
     "q": {
      "ar": "fetch بيرفض لما:",
      "en": "fetch rejects when:"
     },
     "o": [
      {
       "ar": "مفيش رد (شبكة)",
       "en": "there is no reply (network)"
      },
      {
       "ar": "404",
       "en": "404"
      },
      {
       "ar": "500",
       "en": "500"
      }
     ],
     "a": 0,
     "why": {
      "ar": "افحص res.ok للباقي.",
      "en": "Check res.ok for the rest."
     }
    },
    {
     "q": {
      "ar": "res.ok يعني:",
      "en": "res.ok means:"
     },
     "o": [
      "status 200–299",
      "status 200 only",
      {
       "ar": "مفيش خطأ JSON",
       "en": "no JSON error"
      }
     ],
     "a": 0,
     "why": {
      "ar": "2xx.",
      "en": "2xx."
     }
    },
    {
     "q": {
      "ar": "422 معناها:",
      "en": "422 means:"
     },
     "o": [
      {
       "ar": "البيانات فشلت في التحقق",
       "en": "the data failed validation"
      },
      {
       "ar": "السيرفر واقع",
       "en": "the server is down"
      },
      {
       "ar": "تم",
       "en": "done"
      }
     ],
     "a": 0,
     "why": {
      "ar": "صلّح الطلب.",
      "en": "Fix the request."
     }
    },
    {
     "q": {
      "ar": "JSON في POST:",
      "en": "JSON in a POST:"
     },
     "o": [
      "body: JSON.stringify(data)",
      "body: data",
      "query: data"
     ],
     "a": 0,
     "why": {
      "ar": "نص.",
      "en": "Text."
     }
    },
    {
     "q": {
      "ar": "بناء ?q=… بنص عربي:",
      "en": "Building ?q=… with Arabic text:"
     },
     "o": [
      "URLSearchParams",
      {
       "ar": "جمع نصوص",
       "en": "string concatenation"
      },
      "JSON.stringify"
     ],
     "a": 0,
     "why": {
      "ar": "تشفير.",
      "en": "Encoding."
     }
    },
    {
     "q": {
      "ar": "PATCH:",
      "en": "PATCH:"
     },
     "o": [
      {
       "ar": "تعديل حقول",
       "en": "changes some fields"
      },
      {
       "ar": "مسح",
       "en": "deletes"
      },
      {
       "ar": "قراءة",
       "en": "reads"
      }
     ],
     "a": 0,
     "why": {
      "ar": "جزئي.",
      "en": "Partial."
     }
    },
    {
     "q": {
      "ar": "توكن سري للـ AI في صفحة عامة:",
      "en": "A secret AI token in a public page:"
     },
     "o": [
      {
       "ar": "ممنوع؛ proxy عبر n8n",
       "en": "never; proxy through n8n"
      },
      {
       "ar": "عادي",
       "en": "fine"
      },
      {
       "ar": "لو base64",
       "en": "fine if base64"
      }
     ],
     "a": 0,
     "why": {
      "ar": "مكشوف.",
      "en": "Exposed."
     }
    },
    {
     "q": {
      "ar": "preflight هو:",
      "en": "A preflight is:"
     },
     "o": [
      {
       "ar": "طلب OPTIONS قبل الحقيقي",
       "en": "an OPTIONS request before the real one"
      },
      {
       "ar": "كاش",
       "en": "a cache"
      },
      {
       "ar": "خطأ",
       "en": "an error"
      }
     ],
     "a": 0,
     "why": {
      "ar": "CORS.",
      "en": "CORS."
     }
    },
    {
     "q": {
      "ar": "مهلة لـ fetch:",
      "en": "A timeout for fetch:"
     },
     "o": [
      "AbortSignal.timeout(ms)",
      "{ timeout: ms }",
      "setTimeout(fetch)"
     ],
     "a": 0,
     "why": {
      "ar": "signal.",
      "en": "A signal."
     }
    },
    {
     "q": {
      "ar": "429:",
      "en": "429:"
     },
     "o": [
      {
       "ar": "استنى (Retry-After) وأعد",
       "en": "wait (Retry-After) and retry"
      },
      {
       "ar": "صلّح البيانات",
       "en": "fix the data"
      },
      {
       "ar": "سجّل دخول",
       "en": "sign in"
      }
     ],
     "a": 0,
     "why": {
      "ar": "كتير قوي.",
      "en": "Too many."
     }
    },
    {
     "q": {
      "ar": "الصفحات من غير حد أقصى:",
      "en": "Pages with no cap:"
     },
     "o": [
      {
       "ar": "ممكن تلف للأبد",
       "en": "may loop forever"
      },
      {
       "ar": "أسرع",
       "en": "faster"
      },
      {
       "ar": "أأمن",
       "en": "safer"
      }
     ],
     "a": 0,
     "why": {
      "ar": "حط maxPages.",
      "en": "Set maxPages."
     }
    },
    {
     "q": {
      "ar": "API غيّر اسم حقل:",
      "en": "An API renamed a field:"
     },
     "o": [
      {
       "ar": "عدّل الـ mapper بس",
       "en": "edit only the mapper"
      },
      {
       "ar": "عدّل كل الملفات",
       "en": "edit every file"
      },
      {
       "ar": "ابدأ من الأول",
       "en": "start over"
      }
     ],
     "a": 0,
     "why": {
      "ar": "مكان واحد.",
      "en": "One place."
     }
    }
   ],
   "minutes": 120
  }
 ]
});
