// Week 46 — generated by tools/build_weeks.js from content/js/src/w46.js. Edit the source, not this file.
JOURNEY.week({
 "track": "js",
 "n": 46,
 "month": 12,
 "level": {
  "ar": "خبير",
  "en": "Expert"
 },
 "title": {
  "ar": "CI/CD والمراقبة لـ Node",
  "en": "CI/CD and monitoring for Node"
 },
 "goal": {
  "ar": "من commit لإنتاج مراقَب: pipelines سريعة بمصفوفات وكاش وحماية للفروع، نشر لبيئات بموافقة ومن غير مفاتيح طويلة العمر، إصدارات آلية، ولوج ومقاييس وتتبع وتتبع أخطاء، وSLOs وتنبيهات بتصحّي حد بس لما يستاهل.",
  "en": "From commit to monitored production: fast pipelines with matrices, caching and branch protection, deploys to environments with approval and no long-lived keys, automated releases, logs, metrics, tracing and error tracking, and SLOs with alerts that wake someone only when it matters."
 },
 "days": [
  {
   "d": 1,
   "title": {
    "ar": "CI سريع وموثوق",
    "en": "Fast, reliable CI"
   },
   "goal": {
    "ar": "كل PR بيتفحص في دقايق.",
    "en": "Every PR checked in minutes."
   },
   "learn": [
    {
     "h": {
      "ar": "workflow كامل",
      "en": "A complete workflow"
     },
     "p": {
      "ar": "**github actions**: lint وtypes وtests في **matrix** (نسخ Node وأنظمة)، كاش npm، و**artifact** للتقارير. **required check** مع **branch protection** = مفيش merge على main غير لما الـ CI ينجح ومراجعة. واقسم الـ jobs عشان تشتغل بالتوازي.",
      "en": "**github actions**: lint, types and tests in a **matrix** (Node versions and systems), an npm cache, and an **artifact** for reports. A **required check** with **branch protection** = no merge to main until CI passes and a review. And split jobs so they run in parallel."
     },
     "ex": "name: ci\non: { pull_request: {}, push: { branches: [main] } }\nconcurrency: { group: \"ci-${{ github.ref }}\", cancel-in-progress: true }\njobs:\n  lint:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v5\n      - uses: actions/setup-node@v5\n        with: { node-version: 22, cache: npm }\n      - run: npm ci --ignore-scripts\n      - run: npm run lint && npx tsc --noEmit\n  test:\n    strategy: { matrix: { node: [22, 24], os: [ubuntu-latest, windows-latest] } }\n    runs-on: ${{ matrix.os }}\n    steps:\n      - uses: actions/checkout@v5\n      - uses: actions/setup-node@v5\n        with: { node-version: \"${{ matrix.node }}\", cache: npm }\n      - run: npm ci --ignore-scripts\n      - run: node --test --test-reporter=junit --test-reporter-destination=report.xml\n      - uses: actions/upload-artifact@v4\n        if: always()\n        with: { name: \"report-${{ matrix.os }}-${{ matrix.node }}\", path: report.xml }",
     "lang": "text"
    },
    {
     "h": {
      "ar": "اختبارات تكامل في CI",
      "en": "Integration tests in CI"
     },
     "p": {
      "ar": "خدمات حقيقية في CI بـ `services:` (Postgres، Redis) — نفس نسخة الإنتاج. وشغّل الترحيلات قبل الاختبارات. والاختبارات البطيئة (e2e بـ Playwright) في job منفصل أو كل ليلة عشان الـ PR يفضل سريع.",
      "en": "Real services in CI with `services:` (Postgres, Redis) — the same version as production. Run migrations before the tests. And keep slow tests (Playwright e2e) in a separate job or nightly so PRs stay fast."
     },
     "ex": "integration:\n  runs-on: ubuntu-latest\n  services:\n    postgres:\n      image: postgres:17\n      env: { POSTGRES_PASSWORD: ci-only, POSTGRES_DB: shop_test }\n      ports: [\"5432:5432\"]\n      options: --health-cmd \"pg_isready\" --health-interval 5s --health-retries 10\n  env: { DATABASE_URL: \"postgres://postgres:ci-only@localhost:5432/shop_test\" }\n  steps:\n    - uses: actions/checkout@v5\n    - uses: actions/setup-node@v5\n      with: { node-version: 22, cache: npm }\n    - run: npm ci --ignore-scripts\n    - run: npm run migrate\n    - run: node --test test/integration/",
     "lang": "text"
    },
    {
     "h": {
      "ar": "إصدارات آلية",
      "en": "Automated releases"
     },
     "p": {
      "ar": "مع conventional commits (أسبوع 28) أداة زي **release please** بتفتح PR فيه رقم الإصدار الجاي والـ changelog، ولما تدمجه بيعمل tag وrelease. المثال بيحسب الرقم الجاي من الـ commits — نفس المنطق.",
      "en": "With conventional commits (week 28), a tool like **release please** opens a PR with the next version number and the changelog, and merging it creates a tag and a release. The example computes the next number from the commits — the same logic."
     },
     "ex": "const commits = [\"feat(orders): WhatsApp status endpoint\", \"fix: VAT rounding on credit notes\", \"chore(deps): bump pino\", \"docs: deploy guide\"];\nfunction nextVersion(current, msgs) {\n  let [major, minor, patch] = current.split(\".\").map(Number);\n  const kinds = msgs.map(m => m.match(/^(\\w+)(\\([^)]*\\))?(!)?:/) ?? []);\n  if (kinds.some(k => k[3]) || msgs.some(m => m.includes(\"BREAKING CHANGE\"))) return `${major + 1}.0.0`;\n  if (kinds.some(k => k[1] === \"feat\")) return `${major}.${minor + 1}.0`;\n  if (kinds.some(k => k[1] === \"fix\")) return `${major}.${minor}.${patch + 1}`;\n  return current;\n}\nconsole.log(\"1.8.2 →\", nextVersion(\"1.8.2\", commits));\nconsole.log(\"1.8.2 →\", nextVersion(\"1.8.2\", [\"fix: typo in email\"]));\nconsole.log(\"1.8.2 →\", nextVersion(\"1.8.2\", [\"feat!: new /v2 orders API\"]));\nconsole.log(\"1.8.2 →\", nextVersion(\"1.8.2\", [\"chore: lint\"]), \"(nothing to release)\");",
     "node": 1
    }
   ],
   "practice": [
    {
     "ar": "اعمل workflow بـ lint وtypes وmatrix.",
     "en": "Create a workflow with lint, types and a matrix."
    },
    {
     "ar": "فعّل branch protection وrequired checks.",
     "en": "Enable branch protection and required checks."
    },
    {
     "ar": "ضيف Postgres service لاختبارات التكامل.",
     "en": "Add a Postgres service for integration tests."
    },
    {
     "ar": "جرّب release-please على ريبو.",
     "en": "Try release-please on a repo."
    }
   ],
   "words": [
    {
     "t": "github actions",
     "m": {
      "ar": "نظام CI/CD في GitHub",
      "en": "GitHub’s CI/CD platform"
     },
     "ex": "GitHub Actions runs the tests on every PR."
    },
    {
     "t": "matrix",
     "m": {
      "ar": "تشغيل على تركيبات نسخ وأنظمة",
      "en": "running jobs across combinations"
     },
     "ex": "The matrix covers Node 22 and 24."
    },
    {
     "t": "artifact",
     "m": {
      "ar": "ملف ناتج من الـ pipeline",
      "en": "a file saved from a CI run"
     },
     "ex": "Download the coverage artifact."
    },
    {
     "t": "required check",
     "m": {
      "ar": "فحص لازم ينجح قبل الدمج",
      "en": "a status that must pass before merging"
     },
     "ex": "Tests are a required check."
    },
    {
     "t": "branch protection",
     "m": {
      "ar": "حماية الفرع من الدمج المباشر",
      "en": "rules guarding a branch"
     },
     "ex": "Branch protection needs one review."
    },
    {
     "t": "release please",
     "m": {
      "ar": "أداة إصدارات آلية",
      "en": "a tool automating versions and changelogs"
     },
     "ex": "release-please opened the 1.9.0 PR."
    }
   ],
   "read": [
    {
     "t": "GitHub Actions docs",
     "url": "https://docs.github.com/en/actions",
     "what": {
      "ar": "اقرا Building and testing Node.js.",
      "en": "Read Building and testing Node.js."
     }
    }
   ],
   "challenge": {
    "ar": "ابني CI لخدمة المتجر: lint وtsc وunit في matrix، integration بـ Postgres service، e2e كل ليلة، artifacts للتقارير، branch protection بـ required checks، وrelease-please بيعمل الإصدارات — والـ PR العادي يخلص في أقل من 8 دقايق.",
    "en": "Build CI for the shop service: lint, tsc and unit tests in a matrix, integration with a Postgres service, nightly e2e, report artifacts, branch protection with required checks, and release-please making releases — with a normal PR finishing in under 8 minutes."
   },
   "quiz": [
    {
     "q": {
      "ar": "مفيش merge من غير CI:",
      "en": "No merge without CI:"
     },
     "o": [
      {
       "ar": "branch protection + required check",
       "en": "branch protection + a required check"
      },
      {
       "ar": "ثقة",
       "en": "trust"
      },
      {
       "ar": "إيميل",
       "en": "an email"
      }
     ],
     "a": 0,
     "why": {
      "ar": "حماية.",
      "en": "Protection."
     }
    },
    {
     "q": {
      "ar": "e2e بطيئة:",
      "en": "Slow e2e tests:"
     },
     "o": [
      {
       "ar": "job منفصل أو كل ليلة",
       "en": "a separate job or nightly"
      },
      {
       "ar": "في كل خطوة",
       "en": "in every step"
      },
      {
       "ar": "احذفها",
       "en": "delete them"
      }
     ],
     "a": 0,
     "why": {
      "ar": "سرعة.",
      "en": "Speed."
     }
    },
    {
     "q": {
      "ar": "feat: في commit:",
      "en": "feat: in a commit:"
     },
     "o": [
      {
       "ar": "minor",
       "en": "minor"
      },
      {
       "ar": "major",
       "en": "major"
      },
      {
       "ar": "مفيش إصدار",
       "en": "no release"
      }
     ],
     "a": 0,
     "why": {
      "ar": "ميزة.",
      "en": "Feature."
     }
    }
   ],
   "minutes": 120
  },
  {
   "d": 2,
   "title": {
    "ar": "النشر للبيئات",
    "en": "Deploying to environments"
   },
   "goal": {
    "ar": "staging تلقائي وإنتاج بموافقة.",
    "en": "Automatic staging, approved production."
   },
   "learn": [
    {
     "h": {
      "ar": "البيئات والموافقة",
      "en": "Environments and approval"
     },
     "p": {
      "ar": "GitHub **environment** (staging، production) بأسرار خاصة بكل واحدة و**approval** (مراجع لازم يوافق) لـ production. كل merge على main بيروح **staging** لوحده بنفس الصورة (الـ digest)، وبعد الموافقة نفس الـ digest يروح production. و**continuous deployment** الكامل لو الاختبارات والمراقبة قوية كفاية.",
      "en": "A GitHub **environment** (staging, production) with its own secrets and an **approval** (a reviewer must approve) for production. Every merge to main goes to **staging** automatically with the same image (the digest), and after approval the same digest goes to production. Full **continuous deployment** if tests and monitoring are strong enough."
     },
     "ex": "deploy-staging:\n  needs: [image]\n  environment: staging\n  runs-on: ubuntu-latest\n  steps:\n    - run: ./deploy.sh staging \"${{ needs.image.outputs.digest }}\"\n    - run: npx playwright test --config e2e/smoke.config.ts      # smoke tests against staging\ndeploy-production:\n  needs: [deploy-staging]\n  environment: production                     # required reviewers → waits for approval\n  runs-on: ubuntu-latest\n  steps:\n    - run: ./deploy.sh production \"${{ needs.image.outputs.digest }}\"   # the SAME digest",
     "lang": "text"
    },
    {
     "h": {
      "ar": "من غير مفاتيح طويلة العمر",
      "en": "No long-lived keys"
     },
     "p": {
      "ar": "**oidc**: الـ job بياخد توكن مؤقت من GitHub والسحابة بتثق فيه لريبو وفرع وبيئة محددين — مفيش مفتاح AWS/GCP محفوظ للأبد. ولـ VPS: مفتاح SSH مخصص للنشر بصلاحيات محدودة (أمر واحد) في أسرار الـ environment.",
      "en": "**oidc**: the job gets a short-lived token from GitHub that the cloud trusts only for a specific repo, branch and environment — no AWS/GCP key stored forever. For a VPS: a dedicated deploy SSH key with limited rights (one command) in the environment’s secrets."
     },
     "ex": "# AWS: trust policy condition for the deploy role (only this repo, only the production environment)\n\"Condition\": {\n  \"StringEquals\": { \"token.actions.githubusercontent.com:aud\": \"sts.amazonaws.com\" },\n  \"StringLike\":   { \"token.actions.githubusercontent.com:sub\": \"repo:acme/shop:environment:production\" }\n}\n\n# VPS: ~/.ssh/authorized_keys on the server — the deploy key can run ONE command\ncommand=\"/opt/shop/deploy.sh\",no-port-forwarding,no-agent-forwarding,no-pty ssh-ed25519 AAAA… github-deploy",
     "lang": "text"
    },
    {
     "h": {
      "ar": "بيئات معاينة",
      "en": "Preview environments"
     },
     "p": {
      "ar": "**preview deployment** = كل PR بياخد رابط مؤقت بالنسخة دي (Vercel وNetlify وCloudflare Pages بيعملوها لوحدهم للواجهات). المراجع بيجرّب بدل ما يقرا الكود بس، والعميل يشوف قبل الدمج. واتأكد إنها بتستخدم بيانات تجربة مش بيانات حقيقية، وبتتمسح بعد الدمج.",
      "en": "A **preview deployment** = each PR gets a temporary URL with that version (Vercel, Netlify and Cloudflare Pages do it automatically for front ends). Reviewers try it instead of only reading code, and the client sees it before merging. Make sure it uses test data, not real data, and is removed after merge."
     },
     "ex": "PR #142 «new checkout»\n  CI ✓  → preview: https://pr-142.shop-preview.example.com   (seeded test data, payment sandbox)\n  reviewer comments with screenshots · client approves the flow\n  merge → preview destroyed → staging deploy → production after approval",
     "lang": "text"
    }
   ],
   "practice": [
    {
     "ar": "اعمل environments staging وproduction.",
     "en": "Create staging and production environments."
    },
    {
     "ar": "ضيف required reviewers لـ production.",
     "en": "Add required reviewers for production."
    },
    {
     "ar": "استبدل مفتاح سحابة بـ OIDC.",
     "en": "Replace a cloud key with OIDC."
    },
    {
     "ar": "فعّل preview deployments للواجهة.",
     "en": "Enable preview deployments for the front end."
    }
   ],
   "words": [
    {
     "t": "environment",
     "m": {
      "ar": "بيئة نشر بأسرارها",
      "en": "a deployment target with its own secrets"
     },
     "ex": "The production environment needs approval."
    },
    {
     "t": "approval",
     "m": {
      "ar": "موافقة قبل النشر",
      "en": "a manual sign-off before deploying"
     },
     "ex": "The approval came from the tech lead."
    },
    {
     "t": "staging",
     "m": {
      "ar": "بيئة تجربة شبه الإنتاج",
      "en": "a near-production test environment"
     },
     "ex": "Every merge goes to staging."
    },
    {
     "t": "continuous deployment",
     "m": {
      "ar": "نشر تلقائي لكل تغيير ناجح",
      "en": "releasing every passing change automatically"
     },
     "ex": "Continuous deployment needs good alerts."
    },
    {
     "t": "oidc",
     "m": {
      "ar": "توكن مؤقت بدل المفاتيح",
      "en": "short-lived identity tokens for CI"
     },
     "ex": "OIDC removed the stored AWS key."
    },
    {
     "t": "preview deployment",
     "m": {
      "ar": "نسخة معاينة لكل PR",
      "en": "a temporary deployment per pull request"
     },
     "ex": "The client tested the preview deployment."
    }
   ],
   "read": [
    {
     "t": "GitHub Actions docs",
     "url": "https://docs.github.com/en/actions",
     "what": {
      "ar": "اقرا Deployments and environments.",
      "en": "Read Deployments and environments."
     }
    }
   ],
   "challenge": {
    "ar": "كمّل الـ pipeline: صورة واحدة بـ digest، staging تلقائي بـ smoke tests، production بموافقة بنفس الـ digest، OIDC أو مفتاح نشر محدود، وpreview لكل PR في الواجهة — ووثّق خطة الرجوع.",
    "en": "Complete the pipeline: one image by digest, automatic staging with smoke tests, approved production with the same digest, OIDC or a restricted deploy key, and a preview per PR for the front end — and document the rollback plan."
   },
   "quiz": [
    {
     "q": {
      "ar": "production بيستخدم:",
      "en": "Production uses:"
     },
     "o": [
      {
       "ar": "نفس الـ digest اللي اتجرّب على staging",
       "en": "the same digest tested on staging"
      },
      {
       "ar": "بناء جديد",
       "en": "a fresh build"
      },
      {
       "ar": "latest",
       "en": "latest"
      }
     ],
     "a": 0,
     "why": {
      "ar": "ثبات.",
      "en": "Consistency."
     }
    },
    {
     "q": {
      "ar": "مفتاح AWS محفوظ في GitHub للأبد:",
      "en": "An AWS key stored in GitHub forever:"
     },
     "o": [
      {
       "ar": "استبدله بـ OIDC",
       "en": "replace it with OIDC"
      },
      {
       "ar": "عادي",
       "en": "fine"
      },
      {
       "ar": "أحسن",
       "en": "better"
      }
     ],
     "a": 0,
     "why": {
      "ar": "مؤقت.",
      "en": "Short-lived."
     }
    },
    {
     "q": {
      "ar": "preview deployment:",
      "en": "A preview deployment:"
     },
     "o": [
      {
       "ar": "رابط مؤقت لكل PR ببيانات تجربة",
       "en": "a temporary URL per PR with test data"
      },
      {
       "ar": "الإنتاج",
       "en": "production"
      },
      {
       "ar": "صورة PNG",
       "en": "a PNG"
      }
     ],
     "a": 0,
     "why": {
      "ar": "معاينة.",
      "en": "Preview."
     }
    }
   ],
   "minutes": 120
  },
  {
   "d": 3,
   "title": {
    "ar": "اللوج المنظم",
    "en": "Structured logs"
   },
   "goal": {
    "ar": "لوج تقدر تدوّر فيه بـ request id.",
    "en": "Logs searchable by request id."
   },
   "learn": [
    {
     "h": {
      "ar": "pino واللوج JSON",
      "en": "pino and JSON logs"
     },
     "p": {
      "ar": "**structured logging** = كل سطر JSON بحقول (الوقت، المستوى، الحدث، orderId). في Node **pino** الأسرع والأشهر؛ بيكتب JSON على stdout، والـ orchestrator أو Loki بيجمعوه. ومتسجلش أسرار ولا PII — pino فيه `redact` بمسارات.",
      "en": "**structured logging** = every line JSON with fields (time, level, event, orderId). In Node **pino** is the fastest and most popular; it writes JSON to stdout, and the orchestrator or Loki collects it. And never log secrets or PII — pino has `redact` with paths."
     },
     "ex": "import pino from \"pino\";\nimport pinoHttp from \"pino-http\";\n\nexport const log = pino({\n  level: process.env.LOG_LEVEL ?? \"info\",\n  redact: { paths: [\"req.headers.authorization\", \"req.headers.cookie\", \"*.password\", \"*.cardNumber\"], censor: \"***\" },\n  base: { service: \"shop-api\", version: process.env.APP_VERSION },\n});\napp.use(pinoHttp({ logger: log, genReqId: req => req.headers[\"x-request-id\"] ?? crypto.randomUUID() }));\n\nlog.info({ event: \"order_paid\", orderId: 1042, total: 650, gateway: \"paymob\" }, \"order paid\");",
     "lang": "js"
    },
    {
     "h": {
      "ar": "request id بـ AsyncLocalStorage",
      "en": "Request ids with AsyncLocalStorage"
     },
     "p": {
      "ar": "عايز كل سطر لوج (حتى جوه دوال عميقة وفي callbacks async) فيه الـ request id من غير ما تمرره يدوي؟ **asynclocalstorage** (`node:async_hooks`) بيخزّن قيمة للطلب الحالي عبر كل الـ async. المثال logger بيضيف الـ id لوحده لطلبات متداخلة.",
      "en": "Want every log line (even deep in functions and async callbacks) to carry the request id without passing it by hand? **asynclocalstorage** (`node:async_hooks`) stores a value for the current request across all async work. The example is a logger adding the id automatically for interleaved requests."
     },
     "ex": "import { AsyncLocalStorage } from \"node:async_hooks\";\nimport { randomUUID } from \"node:crypto\";\n\nconst als = new AsyncLocalStorage();\nconst log = (level, event, fields = {}) =>\n  console.log(JSON.stringify({ level, event, requestId: als.getStore()?.requestId ?? \"-\", ...fields }));\n\nasync function chargeCard(orderId) {               // deep in the code: no id parameter\n  await new Promise(r => setTimeout(r, Math.random() * 20));\n  log(\"info\", \"payment_captured\", { orderId });\n}\nasync function handleRequest(orderId) {\n  return als.run({ requestId: randomUUID().slice(0, 8) }, async () => {\n    log(\"info\", \"request_start\", { orderId });\n    await chargeCard(orderId);\n    log(\"info\", \"request_end\", { orderId });\n  });\n}\nawait Promise.all([handleRequest(1042), handleRequest(1043), handleRequest(1044)]);",
     "node": 1
    },
    {
     "h": {
      "ar": "المستويات والتكلفة",
      "en": "Levels and cost"
     },
     "p": {
      "ar": "info للأحداث المهمة، warn للحاجات الغريبة، error للفشل، debug للتطوير بس (اقفله في الإنتاج أو اعمله sampling). اللوج بفلوس (تخزين وفهرسة) — 1 مليون طلب × 10 سطور debug = فاتورة. وسجّل الأحداث بأسماء ثابتة (`order_paid`) عشان تعدّ وتعمل dashboards.",
      "en": "info for important events, warn for odd things, error for failures, debug only during development (switch it off in production or sample it). Logs cost money (storage and indexing) — 1 million requests × 10 debug lines = a bill. And log events with stable names (`order_paid`) so you can count them and build dashboards."
     },
     "ex": "log levels in production\nerror   invoice_failed {orderId, reason, err}            → alert if > 5 in 10 min\nwarn    odoo_slow {orderId, ms}                          → weekly review\ninfo    order_paid / order_shipped / refund_requested    → business dashboards\ndebug   off (LOG_LEVEL=info) · enable per request with a header for support cases\n\nnever: passwords, tokens, full card numbers, full addresses, whole request bodies",
     "lang": "text"
    }
   ],
   "practice": [
    {
     "ar": "حوّل console.log لـ pino بحقول.",
     "en": "Switch console.log to pino with fields."
    },
    {
     "ar": "ضيف redact لـ authorization وpassword.",
     "en": "Add redact for authorization and password."
    },
    {
     "ar": "استخدم AsyncLocalStorage للـ request id.",
     "en": "Use AsyncLocalStorage for the request id."
    },
    {
     "ar": "سمّي الأحداث بأسماء ثابتة.",
     "en": "Give events stable names."
    }
   ],
   "words": [
    {
     "t": "structured logging",
     "m": {
      "ar": "لوج JSON بحقول",
      "en": "logging as fields, usually JSON"
     },
     "ex": "Structured logging made errors countable."
    },
    {
     "t": "pino",
     "m": {
      "ar": "logger سريع لـ Node",
      "en": "a fast JSON logger for Node"
     },
     "ex": "pino writes JSON to stdout."
    },
    {
     "t": "redact",
     "m": {
      "ar": "إخفاء حقول حساسة في اللوج",
      "en": "masking sensitive fields in logs"
     },
     "ex": "redact hides the authorization header."
    },
    {
     "t": "asynclocalstorage",
     "m": {
      "ar": "تخزين لكل طلب عبر الـ async",
      "en": "per-request storage across async calls"
     },
     "ex": "AsyncLocalStorage carries the request id."
    },
    {
     "t": "log sampling",
     "m": {
      "ar": "تسجيل نسبة من اللوج",
      "en": "keeping only a share of log lines"
     },
     "ex": "Log sampling cut costs by 80%."
    }
   ],
   "read": [
    {
     "t": "Node.js: Asynchronous context tracking",
     "url": "https://nodejs.org/api/async_context.html",
     "what": {
      "ar": "اقرا AsyncLocalStorage.",
      "en": "Read AsyncLocalStorage."
     }
    }
   ],
   "challenge": {
    "ar": "خلّي لوج خدمة المتجر قابل للتحقيق: pino بـ redact، request id من header أو جديد عبر AsyncLocalStorage لحد الـ workers، أحداث بأسماء ثابتة، ومستويات مظبوطة — وجاوب «إيه اللي حصل لطلب 1042؟» من اللوج في دقيقة.",
    "en": "Make the shop service’s logs investigable: pino with redact, a request id from a header or new via AsyncLocalStorage reaching the workers, stable event names and correct levels — then answer «what happened to order 1042?» from the logs in a minute."
   },
   "quiz": [
    {
     "q": {
      "ar": "request id من غير ما تمرره:",
      "en": "A request id without passing it around:"
     },
     "o": [
      {
       "ar": "AsyncLocalStorage",
       "en": "AsyncLocalStorage"
      },
      {
       "ar": "متغير global",
       "en": "a global variable"
      },
      {
       "ar": "ملف",
       "en": "a file"
      }
     ],
     "a": 0,
     "why": {
      "ar": "سياق.",
      "en": "Context."
     }
    },
    {
     "q": {
      "ar": "authorization header في اللوج:",
      "en": "An authorization header in logs:"
     },
     "o": [
      {
       "ar": "redact",
       "en": "redact it"
      },
      {
       "ar": "سجّله كامل",
       "en": "log it in full"
      },
      {
       "ar": "اطبعه مرتين",
       "en": "print it twice"
      }
     ],
     "a": 0,
     "why": {
      "ar": "أسرار.",
      "en": "Secrets."
     }
    },
    {
     "q": {
      "ar": "debug في الإنتاج:",
      "en": "debug in production:"
     },
     "o": [
      {
       "ar": "مقفول أو sampling",
       "en": "off or sampled"
      },
      {
       "ar": "دايمًا شغال",
       "en": "always on"
      },
      {
       "ar": "إجباري",
       "en": "required"
      }
     ],
     "a": 0,
     "why": {
      "ar": "تكلفة.",
      "en": "Cost."
     }
    }
   ],
   "minutes": 120
  },
  {
   "d": 4,
   "title": {
    "ar": "المقاييس والتتبع والأخطاء",
    "en": "Metrics, tracing and errors"
   },
   "goal": {
    "ar": "تعرف صحة الخدمة في نظرة.",
    "en": "Know the service’s health at a glance."
   },
   "learn": [
    {
     "h": {
      "ar": "مقاييس Prometheus",
      "en": "Prometheus metrics"
     },
     "p": {
      "ar": "**metrics**: counter (الطلبات، الأخطاء)، gauge (طول الطابور)، و**histogram** (زمن الاستجابة في buckets للـ p95). في Node **prom-client** بيعرض `/metrics` بصيغة **prometheus**، ومعاه مقاييس Node الافتراضية (event loop lag، الذاكرة، GC). المثال بيبني histogram ويطبع الصيغة.",
      "en": "**metrics**: a counter (requests, errors), a gauge (queue length), and a **histogram** (response time in buckets for p95). In Node **prom-client** exposes `/metrics` in **prometheus** format, with Node’s default metrics (event-loop lag, memory, GC). The example builds a histogram and prints the format."
     },
     "ex": "const buckets = [0.05, 0.1, 0.25, 0.5, 1, 2.5];\nconst h = { counts: Array(buckets.length + 1).fill(0), sum: 0, n: 0 };\nconst observe = s => { const i = buckets.findIndex(b => s <= b); h.counts[i === -1 ? buckets.length : i]++; h.sum += s; h.n++; };\nlet seed = 7; const rand = () => (seed = (seed * 16807) % 2147483647) / 2147483647;\nfor (let i = 0; i < 1000; i++) observe(Math.exp(-2.4 + rand() * 2.2) * (rand() < 0.02 ? 6 : 1));   // fast, with a slow tail\n\nlet cum = 0;\nconst lines = buckets.map((b, i) => `http_request_duration_seconds_bucket{route=\"/orders/:id\",le=\"${b}\"} ${(cum += h.counts[i])}`);\nlines.push(`http_request_duration_seconds_bucket{route=\"/orders/:id\",le=\"+Inf\"} ${h.n}`);\nlines.push(`http_request_duration_seconds_sum{route=\"/orders/:id\"} ${h.sum.toFixed(2)}`, `http_request_duration_seconds_count{route=\"/orders/:id\"} ${h.n}`);\nconsole.log(\"# TYPE http_request_duration_seconds histogram\\n\" + lines.join(\"\\n\"));\nconst p95bucket = buckets.find((b, i) => h.counts.slice(0, i + 1).reduce((a, c) => a + c, 0) >= 0.95 * h.n);\nconsole.log(`≈ p95 ≤ ${p95bucket}s`);",
     "node": 1
    },
    {
     "h": {
      "ar": "OpenTelemetry",
      "en": "OpenTelemetry"
     },
     "p": {
      "ar": "**opentelemetry** لـ Node: auto-instrumentation لـ http وExpress وpg وundici (fetch) — بتشوف كل طلب كشجرة spans عبر الخدمات (API ← Odoo ← worker). ابدأه قبل أي import تاني (`--import ./otel.mjs`)، وابعت لـ Tempo/Jaeger أو Grafana Cloud، بـ sampling.",
      "en": "**opentelemetry** for Node: auto-instrumentation for http, Express, pg and undici (fetch) — you see each request as a span tree across services (API → Odoo → worker). Start it before any other import (`--import ./otel.mjs`), and export to Tempo/Jaeger or Grafana Cloud, with sampling."
     },
     "ex": "// otel.mjs — loaded with: node --import ./otel.mjs dist/server.js\nimport { NodeSDK } from \"@opentelemetry/sdk-node\";\nimport { getNodeAutoInstrumentations } from \"@opentelemetry/auto-instrumentations-node\";\nimport { OTLPTraceExporter } from \"@opentelemetry/exporter-trace-otlp-http\";\nimport { TraceIdRatioBasedSampler, ParentBasedSampler } from \"@opentelemetry/sdk-trace-base\";\n\nnew NodeSDK({\n  serviceName: \"shop-api\",\n  traceExporter: new OTLPTraceExporter({ url: process.env.OTEL_EXPORTER_OTLP_ENDPOINT + \"/v1/traces\" }),\n  sampler: new ParentBasedSampler({ root: new TraceIdRatioBasedSampler(0.2) }),\n  instrumentations: [getNodeAutoInstrumentations({ \"@opentelemetry/instrumentation-fs\": { enabled: false } })],\n}).start();",
     "lang": "js"
    },
    {
     "h": {
      "ar": "تتبع الأخطاء",
      "en": "Error tracking"
     },
     "p": {
      "ar": "**error tracking** (**sentry** أو بدائل مفتوحة زي GlitchTip): كل exception بيتجمّع مع أمثاله، ومعاه الـ stack والطلب والإصدار، وبتعرف «خطأ جديد بعد نشر 1.9.0». ارفع **source maps** عشان الـ stack يبان بأسطر TypeScript الأصلية — ومتنشرهاش للعامة.",
      "en": "**error tracking** (**sentry** or open alternatives like GlitchTip): every exception is grouped with similar ones, with the stack, the request and the release, so you know «a new error after deploying 1.9.0». Upload **source maps** so stacks show original TypeScript lines — and do not publish them publicly."
     },
     "ex": "import * as Sentry from \"@sentry/node\";\n\nSentry.init({\n  dsn: process.env.SENTRY_DSN,\n  release: process.env.APP_VERSION,            // «new in 1.9.0» alerts\n  environment: process.env.APP_ENV,\n  tracesSampleRate: 0.1,\n  beforeSend(event) {                         // never send PII\n    delete event.request?.cookies;\n    if (event.request?.headers) delete event.request.headers.authorization;\n    return event;\n  },\n});\nSentry.setupExpressErrorHandler(app);          // after the routes\n// CI: upload source maps for this release, then delete them from the deployed image",
     "lang": "js"
    }
   ],
   "practice": [
    {
     "ar": "اعرض /metrics بـ prom-client ومقاييس Node.",
     "en": "Expose /metrics with prom-client and Node metrics."
    },
    {
     "ar": "اعمل dashboard RED في Grafana.",
     "en": "Build a RED dashboard in Grafana."
    },
    {
     "ar": "شغّل OpenTelemetry وشوف trace لطلب.",
     "en": "Run OpenTelemetry and view a request trace."
    },
    {
     "ar": "ضيف Sentry بـ beforeSend وsource maps.",
     "en": "Add Sentry with beforeSend and source maps."
    }
   ],
   "words": [
    {
     "t": "metrics",
     "m": {
      "ar": "مقاييس رقمية مع الوقت",
      "en": "numbers tracked over time"
     },
     "ex": "Metrics show the trend."
    },
    {
     "t": "histogram",
     "m": {
      "ar": "توزيع قيم في buckets",
      "en": "a distribution in buckets"
     },
     "ex": "Latency is a histogram."
    },
    {
     "t": "prometheus",
     "m": {
      "ar": "نظام مقاييس بيسحب من /metrics",
      "en": "a metrics system scraping /metrics"
     },
     "ex": "Prometheus scrapes every 15 s."
    },
    {
     "t": "prom-client",
     "m": {
      "ar": "مكتبة مقاييس Prometheus لـ Node",
      "en": "the Prometheus client for Node"
     },
     "ex": "prom-client exposes event-loop lag."
    },
    {
     "t": "opentelemetry",
     "m": {
      "ar": "معيار المراقبة المفتوح",
      "en": "the open observability standard"
     },
     "ex": "OpenTelemetry traces the Odoo call."
    },
    {
     "t": "error tracking",
     "m": {
      "ar": "تجميع وتتبع الأخطاء",
      "en": "grouping and tracking exceptions"
     },
     "ex": "Error tracking flagged a new bug."
    },
    {
     "t": "sentry",
     "m": {
      "ar": "خدمة تتبع أخطاء",
      "en": "an error-tracking service"
     },
     "ex": "Sentry groups the TypeError."
    },
    {
     "t": "source maps",
     "m": {
      "ar": "خرايط للكود الأصلي",
      "en": "maps from built code to source"
     },
     "ex": "Upload source maps privately."
    }
   ],
   "read": [
    {
     "t": "OpenTelemetry JavaScript",
     "url": "https://opentelemetry.io/docs/languages/js/",
     "what": {
      "ar": "اقرا Getting Started (Node.js).",
      "en": "Read Getting Started (Node.js)."
     }
    }
   ],
   "challenge": {
    "ar": "ضيف المراقبة لخدمة المتجر: /metrics بـ RED لكل route ومقاييس Node وbusiness counters، dashboard في Grafana، OpenTelemetry بـ sampling 20%، وSentry بالإصدار وsource maps خاصة — ولاقي أبطأ نداء في trace حقيقي.",
    "en": "Add monitoring to the shop service: /metrics with RED per route, Node metrics and business counters, a Grafana dashboard, OpenTelemetry with 20% sampling, and Sentry with the release and private source maps — and find the slowest call in a real trace."
   },
   "quiz": [
    {
     "q": {
      "ar": "p95 من:",
      "en": "p95 comes from:"
     },
     "o": [
      {
       "ar": "histogram",
       "en": "a histogram"
      },
      {
       "ar": "counter",
       "en": "a counter"
      },
      {
       "ar": "اللوج بس",
       "en": "logs only"
      }
     ],
     "a": 0,
     "why": {
      "ar": "توزيع.",
      "en": "Distribution."
     }
    },
    {
     "q": {
      "ar": "OpenTelemetry يتحمّل:",
      "en": "OpenTelemetry is loaded:"
     },
     "o": [
      {
       "ar": "قبل أي import تاني",
       "en": "before any other import"
      },
      {
       "ar": "آخر حاجة",
       "en": "last"
      },
      {
       "ar": "في المتصفح بس",
       "en": "only in the browser"
      }
     ],
     "a": 0,
     "why": {
      "ar": "instrumentation.",
      "en": "Instrumentation."
     }
    },
    {
     "q": {
      "ar": "source maps:",
      "en": "Source maps:"
     },
     "o": [
      {
       "ar": "ترفعها لـ Sentry ومتنشرهاش للعامة",
       "en": "upload to Sentry, don’t publish"
      },
      {
       "ar": "انشرها للكل",
       "en": "publish to all"
      },
      {
       "ar": "متعملهاش",
       "en": "never create them"
      }
     ],
     "a": 0,
     "why": {
      "ar": "خاص.",
      "en": "Private."
     }
    }
   ],
   "minutes": 120
  },
  {
   "d": 5,
   "title": {
    "ar": "SLOs والتنبيهات",
    "en": "SLOs and alerts"
   },
   "goal": {
    "ar": "تنبيهات قليلة وكلها مهمة.",
    "en": "Few alerts, all meaningful."
   },
   "learn": [
    {
     "h": {
      "ar": "SLO وميزانية الأخطاء",
      "en": "SLO and error budget"
     },
     "p": {
      "ar": "**slo** = هدف من وجهة نظر المستخدم («99.5% من طلبات الدفع تنجح في أقل من ثانية خلال 30 يوم»). الفرق لـ 100% = **error budget**. لو الميزانية بتخلص: وقّف الميزات الخطرة وركّز على الاعتمادية. والتنبيه على سرعة صرف الميزانية (burn rate) مش على CPU.",
      "en": "An **slo** = a target from the user’s view («99.5% of payment requests succeed in under a second over 30 days»). The gap to 100% = the **error budget**. If the budget is running out: pause risky features and focus on reliability. And alert on how fast the budget burns (burn rate), not on CPU."
     },
     "ex": "const slo = 0.995;\nconst windowRequests = 420_000, bad = 1_470;\nconst budget = Math.round((1 - slo) * windowRequests);\nconsole.log(`SLI ${(100 * (1 - bad / windowRequests)).toFixed(2)}% · budget ${budget} bad requests · used ${(100 * bad / budget).toFixed(0)}%`);\n\nconst burn = (errorRatio) => errorRatio / (1 - slo);\nfor (const [window, ratio] of [[\"5 min\", 0.09], [\"1 h\", 0.075], [\"6 h\", 0.02], [\"3 days\", 0.004]]) {\n  const b = burn(ratio);\n  console.log(`${window.padEnd(6)} error ratio ${(ratio * 100).toFixed(1)}% → burn ${b.toFixed(1)}× → ${b >= 14 ? \"PAGE\" : b >= 3 ? \"ticket\" : \"ok\"}`);\n}",
     "node": 1
    },
    {
     "h": {
      "ar": "فحوصات من برّه وheartbeats",
      "en": "External checks and heartbeats"
     },
     "p": {
      "ar": "**uptime monitoring** و**synthetic check**: سكربت من برّه بيعمل اللي العميل بيعمله كل دقيقة (يفتح الصفحة، يعمل طلب تجربة). وللمهام المجدولة: heartbeat بعد كل تشغيل ناجح؛ لو اتأخر = تنبيه — ده بيمسك cron وقف بصمت. المثال بيفحص heartbeats.",
      "en": "**uptime monitoring** and a **synthetic check**: a script from outside doing what a customer does every minute (open the page, place a test order). For scheduled jobs: a heartbeat after each successful run; if it is late = an alert — this catches a cron that stopped silently. The example checks heartbeats."
     },
     "ex": "const now = Date.parse(\"2026-10-04T09:40:00Z\");\nconst jobs = [\n  { name: \"daily-report\", everyMin: 1440, last: \"2026-10-04T04:01:00Z\" },\n  { name: \"sync-odoo\", everyMin: 15, last: \"2026-10-04T09:31:00Z\" },\n  { name: \"backup-db\", everyMin: 1440, last: \"2026-10-02T02:00:00Z\" },\n  { name: \"price-watch\", everyMin: 60, last: \"2026-10-04T08:10:00Z\" },\n];\nfor (const j of jobs) {\n  const lateMin = (now - Date.parse(j.last)) / 60000 - j.everyMin;\n  const status = lateMin > j.everyMin * 0.25 ? `ALERT: ${Math.round(lateMin)} min overdue` : \"ok\";\n  console.log(j.name.padEnd(13), status);\n}",
     "node": 1
    },
    {
     "h": {
      "ar": "on-call والـ postmortem",
      "en": "On-call and the postmortem"
     },
     "p": {
      "ar": "**alert** واحد = حد هيعمل حاجة؛ لو محدش بيتصرف عليه، امسحه. **on-call**: مين بيستلم بالليل، وrunbook لكل تنبيه. وبعد أي حادثة: **postmortem** من غير لوم — الترتيب الزمني، ليه النظام سمح بيه، وإجراءات بمسؤولين ومواعيد.",
      "en": "One **alert** = someone will act; if nobody acts on it, delete it. **on-call**: who receives it at night, and a runbook for each alert. And after any incident: a blameless **postmortem** — the timeline, why the system allowed it, and actions with owners and dates."
     },
     "ex": "alert: payments-burn-rate-fast\nwhen      burn rate ≥ 14× over 5 min AND 1 h\nwho       on-call (PagerDuty / Telegram group)\nrunbook   1. check Paymob status page  2. check last deploy → roll back by digest if < 2 h old\n          3. switch checkout banner «card payments delayed — cash on delivery available»\npostmortem (blameless) within 3 days: timeline · impact · why the system allowed it · 3 actions with owners",
     "lang": "text"
    }
   ],
   "practice": [
    {
     "ar": "اكتب SLO لأهم مسار (الدفع أو الطلب).",
     "en": "Write an SLO for the most important path (payment or ordering)."
    },
    {
     "ar": "حط تنبيهات burn rate بدل CPU.",
     "en": "Set burn-rate alerts instead of CPU alerts."
    },
    {
     "ar": "ضيف synthetic check وheartbeat لكل cron.",
     "en": "Add a synthetic check and a heartbeat for every cron."
    },
    {
     "ar": "اكتب runbook لكل تنبيه.",
     "en": "Write a runbook for each alert."
    }
   ],
   "words": [
    {
     "t": "slo",
     "m": {
      "ar": "هدف مستوى الخدمة",
      "en": "a service level objective"
     },
     "ex": "Our SLO is 99.5% over 30 days."
    },
    {
     "t": "error budget",
     "m": {
      "ar": "ميزانية الأخطاء المسموحة",
      "en": "the failures an SLO allows"
     },
     "ex": "We used 70% of the error budget."
    },
    {
     "t": "burn rate",
     "m": {
      "ar": "سرعة صرف الميزانية",
      "en": "how fast the error budget is spent"
     },
     "ex": "A 14× burn rate pages on-call."
    },
    {
     "t": "uptime monitoring",
     "m": {
      "ar": "مراقبة إن الخدمة شغالة",
      "en": "checking a service is reachable"
     },
     "ex": "Uptime monitoring pings /livez."
    },
    {
     "t": "synthetic check",
     "m": {
      "ar": "فحص بيقلّد المستخدم",
      "en": "a scripted user journey check"
     },
     "ex": "A synthetic check places a test order."
    },
    {
     "t": "alert",
     "m": {
      "ar": "تنبيه",
      "en": "a notification needing action"
     },
     "ex": "Every alert has a runbook."
    },
    {
     "t": "on-call",
     "m": {
      "ar": "المناوبة",
      "en": "being responsible for responding to alerts"
     },
     "ex": "On-call rotates weekly."
    },
    {
     "t": "postmortem",
     "m": {
      "ar": "تحليل ما بعد الحادثة",
      "en": "a review after an incident"
     },
     "ex": "The postmortem listed three actions."
    }
   ],
   "read": [
    {
     "t": "Google SRE Workbook: Alerting on SLOs",
     "url": "https://sre.google/workbook/alerting-on-slos/",
     "what": {
      "ar": "اقرا Burn rate.",
      "en": "Read Burn rate."
     }
    }
   ],
   "challenge": {
    "ar": "اعمل نظام تنبيهات لخدمة المتجر: SLO للدفع وواحد للـ API، تنبيهات burn rate (page وticket)، synthetic check كل 5 دقايق، heartbeat لكل cron، runbook لكل تنبيه، وتمرين حادثة بـ postmortem — وامسح أي تنبيه محدش بيتصرف عليه.",
    "en": "Build alerting for the shop service: an SLO for payments and one for the API, burn-rate alerts (page and ticket), a 5-minute synthetic check, a heartbeat for every cron, a runbook for every alert, and an incident drill with a postmortem — and delete any alert nobody acts on."
   },
   "quiz": [
    {
     "q": {
      "ar": "SLO 99.5% على 400 ألف طلب:",
      "en": "A 99.5% SLO over 400,000 requests:"
     },
     "o": [
      {
       "ar": "ميزانية 2000 طلب فاشل",
       "en": "a budget of 2,000 failed requests"
      },
      {
       "ar": "صفر",
       "en": "zero"
      },
      {
       "ar": "200 ألف",
       "en": "200,000"
      }
     ],
     "a": 0,
     "why": {
      "ar": "0.5%.",
      "en": "0.5%."
     }
    },
    {
     "q": {
      "ar": "تنبيه CPU 80% بالليل:",
      "en": "A CPU-80% alert at night:"
     },
     "o": [
      {
       "ar": "غالبًا متصحّيش حد",
       "en": "usually don’t page"
      },
      {
       "ar": "page فورًا",
       "en": "page at once"
      },
      {
       "ar": "أهم تنبيه",
       "en": "the most important alert"
      }
     ],
     "a": 0,
     "why": {
      "ar": "أعراض.",
      "en": "Symptoms."
     }
    },
    {
     "q": {
      "ar": "cron وقف بصمت:",
      "en": "A cron stopped silently:"
     },
     "o": [
      {
       "ar": "heartbeat",
       "en": "a heartbeat"
      },
      {
       "ar": "اللوج بس",
       "en": "only logs"
      },
      {
       "ar": "مستحيل يتكشف",
       "en": "undetectable"
      }
     ],
     "a": 0,
     "why": {
      "ar": "إشارة.",
      "en": "Signal."
     }
    }
   ],
   "minutes": 120
  },
  {
   "d": 6,
   "title": {
    "ar": "مراجعة الأسبوع ومشروعه",
    "en": "Week review and project"
   },
   "goal": {
    "ar": "من commit لإنتاج مراقَب.",
    "en": "From commit to monitored production."
   },
   "review": [
    {
     "ar": "CI بـ matrix وكاش وخدمات وbranch protection وrelease-please.",
     "en": "CI with matrices, caching, services, branch protection and release-please."
    },
    {
     "ar": "البيئات والموافقة وOIDC والـ previews.",
     "en": "Environments, approval, OIDC and previews."
    },
    {
     "ar": "pino وredact وAsyncLocalStorage.",
     "en": "pino, redact and AsyncLocalStorage."
    },
    {
     "ar": "prom-client وOpenTelemetry وSentry.",
     "en": "prom-client, OpenTelemetry and Sentry."
    },
    {
     "ar": "SLOs وburn rate وheartbeats والـ postmortems.",
     "en": "SLOs, burn rates, heartbeats and postmortems."
    }
   ],
   "project": {
    "ar": "مشروع الأسبوع «خط تسليم ومراقبة» لخدمة المتجر: CI بـ lint وtsc وmatrix وintegration بـ Postgres، branch protection، release-please، صورة بـ digest لـ staging تلقائي وproduction بموافقة وOIDC، pino بـ redact وrequest id عبر AsyncLocalStorage، /metrics وdashboard، OpenTelemetry وSentry، SLOs بتنبيهات burn rate وheartbeats وrunbooks — وتمرين حادثة بـ postmortem.",
    "en": "Week project «delivery and monitoring pipeline» for the shop service: CI with lint, tsc, a matrix and integration with Postgres, branch protection, release-please, an image by digest to automatic staging and approved production with OIDC, pino with redact and a request id via AsyncLocalStorage, /metrics and a dashboard, OpenTelemetry and Sentry, SLOs with burn-rate alerts, heartbeats and runbooks — and an incident drill with a postmortem."
   },
   "test": [
    {
     "q": {
      "ar": "matrix:",
      "en": "A matrix:"
     },
     "o": [
      {
       "ar": "تشغيل على تركيبات نسخ وأنظمة",
       "en": "runs across version/OS combinations"
      },
      {
       "ar": "جدول بيانات",
       "en": "a data table"
      },
      {
       "ar": "فيلم",
       "en": "a film"
      }
     ],
     "a": 0,
     "why": {
      "ar": "تغطية.",
      "en": "Coverage."
     }
    },
    {
     "q": {
      "ar": "concurrency بـ cancel-in-progress:",
      "en": "concurrency with cancel-in-progress:"
     },
     "o": [
      {
       "ar": "يلغي التشغيل القديم لنفس الفرع",
       "en": "cancels older runs on the same branch"
      },
      {
       "ar": "يشغّل أكتر",
       "en": "runs more"
      },
      {
       "ar": "يمسح الفرع",
       "en": "deletes the branch"
      }
     ],
     "a": 0,
     "why": {
      "ar": "توفير.",
      "en": "Saving."
     }
    },
    {
     "q": {
      "ar": "services: postgres في CI:",
      "en": "services: postgres in CI:"
     },
     "o": [
      {
       "ar": "قاعدة حقيقية لاختبارات التكامل",
       "en": "a real database for integration tests"
      },
      {
       "ar": "إنتاج",
       "en": "production"
      },
      {
       "ar": "mock",
       "en": "a mock"
      }
     ],
     "a": 0,
     "why": {
      "ar": "تكامل.",
      "en": "Integration."
     }
    },
    {
     "q": {
      "ar": "release please:",
      "en": "release please:"
     },
     "o": [
      {
       "ar": "PR بالإصدار والـ changelog",
       "en": "a PR with the version and changelog"
      },
      {
       "ar": "يطلب إذن",
       "en": "asks permission"
      },
      {
       "ar": "يحذف الإصدارات",
       "en": "deletes releases"
      }
     ],
     "a": 0,
     "why": {
      "ar": "آلي.",
      "en": "Automated."
     }
    },
    {
     "q": {
      "ar": "production environment بـ reviewers:",
      "en": "A production environment with reviewers:"
     },
     "o": [
      {
       "ar": "بيستنى موافقة",
       "en": "waits for approval"
      },
      {
       "ar": "بينشر فورًا",
       "en": "deploys at once"
      },
      {
       "ar": "مش بينشر",
       "en": "never deploys"
      }
     ],
     "a": 0,
     "why": {
      "ar": "بوابة.",
      "en": "Gate."
     }
    },
    {
     "q": {
      "ar": "OIDC:",
      "en": "OIDC:"
     },
     "o": [
      {
       "ar": "توكن مؤقت لريبو وبيئة",
       "en": "a short-lived token for a repo and environment"
      },
      {
       "ar": "مفتاح دائم",
       "en": "a permanent key"
      },
      {
       "ar": "كلمة سر",
       "en": "a password"
      }
     ],
     "a": 0,
     "why": {
      "ar": "مؤقت.",
      "en": "Short-lived."
     }
    },
    {
     "q": {
      "ar": "pino:",
      "en": "pino:"
     },
     "o": [
      {
       "ar": "logger JSON سريع",
       "en": "a fast JSON logger"
      },
      {
       "ar": "قاعدة بيانات",
       "en": "a database"
      },
      {
       "ar": "framework",
       "en": "a framework"
      }
     ],
     "a": 0,
     "why": {
      "ar": "لوج.",
      "en": "Logs."
     }
    },
    {
     "q": {
      "ar": "AsyncLocalStorage:",
      "en": "AsyncLocalStorage:"
     },
     "o": [
      {
       "ar": "قيمة لكل طلب عبر الـ async",
       "en": "a per-request value across async work"
      },
      {
       "ar": "localStorage في Node",
       "en": "localStorage in Node"
      },
      {
       "ar": "كاش",
       "en": "a cache"
      }
     ],
     "a": 0,
     "why": {
      "ar": "سياق.",
      "en": "Context."
     }
    },
    {
     "q": {
      "ar": "label بقيمة orderId في Prometheus:",
      "en": "A label holding orderId in Prometheus:"
     },
     "o": [
      {
       "ar": "غلط: cardinality عالي",
       "en": "wrong: high cardinality"
      },
      {
       "ar": "ممتاز",
       "en": "excellent"
      },
      {
       "ar": "إجباري",
       "en": "required"
      }
     ],
     "a": 0,
     "why": {
      "ar": "سلاسل.",
      "en": "Series."
     }
    },
    {
     "q": {
      "ar": "Sentry release:",
      "en": "The Sentry release:"
     },
     "o": [
      {
       "ar": "يعرّف «خطأ جديد بعد نشر»",
       "en": "reveals «new error after a deploy»"
      },
      {
       "ar": "اسم الشركة",
       "en": "the company name"
      },
      {
       "ar": "مش مهم",
       "en": "unimportant"
      }
     ],
     "a": 0,
     "why": {
      "ar": "إصدار.",
      "en": "Version."
     }
    },
    {
     "q": {
      "ar": "burn rate 14×:",
      "en": "A 14× burn rate:"
     },
     "o": [
      {
       "ar": "page",
       "en": "page"
      },
      {
       "ar": "تجاهل",
       "en": "ignore"
      },
      {
       "ar": "إيميل الشهر الجاي",
       "en": "an email next month"
      }
     ],
     "a": 0,
     "why": {
      "ar": "خطر.",
      "en": "Danger."
     }
    },
    {
     "q": {
      "ar": "تنبيه محدش بيتصرف عليه:",
      "en": "An alert nobody acts on:"
     },
     "o": [
      {
       "ar": "امسحه",
       "en": "delete it"
      },
      {
       "ar": "ضاعفه",
       "en": "duplicate it"
      },
      {
       "ar": "سيبه",
       "en": "keep it"
      }
     ],
     "a": 0,
     "why": {
      "ar": "ضوضاء.",
      "en": "Noise."
     }
    }
   ],
   "minutes": 120
  }
 ]
});
