// Python week 12 — PDF, Word, images, email and the month project.
const B = (ar, en) => ({ ar, en });
module.exports = {
  level: B('متوسط', 'Intermediate'),
  title: B('PDF وWord والصور والإيميل ومشروع الشهر', 'PDF, Word, images, email and the month project'),
  goal: B('تقرا وتدمج وتقسّم ملفات PDF، وتعمل مستندات Word من قوالب، وتعالج مئات الصور مرة واحدة، وتبعت إيميلات بمرفقات بأمان، وتطلّع فواتير PDF — وتجمع ده كله في مشروع الشهر التالت: مولّد ومُرسِل الفواتير.',
          'Read, merge and split PDF files, create Word documents from templates, process hundreds of images at once, send emails with attachments safely, and produce PDF invoices — then bring it all together in the month 3 project: an invoice generator and sender.'),
  days: [
    { title: B('ملفات PDF', 'PDF files'),
      goal: B('تقرا النص من PDF، وتدمج ملفات، وتقسّم وتلف صفحات، وتعرف ليه PDF الممسوح ضوئيًا محتاج OCR.', 'Read text from a PDF, merge files, split and rotate pages, and know why a scanned PDF needs OCR.'),
      learn: [
        { h: B('قراءة النص', 'Reading the text'),
          p: B('`pip install pypdf`. `PdfReader("file.pdf")` و`len(reader.pages)` عدد الصفحات، و`page.extract_text()` النص. النص بيطلع زي ما هو مرسوم في الملف، فممكن الأعمدة والجداول تتلخبط — نضّفه بـ Regex (أسبوع 10). ولو `extract_text()` رجّعت فاضي، غالبًا الملف صور ممسوحة ومحتاج OCR (زي Tesseract) مش pypdf.', '`pip install pypdf`. `PdfReader("file.pdf")`, `len(reader.pages)` for the page count, and `page.extract_text()` for the text. Text comes out as it is drawn in the file, so columns and tables can get mixed up — clean it with regex (week 10). If `extract_text()` returns nothing, the file is probably scanned images and needs OCR (such as Tesseract), not pypdf.'),
          ex: '# pip install pypdf\nfrom pypdf import PdfReader\n\nreader = PdfReader("invoice.pdf")\nprint(len(reader.pages), "pages", reader.metadata.title if reader.metadata else "")\nfor n, page in enumerate(reader.pages, 1):\n    text = page.extract_text() or ""\n    print(f"--- page {n}: {len(text)} characters")\n    print(text[:300])' },
        { h: B('دمج وتقسيم', 'Merging and splitting'),
          p: B('`PdfWriter()` و`writer.append("a.pdf")` يضيف ملف كامل (أو صفحات معيّنة بـ `pages=(0, 3)`)، و`writer.write("out.pdf")`. التقسيم: لف على الصفحات واعمل writer لكل صفحة. و`page.rotate(90)` يلف صفحة متصوّرة بالعرض.', '`PdfWriter()`, then `writer.append("a.pdf")` adds a whole file (or chosen pages with `pages=(0, 3)`), and `writer.write("out.pdf")`. To split: loop over the pages and make a writer per page. `page.rotate(90)` turns a page scanned sideways.'),
          ex: 'from pathlib import Path\nfrom pypdf import PdfReader, PdfWriter\n\n# merge every PDF in a folder, in name order\nwriter = PdfWriter()\nfor pdf in sorted(Path("invoices").glob("*.pdf")):\n    writer.append(str(pdf))\nwriter.write("all_invoices.pdf")\n\n# split a file into one PDF per page\nreader = PdfReader("all_invoices.pdf")\nfor i, page in enumerate(reader.pages, 1):\n    w = PdfWriter()\n    w.add_page(page)\n    w.write(f"page_{i:03}.pdf")' },
        { h: B('نص من فواتير PDF', 'Data out of PDF invoices'),
          p: B('الشغل الحقيقي: 200 فاتورة PDF من مورّد، عايز منها رقم الفاتورة والتاريخ والإجمالي في Excel. اقرا النص، طلّع الحقول بـ Regex بأسماء، وحط اللي مطابقش في قايمة مراجعة يدوية. ولو الفواتير ممسوحة ضوئيًا، n8n والـ AI (أسبوع 23) بيقروها أحسن.', 'The real job: 200 PDF invoices from a supplier, and you want the invoice number, date and total in Excel. Read the text, extract the fields with named regex groups, and put the ones that did not match on a manual-review list. If the invoices are scanned, n8n and AI (week 23) read them better.'),
          ex: 'import re\nfrom pathlib import Path\nfrom pypdf import PdfReader\n\nFIELDS = {\n    "number": re.compile(r"Invoice\\s*(?:No\\.?|#)\\s*([A-Z0-9-]+)", re.I),\n    "date": re.compile(r"Date[:\\s]+(\\d{4}-\\d{2}-\\d{2}|\\d{2}/\\d{2}/\\d{4})", re.I),\n    "total": re.compile(r"Total[:\\s]+([\\d,]+\\.\\d{2})", re.I),\n}\nrows, review = [], []\nfor pdf in sorted(Path("invoices").glob("*.pdf")):\n    text = "\\n".join(p.extract_text() or "" for p in PdfReader(pdf).pages)\n    found = {k: (m.group(1) if (m := rx.search(text)) else None) for k, rx in FIELDS.items()}\n    (rows if all(found.values()) else review).append({"file": pdf.name, **found})\nprint(len(rows), "read,", len(review), "need a human")' }
      ],
      practice: [
        B('ثبّت pypdf واطبع عدد صفحات وأول 200 حرف من 3 ملفات PDF عندك.', 'Install pypdf and print the page count and first 200 characters of 3 PDFs you have.'),
        B('ادمج 3 ملفات PDF في ملف واحد بالترتيب اللي تختاره.', 'Merge 3 PDFs into one in the order you choose.'),
        B('طلّع الصفحات من 2 لـ 4 من ملف لملف جديد.', 'Extract pages 2 to 4 of a file into a new file.'),
        B('جرّب `extract_text()` على PDF ممسوح ضوئيًا وشوف إنها بترجّع فاضي.', 'Try `extract_text()` on a scanned PDF and see it return nothing.')
      ],
      code: [
        { u: B('بحث في كل ملفات PDF', 'Searching every PDF'), p: 'from pathlib import Path\nfrom pypdf import PdfReader\n\ndef search_pdfs(folder, word):\n    for pdf in Path(folder).rglob("*.pdf"):\n        try:\n            reader = PdfReader(pdf)\n        except Exception as e:\n            print("cannot read", pdf, e)\n            continue\n        for n, page in enumerate(reader.pages, 1):\n            if word.lower() in (page.extract_text() or "").lower():\n                print(f"{pdf.name}: page {n}")\n\nsearch_pdfs("Documents", "contract")' }
      ],
      words: [
        { t: 'PDF', m: B('شكل مستندات ثابت بيتعرض بنفس الشكل في كل مكان', 'a fixed document format that looks the same everywhere'), ex: 'invoice.pdf' },
        { t: 'pypdf', m: B('مكتبة Python لقراءة ودمج وتقسيم ملفات PDF', 'a Python library to read, merge and split PDFs'), ex: 'from pypdf import PdfReader' },
        { t: 'text extraction', m: B('سحب النص المكتوب من جوه ملف', 'pulling the written text out of a file'), ex: 'page.extract_text()' },
        { t: 'OCR', m: B('قراءة النص من صورة أو ملف ممسوح ضوئيًا', 'reading text from an image or a scanned file'), ex: 'Tesseract, AI vision' },
        { t: 'scanned PDF', m: B('PDF عبارة عن صور صفحات من غير نص حقيقي', 'a PDF made of page images with no real text'), ex: 'extract_text() returns ""' },
        { t: 'PdfWriter', m: B('بيبني ملف PDF جديد من صفحات', 'builds a new PDF from pages'), ex: 'writer.append("a.pdf")' }
      ],
      read: [{ lib: 'pypdf documentation', what: B('اقرا Extract Text وMerging PDF files.', 'Read Extract Text and Merging PDF files.') }, { lib: 'Automate the Boring Stuff with Python', what: B('فصل PDF and Word Documents: جزء PDF.', 'The PDF and Word Documents chapter: the PDF part.') }],
      challenge: B('اكتب `pdf_tools.py` بأوامر: `merge out.pdf a.pdf b.pdf` و`split file.pdf` و`pages file.pdf 2-5` و`text file.pdf` (يكتب النص في .txt جنبه) — بـ argparse أو sys.argv، ورسايل خطأ واضحة.', 'Write `pdf_tools.py` with commands: `merge out.pdf a.pdf b.pdf`, `split file.pdf`, `pages file.pdf 2-5` and `text file.pdf` (writes the text to a .txt next to it) — with argparse or sys.argv and clear error messages.'),
      quiz: [
        { q: B('`extract_text()` رجّعت نص فاضي. الغالب:', '`extract_text()` returned empty text. Most likely:'), o: [B('الملف صور ممسوحة ومحتاج OCR', 'the file is scanned images and needs OCR'), B('pypdf قديمة', 'pypdf is old'), B('الملف فاضي', 'the file is blank')], a: 0, why: B('مفيش طبقة نص.', 'There is no text layer.') },
        { q: B('عشان تدمج ملفات PDF:', 'To merge PDF files:'), o: ['PdfWriter + append', 'PdfReader + extract_text', 'open(..., "a")'], a: 0, why: B('writer بيجمع الصفحات.', 'A writer collects pages.') },
        { q: B('أول صفحة في `reader.pages`:', 'The first page in `reader.pages`:'), o: ['reader.pages[0]', 'reader.pages[1]', 'reader.page(1)'], a: 0, why: B('بتبدأ من صفر.', 'It starts at zero.') }
      ] },

    { title: B('مستندات Word', 'Word documents'),
      goal: B('تعمل ملف Word بعناوين وفقرات وجداول وصور، وتملا قالب Word جاهز (عقد أو خطاب) لكل عميل.', 'Create a Word file with headings, paragraphs, tables and images, and fill a ready Word template (a contract or a letter) for each customer.'),
      learn: [
        { h: B('مستند من الصفر', 'A document from scratch'),
          p: B('`pip install python-docx`. `doc = Document()`، و`doc.add_heading("Title", level=1)`، و`doc.add_paragraph("...")`، و`doc.add_picture("logo.png", width=Inches(1.5))`، و`doc.save("report.docx")`. الفقرة فيها runs: `p.add_run("bold").bold = True` عشان تنسّق كلمة جوه جملة.', '`pip install python-docx`. `doc = Document()`, `doc.add_heading("Title", level=1)`, `doc.add_paragraph("...")`, `doc.add_picture("logo.png", width=Inches(1.5))`, and `doc.save("report.docx")`. A paragraph is made of runs: `p.add_run("bold").bold = True` formats one word inside a sentence.'),
          ex: '# pip install python-docx\nfrom docx import Document\nfrom docx.shared import Pt\n\ndoc = Document()\ndoc.add_heading("Monthly sales report", level=1)\np = doc.add_paragraph("Revenue this month was ")\nrun = p.add_run("128,500 EGP")\nrun.bold = True\np.add_run(", up 12% on last month.")\ndoc.add_heading("Top cities", level=2)\nfor city in ["Cairo", "Alexandria", "Giza"]:\n    doc.add_paragraph(city, style="List Bullet")\ndoc.save("report.docx")' },
        { h: B('جداول', 'Tables'),
          p: B('`table = doc.add_table(rows=1, cols=3)` و`table.style = "Light Grid Accent 1"`، والصف الأول عناوين، وبعدين `row = table.add_row().cells` لكل سجل. ده بيحوّل أي قايمة dicts (من Excel أو API) لجدول Word في ثواني.', '`table = doc.add_table(rows=1, cols=3)` with `table.style = "Light Grid Accent 1"`; the first row holds headers, then `row = table.add_row().cells` for each record. This turns any list of dicts (from Excel or an API) into a Word table in seconds.'),
          ex: 'from docx import Document\n\nrows = [{"city": "Cairo", "orders": 42, "revenue": 128500.5}, {"city": "Giza", "orders": 18, "revenue": 40210}]\ndoc = Document()\ndoc.add_heading("Revenue by city", level=2)\ntable = doc.add_table(rows=1, cols=3)\ntable.style = "Light Grid Accent 1"\nfor cell, title in zip(table.rows[0].cells, ["City", "Orders", "Revenue"]):\n    cell.text = title\nfor r in rows:\n    cells = table.add_row().cells\n    cells[0].text = r["city"]\n    cells[1].text = str(r["orders"])\n    cells[2].text = f"{r[\'revenue\']:,.2f}"\ndoc.save("cities.docx")' },
        { h: B('تعبئة قالب', 'Filling a template'),
          p: B('اعمل القالب في Word بنفسك بالتنسيق اللي عايزه وحط أماكن زي `{{name}}` و`{{date}}`. السكربت يفتح القالب ويبدّل الأماكن في كل فقرة ويحفظ نسخة لكل عميل. ملاحظة: Word أحيانًا بيقسّم `{{name}}` على أكتر من run، فاكتب المكان مرة واحدة من غير تعديل في نصه. (مكتبة `docxtpl` بتعمل ده بشكل أقوى لو احتجت.)', 'Design the template in Word yourself with the formatting you want and put placeholders like `{{name}}` and `{{date}}`. The script opens the template, replaces the placeholders in every paragraph and saves a copy per customer. Note: Word sometimes splits `{{name}}` across several runs, so type each placeholder in one go without editing inside it. (The `docxtpl` library does this more robustly if you need it.)'),
          ex: 'from pathlib import Path\nfrom docx import Document\n\ndef fill(template, values, out):\n    doc = Document(template)\n    for p in doc.paragraphs:\n        for key, val in values.items():\n            mark = "{{" + key + "}}"\n            if mark in p.text:\n                for run in p.runs:\n                    run.text = run.text.replace(mark, str(val))\n    doc.save(out)\n\nPath("letters").mkdir(exist_ok=True)\nfor c in [{"name": "Sara Ahmed", "amount": "1,200.00", "date": "2026-10-01"}, {"name": "Omar Adel", "amount": "450.50", "date": "2026-10-01"}]:\n    fill("reminder_template.docx", c, Path("letters") / f"reminder_{c[\'name\'].replace(\' \', \'_\')}.docx")' }
      ],
      practice: [
        B('اعمل تقرير Word فيه عنوان وفقرتين وقايمة نقط وجدول من بيانات أسبوع 11.', 'Build a Word report with a title, two paragraphs, a bullet list and a table from week 11’s data.'),
        B('صمّم قالب خطاب تذكير بالدفع في Word بأماكن `{{name}}` و`{{amount}}` و`{{date}}`.', 'Design a payment-reminder letter template in Word with `{{name}}`, `{{amount}}` and `{{date}}`.'),
        B('املا القالب لـ 5 عملاء من CSV واتأكد إن التنسيق فضل زي ما هو.', 'Fill the template for 5 customers from a CSV and check the formatting stayed the same.'),
        B('اقرا مستند Word موجود واطبع كل العناوين بس (`p.style.name.startswith("Heading")`).', 'Read an existing Word document and print only its headings (`p.style.name.startswith("Heading")`).')
      ],
      code: [
        { u: B('فهرس مستند Word', 'An outline of a Word document'), p: 'from docx import Document\n\ndoc = Document("report.docx")\nfor p in doc.paragraphs:\n    if p.style.name.startswith("Heading"):\n        level = p.style.name.replace("Heading", "").strip() or "1"\n        print("  " * (int(level) - 1) + p.text)\nprint(len(doc.tables), "tables")' }
      ],
      words: [
        { t: 'python-docx', m: B('مكتبة لعمل وقراءة ملفات Word (docx)', 'a library to create and read Word (docx) files'), ex: 'from docx import Document' },
        { t: 'paragraph', m: B('فقرة في مستند Word', 'a paragraph in a Word document'), ex: 'doc.add_paragraph("...")' },
        { t: 'run', m: B('جزء من فقرة بتنسيق واحد', 'a piece of a paragraph with one formatting'), ex: 'p.add_run("bold").bold = True' },
        { t: 'heading', m: B('عنوان بمستوى (1 أكبر)', 'a title with a level (1 is the largest)'), ex: 'doc.add_heading("Title", level=1)' },
        { t: 'template', m: B('ملف جاهز فيه أماكن تتملي لكل حالة', 'a ready file with placeholders filled for each case'), ex: 'reminder_template.docx' },
        { t: 'placeholder', m: B('علامة في القالب بتتبدّل بقيمة', 'a marker in a template replaced by a value'), ex: '{{name}}' }
      ],
      read: [{ lib: 'python-docx documentation', what: B('اقرا Quickstart كله.', 'Read the whole Quickstart.') }, { lib: 'Automate the Boring Stuff with Python', what: B('فصل PDF and Word Documents: جزء Word.', 'The PDF and Word Documents chapter: the Word part.') }],
      challenge: B('اعمل «مولّد شهادات»: قالب Word شهادة حضور فيه الاسم والكورس والتاريخ، والسكربت ياخد قايمة 20 اسم من Excel ويطلّع شهادة لكل واحد في فولدر، بأسماء ملفات آمنة.', 'Build a «certificate generator»: a Word attendance-certificate template with the name, course and date; the script takes 20 names from Excel and produces a certificate for each in a folder, with safe file names.'),
      quiz: [
        { q: B('عشان تخلي كلمة واحدة bold جوه جملة:', 'To make one word bold inside a sentence:'), o: [B('run منفصل بـ bold=True', 'a separate run with bold=True'), B('فقرة جديدة', 'a new paragraph'), B('عنوان', 'a heading')], a: 0, why: B('التنسيق على مستوى الـ run.', 'Formatting lives at the run level.') },
        { q: B('أحسن طريقة لخطاب بتنسيق معيّن لـ 100 عميل:', 'The best way to make a styled letter for 100 customers:'), o: [B('قالب Word بأماكن تتملي', 'a Word template with placeholders'), B('تكتب التنسيق كله بالكود', 'code all the formatting'), B('نسخ ولزق', 'copy and paste')], a: 0, why: B('التصميم في Word والبيانات من Python.', 'Design in Word, data from Python.') },
        { q: B('`doc.add_table(rows=1, cols=3)` الصف الأول عادة:', 'In `doc.add_table(rows=1, cols=3)` the first row is usually:'), o: [B('العناوين', 'the headers'), B('الإجمالي', 'the total'), B('فاضي دايمًا', 'always empty')], a: 0, why: B('وبعدين add_row لكل سجل.', 'Then add_row for each record.') }
      ] },

    { title: B('الصور بالجملة بـ Pillow', 'Images in bulk with Pillow'),
      goal: B('تصغّر وتقص وتحوّل صيغ مئات الصور مرة واحدة، وتعمل صور مصغرة، وتحط علامة مائية، وتصلّح الصور اللي بتظهر مقلوبة.', 'Resize, crop and convert hundreds of images at once, make thumbnails, add a watermark, and fix photos that show up rotated.'),
      learn: [
        { h: B('فتح وتصغير وحفظ', 'Open, resize and save'),
          p: B('`pip install Pillow`. `img = Image.open("photo.jpg")`، `img.size` العرض والطول، و`img.thumbnail((800, 800))` تصغّر وتحافظ على النسبة (أهم دالة لصور المتاجر والسوشيال). احفظ بـ `img.save("out.jpg", quality=85, optimize=True)` تقلّل الحجم كتير من غير فرق واضح.', '`pip install Pillow`. `img = Image.open("photo.jpg")`, `img.size` gives width and height, and `img.thumbnail((800, 800))` shrinks while keeping the proportions (the key function for shop and social images). Save with `img.save("out.jpg", quality=85, optimize=True)` to cut the size a lot with no visible difference.'),
          ex: '# pip install Pillow\nfrom PIL import Image\n\nimg = Image.open("product.jpg")\nprint(img.size, img.mode, img.format)\nimg.thumbnail((800, 800))\nimg.save("product_800.jpg", quality=85, optimize=True)\nprint("new size:", img.size)' },
        { h: B('بالجملة وتحويل الصيغ', 'In bulk, and converting formats'),
          p: B('لف على الصور بـ glob، وصغّر كل واحدة، واحفظها في فولدر تاني بنفس الاسم. صور PNG فيها شفافية (RGBA) لازم تتحول `convert("RGB")` قبل ما تتحفظ JPG. وWebP صيغة أصغر للمواقع. وصور الموبايل فيها معلومة اتجاه (EXIF) — `ImageOps.exif_transpose(img)` بيلفّها صح قبل أي حاجة.', 'Loop over the images with glob, shrink each one, and save it in another folder with the same name. PNG images with transparency (RGBA) must be `convert("RGB")` before saving as JPG. WebP is a smaller format for websites. Phone photos carry an orientation tag (EXIF) — `ImageOps.exif_transpose(img)` rotates them correctly before anything else.'),
          ex: 'from pathlib import Path\nfrom PIL import Image, ImageOps\n\nsrc, out = Path("photos"), Path("web")\nout.mkdir(exist_ok=True)\nfor f in sorted(src.iterdir()):\n    if f.suffix.lower() not in {".jpg", ".jpeg", ".png", ".webp"}:\n        continue\n    with Image.open(f) as img:\n        img = ImageOps.exif_transpose(img)\n        img.thumbnail((1200, 1200))\n        img.convert("RGB").save(out / (f.stem + ".webp"), quality=80)\n    print("done", f.name)' },
        { h: B('قص وعلامة مائية', 'Crop and watermark'),
          p: B('`img.crop((left, top, right, bottom))` بيقص، و`ImageOps.fit(img, (600, 600))` بيقص من النص لمقاس مربع بالظبط (ممتاز لصور البروفايل والمنتجات). العلامة المائية: `ImageDraw.Draw(img).text(...)` بخط ولون شفاف، أو `img.paste(logo, position, logo)` للوجو.', '`img.crop((left, top, right, bottom))` crops, and `ImageOps.fit(img, (600, 600))` centre-crops to an exact square (great for profile and product pictures). For a watermark: `ImageDraw.Draw(img).text(...)` with a font and a see-through colour, or `img.paste(logo, position, logo)` for a logo.'),
          ex: 'from PIL import Image, ImageDraw, ImageFont, ImageOps\n\nimg = Image.open("product.jpg").convert("RGBA")\nsquare = ImageOps.fit(img, (800, 800))\nlayer = Image.new("RGBA", square.size, (0, 0, 0, 0))\ndraw = ImageDraw.Draw(layer)\nfont = ImageFont.load_default(size=36)\ndraw.text((20, 740), "© Nile Shop", font=font, fill=(255, 255, 255, 140))\nresult = Image.alpha_composite(square, layer).convert("RGB")\nresult.save("product_square.jpg", quality=88)' }
      ],
      practice: [
        B('صغّر 20 صورة لـ 1200 بكسل كحد أقصى في فولدر جديد وقارن الحجم قبل وبعد.', 'Shrink 20 images to at most 1200 pixels in a new folder and compare the sizes before and after.'),
        B('حوّل صور PNG شفافة لـ JPG وشوف ليه محتاج convert("RGB").', 'Convert transparent PNGs to JPG and see why convert("RGB") is needed.'),
        B('اعمل صور منتجات مربعة 800×800 بـ `ImageOps.fit`.', 'Make 800×800 square product images with `ImageOps.fit`.'),
        B('حط اسمك كعلامة مائية شفافة على 5 صور.', 'Put your name as a see-through watermark on 5 images.')
      ],
      code: [
        { u: B('تقرير أحجام الصور', 'An image size report'), p: 'from pathlib import Path\nfrom PIL import Image\n\nfor f in sorted(Path("photos").glob("*.*")):\n    try:\n        with Image.open(f) as img:\n            w, h = img.size\n        kb = f.stat().st_size / 1024\n        flag = "  <- too big" if kb > 500 or max(w, h) > 2000 else ""\n        print(f"{f.name:<28}{w:>6}x{h:<6}{kb:>8.0f} KB{flag}")\n    except OSError:\n        print(f"{f.name:<28} not an image")' }
      ],
      words: [
        { t: 'Pillow', m: B('مكتبة Python لمعالجة الصور (PIL)', 'Python’s image processing library (PIL)'), ex: 'from PIL import Image' },
        { t: 'thumbnail', m: B('نسخة مصغّرة بتحافظ على نسبة الصورة', 'a smaller copy keeping the image’s proportions'), ex: 'img.thumbnail((800, 800))' },
        { t: 'aspect ratio', m: B('نسبة العرض للطول', 'the ratio of width to height'), ex: '1200x800 is 3:2' },
        { t: 'EXIF', m: B('معلومات جوه الصورة: الكاميرا والتاريخ والاتجاه', 'data inside a photo: the camera, the date and the orientation'), ex: 'ImageOps.exif_transpose(img)' },
        { t: 'watermark', m: B('علامة أو اسم شفاف على الصورة', 'a faint mark or name over an image'), ex: '© Nile Shop' },
        { t: 'WebP', m: B('صيغة صور أصغر للمواقع', 'a smaller image format for websites'), ex: 'img.save("a.webp", quality=80)' },
        { t: 'RGBA', m: B('ألوان بقناة شفافية', 'colours with a transparency channel'), ex: 'PNG logos are often RGBA' }
      ],
      read: [{ lib: 'Pillow (PIL) documentation', what: B('اقرا Tutorial: Using the Image class وCreate JPEG thumbnails.', 'Read the Tutorial: Using the Image class and Create JPEG thumbnails.') }, { lib: 'Automate the Boring Stuff with Python', what: B('فصل Manipulating Images.', 'The Manipulating Images chapter.') }],
      challenge: B('اعمل `prepare_products.py`: ياخد فولدر صور منتجات (أي صيغة)، ويطلّع لكل صورة: نسخة 1200 WebP للموقع، ومربعة 800 JPG بالعلامة المائية للسوشيال، وصغيرة 300 للـ thumbnails، في 3 فولدرات، وتقرير CSV بالأحجام قبل وبعد.', 'Write `prepare_products.py`: take a folder of product images (any format) and produce for each: a 1200 WebP for the site, an 800 square JPG with the watermark for social media, and a 300 thumbnail, in 3 folders, plus a CSV report of sizes before and after.'),
      quiz: [
        { q: B('`thumbnail((800, 800))` على صورة 4000×2000:', '`thumbnail((800, 800))` on a 4000×2000 image gives:'), o: ['800×400', '800×800', '400×800'], a: 0, why: B('بتحافظ على النسبة.', 'It keeps the proportions.') },
        { q: B('حفظ صورة RGBA كـ JPG من غير تحويل:', 'Saving an RGBA image as JPG without converting:'), o: [B('خطأ؛ JPG مفيهوش شفافية', 'an error; JPG has no transparency'), B('بيتحفظ عادي', 'it saves fine'), B('بيتحفظ PNG', 'it saves as PNG')], a: 0, why: B('convert("RGB") الأول.', 'convert("RGB") first.') },
        { q: B('صورة موبايل بتظهر مقلوبة بعد المعالجة. الحل:', 'A phone photo appears rotated after processing. The fix:'), o: ['ImageOps.exif_transpose', 'img.crop', 'quality=100'], a: 0, why: B('بيطبّق اتجاه الـ EXIF.', 'It applies the EXIF orientation.') }
      ] },

    { title: B('الإيميل من Python', 'Email from Python'),
      goal: B('تبني إيميل بنص وHTML ومرفقات بـ EmailMessage، وتبعته بأمان عن طريق SMTP بكلمة سر تطبيقات من .env، وتعرف حدود الإرسال وتجرّب من غير ما تبعت فعلًا.', 'Build an email with text, HTML and attachments using EmailMessage, send it safely over SMTP with an app password from .env, and know the sending limits and how to test without really sending.'),
      learn: [
        { h: B('بناء الرسالة', 'Building the message'),
          p: B('`EmailMessage()` و`msg["Subject"]` و`msg["From"]` و`msg["To"]`، و`msg.set_content("نص عادي")` وبعدين `msg.add_alternative(html, subtype="html")` لنسخة HTML (البرامج اللي مبتعرضش HTML بتعرض النص). المرفق: `msg.add_attachment(data, maintype=..., subtype=..., filename=...)` و`mimetypes.guess_type` بيعرف النوع.', '`EmailMessage()`, then `msg["Subject"]`, `msg["From"]` and `msg["To"]`, `msg.set_content("plain text")`, then `msg.add_alternative(html, subtype="html")` for an HTML version (clients that cannot show HTML display the text). An attachment: `msg.add_attachment(data, maintype=..., subtype=..., filename=...)`, with `mimetypes.guess_type` working out the type.'),
          ex: 'import mimetypes\nfrom email.message import EmailMessage\nfrom pathlib import Path\n\nPath("report.csv").write_text("city,total\\nCairo,1200\\n", encoding="utf-8")\nmsg = EmailMessage()\nmsg["Subject"] = "Monthly report — September 2026"\nmsg["From"] = "reports@example.com"\nmsg["To"] = "boss@example.com"\nmsg.set_content("Hello,\\nThe September report is attached.\\nRegards")\nmsg.add_alternative("<p>Hello,</p><p>The <b>September</b> report is attached.</p>", subtype="html")\nctype = mimetypes.guess_type("report.csv")[0] or "application/octet-stream"\nmaintype, subtype = ctype.split("/")\nmsg.add_attachment(Path("report.csv").read_bytes(), maintype=maintype, subtype=subtype, filename="report.csv")\nprint(msg["Subject"], "|", [p.get_filename() for p in msg.iter_attachments()])\nprint(len(msg.as_bytes()), "bytes")', run: 1 },
        { h: B('الإرسال بـ SMTP', 'Sending over SMTP'),
          p: B('`smtplib.SMTP_SSL(host, 465)` أو `SMTP(host, 587)` مع `starttls()`، و`login(user, password)` و`send_message(msg)`. Gmail ومعظم الخدمات مش بتقبل باسورد حسابك العادي؛ اعمل «App password» (بعد تفعيل التحقق بخطوتين) وحطه في `.env` — عمره ما يتكتب في الكود. وفيه حد يومي للإرسال، فللإيميلات الكتير استخدم خدمة إرسال (أو n8n).', '`smtplib.SMTP_SSL(host, 465)`, or `SMTP(host, 587)` with `starttls()`, then `login(user, password)` and `send_message(msg)`. Gmail and most providers reject your normal account password; create an «App password» (after turning on two-step verification) and keep it in `.env` — never in the code. There is a daily sending limit, so for bulk email use a sending service (or n8n).'),
          ex: 'import os, smtplib, ssl\nfrom email.message import EmailMessage\nfrom dotenv import load_dotenv\n\nload_dotenv()\nmsg = EmailMessage()\nmsg["Subject"] = "Test from Python"\nmsg["From"] = os.environ["SMTP_USER"]\nmsg["To"] = os.environ["SMTP_USER"]          # send to yourself first\nmsg.set_content("It works.")\nwith smtplib.SMTP_SSL(os.environ.get("SMTP_HOST", "smtp.gmail.com"), 465, context=ssl.create_default_context()) as s:\n    s.login(os.environ["SMTP_USER"], os.environ["SMTP_APP_PASSWORD"])\n    s.send_message(msg)\nprint("sent")' },
        { h: B('جرّب من غير ما تبعت', 'Test without sending'),
          p: B('قبل ما تبعت لـ 200 عميل: dry run بيكتب كل إيميل في ملف `.eml` (تفتحه في Outlook وتشوف شكله)، وابعت أول إيميل لنفسك، واستنى ثانية أو اتنين بين الرسايل، وسجّل كل إرسال (لمين ونجح ولا لأ) عشان لو السكربت وقف تكمّل من غير تكرار.', 'Before mailing 200 customers: a dry run that writes each email to an `.eml` file (open it in Outlook to see it), send the first one to yourself, wait a second or two between messages, and log every send (to whom, and whether it worked) so you can resume without duplicates if the script stops.'),
          ex: 'import json, time\nfrom email.message import EmailMessage\nfrom pathlib import Path\n\ncustomers = [{"name": "Sara", "email": "sara@example.com", "due": 1200}, {"name": "Omar", "email": "omar@example.com", "due": 450.5}]\nsent_log = Path("sent.json")\nsent = set(json.loads(sent_log.read_text(encoding="utf-8"))) if sent_log.exists() else set()\nout = Path("outbox"); out.mkdir(exist_ok=True)\nDRY_RUN = True\nfor c in customers:\n    if c["email"] in sent:\n        continue\n    msg = EmailMessage()\n    msg["Subject"] = f"Payment reminder: {c[\'due\']:,.2f} EGP"\n    msg["To"] = c["email"]\n    msg.set_content(f"Hello {c[\'name\']},\\nA friendly reminder that {c[\'due\']:,.2f} EGP is due.")\n    if DRY_RUN:\n        (out / f"{c[\'email\']}.eml").write_bytes(msg.as_bytes())\n    else:\n        pass  # smtp.send_message(msg); time.sleep(1.5)\n    sent.add(c["email"])\nsent_log.write_text(json.dumps(sorted(sent)), encoding="utf-8")\nprint(sorted(p.name for p in out.iterdir()))', run: 1 }
      ],
      practice: [
        B('ابني إيميل بنص وHTML ومرفقين واطبع أسماء المرفقات.', 'Build an email with text, HTML and two attachments and print the attachment names.'),
        B('فعّل التحقق بخطوتين واعمل App password لإيميل تجربة، وحطه في .env.', 'Turn on two-step verification, create an App password for a test mailbox, and put it in .env.'),
        B('ابعت إيميل لنفسك من Python واتأكد إنه وصل والعربي سليم.', 'Send an email to yourself from Python and check it arrived with the Arabic intact.'),
        B('شغّل الـ dry run وافتح ملف .eml في برنامج الإيميل.', 'Run the dry run and open an .eml file in your mail program.')
      ],
      code: [
        { u: B('دالة إرسال قابلة لإعادة الاستخدام', 'A reusable send function'), p: 'import os, smtplib, ssl, mimetypes\nfrom email.message import EmailMessage\nfrom pathlib import Path\n\ndef send_email(to: str, subject: str, text: str, html: str | None = None, attachments: list[Path] = ()) -> None:\n    msg = EmailMessage()\n    msg["From"], msg["To"], msg["Subject"] = os.environ["SMTP_USER"], to, subject\n    msg.set_content(text)\n    if html:\n        msg.add_alternative(html, subtype="html")\n    for path in attachments:\n        ctype = mimetypes.guess_type(path.name)[0] or "application/octet-stream"\n        main, sub = ctype.split("/")\n        msg.add_attachment(path.read_bytes(), maintype=main, subtype=sub, filename=path.name)\n    with smtplib.SMTP_SSL(os.environ["SMTP_HOST"], 465, context=ssl.create_default_context()) as s:\n        s.login(os.environ["SMTP_USER"], os.environ["SMTP_APP_PASSWORD"])\n        s.send_message(msg)' }
      ],
      words: [
        { t: 'SMTP', m: B('البروتوكول اللي بيبعت الإيميلات', 'the protocol that sends email'), ex: 'smtp.gmail.com:465' },
        { t: 'smtplib', m: B('موديول Python للإرسال عن طريق SMTP', 'Python’s module for sending over SMTP'), ex: 'smtplib.SMTP_SSL(host, 465)' },
        { t: 'EmailMessage', m: B('كلاس بيبني رسالة إيميل بعناوينها ومحتواها', 'a class that builds an email with its headers and content'), ex: 'msg = EmailMessage()' },
        { t: 'app password', m: B('كلمة سر خاصة لبرنامج بدل باسورد الحساب', 'a special password for a program instead of the account password'), ex: 'SMTP_APP_PASSWORD in .env' },
        { t: 'attachment', m: B('ملف مرفق مع الإيميل', 'a file sent with an email'), ex: 'msg.add_attachment(...)' },
        { t: 'MIME type', m: B('نوع المحتوى زي text/csv أو application/pdf', 'the content type such as text/csv or application/pdf'), ex: 'mimetypes.guess_type("a.pdf")' },
        { t: 'rate limit', m: B('حد لعدد الطلبات أو الرسايل في وقت معيّن', 'a cap on requests or messages in a period'), ex: 'about 500 emails a day on a free mailbox' }
      ],
      read: [{ lib: 'email: Examples', what: B('اقرا أول 3 أمثلة.', 'Read the first 3 examples.') }, { lib: 'Automate the Boring Stuff with Python', what: B('فصل Sending Email and Text Messages.', 'The Sending Email and Text Messages chapter.') }],
      challenge: B('اعمل «تذكير بالمستحقات»: يقرا CSV عملاء ومبالغهم، ويبني لكل واحد إيميل HTML بجدول صغير لفواتيره، ويشتغل dry run افتراضيًا (ملفات .eml)، و`--send` يبعت فعلًا بفاصل ثانيتين ويسجّل في sent.json عشان لو اتقطع يكمّل.', 'Build a «payment reminder»: read a CSV of customers and amounts, build an HTML email with a small table of each one’s invoices, run as a dry run by default (.eml files), and with `--send` really send with a 2-second gap, logging to sent.json so it can resume if interrupted.'),
      quiz: [
        { q: B('باسورد SMTP يتحط فين؟', 'Where does the SMTP password go?'), o: [B('.env كـ app password', 'in .env, as an app password'), B('في الكود', 'in the code'), B('في الـ Subject', 'in the subject')], a: 0, why: B('عمره ما يتكتب في الكود.', 'Never in the code.') },
        { q: B('`add_alternative(html, subtype="html")` فايدتها:', 'What `add_alternative(html, subtype="html")` is for:'), o: [B('نسخة HTML جنب النص العادي', 'an HTML version next to the plain text'), B('مرفق', 'an attachment'), B('تشفير', 'encryption')], a: 0, why: B('البرنامج بيختار اللي يقدر يعرضه.', 'The client shows what it can.') },
        { q: B('أول حاجة قبل إرسال 300 إيميل:', 'The first thing before sending 300 emails:'), o: [B('dry run وإيميل لنفسك', 'a dry run and an email to yourself'), B('تبعت كله مرة واحدة', 'send them all at once'), B('تشيل اللوج', 'remove the log')], a: 0, why: B('غلطة واحدة هتتكرر 300 مرة.', 'One mistake would repeat 300 times.') }
      ] },

    { title: B('فواتير PDF وQR', 'PDF invoices and QR codes'),
      goal: B('تطلّع ملف PDF (فاتورة أو تقرير) من Python بـ fpdf2، وتحط فيه جدول ولوجو، وتعرف إزاي تكتب عربي صح، وتضيف QR code.', 'Produce a PDF (an invoice or a report) from Python with fpdf2, add a table and a logo, know how to write Arabic correctly, and add a QR code.'),
      learn: [
        { h: B('PDF بـ fpdf2', 'A PDF with fpdf2'),
          p: B('`pip install fpdf2`. `pdf = FPDF()` و`pdf.add_page()` و`pdf.set_font("Helvetica", size=12)` و`pdf.cell(...)` لسطر و`pdf.multi_cell(...)` لفقرة، و`pdf.output("invoice.pdf")`. الجداول: `with pdf.table() as table:` وكل صف `row = table.row()` و`row.cell(...)`.', '`pip install fpdf2`. `pdf = FPDF()`, `pdf.add_page()`, `pdf.set_font("Helvetica", size=12)`, `pdf.cell(...)` for a line and `pdf.multi_cell(...)` for a paragraph, and `pdf.output("invoice.pdf")`. Tables: `with pdf.table() as table:`, then `row = table.row()` and `row.cell(...)` per row.'),
          ex: '# pip install fpdf2\nfrom fpdf import FPDF\n\nlines = [("Notebook", 3, 45.0), ("Backpack", 1, 650.0), ("Pen Pro", 4, 30.0)]\npdf = FPDF()\npdf.add_page()\npdf.set_font("Helvetica", "B", 18)\npdf.cell(0, 12, "Invoice INV-2026-0091", new_x="LMARGIN", new_y="NEXT")\npdf.set_font("Helvetica", size=11)\npdf.cell(0, 8, "Customer: Sara Ahmed  |  Date: 2026-10-01", new_x="LMARGIN", new_y="NEXT")\npdf.ln(4)\nwith pdf.table(col_widths=(60, 20, 30, 30), text_align=("LEFT", "RIGHT", "RIGHT", "RIGHT")) as table:\n    table.row(["Item", "Qty", "Price", "Total"])\n    for name, qty, price in lines:\n        table.row([name, str(qty), f"{price:,.2f}", f"{qty * price:,.2f}"])\ntotal = sum(q * p for _, q, p in lines)\npdf.ln(4)\npdf.set_font("Helvetica", "B", 12)\npdf.cell(0, 8, f"Total due: {total * 1.14:,.2f} EGP (incl. 14% VAT)", align="R")\npdf.output("invoice.pdf")' },
        { h: B('العربي في PDF', 'Arabic in a PDF'),
          p: B('الخطوط الافتراضية مفيهاش عربي. حمّل خط عربي مجاني (زي Amiri أو Cairo أو Noto Naskh Arabic من Google Fonts) و`pdf.add_font("Amiri", fname="Amiri-Regular.ttf")`، وفعّل تشكيل الحروف بـ `pdf.set_text_shaping(True)` (محتاج حزمة `uharfbuzz`) عشان الحروف تتوصل والاتجاه يبقى من اليمين. جرّب دايمًا بأسماء عربي حقيقية قبل ما تعتمد.', 'The default fonts have no Arabic. Download a free Arabic font (such as Amiri, Cairo or Noto Naskh Arabic from Google Fonts), `pdf.add_font("Amiri", fname="Amiri-Regular.ttf")`, and turn on text shaping with `pdf.set_text_shaping(True)` (it needs the `uharfbuzz` package) so letters join and run right to left. Always test with real Arabic names before relying on it.'),
          ex: '# pip install fpdf2 uharfbuzz   + download Amiri-Regular.ttf from Google Fonts\nfrom fpdf import FPDF\n\npdf = FPDF()\npdf.add_page()\npdf.add_font("Amiri", fname="Amiri-Regular.ttf")\npdf.set_font("Amiri", size=16)\npdf.set_text_shaping(True)\npdf.cell(0, 12, "فاتورة رقم ٩١ — العميلة: سارة أحمد", align="R", new_x="LMARGIN", new_y="NEXT")\npdf.cell(0, 12, "الإجمالي: ١٬٤٨٠ جنيه", align="R")\npdf.output("invoice_ar.pdf")' },
        { h: B('QR code ولوجو', 'A QR code and a logo'),
          p: B('`pip install qrcode` و`qrcode.make(text)` بترجّع صورة تحفظها وتحطها في الـ PDF بـ `pdf.image(path, x, y, w)` — مثلًا QR فيه لينك الدفع أو رقم الفاتورة. واللوجو بنفس الطريقة. خلي الـ QR بمقاس 25-35 مم عشان يتقري من الموبايل.', '`pip install qrcode`, and `qrcode.make(text)` returns an image you save and place in the PDF with `pdf.image(path, x, y, w)` — for example a QR with the payment link or the invoice number. A logo works the same way. Keep the QR 25-35 mm wide so a phone can read it.'),
          ex: '# pip install qrcode fpdf2\nimport qrcode\nfrom fpdf import FPDF\n\nqrcode.make("https://pay.example.com/i/INV-2026-0091").save("pay_qr.png")\npdf = FPDF()\npdf.add_page()\npdf.set_font("Helvetica", "B", 16)\npdf.cell(0, 10, "Invoice INV-2026-0091")\npdf.image("pay_qr.png", x=170, y=10, w=30)\npdf.set_xy(10, 45)\npdf.set_font("Helvetica", size=10)\npdf.cell(0, 6, "Scan to pay online.")\npdf.output("invoice_qr.pdf")' }
      ],
      practice: [
        B('اعمل فاتورة PDF بجدول منتجات وإجمالي وضريبة.', 'Make a PDF invoice with a product table, a total and VAT.'),
        B('نزّل خط Amiri أو Cairo وجرّب سطر عربي، مرة من غير text shaping ومرة بيه.', 'Download the Amiri or Cairo font and try an Arabic line, once without text shaping and once with it.'),
        B('ضيف QR فيه رقم الفاتورة ولوجو صغير فوق على الشمال.', 'Add a QR with the invoice number and a small logo at the top left.'),
        B('حط الدالة كلها في `make_invoice(order: dict, path: Path)` واطلّع 3 فواتير.', 'Wrap it all in `make_invoice(order: dict, path: Path)` and produce 3 invoices.')
      ],
      code: [
        { u: B('هيكل دالة الفاتورة', 'The invoice function skeleton'), p: 'from pathlib import Path\nfrom fpdf import FPDF\n\nVAT = 0.14\n\ndef make_invoice(order: dict, out: Path) -> Path:\n    pdf = FPDF()\n    pdf.add_page()\n    pdf.set_font("Helvetica", "B", 16)\n    pdf.cell(0, 10, f"Invoice {order[\'id\']}", new_x="LMARGIN", new_y="NEXT")\n    pdf.set_font("Helvetica", size=11)\n    pdf.cell(0, 7, f"{order[\'customer\']}  |  {order[\'date\']}", new_x="LMARGIN", new_y="NEXT")\n    with pdf.table(col_widths=(70, 20, 30, 30)) as table:\n        table.row(["Item", "Qty", "Price", "Total"])\n        for it in order["items"]:\n            table.row([it["name"], str(it["qty"]), f"{it[\'price\']:,.2f}", f"{it[\'qty\'] * it[\'price\']:,.2f}"])\n    subtotal = sum(it["qty"] * it["price"] for it in order["items"])\n    pdf.cell(0, 9, f"Total: {subtotal * (1 + VAT):,.2f} EGP", align="R")\n    out.parent.mkdir(parents=True, exist_ok=True)\n    pdf.output(str(out))\n    return out' }
      ],
      words: [
        { t: 'fpdf2', m: B('مكتبة بسيطة لعمل ملفات PDF من Python', 'a simple library for making PDFs from Python'), ex: 'from fpdf import FPDF' },
        { t: 'font file', m: B('ملف الخط (ttf) اللي بيحدد شكل الحروف', 'the font file (ttf) defining the letter shapes'), ex: 'Amiri-Regular.ttf' },
        { t: 'text shaping', m: B('توصيل الحروف العربي واتجاه الكتابة صح', 'joining Arabic letters and getting the direction right'), ex: 'pdf.set_text_shaping(True)' },
        { t: 'right-to-left', m: B('اتجاه الكتابة من اليمين للشمال (RTL)', 'writing direction from right to left (RTL)'), ex: 'Arabic and Hebrew' },
        { t: 'QR code', m: B('مربع بيشفّر نص أو لينك وبيتقري بالكاميرا', 'a square that encodes text or a link, read by a camera'), ex: 'qrcode.make(url)' },
        { t: 'invoice', m: B('فاتورة: مستند بالمطلوب دفعه', 'a document stating what is owed'), ex: 'INV-2026-0091' }
      ],
      read: [{ lib: 'Real Python Tutorials', what: B('دوّر على «create pdf python» واقرا مقال fpdf2 أو ReportLab.', 'Search for «create pdf python» and read the fpdf2 or ReportLab article.') }, { lib: 'fpdf2 documentation', what: B('اقرا Tutorial وTables وجزء Text shaping.', 'Read the Tutorial, Tables and the Text shaping part.') }, 'lib:Google Fonts: Amiri'],
      challenge: B('اعمل `invoices.py` بياخد ملف `orders.json` (من مشروع أسبوع 5) ويطلّع فاتورة PDF لكل طلب مدفوع في `invoices/YYYY-MM/`، فيها QR بلينك تجريبي، ولو فيه اسم عميل عربي يتكتب صح بخط عربي.', 'Write `invoices.py` that takes `orders.json` (from the week 5 project) and produces a PDF invoice for each paid order in `invoices/YYYY-MM/`, with a QR holding a test link, and Arabic customer names written correctly with an Arabic font.'),
      quiz: [
        { q: B('العربي بيطلع مربعات في الـ PDF. السبب:', 'Arabic shows as boxes in the PDF. Why?'), o: [B('الخط مفيهوش حروف عربي', 'the font has no Arabic letters'), B('الملف كبير', 'the file is large'), B('Python مبتدعمش العربي', 'Python lacks Arabic support')], a: 0, why: B('حمّل خط عربي.', 'Load an Arabic font.') },
        { q: B('الحروف العربي منفصلة ومقلوبة الاتجاه:', 'Arabic letters are separate and reversed:'), o: [B('فعّل text shaping', 'turn on text shaping'), B('غيّر حجم الخط', 'change the font size'), B('استخدم JPG', 'use JPG')], a: 0, why: B('التشكيل بيوصل الحروف ويظبط الاتجاه.', 'Shaping joins the letters and fixes the direction.') },
        { q: B('QR code للدفع بيتحط في الفاتورة كـ:', 'A payment QR goes into the invoice as:'), o: [B('صورة', 'an image'), B('خط', 'a font'), B('جدول', 'a table')], a: 0, why: B('pdf.image(...).', 'pdf.image(...).') }
      ] },

    { title: B('مشروع الشهر التالت واختبار الأسبوع', 'The month 3 project and weekly test'),
      goal: B('تبني نظام فواتير كامل من البيانات للـ PDF للإيميل، وتعدّي اختبار الأسبوع عشان امتحان الشهر التالت يفتح.', 'Build a complete invoicing system from data to PDF to email, and pass the weekly test to open the month 3 exam.'),
      review: [
        B('pypdf: قراءة النص والدمج والتقسيم، والـ PDF الممسوح محتاج OCR.', 'pypdf: reading text, merging and splitting; scanned PDFs need OCR.'),
        B('python-docx: عناوين وفقرات وruns وجداول وقوالب.', 'python-docx: headings, paragraphs, runs, tables and templates.'),
        B('Pillow: thumbnail وexif_transpose وconvert وfit وعلامة مائية.', 'Pillow: thumbnail, exif_transpose, convert, fit and a watermark.'),
        B('EmailMessage وSMTP وapp password وdry run وسجل الإرسال.', 'EmailMessage, SMTP, app passwords, dry runs and a send log.'),
        B('fpdf2 والجداول والخط العربي وtext shaping وQR.', 'fpdf2, tables, an Arabic font, text shaping and QR codes.')
      ],
      project: B('**مشروع الشهر: مولّد ومُرسِل الفواتير** (`invoicer/`): (1) يقرا الطلبات من Excel (شيت `orders` وشيت `customers`) وينضّفها بدوالك. (2) يطلّع فاتورة PDF لكل طلب مدفوع بلوجو وQR وخط عربي، في `out/invoices/YYYY-MM/`. (3) يدمج كل فواتير الشهر في PDF واحد للمحاسب. (4) يبعت لكل عميل إيميل HTML ومعاه فاتورته (dry run افتراضيًا بملفات .eml، و`--send` يبعت فعلًا بفاصل وsent.json). (5) يكتب تقرير Excel منسّق بكل اللي اتعمل. الإعدادات في `config.toml`، والأسرار في `.env`، ولوج كامل، و15 test على الدوال اللي مبتلمسش ملفات أو شبكة، وREADME بخطوات التشغيل.', '**Month project: the invoice generator and sender** (`invoicer/`): (1) read the orders from Excel (an `orders` sheet and a `customers` sheet) and clean them with your functions. (2) Produce a PDF invoice for each paid order with a logo, a QR and an Arabic font, in `out/invoices/YYYY-MM/`. (3) Merge the month’s invoices into one PDF for the accountant. (4) Email each customer an HTML message with their invoice attached (a dry run by default with .eml files; `--send` really sends, with a gap and sent.json). (5) Write a formatted Excel report of everything done. Settings in `config.toml`, secrets in `.env`, a full log, 15 tests on the functions that touch no files or network, and a README with the run steps.'),
      test: [
        { q: B('مكتبة قراءة ودمج PDF:', 'The library to read and merge PDFs:'), o: ['pypdf', 'python-docx', 'Pillow'], a: 0, why: B('pypdf.', 'pypdf.') },
        { q: B('`PdfWriter().append("a.pdf")` بيضيف:', '`PdfWriter().append("a.pdf")` adds:'), o: [B('كل صفحات a.pdf', 'every page of a.pdf'), B('أول صفحة بس', 'only the first page'), B('النص بس', 'only the text')], a: 0, why: B('إلا لو حددت pages.', 'Unless you pass pages.') },
        { q: B('في python-docx التنسيق المختلف لكلمة جوه فقرة بيبقى في:', 'In python-docx, different formatting for one word in a paragraph lives in a:'), o: ['run', 'heading', 'table'], a: 0, why: B('الفقرة مجموعة runs.', 'A paragraph is a list of runs.') },
        { q: B('تصغير صورة مع الحفاظ على النسبة:', 'Shrinking an image while keeping proportions:'), o: ['img.thumbnail(size)', 'img.resize(size)', 'img.crop(box)'], a: 0, why: B('resize بيمط لو المقاس مش متناسب.', 'resize stretches if the size does not match.') },
        { q: B('صورة PNG شفافة هتتحفظ JPG، لازم:', 'A transparent PNG to be saved as JPG needs:'), o: ['convert("RGB")', 'exif_transpose', 'quality=100'], a: 0, why: B('JPG مفيهوش شفافية.', 'JPG has no transparency.') },
        { q: B('`msg.add_attachment(...)` بتحتاج:', '`msg.add_attachment(...)` needs:'), o: [B('البايتات والنوع واسم الملف', 'the bytes, the type and the file name'), B('المسار بس', 'only the path'), B('باسورد', 'a password')], a: 0, why: B('maintype وsubtype وfilename.', 'maintype, subtype and filename.') },
        { q: B('بورت SMTP_SSL المعتاد:', 'The usual SMTP_SSL port:'), o: ['465', '80', '22'], a: 0, why: B('587 لـ starttls.', '587 is for starttls.') },
        { q: B('ليه sent.json في سكربت الإرسال؟', 'Why sent.json in the sending script?'), o: [B('عشان لو وقف يكمّل من غير تكرار', 'to resume without duplicates if it stops'), B('عشان Gmail بيطلبه', 'Gmail requires it'), B('عشان يبعت أسرع', 'to send faster')], a: 0, why: B('سجل باللي اتبعت.', 'A record of what was sent.') },
        { q: B('الخط الافتراضي في fpdf2 وفيه عربي:', 'The default fpdf2 font with Arabic text:'), o: [B('مش هيعرضه؛ لازم خط عربي', 'cannot show it; you need an Arabic font'), B('بيعرضه عادي', 'shows it fine'), B('بيترجمه', 'translates it')], a: 0, why: B('Helvetica مفيهاش عربي.', 'Helvetica has no Arabic.') },
        { q: B('PDF ممسوح ضوئيًا محتاج عشان تقرا نصه:', 'To read the text of a scanned PDF you need:'), o: ['OCR', 'pypdf.extract_text', 'python-docx'], a: 0, why: B('مفيش نص، صور بس.', 'There is no text, only images.') },
        { q: B('`ImageOps.fit(img, (600, 600))`:', '`ImageOps.fit(img, (600, 600))`:'), o: [B('يقص من النص لمربع 600 بالظبط', 'centre-crops to exactly 600×600'), B('يصغّر من غير قص', 'shrinks without cropping'), B('يكبّر', 'enlarges')], a: 0, why: B('fit = قص للمقاس.', 'fit = crop to size.') },
        { q: B('أول إيميل في حملة جديدة يروح لـ:', 'The first email of a new campaign should go to:'), o: [B('نفسك', 'yourself'), B('أكبر عميل', 'your biggest customer'), B('كل العملاء', 'every customer')], a: 0, why: B('تشوفه قبل أي حد.', 'You see it before anyone else.') }
      ] }
  ]
};
