// Python week 16 — Web scraping and the month project.
const B = (ar, en) => ({ ar, en });
module.exports = {
  level: B('متوسط', 'Intermediate'),
  title: B('الـ Web scraping ومشروع الشهر', 'Web scraping and the month project'),
  goal: B('تسحب بيانات من مواقع بشكل مسؤول وقانوني (robots.txt والشروط والسرعة)، بـ requests وBeautiful Soup للصفحات العادية وPlaywright للصفحات اللي بتتبني بـ JavaScript، وتلاقي الـ API المخفي، وتبني مراقب أسعار بيبلّغك بالتغيير — مشروع الشهر الرابع.',
          'Collect data from websites responsibly and legally (robots.txt, terms and speed), with requests and Beautiful Soup for normal pages and Playwright for pages built by JavaScript, find the hidden API, and build a price monitor that tells you about changes — the month 4 project.'),
  days: [
    { title: B('قبل ما تسحب: الأخلاق والقانون والاستكشاف', 'Before you scrape: ethics, law and exploring'),
      goal: B('تعرف امتى الـ scraping مقبول، وتقرا robots.txt بالكود، وتستكشف الصفحة في DevTools، وتدوّر على API رسمي الأول.', 'Know when scraping is acceptable, read robots.txt in code, explore the page in DevTools, and look for an official API first.'),
      learn: [
        { h: B('القواعد الذهبية', 'The golden rules'),
          p: B('1) دوّر على **API رسمي** أو ملف تصدير الأول — أسهل وأثبت ومسموح. 2) اقرا **شروط الاستخدام** وrobots.txt والتزم بيهم. 3) متسحبش بيانات شخصية ولا محتوى عليه حقوق تعيد نشره. 4) **بالراحة**: طلب كل ثانية أو اتنين، وعرّف نفسك بـ User-Agent فيه طريقة تواصل. 5) خزّن اللي جبته ومتطلبش نفس الصفحة كل شوية. اتمرّن على مواقع معمولة للتمرين زي books.toscrape.com.', '1) Look for an **official API** or an export file first — easier, more stable and allowed. 2) Read the **terms of use** and robots.txt and follow them. 3) Do not collect personal data or republish copyrighted content. 4) **Go slowly**: one request every second or two, and identify yourself with a User-Agent that includes a contact. 5) Store what you fetched instead of requesting the same page again and again. Practise on sites made for it, such as books.toscrape.com.'),
          ex: 'HEADERS = {"User-Agent": "price-watch/1.0 (contact: you@example.com)"}\nDELAY_SECONDS = 1.5          # between requests\nCACHE_HOURS = 12             # do not re-download a page within this time\nALLOWED = ["books.toscrape.com", "quotes.toscrape.com"]   # practice sites', show: 1 },
        { h: B('robots.txt بالكود', 'robots.txt in code'),
          p: B('`urllib.robotparser` بيقرا robots.txt ويقولك المسار ده مسموح لبرنامجك ولا لأ، وفيه crawl-delay ولا لأ. شغّل الفحص ده أول السكربت. المثال هنا بيقرا نص robots جاهز عشان يشتغل في الصفحة.', '`urllib.robotparser` reads robots.txt and tells you whether a path is allowed for your program and whether there is a crawl-delay. Run this check at the start of your script. The example parses a ready robots text so it runs on the page.'),
          ex: 'from urllib.robotparser import RobotFileParser\nrobots = """User-agent: *\nDisallow: /admin/\nDisallow: /cart\nCrawl-delay: 2\n\nUser-agent: BadBot\nDisallow: /\n"""\nrp = RobotFileParser()\nrp.parse(robots.splitlines())\nfor path in ["/catalogue/page-2.html", "/admin/users", "/cart"]:\n    print(path, rp.can_fetch("price-watch", "https://shop.example.com" + path))\nprint("crawl delay:", rp.crawl_delay("price-watch"))\nprint("BadBot allowed /:", rp.can_fetch("BadBot", "https://shop.example.com/"))', run: 1 },
        { h: B('استكشف الصفحة الأول', 'Explore the page first'),
          p: B('افتح الصفحة، كليك يمين على المنتج → Inspect: شوف الـ tag والـ class اللي فيه السعر والاسم. اختار selector ثابت (class بيوصف المعنى زي `.price_color`، مش class عشوائي زي `css-1x2y3z`). وافتح تبويب Network → Fetch/XHR وحدّث الصفحة: لو لقيت طلب بيرجّع JSON فيه البيانات، ده API مخفي — استخدمه بدل الـ HTML.', 'Open the page, right-click the product → Inspect: see the tag and class holding the price and the name. Pick a stable selector (a meaningful class like `.price_color`, not a random one like `css-1x2y3z`). Then open Network → Fetch/XHR and reload: if a request returns JSON with the data, that is a hidden API — use it instead of the HTML.'),
          ex: '<!-- what Inspect shows on books.toscrape.com -->\n<article class="product_pod">\n  <h3><a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">A Light in the ...</a></h3>\n  <div class="product_price">\n    <p class="price_color">£51.77</p>\n    <p class="instock availability">In stock</p>\n  </div>\n</article>', lang: 'html' }
      ],
      practice: [
        B('افتح robots.txt لـ 3 مواقع مشهورة واقرا مين مسموحله إيه.', 'Open robots.txt on 3 well-known sites and read who may access what.'),
        B('اقرا robots.txt الحقيقي لـ books.toscrape.com بـ `rp.set_url(...)` و`rp.read()`.', 'Read the real robots.txt of books.toscrape.com with `rp.set_url(...)` and `rp.read()`.'),
        B('افتح books.toscrape.com وInspect اسم كتاب وسعره وتقييمه، واكتب الـ selector لكل واحد.', 'Open books.toscrape.com and inspect a book’s title, price and rating, writing the selector for each.'),
        B('افتح Network → Fetch/XHR على موقع بيحمّل بيانات وهو شغال (زي موقع طقس) ولاقي الطلب اللي بيرجّع JSON.', 'Open Network → Fetch/XHR on a site that loads data as it runs (like a weather site) and find the request returning JSON.')
      ],
      code: [
        { u: B('فحص robots قبل أي طلب', 'Checking robots before any request'), p: 'from urllib.parse import urlparse\nfrom urllib.robotparser import RobotFileParser\n\n_robots = {}\n\ndef allowed(url: str, agent: str = "price-watch") -> bool:\n    base = "{0.scheme}://{0.netloc}".format(urlparse(url))\n    if base not in _robots:\n        rp = RobotFileParser(base + "/robots.txt")\n        try:\n            rp.read()\n        except OSError:\n            return False          # cannot read it: be careful and skip\n        _robots[base] = rp\n    return _robots[base].can_fetch(agent, url)' }
      ],
      words: [
        { t: 'web scraping', m: B('سحب بيانات من صفحات الويب بالكود', 'collecting data from web pages with code'), ex: 'prices from a catalogue page' },
        { t: 'robots.txt', m: B('ملف في الموقع بيقول البرامج مسموحلها تدخل فين', 'a site file saying where programs may go'), ex: 'https://site.com/robots.txt' },
        { t: 'terms of service', m: B('شروط استخدام الموقع؛ ممكن تمنع السحب', 'a site’s terms of use; they may forbid scraping'), ex: 'read them before scraping' },
        { t: 'crawl delay', m: B('المدة اللي الموقع طالب تستناها بين الطلبات', 'the wait a site asks for between requests'), ex: 'Crawl-delay: 2' },
        { t: 'hidden API', m: B('طلب JSON بتستخدمه الصفحة نفسها، تقدر تستخدمه بدل الـ HTML', 'a JSON request the page itself uses, which you can use instead of HTML'), ex: 'Network → Fetch/XHR' },
        { t: 'Inspect element', m: B('أداة المتصفح اللي بتوريك الـ HTML ورا أي جزء', 'the browser tool showing the HTML behind any part'), ex: 'right-click → Inspect' }
      ],
      read: ['lib:Google: robots.txt introduction', { lib: 'Books to Scrape', what: B('لف في الموقع واعرف شكل صفحة الكتاب وصفحات الأقسام.', 'Browse the site and learn the shape of a book page and the category pages.') }],
      challenge: B('اكتب «تقرير استكشاف» لموقع تتمرّن عليه: المسموح في robots، والـ selectors لـ 5 حقول، وهل فيه API مخفي، وشكل الصفحات (رقم صفحة ولا لينك next)، وتقدير لعدد الطلبات والوقت لو مشيت بطلب كل ثانية ونص.', 'Write an «exploration report» for a practice site: what robots allows, the selectors for 5 fields, whether there is a hidden API, how pages work (page numbers or a next link), and an estimate of requests and time at one request every 1.5 seconds.'),
      quiz: [
        { q: B('أول حاجة قبل ما تعمل scraping لموقع:', 'The first thing before scraping a site:'), o: [B('تدوّر على API رسمي وتقرا الشروط وrobots', 'look for an official API and read the terms and robots'), B('تسحب بأقصى سرعة', 'scrape as fast as possible'), B('تغيّر الـ User-Agent لمتصفح عادي', 'pretend to be a normal browser')], a: 0, why: B('أسهل ومسموح.', 'Easier and allowed.') },
        { q: B('`Crawl-delay: 2` معناها:', '`Crawl-delay: 2` means:'), o: [B('استنى ثانيتين بين الطلبات', 'wait two seconds between requests'), B('ممنوع', 'forbidden'), B('مرتين في اليوم', 'twice a day')], a: 0, why: B('سرعة مسموحة.', 'An allowed pace.') },
        { q: B('selector أثبت:', 'A more stable selector:'), o: ['.price_color', '.css-1x2y3z', 'div > div > div:nth-child(7)'], a: 0, why: B('اسم بيوصف المعنى أقل تغيير.', 'A meaningful name changes less.') }
      ] },

    { title: B('Beautiful Soup', 'Beautiful Soup'),
      goal: B('تحوّل HTML لشجرة تدوّر فيها بـ find وselect، وتطلّع النصوص والـ attributes، وتحوّل اللينكات النسبية لكاملة.', 'Turn HTML into a tree you search with find and select, extract text and attributes, and turn relative links into full ones.'),
      learn: [
        { h: B('من HTML لشجرة', 'From HTML to a tree'),
          p: B('`pip install beautifulsoup4`. `soup = BeautifulSoup(html, "html.parser")`، وبعدين `soup.select(".product_pod")` (CSS selectors اللي اتعلمتها أسبوع 14) أو `soup.find_all("article", class_="product_pod")`. `el.get_text(strip=True)` النص، و`el["href"]` أو `el.get("href")` attribute.', '`pip install beautifulsoup4`. `soup = BeautifulSoup(html, "html.parser")`, then `soup.select(".product_pod")` (the CSS selectors from week 14) or `soup.find_all("article", class_="product_pod")`. `el.get_text(strip=True)` gives the text, and `el["href"]` or `el.get("href")` an attribute.'),
          ex: '# pip install beautifulsoup4\nfrom bs4 import BeautifulSoup\n\nhtml = """<article class="product_pod"><h3><a href="catalogue/book-1/index.html" title="Sharp Objects">Sharp Obj...</a></h3>\n<p class="star-rating Four"></p><p class="price_color">£47.82</p><p class="instock availability"> In stock </p></article>\n<article class="product_pod"><h3><a href="catalogue/book-2/index.html" title="Soumission">Soumission</a></h3>\n<p class="star-rating One"></p><p class="price_color">£50.10</p><p class="availability">Out of stock</p></article>"""\nsoup = BeautifulSoup(html, "html.parser")\nfor book in soup.select("article.product_pod"):\n    link = book.select_one("h3 a")\n    print(link["title"], "|", book.select_one(".price_color").get_text(), "|", book.select_one(".availability").get_text(strip=True))', run: 1 },
        { h: B('find وselect والتنقل', 'find, select and moving around'),
          p: B('`select_one` أول واحد أو None (اتأكد قبل ما تستخدمه)، و`select` كلهم. والتنقل: `.parent` و`.find_next_sibling()`. والـ class اللي فيه أكتر من كلمة (`star-rating Four`): `el["class"]` بترجّع قايمة. حوّل التقييم بالكلام لرقم بـ dict.', '`select_one` returns the first match or None (check before using it) and `select` all of them. To move around: `.parent` and `.find_next_sibling()`. A class with several words (`star-rating Four`): `el["class"]` returns a list. Turn a worded rating into a number with a dict.'),
          ex: 'from bs4 import BeautifulSoup\nRATING = {"One": 1, "Two": 2, "Three": 3, "Four": 4, "Five": 5}\nsoup = BeautifulSoup(\'<p class="star-rating Four"></p><table><tr><th>UPC</th><td>a897fe39b1053632</td></tr><tr><th>Availability</th><td>In stock (22 available)</td></tr></table>\', "html.parser")\nclasses = soup.select_one(".star-rating")["class"]\nprint(classes, RATING[classes[1]])\ninfo = {th.get_text(): th.find_next_sibling("td").get_text() for th in soup.select("table th")}\nprint(info)\nmissing = soup.select_one(".discount")\nprint(missing.get_text() if missing else "no discount")', run: 1 },
        { h: B('اللينكات النسبية والنضافة', 'Relative links and cleaning'),
          p: B('اللينكات جوه الصفحة غالبًا نسبية (`catalogue/book-1/index.html`)؛ `urljoin(page_url, href)` بيحوّلها كاملة. والأسعار والأرقام بتيجي نص فيه رموز (`£47.82` و`(22 available)`) — نضّفها بـ Regex (أسبوع 10) قبل ما تحسب. وخزّن الـ URL الكامل لكل عنصر عشان ترجعله.', 'Links inside a page are often relative (`catalogue/book-1/index.html`); `urljoin(page_url, href)` makes them full. Prices and numbers arrive as text with symbols (`£47.82`, `(22 available)`) — clean them with regex (week 10) before calculating. Store each item’s full URL so you can go back to it.'),
          ex: 'import re\nfrom urllib.parse import urljoin\npage = "https://books.toscrape.com/catalogue/page-2.html"\nfor href in ["a-light-in-the-attic_1000/index.html", "../index.html", "/static/x.css", "https://other.site/p"]:\n    print(href, "->", urljoin(page, href))\nprice = float(re.sub(r"[^\\d.]", "", "£47.82"))\nstock = int(re.search(r"\\d+", "In stock (22 available)").group())\nprint(price, stock)', run: 1 }
      ],
      practice: [
        B('ثبّت beautifulsoup4 وطلّع من HTML المثال: العنوان والسعر كرقم والتقييم كرقم والتوفّر.', 'Install beautifulsoup4 and extract from the sample HTML the title, the price as a number, the rating as a number and availability.'),
        B('احفظ صفحة من books.toscrape.com بـ requests في ملف، واشتغل على الملف (متطلبش الصفحة كل مرة).', 'Save a books.toscrape.com page with requests to a file and work on the file (do not request the page every time).'),
        B('طلّع كل لينكات الكتب من الصفحة وحوّلها لـ URLs كاملة بـ urljoin.', 'Extract every book link on the page and make them full URLs with urljoin.'),
        B('جرّب `select_one` على حاجة مش موجودة واكتب الكود اللي يتعامل مع None.', 'Try `select_one` on something missing and write the code that handles None.')
      ],
      code: [
        { u: B('دالة تحليل صفحة كتب', 'A function to parse a books page'), p: 'import re\nfrom urllib.parse import urljoin\nfrom bs4 import BeautifulSoup\n\nRATING = {"One": 1, "Two": 2, "Three": 3, "Four": 4, "Five": 5}\n\ndef parse_list(html: str, page_url: str) -> list[dict]:\n    soup = BeautifulSoup(html, "html.parser")\n    books = []\n    for pod in soup.select("article.product_pod"):\n        a = pod.select_one("h3 a")\n        price = pod.select_one(".price_color")\n        rating = pod.select_one(".star-rating")\n        books.append({\n            "title": a["title"],\n            "url": urljoin(page_url, a["href"]),\n            "price": float(re.sub(r"[^\\d.]", "", price.get_text())) if price else None,\n            "rating": RATING.get(rating["class"][1]) if rating else None,\n            "in_stock": "In stock" in pod.get_text(),\n        })\n    return books' }
      ],
      words: [
        { t: 'Beautiful Soup', m: B('مكتبة Python لتحليل HTML والتدوير فيه', 'a Python library to parse and search HTML'), ex: 'from bs4 import BeautifulSoup' },
        { t: 'parse tree', m: B('الـ HTML بعد ما اتحوّل لشجرة عناصر', 'the HTML turned into a tree of elements'), ex: 'soup = BeautifulSoup(html, "html.parser")' },
        { t: 'select_one', m: B('أول عنصر يطابق CSS selector أو None', 'the first element matching a CSS selector, or None'), ex: 'pod.select_one(".price_color")' },
        { t: 'get_text', m: B('بترجّع النص اللي جوه العنصر', 'returns the text inside an element'), ex: 'el.get_text(strip=True)' },
        { t: 'urljoin', m: B('بتحوّل لينك نسبي لكامل حسب الصفحة', 'turns a relative link into a full one based on the page'), ex: 'urljoin(page, href)' },
        { t: 'relative URL', m: B('لينك من غير الدومين، نسبة للصفحة الحالية', 'a link without the domain, relative to the current page'), ex: '../index.html' }
      ],
      read: [{ lib: 'Beautiful Soup documentation', what: B('اقرا Quick Start وSearching the tree وCSS selectors.', 'Read Quick Start, Searching the tree and CSS selectors.') }, { lib: 'Automate the Boring Stuff with Python', what: B('فصل Web Scraping: جزء Parsing HTML with Beautiful Soup.', 'The Web Scraping chapter: Parsing HTML with Beautiful Soup.') }],
      challenge: B('اكتب `parse_detail(html, url)` لصفحة كتاب واحد في books.toscrape.com: العنوان والسعر والتوفّر كرقم والوصف وUPC والقسم (من الـ breadcrumb) — على ملف HTML محفوظ.', 'Write `parse_detail(html, url)` for a single book page on books.toscrape.com: the title, price, stock as a number, description, UPC and category (from the breadcrumb) — on a saved HTML file.'),
      quiz: [
        { q: B('`soup.select_one(".x")` لو مفيش عنصر:', '`soup.select_one(".x")` when nothing matches:'), o: ['None', B('خطأ', 'an error'), '[]'], a: 0, why: B('اتأكد قبل الاستخدام.', 'Check before using it.') },
        { q: B('`urljoin("https://a.com/x/page.html", "../img.png")`:', '`urljoin("https://a.com/x/page.html", "../img.png")`:'), o: ['https://a.com/img.png', 'https://a.com/x/img.png', '../img.png'], a: 0, why: B('.. بيطلع فولدر.', '.. goes up a folder.') },
        { q: B('`el["class"]` على `class="star-rating Four"`:', '`el["class"]` on `class="star-rating Four"`:'), o: ['["star-rating", "Four"]', '"star-rating Four"', '"Four"'], a: 0, why: B('class بيرجع قايمة.', 'class returns a list.') }
      ] },

    { title: B('سحب موقع كامل بالصفحات', 'Scraping a whole site, page by page'),
      goal: B('تمشي على كل صفحات قسم بلينك «next»، وتدخل صفحات التفاصيل، بـ Session وتأخير وcache، وتحفظ النتيجة CSV وExcel.', 'Walk every page of a section through the «next» link, visit detail pages, with a Session, delays and a cache, and save the result as CSV and Excel.'),
      learn: [
        { h: B('لينك next لحد ما يخلص', 'Follow next until it ends'),
          p: B('ابدأ من الصفحة الأولى، حلّلها، ولاقي لينك «next» (`li.next a`)، وكمّل لحد ما ميبقاش موجود. حط حد أقصى لعدد الصفحات (أمان)، و`time.sleep` بين كل طلب، وخلي الدالة generator بترجّع العناصر.', 'Start from the first page, parse it, find the «next» link (`li.next a`) and continue until it is gone. Set a maximum page count (a safety net), `time.sleep` between requests, and make the function a generator yielding items.'),
          ex: 'import time, requests\nfrom urllib.parse import urljoin\nfrom bs4 import BeautifulSoup\n\nSESSION = requests.Session()\nSESSION.headers["User-Agent"] = "python-journey/1.0 (contact: you@example.com)"\n\ndef crawl(start_url, max_pages=60, delay=1.0):\n    url, pages = start_url, 0\n    while url and pages < max_pages:\n        r = SESSION.get(url, timeout=15)\n        r.raise_for_status()\n        soup = BeautifulSoup(r.text, "html.parser")\n        yield from parse_list(r.text, url)          # from yesterday\n        nxt = soup.select_one("li.next a")\n        url = urljoin(url, nxt["href"]) if nxt else None\n        pages += 1\n        time.sleep(delay)\n\nbooks = list(crawl("https://books.toscrape.com/catalogue/category/books/travel_2/index.html"))\nprint(len(books), books[0])' },
        { h: B('cache: متطلبش نفس الصفحة مرتين', 'A cache: never fetch the same page twice'),
          p: B('وانت بتطوّر السكربت هتشغّله 50 مرة. خزّن كل صفحة جبتها في فولدر `cache/` باسم من الـ hash بتاع الـ URL، ولو الملف موجود وجديد اقرا منه. ده بيريح الموقع ويسرّعك جدًا. (مكتبة `requests-cache` بتعمل ده لوحدها لو حبيت.)', 'While developing you will run the script 50 times. Store every fetched page in a `cache/` folder named by the URL’s hash, and read from it when the file exists and is fresh. It spares the site and speeds you up a lot. (The `requests-cache` library does this for you if you prefer.)'),
          ex: 'import hashlib, time\nfrom pathlib import Path\n\nCACHE = Path("cache"); CACHE.mkdir(exist_ok=True)\n\ndef cached_get(url: str, max_age_hours: float = 12, fetch=None) -> str:\n    path = CACHE / (hashlib.sha256(url.encode()).hexdigest()[:20] + ".html")\n    if path.exists() and time.time() - path.stat().st_mtime < max_age_hours * 3600:\n        return path.read_text(encoding="utf-8")\n    html = fetch(url)\n    path.write_text(html, encoding="utf-8")\n    return html\n\ncalls = []\nfake = lambda u: (calls.append(u), f"<html>{u}</html>")[1]\ncached_get("https://books.toscrape.com/", fetch=fake)\ncached_get("https://books.toscrape.com/", fetch=fake)\nprint("network calls:", len(calls))', run: 1 },
        { h: B('صفحات التفاصيل والحفظ', 'Detail pages and saving'),
          p: B('القايمة فيها بيانات قليلة؛ التفاصيل (الوصف وعدد المتاح) في صفحة كل منتج. لف على اللينكات بـ تأخير، وامسك الأخطاء لكل صفحة لوحدها (صفحة واحدة بايظة متوقفش الكل)، وسجّل الفاشلين. وفي الآخر احفظ CSV وExcel منسّق (أسبوع 11) ومعاهم تاريخ السحب.', 'The list holds little data; the details (description, quantity available) are on each product’s page. Loop over the links with a delay, catch errors per page (one broken page must not stop everything), and record the failures. Finally save a CSV and a formatted Excel (week 11) with the scrape date.'),
          ex: 'import csv, logging, time\nfrom datetime import date\n\nlog = logging.getLogger("scraper")\n\ndef enrich(books, delay=1.0):\n    failed = []\n    for b in books:\n        try:\n            html = cached_get(b["url"], fetch=lambda u: SESSION.get(u, timeout=15).text)\n            b.update(parse_detail(html, b["url"]))\n        except Exception:\n            log.exception("detail page failed: %s", b["url"])\n            failed.append(b["url"])\n        time.sleep(delay)\n    return failed\n\ndef save_csv(rows, path):\n    with open(path, "w", newline="", encoding="utf-8-sig") as f:\n        w = csv.DictWriter(f, fieldnames=list(rows[0]) + ["scraped_on"])\n        w.writeheader()\n        w.writerows({**r, "scraped_on": date.today().isoformat()} for r in rows)' }
      ],
      practice: [
        B('اسحب قسم «Travel» كله من books.toscrape.com (صفحات القايمة بس) واطبع عدد الكتب ومتوسط السعر.', 'Scrape the whole «Travel» category of books.toscrape.com (list pages only) and print the book count and average price.'),
        B('زوّد cache وشغّل السكربت مرتين وقيس الوقت.', 'Add a cache, run the script twice and time it.'),
        B('ادخل صفحات التفاصيل لأول 10 كتب بتأخير ثانية وطلّع الوصف وعدد المتاح.', 'Visit the detail pages of the first 10 books with a 1-second delay and extract the description and quantity.'),
        B('احفظ النتيجة CSV وExcel منسّق.', 'Save the result as CSV and a formatted Excel file.')
      ],
      code: [
        { u: B('تقرير سريع من البيانات المسحوبة', 'A quick report from scraped data'), p: 'from collections import Counter\nfrom statistics import mean\n\nbooks = [{"title": "A", "price": 51.77, "rating": 3, "in_stock": True}, {"title": "B", "price": 13.99, "rating": 5, "in_stock": False}, {"title": "C", "price": 22.65, "rating": 5, "in_stock": True}]\nprint("books:", len(books), "| average price:", round(mean(b["price"] for b in books), 2))\nprint("ratings:", dict(sorted(Counter(b["rating"] for b in books).items())))\nbest_value = min((b for b in books if b["rating"] >= 4), key=lambda b: b["price"])\nprint("best value 4+ stars:", best_value["title"], best_value["price"])', run: 1 }
      ],
      words: [
        { t: 'crawler', m: B('برنامج بيمشي من صفحة للتانية باللينكات', 'a program moving from page to page by links'), ex: 'follow li.next a' },
        { t: 'next page link', m: B('اللينك اللي بيوديك للصفحة الجاية في القايمة', 'the link to the following page of a list'), ex: 'li.next a' },
        { t: 'detail page', m: B('صفحة منتج أو عنصر واحد بكل تفاصيله', 'the page of one product or item with all its details'), ex: 'catalogue/book-1/index.html' },
        { t: 'response cache', m: B('تخزين الصفحات اللي جبتها عشان متطلبهاش تاني', 'storing fetched pages so you do not request them again'), ex: 'cache/<hash>.html' },
        { t: 'politeness delay', m: B('انتظار بين الطلبات عشان متضغطش على الموقع', 'a wait between requests so you do not overload a site'), ex: 'time.sleep(1.5)' },
        { t: 'max pages', m: B('حد أقصى للصفحات كشبكة أمان', 'a page limit as a safety net'), ex: 'max_pages=60' }
      ],
      read: [{ lib: 'Books to Scrape', what: B('اعرف عدد صفحات قسم كامل وشكل لينك next.', 'Find the page count of a whole category and the shape of the next link.') }, { lib: 'Real Python Tutorials', what: B('دوّر على «web scraping beautiful soup».', 'Search for «web scraping beautiful soup».') }],
      challenge: B('اسحب كل الـ 1000 كتاب من books.toscrape.com (50 صفحة) بـ cache وتأخير ثانية، واطلّع Excel فيه شيت لكل تقييم (1 لـ 5) وشيت ملخص بمتوسط السعر لكل تقييم — وسجّل الوقت الكلي وعدد الطلبات الحقيقية.', 'Scrape all 1,000 books on books.toscrape.com (50 pages) with a cache and a 1-second delay, and produce an Excel file with a sheet per rating (1 to 5) and a summary sheet with the average price per rating — logging the total time and the real request count.'),
      quiz: [
        { q: B('إمتى يقف الـ crawler؟', 'When does the crawler stop?'), o: [B('مفيش لينك next أو وصل للحد الأقصى', 'no next link, or the page limit is reached'), B('بعد أول خطأ', 'after the first error'), B('عمره ما يقف', 'never')], a: 0, why: B('الشرطين.', 'Both conditions.') },
        { q: B('فايدة الـ cache وانت بتطوّر:', 'The point of a cache while developing:'), o: [B('متطلبش نفس الصفحة من الموقع كل مرة', 'not fetching the same page from the site every time'), B('يخلي البيانات أحدث', 'fresher data'), B('بيتخطى robots.txt', 'it bypasses robots.txt')], a: 0, why: B('أرحم وأسرع.', 'Kinder and faster.') },
        { q: B('صفحة تفاصيل واحدة وقعت:', 'One detail page crashed:'), o: [B('سجّلها وكمّل الباقي', 'log it and continue with the rest'), B('وقّف كل حاجة', 'stop everything'), B('تجاهلها من غير لوج', 'ignore it with no log')], a: 0, why: B('try/except لكل صفحة.', 'try/except per page.') }
      ] },

    { title: B('الصفحات اللي بتتبني بـ JavaScript: Playwright', 'Pages built by JavaScript: Playwright'),
      goal: B('تسحب من صفحات مبتظهرش بياناتها في الـ HTML الأصلي، بمتصفح حقيقي من Python (Playwright): تستنى العناصر، وتدوس وتملا فورمز، وتاخد screenshot وPDF — وتدوّر على الـ API المخفي الأول.', 'Scrape pages whose data is missing from the original HTML, with a real browser driven from Python (Playwright): wait for elements, click and fill forms, take screenshots and PDFs — and look for the hidden API first.'),
      learn: [
        { h: B('ليه requests مش كفاية أحيانًا', 'Why requests is sometimes not enough'),
          p: B('مواقع كتير بتبعت HTML فاضي وبعدين JavaScript يجيب البيانات ويرسمها. requests بياخد الـ HTML الأول بس، فمش هتلاقي البيانات. الحل الأحسن: Network tab ولاقي طلب الـ JSON واستخدمه بـ requests (أسرع 100 مرة). لو مفيش، متصفح حقيقي: Playwright.', 'Many sites send an empty HTML and then JavaScript fetches and draws the data. requests only gets that first HTML, so the data is not there. The best fix: find the JSON request in the Network tab and call it with requests (100× faster). If there is none, a real browser: Playwright.'),
          ex: 'import requests\nr = requests.get("https://quotes.toscrape.com/js/", timeout=15)\nprint("quote" in r.text, r.text.count(\'class="quote"\'))   # the quotes are not in the raw HTML\nprint("var data" in r.text)                                    # they sit in a script the browser runs' },
        { h: B('أول سكربت Playwright', 'A first Playwright script'),
          p: B('`pip install playwright` وبعدين `playwright install chromium` مرة واحدة. `sync_playwright()` يفتح متصفح (headless من غير شاشة)، و`page.goto(url)`، و`page.wait_for_selector(".quote")` يستنى البيانات تترسم، و`page.locator(".quote")` يرجّع العناصر و`.all_inner_texts()` نصوصها.', '`pip install playwright` then `playwright install chromium` once. `sync_playwright()` opens a browser (headless, no window), `page.goto(url)`, `page.wait_for_selector(".quote")` waits for the data to be drawn, and `page.locator(".quote")` returns the elements with `.all_inner_texts()` for their text.'),
          ex: '# pip install playwright && playwright install chromium\nfrom playwright.sync_api import sync_playwright\n\nwith sync_playwright() as p:\n    browser = p.chromium.launch(headless=True)\n    page = browser.new_page(user_agent="python-journey/1.0 (contact: you@example.com)")\n    page.goto("https://quotes.toscrape.com/js/", timeout=30000)\n    page.wait_for_selector(".quote")\n    for q in page.locator(".quote").all()[:3]:\n        print(q.locator(".text").inner_text(), "—", q.locator(".author").inner_text())\n    browser.close()' },
        { h: B('تدوس وتملا وتصوّر', 'Click, fill and capture'),
          p: B('`page.fill("#username", "...")` و`page.click("text=Login")` و`page.get_by_role("button", name="Next").click()`. `page.screenshot(path="s.png", full_page=True)` صورة، و`page.pdf(path="r.pdf")` بيحوّل الصفحة PDF (ممتاز لتقرير HTML بتاعك من أسبوع 14!). متستخدمش ده تدخل حسابات بباسوردات حقيقية في السكربت؛ ودايمًا شوف الشروط.', '`page.fill("#username", "...")`, `page.click("text=Login")` and `page.get_by_role("button", name="Next").click()`. `page.screenshot(path="s.png", full_page=True)` takes a picture and `page.pdf(path="r.pdf")` turns the page into a PDF (great for your week 14 HTML report!). Do not use this to log into accounts with real passwords in the script, and always check the terms.'),
          ex: 'from pathlib import Path\nfrom playwright.sync_api import sync_playwright\n\nreport = Path("out/dashboard.html").resolve()\nwith sync_playwright() as p:\n    browser = p.chromium.launch()\n    page = browser.new_page()\n    page.goto(report.as_uri())\n    page.wait_for_timeout(500)                          # let the charts draw\n    page.screenshot(path="out/dashboard.png", full_page=True)\n    page.pdf(path="out/dashboard.pdf", format="A4", print_background=True)\n    # paging through a JS site:\n    page.goto("https://quotes.toscrape.com/js/")\n    while True:\n        page.wait_for_selector(".quote")\n        print(page.locator(".quote .author").all_inner_texts())\n        nxt = page.locator("li.next a")\n        if nxt.count() == 0:\n            break\n        nxt.click()\n    browser.close()' }
      ],
      practice: [
        B('اطلب quotes.toscrape.com/js بـ requests وشوف إن الاقتباسات مش في الـ HTML.', 'Request quotes.toscrape.com/js with requests and see the quotes are not in the HTML.'),
        B('ثبّت Playwright وطلّع كل الاقتباسات من النسخة /js بالصفحات.', 'Install Playwright and extract every quote from the /js version, page by page.'),
        B('حوّل `dashboard.html` بتاعك لـ PDF وPNG بـ Playwright.', 'Turn your `dashboard.html` into a PDF and a PNG with Playwright.'),
        B('افتح Network tab على quotes.toscrape.com/scroll ولاقي الـ API المخفي واسحب منه بـ requests.', 'Open the Network tab on quotes.toscrape.com/scroll, find the hidden API and fetch from it with requests.')
      ],
      code: [
        { u: B('الـ API المخفي بدل المتصفح', 'The hidden API instead of a browser'), p: 'import requests\n\n# quotes.toscrape.com/scroll loads more quotes from this JSON endpoint (seen in DevTools → Network)\nquotes, page = [], 1\nwhile True:\n    data = requests.get("https://quotes.toscrape.com/api/quotes", params={"page": page}, timeout=15).json()\n    quotes += [(q["text"], q["author"]["name"]) for q in data["quotes"]]\n    if not data["has_next"]:\n        break\n    page += 1\nprint(len(quotes), "quotes;", quotes[0])' }
      ],
      words: [
        { t: 'headless browser', m: B('متصفح حقيقي بيشتغل من غير شاشة', 'a real browser running without a window'), ex: 'chromium.launch(headless=True)' },
        { t: 'Playwright', m: B('مكتبة بتتحكم في متصفح حقيقي من الكود', 'a library that drives a real browser from code'), ex: 'from playwright.sync_api import sync_playwright' },
        { t: 'locator', m: B('طريقة Playwright للإشارة لعناصر في الصفحة', 'Playwright’s way to point at elements on a page'), ex: 'page.locator(".quote")' },
        { t: 'wait_for_selector', m: B('بيستنى لحد ما عنصر يظهر', 'waits until an element appears'), ex: 'page.wait_for_selector(".quote")' },
        { t: 'client-side rendering', m: B('الصفحة بتترسم بـ JavaScript في المتصفح مش في السيرفر', 'the page is drawn by JavaScript in the browser, not on the server'), ex: 'empty HTML + a data request' },
        { t: 'Network tab', m: B('جزء في DevTools بيوريك كل طلبات الصفحة', 'the DevTools panel listing every request a page makes'), ex: 'Fetch/XHR → a JSON response' }
      ],
      read: [{ lib: 'Playwright for Python', what: B('اقرا Installation وLocators وScreenshots.', 'Read Installation, Locators and Screenshots.') }, { lib: 'Quotes to Scrape', what: B('جرّب النسخ /js و/scroll و/login.', 'Try the /js, /scroll and /login versions.') }],
      challenge: B('اعمل `snap.py`: ياخد قايمة URLs من ملف، ويفتح كل واحد بـ Playwright، وياخد screenshot كاملة وPDF في فولدر باسم التاريخ، ويكتب CSV بعنوان كل صفحة ووقت التحميل — ومع تأخير بين المواقع.', 'Write `snap.py`: take a list of URLs from a file, open each with Playwright, save a full screenshot and a PDF into a folder named with the date, and write a CSV with each page’s title and load time — with a delay between sites.'),
      quiz: [
        { q: B('البيانات مش في `r.text` بس بتظهر في المتصفح. أول حل:', 'The data is missing from `r.text` but shows in the browser. The first fix:'), o: [B('دوّر على الـ API في Network tab', 'look for the API in the Network tab'), B('Playwright على طول', 'Playwright right away'), B('Regex على الـ HTML', 'regex on the HTML')], a: 0, why: B('أسرع وأثبت.', 'Faster and more stable.') },
        { q: B('`page.wait_for_selector(".quote")` فايدتها:', '`page.wait_for_selector(".quote")` is for:'), o: [B('تستنى لحد ما JavaScript يرسم البيانات', 'waiting until JavaScript has drawn the data'), B('تسرّع الصفحة', 'speeding the page up'), B('تمسح العناصر', 'removing elements')], a: 0, why: B('من غيرها ممكن تقرا صفحة فاضية.', 'Without it you may read an empty page.') },
        { q: B('عشان تحوّل تقرير HTML لـ PDF أوتوماتيك:', 'To turn an HTML report into a PDF automatically:'), o: ['page.pdf(...)', 'requests.get(...)', 'BeautifulSoup(...)'], a: 0, why: B('Playwright بيطبع.', 'Playwright prints it.') }
      ] },

    { title: B('مراقبة التغييرات والصيانة', 'Watching for changes and maintenance'),
      goal: B('تحوّل الـ scraper لمراقب: يحفظ لقطة كل مرة، ويقارنها باللي فاتت (سعر نزل، منتج جديد، اتشال)، ويبلّغك، ويقاوم تغيير شكل الموقع.', 'Turn a scraper into a watcher: save a snapshot each time, compare it with the last one (price drop, new product, removed), alert you, and survive changes in the site’s layout.'),
      learn: [
        { h: B('لقطة ومقارنة', 'A snapshot and a comparison'),
          p: B('كل تشغيل: احفظ النتيجة في `snapshots/YYYY-MM-DD_HHMM.json` بمفتاح ثابت لكل عنصر (الـ URL أو SKU). وقارن بآخر لقطة: الموجود في الجديد ومش في القديم = جديد، والعكس = اتشال، والاتنين بس السعر اتغير = تغيير. كده بتعمل «مراقب أسعار» أو «مراقب وظائف» أو «مراقب أخبار» بنفس الكود.', 'Every run: save the result to `snapshots/YYYY-MM-DD_HHMM.json` with a stable key per item (the URL or a SKU). Compare with the last snapshot: in the new but not the old = new, the reverse = removed, in both with a different price = changed. The same code makes a «price watcher», a «job watcher» or a «news watcher».'),
          ex: 'def diff(old: dict, new: dict, min_change: float = 0.05):\n    added = sorted(new.keys() - old.keys())\n    removed = sorted(old.keys() - new.keys())\n    changed = []\n    for key in new.keys() & old.keys():\n        before, after = old[key]["price"], new[key]["price"]\n        if before and abs(after - before) / before >= min_change:\n            changed.append((key, before, after))\n    return added, removed, sorted(changed, key=lambda c: c[2] - c[1])\n\nold = {"/b1": {"price": 50.0}, "/b2": {"price": 20.0}, "/b3": {"price": 30.0}}\nnew = {"/b1": {"price": 42.5}, "/b2": {"price": 20.4}, "/b4": {"price": 15.0}}\nadded, removed, changed = diff(old, new)\nprint("new:", added, "| gone:", removed)\nfor key, a, b in changed:\n    print(f"{key}: {a} -> {b} ({(b - a) / a:+.0%})")', run: 1 },
        { h: B('لما الموقع يغيّر شكله', 'When the site changes its layout'),
          p: B('أي موقع هيغيّر الـ HTML يوم ما، والـ scraper هيرجّع فاضي من غير ما يقع — وده أخطر. ضيف «فحوصات سلامة»: لو عدد العناصر أقل من المتوقع جدًا، أو نسبة كبيرة منها من غير سعر، **متكتبش** لقطة جديدة وابعت تنبيه. ولكل حقل مهم جرّب أكتر من selector بالترتيب.', 'Every site will change its HTML one day, and the scraper will return nothing without crashing — which is worse. Add «sanity checks»: if the item count is far below normal, or many items have no price, **do not** write a new snapshot and send an alert. For each important field try several selectors in order.'),
          ex: 'def first_text(soup_el, selectors):\n    """Try several selectors in order; return the first text found or None."""\n    for sel in selectors:\n        el = soup_el.select_one(sel)\n        if el and el.get_text(strip=True):\n            return el.get_text(strip=True)\n    return None\n\ndef looks_healthy(items, expected_min=15, max_missing=0.2):\n    if len(items) < expected_min:\n        return False, f"only {len(items)} items (expected at least {expected_min})"\n    missing = sum(1 for i in items if i.get("price") is None) / len(items)\n    if missing > max_missing:\n        return False, f"{missing:.0%} of items have no price"\n    return True, "ok"\n\nprint(looks_healthy([{"price": 1.0}] * 20))\nprint(looks_healthy([{"price": None}] * 18 + [{"price": 3.0}] * 2))\nprint(looks_healthy([{"price": 1.0}] * 4))', run: 1 },
        { h: B('تشغيل دوري وتنبيه', 'Running regularly and alerting'),
          p: B('المراقب بيشتغل لوحده (كل 6 ساعات مثلًا) بـ cron أو Task Scheduler (أسبوع 20) أو Schedule Trigger في n8n بينادي السكربت. لما يلاقي تغيير مهم يبعت Telegram أو يبعت JSON لـ n8n Webhook (أسبوع 13) اللي يوزّعه. ومتبعتش تنبيه لو مفيش جديد — التنبيهات الكتير بتتجاهل.', 'The watcher runs by itself (every 6 hours, say) via cron or Task Scheduler (week 20) or an n8n Schedule Trigger calling the script. When it finds an important change it sends Telegram or posts JSON to an n8n Webhook (week 13) to spread it. Send nothing when nothing changed — too many alerts get ignored.'),
          ex: 'def build_message(added, removed, changed, titles):\n    lines = []\n    for key, before, after in changed:\n        arrow = "📉" if after < before else "📈"\n        lines.append(f"{arrow} {titles.get(key, key)}: {before:.2f} → {after:.2f}")\n    if added:\n        lines.append(f"🆕 {len(added)} new: " + ", ".join(titles.get(k, k) for k in added[:5]))\n    if removed:\n        lines.append(f"❌ {len(removed)} removed")\n    return "\\n".join(lines)   # empty string = nothing to send\n\nmsg = build_message(["/b4"], [], [("/b1", 50.0, 42.5)], {"/b1": "Sharp Objects", "/b4": "Soumission"})\nprint(msg or "(no alert)")', run: 1 }
      ],
      practice: [
        B('اعمل لقطتين وهميتين وجرّب diff بحالات: سعر نزل، سعر طلع، جديد، اتشال.', 'Make two fake snapshots and try diff with: a price drop, a rise, a new item and a removed one.'),
        B('غيّر selector السعر في الـ scraper لحاجة غلط وشوف فحص السلامة بيمنع اللقطة.', 'Break the price selector in the scraper and watch the sanity check block the snapshot.'),
        B('ضيف selectors بديلة لحقلين.', 'Add fallback selectors for two fields.'),
        B('خلي الرسالة تتبعت Telegram بس لو فيه تغيير.', 'Send the message to Telegram only when something changed.')
      ],
      code: [
        { u: B('حفظ وقراءة آخر لقطة', 'Saving and loading the last snapshot'), p: 'import json\nfrom datetime import datetime\nfrom pathlib import Path\n\nSNAPS = Path("snapshots"); SNAPS.mkdir(exist_ok=True)\n\ndef save_snapshot(items: dict) -> Path:\n    path = SNAPS / f"{datetime.now():%Y-%m-%d_%H%M}.json"\n    path.write_text(json.dumps(items, ensure_ascii=False, indent=1), encoding="utf-8")\n    return path\n\ndef last_snapshot() -> dict:\n    files = sorted(SNAPS.glob("*.json"))\n    return json.loads(files[-1].read_text(encoding="utf-8")) if files else {}\n\nprint(last_snapshot())\nsave_snapshot({"/b1": {"price": 42.5}})\nprint(last_snapshot())', run: 1 }
      ],
      words: [
        { t: 'snapshot', m: B('نسخة محفوظة من البيانات في لحظة معيّنة', 'a saved copy of the data at a moment'), ex: 'snapshots/2026-10-01_0800.json' },
        { t: 'diff', m: B('المقارنة بين نسختين: الجديد والمحذوف والمتغير', 'the comparison of two versions: added, removed and changed'), ex: 'new.keys() - old.keys()' },
        { t: 'price monitor', m: B('برنامج بيتابع الأسعار ويبلّغك بالتغيير', 'a program that tracks prices and reports changes'), ex: '📉 Sharp Objects: 50 → 42.5' },
        { t: 'sanity check', m: B('فحص سريع إن النتيجة منطقية قبل ما تعتمد عليها', 'a quick check that a result makes sense before relying on it'), ex: 'at least 15 items, most with a price' },
        { t: 'fallback selector', m: B('selector بديل لو الأساسي ملقاش حاجة', 'an alternative selector when the main one finds nothing'), ex: '[".price_color", ".price", "[itemprop=price]"]' },
        { t: 'alert fatigue', m: B('إنك تتجاهل التنبيهات لأنها كتير ومش مهمة', 'ignoring alerts because there are too many unimportant ones'), ex: 'send only when something changed' }
      ],
      read: [{ lib: 'Real Python Tutorials', what: B('دوّر على «web scraping» واقرا جزء التعامل مع تغيّر المواقع.', 'Search for «web scraping» and read the part on handling site changes.') }, { lib: 'Beautiful Soup documentation', what: B('اقرا Navigating the tree بسرعة.', 'Skim Navigating the tree.') }],
      challenge: B('اكتب `watch.py` بيشغّل الـ scraper بتاعك، ويطبّق فحص السلامة، ويقارن بآخر لقطة، ويحفظ اللقطة الجديدة، ويطبع رسالة التغييرات (أو «مفيش جديد») — وجرّبه 3 مرات بتعديل يدوي على لقطة قديمة عشان تشوف كل نوع تغيير.', 'Write `watch.py` that runs your scraper, applies the sanity check, compares with the last snapshot, saves the new one and prints the change message (or «nothing new») — run it 3 times, editing an old snapshot by hand to see every kind of change.'),
      quiz: [
        { q: B('أخطر حاجة لما الموقع يغيّر شكله:', 'The most dangerous thing when a site changes its layout:'), o: [B('الـ scraper يرجّع فاضي من غير ما يقع', 'the scraper returns nothing without crashing'), B('الـ scraper يقع', 'the scraper crashes'), B('يبطّأ', 'it slows down')], a: 0, why: B('هتفتكر مفيش منتجات!', 'You would think there are no products!') },
        { q: B('عشان تعرف المنتجات الجديدة من لقطتين:', 'To find new products between two snapshots:'), o: ['new.keys() - old.keys()', 'old.keys() - new.keys()', 'new.keys() & old.keys()'], a: 0, why: B('الفرق.', 'The difference.') },
        { q: B('المراقب ملقاش أي تغيير. يعمل إيه؟', 'The watcher found no change. What should it do?'), o: [B('ميبعتش تنبيه', 'send no alert'), B('يبعت «مفيش جديد» كل مرة', 'send «nothing new» every time'), B('يوقف للأبد', 'stop forever')], a: 0, why: B('تجنّب alert fatigue.', 'Avoid alert fatigue.') }
      ] },

    { title: B('مشروع الشهر الرابع واختبار الأسبوع', 'The month 4 project and weekly test'),
      goal: B('تبني مراقب أسعار كامل بالويب كله اللي اتعلمته الشهر ده، وتعدّي اختبار الأسبوع عشان امتحان الشهر يفتح.', 'Build a complete price watcher with all the web skills of this month, and pass the weekly test to open the month exam.'),
      review: [
        B('القواعد: API الأول، الشروط وrobots.txt، السرعة، وعرّف نفسك.', 'The rules: an API first, terms and robots.txt, speed, and identifying yourself.'),
        B('Beautiful Soup: select وselect_one وget_text والـ attributes وurljoin.', 'Beautiful Soup: select, select_one, get_text, attributes and urljoin.'),
        B('crawl بلينك next، والـ cache، وصفحات التفاصيل، والحفظ CSV/Excel.', 'Crawling by the next link, caching, detail pages, and saving CSV/Excel.'),
        B('Playwright للصفحات بـ JavaScript، والـ API المخفي، وscreenshot وPDF.', 'Playwright for JavaScript pages, the hidden API, screenshots and PDFs.'),
        B('اللقطات والمقارنة وفحص السلامة والـ selectors البديلة والتنبيه الذكي.', 'Snapshots, diffs, sanity checks, fallback selectors and smart alerts.')
      ],
      project: B('**مشروع الشهر: مراقب الأسعار** (`price_watch/`): (1) `config.toml` فيه أقسام من books.toscrape.com تراقبها ونسبة التغيير اللي تهمك والتأخير. (2) scraper بـ Session وUser-Agent بتواصل وcache وتأخير، ويحترم robots.txt (فحص بالكود). (3) فحص سلامة قبل حفظ أي لقطة. (4) مقارنة بآخر لقطة: نزول/طلوع سعر بالنسبة، جديد، اتشال. (5) تقرير HTML (أسبوع 14/15) بالتغييرات ورسم بياني لأرخص 10، ونسخة PDF بـ Playwright. (6) تنبيه Telegram أو n8n Webhook لو فيه تغيير بس (dry run افتراضيًا). (7) لوج، وكود خروج صح، و12 test على diff وparse (على HTML محفوظ في `tests/fixtures/`). README بيشرح إزاي تشغّله وإزاي تضيف موقع.', '**Month project: the price watcher** (`price_watch/`): (1) `config.toml` lists the books.toscrape.com categories to watch, the change threshold and the delay. (2) A scraper with a Session, a User-Agent with contact details, a cache and delays, honouring robots.txt (checked in code). (3) A sanity check before saving any snapshot. (4) A comparison with the last snapshot: price drops/rises by percentage, new, removed. (5) An HTML report (weeks 14/15) of the changes with a chart of the 10 cheapest, plus a PDF made with Playwright. (6) A Telegram or n8n Webhook alert only when something changed (dry run by default). (7) A log, the right exit code, and 12 tests on diff and parse (on HTML saved in `tests/fixtures/`). A README explaining how to run it and how to add a site.'),
      test: [
        { q: B('أول مصدر تدوّر عليه قبل الـ scraping:', 'The first source to look for before scraping:'), o: [B('API رسمي', 'an official API'), B('Playwright', 'Playwright'), B('Regex', 'regex')], a: 0, why: B('أثبت ومسموح.', 'Stable and allowed.') },
        { q: B('`rp.can_fetch(agent, url)` بترجّع False:', '`rp.can_fetch(agent, url)` returns False:'), o: [B('متسحبش الصفحة دي', 'do not fetch that page'), B('اسحبها أسرع', 'fetch it faster'), B('غيّر الـ agent', 'change the agent')], a: 0, why: B('robots بيمنع.', 'robots forbids it.') },
        { q: B('`soup.select("ul li")` بترجّع:', '`soup.select("ul li")` returns:'), o: [B('كل li جوه ul', 'every li inside a ul'), B('أول li', 'the first li'), B('النص', 'the text')], a: 0, why: B('قايمة.', 'A list.') },
        { q: B('`get_text(strip=True)`:', '`get_text(strip=True)`:'), o: [B('النص من غير مسافات الأطراف', 'the text without surrounding spaces'), B('الـ HTML', 'the HTML'), B('الـ attributes', 'the attributes')], a: 0, why: B('strip.', 'strip.') },
        { q: B('سعر `"£51.77"` لرقم:', 'The price `"£51.77"` as a number:'), o: ['float(re.sub(r"[^\\d.]", "", s))', 'int(s)', 'float(s)'], a: 0, why: B('شيل غير الأرقام والنقطة.', 'Strip everything but digits and the dot.') },
        { q: B('التأخير بين الطلبات اسمه:', 'The wait between requests is a:'), o: ['politeness delay', 'timeout', 'cache'], a: 0, why: B('عشان متضغطش الموقع.', 'So you do not overload the site.') },
        { q: B('الـ cache في الـ scraping بيقلل:', 'A cache in scraping reduces:'), o: [B('الطلبات على الموقع', 'requests to the site'), B('دقة البيانات', 'data accuracy'), B('الـ selectors', 'selectors')], a: 0, why: B('بتقرا من القرص.', 'You read from disk.') },
        { q: B('صفحة بتتبني بـ JavaScript وملقيتش API:', 'A JavaScript-built page and no API found:'), o: ['Playwright', 'requests + BeautifulSoup', 'csv'], a: 0, why: B('متصفح حقيقي.', 'A real browser.') },
        { q: B('`page.wait_for_selector(...)` بيمنع:', '`page.wait_for_selector(...)` prevents:'), o: [B('إنك تقرا الصفحة قبل ما البيانات ترسم', 'reading the page before the data is drawn'), B('الـ CORS', 'CORS'), B('الـ 429', '429s')], a: 0, why: B('بيستنى العنصر.', 'It waits for the element.') },
        { q: B('عدد المنتجات نزل من 500 لـ 3 فجأة:', 'The product count suddenly fell from 500 to 3:'), o: [B('غالبًا الموقع غيّر شكله؛ متحفظش وابعت تنبيه', 'probably a layout change; do not save, send an alert'), B('المحل فلّس', 'the shop went bust'), B('احفظ عادي', 'save as usual')], a: 0, why: B('فحص السلامة.', 'The sanity check.') },
        { q: B('مفتاح ثابت لكل منتج في اللقطة:', 'A stable key per product in a snapshot:'), o: [B('الـ URL أو SKU', 'the URL or a SKU'), B('ترتيبه في الصفحة', 'its position on the page'), B('السعر', 'the price')], a: 0, why: B('الترتيب والسعر بيتغيروا.', 'Position and price change.') },
        { q: B('تنبيه كل ساعة «مفيش جديد» بيعمل:', 'An hourly «nothing new» alert causes:'), o: ['alert fatigue', B('أمان أكتر', 'more safety'), B('سرعة', 'speed')], a: 0, why: B('هتتجاهل الكل.', 'You end up ignoring them all.') }
      ] }
  ]
};
