// Python week 17 — Object-oriented programming (OOP).
const B = (ar, en) => ({ ar, en });
module.exports = {
  level: B('متقدم', 'Advanced'),
  title: B('البرمجة بالكائنات (OOP)', 'Object-oriented programming (OOP)'),
  goal: B('تجمع البيانات والسلوك في كلاسات: __init__ وself والـ methods، والـ dunder methods والـ properties، والـ dataclasses والـ Enum، والوراثة والتركيب، وتعرف امتى الكلاس أحسن من الدوال — وتعيد بناء نظام الفواتير بكلاسات نضيفة.',
          'Bundle data and behaviour in classes: __init__, self and methods; dunder methods and properties; dataclasses and Enum; inheritance and composition; and know when a class beats plain functions — then rebuild the invoicing system with clean classes.'),
  days: [
    { title: B('الكلاس والكائن', 'Classes and objects'),
      goal: B('تعمل كلاس بـ __init__ وattributes وmethods، وتفهم self، وتعمل منه كذا كائن.', 'Write a class with __init__, attributes and methods, understand self, and create several objects from it.'),
      learn: [
        { h: B('ليه كلاس؟', 'Why a class?'),
          p: B('لحد دلوقتي العميل dict والدوال اللي بتشتغل عليه مفرّقة. الكلاس بيجمعهم: «قالب» فيه البيانات (attributes) والأفعال (methods). من القالب بتعمل كائنات (instances) كتير، كل واحد ببياناته. `class Customer:` واسم الكلاس بـ CamelCase.', 'So far a customer is a dict and the functions working on it are scattered. A class bundles them: a «template» holding the data (attributes) and the actions (methods). From the template you make many objects (instances), each with its own data. `class Customer:` with the class name in CamelCase.'),
          ex: 'class Customer:\n    def __init__(self, name, email, balance=0.0):\n        self.name = name\n        self.email = email.strip().lower()\n        self.balance = balance\n\n    def charge(self, amount):\n        self.balance += amount\n\n    def summary(self):\n        return f"{self.name} <{self.email}> owes {self.balance:,.2f}"\n\nsara = Customer("Sara", " SARA@Mail.com ")\nomar = Customer("Omar", "omar@mail.com", 120)\nsara.charge(450.5)\nprint(sara.summary())\nprint(omar.summary())', run: 1 },
        { h: B('self و__init__', 'self and __init__'),
          p: B('`__init__` بتتنفّذ لوحدها لما تعمل كائن جديد، وبتجهّز بياناته. `self` هو الكائن نفسه: `self.name` يعني «اسم الكائن ده». لما تكتب `sara.charge(10)` Python بتنادي `Customer.charge(sara, 10)` — عشان كده أول معامل دايمًا self.', '`__init__` runs by itself when you create a new object and prepares its data. `self` is the object itself: `self.name` means «this object’s name». When you write `sara.charge(10)` Python calls `Customer.charge(sara, 10)` — which is why the first parameter is always self.'),
          ex: 'class Counter:\n    def __init__(self, start=0):\n        print("making a counter at", start)\n        self.value = start\n\n    def add(self, n=1):\n        self.value += n\n        return self          # returning self lets you chain calls\n\nc = Counter(5)\nc.add().add(3)\nprint(c.value)\nprint(Counter.add(c, 10).value)   # what c.add(10) really does', run: 1 },
        { h: B('كل كائن ليه بياناته', 'Each object has its own data'),
          p: B('`isinstance(x, Customer)` بيسأل عن النوع، و`vars(x)` بيوريك attributes الكائن كـ dict. كل كائن مستقل: تغيير `sara.balance` مالوش دعوة بـ `omar`. وتقدر تحط كائنات في قوايم وdicts زي أي قيمة.', '`isinstance(x, Customer)` checks the type, and `vars(x)` shows an object’s attributes as a dict. Each object is independent: changing `sara.balance` has nothing to do with `omar`. You can keep objects in lists and dicts like any value.'),
          ex: 'class Product:\n    def __init__(self, sku, name, price, stock=0):\n        self.sku, self.name, self.price, self.stock = sku, name, price, stock\n\n    def value(self):\n        return self.price * self.stock\n\nitems = [Product("P-1", "Pen", 7.5, 120), Product("B-7", "Bag", 650, 4), Product("N-3", "Notebook", 45, 0)]\nprint(vars(items[0]))\nprint(sum(p.value() for p in items))\nprint([p.name for p in items if p.stock == 0], isinstance(items[1], Product))', run: 1 }
      ],
      practice: [
        B('اعمل كلاس `BankAccount` فيه deposit وwithdraw (يرفض لو الرصيد مش كفاية) وbalance.', 'Write a `BankAccount` class with deposit, withdraw (refusing when the balance is short) and balance.'),
        B('اعمل 3 حسابات وحرّك فلوس بينهم واطبع الأرصدة.', 'Create 3 accounts, move money between them and print the balances.'),
        B('حوّل dict العميل من أسبوع 5 لكلاس `Customer` بـ method بتنضّف الإيميل.', 'Turn the week 5 customer dict into a `Customer` class with a method that cleans the email.'),
        B('اطبع `vars()` لكائن وشوف إن كل كائن بياناته لوحده.', 'Print `vars()` of an object and see each object keeps its own data.')
      ],
      code: [
        { u: B('كلاس سلة مشتريات', 'A shopping-basket class'), p: 'class Basket:\n    def __init__(self):\n        self.lines = []            # (name, price, qty)\n\n    def add(self, name, price, qty=1):\n        if qty <= 0:\n            raise ValueError("qty must be positive")\n        self.lines.append((name, price, qty))\n\n    def total(self, vat=0.14):\n        return round(sum(p * q for _, p, q in self.lines) * (1 + vat), 2)\n\nb = Basket()\nb.add("Pen", 7.5, 4)\nb.add("Bag", 650)\nprint(len(b.lines), "lines, total", b.total())', run: 1 }
      ],
      words: [
        { t: 'class', m: B('قالب بيجمع بيانات وأفعال، بتعمل منه كائنات', 'a template bundling data and actions, from which you make objects'), ex: 'class Customer:' },
        { t: 'instance', m: B('كائن واحد معمول من كلاس', 'one object made from a class'), ex: 'sara = Customer("Sara", ...)' },
        { t: 'constructor', m: B('__init__: بتجهّز الكائن الجديد', '__init__: prepares a new object'), ex: 'def __init__(self, name):' },
        { t: 'self', m: B('الكائن نفسه جوه الـ methods بتاعته', 'the object itself inside its own methods'), ex: 'self.balance += amount' },
        { t: 'instance attribute', m: B('بيانات خاصة بكائن واحد', 'data belonging to one object'), ex: 'self.email' },
        { t: 'isinstance', m: B('بتسأل الكائن ده من النوع ده؟', 'asks whether an object is of a given type'), ex: 'isinstance(x, Customer)' }
      ],
      read: [{ lib: 'Classes (tutorial)', what: B('اقرا 9.3 A First Look at Classes.', 'Read 9.3 A First Look at Classes.') }, { lib: 'Real Python Tutorials', what: B('دوّر على «object-oriented programming in python 3».', 'Search for «object-oriented programming in python 3».') }],
      challenge: B('اعمل كلاس `Inventory` بيحفظ منتجات (dict من SKU لـ Product)، وفيه add وremove وrestock وsell (يرفض لو المخزون مش كفاية) وlow_stock(limit) وtotal_value — وجرّبه بقايمة أوامر صغيرة.', 'Write an `Inventory` class holding products (a dict from SKU to Product) with add, remove, restock, sell (refusing when stock is short), low_stock(limit) and total_value — and drive it with a small command menu.'),
      quiz: [
        { q: B('`__init__` بتتنفّذ امتى؟', 'When does `__init__` run?'), o: [B('لما تعمل كائن جديد', 'when you create a new object'), B('لما تمسح الكائن', 'when the object is deleted'), B('لما تطبعه', 'when you print it')], a: 0, why: B('constructor.', 'The constructor.') },
        { q: B('`self` في method هو:', '`self` in a method is:'), o: [B('الكائن اللي اتنادت عليه', 'the object it was called on'), B('الكلاس', 'the class'), B('كلمة محجوزة إجبارية الاسم', 'a reserved word that must be spelt so')], a: 0, why: B('الاسم اتفاق، بس الكل بيستخدمه.', 'The name is a convention everyone follows.') },
        { q: B('`a = Product(...)` و`b = Product(...)`؛ تغيير a.price:', '`a = Product(...)` and `b = Product(...)`; changing a.price:'), o: [B('ميغيرش b', 'does not change b'), B('يغيّر b', 'changes b'), B('يغيّر الكلاس', 'changes the class')], a: 0, why: B('كل كائن مستقل.', 'Each object is independent.') }
      ] },

    { title: B('الـ dunder methods والـ properties', 'Dunder methods and properties'),
      goal: B('تخلي كائناتك تتطبع وتتقارن وتترتب زي القيم العادية بـ __repr__ و__eq__ و__lt__، وتحمي بياناتها بـ @property، وتفرّق بين attribute الكلاس والكائن.', 'Make your objects print, compare and sort like built-in values with __repr__, __eq__ and __lt__, guard their data with @property, and tell class attributes from instance attributes.'),
      learn: [
        { h: B('__repr__ و__str__', '__repr__ and __str__'),
          p: B('من غيرهم `print(sara)` بيطبع `<__main__.Customer object at 0x…>`. `__repr__` للمبرمج (يوضّح الكائن بالظبط، ويظهر في القوايم والـ debugger)، و`__str__` للمستخدم (شكل لطيف لـ print). لو هتكتب واحد بس، اكتب `__repr__`.', 'Without them `print(sara)` shows `<__main__.Customer object at 0x…>`. `__repr__` is for programmers (shows the object exactly, and appears in lists and the debugger), and `__str__` is for users (a friendly look for print). If you write only one, write `__repr__`.'),
          ex: 'class Money:\n    def __init__(self, amount, currency="EGP"):\n        self.amount, self.currency = round(amount, 2), currency\n\n    def __repr__(self):\n        return f"Money({self.amount!r}, {self.currency!r})"\n\n    def __str__(self):\n        return f"{self.amount:,.2f} {self.currency}"\n\nprice = Money(1250.5)\nprint(price)            # __str__\nprint([price])          # __repr__ inside a list\nprint(repr(price))', run: 1 },
        { h: B('المقارنة والترتيب والعمليات', 'Comparing, sorting and operators'),
          p: B('`__eq__` بيحدد امتى كائنين «متساويين»، و`__lt__` (أصغر من) بيخلي `sorted()` يشتغل على كائناتك. و`__add__` بيخلي `+` يشتغل (فلوس + فلوس)، و`__len__` بيخلي `len()` يشتغل. الأسماء دي اسمها dunder (double underscore).', '`__eq__` decides when two objects are «equal», and `__lt__` (less than) lets `sorted()` work on your objects. `__add__` makes `+` work (money + money) and `__len__` makes `len()` work. These names are called dunders (double underscore).'),
          ex: 'class Money:\n    def __init__(self, amount, currency="EGP"):\n        self.amount, self.currency = round(amount, 2), currency\n    def __repr__(self):\n        return f"{self.amount:,.2f} {self.currency}"\n    def __eq__(self, other):\n        return (self.amount, self.currency) == (other.amount, other.currency)\n    def __lt__(self, other):\n        if self.currency != other.currency:\n            raise ValueError("different currencies")\n        return self.amount < other.amount\n    def __add__(self, other):\n        if self.currency != other.currency:\n            raise ValueError("different currencies")\n        return Money(self.amount + other.amount, self.currency)\n\nprices = [Money(650), Money(7.5), Money(45)]\nprint(sorted(prices), max(prices))\nprint(Money(10) + Money(5.25), Money(1) == Money(1.0))', run: 1 },
        { h: B('@property والـ attributes بتاعة الكلاس', '@property and class attributes'),
          p: B('`@property` بتخلي method تتقري كأنها attribute (`order.total` من غير أقواس) وبتتحسب كل مرة، ومعاها `@x.setter` تتحقق من القيمة قبل ما تتحفظ. والـ attribute اللي بيتكتب في جسم الكلاس (برّه __init__) مشترك بين كل الكائنات — مناسب للثوابت زي `VAT = 0.14`. و`_name` بشرطة اتفاق إنها «داخلية».', '`@property` makes a method read like an attribute (`order.total`, no brackets), computed each time, and `@x.setter` checks a value before storing it. An attribute written in the class body (outside __init__) is shared by all objects — right for constants like `VAT = 0.14`. A leading underscore `_name` is the convention for «internal».'),
          ex: 'class Order:\n    VAT = 0.14                       # shared by every order\n\n    def __init__(self, qty, price):\n        self.price = price\n        self.qty = qty               # goes through the setter below\n\n    @property\n    def qty(self):\n        return self._qty\n\n    @qty.setter\n    def qty(self, value):\n        if not isinstance(value, int) or value <= 0:\n            raise ValueError(f"qty must be a positive whole number, got {value!r}")\n        self._qty = value\n\n    @property\n    def total(self):\n        return round(self.qty * self.price * (1 + self.VAT), 2)\n\no = Order(3, 100)\nprint(o.total)\no.qty = 5\nprint(o.total, Order.VAT)\ntry:\n    o.qty = 0\nexcept ValueError as e:\n    print("rejected:", e)', run: 1 }
      ],
      practice: [
        B('ضيف `__repr__` لكل كلاساتك من إمبارح وشوف القوايم بقت مقروءة.', 'Add `__repr__` to all of yesterday’s classes and see lists become readable.'),
        B('خلّي `Product` يترتب بالسعر بـ `__lt__` وجرّب `sorted` و`min`.', 'Make `Product` sortable by price with `__lt__` and try `sorted` and `min`.'),
        B('حوّل `total()` لـ `@property` وشيل الأقواس من كل الاستخدامات.', 'Turn `total()` into a `@property` and remove the brackets everywhere it is used.'),
        B('اعمل setter بيرفض سعر سالب وجرّب تكسره.', 'Write a setter that refuses a negative price and try to break it.')
      ],
      code: [
        { u: B('كلاس نسبة مئوية', 'A percentage class'), p: 'class Percent:\n    def __init__(self, value):\n        if not 0 <= value <= 100:\n            raise ValueError("percent must be 0-100")\n        self.value = value\n    def __repr__(self):\n        return f"{self.value:g}%"\n    def of(self, amount):\n        return amount * self.value / 100\n    def __lt__(self, other):\n        return self.value < other.value\n\ndiscounts = [Percent(15), Percent(5), Percent(25)]\nprint(sorted(discounts), max(discounts).of(2000))', run: 1 }
      ],
      words: [
        { t: 'dunder method', m: B('method اسمها بين __ بتخلي الكائن يشتغل مع أدوات Python', 'a method named between __ that lets objects work with Python’s tools'), ex: '__repr__, __eq__, __len__' },
        { t: '__repr__', m: B('شكل الكائن الواضح للمبرمج', 'an object’s exact look for programmers'), ex: 'Money(1250.5, \'EGP\')' },
        { t: '__eq__', m: B('بتحدد امتى كائنين متساويين', 'decides when two objects are equal'), ex: 'a == b' },
        { t: 'operator overloading', m: B('تعريف + و< وغيرهم لكائناتك', 'defining +, < and others for your objects'), ex: 'Money(10) + Money(5)' },
        { t: 'property', m: B('method بتتقري كأنها attribute، ممكن بـ setter بيتحقق', 'a method read like an attribute, optionally with a validating setter'), ex: '@property def total(self):' },
        { t: 'class attribute', m: B('قيمة في جسم الكلاس مشتركة بين كل الكائنات', 'a value in the class body shared by all objects'), ex: 'VAT = 0.14' }
      ],
      read: [{ lib: 'Classes (tutorial)', what: B('اقرا 9.4 Random Remarks.', 'Read 9.4 Random Remarks.') }, { lib: 'Built-in Functions', what: B('اقرا property وrepr وisinstance.', 'Read property, repr and isinstance.') }],
      challenge: B('اعمل كلاس `Money` كامل: جمع وطرح وضرب في رقم، ومقارنة، ورفض العملات المختلفة، وتقريب للقرش بـ Decimal (أسبوع 2)، و`__str__` بفواصل — و10 assert بيختبروه.', 'Build a complete `Money` class: addition, subtraction, multiplying by a number, comparison, refusing mixed currencies, rounding to cents with Decimal (week 2), and a `__str__` with separators — plus 10 asserts testing it.'),
      quiz: [
        { q: B('عشان `sorted(products)` يشتغل لازم:', 'For `sorted(products)` to work you need:'), o: ['__lt__', '__len__', '__str__'], a: 0, why: B('sorted بتقارن بـ <.', 'sorted compares with <.') },
        { q: B('`@property def total(self)` بتتقري:', '`@property def total(self)` is read as:'), o: ['order.total', 'order.total()', 'order["total"]'], a: 0, why: B('من غير أقواس.', 'Without brackets.') },
        { q: B('attribute مكتوب في جسم الكلاس:', 'An attribute written in the class body:'), o: [B('مشترك بين كل الكائنات', 'is shared by all objects'), B('خاص بكائن واحد', 'belongs to one object'), B('خطأ', 'is an error')], a: 0, why: B('class attribute.', 'A class attribute.') }
      ] },

    { title: B('dataclasses وEnum', 'dataclasses and Enum'),
      goal: B('تكتب كلاسات بيانات في سطور قليلة بـ @dataclass (القيم الافتراضية والترتيب والثبات والتحويل لـ dict)، وتستخدم Enum للقيم المحدودة زي حالة الطلب.', 'Write data classes in a few lines with @dataclass (defaults, ordering, immutability and converting to a dict), and use Enum for limited values such as an order status.'),
      learn: [
        { h: B('@dataclass', '@dataclass'),
          p: B('أغلب كلاساتك «بيانات بأسماء». `@dataclass` بيكتبلك `__init__` و`__repr__` و`__eq__` لوحده من الحقول اللي بتكتبها بأنواعها. وتقدر تزوّد methods وproperties عادي. ده الشكل اللي هتستخدمه أغلب الوقت.', 'Most of your classes are «named data». `@dataclass` writes `__init__`, `__repr__` and `__eq__` for you from the fields you declare with their types. You can still add methods and properties. This is the form you will use most of the time.'),
          ex: 'from dataclasses import dataclass\n\n@dataclass\nclass Product:\n    sku: str\n    name: str\n    price: float\n    stock: int = 0\n\n    @property\n    def value(self) -> float:\n        return self.price * self.stock\n\np = Product("B-7", "Bag", 650, 4)\nprint(p)\nprint(p.value, p == Product("B-7", "Bag", 650, 4))', run: 1 },
        { h: B('field وorder وfrozen وasdict', 'field, order, frozen and asdict'),
          p: B('القايمة الافتراضية: `tags: list = field(default_factory=list)` (فاكر فخ القايمة الافتراضية أسبوع 6؟). `@dataclass(order=True)` بيرتّب بالحقول بالترتيب، و`frozen=True` بيمنع التعديل (ينفع يبقى مفتاح dict). و`asdict(obj)` بيحوّله dict جاهز لـ JSON.', 'A list default: `tags: list = field(default_factory=list)` (remember the mutable default trap of week 6?). `@dataclass(order=True)` sorts by the fields in order, and `frozen=True` forbids changes (so it can be a dict key). `asdict(obj)` turns it into a dict ready for JSON.'),
          ex: 'import json\nfrom dataclasses import dataclass, field, asdict\n\n@dataclass(order=True)\nclass Ticket:\n    priority: int\n    title: str = field(compare=False)\n    tags: list[str] = field(default_factory=list, compare=False)\n\n@dataclass(frozen=True)\nclass Point:\n    lat: float\n    lon: float\n\ntickets = [Ticket(2, "Refund"), Ticket(1, "Site down", ["urgent"]), Ticket(3, "Typo")]\nprint([t.title for t in sorted(tickets)])\nprint(json.dumps(asdict(tickets[1])))\ncairo = Point(30.04, 31.24)\nprint({cairo: "Cairo"}[Point(30.04, 31.24)])\ntry:\n    cairo.lat = 0\nexcept Exception as e:\n    print(type(e).__name__)', run: 1 },
        { h: B('Enum للقيم المحدودة', 'Enum for limited values'),
          p: B('حالة الطلب مش أي نص: «new» أو «paid» أو «shipped» أو «cancelled» بس. `class Status(Enum)` بيمنع الغلطات الإملائية (`"payed"`)، والمحرر بيكمّلك، و`Status("paid")` بيحوّل نص جاي من API (ويطلّع خطأ لو مش مسموح). و`StrEnum` بيخلي القيمة نص عادي في JSON.', 'An order status is not any text: only «new», «paid», «shipped» or «cancelled». `class Status(Enum)` prevents typos (`"payed"`), the editor completes it for you, and `Status("paid")` converts text from an API (raising an error when not allowed). `StrEnum` keeps the value a plain string in JSON.'),
          ex: 'from enum import StrEnum\n\nclass Status(StrEnum):\n    NEW = "new"\n    PAID = "paid"\n    SHIPPED = "shipped"\n    CANCELLED = "cancelled"\n\nNEXT = {Status.NEW: {Status.PAID, Status.CANCELLED}, Status.PAID: {Status.SHIPPED, Status.CANCELLED}}\n\ndef move(current: Status, new: Status) -> Status:\n    if new not in NEXT.get(current, set()):\n        raise ValueError(f"cannot go from {current} to {new}")\n    return new\n\ns = Status("new")\ns = move(s, Status.PAID)\nprint(s, s == "paid", [x.value for x in Status])\ntry:\n    Status("payed")\nexcept ValueError as e:\n    print(e)\ntry:\n    move(Status.SHIPPED, Status.NEW)\nexcept ValueError as e:\n    print(e)', run: 1 }
      ],
      practice: [
        B('حوّل `Product` و`Customer` لـ dataclasses وشوف قد إيه الكود قصر.', 'Turn `Product` and `Customer` into dataclasses and see how much shorter the code gets.'),
        B('اعمل dataclass فيه قايمة tags بـ default_factory، واتأكد إن الكائنات مش بتتشارك القايمة.', 'Make a dataclass with a tags list using default_factory and check objects do not share the list.'),
        B('حوّل قايمة dataclasses لـ JSON بـ asdict وارجع اقراها.', 'Turn a list of dataclasses into JSON with asdict and read it back.'),
        B('اعمل Enum لحالات الطلب وحوّل 5 نصوص (منهم واحد غلط) ليه.', 'Make an Enum for order states and convert 5 strings (one invalid) to it.')
      ],
      code: [
        { u: B('من dict لـ dataclass بأمان', 'From a dict to a dataclass safely'), p: 'from dataclasses import dataclass, fields\n\n@dataclass\nclass Customer:\n    name: str\n    email: str\n    city: str = "Cairo"\n\n    @classmethod\n    def from_dict(cls, d: dict) -> "Customer":\n        known = {f.name for f in fields(cls)}\n        return cls(**{k: v for k, v in d.items() if k in known})\n\nprint(Customer.from_dict({"name": "Huda", "email": "huda@x.com", "phone": "010", "id": 7}))', run: 1 }
      ],
      words: [
        { t: 'dataclass', m: B('كلاس بيانات بيتكتبله __init__ و__repr__ لوحده', 'a data class whose __init__ and __repr__ are written for you'), ex: '@dataclass class Product:' },
        { t: 'default_factory', m: B('دالة بتعمل قيمة افتراضية جديدة لكل كائن', 'a function making a fresh default for each object'), ex: 'field(default_factory=list)' },
        { t: 'frozen dataclass', m: B('dataclass مينفعش يتعدّل بعد ما يتعمل', 'a dataclass that cannot change once created'), ex: '@dataclass(frozen=True)' },
        { t: 'asdict', m: B('بتحوّل dataclass لـ dict', 'turns a dataclass into a dict'), ex: 'json.dumps(asdict(p))' },
        { t: 'Enum', m: B('نوع ليه مجموعة قيم محدودة بأسماء', 'a type with a limited set of named values'), ex: 'class Status(Enum)' },
        { t: 'StrEnum', m: B('Enum قيمه نصوص بتتعامل كنص عادي', 'an Enum whose values are strings that act as plain text'), ex: 'Status.PAID == "paid"' },
        { t: 'state transition', m: B('الانتقال المسموح من حالة لحالة', 'an allowed move from one state to another'), ex: 'new → paid → shipped' }
      ],
      read: ['lib:dataclasses', { lib: 'The Python Standard Library', what: B('افتح صفحة enum واقرا أول جزء وStrEnum.', 'Open the enum page and read the first part and StrEnum.') }],
      challenge: B('اعمل `models.py` لمشروع الفواتير: `Customer` و`LineItem` و`Order` (dataclasses) و`Status` (StrEnum)، و`Order.total` وأي حالة مش مسموحة تطلّع خطأ، و`Order.from_dict` بيقرا من JSON أسبوع 5.', 'Write `models.py` for the invoicing project: `Customer`, `LineItem` and `Order` (dataclasses) and `Status` (StrEnum), with `Order.total`, errors on forbidden status changes, and `Order.from_dict` reading the week 5 JSON.'),
      quiz: [
        { q: B('`@dataclass` بيكتبلك لوحده:', '`@dataclass` writes for you:'), o: [B('__init__ و__repr__ و__eq__', '__init__, __repr__ and __eq__'), B('قاعدة بيانات', 'a database'), B('اختبارات', 'tests')], a: 0, why: B('من الحقول.', 'From the fields.') },
        { q: B('قيمة افتراضية لقايمة في dataclass:', 'A list default in a dataclass:'), o: ['field(default_factory=list)', 'tags: list = []', 'tags = list'], a: 0, why: B('= [] ممنوعة (القايمة هتتشارك).', '= [] is refused (the list would be shared).') },
        { q: B('ميزة Enum لحالة الطلب:', 'The benefit of an Enum for an order status:'), o: [B('بيمنع القيم الغلط والأخطاء الإملائية', 'it prevents invalid values and typos'), B('أسرع في الطباعة', 'faster printing'), B('بيحفظ في قاعدة بيانات', 'it saves to a database')], a: 0, why: B('قيم محدودة.', 'Limited values.') }
      ] },

    { title: B('الوراثة والتركيب', 'Inheritance and composition'),
      goal: B('تعمل كلاس أساسي وكلاسات بتورث منه وتغيّر سلوكه (super والـ override)، وتستخدم polymorphism (نفس الواجهة لحاجات مختلفة)، وتعرف امتى التركيب أحسن من الوراثة.', 'Create a base class and subclasses that inherit and change its behaviour (super and overriding), use polymorphism (one interface for different things), and know when composition beats inheritance.'),
      learn: [
        { h: B('الوراثة وsuper', 'Inheritance and super'),
          p: B('`class TelegramNotifier(Notifier):` بياخد كل حاجة من `Notifier` ويغيّر اللي محتاجه (override). `super().__init__(...)` بتنادي نسخة الأب عشان متكررش كودها. استخدم الوراثة لما يكون «X هو نوع من Y» فعلًا.', '`class TelegramNotifier(Notifier):` takes everything from `Notifier` and changes what it needs (overriding). `super().__init__(...)` calls the parent’s version so you do not repeat its code. Use inheritance when «X is a kind of Y» is really true.'),
          ex: 'class Notifier:\n    def __init__(self, name):\n        self.name = name\n        self.sent = 0\n\n    def format(self, text):\n        return f"[{self.name}] {text}"\n\n    def send(self, text):\n        raise NotImplementedError("each notifier sends its own way")\n\nclass ConsoleNotifier(Notifier):\n    def send(self, text):\n        print(self.format(text))\n        self.sent += 1\n\nclass LoudNotifier(ConsoleNotifier):\n    def format(self, text):\n        return super().format(text).upper() + " !!!"\n\nfor n in [ConsoleNotifier("ops"), LoudNotifier("alarm")]:\n    n.send("disk almost full")\nprint(isinstance(LoudNotifier("x"), Notifier))', run: 1 },
        { h: B('polymorphism وABC', 'Polymorphism and ABC'),
          p: B('لو كل الـ notifiers ليهم `send(text)`، الكود اللي بيستخدمهم ميهمهوش أنهي نوع: `for n in notifiers: n.send(msg)` — ده polymorphism. `ABC` و`@abstractmethod` بيجبروا أي كلاس وارث إنه يكتب `send`، وإلا ميتعملش منه كائن أصلًا (بدل ما يقع بعدين).', 'If every notifier has `send(text)`, the code using them does not care which kind: `for n in notifiers: n.send(msg)` — that is polymorphism. `ABC` with `@abstractmethod` forces every subclass to implement `send`, or it cannot be instantiated at all (instead of failing later).'),
          ex: 'from abc import ABC, abstractmethod\n\nclass Notifier(ABC):\n    @abstractmethod\n    def send(self, text: str) -> None: ...\n\nclass FileNotifier(Notifier):\n    def __init__(self):\n        self.lines = []\n    def send(self, text):\n        self.lines.append(text)\n\nclass PrintNotifier(Notifier):\n    def send(self, text):\n        print("PRINT:", text)\n\nclass Broken(Notifier):\n    pass\n\nfile_n = FileNotifier()\nfor n in [file_n, PrintNotifier()]:\n    n.send("report ready")\nprint(file_n.lines)\ntry:\n    Broken()\nexcept TypeError as e:\n    print("TypeError:", e)', run: 1 },
        { h: B('التركيب أحسن غالبًا', 'Composition is usually better'),
          p: B('بدل ما `Order` يورث من `list`، خليه **فيه** قايمة lines. بدل ما `ReportBot` يورث من `EmailSender`، خليه **فيه** notifier تبعته وقت ما تعمله. التركيب بيخلي القطع تتبدّل بسهولة (Telegram بدل Email، أو notifier وهمي في الاختبارات). القاعدة: «فيه» → تركيب، «هو نوع من» → وراثة.', 'Instead of `Order` inheriting from `list`, give it a list of lines. Instead of `ReportBot` inheriting from `EmailSender`, give it a notifier you pass in when you create it. Composition lets parts be swapped easily (Telegram instead of email, or a fake notifier in tests). The rule: «has a» → composition, «is a kind of» → inheritance.'),
          ex: 'class MemoryNotifier:\n    def __init__(self):\n        self.messages = []\n    def send(self, text):\n        self.messages.append(text)\n\nclass ReportBot:\n    def __init__(self, notifier, threshold=1000):\n        self.notifier = notifier          # composition: the bot HAS a notifier\n        self.threshold = threshold\n\n    def check(self, sales: dict):\n        for city, amount in sales.items():\n            if amount < self.threshold:\n                self.notifier.send(f"low sales in {city}: {amount}")\n\nfake = MemoryNotifier()                    # in tests, swap in a fake\nReportBot(fake).check({"Cairo": 5200, "Aswan": 340, "Luxor": 120})\nprint(fake.messages)', run: 1 }
      ],
      practice: [
        B('اعمل `Notifier` (ABC) وتحته `ConsoleNotifier` و`FileNotifier` و`TelegramNotifier` (اللي بيستخدم دالة أسبوع 13).', 'Write a `Notifier` ABC with `ConsoleNotifier`, `FileNotifier` and `TelegramNotifier` (using the week 13 function) below it.'),
        B('اعمل `MultiNotifier` فيه قايمة notifiers وبيبعت لكلهم (تركيب).', 'Write a `MultiNotifier` holding a list of notifiers and sending to all of them (composition).'),
        B('جرّب تعمل كائن من كلاس وارث ناسي `send` وشوف الخطأ.', 'Try instantiating a subclass that forgot `send` and see the error.'),
        B('اكتب جملة لكل علاقة في مشروعك: «فيه» ولا «هو نوع من»؟', 'Write a sentence for each relation in your project: «has a» or «is a kind of»?')
      ],
      code: [
        { u: B('Notifier بيبعت لأكتر من مكان', 'A notifier sending to several places'), p: 'class MultiNotifier:\n    def __init__(self, *notifiers):\n        self.notifiers = list(notifiers)\n\n    def send(self, text):\n        failures = []\n        for n in self.notifiers:\n            try:\n                n.send(text)\n            except Exception as e:          # one broken channel must not stop the others\n                failures.append((type(n).__name__, str(e)))\n        return failures\n\nclass Ok:\n    def send(self, text): print("ok:", text)\nclass Down:\n    def send(self, text): raise ConnectionError("telegram down")\n\nprint(MultiNotifier(Ok(), Down(), Ok()).send("backup finished"))', run: 1 }
      ],
      words: [
        { t: 'inheritance', m: B('كلاس بياخد attributes وmethods من كلاس أب', 'a class taking attributes and methods from a parent class'), ex: 'class Email(Notifier):' },
        { t: 'super()', m: B('بتنادي نسخة الأب من method', 'calls the parent’s version of a method'), ex: 'super().__init__(name)' },
        { t: 'method override', m: B('كلاس وارث بيكتب نسخته من method الأب', 'a subclass writing its own version of a parent method'), ex: 'def send(self, text): ...' },
        { t: 'polymorphism', m: B('أنواع مختلفة بنفس الواجهة بتتستخدم بنفس الكود', 'different types with one interface used by the same code'), ex: 'for n in notifiers: n.send(msg)' },
        { t: 'abstract base class', m: B('كلاس بيحدد methods لازم الوارث يكتبها (ABC)', 'a class declaring methods subclasses must implement (ABC)'), ex: '@abstractmethod def send' },
        { t: 'composition', m: B('كائن فيه كائنات تانية بدل ما يورث منها', 'an object holding other objects instead of inheriting from them'), ex: 'self.notifier = notifier' }
      ],
      read: [{ lib: 'Classes (tutorial)', what: B('اقرا 9.5 Inheritance.', 'Read 9.5 Inheritance.') }, { lib: 'Beyond the Basic Stuff with Python', what: B('الفصول عن OOP والوراثة.', 'The chapters on OOP and inheritance.') }],
      challenge: B('اعمل `exporters.py`: `Exporter` (ABC) بـ `export(rows, path)` وتحته `CsvExporter` و`JsonExporter` و`ExcelExporter` (أسبوع 11)، ودالة `export_all(rows, exporters)` بتستخدمهم كلهم من غير ما تعرف نوعهم.', 'Write `exporters.py`: an `Exporter` ABC with `export(rows, path)` and below it `CsvExporter`, `JsonExporter` and `ExcelExporter` (week 11), plus `export_all(rows, exporters)` using them all without knowing their types.'),
      quiz: [
        { q: B('`super().__init__(name)` بتعمل:', '`super().__init__(name)`:'), o: [B('تنادي __init__ بتاع الأب', 'calls the parent’s __init__'), B('تعمل كلاس جديد', 'makes a new class'), B('تمسح الكائن', 'deletes the object')], a: 0, why: B('عشان متكررش كود الأب.', 'So you do not repeat the parent’s code.') },
        { q: B('«التقرير فيه notifier» علاقة:', '«The report has a notifier» is:'), o: [B('تركيب', 'composition'), B('وراثة', 'inheritance'), B('ولا حاجة', 'neither')], a: 0, why: B('«فيه».', '«has a».') },
        { q: B('كلاس وارث من ABC ونسي abstractmethod:', 'A subclass of an ABC that forgot an abstractmethod:'), o: [B('مينفعش يتعمل منه كائن (TypeError)', 'cannot be instantiated (TypeError)'), B('بيشتغل عادي', 'works fine'), B('بيقع وقت الاستخدام بس', 'fails only when used')], a: 0, why: B('ABC بيمنعه بدري.', 'The ABC stops it early.') }
      ] },

    { title: B('امتى كلاس؟ وclassmethod وcontext managers', 'When a class? classmethod and context managers'),
      goal: B('تقرر بين كلاس ودوال، وتكتب constructors بديلة بـ @classmethod، وstaticmethod، وكلاس API client بـ Session، وكلاسك يشتغل مع with.', 'Decide between a class and functions, write alternative constructors with @classmethod, use staticmethod, build an API client class around a Session, and make your class work with with.'),
      learn: [
        { h: B('كلاس ولا دوال؟', 'A class or functions?'),
          p: B('**دوال** لو الشغل «حوّل ده لده» من غير حالة محفوظة (تنضيف نص، حساب ضريبة). **كلاس** لو فيه بيانات بتعيش وبتتغير مع الوقت وأفعال عليها (سلة، حساب، اتصال بـ API فيه token وsession)، أو لو عندك أنواع كتير بنفس الواجهة. متعملش كلاس فيه method واحدة غير __init__ — ده غالبًا دالة.', '**Functions** when the job is «turn this into that» with no saved state (cleaning text, computing VAT). **A class** when data lives and changes over time with actions on it (a basket, an account, an API connection holding a token and a session), or when you have many kinds sharing one interface. Do not write a class with one method besides __init__ — that is usually a function.'),
          ex: '# a function is enough:\ndef vat(amount, rate=0.14):\n    return round(amount * rate, 2)\n\n# a class earns its place: state that changes, several actions on it\nclass RateLimiter:\n    def __init__(self, per_minute):\n        self.per_minute = per_minute\n        self.calls = []\n    def allow(self, now):\n        self.calls = [t for t in self.calls if now - t < 60]\n        if len(self.calls) < self.per_minute:\n            self.calls.append(now)\n            return True\n        return False\n\nlimiter = RateLimiter(3)\nprint(vat(1000), [limiter.allow(t) for t in [0, 1, 2, 3, 61]])', run: 1 },
        { h: B('@classmethod و@staticmethod', '@classmethod and @staticmethod'),
          p: B('`@classmethod` بتاخد الكلاس نفسه (`cls`) بدل الكائن — أشهر استخدام: constructors بديلة زي `Order.from_row(row)` و`Customer.from_json(text)`. `@staticmethod` دالة عادية متعلقة بالكلاس ومحتاجتش لا self ولا cls (زي `Order.parse_date`).', '`@classmethod` receives the class itself (`cls`) instead of an object — its best-known use: alternative constructors like `Order.from_row(row)` and `Customer.from_json(text)`. `@staticmethod` is a plain function that belongs with the class and needs neither self nor cls (like `Order.parse_date`).'),
          ex: 'import json\nfrom dataclasses import dataclass\nfrom datetime import date\n\n@dataclass\nclass Order:\n    id: int\n    customer: str\n    total: float\n    day: date\n\n    @staticmethod\n    def parse_date(text: str) -> date:\n        return date.fromisoformat(text.strip())\n\n    @classmethod\n    def from_row(cls, row: list[str]) -> "Order":\n        return cls(int(row[0]), row[1].strip(), float(row[2].replace(",", "")), cls.parse_date(row[3]))\n\n    @classmethod\n    def from_json(cls, text: str) -> "Order":\n        d = json.loads(text)\n        return cls(d["id"], d["customer"], float(d["total"]), cls.parse_date(d["date"]))\n\nprint(Order.from_row(["7", " Sara ", "1,200.50", "2026-10-01"]))\nprint(Order.from_json(\'{"id": 8, "customer": "Omar", "total": "450", "date": "2026-10-02"}\'))', run: 1 },
        { h: B('كلاس API client وwith', 'An API client class and with'),
          p: B('كلاس بيلف API: بيعمل Session مرة واحدة بالـ headers والـ timeout، وmethods بأسماء الشغل (`get_users()` بدل URLs في كل حتة). ولو فيه حاجة لازم تتقفل، اكتب `__enter__` و`__exit__` عشان يتستخدم بـ `with` ويقفل لوحده حتى لو حصل خطأ.', 'A class wrapping an API: it creates the Session once with headers and a timeout, and offers methods named after the work (`get_users()` instead of URLs everywhere). If something must be closed, write `__enter__` and `__exit__` so it works with `with` and closes itself even after an error.'),
          ex: 'class ShopClient:\n    def __init__(self, base_url, token, timeout=15):\n        import requests\n        self.base_url = base_url.rstrip("/")\n        self.timeout = timeout\n        self.session = requests.Session()\n        self.session.headers.update({"Authorization": f"Bearer {token}", "User-Agent": "shop-bot/1.0"})\n\n    def _get(self, path, **params):\n        r = self.session.get(f"{self.base_url}{path}", params=params, timeout=self.timeout)\n        r.raise_for_status()\n        return r.json()\n\n    def orders(self, status="paid"):\n        return self._get("/v1/orders", status=status)\n\n    def close(self):\n        self.session.close()\n\n    def __enter__(self):\n        return self\n\n    def __exit__(self, exc_type, exc, tb):\n        self.close()\n        return False          # do not hide errors\n\n# with ShopClient("https://api.shop.example.com", os.environ["SHOP_TOKEN"]) as shop:\n#     for o in shop.orders(): ...' }
      ],
      practice: [
        B('راجع 3 كلاسات كتبتها الأسبوع ده: أنهي واحد المفروض يبقى دالة؟', 'Review 3 classes you wrote this week: which should have been a function?'),
        B('زوّد `from_row` و`from_dict` لـ dataclass بتاعك.', 'Add `from_row` and `from_dict` to one of your dataclasses.'),
        B('حوّل `api_client.py` (أسبوع 13) لكلاس بـ Session وmethods بأسماء الشغل.', 'Turn `api_client.py` (week 13) into a class with a Session and work-named methods.'),
        B('خلّي كلاس بيفتح ملف لوج يشتغل مع with ويقفله لوحده.', 'Make a class that opens a log file work with with and close it by itself.')
      ],
      code: [
        { u: B('كلاس بيشتغل مع with', 'A class that works with with'), p: 'class Timer:\n    import time as _time\n    def __enter__(self):\n        self.start = self._time.perf_counter()\n        return self\n    def __exit__(self, *exc):\n        self.seconds = self._time.perf_counter() - self.start\n        print(f"took {self.seconds:.3f}s")\n        return False\n\nwith Timer() as t:\n    total = sum(i * i for i in range(200_000))\nprint(total, round(t.seconds, 3) >= 0)', run: 1 }
      ],
      words: [
        { t: 'classmethod', m: B('method بتاخد الكلاس (cls)، غالبًا constructor بديل', 'a method receiving the class (cls), often an alternative constructor'), ex: 'Order.from_row(row)' },
        { t: 'staticmethod', m: B('دالة عادية جوه الكلاس من غير self ولا cls', 'a plain function inside a class, with no self or cls'), ex: 'Order.parse_date(text)' },
        { t: 'alternative constructor', m: B('طريقة تانية تعمل بيها كائن من شكل بيانات مختلف', 'another way to build an object from a different data shape'), ex: 'from_json, from_row' },
        { t: 'API client', m: B('كلاس بيلف API في methods سهلة', 'a class wrapping an API in easy methods'), ex: 'shop.orders(status="paid")' },
        { t: '__enter__/__exit__', m: B('methods بتخلي الكائن يشتغل مع with', 'methods that let an object work with with'), ex: 'with ShopClient(...) as shop:' },
        { t: 'state', m: B('البيانات اللي الكائن فاكرها وبتتغير مع الوقت', 'the data an object remembers that changes over time'), ex: 'a basket’s lines' }
      ],
      read: [{ lib: 'Built-in Functions', what: B('اقرا classmethod وstaticmethod.', 'Read classmethod and staticmethod.') }, { lib: 'Python HOWTOs', what: B('(اختياري) Descriptor HowTo Guide: الجزء الأول بس.', '(optional) Descriptor HowTo Guide: just the first part.') }],
      challenge: B('اعمل كلاس `JsonStore` بيحفظ dict في ملف JSON: `get` و`set` و`delete`، وبيقرا الملف أول مرة بس، وبيكتب بأمان (يكتب ملف مؤقت ويغيّر اسمه)، ويشتغل مع with ويحفظ في `__exit__` — واستخدمه في مراقب الأسعار بدل الملفات المتفرقة.', 'Write a `JsonStore` class keeping a dict in a JSON file: `get`, `set` and `delete`, reading the file only once, writing safely (a temp file then a rename), working with with and saving in `__exit__` — and use it in the price watcher instead of scattered files.'),
      quiz: [
        { q: B('`Order.from_row(row)` مثال على:', '`Order.from_row(row)` is an example of:'), o: [B('classmethod كـ constructor بديل', 'a classmethod as an alternative constructor'), B('staticmethod', 'a staticmethod'), B('property', 'a property')], a: 0, why: B('بيرجّع cls(...).', 'It returns cls(...).') },
        { q: B('حساب الضريبة من مبلغ، الأنسب:', 'Computing VAT from an amount is best as:'), o: [B('دالة', 'a function'), B('كلاس فيه method واحدة', 'a class with one method'), B('Enum', 'an Enum')], a: 0, why: B('مفيش حالة محفوظة.', 'There is no saved state.') },
        { q: B('`__exit__` بيتنفّذ:', '`__exit__` runs:'), o: [B('في آخر with حتى لو حصل خطأ', 'at the end of with, even after an error'), B('لو مفيش خطأ بس', 'only when there was no error'), B('أول with', 'at the start of with')], a: 0, why: B('زي finally.', 'Like finally.') }
      ] },

    { title: B('مراجعة ومشروع واختبار الأسبوع', 'Review, project and weekly test'),
      goal: B('تعيد بناء نظام الفواتير بكلاسات نضيفة قابلة للاختبار، وتعدّي الاختبار.', 'Rebuild the invoicing system with clean, testable classes, and pass the test.'),
      review: [
        B('class و__init__ وself والـ methods والكائنات المستقلة.', 'class, __init__, self, methods and independent objects.'),
        B('__repr__ و__eq__ و__lt__ و__add__ و@property والـ class attributes.', '__repr__, __eq__, __lt__, __add__, @property and class attributes.'),
        B('@dataclass وfield وfrozen وorder وasdict، وEnum وStrEnum.', '@dataclass, field, frozen, order and asdict; Enum and StrEnum.'),
        B('الوراثة وsuper والـ override وABC وpolymorphism، والتركيب أحسن غالبًا.', 'Inheritance, super, overriding, ABC and polymorphism — and composition is usually better.'),
        B('امتى كلاس، وclassmethod وstaticmethod، وكلاس API client، و__enter__/__exit__.', 'When to use a class, classmethod and staticmethod, an API client class, and __enter__/__exit__.')
      ],
      project: B('**نظام الفواتير بالكلاسات** (`invoicer` من أسبوع 12): `models.py` (dataclasses: Customer وLineItem وOrder بـ total كـ property، وStatus StrEnum بانتقالات مسموحة، وfrom_dict/from_row)، و`money.py` (كلاس Money بـ Decimal)، و`renderers.py` (Renderer ABC وتحته PdfRenderer وHtmlRenderer)، و`notifiers.py` (Notifier ABC: Email وTelegram وMemory للاختبارات + MultiNotifier)، و`app.py` بيركّبهم مع بعض (تركيب: InvoiceApp فيه loader وrenderer وnotifier). اكتب 20 test على models وmoney والـ app باستخدام MemoryNotifier (من غير شبكة). البرنامج من برّه يشتغل زي الأول.', '**The invoicing system with classes** (`invoicer` from week 12): `models.py` (dataclasses: Customer, LineItem and Order with total as a property, a Status StrEnum with allowed transitions, and from_dict/from_row), `money.py` (a Money class with Decimal), `renderers.py` (a Renderer ABC with PdfRenderer and HtmlRenderer), `notifiers.py` (a Notifier ABC: Email, Telegram and Memory for tests, plus MultiNotifier), and `app.py` assembling them (composition: InvoiceApp has a loader, a renderer and a notifier). Write 20 tests on models, money and the app using MemoryNotifier (no network). From the outside the program behaves as before.'),
      test: [
        { q: B('أول معامل في أي method عادية:', 'The first parameter of a normal method:'), o: ['self', 'cls', 'this'], a: 0, why: B('الكائن.', 'The object.') },
        { q: B('`class B(A):` معناها:', '`class B(A):` means:'), o: [B('B بيورث من A', 'B inherits from A'), B('A بيورث من B', 'A inherits from B'), B('B فيه A', 'B contains an A')], a: 0, why: B('وراثة.', 'Inheritance.') },
        { q: B('`print(obj)` بيستخدم:', '`print(obj)` uses:'), o: [B('__str__ (ولو مش موجودة __repr__)', '__str__ (falling back to __repr__)'), '__init__', '__eq__'], a: 0, why: B('str ثم repr.', 'str, then repr.') },
        { q: B('عشان `obj1 == obj2` تقارن بالبيانات:', 'For `obj1 == obj2` to compare data:'), o: ['__eq__', '__lt__', B('__hash__ بس', '__hash__ only')], a: 0, why: B('dataclass بيكتبها لوحده.', 'A dataclass writes it for you.') },
        { q: B('@property فايدتها:', 'What @property is for:'), o: [B('method تتقري كـ attribute، وممكن تتحقق بـ setter', 'a method read as an attribute, optionally validated by a setter'), B('تخلي الكلاس أسرع', 'making the class faster'), B('تمنع الوراثة', 'preventing inheritance')], a: 0, why: B('حساب وتحقق.', 'Computing and validating.') },
        { q: B('`@dataclass(frozen=True)`:', '`@dataclass(frozen=True)`:'), o: [B('الكائن مبيتعدلش', 'the object cannot change'), B('أسرع', 'faster'), B('بيتحفظ لوحده', 'saves itself')], a: 0, why: B('immutable.', 'Immutable.') },
        { q: B('`Status("payed")` لـ StrEnum مفيهوش payed:', '`Status("payed")` on a StrEnum without payed:'), o: ['ValueError', B('بيرجّع None', 'returns None'), B('بيضيفها', 'adds it')], a: 0, why: B('قيم محدودة.', 'Limited values.') },
        { q: B('`super().send(text)` جوه override:', '`super().send(text)` inside an override:'), o: [B('بتنادي نسخة الأب', 'calls the parent’s version'), B('بتنادي نفسها للأبد', 'calls itself forever'), B('خطأ', 'an error')], a: 0, why: B('تكمّل على شغل الأب.', 'It builds on the parent’s work.') },
        { q: B('MemoryNotifier في الاختبارات فايدته:', 'A MemoryNotifier in tests:'), o: [B('تختبر من غير ما تبعت رسايل حقيقية', 'lets you test without sending real messages'), B('أسرع في الإنتاج', 'is faster in production'), B('بيحفظ الباسوردات', 'stores passwords')], a: 0, why: B('تركيب يسهّل التبديل.', 'Composition makes swapping easy.') },
        { q: B('`@classmethod def from_json(cls, text)` بترجّع غالبًا:', '`@classmethod def from_json(cls, text)` usually returns:'), o: ['cls(...)', 'self', 'None'], a: 0, why: B('كائن جديد.', 'A new object.') },
        { q: B('كلاس مفيهوش غير __init__ وmethod واحدة ومن غير حالة:', 'A class with only __init__, one method and no state:'), o: [B('غالبًا يبقى دالة', 'should usually be a function'), B('ممتاز كده', 'is perfect'), B('لازم Enum', 'needs an Enum')], a: 0, why: B('بساطة.', 'Simplicity.') },
        { q: B('`with Client() as c:` محتاج في الكلاس:', '`with Client() as c:` needs in the class:'), o: [B('__enter__ و__exit__', '__enter__ and __exit__'), B('__init__ بس', 'only __init__'), '__repr__'], a: 0, why: B('context manager protocol.', 'The context manager protocol.') }
      ] }
  ]
};
