// Python week 18 — SQL and sqlite3.
const B = (ar, en) => ({ ar, en });
const SHOP = 'import sqlite3\ndb = sqlite3.connect(":memory:")\ndb.executescript("""\nCREATE TABLE customers (id INTEGER PRIMARY KEY, name TEXT NOT NULL, city TEXT);\nCREATE TABLE orders (id INTEGER PRIMARY KEY, customer_id INTEGER REFERENCES customers(id), day TEXT, total REAL, status TEXT);\nINSERT INTO customers VALUES (1,\'Sara\',\'Cairo\'),(2,\'Omar\',\'Giza\'),(3,\'Mona\',\'Cairo\'),(4,\'Hany\',\'Alexandria\');\nINSERT INTO orders VALUES (1,1,\'2026-09-02\',1200,\'paid\'),(2,2,\'2026-09-05\',450.5,\'paid\'),(3,1,\'2026-09-18\',3100,\'paid\'),(4,3,\'2026-09-20\',90,\'new\'),(5,2,\'2026-10-01\',980,\'cancelled\');\n""")\n';
module.exports = {
  level: B('متقدم', 'Advanced'),
  title: B('SQL وsqlite3', 'SQL and sqlite3'),
  goal: B('تخزّن بياناتك في قاعدة بيانات حقيقية بدل ملفات JSON: تكتب SQL (SELECT وWHERE وGROUP BY وJOIN)، وتستخدم sqlite3 من Python بأمان (parameters والـ transactions)، وتصمم جداول بمفاتيح وقيود وindexes، وتنقل بيانات من CSV للقاعدة والعكس — نفس المهارة اللي هتستخدمها مع Postgres في n8n.',
          'Store your data in a real database instead of JSON files: write SQL (SELECT, WHERE, GROUP BY and JOIN), use sqlite3 from Python safely (parameters and transactions), design tables with keys, constraints and indexes, and move data from CSV into the database and back — the same skill you use with Postgres in n8n.'),
  days: [
    { title: B('أول قاعدة بيانات وأول SELECT', 'A first database and a first SELECT'),
      goal: B('تفهم الجداول والصفوف والأعمدة، وتعمل قاعدة SQLite بـ Python، وتكتب CREATE وINSERT وSELECT بـ WHERE وORDER BY وLIMIT.', 'Understand tables, rows and columns, create a SQLite database from Python, and write CREATE, INSERT and SELECT with WHERE, ORDER BY and LIMIT.'),
      learn: [
        { h: B('ليه قاعدة بيانات؟', 'Why a database?'),
          p: B('ملف JSON كويس لحد مئات الصفوف، لكن مع آلاف الطلبات وأكتر من برنامج بيكتب في نفس الوقت محتاج قاعدة بيانات: بحث سريع، وقيود بتمنع البيانات الغلط، وعمليات كاملة يا تتم يا لأ. SQLite قاعدة كاملة في ملف واحد ومعاها Python من غير تثبيت (وبتشتغل هنا في الصفحة). نفس الـ SQL بيشتغل تقريبًا في Postgres وMySQL.', 'A JSON file is fine up to hundreds of rows, but with thousands of orders and several programs writing at once you need a database: fast search, constraints that block bad data, and operations that either fully happen or not at all. SQLite is a complete database in one file that ships with Python (and runs right here on the page). Nearly the same SQL works in Postgres and MySQL.'),
          ex: 'import sqlite3\ndb = sqlite3.connect(":memory:")      # or "shop.db" for a file on disk\ndb.execute("CREATE TABLE products (id INTEGER PRIMARY KEY, name TEXT, price REAL, stock INTEGER)")\ndb.execute("INSERT INTO products (name, price, stock) VALUES (\'Pen\', 7.5, 120)")\ndb.execute("INSERT INTO products (name, price, stock) VALUES (\'Bag\', 650, 4)")\ndb.execute("INSERT INTO products (name, price, stock) VALUES (\'Notebook\', 45, 0)")\nfor row in db.execute("SELECT id, name, price FROM products"):\n    print(row)', run: 1 },
        { h: B('SELECT بشروط وترتيب', 'SELECT with conditions and order'),
          p: B('`SELECT columns FROM table WHERE condition ORDER BY column DESC LIMIT n`. الشروط: `=` و`<>` و`>` و`BETWEEN` و`IN (...)` و`LIKE \'%Pro%\'` و`IS NULL`، وتجمعهم بـ AND وOR. النصوص بين علامات تنصيص مفردة في SQL. والـ SQL مش حساس للحروف في الكلمات (SELECT = select)، بس الأسهل تكتبها كابيتال.', '`SELECT columns FROM table WHERE condition ORDER BY column DESC LIMIT n`. Conditions: `=`, `<>`, `>`, `BETWEEN`, `IN (...)`, `LIKE \'%Pro%\'` and `IS NULL`, joined with AND and OR. Text goes in single quotes in SQL. SQL keywords ignore case (SELECT = select), but capitals are easier to read.'),
          ex: SHOP + 'print(db.execute("SELECT name, city FROM customers WHERE city = \'Cairo\' ORDER BY name").fetchall())\nprint(db.execute("SELECT id, total FROM orders WHERE status = \'paid\' AND total > 1000").fetchall())\nprint(db.execute("SELECT id, day FROM orders WHERE day BETWEEN \'2026-09-01\' AND \'2026-09-30\' ORDER BY total DESC LIMIT 2").fetchall())\nprint(db.execute("SELECT name FROM customers WHERE city IN (\'Giza\', \'Alexandria\')").fetchall())', run: 1 },
        { h: B('fetchone وfetchall وUPDATE وDELETE', 'fetchone, fetchall, UPDATE and DELETE'),
          p: B('`db.execute(sql)` بترجّع cursor: `fetchone()` صف واحد (أو None)، و`fetchall()` كلهم، أو تلف عليه على طول. `UPDATE table SET col = value WHERE ...` تعدّل، و`DELETE FROM table WHERE ...` تمسح — **متنساش WHERE** وإلا هتعدّل أو تمسح الجدول كله! جرّب الأول بـ SELECT بنفس الشرط.', '`db.execute(sql)` returns a cursor: `fetchone()` one row (or None), `fetchall()` all of them, or loop over it directly. `UPDATE table SET col = value WHERE ...` changes rows and `DELETE FROM table WHERE ...` removes them — **never forget WHERE** or you change or delete the whole table! Try the same condition with SELECT first.'),
          ex: SHOP + 'print(db.execute("SELECT COUNT(*) FROM orders WHERE status = \'new\'").fetchone())\ncur = db.execute("UPDATE orders SET status = \'paid\' WHERE id = 4")\nprint("updated rows:", cur.rowcount)\ncur = db.execute("DELETE FROM orders WHERE status = \'cancelled\'")\nprint("deleted rows:", cur.rowcount)\nprint(db.execute("SELECT id, status FROM orders").fetchall())', run: 1 }
      ],
      practice: [
        B('اعمل جدول `expenses` (id وday وcategory وamount وnote) وحط فيه 8 مصاريف بـ INSERT.', 'Create an `expenses` table (id, day, category, amount, note) and insert 8 expenses.'),
        B('اكتب 5 SELECT مختلفة: فئة معيّنة، فوق مبلغ، في أسبوع، أكبر 3، فيها كلمة في الملاحظة.', 'Write 5 different SELECTs: one category, above an amount, within a week, the top 3, a word in the note.'),
        B('اعمل UPDATE بشرط، وجرّب نفس الشرط بـ SELECT قبلها.', 'Run an UPDATE with a condition, trying the same condition with SELECT first.'),
        B('افتح `shop.db` (ملف) بأداة DB Browser for SQLite وشوف الجداول.', 'Open `shop.db` (a file) in DB Browser for SQLite and look at the tables.')
      ],
      code: [
        { u: B('قاعدة في ملف', 'A database in a file'), p: 'import sqlite3\nfrom pathlib import Path\n\npath = Path("shop.db")\nwith sqlite3.connect(path) as db:          # commits when the block ends without an error\n    db.execute("CREATE TABLE IF NOT EXISTS notes (id INTEGER PRIMARY KEY, body TEXT, created TEXT DEFAULT CURRENT_TIMESTAMP)")\n    db.execute("INSERT INTO notes (body) VALUES (\'first note\')")\nwith sqlite3.connect(path) as db:\n    print(db.execute("SELECT id, body, created FROM notes").fetchall())\nprint(path.stat().st_size, "bytes on disk")', run: 1 }
      ],
      words: [
        { t: 'database', m: B('مخزن بيانات منظم بيدعم البحث والقيود والعمليات الآمنة', 'an organised data store with search, constraints and safe operations'), ex: 'shop.db' },
        { t: 'SQL', m: B('اللغة اللي بتكلّم بيها قواعد البيانات', 'the language for talking to databases'), ex: 'SELECT name FROM customers' },
        { t: 'database table', m: B('جدول بأعمدة ثابتة وصفوف بيانات', 'a table with fixed columns and rows of data'), ex: 'CREATE TABLE orders (...)' },
        { t: 'SQLite', m: B('قاعدة بيانات كاملة في ملف واحد، جاية مع Python', 'a complete database in one file, shipped with Python'), ex: 'sqlite3.connect("shop.db")' },
        { t: 'database cursor', m: B('نتيجة استعلام بتلف عليها أو تجيب منها صفوف', 'a query result you loop over or fetch rows from'), ex: 'cur.fetchall()' },
        { t: 'WHERE clause', m: B('الشرط اللي بيختار الصفوف', 'the condition that picks rows'), ex: "WHERE status = 'paid'" },
        { t: 'rowcount', m: B('عدد الصفوف اللي اتأثرت بـ UPDATE أو DELETE', 'the number of rows an UPDATE or DELETE touched'), ex: 'cur.rowcount' }
      ],
      read: [{ lib: 'sqlite3 — DB-API interface', what: B('اقرا Tutorial كله.', 'Read the whole Tutorial.') }, { lib: 'SQLBolt', what: B('الدروس 1 لـ 4.', 'Lessons 1 to 4.') }],
      challenge: B('اعمل `products.db` فيه 15 منتج (اسم وفئة وسعر ومخزون)، واكتب سكربت بيطبع: المنتجات اللي خلصت، وأغلى 3 في كل فئة (3 استعلامات أو لوب)، وبعدين يزوّد سعر فئة معيّنة 10% بـ UPDATE واحد.', 'Create `products.db` with 15 products (name, category, price, stock) and write a script that prints the out-of-stock products and the 3 most expensive per category (3 queries or a loop), then raises one category’s prices by 10% with a single UPDATE.'),
      quiz: [
        { q: B('`DELETE FROM orders` من غير WHERE:', '`DELETE FROM orders` without WHERE:'), o: [B('بيمسح كل الطلبات', 'deletes every order'), B('بيطلّع خطأ', 'raises an error'), B('ميعملش حاجة', 'does nothing')], a: 0, why: B('جرّب بـ SELECT الأول دايمًا.', 'Always try with SELECT first.') },
        { q: B('النص في SQL بيتكتب بين:', 'Text in SQL goes between:'), o: [B('علامات تنصيص مفردة', 'single quotes'), B('أقواس', 'brackets'), B('backticks', 'backticks')], a: 0, why: B("'Cairo'.", "'Cairo'.") },
        { q: B('`fetchone()` لو مفيش صفوف:', '`fetchone()` when there are no rows:'), o: ['None', '[]', B('خطأ', 'an error')], a: 0, why: B('صف واحد أو None.', 'One row or None.') }
      ] },

    { title: B('Python وSQL بأمان', 'Python and SQL safely'),
      goal: B('تبعت قيم للـ SQL بالـ parameters (مش f-string) عشان تمنع SQL injection، وتستخدم executemany والـ transactions وcommit وrollback، وترجّع الصفوف كـ dicts.', 'Pass values to SQL with parameters (not f-strings) to prevent SQL injection, use executemany, transactions, commit and rollback, and get rows back as dicts.'),
      learn: [
        { h: B('الـ parameters وSQL injection', 'Parameters and SQL injection'),
          p: B('**عمرك ما تحط قيمة جاية من برّه جوه SQL بـ f-string.** اسم زي `x\' OR \'1\'=\'1` بيغيّر معنى الاستعلام ويجيب كل البيانات (أو يمسحها). اكتب `?` مكان كل قيمة وابعت القيم في tuple: `db.execute("... WHERE name = ?", (name,))`. sqlite3 هو اللي بيحطها بأمان.', '**Never put an outside value into SQL with an f-string.** A name like `x\' OR \'1\'=\'1` changes the query’s meaning and returns all the data (or deletes it). Write `?` for each value and pass the values in a tuple: `db.execute("... WHERE name = ?", (name,))`. sqlite3 inserts them safely.'),
          ex: SHOP + 'evil = "x\' OR \'1\'=\'1"\nunsafe = f"SELECT name FROM customers WHERE name = \'{evil}\'"\nprint("f-string:", db.execute(unsafe).fetchall())          # leaks every customer!\nsafe = db.execute("SELECT name FROM customers WHERE name = ?", (evil,)).fetchall()\nprint("parameter:", safe)                                  # nothing matches\nprint(db.execute("SELECT name FROM customers WHERE city = ? AND id > ?", ("Cairo", 1)).fetchall())', run: 1 },
        { h: B('executemany والـ transactions', 'executemany and transactions'),
          p: B('`executemany(sql, list_of_tuples)` بيدخّل آلاف الصفوف مرة واحدة (أسرع بكتير من لوب). والـ transaction: مجموعة عمليات يا تتم كلها يا ولا واحدة. `with db:` بيعمل commit لو الـ block خلص من غير خطأ، وrollback (يرجّع كله) لو حصل خطأ في النص — مهم جدًا في التحويلات والطلبات.', '`executemany(sql, list_of_tuples)` inserts thousands of rows in one go (much faster than a loop). A transaction is a group of operations that all happen or none do. `with db:` commits when the block ends without an error, and rolls back (undoes everything) when an error happens midway — vital for transfers and orders.'),
          ex: 'import sqlite3\ndb = sqlite3.connect(":memory:")\ndb.execute("CREATE TABLE accounts (name TEXT PRIMARY KEY, balance REAL CHECK (balance >= 0))")\ndb.executemany("INSERT INTO accounts VALUES (?, ?)", [("Sara", 500), ("Omar", 100)])\ndb.commit()\n\ndef transfer(src, dst, amount):\n    try:\n        with db:   # one transaction\n            db.execute("UPDATE accounts SET balance = balance + ? WHERE name = ?", (amount, dst))\n            db.execute("UPDATE accounts SET balance = balance - ? WHERE name = ?", (amount, src))\n        print("ok", src, "->", dst, amount)\n    except sqlite3.IntegrityError as e:\n        print("refused, rolled back:", e)\n\ntransfer("Sara", "Omar", 200)\ntransfer("Omar", "Sara", 900)        # would go negative: CHECK fails, nothing changes\nprint(db.execute("SELECT * FROM accounts").fetchall())', run: 1 },
        { h: B('صفوف كـ dicts', 'Rows as dicts'),
          p: B('افتراضيًا كل صف tuple. `db.row_factory = sqlite3.Row` بيخلي الصف تقراه بالاسم `row["name"]` وتحوّله `dict(row)` — جاهز لـ JSON والقوالب والـ dataclasses (أسبوع 17).', 'By default each row is a tuple. `db.row_factory = sqlite3.Row` lets you read a row by name, `row["name"]`, and turn it into `dict(row)` — ready for JSON, templates and dataclasses (week 17).'),
          ex: SHOP + 'import json\ndb.row_factory = sqlite3.Row\nrows = db.execute("SELECT id, name, city FROM customers WHERE city = ?", ("Cairo",)).fetchall()\nprint(rows[0]["name"], rows[0].keys())\nprint(json.dumps([dict(r) for r in rows], ensure_ascii=False))', run: 1 }
      ],
      practice: [
        B('جرّب الـ injection بنفسك في مثال الدرس، وبعدين صلّحه بـ `?`.', 'Try the injection yourself in the lesson’s example, then fix it with `?`.'),
        B('دخّل 1000 صف بلوب مرة وبـ executemany مرة وقيس الوقت.', 'Insert 1,000 rows with a loop and with executemany, and time both.'),
        B('اعمل transaction فيها 3 عمليات وخلي التالتة تفشل، واتأكد إن مفيش حاجة اتغيرت.', 'Run a transaction with 3 operations where the third fails, and check nothing changed.'),
        B('رجّع نتيجة استعلام كقايمة dicts وحوّلها JSON.', 'Return a query result as a list of dicts and turn it into JSON.')
      ],
      code: [
        { u: B('دوال قاعدة بيانات صغيرة', 'Small database helpers'), p: 'import sqlite3\n\ndef connect(path=":memory:") -> sqlite3.Connection:\n    db = sqlite3.connect(path)\n    db.row_factory = sqlite3.Row\n    db.execute("PRAGMA foreign_keys = ON")\n    return db\n\ndef query(db, sql, *params) -> list[dict]:\n    return [dict(r) for r in db.execute(sql, params)]\n\ndb = connect()\ndb.execute("CREATE TABLE t (id INTEGER PRIMARY KEY, name TEXT)")\nwith db:\n    db.executemany("INSERT INTO t (name) VALUES (?)", [("a",), ("b",), ("c",)])\nprint(query(db, "SELECT * FROM t WHERE id > ?", 1))', run: 1 }
      ],
      words: [
        { t: 'query parameter', m: B('مكان ? في SQL بتتحط فيه قيمة بأمان', 'a ? in SQL where a value is inserted safely'), ex: 'WHERE name = ?' },
        { t: 'SQL injection', m: B('ثغرة: قيمة من برّه بتغيّر معنى الاستعلام', 'a hole where an outside value changes the query’s meaning'), ex: "x' OR '1'='1" },
        { t: 'executemany', m: B('بينفّذ نفس الـ SQL على قايمة قيم', 'runs the same SQL over a list of values'), ex: 'db.executemany(sql, rows)' },
        { t: 'transaction', m: B('مجموعة عمليات يا تتم كلها يا ولا واحدة', 'a group of operations that all happen or none do'), ex: 'with db: ...' },
        { t: 'commit', m: B('تثبيت التغييرات في القاعدة', 'making changes permanent in the database'), ex: 'db.commit()' },
        { t: 'rollback', m: B('إلغاء تغييرات الـ transaction', 'undoing a transaction’s changes'), ex: 'an error inside with db: rolls back' },
        { t: 'row_factory', m: B('بيحدد شكل الصفوف الراجعة (زي sqlite3.Row)', 'sets the shape of returned rows (such as sqlite3.Row)'), ex: 'db.row_factory = sqlite3.Row' }
      ],
      read: [{ lib: 'sqlite3 — DB-API interface', what: B('اقرا How to use placeholders to bind values in SQL queries وTransaction control.', 'Read How to use placeholders to bind values and Transaction control.') }, { lib: 'SQLite: SQL As Understood By SQLite', what: B('افتح INSERT وUPDATE.', 'Open INSERT and UPDATE.') }],
      challenge: B('اعمل `orders_db.py` بدوال `add_order(db, customer_id, items)` اللي بتدخّل الطلب وسطوره في transaction واحدة (لو أي سطر غلط ولا حاجة تتحفظ)، و`order_total(db, order_id)` — كلها بـ parameters، و6 tests.', 'Write `orders_db.py` with `add_order(db, customer_id, items)`, inserting the order and its lines in one transaction (if any line is bad nothing is saved), and `order_total(db, order_id)` — all with parameters, plus 6 tests.'),
      quiz: [
        { q: B('الطريقة الآمنة تبعت اسم من المستخدم لـ SQL:', 'The safe way to send a user’s name to SQL:'), o: ['execute("... WHERE name = ?", (name,))', 'execute(f"... WHERE name = \'{name}\'")', 'execute("... WHERE name = " + name)'], a: 0, why: B('parameter.', 'A parameter.') },
        { q: B('`with db:` لو حصل خطأ جوه:', '`with db:` when an error happens inside:'), o: [B('rollback لكل اللي اتعمل في الـ block', 'rolls back everything in the block'), B('commit لنص الشغل', 'commits half the work'), B('بيتجاهل الخطأ', 'ignores the error')], a: 0, why: B('transaction.', 'A transaction.') },
        { q: B('`(name,)` ليه فيها فاصلة؟', 'Why does `(name,)` have a comma?'), o: [B('عشان تبقى tuple من عنصر واحد', 'to make a one-item tuple'), B('غلطة', 'it is a typo'), B('عشان العربي', 'for Arabic')], a: 0, why: B('أسبوع 4.', 'Week 4.') }
      ] },

    { title: B('التجميع والـ JOIN', 'Aggregates and JOIN'),
      goal: B('تلخّص بـ COUNT وSUM وAVG وGROUP BY وHAVING، وتربط جداول بـ JOIN وLEFT JOIN، وتكتب استعلامات بخطوات بـ WITH (CTE)، وتتعامل مع التواريخ في SQLite.', 'Summarise with COUNT, SUM, AVG, GROUP BY and HAVING, combine tables with JOIN and LEFT JOIN, write step-by-step queries with WITH (CTE), and handle dates in SQLite.'),
      learn: [
        { h: B('GROUP BY وHAVING', 'GROUP BY and HAVING'),
          p: B('`SELECT status, COUNT(*) AS n, SUM(total) FROM orders GROUP BY status` = نفس الـ grouping بتاع أسبوع 5 بس في سطر. `HAVING` شرط على النتيجة بعد التجميع (`HAVING SUM(total) > 1000`)، و`WHERE` شرط على الصفوف قبل التجميع. `ROUND(x, 2)` للتقريب.', '`SELECT status, COUNT(*) AS n, SUM(total) FROM orders GROUP BY status` = the week 5 grouping in one line. `HAVING` filters the result after grouping (`HAVING SUM(total) > 1000`), and `WHERE` filters rows before it. `ROUND(x, 2)` rounds.'),
          ex: SHOP + 'for row in db.execute("SELECT status, COUNT(*) AS n, ROUND(SUM(total), 2) AS revenue FROM orders GROUP BY status ORDER BY revenue DESC"):\n    print(row)\nprint(db.execute("SELECT customer_id, SUM(total) FROM orders WHERE status = \'paid\' GROUP BY customer_id HAVING SUM(total) > 1000").fetchall())\nprint(db.execute("SELECT ROUND(AVG(total), 2), MIN(total), MAX(total) FROM orders").fetchone())', run: 1 },
        { h: B('JOIN وLEFT JOIN', 'JOIN and LEFT JOIN'),
          p: B('البيانات متقسمة: الطلب فيه `customer_id` بس. `JOIN customers c ON c.id = o.customer_id` بيجيب اسم العميل جنب كل طلب. `JOIN` (inner) بيسيب الطلبات اللي ليها عميل بس، و`LEFT JOIN` بيسيب كل صفوف الجدول الشمال حتى لو مالهاش مقابل (مفيد عشان تلاقي «العملاء اللي معملوش طلبات» بـ `IS NULL`).', 'The data is split: an order holds only `customer_id`. `JOIN customers c ON c.id = o.customer_id` brings the customer’s name next to each order. `JOIN` (inner) keeps only orders with a customer, while `LEFT JOIN` keeps every row of the left table even without a match (handy to find «customers with no orders» using `IS NULL`).'),
          ex: SHOP + 'sql = """SELECT o.id, c.name, c.city, o.total FROM orders o\n         JOIN customers c ON c.id = o.customer_id WHERE o.status = \'paid\' ORDER BY o.total DESC"""\nfor row in db.execute(sql):\n    print(row)\nprint(db.execute("SELECT c.name FROM customers c LEFT JOIN orders o ON o.customer_id = c.id WHERE o.id IS NULL").fetchall())\nprint(db.execute("SELECT c.city, ROUND(SUM(o.total), 2) FROM orders o JOIN customers c ON c.id = o.customer_id WHERE o.status = \'paid\' GROUP BY c.city").fetchall())', run: 1 },
        { h: B('WITH والتواريخ', 'WITH and dates'),
          p: B('`WITH paid AS (SELECT ...) SELECT ... FROM paid` بيقسّم استعلام طويل لخطوات بأسماء — أوضح بكتير من استعلامات جوه بعض. والتواريخ في SQLite نصوص ISO (`2026-09-30`)، فبتتقارن وتترتب صح، و`strftime(\'%Y-%m\', day)` بيطلّع الشهر للتجميع، و`date(\'now\', \'-30 days\')` من 30 يوم.', '`WITH paid AS (SELECT ...) SELECT ... FROM paid` splits a long query into named steps — much clearer than queries nested in each other. Dates in SQLite are ISO strings (`2026-09-30`), so they compare and sort correctly; `strftime(\'%Y-%m\', day)` extracts the month for grouping, and `date(\'now\', \'-30 days\')` is 30 days ago.'),
          ex: SHOP + 'sql = """\nWITH paid AS (\n    SELECT customer_id, total, strftime(\'%Y-%m\', day) AS month FROM orders WHERE status = \'paid\'\n), per_customer AS (\n    SELECT customer_id, month, SUM(total) AS spent FROM paid GROUP BY customer_id, month\n)\nSELECT c.name, p.month, p.spent FROM per_customer p JOIN customers c ON c.id = p.customer_id ORDER BY p.spent DESC\n"""\nfor row in db.execute(sql):\n    print(row)\nprint(db.execute("SELECT date(\'2026-10-01\', \'-30 days\'), strftime(\'%W\', \'2026-10-01\')").fetchone())', run: 1 }
      ],
      practice: [
        B('اطبع لكل فئة في `expenses`: العدد والمجموع والمتوسط، مترتبين بالمجموع.', 'Print for each category in `expenses`: the count, total and average, sorted by total.'),
        B('اعمل جدول `categories` واربطه بالمصاريف بـ JOIN.', 'Create a `categories` table and join it to the expenses.'),
        B('لاقي الفئات اللي مفيهاش مصاريف الشهر ده بـ LEFT JOIN.', 'Find the categories with no expenses this month using LEFT JOIN.'),
        B('اكتب تقرير شهري (الشهر والمجموع) بـ strftime وGROUP BY.', 'Write a monthly report (month and total) with strftime and GROUP BY.')
      ],
      code: [
        { u: B('تقرير بالشهر والمدينة', 'A report by month and city'), p: SHOP + 'rows = db.execute("""SELECT strftime(\'%Y-%m\', o.day) AS month, c.city, COUNT(*) AS orders, ROUND(SUM(o.total), 2) AS revenue\n    FROM orders o JOIN customers c ON c.id = o.customer_id\n    WHERE o.status = \'paid\' GROUP BY month, c.city ORDER BY month, revenue DESC""").fetchall()\nprint(f"{\'month\':<9}{\'city\':<12}{\'orders\':>7}{\'revenue\':>10}")\nfor month, city, n, revenue in rows:\n    print(f"{month:<9}{city:<12}{n:>7}{revenue:>10,.2f}")', run: 1 }
      ],
      words: [
        { t: 'aggregate function', m: B('دالة بتلخّص صفوف كتير لقيمة: COUNT وSUM وAVG', 'a function summarising many rows into a value: COUNT, SUM, AVG'), ex: 'SUM(total)' },
        { t: 'GROUP BY', m: B('بيجمّع الصفوف حسب عمود قبل التلخيص', 'groups rows by a column before summarising'), ex: 'GROUP BY status' },
        { t: 'HAVING', m: B('شرط على النتيجة بعد التجميع', 'a condition on the result after grouping'), ex: 'HAVING SUM(total) > 1000' },
        { t: 'JOIN', m: B('ربط صفوف جدولين بعمود مشترك', 'combining rows of two tables on a shared column'), ex: 'JOIN customers c ON c.id = o.customer_id' },
        { t: 'LEFT JOIN', m: B('JOIN بيسيب كل صفوف الجدول الشمال حتى من غير مقابل', 'a JOIN keeping every left-table row, even without a match'), ex: '... WHERE o.id IS NULL' },
        { t: 'CTE', m: B('استعلام بخطوات بأسماء بـ WITH', 'a query in named steps with WITH'), ex: 'WITH paid AS (...)' },
        { t: 'table alias', m: B('اسم مختصر لجدول أو عمود في الاستعلام', 'a short name for a table or column in a query'), ex: 'orders o, SUM(total) AS revenue' }
      ],
      read: [{ lib: 'SQLBolt', what: B('الدروس 6 لـ 12 (JOINs والتجميع).', 'Lessons 6 to 12 (JOINs and aggregates).') }, { lib: 'SQLite: SQL As Understood By SQLite', what: B('افتح Date And Time Functions.', 'Open Date And Time Functions.') }],
      challenge: B('على قاعدة المتجر (جداول customers وproducts وorders وorder_items): اكتب 6 استعلامات: أفضل 3 عملاء، وأكتر منتج اتباع بالقطع، والإيراد لكل فئة منتج، والعملاء اللي اشتروا مرة واحدة بس، ومتوسط قيمة الطلب لكل شهر، والمنتجات اللي ما اتباعتش.', 'On the shop database (customers, products, orders and order_items): write 6 queries: the top 3 customers, the best-selling product by pieces, revenue per product category, customers who bought only once, the average order value per month, and products never sold.'),
      quiz: [
        { q: B('شرط على مجموع بعد GROUP BY بيتكتب بـ:', 'A condition on a sum after GROUP BY uses:'), o: ['HAVING', 'WHERE', 'ORDER BY'], a: 0, why: B('WHERE قبل التجميع.', 'WHERE comes before grouping.') },
        { q: B('عشان تلاقي العملاء اللي ملهمش طلبات:', 'To find customers with no orders:'), o: ['LEFT JOIN ... WHERE o.id IS NULL', 'JOIN ... WHERE o.id = 0', 'GROUP BY customer'], a: 0, why: B('LEFT بيسيب اللي مالوش مقابل.', 'LEFT keeps rows without a match.') },
        { q: B('`strftime(\'%Y-%m\', \'2026-09-30\')`:', '`strftime(\'%Y-%m\', \'2026-09-30\')`:'), o: ["'2026-09'", "'09-2026'", "'2026'"], a: 0, why: B('السنة والشهر.', 'Year and month.') }
      ] },

    { title: B('تصميم الجداول', 'Designing tables'),
      goal: B('تصمم جداول صح: مفتاح أساسي، ومفاتيح أجنبية، وقيود (NOT NULL وUNIQUE وCHECK)، وindexes للسرعة، وتفصل البيانات المكررة (normalization)، وتعمل upsert وترقية للقاعدة.', 'Design tables properly: a primary key, foreign keys, constraints (NOT NULL, UNIQUE, CHECK), indexes for speed, splitting repeated data (normalisation), upserts and database upgrades.'),
      learn: [
        { h: B('المفاتيح والقيود', 'Keys and constraints'),
          p: B('`id INTEGER PRIMARY KEY` رقم فريد لكل صف. `customer_id INTEGER REFERENCES customers(id)` مفتاح أجنبي: ميقبلش عميل مش موجود (في SQLite لازم `PRAGMA foreign_keys = ON`). `NOT NULL` إجباري، و`UNIQUE` ميتكررش (زي الإيميل)، و`CHECK (qty > 0)` شرط. القيود دي بتمنع البيانات الغلط **قبل** ما تدخل — أحسن من ألف if في الكود.', '`id INTEGER PRIMARY KEY` is a unique number per row. `customer_id INTEGER REFERENCES customers(id)` is a foreign key: it refuses a customer who does not exist (in SQLite you need `PRAGMA foreign_keys = ON`). `NOT NULL` is required, `UNIQUE` cannot repeat (like an email), and `CHECK (qty > 0)` is a rule. These constraints stop bad data **before** it gets in — better than a thousand ifs in code.'),
          ex: 'import sqlite3\ndb = sqlite3.connect(":memory:")\ndb.execute("PRAGMA foreign_keys = ON")\ndb.executescript("""\nCREATE TABLE customers (id INTEGER PRIMARY KEY, email TEXT NOT NULL UNIQUE, name TEXT NOT NULL);\nCREATE TABLE orders (id INTEGER PRIMARY KEY, customer_id INTEGER NOT NULL REFERENCES customers(id), qty INTEGER CHECK (qty > 0));\nINSERT INTO customers (email, name) VALUES (\'sara@x.com\', \'Sara\');\n""")\nfor sql, params in [("INSERT INTO customers (email, name) VALUES (?, ?)", ("sara@x.com", "Sara 2")),\n                    ("INSERT INTO orders (customer_id, qty) VALUES (?, ?)", (99, 1)),\n                    ("INSERT INTO orders (customer_id, qty) VALUES (?, ?)", (1, 0)),\n                    ("INSERT INTO orders (customer_id, qty) VALUES (?, ?)", (1, 2))]:\n    try:\n        db.execute(sql, params)\n        print("ok", params)\n    except sqlite3.IntegrityError as e:\n        print("refused", params, "->", e)', run: 1 },
        { h: B('normalization وindexes', 'Normalisation and indexes'),
          p: B('لو اسم العميل ومدينته متكررين في كل طلب، تغيير المدينة هيحتاج تعدّل 100 صف (وهتنسى واحد). افصلهم: جدول عملاء، وجدول طلبات فيه `customer_id` بس، وجدول سطور طلبات. والـ index على عمود بتدوّر بيه كتير (`CREATE INDEX idx_orders_customer ON orders(customer_id)`) بيخلي البحث فوري مع ملايين الصفوف. `EXPLAIN QUERY PLAN` بيقولك القاعدة استخدمت index ولا لأ.', 'If a customer’s name and city repeat in every order, changing the city means editing 100 rows (and missing one). Split them: a customers table, an orders table holding only `customer_id`, and an order-lines table. An index on a column you search often (`CREATE INDEX idx_orders_customer ON orders(customer_id)`) makes lookups instant with millions of rows. `EXPLAIN QUERY PLAN` tells you whether the database used an index.'),
          ex: 'import sqlite3, random, time\nrandom.seed(1)\ndb = sqlite3.connect(":memory:")\ndb.execute("CREATE TABLE orders (id INTEGER PRIMARY KEY, customer_id INTEGER, total REAL)")\ndb.executemany("INSERT INTO orders (customer_id, total) VALUES (?, ?)", [(random.randint(1, 50_000), random.random() * 1000) for _ in range(200_000)])\n\ndef timed():\n    t = time.perf_counter()\n    for c in range(1, 201):\n        db.execute("SELECT SUM(total) FROM orders WHERE customer_id = ?", (c,)).fetchone()\n    return (time.perf_counter() - t) * 1000\n\nprint(f"without index: {timed():.0f} ms")\ndb.execute("CREATE INDEX idx_orders_customer ON orders(customer_id)")\nprint(f"with index:    {timed():.0f} ms")\nprint(db.execute("EXPLAIN QUERY PLAN SELECT * FROM orders WHERE customer_id = 7").fetchall())', run: 1 },
        { h: B('upsert وترقية القاعدة', 'Upserts and upgrading the database'),
          p: B('`INSERT ... ON CONFLICT(email) DO UPDATE SET name = excluded.name` = «لو موجود حدّثه، ولو مش موجود ضيفه» في سطر — مثالي لمزامنة بيانات من API كل يوم. ولما تغيّر شكل الجداول بعد ما البرنامج اشتغل، استخدم رقم إصدار (`PRAGMA user_version`) وخطوات ترقية بالترتيب بدل ما تمسح القاعدة.', '`INSERT ... ON CONFLICT(email) DO UPDATE SET name = excluded.name` = «update it if it exists, add it if not» in one line — perfect for syncing data from an API daily. When you change the tables after the program is in use, keep a version number (`PRAGMA user_version`) and apply upgrade steps in order instead of deleting the database.'),
          ex: 'import sqlite3\ndb = sqlite3.connect(":memory:")\nMIGRATIONS = [\n    "CREATE TABLE customers (id INTEGER PRIMARY KEY, email TEXT UNIQUE NOT NULL, name TEXT)",\n    "ALTER TABLE customers ADD COLUMN city TEXT",\n    "CREATE INDEX idx_customers_city ON customers(city)",\n]\n\ndef migrate(db):\n    version = db.execute("PRAGMA user_version").fetchone()[0]\n    for n, sql in enumerate(MIGRATIONS[version:], start=version + 1):\n        with db:\n            db.execute(sql)\n            db.execute(f"PRAGMA user_version = {n}")\n        print("applied migration", n)\n\nmigrate(db); migrate(db)        # the second call does nothing\nUPSERT = """INSERT INTO customers (email, name, city) VALUES (?, ?, ?)\n            ON CONFLICT(email) DO UPDATE SET name = excluded.name, city = excluded.city"""\nwith db:\n    db.executemany(UPSERT, [("sara@x.com", "Sara", "Cairo"), ("omar@x.com", "Omar", "Giza"), ("sara@x.com", "Sara Ahmed", "Alexandria")])\nprint(db.execute("SELECT email, name, city FROM customers").fetchall())', run: 1 }
      ],
      practice: [
        B('صمّم قاعدة المتجر بـ 4 جداول (customers وproducts وorders وorder_items) بمفاتيح وقيود.', 'Design the shop database with 4 tables (customers, products, orders, order_items) with keys and constraints.'),
        B('جرّب 4 إدخالات غلط (إيميل مكرر، عميل مش موجود، كمية صفر، اسم فاضي) وشوف القاعدة بترفض.', 'Try 4 bad inserts (a duplicate email, a missing customer, zero quantity, an empty name) and watch the database refuse.'),
        B('قيس استعلام بحث قبل وبعد index على 200 ألف صف.', 'Time a lookup query before and after an index on 200,000 rows.'),
        B('اعمل upsert لقايمة عملاء من API (JSONPlaceholder users) مرتين واتأكد إن مفيش تكرار.', 'Upsert a customer list from an API (JSONPlaceholder users) twice and check there are no duplicates.')
      ],
      code: [
        { u: B('مخطط متجر كامل', 'A complete shop schema'), p: 'SCHEMA = """\nPRAGMA foreign_keys = ON;\nCREATE TABLE IF NOT EXISTS customers (\n  id INTEGER PRIMARY KEY, email TEXT NOT NULL UNIQUE, name TEXT NOT NULL, city TEXT,\n  created TEXT NOT NULL DEFAULT (date(\'now\')));\nCREATE TABLE IF NOT EXISTS products (\n  id INTEGER PRIMARY KEY, sku TEXT NOT NULL UNIQUE, name TEXT NOT NULL,\n  price REAL NOT NULL CHECK (price >= 0), stock INTEGER NOT NULL DEFAULT 0 CHECK (stock >= 0));\nCREATE TABLE IF NOT EXISTS orders (\n  id INTEGER PRIMARY KEY, customer_id INTEGER NOT NULL REFERENCES customers(id),\n  day TEXT NOT NULL DEFAULT (date(\'now\')), status TEXT NOT NULL DEFAULT \'new\'\n  CHECK (status IN (\'new\', \'paid\', \'shipped\', \'cancelled\')));\nCREATE TABLE IF NOT EXISTS order_items (\n  order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,\n  product_id INTEGER NOT NULL REFERENCES products(id),\n  qty INTEGER NOT NULL CHECK (qty > 0), price REAL NOT NULL,\n  PRIMARY KEY (order_id, product_id));\nCREATE INDEX IF NOT EXISTS idx_orders_customer ON orders(customer_id);\n"""\nimport sqlite3\ndb = sqlite3.connect(":memory:")\ndb.executescript(SCHEMA)\nprint([r[0] for r in db.execute("SELECT name FROM sqlite_master WHERE type = \'table\'")])', run: 1 }
      ],
      words: [
        { t: 'primary key', m: B('عمود قيمته فريدة بتحدد كل صف', 'a column whose unique value identifies each row'), ex: 'id INTEGER PRIMARY KEY' },
        { t: 'foreign key', m: B('عمود بيشاور على صف في جدول تاني', 'a column pointing at a row in another table'), ex: 'REFERENCES customers(id)' },
        { t: 'constraint', m: B('قاعدة في الجدول بترفض البيانات الغلط', 'a table rule rejecting bad data'), ex: 'NOT NULL, UNIQUE, CHECK' },
        { t: 'IntegrityError', m: B('خطأ لما إدخال يكسر قيد', 'the error when an insert breaks a constraint'), ex: 'UNIQUE constraint failed' },
        { t: 'database index', m: B('فهرس بيخلي البحث بعمود سريع جدًا', 'a lookup structure making searches on a column very fast'), ex: 'CREATE INDEX ... ON orders(customer_id)' },
        { t: 'database normalization', m: B('تقسيم البيانات لجداول عشان متتكررش', 'splitting data into tables so it is not repeated'), ex: 'customers apart from orders' },
        { t: 'upsert', m: B('إدخال لو مش موجود وتحديث لو موجود', 'insert if missing, update if present'), ex: 'ON CONFLICT(email) DO UPDATE' },
        { t: 'migration', m: B('خطوة ترقية لشكل القاعدة بترتيب', 'an ordered upgrade step for the database’s shape'), ex: 'PRAGMA user_version' }
      ],
      read: [{ lib: 'SQLite: SQL As Understood By SQLite', what: B('افتح CREATE TABLE وCREATE INDEX وupsert.', 'Open CREATE TABLE, CREATE INDEX and upsert.') }, { lib: 'SQLBolt', what: B('الدروس 13 لـ 18 (إنشاء وتعديل الجداول).', 'Lessons 13 to 18 (creating and changing tables).') }],
      challenge: B('اعمل `db.py` لمراقب الأسعار (أسبوع 16): جداول products (url فريد) وprices (product_id وday وprice) بمفاتيح وindex، وmigrations بـ user_version، وupsert للمنتجات، وإدخال سعر اليوم — واستعلام بيطلّع المنتجات اللي سعرها نزل أكتر من 5% عن آخر قراية.', 'Write `db.py` for the price watcher (week 16): tables products (unique url) and prices (product_id, day, price) with keys and an index, migrations with user_version, a product upsert and today’s price insert — plus a query listing products whose price fell more than 5% since the previous reading.'),
      quiz: [
        { q: B('عمود إيميل ميتكررش:', 'An email column that must not repeat:'), o: ['UNIQUE', 'INDEX', 'PRIMARY'], a: 0, why: B('قيد UNIQUE.', 'A UNIQUE constraint.') },
        { q: B('الـ foreign keys في SQLite محتاجة:', 'Foreign keys in SQLite need:'), o: ['PRAGMA foreign_keys = ON', 'CREATE INDEX', B('مفيش حاجة', 'nothing')], a: 0, why: B('مقفولة افتراضيًا.', 'They are off by default.') },
        { q: B('index على عمود بيخلي:', 'An index on a column makes:'), o: [B('البحث بيه أسرع جدًا', 'searching by it much faster'), B('الإدخال أسرع', 'inserts faster'), B('الملف أصغر', 'the file smaller')], a: 0, why: B('الإدخال بيبطأ شوية.', 'Inserts get a bit slower.') }
      ] },

    { title: B('من الملفات للقاعدة والعكس، وما بعد SQLite', 'From files to the database and back, and beyond SQLite'),
      goal: B('تنقل CSV وExcel لـ SQLite وتطلّع تقارير منها، وتعرف pandas مع SQL، وSQLAlchemy، وامتى تنقل لـ Postgres (اللي n8n بيستخدمه).', 'Move CSV and Excel into SQLite and produce reports from it, meet pandas with SQL and SQLAlchemy, and know when to move to Postgres (which n8n uses).'),
      learn: [
        { h: B('CSV → SQLite → تقرير', 'CSV → SQLite → report'),
          p: B('اقرا CSV بـ DictReader، ونضّف (أسبوع 10 و11)، وادخّله بـ executemany في transaction، واعمل upsert لو هتعيد التحميل كل يوم. وبعد كده أي تقرير = استعلام SQL واحد بدل لوبات Python. وطلّع النتيجة CSV أو Excel منسّق أو JSON للوحة (أسبوع 15).', 'Read the CSV with DictReader, clean it (weeks 10 and 11), insert it with executemany inside a transaction, and upsert when reloading daily. After that, any report is one SQL query instead of Python loops. Export the result as CSV, a formatted Excel file or JSON for the dashboard (week 15).'),
          ex: 'import csv, io, sqlite3\ncsv_text = "day,city,product,qty,price\\n2026-09-01,Cairo,Pen,10,7.5\\n2026-09-01,Giza,Bag,1,650\\n2026-09-02,Cairo,Bag,2,650\\n2026-09-02,Alex,Notebook,5,45\\n"\ndb = sqlite3.connect(":memory:")\ndb.execute("CREATE TABLE sales (day TEXT, city TEXT, product TEXT, qty INTEGER, price REAL)")\nrows = [(r["day"], r["city"], r["product"], int(r["qty"]), float(r["price"])) for r in csv.DictReader(io.StringIO(csv_text))]\nwith db:\n    db.executemany("INSERT INTO sales VALUES (?, ?, ?, ?, ?)", rows)\nreport = db.execute("SELECT city, SUM(qty * price) AS revenue FROM sales GROUP BY city ORDER BY revenue DESC").fetchall()\nout = io.StringIO()\nw = csv.writer(out)\nw.writerow(["city", "revenue"]); w.writerows(report)\nprint(out.getvalue())', run: 1 },
        { h: B('pandas مع SQL (لمحة)', 'pandas with SQL (a preview)'),
          p: B('`pd.read_sql(query, db)` بيرجّع نتيجة الاستعلام DataFrame، و`df.to_sql("table", db)` بيكتب DataFrame كجدول. ده جسر بين أسبوع 18 والأسبوع الجاي: SQL للتخزين والفلترة، وpandas للتحليل والرسم. (المثال بيحمّل pandas في الصفحة أول مرة.)', '`pd.read_sql(query, db)` returns a query result as a DataFrame and `df.to_sql("table", db)` writes a DataFrame as a table. It bridges this week and the next: SQL for storage and filtering, pandas for analysis and charts. (The example loads pandas on the page the first time.)'),
          ex: SHOP + 'import pandas as pd\ndf = pd.read_sql("SELECT c.city, o.total, o.status FROM orders o JOIN customers c ON c.id = o.customer_id", db)\nprint(df)\nprint(df[df.status == "paid"].groupby("city")["total"].sum())\ndf.assign(total_with_vat=df.total * 1.14).to_sql("orders_vat", db, index=False)\nprint(db.execute("SELECT COUNT(*) FROM orders_vat").fetchone())', run: 1 },
        { h: B('SQLAlchemy وPostgres', 'SQLAlchemy and Postgres'),
          p: B('لما المشروع يكبر أو أكتر من سيرفر يكتب في نفس الوقت، انقل لـ **PostgreSQL** (نفس اللي n8n بيستخدمه في الإنتاج، وفيه Postgres node). **SQLAlchemy** بيخلي نفس كود Python يشتغل على SQLite وPostgres بتغيير سطر الاتصال بس، وبيدّيك ORM (جداول ككلاسات). سطر الاتصال (فيه الباسورد) مكانه .env.', 'When the project grows or several servers write at once, move to **PostgreSQL** (what n8n uses in production, with a Postgres node). **SQLAlchemy** lets the same Python code work on SQLite and Postgres by changing only the connection string, and offers an ORM (tables as classes). The connection string (with its password) belongs in .env.'),
          ex: '# pip install sqlalchemy psycopg[binary]\nimport os\nfrom sqlalchemy import create_engine, text\n\n# sqlite:///shop.db   or   postgresql+psycopg://user:password@host:5432/shop\nengine = create_engine(os.environ.get("DATABASE_URL", "sqlite:///shop.db"))\nwith engine.begin() as conn:                      # a transaction\n    conn.execute(text("CREATE TABLE IF NOT EXISTS notes (id INTEGER PRIMARY KEY, body TEXT)"))\n    conn.execute(text("INSERT INTO notes (body) VALUES (:body)"), [{"body": "hello"}, {"body": "world"}])\nwith engine.connect() as conn:\n    for row in conn.execute(text("SELECT id, body FROM notes WHERE body LIKE :q"), {"q": "%o%"}):\n        print(row.id, row.body)' }
      ],
      practice: [
        B('حمّل ملف مبيعات أسبوع 11 (CSV) في SQLite بـ executemany واطبع 3 تقارير بـ SQL.', 'Load the week 11 sales file (CSV) into SQLite with executemany and print 3 SQL reports.'),
        B('صدّر تقرير SQL لـ Excel منسّق بدالة style_table.', 'Export an SQL report to a formatted Excel file with style_table.'),
        B('جرّب `pd.read_sql` و`to_sql` على قاعدتك (في الصفحة أو على جهازك).', 'Try `pd.read_sql` and `to_sql` on your database (on the page or your machine).'),
        B('ثبّت SQLAlchemy وشغّل نفس المثال على SQLite، واقرا إزاي تغيّر DATABASE_URL لـ Postgres.', 'Install SQLAlchemy, run the same example on SQLite, and read how DATABASE_URL changes for Postgres.')
      ],
      code: [
        { u: B('Excel → SQLite بالجملة', 'Excel → SQLite in bulk'), p: 'import sqlite3\nfrom pathlib import Path\nfrom openpyxl import load_workbook\n\ndef excel_to_sqlite(xlsx: Path, db_path: Path, table: str) -> int:\n    ws = load_workbook(xlsx, data_only=True, read_only=True).active\n    rows = ws.iter_rows(values_only=True)\n    headers = [str(h).strip().lower().replace(" ", "_") for h in next(rows)]\n    data = [r for r in rows if any(v is not None for v in r)]\n    with sqlite3.connect(db_path) as db:\n        db.execute(f"DROP TABLE IF EXISTS {table}")\n        db.execute(f"CREATE TABLE {table} ({\', \'.join(headers)})")\n        db.executemany(f"INSERT INTO {table} VALUES ({\', \'.join(\'?\' * len(headers))})", data)\n    return len(data)\n\n# print(excel_to_sqlite(Path("sales.xlsx"), Path("sales.db"), "sales"))' }
      ],
      words: [
        { t: 'bulk load', m: B('تحميل بيانات كتير للقاعدة مرة واحدة', 'loading a lot of data into the database at once'), ex: 'executemany inside one transaction' },
        { t: 'read_sql', m: B('دالة pandas بترجّع نتيجة SQL كـ DataFrame', 'a pandas function returning an SQL result as a DataFrame'), ex: 'pd.read_sql(query, db)' },
        { t: 'ORM', m: B('طريقة تتعامل بيها مع الجداول ككلاسات وكائنات', 'a way to treat tables as classes and objects'), ex: 'SQLAlchemy ORM' },
        { t: 'SQLAlchemy', m: B('أشهر مكتبة قواعد بيانات في Python', 'the best-known database library in Python'), ex: 'create_engine(url)' },
        { t: 'PostgreSQL', m: B('قاعدة بيانات سيرفر قوية ومفتوحة، بيستخدمها n8n', 'a powerful open-source server database, used by n8n'), ex: 'postgresql+psycopg://…' },
        { t: 'connection string', m: B('سطر فيه نوع القاعدة ومكانها وبيانات الدخول', 'a line holding the database type, location and login'), ex: 'DATABASE_URL in .env' }
      ],
      read: ['lib:SQLAlchemy Unified Tutorial', { lib: 'Python for Data Analysis, 3E', what: B('الجزء الخاص بـ Interacting with Databases.', 'The part on Interacting with Databases.') }],
      challenge: B('اعمل `sales_db.py`: يحمّل كل ملفات CSV من فولدر لجدول sales (مع عمود source، ومن غير تكرار لو اتشغّل مرتين بـ UNIQUE وupsert)، ويطلّع `report.xlsx` فيه 3 شيتات من 3 استعلامات SQL — وكل ده في transaction لكل ملف.', 'Write `sales_db.py`: load every CSV in a folder into a sales table (with a source column, and no duplicates when run twice thanks to UNIQUE and an upsert), then produce `report.xlsx` with 3 sheets from 3 SQL queries — one transaction per file.'),
      quiz: [
        { q: B('ليه executemany في transaction واحدة؟', 'Why executemany inside one transaction?'), o: [B('أسرع، ويا الملف كله يدخل يا ولا حاجة', 'faster, and the whole file goes in or nothing'), B('عشان CSV', 'because of CSV'), B('مالهاش فايدة', 'no benefit')], a: 0, why: B('سرعة وسلامة.', 'Speed and safety.') },
        { q: B('ميزة SQLAlchemy الكبيرة:', 'SQLAlchemy’s big advantage:'), o: [B('نفس الكود على SQLite وPostgres', 'the same code on SQLite and Postgres'), B('مش محتاج SQL خالص', 'no SQL ever'), B('أسرع من كل حاجة', 'faster than everything')], a: 0, why: B('بتغيّر الـ URL بس.', 'You change only the URL.') },
        { q: B('سطر اتصال Postgres فيه باسورد، مكانه:', 'A Postgres connection string with a password goes in:'), o: ['.env', B('الكود', 'the code'), 'README'], a: 0, why: B('سر.', 'It is a secret.') }
      ] },

    { title: B('مراجعة ومشروع واختبار الأسبوع', 'Review, project and weekly test'),
      goal: B('تنقل مشروع حقيقي من ملفات لقاعدة بيانات مصممة صح، وتعدّي الاختبار.', 'Move a real project from files to a well-designed database, and pass the test.'),
      review: [
        B('CREATE وINSERT وSELECT وWHERE وORDER BY وLIMIT وUPDATE وDELETE (ومتنساش WHERE).', 'CREATE, INSERT, SELECT, WHERE, ORDER BY, LIMIT, UPDATE and DELETE (never forget WHERE).'),
        B('الـ parameters ضد SQL injection، وexecutemany، والـ transactions، وsqlite3.Row.', 'Parameters against SQL injection, executemany, transactions and sqlite3.Row.'),
        B('COUNT وSUM وGROUP BY وHAVING وJOIN وLEFT JOIN وWITH والتواريخ.', 'COUNT, SUM, GROUP BY, HAVING, JOIN, LEFT JOIN, WITH and dates.'),
        B('المفاتيح والقيود والـ indexes والـ normalization والـ upsert والـ migrations.', 'Keys, constraints, indexes, normalisation, upserts and migrations.'),
        B('CSV/Excel ↔ SQLite، وpandas.read_sql، وSQLAlchemy، وامتى Postgres.', 'CSV/Excel ↔ SQLite, pandas.read_sql, SQLAlchemy, and when to use Postgres.')
      ],
      project: B('**متتبع المصاريف على SQLite** (من أسابيع 4 و6 و8 و9): انقله لقاعدة `expenses.db`: جداول categories وexpenses (بمفاتيح وقيود: المبلغ موجب والتاريخ ISO والفئة من الجدول) وindex على التاريخ، وmigrations بـ user_version، وكل الأوامر (add وlist وtop وby-cat وdelete) بقت استعلامات SQL بـ parameters. زوّد أوامر: `month 2026-09` (تقرير شهر)، و`import file.csv` (upsert بدون تكرار)، و`export report.xlsx`. سكربت ترحيل بيقرا `expenses.json` القديم ويدخّله مرة واحدة. 15 test على قاعدة `:memory:`.', '**The expense tracker on SQLite** (from weeks 4, 6, 8 and 9): move it to an `expenses.db` database: categories and expenses tables (with keys and constraints: a positive amount, an ISO date and a category from its table) with an index on the date, migrations with user_version, and every command (add, list, top, by-cat, delete) as a parameterised SQL query. Add commands: `month 2026-09` (a month report), `import file.csv` (an upsert without duplicates) and `export report.xlsx`. A migration script reads the old `expenses.json` and loads it once. 15 tests on a `:memory:` database.'),
      test: [
        { q: B('`SELECT * FROM t LIMIT 5` بيرجّع:', '`SELECT * FROM t LIMIT 5` returns:'), o: [B('أول 5 صفوف بس', 'only the first 5 rows'), B('الصف رقم 5', 'row number 5'), B('5 أعمدة', '5 columns')], a: 0, why: B('LIMIT للعدد.', 'LIMIT caps the count.') },
        { q: B('`WHERE name LIKE \'S%\'`:', '`WHERE name LIKE \'S%\'`:'), o: [B('الأسماء اللي بتبدأ بـ S', 'names starting with S'), B('اللي بتنتهي بـ S', 'names ending with S'), B('S بالظبط', 'exactly S')], a: 0, why: B('% أي حاجة بعدها.', '% is anything after.') },
        { q: B('`COUNT(*)` بيعد:', '`COUNT(*)` counts:'), o: [B('الصفوف', 'rows'), B('الأعمدة', 'columns'), B('الجداول', 'tables')], a: 0, why: B('عدد الصفوف.', 'The number of rows.') },
        { q: B('الـ ? في `execute("... WHERE id = ?", (5,))`:', 'The ? in `execute("... WHERE id = ?", (5,))`:'), o: [B('مكان قيمة بتتحط بأمان', 'a slot where a value goes in safely'), B('أي حاجة', 'anything'), B('خطأ', 'an error')], a: 0, why: B('parameter.', 'A parameter.') },
        { q: B('خطأ في نص transaction بـ `with db:`:', 'An error midway through a `with db:` transaction:'), o: [B('كل حاجة بترجع زي ما كانت', 'everything returns to how it was'), B('اللي اتعمل بيتحفظ', 'what was done is saved'), B('القاعدة بتتمسح', 'the database is deleted')], a: 0, why: B('rollback.', 'A rollback.') },
        { q: B('JOIN بيربط جدولين بـ:', 'A JOIN combines two tables on:'), o: [B('عمود مشترك (ON)', 'a shared column (ON)'), B('الترتيب', 'their order'), B('أسماء الجداول', 'the table names')], a: 0, why: B('ON c.id = o.customer_id.', 'ON c.id = o.customer_id.') },
        { q: B('شرط على `SUM(total)`:', 'A condition on `SUM(total)`:'), o: ['HAVING', 'WHERE', 'LIMIT'], a: 0, why: B('بعد التجميع.', 'After grouping.') },
        { q: B('إيميل مكرر في عمود UNIQUE بيطلّع:', 'A duplicate email in a UNIQUE column raises:'), o: ['IntegrityError', 'ValueError', 'KeyError'], a: 0, why: B('قيد اتكسر.', 'A constraint was broken.') },
        { q: B('البحث بطيء بعمود customer_id على مليون صف. الحل:', 'Searching by customer_id over a million rows is slow. The fix:'), o: ['CREATE INDEX', 'DELETE', 'LIMIT 1'], a: 0, why: B('index.', 'An index.') },
        { q: B('«ضيفه لو مش موجود وحدّثه لو موجود»:', '«Add it if missing, update it if present»:'), o: ['upsert (ON CONFLICT DO UPDATE)', 'INSERT OR FAIL', 'SELECT'], a: 0, why: B('upsert.', 'An upsert.') },
        { q: B('نفس الطلب فيه اسم العميل ومدينته في كل صف. المشكلة:', 'Each order row repeats the customer’s name and city. The problem:'), o: [B('تكرار؛ افصل جدول عملاء', 'repetition; split out a customers table'), B('مفيش مشكلة', 'none'), B('محتاج index', 'it needs an index')], a: 0, why: B('normalization.', 'Normalisation.') },
        { q: B('قاعدة n8n في الإنتاج غالبًا:', 'n8n’s production database is usually:'), o: ['PostgreSQL', 'SQLite', 'Excel'], a: 0, why: B('Postgres.', 'Postgres.') }
      ] }
  ]
};
