// Python week 21 — Building APIs with FastAPI and connecting n8n.
const B = (ar, en) => ({ ar, en });
module.exports = {
  level: B('محترف', 'Professional'),
  title: B('بناء APIs بـ FastAPI والربط مع n8n', 'Building APIs with FastAPI and connecting n8n'),
  goal: B('تحوّل أدواتك (تنضيف بيانات، فواتير، تقارير) لـ API بـ FastAPI يناديه n8n أو أي برنامج: endpoints وparameters، وتحقق تلقائي بـ Pydantic، وتوثيق تلقائي، وحماية بمفتاح، وقاعدة بيانات، واختبارات — Python بيعمل الشغل التقيل وn8n بيرتّب.',
          'Turn your tools (data cleaning, invoices, reports) into an API with FastAPI that n8n or any program can call: endpoints and parameters, automatic validation with Pydantic, automatic docs, key protection, a database and tests — Python does the heavy lifting and n8n orchestrates.'),
  days: [
    { title: B('أول API بـ FastAPI', 'A first API with FastAPI'),
      goal: B('تعمل تطبيق FastAPI بـ endpoints فيها path وquery parameters، وتشغّله، وتجرّبه من صفحة التوثيق التلقائية.', 'Create a FastAPI app with endpoints using path and query parameters, run it, and try it from the automatic docs page.'),
      learn: [
        { h: B('ليه API؟', 'Why an API?'),
          p: B('سكربت بيشتغل على جهازك بس. API بيخلي أي حاجة تناديه عبر HTTP: n8n (HTTP Request node)، أو صفحة ويب (fetch)، أو سكربت تاني، أو زميلك. كده Python بتاعك (pandas وPDF والتنضيف) يبقى «node» تستخدمه في أي workflow. FastAPI أسهل وأسرع framework لده، وبيستخدم الـ type hints (أسبوع 6) للتحقق والتوثيق.', 'A script runs only on your machine. An API lets anything call it over HTTP: n8n (the HTTP Request node), a web page (fetch), another script, or a colleague. Your Python (pandas, PDF, cleaning) becomes a «node» you can use in any workflow. FastAPI is the easiest and fastest framework for this, and it uses type hints (week 6) for validation and docs.'),
          ex: '# pip install "fastapi[standard]"\n# main.py\nfrom fastapi import FastAPI\n\napp = FastAPI(title="Shop tools")\n\n@app.get("/")\ndef home():\n    return {"status": "ok", "service": "shop tools"}\n\n@app.get("/vat/{amount}")\ndef vat(amount: float, rate: float = 0.14):\n    return {"amount": amount, "rate": rate, "vat": round(amount * rate, 2), "total": round(amount * (1 + rate), 2)}\n\n# run:  fastapi dev main.py      then open http://127.0.0.1:8000/docs' },
        { h: B('path وquery', 'Path and query'),
          p: B('`/vat/{amount}` → `amount` من المسار، وأي معامل تاني في الدالة مش في المسار بيبقى query (`?rate=0.2`). الـ type hint (`float` و`int`) بيحوّل ويتحقق لوحده: `/vat/abc` بيرجّع 422 برسالة واضحة من غير ما تكتب سطر تحقق. والقيمة اللي بترجّعها (dict أو list) بتتحول JSON لوحدها.', '`/vat/{amount}` → `amount` comes from the path, and any other function parameter not in the path becomes a query (`?rate=0.2`). The type hint (`float`, `int`) converts and validates by itself: `/vat/abc` returns 422 with a clear message without you writing a check. Whatever you return (a dict or list) becomes JSON automatically.'),
          ex: 'from fastapi import FastAPI\nfrom fastapi.testclient import TestClient\n\napp = FastAPI()\n\n@app.get("/vat/{amount}")\ndef vat(amount: float, rate: float = 0.14):\n    return {"total": round(amount * (1 + rate), 2)}\n\n# TestClient calls the app without starting a server — perfect for trying and testing\nclient = TestClient(app)\nprint(client.get("/vat/100").json())\nprint(client.get("/vat/100?rate=0.2").json())\nr = client.get("/vat/abc")\nprint(r.status_code, r.json()["detail"][0]["msg"])' },
        { h: B('التشغيل والتوثيق', 'Running and the docs'),
          p: B('`fastapi dev main.py` بيشغّل سيرفر تطوير بيعيد التحميل لما تحفظ (Uvicorn تحت). افتح `/docs`: صفحة تفاعلية فيها كل endpoint وتقدر تجرّبه بزرار «Try it out» — ومن نفس التوثيق n8n تقدر تعرف تبعت إيه. وللإنتاج: `fastapi run main.py` أو `uvicorn main:app --host 0.0.0.0 --port 8000`.', '`fastapi dev main.py` starts a development server that reloads when you save (Uvicorn underneath). Open `/docs`: an interactive page listing every endpoint that you can try with «Try it out» — and from the same docs you know what to send from n8n. For production: `fastapi run main.py` or `uvicorn main:app --host 0.0.0.0 --port 8000`.'),
          ex: 'python -m venv .venv && .venv\\Scripts\\Activate.ps1\npython -m pip install "fastapi[standard]"\nfastapi dev main.py          # http://127.0.0.1:8000  — docs at /docs and /redoc\ncurl "http://127.0.0.1:8000/vat/250?rate=0.14"\nfastapi run main.py          # production mode, no auto-reload', lang: 'text' }
      ],
      practice: [
        B('ثبّت FastAPI واعمل `main.py` بـ 3 endpoints (home وvat وgreet/{name}).', 'Install FastAPI and write `main.py` with 3 endpoints (home, vat and greet/{name}).'),
        B('شغّله بـ `fastapi dev` وجرّب كل endpoint من `/docs`.', 'Run it with `fastapi dev` and try each endpoint from `/docs`.'),
        B('ابعت قيمة غلط (نص مكان رقم) واقرا رد الـ 422.', 'Send a wrong value (text for a number) and read the 422 response.'),
        B('جرّب نفس الطلبات بـ TestClient في سكربت.', 'Try the same requests with TestClient in a script.')
      ],
      code: [
        { u: B('endpoint بيلف دالة قديمة', 'An endpoint wrapping an old function'), p: 'import re\nfrom fastapi import FastAPI\n\napp = FastAPI(title="Cleaning tools")\n\ndef normalise_eg_mobile(raw: str) -> str | None:        # from week 10\n    digits = re.sub(r"\\D", "", raw)\n    digits = re.sub(r"^(?:0020|20)(?=1)", "0", digits)\n    return digits if re.fullmatch(r"01[0125]\\d{8}", digits) else None\n\n@app.get("/clean/phone")\ndef clean_phone(phone: str):\n    clean = normalise_eg_mobile(phone)\n    return {"input": phone, "phone": clean, "valid": clean is not None}' }
      ],
      words: [
        { t: 'web API', m: B('برنامج بيستقبل طلبات HTTP ويرجّع بيانات (غالبًا JSON)', 'a program receiving HTTP requests and returning data (usually JSON)'), ex: 'GET /vat/100' },
        { t: 'FastAPI', m: B('framework سريع لبناء APIs بـ Python', 'a fast framework for building APIs in Python'), ex: 'app = FastAPI()' },
        { t: 'path operation', m: B('دالة مربوطة بـ method ومسار (@app.get)', 'a function bound to a method and a path (@app.get)'), ex: '@app.get("/vat/{amount}")' },
        { t: 'path parameter', m: B('جزء متغير في المسار نفسه', 'a variable part of the path itself'), ex: '/vat/{amount}' },
        { t: 'Uvicorn', m: B('السيرفر اللي بيشغّل تطبيق FastAPI', 'the server that runs a FastAPI app'), ex: 'uvicorn main:app' },
        { t: 'OpenAPI docs', m: B('صفحة توثيق تفاعلية بتتعمل لوحدها (/docs)', 'an interactive docs page generated automatically (/docs)'), ex: 'http://127.0.0.1:8000/docs' },
        { t: 'TestClient', m: B('بينادي التطبيق من غير سيرفر، للتجربة والاختبار', 'calls the app without a server, for trying and testing'), ex: 'client.get("/vat/100")' }
      ],
      read: [{ lib: 'FastAPI documentation', what: B('Tutorial: First Steps وPath Parameters وQuery Parameters.', 'Tutorial: First Steps, Path Parameters and Query Parameters.') }, { lib: 'Flask documentation', what: B('(للمقارنة) اقرا Quickstart بسرعة.', '(for comparison) skim the Quickstart.') }],
      challenge: B('اعمل API «أدوات النصوص»: `/clean/phone` و`/clean/email` و`/clean/name` و`/mask?text=` (بيستخدم redact من أسبوع 10)، وكل واحد بيرجّع الأصل والنضيف، وجرّبهم كلهم من /docs ومن TestClient.', 'Build a «text tools» API: `/clean/phone`, `/clean/email`, `/clean/name` and `/mask?text=` (using redact from week 10), each returning the input and the cleaned value, and try them all from /docs and with TestClient.'),
      quiz: [
        { q: B('في `@app.get("/items/{id}")` والدالة `def f(id: int, page: int = 1)`، page:', 'In `@app.get("/items/{id}")` with `def f(id: int, page: int = 1)`, page is:'), o: [B('query parameter', 'a query parameter'), B('path parameter', 'a path parameter'), B('body', 'the body')], a: 0, why: B('مش في المسار.', 'It is not in the path.') },
        { q: B('`/vat/abc` و amount: float:', '`/vat/abc` with amount: float:'), o: [B('422 برسالة تحقق', '422 with a validation message'), B('500', '500'), B('200', '200')], a: 0, why: B('FastAPI بيتحقق لوحده.', 'FastAPI validates by itself.') },
        { q: B('صفحة التوثيق التفاعلية:', 'The interactive docs page:'), o: ['/docs', '/help', '/api'], a: 0, why: B('OpenAPI.', 'OpenAPI.') }
      ] },

    { title: B('Pydantic: البيانات الداخلة والخارجة', 'Pydantic: data in and out'),
      goal: B('تستقبل JSON في POST بموديلات Pydantic بتتحقق لوحدها (أنواع وقيود وقيم افتراضية)، وتحدد شكل الرد بـ response_model، وتفهم أخطاء 422.', 'Receive JSON in a POST with Pydantic models that validate by themselves (types, constraints and defaults), shape the response with response_model, and understand 422 errors.'),
      learn: [
        { h: B('موديل للـ body', 'A model for the body'),
          p: B('`class OrderIn(BaseModel):` بحقول وأنواعها، وendpoint `def create(order: OrderIn)` — FastAPI بيقرا JSON الطلب ويحوّله ويتحقق منه، ولو فيه غلطة بيرجّع 422 بمكان كل غلطة بالظبط. زي الـ dataclass (أسبوع 17) بس بيتحقق ويحوّل (`"3"` → 3).', '`class OrderIn(BaseModel):` with typed fields, and an endpoint `def create(order: OrderIn)` — FastAPI reads the request JSON, converts and validates it, and on a mistake returns 422 pointing at each error exactly. Like a dataclass (week 17) but it validates and converts (`"3"` → 3).'),
          ex: 'from fastapi import FastAPI\nfrom fastapi.testclient import TestClient\nfrom pydantic import BaseModel, EmailStr, Field\n\nclass Line(BaseModel):\n    sku: str\n    qty: int = Field(gt=0)\n    price: float = Field(ge=0)\n\nclass OrderIn(BaseModel):\n    customer: str = Field(min_length=2)\n    email: str\n    lines: list[Line] = Field(min_length=1)\n    coupon: str | None = None\n\napp = FastAPI()\n\n@app.post("/orders/total")\ndef total(order: OrderIn):\n    subtotal = sum(l.qty * l.price for l in order.lines)\n    return {"customer": order.customer, "subtotal": subtotal, "total": round(subtotal * 1.14, 2)}\n\nc = TestClient(app)\nprint(c.post("/orders/total", json={"customer": "Sara", "email": "s@x.com", "lines": [{"sku": "P-1", "qty": "3", "price": 7.5}]}).json())\nbad = c.post("/orders/total", json={"customer": "S", "email": "s@x.com", "lines": [{"sku": "P-1", "qty": 0, "price": 7.5}]})\nprint(bad.status_code, [(e["loc"], e["msg"]) for e in bad.json()["detail"]])' },
        { h: B('response_model وشكل الرد', 'response_model and the response shape'),
          p: B('`@app.post(..., response_model=OrderOut)` بيضمن إن الرد بالشكل ده بالظبط وبيشيل أي حقل زيادة (زي حقول داخلية أو أسرار ما ينفعش تطلع). وبيظهر في /docs، فـ n8n يعرف هيستلم إيه. و`status_code=201` للإنشاء.', '`@app.post(..., response_model=OrderOut)` guarantees the response has exactly that shape and drops extra fields (like internal fields or secrets that must not leak). It shows in /docs, so n8n knows what it will receive. Use `status_code=201` for creation.'),
          ex: 'from fastapi import FastAPI\nfrom fastapi.testclient import TestClient\nfrom pydantic import BaseModel\n\nclass CustomerOut(BaseModel):\n    id: int\n    name: str\n    city: str\n\nDB = {1: {"id": 1, "name": "Sara", "city": "Cairo", "password_hash": "x9…", "notes": "internal"}}\napp = FastAPI()\n\n@app.get("/customers/{cid}", response_model=CustomerOut)\ndef get_customer(cid: int):\n    return DB[cid]          # extra fields are removed from the response\n\nprint(TestClient(app).get("/customers/1").json())' },
        { h: B('موديلات مفيدة لوحدها', 'Models are useful on their own'),
          p: B('Pydantic مش للـ APIs بس: استخدمه تتحقق من أي بيانات جاية من برّه — webhook أو ملف JSON أو رد API. `Model.model_validate(data)` بيحوّل ويتحقق، و`model_dump()` بيرجّع dict، و`ValidationError` فيها كل الأخطاء مرة واحدة (أحسن من validate_order بتاع أسبوع 8).', 'Pydantic is not only for APIs: use it to validate any outside data — a webhook, a JSON file or an API response. `Model.model_validate(data)` converts and validates, `model_dump()` returns a dict, and `ValidationError` lists every error at once (better than week 8’s validate_order).'),
          ex: 'from pydantic import BaseModel, Field, ValidationError\n\nclass Product(BaseModel):\n    sku: str = Field(pattern=r"^[A-Z]{1,3}-\\d+$")\n    name: str\n    price: float = Field(gt=0)\n    stock: int = 0\n\nrows = [{"sku": "P-1", "name": "Pen", "price": "7.5"}, {"sku": "pen1", "name": "Pen", "price": -1}]\nfor row in rows:\n    try:\n        p = Product.model_validate(row)\n        print("ok:", p.model_dump())\n    except ValidationError as e:\n        print("bad:", [(err["loc"][0], err["msg"]) for err in e.errors()])', run: 1 }
      ],
      practice: [
        B('اعمل موديل `Expense` بقيود (مبلغ موجب، فئة من قايمة بـ Literal، تاريخ date) وendpoint POST بيرجّعه.', 'Make an `Expense` model with constraints (a positive amount, a category from a Literal list, a date) and a POST endpoint returning it.'),
        B('ابعت 5 طلبات غلط مختلفة واقرا مكان كل خطأ في الـ 422.', 'Send 5 different bad requests and read where each error is in the 422.'),
        B('اعمل response_model بيخبي حقل داخلي واتأكد إنه مش في الرد.', 'Use a response_model that hides an internal field and confirm it is not in the response.'),
        B('استخدم Pydantic تتحقق من 10 صفوف من ملف JSON من غير API.', 'Use Pydantic to validate 10 rows from a JSON file without an API.')
      ],
      code: [
        { u: B('موديلات طلب ورد', 'Request and response models'), p: 'from datetime import date\nfrom typing import Literal\nfrom pydantic import BaseModel, Field\n\nCategory = Literal["transport", "food", "bills", "other"]\n\nclass ExpenseIn(BaseModel):\n    day: date\n    category: Category\n    amount: float = Field(gt=0, le=1_000_000)\n    note: str = Field(default="", max_length=200)\n\nclass ExpenseOut(ExpenseIn):\n    id: int\n\nprint(ExpenseIn.model_validate({"day": "2026-10-01", "category": "food", "amount": "120.5"}))', run: 1 }
      ],
      words: [
        { t: 'Pydantic model', m: B('كلاس بيانات بيتحقق من الأنواع والقيود ويحوّل', 'a data class that validates types and constraints and converts'), ex: 'class OrderIn(BaseModel):' },
        { t: 'Field', m: B('بيحدد قيود حقل: أكبر من، أقل طول، نمط…', 'sets a field’s constraints: greater than, min length, pattern…'), ex: 'qty: int = Field(gt=0)' },
        { t: '422 Unprocessable Entity', m: B('رد بيقول البيانات اللي بعتها مش سليمة', 'a response saying the data you sent is invalid'), ex: 'detail: [{loc, msg}]' },
        { t: 'response_model', m: B('شكل الرد المضمون اللي بيشيل الحقول الزيادة', 'the guaranteed response shape that drops extra fields'), ex: 'response_model=CustomerOut' },
        { t: 'ValidationError', m: B('خطأ Pydantic فيه كل مشاكل البيانات', 'Pydantic’s error listing every data problem'), ex: 'e.errors()' },
        { t: 'Literal', m: B('نوع بيقبل قيم محددة بس', 'a type accepting only given values'), ex: 'Literal["food", "bills"]' }
      ],
      read: [{ lib: 'FastAPI documentation', what: B('Request Body وResponse Model.', 'Request Body and Response Model.') }, { lib: 'Pydantic documentation', what: B('Models وFields.', 'Models and Fields.') }],
      challenge: B('اعمل `POST /invoices/preview` بياخد طلب بموديل كامل (عميل وسطور وكوبون اختياري)، ويتحقق بقيود معقولة، ويرجّع `InvoicePreview` (الإجمالي والضريبة والخصم والسطور مع إجمالي كل سطر) بـ response_model، و6 tests بـ TestClient.', 'Build `POST /invoices/preview` taking an order with a full model (customer, lines, an optional coupon), validating with sensible constraints, and returning an `InvoicePreview` (total, VAT, discount and lines with their totals) through response_model, plus 6 TestClient tests.'),
      quiz: [
        { q: B('POST بيانات ناقصة حقل إجباري:', 'A POST missing a required field:'), o: ['422', '200', '404'], a: 0, why: B('تحقق Pydantic.', 'Pydantic validation.') },
        { q: B('`qty: int = Field(gt=0)` بيرفض:', '`qty: int = Field(gt=0)` rejects:'), o: [B('0 و-1', '0 and -1'), '1', '"5"'], a: 0, why: B('"5" بيتحول 5.', '"5" is converted to 5.') },
        { q: B('response_model بيفيد في:', 'response_model helps to:'), o: [B('منع تسريب حقول داخلية وتوضيح شكل الرد', 'stop internal fields leaking and document the response'), B('السرعة', 'speed'), B('الحماية بكلمة سر', 'password protection')], a: 0, why: B('شكل مضمون.', 'A guaranteed shape.') }
      ] },

    { title: B('خدمة حقيقية: أخطاء وأمان', 'A real service: errors and security'),
      goal: B('ترجّع أخطاء واضحة بـ HTTPException وstatus codes صح، وتحمي الـ API بمفتاح في header عن طريق dependency، وتفتح CORS للصفحات اللي محتاجاه بس، وتنظّم الكود بـ routers.', 'Return clear errors with HTTPException and the right status codes, protect the API with a header key through a dependency, open CORS only for the pages that need it, and organise the code with routers.'),
      learn: [
        { h: B('HTTPException', 'HTTPException'),
          p: B('`raise HTTPException(status_code=404, detail="order not found")` بيرجّع الخطأ ده بالظبط. اختار الكود الصح (أسبوع 13): 404 مش موجود، 409 تعارض (موجود قبل كده)، 400 طلب مش منطقي، 401/403 صلاحيات. n8n بيقرا الكود ده ويقرر يكمّل ولا يروح لفرع الخطأ.', '`raise HTTPException(status_code=404, detail="order not found")` returns exactly that error. Choose the right code (week 13): 404 not found, 409 conflict (already exists), 400 a request that makes no sense, 401/403 permissions. n8n reads that code and decides whether to continue or take the error branch.'),
          ex: 'from fastapi import FastAPI, HTTPException\nfrom fastapi.testclient import TestClient\n\napp = FastAPI()\nORDERS = {1: {"id": 1, "status": "new"}}\n\n@app.post("/orders/{oid}/pay", status_code=200)\ndef pay(oid: int):\n    order = ORDERS.get(oid)\n    if order is None:\n        raise HTTPException(404, detail=f"order {oid} not found")\n    if order["status"] != "new":\n        raise HTTPException(409, detail=f"order {oid} is already {order[\'status\']}")\n    order["status"] = "paid"\n    return order\n\nc = TestClient(app)\nfor oid in (1, 1, 7):\n    r = c.post(f"/orders/{oid}/pay")\n    print(r.status_code, r.json())' },
        { h: B('مفتاح API بـ dependency', 'An API key through a dependency'),
          p: B('أي API على النت لازم يتحمى. اعمل دالة `require_key` بتقرا header `X-API-Key` وتقارنه بالمفتاح من .env (بـ `secrets.compare_digest`)، وتطلّع 401 لو غلط. `Depends(require_key)` على الـ endpoints (أو الـ router كله) بيشغّلها قبل كل طلب. في n8n: HTTP Request → Authentication → Header Auth بنفس الاسم والقيمة.', 'Any API on the internet must be protected. Write `require_key`, which reads the `X-API-Key` header, compares it with the key from .env (with `secrets.compare_digest`) and raises 401 when wrong. `Depends(require_key)` on the endpoints (or the whole router) runs it before every request. In n8n: HTTP Request → Authentication → Header Auth with the same name and value.'),
          ex: 'import os, secrets\nfrom fastapi import Depends, FastAPI, Header, HTTPException\nfrom fastapi.testclient import TestClient\n\nos.environ.setdefault("TOOLS_API_KEY", "demo-key-for-tests")\n\ndef require_key(x_api_key: str = Header(default="")):\n    if not secrets.compare_digest(x_api_key, os.environ["TOOLS_API_KEY"]):\n        raise HTTPException(401, detail="missing or wrong X-API-Key")\n\napp = FastAPI(dependencies=[Depends(require_key)])   # every endpoint is protected\n\n@app.get("/stats")\ndef stats():\n    return {"orders": 85}\n\nc = TestClient(app)\nprint(c.get("/stats").status_code)\nprint(c.get("/stats", headers={"X-API-Key": "demo-key-for-tests"}).json())' },
        { h: B('CORS وrouters', 'CORS and routers'),
          p: B('لو صفحة ويب (أسبوع 15) هتنادي الـ API من دومين تاني، ضيف `CORSMiddleware` بالدومينات المسموحة **بالاسم** (مش `*` مع مفاتيح). ولما الـ endpoints تكتر قسّمها: `APIRouter(prefix="/orders", tags=["orders"])` في ملف لوحده و`app.include_router(router)`.', 'If a web page (week 15) on another domain will call the API, add `CORSMiddleware` with the allowed domains **by name** (not `*` together with keys). When endpoints multiply, split them: `APIRouter(prefix="/orders", tags=["orders"])` in its own file and `app.include_router(router)`.'),
          ex: '# app/main.py\nfrom fastapi import FastAPI\nfrom fastapi.middleware.cors import CORSMiddleware\nfrom app.routers import orders, tools\n\napp = FastAPI(title="Shop tools", version="1.0")\napp.add_middleware(CORSMiddleware, allow_origins=["https://dashboard.example.com"], allow_methods=["GET", "POST"], allow_headers=["X-API-Key", "Content-Type"])\napp.include_router(orders.router)\napp.include_router(tools.router)\n\n# app/routers/orders.py\nfrom fastapi import APIRouter, Depends\nfrom app.security import require_key\nrouter = APIRouter(prefix="/orders", tags=["orders"], dependencies=[Depends(require_key)])\n\n@router.get("/")\ndef list_orders(status: str = "paid"):\n    return []', lang: 'text' }
      ],
      practice: [
        B('زوّد 404 و409 و400 في endpoints بتاعتك بالمعنى الصح.', 'Add 404, 409 and 400 to your endpoints where they truly fit.'),
        B('احمي الـ API بمفتاح من .env وجرّب من غير header ومعاه.', 'Protect the API with a key from .env and try without the header and with it.'),
        B('اعمل HTTP Request في n8n بـ Header Auth بينادي الـ API بتاعك (شغّال على جهازك).', 'Make an n8n HTTP Request with Header Auth calling your API (running on your machine).'),
        B('قسّم التطبيق لـ routers في فولدر `app/`.', 'Split the app into routers in an `app/` folder.')
      ],
      code: [
        { u: B('معالج أخطاء عام', 'A global error handler'), p: 'import logging\nfrom fastapi import FastAPI, Request\nfrom fastapi.responses import JSONResponse\n\nlog = logging.getLogger("api")\napp = FastAPI()\n\n@app.exception_handler(Exception)\nasync def unexpected(request: Request, exc: Exception):\n    log.exception("unhandled error on %s %s", request.method, request.url.path)\n    return JSONResponse(status_code=500, content={"detail": "internal error — it was logged"})' }
      ],
      words: [
        { t: 'HTTPException', m: B('بتطلّع رد خطأ HTTP بكود ورسالة', 'raises an HTTP error response with a code and message'), ex: 'raise HTTPException(404, "not found")' },
        { t: '409 Conflict', m: B('الطلب بيتعارض مع الحالة الحالية', 'the request conflicts with the current state'), ex: 'already paid' },
        { t: 'dependency injection', m: B('FastAPI بيشغّل دوال محتاجها الـ endpoint قبله (Depends)', 'FastAPI running functions an endpoint needs before it (Depends)'), ex: 'Depends(require_key)' },
        { t: 'X-API-Key', m: B('header شائع لمفتاح الـ API', 'a common header for an API key'), ex: 'Header Auth in n8n' },
        { t: 'CORSMiddleware', m: B('بيسمح لصفحات من دومينات معيّنة تقرا ردود الـ API', 'lets pages from given domains read the API’s responses'), ex: 'allow_origins=["https://…"]' },
        { t: 'APIRouter', m: B('مجموعة endpoints في ملف لوحدها بـ prefix', 'a group of endpoints in its own file with a prefix'), ex: 'APIRouter(prefix="/orders")' }
      ],
      read: [{ lib: 'FastAPI documentation', what: B('Handling Errors وDependencies (أول صفحة) وCORS.', 'Handling Errors, Dependencies (first page) and CORS.') }, { lib: 'Requests documentation', what: B('(مراجعة) Custom Headers.', '(review) Custom Headers.') }],
      challenge: B('حوّل API «أدوات النصوص» لخدمة محمية بمفتاح، بـ routers (clean وorders)، وأخطاء بأكواد صح، ومعالج أخطاء عام بيسجّل، وCORS لدومين لوحتك بس — و8 tests بـ TestClient منهم من غير مفتاح وبمفتاح غلط.', 'Turn the «text tools» API into a key-protected service with routers (clean and orders), correct error codes, a logging global error handler and CORS for your dashboard’s domain only — plus 8 TestClient tests including no key and a wrong key.'),
      quiz: [
        { q: B('طلب على طلب مدفوع قبل كده عشان يدفعه تاني:', 'A request to pay an order that is already paid:'), o: ['409', '404', '201'], a: 0, why: B('تعارض.', 'A conflict.') },
        { q: B('`Depends(require_key)` بيتنفّذ:', '`Depends(require_key)` runs:'), o: [B('قبل الـ endpoint في كل طلب', 'before the endpoint on every request'), B('مرة واحدة وقت التشغيل', 'once at start-up'), B('بعد الرد', 'after the response')], a: 0, why: B('dependency.', 'A dependency.') },
        { q: B('ليه compare_digest للمفتاح؟', 'Why compare_digest for the key?'), o: [B('مقارنة بوقت ثابت ضد timing attacks', 'a constant-time comparison against timing attacks'), B('أسرع', 'faster'), B('عشان العربي', 'for Arabic')], a: 0, why: B('أسبوع 13.', 'Week 13.') }
      ] },

    { title: B('n8n وFastAPI مع بعض', 'n8n and FastAPI together'),
      goal: B('تخلي n8n ينادي الـ API بتاعك (HTTP Request)، والـ API يبعت لـ n8n (Webhook)، وتستقبل webhooks موقّعة، وتشغّل مهام في الخلفية، وتمنع التكرار بـ idempotency key.', 'Have n8n call your API (HTTP Request) and your API post to n8n (Webhook), receive signed webhooks, run background tasks, and prevent duplicates with an idempotency key.'),
      learn: [
        { h: B('n8n → API', 'n8n → the API'),
          p: B('في n8n: HTTP Request node، Method POST، URL الـ API، Header Auth، Body JSON بـ expressions (`{{ $json.email }}`)، وفعّل «Batching» لو بتبعت items كتير. لو n8n في Docker وAPI على جهازك: `http://host.docker.internal:8000`. ابعت قايمة items في طلب واحد لما تقدر (endpoint بياخد list) — أسرع بكتير من طلب لكل item.', 'In n8n: an HTTP Request node, Method POST, the API’s URL, Header Auth, a JSON body with expressions (`{{ $json.email }}`), and enable «Batching» when sending many items. If n8n runs in Docker and the API on your machine: `http://host.docker.internal:8000`. Send a list of items in one request when you can (an endpoint taking a list) — much faster than one request per item.'),
          ex: 'from fastapi import FastAPI\nfrom fastapi.testclient import TestClient\nfrom pydantic import BaseModel\n\nclass Contact(BaseModel):\n    name: str\n    email: str\n    phone: str = ""\n\napp = FastAPI()\n\n@app.post("/contacts/clean")\ndef clean_many(contacts: list[Contact]):           # n8n sends all items in one call\n    out = []\n    for c in contacts:\n        email = c.email.strip().lower()\n        out.append({"name": " ".join(c.name.split()).title(), "email": email, "valid": "@" in email and "." in email.split("@")[-1]})\n    return {"count": len(out), "contacts": out}\n\nprint(TestClient(app).post("/contacts/clean", json=[{"name": "  sara  AHMED", "email": " SARA@Mail.com"}, {"name": "omar", "email": "bad"}]).json())' },
        { h: B('API → n8n، وwebhooks موقّعة', 'The API → n8n, and signed webhooks'),
          p: B('العكس: الـ API بعد ما يخلص شغل تقيل يبعت النتيجة لـ n8n Webhook (أسبوع 13) — والأحسن في **BackgroundTasks** عشان يرد على اللي ناداه فورًا. ولو خدمة برّه (Stripe أو متجر) بتبعت webhooks للـ API بتاعك: اقرا الـ body الخام وتحقق من توقيع HMAC قبل أي حاجة.', 'The reverse: after heavy work the API posts the result to an n8n Webhook (week 13) — ideally in **BackgroundTasks** so it answers the caller immediately. If an outside service (Stripe or a shop) sends webhooks to your API: read the raw body and verify the HMAC signature before anything else.'),
          ex: 'import hashlib, hmac, os\nfrom fastapi import BackgroundTasks, FastAPI, Header, HTTPException, Request\nfrom fastapi.testclient import TestClient\n\nSECRET = os.environ.get("SHOP_WEBHOOK_SECRET", "demo-secret")\nsent = []\n\ndef notify_n8n(payload: dict):            # in real code: requests.post(N8N_WEBHOOK_URL, json=payload, timeout=15)\n    sent.append(payload)\n\napp = FastAPI()\n\n@app.post("/webhooks/shop")\nasync def shop_webhook(request: Request, tasks: BackgroundTasks, x_signature: str = Header(default="")):\n    body = await request.body()\n    expected = hmac.new(SECRET.encode(), body, hashlib.sha256).hexdigest()\n    if not hmac.compare_digest(expected, x_signature):\n        raise HTTPException(401, "bad signature")\n    event = await request.json()\n    tasks.add_task(notify_n8n, {"event": event["type"], "order": event["id"]})\n    return {"received": True}\n\nbody = b\'{"type": "order.paid", "id": 991}\'\nsig = hmac.new(SECRET.encode(), body, hashlib.sha256).hexdigest()\nc = TestClient(app)\nprint(c.post("/webhooks/shop", content=body, headers={"X-Signature": sig}).json(), sent)\nprint(c.post("/webhooks/shop", content=body, headers={"X-Signature": "fake"}).status_code)' },
        { h: B('متكررش: idempotency', 'Do not repeat: idempotency'),
          p: B('n8n بيعيد المحاولة لو الطلب فشل (Retry On Fail)، والخدمات بتبعت نفس الـ webhook أكتر من مرة. لو endpoint بيعمل حاجة (يبعت فاتورة، يسجّل دفع)، اطلب `Idempotency-Key` (أو استخدم id الحدث) واحفظ الردود: لو المفتاح اتشاف قبل كده رجّع نفس الرد من غير ما تعمل الشغل تاني.', 'n8n retries failed requests (Retry On Fail), and services send the same webhook more than once. If an endpoint does something (sends an invoice, records a payment), require an `Idempotency-Key` (or use the event id) and store the responses: if a key was seen before, return the same response without doing the work again.'),
          ex: 'from fastapi import FastAPI, Header\nfrom fastapi.testclient import TestClient\n\napp = FastAPI()\nseen: dict[str, dict] = {}       # use SQLite/Redis in production\ninvoices_sent = []\n\n@app.post("/invoices/{order_id}/send")\ndef send_invoice(order_id: int, idempotency_key: str = Header(...)):\n    if idempotency_key in seen:\n        return seen[idempotency_key]           # a retry: same answer, no second email\n    invoices_sent.append(order_id)\n    result = {"order": order_id, "sent": True}\n    seen[idempotency_key] = result\n    return result\n\nc = TestClient(app)\nfor _ in range(3):\n    c.post("/invoices/7/send", headers={"Idempotency-Key": "order-7-invoice"})\nprint("emails actually sent:", len(invoices_sent))' }
      ],
      practice: [
        B('اعمل workflow: Google Sheets (أو Pin Data) → HTTP Request بيبعت كل الصفوف لـ `/contacts/clean` → يكتب النتيجة.', 'Build a workflow: Google Sheets (or Pin Data) → an HTTP Request sending all rows to `/contacts/clean` → write the result back.'),
        B('خلّي endpoint يبعت لـ n8n Webhook في BackgroundTasks، وشوف إن الرد بيرجع فورًا.', 'Make an endpoint post to an n8n Webhook in BackgroundTasks and see that it answers immediately.'),
        B('جرّب webhook بتوقيع صح وغلط.', 'Try a webhook with a correct and a wrong signature.'),
        B('فعّل Retry On Fail في n8n على endpoint بـ idempotency key واتأكد إن مفيش تكرار.', 'Enable Retry On Fail in n8n against an endpoint with an idempotency key and check nothing repeats.')
      ],
      code: [
        { u: B('إعدادات HTTP Request في n8n', 'HTTP Request settings in n8n'), p: 'Method:          POST\nURL:             http://host.docker.internal:8000/contacts/clean\nAuthentication:  Generic Credential Type → Header Auth  (Name: X-API-Key, Value: from the credential)\nSend Body:       JSON\nBody:            {{ $input.all().map(i => i.json) }}      ← all items in one call\nOptions:         Timeout 30000 · Retry On Fail (3 tries, 2 s) · Response: JSON\nHeaders:         Idempotency-Key = {{ $execution.id }}-{{ $itemIndex }}', lang: 'text' }
      ],
      words: [
        { t: 'HTTP Request node', m: B('نود n8n اللي بينادي أي API', 'the n8n node that calls any API'), ex: 'POST /contacts/clean' },
        { t: 'host.docker.internal', m: B('اسم بيوصل من Docker لجهازك', 'a name reaching your machine from inside Docker'), ex: 'http://host.docker.internal:8000' },
        { t: 'BackgroundTasks', m: B('شغل بيتعمل بعد ما الـ API يرد', 'work done after the API has replied'), ex: 'tasks.add_task(notify_n8n, data)' },
        { t: 'raw body', m: B('البايتات الأصلية للطلب قبل التحويل، للتوقيع', 'the request’s original bytes before parsing, for signatures'), ex: 'await request.body()' },
        { t: 'idempotency key', m: B('مفتاح بيخلي تكرار نفس الطلب ميعملش الشغل مرتين', 'a key making a repeated request not do the work twice'), ex: 'Idempotency-Key: order-7-invoice' },
        { t: 'Retry On Fail', m: B('خيار n8n بيعيد النود لو فشل', 'an n8n option that reruns a failed node'), ex: '3 tries, 2 s apart' }
      ],
      read: [{ lib: 'FastAPI documentation', what: B('Background Tasks وRequest Body (Body - Multiple Parameters).', 'Background Tasks and multiple body parameters.') }, { lib: 'Requests documentation', what: B('(مراجعة) POST with JSON.', '(review) POST with JSON.') }],
      challenge: B('اعمل endpoint `POST /reports/monthly` بياخد `month`، ويرد فورًا بـ `{"accepted": true, "job": id}` (202)، ويبني التقرير (مشروع أسبوع 20) في BackgroundTasks، ويبعت النتيجة لـ n8n Webhook — وفي n8n workflow بيستقبلها ويبعت Telegram.', 'Build `POST /reports/monthly` taking `month`, answering immediately with `{"accepted": true, "job": id}` (202), building the report (the week 20 project) in BackgroundTasks and posting the result to an n8n Webhook — with an n8n workflow that receives it and sends Telegram.'),
      quiz: [
        { q: B('n8n في Docker ينادي API على جهازك:', 'n8n in Docker calling an API on your machine:'), o: ['http://host.docker.internal:8000', 'http://localhost:8000', 'http://0.0.0.0'], a: 0, why: B('localhost جوه الـ container هو الـ container نفسه.', 'localhost inside the container is the container itself.') },
        { q: B('توقيع webhook بيتحسب على:', 'A webhook signature is computed over:'), o: [B('الـ body الخام', 'the raw body'), B('الـ JSON بعد التحويل', 'the parsed JSON'), B('الـ URL', 'the URL')], a: 0, why: B('أي تغيير في المسافات بيغيّره.', 'Any whitespace change alters it.') },
        { q: B('نفس الطلب اتبعت 3 مرات بنفس Idempotency-Key:', 'The same request sent 3 times with the same Idempotency-Key:'), o: [B('الشغل يتعمل مرة واحدة', 'the work happens once'), B('3 مرات', '3 times'), B('ولا مرة', 'never')], a: 0, why: B('الرد المحفوظ.', 'The stored response.') }
      ] },

    { title: B('API بقاعدة بيانات واختبارات', 'An API with a database and tests'),
      goal: B('تعمل CRUD كامل على SQLite (أسبوع 18) بـ dependency للاتصال، وتفهم async def امتى، وتكتب اختبارات بـ pytest وTestClient على قاعدة مؤقتة.', 'Build full CRUD on SQLite (week 18) with a connection dependency, understand when to use async def, and write tests with pytest and TestClient on a temporary database.'),
      learn: [
        { h: B('CRUD على SQLite', 'CRUD on SQLite'),
          p: B('Create وRead وUpdate وDelete: `POST /expenses` و`GET /expenses` و`GET /expenses/{id}` و`PATCH /expenses/{id}` و`DELETE /expenses/{id}`. dependency بترجّع اتصال لكل طلب وتقفله بعده (`yield`). كل الاستعلامات بـ parameters (أسبوع 18) — الـ API على النت يعني أي حد يقدر يجرّب injection.', 'Create, Read, Update and Delete: `POST /expenses`, `GET /expenses`, `GET /expenses/{id}`, `PATCH /expenses/{id}` and `DELETE /expenses/{id}`. A dependency yields a connection per request and closes it afterwards (`yield`). Every query uses parameters (week 18) — an API on the internet means anyone can try injection.'),
          ex: 'import sqlite3\nfrom fastapi import Depends, FastAPI, HTTPException\nfrom fastapi.testclient import TestClient\nfrom pydantic import BaseModel, Field\n\nDB_PATH = "expenses.db"\n\ndef get_db():\n    db = sqlite3.connect(DB_PATH, check_same_thread=False)\n    db.row_factory = sqlite3.Row\n    try:\n        yield db\n    finally:\n        db.close()\n\nclass ExpenseIn(BaseModel):\n    category: str\n    amount: float = Field(gt=0)\n\napp = FastAPI()\nwith sqlite3.connect(DB_PATH) as db:\n    db.execute("CREATE TABLE IF NOT EXISTS expenses (id INTEGER PRIMARY KEY, category TEXT, amount REAL)")\n\n@app.post("/expenses", status_code=201)\ndef create(e: ExpenseIn, db=Depends(get_db)):\n    with db:\n        cur = db.execute("INSERT INTO expenses (category, amount) VALUES (?, ?)", (e.category, e.amount))\n    return {"id": cur.lastrowid, **e.model_dump()}\n\n@app.get("/expenses/{eid}")\ndef read(eid: int, db=Depends(get_db)):\n    row = db.execute("SELECT * FROM expenses WHERE id = ?", (eid,)).fetchone()\n    if row is None:\n        raise HTTPException(404, "expense not found")\n    return dict(row)\n\nc = TestClient(app)\nnew = c.post("/expenses", json={"category": "food", "amount": 120.5}).json()\nprint(new, c.get(f"/expenses/{new[\'id\']}").json(), c.get("/expenses/9999").status_code)' },
        { h: B('async def امتى؟', 'When async def?'),
          p: B('FastAPI بيقبل `def` و`async def`. استخدم `async def` لما جوه الـ endpoint بتستنى حاجات async (زي `httpx.AsyncClient` اللي بينادي APIs تانية) — كده السيرفر يخدم طلبات تانية وهو مستني. لو الكود sync عادي (sqlite3 وpandas) سيبه `def` وFastAPI بيشغّله في thread لوحده. الغلطة الأخطر: كود sync بطيء جوه `async def` بيوقف السيرفر كله.', 'FastAPI accepts `def` and `async def`. Use `async def` when the endpoint awaits async things (like `httpx.AsyncClient` calling other APIs) — the server keeps serving others while it waits. For ordinary sync code (sqlite3, pandas) keep `def`, and FastAPI runs it in a thread for you. The worst mistake: slow sync code inside `async def`, which freezes the whole server.'),
          ex: 'import asyncio, time\n\nasync def fake_api(n):          # stands in for: await client.get(url)\n    await asyncio.sleep(1)\n    return n * 10\n\nasync def main():\n    t = time.perf_counter()\n    results = await asyncio.gather(*(fake_api(n) for n in range(5)))   # 5 calls at the same time\n    print(results, f"{time.perf_counter() - t:.1f}s instead of 5s")\n\nasyncio.run(main())', run: 1 },
        { h: B('اختبارات بـ pytest', 'Tests with pytest'),
          p: B('ملف `test_api.py` فيه دوال بتبدأ بـ `test_`، و`pytest` بيلاقيهم ويشغّلهم (بالتفصيل الأسبوع الجاي). استخدم fixture بتعمل قاعدة مؤقتة لكل اختبار و`app.dependency_overrides[get_db]` يبدّل القاعدة الحقيقية بيها — كده الاختبارات متلمسش بياناتك أبدًا.', 'A `test_api.py` file holds functions starting with `test_`, and `pytest` finds and runs them (in depth next week). Use a fixture creating a temporary database per test and `app.dependency_overrides[get_db]` to swap the real database for it — so tests never touch your data.'),
          ex: '# test_api.py — run with:  pytest -q\nimport sqlite3\nimport pytest\nfrom fastapi.testclient import TestClient\nfrom main import app, get_db\n\n@pytest.fixture\ndef client(tmp_path):\n    path = tmp_path / "test.db"\n    with sqlite3.connect(path) as db:\n        db.execute("CREATE TABLE expenses (id INTEGER PRIMARY KEY, category TEXT, amount REAL)")\n    def test_db():\n        db = sqlite3.connect(path, check_same_thread=False)\n        db.row_factory = sqlite3.Row\n        try:\n            yield db\n        finally:\n            db.close()\n    app.dependency_overrides[get_db] = test_db\n    yield TestClient(app)\n    app.dependency_overrides.clear()\n\ndef test_create_and_read(client):\n    new = client.post("/expenses", json={"category": "food", "amount": 50}).json()\n    assert client.get(f"/expenses/{new[\'id\']}").json()["amount"] == 50\n\ndef test_rejects_negative(client):\n    assert client.post("/expenses", json={"category": "food", "amount": -5}).status_code == 422\n\ndef test_missing_is_404(client):\n    assert client.get("/expenses/123").status_code == 404', lang: 'text' }
      ],
      practice: [
        B('كمّل الـ CRUD: list بفلاتر (category وfrom/to) وPATCH وDELETE.', 'Complete the CRUD: a list with filters (category and from/to), PATCH and DELETE.'),
        B('شغّل مثال asyncio.gather وغيّر العدد لـ 20 وشوف الوقت.', 'Run the asyncio.gather example and change the count to 20 to see the time.'),
        B('اكتب 6 اختبارات pytest بقاعدة مؤقتة وشغّلها.', 'Write 6 pytest tests with a temporary database and run them.'),
        B('جرّب SQL injection في query parameter على الـ API واتأكد إنها مبتشتغلش.', 'Try SQL injection through a query parameter on the API and confirm it fails.')
      ],
      code: [
        { u: B('list بفلاتر وصفحات', 'A list with filters and pages'), p: 'from fastapi import Depends, Query\n\n@app.get("/expenses")\ndef list_expenses(category: str | None = None, min_amount: float = 0,\n                  limit: int = Query(50, le=200), offset: int = 0, db=Depends(get_db)):\n    sql, params = "SELECT * FROM expenses WHERE amount >= ?", [min_amount]\n    if category:\n        sql += " AND category = ?"\n        params.append(category)\n    sql += " ORDER BY id DESC LIMIT ? OFFSET ?"\n    params += [limit, offset]\n    rows = [dict(r) for r in db.execute(sql, params)]\n    return {"count": len(rows), "items": rows, "next_offset": offset + limit if len(rows) == limit else None}', lang: 'text' }
      ],
      words: [
        { t: 'CRUD', m: B('الأربع عمليات: إنشاء وقراءة وتعديل ومسح', 'the four operations: create, read, update and delete'), ex: 'POST, GET, PATCH, DELETE' },
        { t: 'yield dependency', m: B('dependency بتجهّز حاجة وتقفلها بعد الطلب', 'a dependency that prepares something and closes it after the request'), ex: 'def get_db(): … yield db … finally: db.close()' },
        { t: 'async def', m: B('دالة async بتستنى من غير ما توقف البرنامج', 'an async function that waits without blocking the program'), ex: 'async def fetch(): await client.get(url)' },
        { t: 'asyncio.gather', m: B('بيشغّل كذا عملية async في نفس الوقت', 'runs several async operations at the same time'), ex: 'await asyncio.gather(*tasks)' },
        { t: 'pytest fixture', m: B('دالة بتجهّز حاجة للاختبار (قاعدة مؤقتة مثلًا)', 'a function preparing something for a test (a temporary database, say)'), ex: '@pytest.fixture' },
        { t: 'dependency override', m: B('تبديل dependency بنسخة اختبار', 'swapping a dependency for a test version'), ex: 'app.dependency_overrides[get_db] = test_db' }
      ],
      read: [{ lib: 'FastAPI documentation', what: B('Dependencies with yield وTesting وConcurrency and async / await.', 'Dependencies with yield, Testing, and Concurrency and async / await.') }, { lib: 'pytest documentation', what: B('Get Started بس.', 'Just Get Started.') }],
      challenge: B('اعمل API المصاريف كامل (CRUD + `/expenses/summary?month=` بيرجّع المجموع لكل فئة بـ SQL) بمفتاح وroutes وPydantic، و10 اختبارات pytest بقاعدة مؤقتة كلها بتعدّي.', 'Build the full expenses API (CRUD + `/expenses/summary?month=` returning totals per category with SQL) with a key, routers and Pydantic, plus 10 pytest tests on a temporary database, all passing.'),
      quiz: [
        { q: B('endpoint بينادي 5 APIs تانية، الأحسن:', 'An endpoint calling 5 other APIs is best as:'), o: [B('async def مع httpx.AsyncClient وgather', 'async def with httpx.AsyncClient and gather'), B('def مع requests في لوب', 'def with requests in a loop'), B('async def مع requests', 'async def with requests')], a: 0, why: B('بالتوازي ومن غير ما يوقف السيرفر.', 'Concurrent, without blocking the server.') },
        { q: B('`app.dependency_overrides` بيفيد في:', '`app.dependency_overrides` is for:'), o: [B('تبديل القاعدة الحقيقية في الاختبارات', 'swapping the real database in tests'), B('السرعة', 'speed'), B('الأمان', 'security')], a: 0, why: B('اختبارات معزولة.', 'Isolated tests.') },
        { q: B('PATCH غالبًا معناها:', 'PATCH usually means:'), o: [B('تعديل جزء من سجل', 'updating part of a record'), B('مسح', 'deleting'), B('قراءة', 'reading')], a: 0, why: B('PUT للسجل كله.', 'PUT replaces the whole record.') }
      ] },

    { title: B('مراجعة ومشروع واختبار الأسبوع', 'Review, project and weekly test'),
      goal: B('تبني خدمة أدوات Python محمية ومختبرة بيستخدمها n8n، وتعدّي الاختبار.', 'Build a protected, tested Python tools service used by n8n, and pass the test.'),
      review: [
        B('FastAPI: path وquery، والتحويل والتحقق من الأنواع، و/docs، وTestClient.', 'FastAPI: path and query, type conversion and validation, /docs and TestClient.'),
        B('Pydantic: موديلات وField وLiteral و422 وresponse_model وmodel_validate.', 'Pydantic: models, Field, Literal, 422, response_model and model_validate.'),
        B('HTTPException وأكواد الحالة، والمفتاح بـ Depends، وCORS، وrouters.', 'HTTPException and status codes, the key through Depends, CORS and routers.'),
        B('n8n ↔ API: HTTP Request وHeader Auth، وwebhooks موقّعة، وBackgroundTasks، وidempotency.', 'n8n ↔ API: HTTP Request and Header Auth, signed webhooks, BackgroundTasks and idempotency.'),
        B('CRUD على SQLite بـ yield dependency، وasync امتى، وpytest بقاعدة مؤقتة.', 'CRUD on SQLite with a yield dependency, when to use async, and pytest with a temporary database.')
      ],
      project: B('**خدمة أدوات Python لـ n8n** (`tools_api/`): API بـ FastAPI محمي بـ X-API-Key، فيه routers: `/clean` (phone وemail وname وbatch لقايمة)، و`/invoices` (preview بـ Pydantic، وpdf بيرجّع ملف الفاتورة من مشروع أسبوع 12 بـ `FileResponse`، وsend بـ idempotency key)، و`/reports/monthly` (202 + BackgroundTasks + بيبعت لـ n8n Webhook)، و`/webhooks/shop` (توقيع HMAC). معالج أخطاء عام بلوج، وCORS لدومين واحد، و`.env.example`، و15 اختبار pytest. في n8n: workflow «طلب جديد» بيستخدم 3 endpoints (clean ثم invoices/pdf ثم send) بـ Retry On Fail. README فيه لقطة من /docs وخطوات التشغيل.', '**A Python tools service for n8n** (`tools_api/`): a FastAPI API protected by X-API-Key with routers: `/clean` (phone, email, name and batch for a list), `/invoices` (preview with Pydantic, pdf returning the invoice file from the week 12 project via `FileResponse`, and send with an idempotency key), `/reports/monthly` (202 + BackgroundTasks + posts to an n8n Webhook) and `/webhooks/shop` (HMAC signature). A logging global error handler, CORS for one domain, a `.env.example` and 15 pytest tests. In n8n: a «new order» workflow using 3 endpoints (clean, then invoices/pdf, then send) with Retry On Fail. A README with a /docs screenshot and run steps.'),
      test: [
        { q: B('`@app.get("/users/{uid}")` الـ uid بييجي من:', 'In `@app.get("/users/{uid}")` uid comes from:'), o: [B('المسار', 'the path'), B('الـ body', 'the body'), B('الـ header', 'the header')], a: 0, why: B('path parameter.', 'A path parameter.') },
        { q: B('الدالة بترجّع dict، FastAPI بيرجّعه:', 'The function returns a dict; FastAPI sends it as:'), o: ['JSON', 'HTML', B('نص Python', 'Python text')], a: 0, why: B('تلقائي.', 'Automatically.') },
        { q: B('`class X(BaseModel)` في POST endpoint معناها:', '`class X(BaseModel)` in a POST endpoint means:'), o: [B('الـ body JSON بيتحقق ويتحول لـ X', 'the JSON body is validated and converted into X'), B('query', 'a query'), B('header', 'a header')], a: 0, why: B('request body.', 'The request body.') },
        { q: B('حقل إجباري ناقص في الطلب:', 'A required field missing from the request:'), o: ['422', '500', '201'], a: 0, why: B('validation.', 'Validation.') },
        { q: B('لحماية كل endpoints التطبيق بمفتاح:', 'To protect every endpoint with a key:'), o: ['FastAPI(dependencies=[Depends(require_key)])', B('if في كل دالة', 'an if in every function'), 'CORS'], a: 0, why: B('dependency عامة.', 'A global dependency.') },
        { q: B('CORS بيتحكم في:', 'CORS controls:'), o: [B('صفحات أنهي دومينات تقرا الردود', 'which domains’ pages may read the responses'), B('سرعة الـ API', 'the API’s speed'), B('المفاتيح', 'the keys')], a: 0, why: B('للمتصفح.', 'For browsers.') },
        { q: B('شغل تقيل بعد ما الـ API يرد:', 'Heavy work after the API replies:'), o: ['BackgroundTasks', 'response_model', 'Depends'], a: 0, why: B('في الخلفية.', 'In the background.') },
        { q: B('202 Accepted معناها:', '202 Accepted means:'), o: [B('اتقبل وهيتعمل بعدين', 'accepted, it will be done later'), B('خلص', 'done'), B('اترفض', 'refused')], a: 0, why: B('شغل في الخلفية.', 'Background work.') },
        { q: B('n8n بيعيد طلب «ابعت الفاتورة» بعد timeout:', 'n8n retries a «send the invoice» request after a timeout:'), o: [B('idempotency key يمنع التكرار', 'an idempotency key prevents a duplicate'), B('هتتبعت مرتين وخلاص', 'it is sent twice, fine'), B('n8n مبيعيدش', 'n8n never retries')], a: 0, why: B('Retry On Fail.', 'Retry On Fail.') },
        { q: B('كود sync بطيء جوه async def:', 'Slow sync code inside async def:'), o: [B('بيوقف السيرفر كله', 'blocks the whole server'), B('أسرع', 'is faster'), B('عادي', 'is fine')], a: 0, why: B('خليه def.', 'Keep it def.') },
        { q: B('الاختبارات متلمسش قاعدتك الحقيقية بـ:', 'Tests avoid your real database with:'), o: [B('dependency_overrides + قاعدة مؤقتة', 'dependency_overrides + a temporary database'), 'try/except', 'response_model'], a: 0, why: B('عزل.', 'Isolation.') },
        { q: B('مكان مفتاح الـ API في n8n:', 'Where the API key lives in n8n:'), o: [B('Credential (Header Auth)', 'a credential (Header Auth)'), B('جوه الـ URL', 'in the URL'), B('في Code node', 'in a Code node')], a: 0, why: B('مخزن الأسرار.', 'The secret store.') }
      ] }
  ]
};
