// Python week 24 — Deployment and the capstone project.
const B = (ar, en) => ({ ar, en });
module.exports = {
  level: B('محترف', 'Professional'),
  title: B('النشر ومشروع التخرج', 'Deployment and the capstone project'),
  goal: B('تشغّل شغلك في الإنتاج: تحط تطبيق Python في Docker، وتشغّله مع n8n وPostgres بـ docker compose، وتنشره على سيرفر بـ HTTPS، وتخلي GitHub Actions يختبر وينشر لوحده، وتجهّز portfolio وعروض شغل حر — وتختم الرحلة بمشروع تخرج كامل.',
          'Run your work in production: put a Python app in Docker, run it with n8n and Postgres using docker compose, deploy it to a server with HTTPS, let GitHub Actions test and deploy by itself, and prepare a portfolio and freelance offers — then finish the journey with a complete capstone project.'),
  days: [
    { title: B('Docker لتطبيق Python', 'Docker for a Python app'),
      goal: B('تكتب Dockerfile لتطبيق Python (FastAPI)، وتبني image وتشغّل container، وتمرّر الإعدادات والأسرار بمتغيرات البيئة، وتحفظ البيانات في volume.', 'Write a Dockerfile for a Python (FastAPI) app, build an image and run a container, pass settings and secrets through environment variables, and keep data in a volume.'),
      learn: [
        { h: B('ليه Docker؟', 'Why Docker?'),
          p: B('«شغال على جهازي» مش كفاية: السيرفر فيه إصدار Python تاني وحزم تانية. Docker بيحط تطبيقك وPython والحزم كلها في **image** واحدة بتشتغل نفس الشكل في أي مكان. الـ **container** هو نسخة شغالة من الـ image. ونفس الطريقة اللي n8n نفسه بيتنشر بيها (رحلة n8n أسبوع 21).', '«It works on my machine» is not enough: the server has another Python version and other packages. Docker packs your app, Python and every package into one **image** that runs the same everywhere. A **container** is a running copy of the image. It is the same way n8n itself is deployed (n8n journey, week 21).'),
          ex: '# Dockerfile\nFROM python:3.12-slim\n\nENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1\nWORKDIR /app\n\n# dependencies first: this layer is cached until requirements.txt changes\nCOPY requirements.txt .\nRUN pip install --no-cache-dir -r requirements.txt\n\nCOPY app/ ./app/\n\n# do not run as root\nRUN useradd --create-home appuser\nUSER appuser\n\nEXPOSE 8000\nCMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]', lang: 'text' },
        { h: B('build وrun', 'build and run'),
          p: B('`docker build -t tools-api:1.0 .` بيبني الـ image، و`docker run` بيشغّلها: `-p 8000:8000` يوصّل البورت، `--env-file .env` الأسرار (مش جوه الـ image أبدًا)، `-v` يحفظ البيانات برّه الـ container (لأن الـ container لما يتمسح كل اللي جواه بيتمسح)، و`-d` في الخلفية. و`.dockerignore` يمنع `.venv` و`.env` من الدخول في الـ image.', '`docker build -t tools-api:1.0 .` builds the image and `docker run` starts it: `-p 8000:8000` maps the port, `--env-file .env` passes the secrets (never baked into the image), `-v` keeps data outside the container (because deleting a container deletes everything inside it), and `-d` runs it in the background. A `.dockerignore` keeps `.venv` and `.env` out of the image.'),
          ex: '# .dockerignore\n.venv/\n.env\n__pycache__/\n.git/\ntests/\n*.db\n\n# build and run\ndocker build -t tools-api:1.0 .\ndocker run -d --name tools-api -p 8000:8000 --env-file .env -v tools-data:/app/data tools-api:1.0\ndocker ps\ndocker logs -f tools-api\ncurl http://localhost:8000/docs\ndocker stop tools-api && docker rm tools-api', lang: 'text' },
        { h: B('الإعدادات من البيئة', 'Settings from the environment'),
          p: B('التطبيق جوه Docker بياخد كل إعداداته من متغيرات البيئة (أسبوع 7 و twelve-factor): مسار القاعدة، والمفاتيح، ومستوى اللوج. اكتب كلاس إعدادات واحد بيقراهم ويفشل بوضوح لو حاجة إجبارية ناقصة — أحسن من ما يقع بعد ساعة. واللوج للـ stdout (مش ملف) عشان `docker logs` يشوفه.', 'An app inside Docker takes all its settings from environment variables (week 7 and twelve-factor): the database path, the keys and the log level. Write one settings class that reads them and fails clearly when something required is missing — better than crashing an hour later. Log to stdout (not a file) so `docker logs` sees it.'),
          ex: 'import logging, os, sys\nfrom dataclasses import dataclass\n\n@dataclass(frozen=True)\nclass Settings:\n    api_key: str\n    database_url: str = "sqlite:///data/app.db"\n    log_level: str = "INFO"\n\n    @classmethod\n    def from_env(cls, env=os.environ) -> "Settings":\n        missing = [name for name in ("TOOLS_API_KEY",) if not env.get(name)]\n        if missing:\n            sys.exit(f"missing required settings: {\', \'.join(missing)}")\n        return cls(api_key=env["TOOLS_API_KEY"], database_url=env.get("DATABASE_URL", cls.database_url), log_level=env.get("LOG_LEVEL", cls.log_level))\n\nsettings = Settings.from_env({"TOOLS_API_KEY": "demo-key", "LOG_LEVEL": "DEBUG"})\nlogging.basicConfig(stream=sys.stdout, level=settings.log_level, format="%(asctime)s %(levelname)s %(message)s")\nlogging.info("starting with %s", settings.database_url)', run: 1 }
      ],
      practice: [
        B('ثبّت Docker Desktop واكتب Dockerfile وdockerignore لـ tools_api (أسبوع 21).', 'Install Docker Desktop and write a Dockerfile and .dockerignore for tools_api (week 21).'),
        B('ابني الـ image وشغّلها وافتح /docs.', 'Build the image, run it and open /docs.'),
        B('امسح الـ container وشغّله تاني واتأكد إن البيانات فضلت بفضل الـ volume.', 'Delete the container, start it again and check the data survived thanks to the volume.'),
        B('شغّل `docker image ls` وشوف حجم الـ image، وجرّب تصغّره.', 'Run `docker image ls`, look at the image size and try to shrink it.')
      ],
      code: [
        { u: B('healthcheck للـ API', 'A healthcheck for the API'), p: '# in app/main.py\n@app.get("/health")\ndef health():\n    return {"status": "ok"}\n\n# in the Dockerfile\nHEALTHCHECK --interval=30s --timeout=5s --retries=3 \\\n  CMD python -c "import urllib.request; urllib.request.urlopen(\'http://localhost:8000/health\', timeout=4)"', lang: 'text' }
      ],
      words: [
        { t: 'Docker', m: B('أداة بتحط التطبيق ومتطلباته في حاوية بتشتغل في أي مكان', 'a tool packing an app and its needs into a container that runs anywhere'), ex: 'docker run …' },
        { t: 'Dockerfile', m: B('ملف بخطوات بناء الـ image', 'a file with the steps to build an image'), ex: 'FROM python:3.12-slim' },
        { t: 'image', m: B('قالب جاهز فيه التطبيق وكل اللي محتاجه', 'a ready template holding the app and everything it needs'), ex: 'tools-api:1.0' },
        { t: 'container', m: B('نسخة شغالة من image', 'a running copy of an image'), ex: 'docker ps' },
        { t: 'volume', m: B('مكان تخزين بيفضل بعد ما الـ container يتمسح', 'storage that survives when the container is deleted'), ex: '-v tools-data:/app/data' },
        { t: 'port mapping', m: B('توصيل بورت الجهاز ببورت الـ container', 'linking a host port to a container port'), ex: '-p 8000:8000' },
        { t: '.dockerignore', m: B('ملف بيمنع ملفات معيّنة من دخول الـ image', 'a file keeping certain files out of the image'), ex: '.venv/ .env' }
      ],
      read: [{ lib: 'Docker: Python language guide', what: B('Containerize your app وDevelop your app.', 'Containerize your app and Develop your app.') }, { lib: 'The Twelve-Factor App', what: B('(مراجعة) III. Config وXI. Logs.', '(review) III. Config and XI. Logs.') }],
      challenge: B('اعمل image لمراقب الأسعار (أسبوع 16) بيشتغل كأمر واحد (`docker run --rm price-watch`) والـ snapshots في volume، وقيس حجم الـ image، وخليه أقل من 250 ميجا.', 'Build an image for the price watcher (week 16) that runs as one command (`docker run --rm price-watch`) with the snapshots in a volume, measure the image size and keep it under 250 MB.'),
      quiz: [
        { q: B('الأسرار في Docker تتحط:', 'Secrets in Docker go:'), o: [B('في متغيرات بيئة وقت التشغيل (--env-file)', 'in run-time environment variables (--env-file)'), B('جوه الـ image', 'inside the image'), B('في الـ Dockerfile', 'in the Dockerfile')], a: 0, why: B('الـ image ممكن تتشارك.', 'Images can be shared.') },
        { q: B('container اتمسح والبيانات اتمسحت. الحل:', 'A container was deleted with its data. The fix:'), o: ['volume', 'EXPOSE', 'CMD'], a: 0, why: B('تخزين برّه الـ container.', 'Storage outside the container.') },
        { q: B('ليه COPY requirements.txt قبل الكود؟', 'Why COPY requirements.txt before the code?'), o: [B('الـ layer دي تتخزن ومتتعادش غير لو المتطلبات اتغيرت', 'the layer is cached until requirements change'), B('ترتيب أبجدي', 'alphabetical order'), B('مطلوب', 'it is required')], a: 0, why: B('build أسرع.', 'Faster builds.') }
      ] },

    { title: B('docker compose: API وn8n وPostgres', 'docker compose: the API, n8n and Postgres'),
      goal: B('تشغّل أكتر من خدمة مع بعض بملف compose واحد: الـ API بتاعك وn8n وPostgres، بشبكة مشتركة وvolumes وhealthchecks وrestart، والأسرار من .env.', 'Run several services together from one compose file: your API, n8n and Postgres, with a shared network, volumes, healthchecks and restart policies, and secrets from .env.'),
      learn: [
        { h: B('ملف compose', 'A compose file'),
          p: B('`compose.yaml` بيوصف كل الخدمات: الـ image أو build، والبورتات، ومتغيرات البيئة، والـ volumes. `docker compose up -d` بيشغّلهم كلهم، و`docker compose logs -f api` لوج خدمة، و`down` يوقّفهم. الخدمات بتشوف بعض بأساميها: n8n بينادي الـ API على `http://api:8000` (مش localhost).', '`compose.yaml` describes every service: the image or build, ports, environment variables and volumes. `docker compose up -d` starts them all, `docker compose logs -f api` shows one service’s log, and `down` stops them. Services reach each other by name: n8n calls the API at `http://api:8000` (not localhost).'),
          ex: '# compose.yaml\nservices:\n  api:\n    build: .\n    env_file: .env\n    volumes: ["api-data:/app/data"]\n    restart: unless-stopped\n    healthcheck:\n      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen(\'http://localhost:8000/health\')"]\n      interval: 30s\n\n  postgres:\n    image: postgres:16\n    environment:\n      POSTGRES_USER: n8n\n      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}\n      POSTGRES_DB: n8n\n    volumes: ["pg-data:/var/lib/postgresql/data"]\n    restart: unless-stopped\n    healthcheck:\n      test: ["CMD-SHELL", "pg_isready -U n8n"]\n      interval: 10s\n\n  n8n:\n    image: docker.n8n.io/n8nio/n8n\n    ports: ["5678:5678"]\n    environment:\n      DB_TYPE: postgresdb\n      DB_POSTGRESDB_HOST: postgres\n      DB_POSTGRESDB_USER: n8n\n      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}\n      GENERIC_TIMEZONE: Africa/Cairo\n      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}\n    volumes: ["n8n-data:/home/node/.n8n"]\n    depends_on:\n      postgres: { condition: service_healthy }\n    restart: unless-stopped\n\nvolumes: { api-data: {}, pg-data: {}, n8n-data: {} }', lang: 'text' },
        { h: B('الشبكة والأسرار', 'The network and secrets'),
          p: B('compose بيعمل شبكة داخلية: Postgres مش محتاج بورت مفتوح للعالم — n8n بيوصله جوه الشبكة. افتح للعالم اللي لازم بس (n8n، أو الـ API ورا reverse proxy). القيم زي `${POSTGRES_PASSWORD}` بتيجي من ملف `.env` جنب compose.yaml (اللي مبيترفعش على Git)، و`N8N_ENCRYPTION_KEY` احفظه في مكان آمن: من غيره credentials n8n متتفكش لو نقلت السيرفر.', 'compose creates an internal network: Postgres needs no port open to the world — n8n reaches it inside the network. Expose only what must be public (n8n, or the API behind a reverse proxy). Values like `${POSTGRES_PASSWORD}` come from a `.env` file next to compose.yaml (never committed), and keep `N8N_ENCRYPTION_KEY` somewhere safe: without it n8n’s credentials cannot be decrypted if you move servers.'),
          ex: '# .env  (next to compose.yaml, never committed)\nPOSTGRES_PASSWORD=change-me-long-random\nN8N_ENCRYPTION_KEY=change-me-long-random-and-back-it-up\nTOOLS_API_KEY=change-me\n\n# generate random values:\npython -c "import secrets; print(secrets.token_urlsafe(32))"\n\n# useful commands\ndocker compose up -d\ndocker compose ps\ndocker compose logs -f n8n\ndocker compose exec postgres psql -U n8n -c "\\dt"\ndocker compose pull && docker compose up -d      # update images', lang: 'text' },
        { h: B('النسخ الاحتياطي', 'Backups'),
          p: B('الـ volumes هي بياناتك: اعمل نسخة احتياطية منها بانتظام وجرّب ترجّعها (نسخة متجرّبتش = مفيش نسخة). لـ Postgres: `pg_dump` لملف بالتاريخ، واحتفظ بآخر 14 مثلًا، وانقل نسخة لمكان تاني (S3 أو Drive). وصدّر workflows n8n وcredentials (مشفرة) بالـ CLI. سكربت أسبوع 9 + جدولة أسبوع 20 = نسخ احتياطي أوتوماتيك.', 'Volumes are your data: back them up regularly and test restoring (an untested backup is no backup). For Postgres: `pg_dump` to a dated file, keep the last 14, say, and copy one off the server (S3 or Drive). Export n8n workflows and (encrypted) credentials with its CLI. The week 9 script + week 20 scheduling = automatic backups.'),
          ex: '#!/bin/sh\n# backup.sh — run daily by cron\nset -e\nSTAMP=$(date +%Y-%m-%d_%H%M)\nmkdir -p /srv/backups\ndocker compose exec -T postgres pg_dump -U n8n n8n | gzip > /srv/backups/n8n_$STAMP.sql.gz\ndocker compose exec -T n8n n8n export:workflow --all --output=/home/node/.n8n/backup_workflows.json\nls -1t /srv/backups/n8n_*.sql.gz | tail -n +15 | xargs -r rm\n\n# restore test (on another machine):\n# gunzip -c n8n_2026-10-01_0200.sql.gz | docker compose exec -T postgres psql -U n8n n8n', lang: 'text' }
      ],
      practice: [
        B('شغّل compose فيه tools_api وn8n وPostgres على جهازك.', 'Run a compose file with tools_api, n8n and Postgres on your machine.'),
        B('من n8n، اعمل HTTP Request لـ `http://api:8000/health` (باسم الخدمة).', 'From n8n, make an HTTP Request to `http://api:8000/health` (by service name).'),
        B('اعمل pg_dump ورجّعه في Postgres جديد واتأكد إن الـ workflows موجودة.', 'Run pg_dump and restore it into a fresh Postgres, checking the workflows are there.'),
        B('اقفل compose وافتحه تاني واتأكد إن مفيش بيانات ضاعت.', 'Stop compose, start it again and check no data was lost.')
      ],
      code: [
        { u: B('خدمة worker بتشغّل جدولة', 'A worker service running a schedule'), p: '  # add to compose.yaml: the monthly report runs inside its own container\n  report-worker:\n    build: .\n    command: ["python", "-m", "app.scheduler"]      # uses the schedule library (week 20)\n    env_file: .env\n    volumes: ["api-data:/app/data"]\n    depends_on: [api]\n    restart: unless-stopped', lang: 'text' }
      ],
      words: [
        { t: 'docker compose', m: B('أداة تشغّل أكتر من container مع بعض من ملف واحد', 'a tool running several containers together from one file'), ex: 'docker compose up -d' },
        { t: 'service', m: B('خدمة واحدة في ملف compose (api أو n8n أو postgres)', 'one service in a compose file (api, n8n or postgres)'), ex: 'services: api: …' },
        { t: 'restart policy', m: B('بيحدد الـ container يرجع يشتغل لوحده امتى', 'decides when a container restarts by itself'), ex: 'restart: unless-stopped' },
        { t: 'healthcheck', m: B('فحص دوري بيقول الخدمة سليمة ولا لأ', 'a periodic check telling whether a service is healthy'), ex: 'pg_isready -U n8n' },
        { t: 'pg_dump', m: B('أداة بتطلّع نسخة احتياطية من Postgres', 'the tool that backs up Postgres'), ex: 'pg_dump -U n8n n8n | gzip' },
        { t: 'encryption key', m: B('المفتاح اللي n8n بيشفّر بيه الـ credentials', 'the key n8n encrypts credentials with'), ex: 'N8N_ENCRYPTION_KEY' }
      ],
      read: [{ lib: 'Docker: Python language guide', what: B('جزء Use containers for development (compose).', 'The Use containers for development part (compose).') },
        { t: B('n8n Docs: Docker Compose', 'n8n Docs: Docker Compose'), url: 'https://docs.n8n.io/hosting/installation/server-setups/docker-compose/', what: B('اقرا الصفحة كلها وقارنها بالـ compose بتاعك.', 'Read the whole page and compare it with your compose file.') }],
      challenge: B('اعمل `compose.yaml` كامل لمشروعك (api وworker وn8n وpostgres) بـ healthchecks وrestart وvolumes وشبكة داخلية، و`backup.sh` بيتشغّل بـ cron، وREADME بخطوات التشغيل من الصفر والاسترجاع من نسخة.', 'Write a complete `compose.yaml` for your project (api, worker, n8n and postgres) with healthchecks, restart, volumes and an internal network, plus a cron-run `backup.sh` and a README with from-scratch setup and restore steps.'),
      quiz: [
        { q: B('n8n في compose بينادي الـ API على:', 'n8n in compose calls the API at:'), o: ['http://api:8000', 'http://localhost:8000', 'http://127.0.0.1:8000'], a: 0, why: B('باسم الخدمة جوه الشبكة.', 'By service name inside the network.') },
        { q: B('Postgres محتاج بورت مفتوح للنت؟', 'Does Postgres need a port open to the internet?'), o: [B('لأ؛ الخدمات بتوصله جوه الشبكة', 'no; services reach it inside the network'), B('أيوه دايمًا', 'yes, always'), B('لو n8n شغال', 'if n8n runs')], a: 0, why: B('أقل مساحة هجوم.', 'A smaller attack surface.') },
        { q: B('نسخة احتياطية عمرك ما جربت ترجّعها:', 'A backup you never tried restoring:'), o: [B('غالبًا مش هتنفع وقت الحاجة', 'will probably fail when you need it'), B('آمنة تمامًا', 'is perfectly safe'), B('مش مهمة', 'does not matter')], a: 0, why: B('اختبر الاسترجاع.', 'Test the restore.') }
      ] },

    { title: B('النشر على سيرفر بـ HTTPS', 'Deploying to a server with HTTPS'),
      goal: B('تنشر المشروع على VPS: SSH، وتنزّل الكود بـ git، وcompose، وreverse proxy بـ Caddy لـ HTTPS تلقائي، وfirewall، ومتابعة اللوجات والتحديث.', 'Deploy the project to a VPS: SSH, fetch the code with git, compose, a Caddy reverse proxy for automatic HTTPS, a firewall, and keeping an eye on logs and updates.'),
      learn: [
        { h: B('السيرفر', 'The server'),
          p: B('VPS = كمبيوتر Linux على النت (أقل خطة فيها 2 جيجا رام كفاية لـ n8n وAPI صغير). ادخله بـ `ssh` بمفتاح (مش باسورد)، وحدّثه، واعمل يوزر عادي، وثبّت Docker، وفعّل firewall يسمح بـ SSH و80 و443 بس. الخطوات دي مرة واحدة لكل سيرفر.', 'A VPS is a Linux computer on the internet (the smallest plan with 2 GB of RAM is enough for n8n and a small API). Log in with `ssh` using a key (not a password), update it, create a normal user, install Docker, and enable a firewall allowing only SSH, 80 and 443. These steps happen once per server.'),
          ex: '# on your machine: make a key once, copy it to the server\nssh-keygen -t ed25519 -C "me@laptop"\nssh-copy-id deploy@203.0.113.10\n\n# on the server\nsudo apt update && sudo apt upgrade -y\ncurl -fsSL https://get.docker.com | sudo sh\nsudo usermod -aG docker deploy\nsudo ufw allow OpenSSH && sudo ufw allow 80 && sudo ufw allow 443 && sudo ufw enable\n\n# get the project\ngit clone https://github.com/me/shop-automation.git && cd shop-automation\ncp .env.example .env && nano .env\ndocker compose up -d', lang: 'text' },
        { h: B('Caddy لـ HTTPS', 'Caddy for HTTPS'),
          p: B('متفتحش n8n والـ API على HTTP عادي للنت. Caddy reverse proxy قدامهم: بيطلّع شهادة HTTPS مجانية لوحده (Let\'s Encrypt) ويجددها، ويوجّه `n8n.example.com` لـ n8n و`api.example.com` للـ API. محتاج دومين بسجل A بيشاور على IP السيرفر. ظبّط `WEBHOOK_URL` في n8n على الدومين عشان لينكات الـ webhooks تطلع صح.', 'Do not expose n8n and the API over plain HTTP. Put a Caddy reverse proxy in front: it obtains a free HTTPS certificate by itself (Let\'s Encrypt) and renews it, routing `n8n.example.com` to n8n and `api.example.com` to the API. You need a domain with an A record pointing at the server’s IP. Set n8n’s `WEBHOOK_URL` to the domain so webhook links come out right.'),
          ex: '# Caddyfile\nn8n.example.com {\n    reverse_proxy n8n:5678\n}\napi.example.com {\n    reverse_proxy api:8000\n}\n\n# compose.yaml (add)\n  caddy:\n    image: caddy:2\n    ports: ["80:80", "443:443"]\n    volumes: ["./Caddyfile:/etc/caddy/Caddyfile", "caddy-data:/data"]\n    restart: unless-stopped\n# and remove the public "ports" from n8n and api; set in n8n:\n#   WEBHOOK_URL: https://n8n.example.com/\n#   N8N_PROTOCOL: https', lang: 'text' },
        { h: B('التشغيل اليومي', 'Day-to-day running'),
          p: B('`docker compose logs --tail 100 -f` تتابع، و`docker stats` الموارد، و`df -h` المساحة (اللوجات والـ images بتملا الديسك). التحديث: `git pull` ثم `docker compose up -d --build`. وراقب من برّه: خدمة مجانية بتنادي `/health` كل 5 دقايق وتبعتلك لو وقع (أو workflow n8n على سيرفر تاني). وسجّل كل حاجة عملتها في ملف ops.md.', '`docker compose logs --tail 100 -f` to watch, `docker stats` for resources, `df -h` for disk space (logs and images fill the disk). To update: `git pull`, then `docker compose up -d --build`. Monitor from outside: a free service calling `/health` every 5 minutes and alerting you when it fails (or an n8n workflow on another server). Write down everything you did in an ops.md file.'),
          ex: 'import time, urllib.request\n\ndef check(url: str, timeout: float = 5) -> tuple[bool, str]:\n    start = time.perf_counter()\n    try:\n        with urllib.request.urlopen(url, timeout=timeout) as r:\n            ok = r.status == 200\n            return ok, f"{r.status} in {(time.perf_counter() - start) * 1000:.0f} ms"\n    except Exception as e:\n        return False, f"{type(e).__name__}: {e}"\n\n# run every 5 minutes from another machine; alert after 2 failures in a row\nfor url in ["https://api.example.com/health", "https://n8n.example.com/healthz"]:\n    print(url, check(url))' }
      ],
      practice: [
        B('(لو عندك VPS أو حساب تجربة) اعمل يوزر وSSH بمفتاح وfirewall وثبّت Docker.', '(If you have a VPS or a trial account) create a user, SSH with a key, a firewall, and install Docker.'),
        B('انشر compose بتاعك وظبّط دومين فرعي مجاني أو دومين عندك.', 'Deploy your compose project and set up a free subdomain or a domain you own.'),
        B('ضيف Caddy واتأكد إن HTTPS شغال والـ webhooks بتطلع بالدومين.', 'Add Caddy and check HTTPS works and webhooks use the domain.'),
        B('اعمل workflow n8n (على جهازك) بيراقب `/health` ويبعت Telegram لو وقع.', 'Build an n8n workflow (on your machine) that watches `/health` and sends Telegram when it fails.')
      ],
      code: [
        { u: B('سكربت نشر بسيط', 'A simple deploy script'), p: '#!/bin/sh\n# deploy.sh — run on the server:  ./deploy.sh\nset -e\ncd /home/deploy/shop-automation\ngit fetch --all && git reset --hard origin/main\ndocker compose pull\ndocker compose up -d --build --remove-orphans\ndocker image prune -f\nsleep 10\ncurl -fsS https://api.example.com/health && echo " deployed OK"', lang: 'text' }
      ],
      words: [
        { t: 'VPS', m: B('سيرفر افتراضي على النت بتأجّره', 'a virtual server on the internet you rent'), ex: '2 vCPU, 2 GB RAM' },
        { t: 'SSH key', m: B('مفتاح دخول للسيرفر أأمن من الباسورد', 'a login key for a server, safer than a password'), ex: 'ssh-keygen -t ed25519' },
        { t: 'firewall', m: B('بيمنع كل البورتات غير اللي سمحت بيها', 'blocks every port except the ones you allow'), ex: 'ufw allow 443' },
        { t: 'reverse proxy', m: B('سيرفر قدام خدماتك بيوجّه الطلبات ويدير HTTPS', 'a server in front of your services routing requests and handling HTTPS'), ex: 'Caddy, Nginx' },
        { t: 'TLS certificate', m: B('الشهادة اللي بتخلي الموقع HTTPS', 'the certificate that makes a site HTTPS'), ex: "Let's Encrypt" },
        { t: 'DNS A record', m: B('سجل بيربط اسم دومين بـ IP', 'a record linking a domain name to an IP address'), ex: 'n8n.example.com → 203.0.113.10' },
        { t: 'uptime monitoring', m: B('فحص من برّه إن الخدمة شغالة', 'checking from outside that a service is up'), ex: 'GET /health every 5 minutes' }
      ],
      read: ['lib:The Linux Command Line (book)', { t: B('Caddy: Reverse proxy quick-start', 'Caddy: Reverse proxy quick-start'), url: 'https://caddyserver.com/docs/quick-starts/reverse-proxy', what: B('الصفحة كلها.', 'The whole page.') }],
      challenge: B('اكتب `ops.md` لمشروعك: إزاي تنشر من الصفر، وتحدّث، وتشوف اللوجات، وترجّع من نسخة احتياطية، وتغيّر مفتاح، وتعمل إيه لو السيرفر وقع — بحيث حد تاني يقدر يمسك المشروع من الملف ده بس.', 'Write an `ops.md` for your project: how to deploy from scratch, update, read the logs, restore from a backup, rotate a key, and what to do if the server goes down — so someone else could take over the project from that file alone.'),
      quiz: [
        { q: B('الدخول للسيرفر الأأمن:', 'The safest server login:'), o: [B('SSH بمفتاح', 'SSH with a key'), B('SSH بباسورد', 'SSH with a password'), B('FTP', 'FTP')], a: 0, why: B('ومتسيبش root.', 'And do not stay root.') },
        { q: B('Caddy قدام n8n بيدّيك:', 'Caddy in front of n8n gives you:'), o: [B('HTTPS أوتوماتيك وتوجيه بالدومين', 'automatic HTTPS and routing by domain'), B('قاعدة بيانات', 'a database'), B('نسخ احتياطي', 'backups')], a: 0, why: B('reverse proxy.', 'A reverse proxy.') },
        { q: B('لينكات webhooks في n8n طالعة localhost. الحل:', 'n8n webhook links show localhost. The fix:'), o: [B('ظبّط WEBHOOK_URL على الدومين', 'set WEBHOOK_URL to the domain'), B('أعد تشغيل الجهاز', 'reboot'), B('غيّر البورت', 'change the port')], a: 0, why: B('n8n محتاج يعرف عنوانه.', 'n8n must know its address.') }
      ] },

    { title: B('GitHub Actions: CI/CD', 'GitHub Actions: CI/CD'),
      goal: B('تخلي GitHub يشغّل ruff وmypy وpytest مع كل push وpull request، ويبني الـ image، وينشر لوحده لما الاختبارات تعدّي — بأسرار GitHub مش في الكود.', 'Have GitHub run ruff, mypy and pytest on every push and pull request, build the image and deploy by itself when the tests pass — using GitHub secrets, not code.'),
      learn: [
        { h: B('workflow اختبارات (CI)', 'A test workflow (CI)'),
          p: B('ملف في `.github/workflows/ci.yml`: بيتشغّل مع كل push وPR على سيرفر GitHub، بيثبّت Python والحزم، ويشغّل الفحوصات بتاعة أسبوع 22. علامة ✓ أو ✗ بتظهر جنب كل commit، ومتدمجش PR عليه ✗. ده نفس اللي الموقع ده بيعمله في كل تحديث.', 'A file at `.github/workflows/ci.yml` runs on every push and PR on a GitHub server, installs Python and the packages, and runs the week 22 checks. A ✓ or ✗ appears next to each commit, and you never merge a PR with an ✗. This site itself does exactly that on every update.'),
          ex: '# .github/workflows/ci.yml\nname: CI\non:\n  push:\n    branches: [main]\n  pull_request:\n\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-python@v5\n        with:\n          python-version: "3.12"\n          cache: pip\n      - run: pip install -r requirements.txt -r requirements-dev.txt\n      - run: ruff check . && ruff format --check .\n      - run: mypy app\n      - run: pytest -q --cov=app --cov-fail-under=80', lang: 'text' },
        { h: B('النشر بعد ما الاختبارات تعدّي (CD)', 'Deploying after the tests pass (CD)'),
          p: B('job تاني `needs: test` بيشتغل بس لو الاختبارات عدّت وعلى main بس: بيدخل السيرفر بـ SSH ويشغّل `deploy.sh`. المفتاح الخاص وعنوان السيرفر في **GitHub Secrets** (Settings → Secrets) ومبيظهروش في اللوج. ابدأ بنشر يدوي بزرار (`workflow_dispatch`) لحد ما تثق.', 'A second job with `needs: test` runs only when the tests pass and only on main: it logs into the server over SSH and runs `deploy.sh`. The private key and the server address live in **GitHub Secrets** (Settings → Secrets) and never show in the log. Start with a manual button (`workflow_dispatch`) until you trust it.'),
          ex: '  deploy:\n    needs: test\n    if: github.ref == \'refs/heads/main\'\n    runs-on: ubuntu-latest\n    environment: production          # can require a manual approval\n    steps:\n      - name: Deploy over SSH\n        env:\n          SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}\n          HOST: ${{ secrets.DEPLOY_HOST }}\n        run: |\n          mkdir -p ~/.ssh && echo "$SSH_KEY" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519\n          ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts\n          ssh deploy@"$HOST" "cd shop-automation && ./deploy.sh"', lang: 'text' },
        { h: B('تحديثات الحزم والأمان', 'Package updates and security'),
          p: B('Dependabot (ملف `.github/dependabot.yml`) بيفتح PR لوحده لما حزمة ليها تحديث أو ثغرة، والـ CI بيختبره قبل ما تدمجه. وفعّل secret scanning على الريبو. ثبّت إصدارات الحزم (أسبوع 7) عشان البناء يتكرر، وحدّث بخطوات صغيرة.', 'Dependabot (a `.github/dependabot.yml` file) opens a PR by itself when a package has an update or a vulnerability, and CI tests it before you merge. Turn on secret scanning for the repository. Pin package versions (week 7) so builds repeat, and update in small steps.'),
          ex: '# .github/dependabot.yml\nversion: 2\nupdates:\n  - package-ecosystem: pip\n    directory: "/"\n    schedule: { interval: weekly }\n    open-pull-requests-limit: 5\n  - package-ecosystem: github-actions\n    directory: "/"\n    schedule: { interval: monthly }\n  - package-ecosystem: docker\n    directory: "/"\n    schedule: { interval: monthly }', lang: 'text' }
      ],
      practice: [
        B('ضيف ci.yml لمشروعك وادفع وشوف العلامة الخضرا (أو صلّح الحمرا).', 'Add ci.yml to your project, push and see the green tick (or fix the red cross).'),
        B('اعمل PR فيه اختبار فاشل بقصد وشوف إن GitHub بيمنع الدمج (Branch protection).', 'Open a PR with a deliberately failing test and see GitHub block the merge (branch protection).'),
        B('ضيف Dependabot وشوف أول PR يفتحه.', 'Add Dependabot and look at the first PR it opens.'),
        B('(اختياري) اعمل deploy job بـ workflow_dispatch على سيرفرك.', '(Optional) add a deploy job with workflow_dispatch for your server.')
      ],
      code: [
        { u: B('بناء ونشر image على GitHub Container Registry', 'Build and publish an image to GitHub Container Registry'), p: '  image:\n    needs: test\n    if: github.ref == \'refs/heads/main\'\n    runs-on: ubuntu-latest\n    permissions: { contents: read, packages: write }\n    steps:\n      - uses: actions/checkout@v4\n      - uses: docker/login-action@v3\n        with: { registry: ghcr.io, username: "${{ github.actor }}", password: "${{ secrets.GITHUB_TOKEN }}" }\n      - uses: docker/build-push-action@v6\n        with:\n          push: true\n          tags: ghcr.io/${{ github.repository }}:latest,ghcr.io/${{ github.repository }}:${{ github.sha }}', lang: 'text' }
      ],
      words: [
        { t: 'CI', m: B('تشغيل الفحوصات والاختبارات أوتوماتيك مع كل تغيير', 'running checks and tests automatically on every change'), ex: 'pytest on every push' },
        { t: 'CD', m: B('النشر الأوتوماتيك بعد ما الفحوصات تعدّي', 'deploying automatically once the checks pass'), ex: 'deploy job after test' },
        { t: 'GitHub Actions', m: B('خدمة GitHub لتشغيل workflows على كل حدث', 'GitHub’s service running workflows on events'), ex: '.github/workflows/ci.yml' },
        { t: 'GitHub Secrets', m: B('مخزن أسرار الريبو اللي الـ workflows بتقراه', 'the repository secret store that workflows read'), ex: '${{ secrets.DEPLOY_HOST }}' },
        { t: 'branch protection', m: B('قواعد بتمنع الدمج على main لو الفحوصات فشلت', 'rules blocking merges into main when checks fail'), ex: 'require status checks' },
        { t: 'Dependabot', m: B('بيفتح PRs لتحديث الحزم والثغرات', 'opens PRs to update packages and fix vulnerabilities'), ex: '.github/dependabot.yml' }
      ],
      read: ['lib:GitHub Actions: Building and testing Python', { lib: 'Pro Git', what: B('(مراجعة) الفصل 3 Git Branching.', '(review) Chapter 3 Git Branching.') }],
      challenge: B('خلّي مشروع التخرج (بكرة) عليه CI كامل من أول يوم: ruff وmypy وpytest بتغطية 80%، وbranch protection على main، وDependabot، وbadge الحالة في أول الـ README.', 'Give the capstone project (tomorrow) full CI from day one: ruff, mypy and pytest with 80% coverage, branch protection on main, Dependabot, and a status badge at the top of the README.'),
      quiz: [
        { q: B('مكان مفتاح SSH للنشر من GitHub Actions:', 'Where the deploy SSH key goes for GitHub Actions:'), o: ['GitHub Secrets', B('في ملف الـ workflow', 'in the workflow file'), B('في الريبو', 'in the repository')], a: 0, why: B('سر.', 'A secret.') },
        { q: B('`needs: test` في job النشر معناها:', '`needs: test` on the deploy job means:'), o: [B('يشتغل بعد ما test ينجح بس', 'it runs only after test succeeds'), B('يشتغل الأول', 'it runs first'), B('ملهاش لازمة', 'nothing')], a: 0, why: B('ترتيب واعتماد.', 'Ordering and dependency.') },
        { q: B('PR عليه ✗ في CI:', 'A PR with an ✗ in CI:'), o: [B('متدمجوش لحد ما يتصلّح', 'do not merge it until fixed'), B('ادمجه عادي', 'merge it anyway'), B('امسح الـ CI', 'delete the CI')], a: 0, why: B('branch protection.', 'Branch protection.') }
      ] },

    { title: B('الشغل الحر والـ portfolio والخطوة الجاية', 'Freelancing, the portfolio and what comes next'),
      goal: B('تعرض شغلك بـ portfolio مقنع، وتصيغ عروض أتمتة (Python + n8n) بأسعار منطقية، وتسلّم مشاريع بتوثيق وعقد صيانة، وتعرف تكمّل تتعلم إيه.', 'Show your work with a convincing portfolio, package automation offers (Python + n8n) at sensible prices, hand projects over with documentation and a maintenance agreement, and know what to learn next.'),
      learn: [
        { h: B('portfolio بيبيع', 'A portfolio that sells'),
          p: B('3-5 مشاريع كويسة أحسن من 30 تمرين. كل مشروع على GitHub بـ README فيه: المشكلة بلغة صاحب الشغل («كان بياخد 6 ساعات كل أسبوع»)، والحل، وصورة أو GIF أو فيديو دقيقة، والنتيجة بالأرقام («بقى 3 دقايق»)، وإزاي تشغّله. مشاريع الرحلة دي (الفواتير، مراقب الأسعار، التقرير الشهري، مساعد الوارد، خدمة الأدوات) portfolio جاهز.', '3-5 good projects beat 30 exercises. Each project on GitHub with a README stating: the problem in the client’s words («it took 6 hours every week»), the solution, a screenshot, GIF or one-minute video, the result in numbers («now 3 minutes»), and how to run it. The projects of this journey (invoicing, the price watcher, the monthly report, the inbox assistant, the tools service) are a ready portfolio.'),
          ex: '# Invoice bot — from Excel orders to emailed PDF invoices\n\n**Problem:** a shop spent ~6 hours a week making and emailing 150 invoices by hand.\n**Solution:** a Python service + n8n workflow: reads orders, builds Arabic PDF invoices,\nemails them, and logs everything. Runs every morning at 8.\n**Result:** 6 hours → 3 minutes a week; zero missed invoices in 3 months.\n\n![demo](docs/demo.gif)\n\n## Run it\ncp .env.example .env && docker compose up -d\n## Tech\nPython 3.12 · FastAPI · pandas · fpdf2 · SQLite · n8n · Docker · GitHub Actions (tests 92% coverage)', lang: 'text' },
        { h: B('العروض والتسعير', 'Offers and pricing'),
          p: B('بيع النتيجة مش الساعات: «تقارير المبيعات بتوصلك أوتوماتيك كل يوم 8 الصبح». ابدأ بمكالمة تفهم فيها الشغل اليدوي وتحسب وقته (ساعات × تكلفة الساعة × 52 أسبوع = قيمة الأتمتة في السنة)، واعرض سعر ثابت جزء من القيمة دي + صيانة شهرية. حدد المطلوب كتابة (scope) ومراحل وتسليمات، ومتبدأش من غير دفعة مقدمة.', 'Sell the outcome, not the hours: «your sales reports arrive automatically every day at 8». Start with a call to understand the manual work and its time (hours × hourly cost × 52 weeks = the yearly value of automating it), then offer a fixed price that is a fraction of that value plus a monthly maintenance fee. Write down the scope, milestones and deliverables, and do not start without a deposit.'),
          ex: 'def automation_value(hours_per_week: float, cost_per_hour: float, weeks: int = 52) -> float:\n    return hours_per_week * cost_per_hour * weeks\n\nvalue = automation_value(hours_per_week=6, cost_per_hour=150)     # EGP, the client\'s cost of that time\nprice = round(value * 0.3, -2)                                    # a fixed price around 30% of a year\'s value\nmaintenance = round(price * 0.08, -1)                             # per month: monitoring, small fixes, updates\nprint(f"yearly value {value:,.0f} EGP → project {price:,.0f} EGP + {maintenance:,.0f} EGP/month")\nprint(f"the client gets back the project price in {price / (value / 12):.1f} months")', run: 1 },
        { h: B('التسليم والخطوة الجاية', 'Handover and what comes next'),
          p: B('التسليم المحترم: README وops.md (أسبوع 24 يوم 3)، وفيديو قصير بيشرح التشغيل، والأسرار في حساب العميل مش حسابك، والـ credentials باسمه، وفترة ضمان، وعقد صيانة واضح. وبعد الرحلة: اتعمق في اللي بيجيبلك شغل (APIs وبيانات وAI agents)، واقرا كود مفتوح، وساهم فيه، واكتب عن مشاريعك — والرجوع لرحلة n8n والإنجليزي في نفس الموقع بيكمّلوا الصورة.', 'A professional handover: the README and ops.md (week 24, day 3), a short video walking through the operation, secrets in the client’s account not yours, credentials in their name, a warranty period and a clear maintenance agreement. After the journey: go deeper into what brings you work (APIs, data, AI agents), read open-source code, contribute, and write about your projects — and the n8n and English journeys on this site complete the picture.'),
          ex: 'HANDOVER = [\n    "Code in the client\'s GitHub organisation (or a transferred repo)",\n    "Secrets and API keys created in the client\'s own accounts",\n    "README + ops.md: run, update, back up, restore, rotate keys",\n    "A 5-minute screen recording of the normal day and of a failure",\n    "Monitoring + alerts going to the client (and to you during support)",\n    "Backup tested with a real restore",\n    "Warranty: 30 days of fixes; maintenance agreement for after",\n]\nfor item in HANDOVER:\n    print("☐", item)', run: 1 }
      ],
      practice: [
        B('اختار أحسن 3 مشاريع من الرحلة واكتب لكل واحد README بالشكل ده بأرقام.', 'Pick the best 3 projects of the journey and write a README for each in this format, with numbers.'),
        B('سجّل فيديو دقيقة لكل مشروع (OBS أو أي برنامج تصوير شاشة).', 'Record a one-minute video for each project (OBS or any screen recorder).'),
        B('اكتب عرض لشغلانة أتمتة متخيلة بالقيمة والسعر والمراحل.', 'Write an offer for an imagined automation job with the value, price and milestones.'),
        B('ثبّت مشاريعك على بروفايل GitHub، وحدّث LinkedIn أو بروفايل منصة شغل حر.', 'Pin your projects on your GitHub profile and update LinkedIn or a freelancing profile.')
      ],
      code: [
        { u: B('قالب عرض شغل', 'An offer template'), p: 'Proposal — Automatic daily sales reports for {{client}}\n\nToday:     {{hours}} hours a week copying sales into Excel and emailing them.\nAfter:     the report arrives by email and Telegram every day at 8:00, with charts.\nValue:     about {{value}} EGP a year of staff time.\n\nDeliverables\n  1. Data connection (shop API / sheets) + cleaning           — week 1\n  2. Report (Excel + PDF + charts) and email/Telegram          — week 2\n  3. Server setup, monitoring, backups, handover documents     — week 3\n\nPrice:     {{price}} EGP fixed (40% to start, 30% at step 2, 30% at handover)\nSupport:   30 days included; then {{maintenance}} EGP/month (monitoring, fixes, updates)\nNot included: new reports or data sources (quoted separately).', lang: 'text' }
      ],
      words: [
        { t: 'portfolio', m: B('مجموعة مشاريعك اللي بتوري بيها شغلك', 'the set of projects that shows your work'), ex: '3-5 strong GitHub projects' },
        { t: 'case study', m: B('شرح مشروع: المشكلة والحل والنتيجة بالأرقام', 'a project story: problem, solution and result in numbers'), ex: '6 hours → 3 minutes' },
        { t: 'project scope', m: B('حدود الشغل المتفق عليه كتابة', 'the agreed limits of the work, in writing'), ex: 'what is not included' },
        { t: 'value-based pricing', m: B('تسعير حسب قيمة النتيجة للعميل مش بالساعة', 'pricing by the outcome’s value to the client, not by the hour'), ex: '30% of a year’s saving' },
        { t: 'maintenance agreement', m: B('اتفاق شهري للمتابعة والتصليح والتحديث', 'a monthly agreement for monitoring, fixes and updates'), ex: '1,500 EGP / month' },
        { t: 'handover', m: B('تسليم المشروع بتوثيقه وأسراره وتدريب', 'delivering a project with its docs, secrets and training'), ex: 'README + ops.md + video' }
      ],
      read: [{ t: B('GitHub Docs: Managing your profile README', 'GitHub Docs: Managing your profile README'), url: 'https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/managing-your-profile-readme', what: B('اعمل README لبروفايلك.', 'Make a README for your profile.') }, { lib: 'Exercism: Python track', what: B('كمّل تمرين كل أسبوع عشان المستوى ميقعش.', 'Keep solving one exercise a week so your level holds.') }],
      challenge: B('اعمل صفحة portfolio (GitHub Pages، أسبوع 14 وn8n أسبوع 24) فيها 3 case studies بأرقام وفيديوهات وصفحة «خدماتي» بـ 3 عروض أتمتة بأسعار مبدئية وفورم تواصل بيروح لـ n8n.', 'Build a portfolio page (GitHub Pages; week 14 and n8n week 24) with 3 case studies with numbers and videos, plus a «services» page with 3 automation offers at starting prices and a contact form that posts to n8n.'),
      quiz: [
        { q: B('README مشروع في portfolio أهم حاجة فيه:', 'The most important part of a portfolio project README:'), o: [B('المشكلة والنتيجة بالأرقام', 'the problem and the result in numbers'), B('كل الكود', 'all the code'), B('قايمة المكتبات بس', 'only the list of libraries')], a: 0, why: B('صاحب الشغل بيدور على نتيجة.', 'Clients look for outcomes.') },
        { q: B('أسرار مشروع العميل تتعمل في:', 'A client project’s secrets are created in:'), o: [B('حسابات العميل نفسه', 'the client’s own accounts'), B('حسابك انت', 'your account'), B('الكود', 'the code')], a: 0, why: B('ملكه وتحت سيطرته.', 'They own and control them.') },
        { q: B('قبل ما تبدأ مشروع حر:', 'Before starting a freelance project:'), o: [B('scope مكتوب ودفعة مقدمة', 'a written scope and a deposit'), B('ابدأ وشوف', 'start and see'), B('اكتب الكود كله الأول', 'write all the code first')], a: 0, why: B('حماية للطرفين.', 'Protection for both sides.') }
      ] },

    { title: B('مشروع التخرج والاختبار الأخير', 'The capstone project and the last test'),
      goal: B('تبني مشروع تخرج كامل بيجمع الرحلة كلها وتنشره، وتعدّي آخر اختبار عشان الامتحان النهائي يفتح.', 'Build a complete capstone project that brings the whole journey together and deploy it, then pass the last test to open the final exam.'),
      review: [
        B('Dockerfile وimage وcontainer وvolume وdockerignore والإعدادات من البيئة.', 'Dockerfile, image, container, volume, .dockerignore and settings from the environment.'),
        B('docker compose: api وn8n وpostgres وhealthchecks وrestart والنسخ الاحتياطي.', 'docker compose: api, n8n and postgres, healthchecks, restart and backups.'),
        B('VPS وSSH بمفتاح وfirewall وCaddy وHTTPS والمراقبة.', 'A VPS, SSH keys, a firewall, Caddy and HTTPS, and monitoring.'),
        B('GitHub Actions: CI بالفحوصات وCD بعد النجاح وSecrets وDependabot.', 'GitHub Actions: CI with the checks, CD after success, Secrets and Dependabot.'),
        B('portfolio بأرقام، وعروض بالقيمة، وتسليم محترم.', 'A portfolio with numbers, value-based offers and a professional handover.')
      ],
      project: B('**مشروع التخرج: منصة أتمتة لمحل صغير** (`shop-automation/`) — اختار 4 على الأقل من دول وجمعهم في نظام واحد: (1) API بـ FastAPI ومحمي وموثّق (أسبوع 21) فوق SQLite أو Postgres (أسبوع 18). (2) استيراد وتنضيف بيانات من Excel/CSV بـ pandas (أسابيع 11 و19). (3) فواتير PDF عربي وإيميلات (أسبوع 12). (4) تقرير شهري برسوم يتجدول (أسبوع 20). (5) مراقب أسعار منافسين بـ scraping مسؤول (أسبوع 16). (6) مساعد AI بيصنّف رسايل العملاء ويطلّع بيانات منظمة + MCP server (أسبوع 23). (7) لوحة HTML/JS بـ Chart.js (أسبوع 15). وn8n بيرتّب كل ده (Webhooks وجدولة وTelegram). الشروط: compose واحد بيشغّل كله، وCI أخضر (ruff وmypy وpytest 80%+)، ونسخ احتياطي متجرّب، وREADME بـ case study وفيديو 3 دقايق، وops.md. ومنشور على سيرفر بـ HTTPS (أو بفيديو للتشغيل المحلي لو مفيش سيرفر).', '**Capstone: an automation platform for a small shop** (`shop-automation/`) — choose at least 4 of these and combine them into one system: (1) a protected, documented FastAPI API (week 21) over SQLite or Postgres (week 18). (2) Importing and cleaning data from Excel/CSV with pandas (weeks 11 and 19). (3) Arabic PDF invoices and emails (week 12). (4) A scheduled monthly report with charts (week 20). (5) A responsible competitor price watcher (week 16). (6) An AI assistant classifying customer messages into structured data + an MCP server (week 23). (7) An HTML/JS dashboard with Chart.js (week 15). n8n orchestrates it all (webhooks, schedules, Telegram). Requirements: one compose file running everything, green CI (ruff, mypy and pytest 80%+), a tested backup, a README with a case study and a 3-minute video, and an ops.md. Deployed to a server with HTTPS (or a video of the local run if you have no server).'),
      test: [
        { q: B('الفرق بين image وcontainer:', 'The difference between an image and a container:'), o: [B('image قالب، container نسخة شغالة منه', 'an image is a template, a container a running copy'), B('نفس الحاجة', 'they are the same'), B('container أكبر', 'a container is bigger')], a: 0, why: B('build ثم run.', 'build, then run.') },
        { q: B('`docker compose up -d`:', '`docker compose up -d`:'), o: [B('يشغّل كل الخدمات في الخلفية', 'starts every service in the background'), B('يمسح كل حاجة', 'deletes everything'), B('يبني بس', 'only builds')], a: 0, why: B('-d = detached.', '-d = detached.') },
        { q: B('خدمتين في compose بيكلّموا بعض بـ:', 'Two services in compose talk to each other by:'), o: [B('اسم الخدمة', 'the service name'), 'localhost', B('IP ثابت لازم', 'a fixed IP, always')], a: 0, why: B('DNS داخلي.', 'Internal DNS.') },
        { q: B('`restart: unless-stopped`:', '`restart: unless-stopped`:'), o: [B('يرجع يشتغل لوحده إلا لو انت وقفته', 'restarts by itself unless you stopped it'), B('ميرجعش أبدًا', 'never restarts'), B('يعيد كل دقيقة', 'restarts every minute')], a: 0, why: B('بعد crash أو reboot.', 'After a crash or a reboot.') },
        { q: B('HTTPS أوتوماتيك قدام خدماتك:', 'Automatic HTTPS in front of your services:'), o: [B('Caddy reverse proxy', 'a Caddy reverse proxy'), B('Postgres', 'Postgres'), B('cron', 'cron')], a: 0, why: B("Let's Encrypt.", "Let's Encrypt.") },
        { q: B('أول حاجة تعملها في سيرفر جديد:', 'The first thing on a new server:'), o: [B('تحديث وSSH بمفتاح وfirewall', 'updates, SSH with a key and a firewall'), B('تفتح كل البورتات', 'open every port'), B('تشغّل كأدمن على طول', 'run everything as root')], a: 0, why: B('أمان أولًا.', 'Security first.') },
        { q: B('CI بيعمل إيه؟', 'What does CI do?'), o: [B('يشغّل الفحوصات والاختبارات مع كل تغيير', 'runs the checks and tests on every change'), B('ينشر من غير اختبار', 'deploys without testing'), B('يكتب الكود', 'writes the code')], a: 0, why: B('continuous integration.', 'Continuous integration.') },
        { q: B('مفتاح النشر في GitHub Actions مكانه:', 'The deploy key for GitHub Actions lives in:'), o: ['GitHub Secrets', 'ci.yml', 'README'], a: 0, why: B('مبيظهرش في اللوج.', 'It never shows in the log.') },
        { q: B('Dependabot بيعمل:', 'Dependabot:'), o: [B('PRs لتحديث الحزم والثغرات', 'opens PRs for package updates and vulnerabilities'), B('ينشر', 'deploys'), B('يختبر', 'tests')], a: 0, why: B('والـ CI يختبرها.', 'And CI tests them.') },
        { q: B('أحسن تسعير لأتمتة:', 'The best way to price an automation:'), o: [B('حسب قيمة النتيجة للعميل', 'by the outcome’s value to the client'), B('بعدد سطور الكود', 'by lines of code'), B('أقل سعر في السوق', 'the lowest price in the market')], a: 0, why: B('value-based.', 'Value-based.') },
        { q: B('N8N_ENCRYPTION_KEY لو ضاع:', 'If N8N_ENCRYPTION_KEY is lost:'), o: [B('الـ credentials مش هتتفك على سيرفر جديد', 'credentials cannot be decrypted on a new server'), B('مفيش مشكلة', 'no problem'), B('n8n يعمل واحد جديد ويفك القديم', 'n8n makes a new one and decrypts the old')], a: 0, why: B('احفظه في مكان آمن.', 'Keep it somewhere safe.') },
        { q: B('تسليم مشروع محترم بيشمل:', 'A professional project handover includes:'), o: [B('توثيق تشغيل وأسرار باسم العميل ونسخ احتياطي متجرّب', 'run documentation, secrets in the client’s name and a tested backup'), B('الكود بس', 'only the code'), B('باسوردك', 'your password')], a: 0, why: B('حد تاني يقدر يمسكه.', 'Someone else can take it over.') }
      ] }
  ]
};
