// The 48-week (12-month) JavaScript journey (JavaScript, HTML, CSS, Node.js and TypeScript for automation): months, week titles, ready weeks.
// Months 1–3 are the intensive start (3 hours a day); then 2 hours a day from intermediate to expert.
JOURNEY.outline({
 track: 'js',
 ready: [1, 2, 3, 4],
 months: [
  { n: 1, level: { ar: 'مبتدئ · مكثّف', en: 'Beginner · intensive' }, title: { ar: 'أساسيات جافاسكريبت', en: 'JavaScript basics' } },
  { n: 2, level: { ar: 'مبتدئ · مكثّف', en: 'Beginner · intensive' }, title: { ar: 'الكائنات والدوال والبيانات', en: 'Objects, functions and data' } },
  { n: 3, level: { ar: 'مبتدئ · مكثّف', en: 'Beginner · intensive' }, title: { ar: 'HTML وCSS وDOM', en: 'HTML, CSS and the DOM' } },
  { n: 4, level: { ar: 'متوسط', en: 'Intermediate' }, title: { ar: 'الكود غير المتزامن والـ APIs وNode.js', en: 'Async code, APIs and Node.js' } },
  { n: 5, level: { ar: 'متوسط', en: 'Intermediate' }, title: { ar: 'Node.js للأتمتة', en: 'Node.js for automation' } },
  { n: 6, level: { ar: 'متوسط', en: 'Intermediate' }, title: { ar: 'جافاسكريبت في الأتمتة: n8n والمتصفح', en: 'JavaScript in automation: n8n and the browser' } },
  { n: 7, level: { ar: 'محترف', en: 'Professional' }, title: { ar: 'TypeScript والجودة', en: 'TypeScript and quality' } },
  { n: 8, level: { ar: 'محترف', en: 'Professional' }, title: { ar: 'الواجهات المتقدمة', en: 'Advanced front-end' } },
  { n: 9, level: { ar: 'محترف', en: 'Professional' }, title: { ar: 'الباك إند والبيانات', en: 'Back-end and data' } },
  { n: 10, level: { ar: 'خبير', en: 'Expert' }, title: { ar: 'الذكاء الاصطناعي والإضافات', en: 'AI and extensions' } },
  { n: 11, level: { ar: 'خبير', en: 'Expert' }, title: { ar: 'الأداء والمعمارية والأمان', en: 'Performance, architecture and security' } },
  { n: 12, level: { ar: 'خبير', en: 'Expert' }, title: { ar: 'الخبير في الإنتاج', en: 'The expert in production' } }
 ],
 weeks: [
  { ar: 'البداية: جافاسكريبت في المتصفح وNode والمتغيرات والأنواع', en: 'Getting started: JavaScript in the browser and Node, variables and types' },
  { ar: 'النصوص والأرقام والعمليات', en: 'Strings, numbers and operators' },
  { ar: 'الشروط والتكرار', en: 'Conditions and loops' },
  { ar: 'المصفوفات ومشروع الشهر', en: 'Arrays and the month project' },
  { ar: 'الكائنات وJSON', en: 'Objects and JSON' },
  { ar: 'الدوال والنطاق والـ Closures', en: 'Functions, scope and closures' },
  { ar: 'دوال المصفوفات: map وfilter وreduce', en: 'Array methods: map, filter and reduce' },
  { ar: 'الأخطاء والـ Debugging وأدوات المطوّر ومشروع الشهر', en: 'Errors, debugging, DevTools and the month project' },
  { ar: 'HTML بعمق: الدلالة والفورمز', en: 'HTML in depth: semantics and forms' },
  { ar: 'أساسيات CSS: المحددات والـ Box model والخطوط', en: 'CSS basics: selectors, the box model and fonts' },
  { ar: 'التخطيط: Flexbox وGrid والتصميم المتجاوب', en: 'Layout: Flexbox, Grid and responsive design' },
  { ar: 'الـ DOM والأحداث ومشروع الشهر', en: 'The DOM, events and the month project' },
  { ar: 'الكود غير المتزامن: Promises وasync/await', en: 'Async code: promises and async/await' },
  { ar: 'fetch والـ APIs', en: 'fetch and APIs' },
  { ar: 'الوحدات وnpm والأدوات', en: 'Modules, npm and tooling' },
  { ar: 'أساسيات Node.js: الملفات والمسارات والعمليات ومشروع الشهر', en: 'Node.js basics: files, paths, processes and the month project' },
  { ar: 'سكربتات أتمتة بـ Node.js وسطر الأوامر', en: 'Automation scripts and the command line with Node.js' },
  { ar: 'خوادم HTTP والـ Webhooks بـ Express', en: 'HTTP servers and webhooks with Express' },
  { ar: 'ملفات البيانات: CSV وExcel وPDF في Node', en: 'Data files in Node: CSV, Excel and PDF' },
  { ar: 'Regex ومعالجة النصوص ومشروع الشهر', en: 'Regex, text processing and the month project' },
  { ar: 'جافاسكريبت في Code node بتاع n8n بعمق', en: 'JavaScript in the n8n Code node in depth' },
  { ar: 'أتمتة Google بـ Apps Script', en: 'Automating Google with Apps Script' },
  { ar: 'أتمتة المتصفح بـ Playwright', en: 'Browser automation with Playwright' },
  { ar: 'الـ Scraping بـ Node ومشروع الشهر', en: 'Scraping with Node and the month project' },
  { ar: 'أساسيات TypeScript', en: 'TypeScript basics' },
  { ar: 'TypeScript المتقدم: الأنواع العامة والمساعدة', en: 'Advanced TypeScript: generics and utility types' },
  { ar: 'الاختبارات بـ Vitest', en: 'Testing with Vitest' },
  { ar: 'جودة الكود: ESLint وPrettier وسير عمل Git ومشروع الشهر', en: 'Code quality: ESLint, Prettier, Git workflows and the month project' },
  { ar: 'CSS المتقدم: المتغيرات والحركة والميزات الحديثة', en: 'Advanced CSS: variables, animation and modern features' },
  { ar: 'إمكانية الوصول والأداء في الواجهة', en: 'Accessibility and front-end performance' },
  { ar: 'مكوّنات واجهة من غير Framework', en: 'UI components without a framework' },
  { ar: 'مقدمة React ومشروع الشهر', en: 'An introduction to React and the month project' },
  { ar: 'قواعد البيانات من Node: SQL وPostgres', en: 'Databases from Node: SQL and Postgres' },
  { ar: 'الصلاحيات والأمان في الـ APIs: JWT وOAuth', en: 'Auth and API security: JWT and OAuth' },
  { ar: 'الوقت الحقيقي: WebSockets وSSE', en: 'Real time: WebSockets and SSE' },
  { ar: 'الطوابير والمهام الخلفية ومشروع الشهر', en: 'Queues, background jobs and the month project' },
  { ar: 'الذكاء الاصطناعي بجافاسكريبت: Claude API والـ Streaming والأدوات', en: 'AI in JavaScript: the Claude API, streaming and tools' },
  { ar: 'خوادم MCP بـ TypeScript', en: 'MCP servers in TypeScript' },
  { ar: 'Nodes مخصصة لـ n8n بـ TypeScript', en: 'Custom n8n nodes in TypeScript' },
  { ar: 'إضافات المتصفح ومشروع الشهر', en: 'Browser extensions and the month project' },
  { ar: 'الأداء: الـ Event loop والـ Streams والـ Workers', en: 'Performance: the event loop, streams and workers' },
  { ar: 'المعمارية وأنماط التصميم', en: 'Architecture and design patterns' },
  { ar: 'أمان الويب بعمق: XSS وCSRF وسلسلة التوريد', en: 'Web security in depth: XSS, CSRF and the supply chain' },
  { ar: 'Serverless والـ Edge ومشروع الشهر', en: 'Serverless, the edge and the month project' },
  { ar: 'Docker ونشر تطبيقات Node', en: 'Docker and deploying Node apps' },
  { ar: 'CI/CD والمراقبة', en: 'CI/CD and monitoring' },
  { ar: 'العمل الحر كمطوّر أتمتة بجافاسكريبت', en: 'Freelancing as a JavaScript automation developer' },
  { ar: 'مشروع الخبير النهائي', en: 'The expert capstone project' }
 ]
});
