// Week 16 — generated by tools/build_weeks.js from content/english/src/w16.js. Edit the source, not this file.
JOURNEY.week({
 "track": "english",
 "n": 16,
 "month": 4,
 "level": "B1",
 "title": {
  "ar": "التفاوض والاتفاق مع العميل",
  "en": "Negotiating and agreeing with clients"
 },
 "goal": {
  "ar": "تتكلم مع عميل عن النطاق والسعر والمواعيد: تعرض، وتفاوض، وترفض بأدب، وتكتب الاتفاق وشروط الدفع بوضوح.",
  "en": "Talk with a client about scope, price and deadlines: make an offer, negotiate, say no politely, and write the agreement and payment terms clearly."
 },
 "days": [
  {
   "d": 1,
   "title": {
    "ar": "النطاق والعرض",
    "en": "Scope and the proposal"
   },
   "goal": {
    "ar": "تكتب عرض (proposal) قصير: المشكلة، والحل، والمخرجات، والسعر، والمدة.",
    "en": "Write a short proposal: the problem, the solution, the deliverables, the price and the timeline."
   },
   "learn": [
    {
     "h": {
      "ar": "هيكل العرض",
      "en": "Proposal structure"
     },
     "p": {
      "ar": "Problem (بكلام العميل)، Solution، Deliverables (قايمة حاجات هيستلمها)، Out of scope (اللي مش ضمن الشغل)، Timeline، Price، Next steps.",
      "en": "Problem (in the client's words), Solution, Deliverables (a list of what they will receive), Out of scope, Timeline, Price, Next steps."
     },
     "ex": "Deliverables:\n- An n8n workflow that syncs orders to Google Sheets\n- A one-page user guide\nOut of scope: changes to the website itself.\nPrice: USD 600, 50% upfront."
    },
    {
     "h": {
      "ar": "ليه Out of scope مهم",
      "en": "Why \"Out of scope\" matters"
     },
     "p": {
      "ar": "بيحميك من scope creep. أي طلب جديد بعدين: That's outside the current scope, but I'm happy to quote it separately.",
      "en": "It protects you from scope creep. For any new request later: That's outside the current scope, but I'm happy to quote it separately."
     },
     "ex": "Adding a mobile app is outside the current scope. I can send you a separate estimate."
    },
    {
     "h": {
      "ar": "الأرقام بالحروف ولا بالأرقام",
      "en": "Numbers in words or digits"
     },
     "p": {
      "ar": "في الكتابة العادية: الأرقام من 1 لـ 9 بالحروف، و10 وأكتر بالأرقام. والجملة مبتبدأش برقم.",
      "en": "In normal writing: write one to nine as words and 10 or more as digits. Don't start a sentence with a digit."
     },
     "ex": "✗ 3 tests failed and nine passed.\n✓ Three tests failed and nine passed."
    }
   ],
   "practice": [
    {
     "ar": "اكتب proposal من صفحة لمشروع أتمتة صغير لعميل متخيّل.",
     "en": "Write a one-page proposal for a small automation project for an imagined client."
    },
    {
     "ar": "اكتب قايمة deliverables من 4 بنود وقايمة out of scope من 3.",
     "en": "Write a 4-item deliverables list and a 3-item out-of-scope list."
    },
    {
     "ar": "اكتب 4 ردود على طلبات بره النطاق.",
     "en": "Write 4 replies to out-of-scope requests."
    },
    {
     "ar": "اكتب 5 أسعار ومبالغ بالشكل الصح: USD 1,200، EUR 50، 15%.",
     "en": "Write 5 prices and amounts correctly: USD 1,200, EUR 50, 15%."
    }
   ],
   "words": [
    {
     "t": "client / customer",
     "m": {
      "ar": "عميل",
      "en": "a person or company that buys from you"
     },
     "ex": "The client wants a demo on Monday."
    },
    {
     "t": "contract",
     "m": {
      "ar": "عقد",
      "en": "a written legal agreement"
     },
     "ex": "Read the contract before you sign it."
    },
    {
     "t": "invoice",
     "m": {
      "ar": "فاتورة",
      "en": "a bill for work or products"
     },
     "ex": "I will send the invoice at the end of the month."
    },
    {
     "t": "budget",
     "m": {
      "ar": "ميزانية",
      "en": "the money planned for something"
     },
     "ex": "The project is within budget."
    },
    {
     "t": "deliverable",
     "m": {
      "ar": "حاجة هتتسلّم فعلاً للعميل",
      "en": "Something you'll actually hand over to the client"
     },
     "ex": "The main deliverable is a working workflow."
    },
    {
     "t": "proposal",
     "m": {
      "ar": "عرض شغل لعميل",
      "en": "A job offer you send to a client"
     },
     "ex": "I sent a proposal for the automation project."
    },
    {
     "t": "expense",
     "m": {
      "ar": "مصروف / تكلفة",
      "en": "money spent"
     },
     "ex": "Hosting is our biggest monthly expense."
    }
   ],
   "read": [
    {
     "t": "freeCodeCamp News",
     "url": "https://www.freecodecamp.org/news/",
     "what": {
      "ar": "دوّر على مقال عن «freelance proposal» أو «pricing freelance» واقراه.",
      "en": "Search for an article about \"freelance proposals\" or \"pricing freelance work\" and read it."
     }
    }
   ],
   "challenge": {
    "ar": "ابعت proposal حقيقي لعميل أو لمشروع على منصة freelance (أو احفظه جاهز)، واطلب رأي حد عنده خبرة.",
    "en": "Send a real proposal to a client or a freelance-platform project (or keep it ready), and ask someone experienced for feedback."
   },
   "quiz": [
    {
     "q": {
      "ar": "deliverable هو:",
      "en": "A deliverable is:"
     },
     "o": [
      {
       "ar": "حاجة هيستلمها العميل",
       "en": "something the client will receive"
      },
      {
       "ar": "ميعاد التسليم",
       "en": "the delivery date"
      },
      {
       "ar": "شركة الشحن",
       "en": "a courier company"
      }
     ],
     "a": 0,
     "why": {
      "ar": "مخرج ملموس.",
      "en": "A tangible output."
     }
    },
    {
     "q": {
      "ar": "رد على طلب بره النطاق:",
      "en": "A reply to an out-of-scope request:"
     },
     "o": [
      "No.",
      "That's outside the current scope, but I can quote it separately.",
      "OK, free."
     ],
     "a": 1,
     "why": {
      "ar": "رفض مؤدب + فرصة.",
      "en": "A polite no + an opportunity."
     }
    },
    {
     "q": {
      "ar": "أنهي كتابة صح لسعر؟",
      "en": "Which is written correctly?"
     },
     "o": [
      "1200$USD",
      "USD 1,200",
      "1.200 dollars$"
     ],
     "a": 1,
     "why": {
      "ar": "العملة + الرقم بفاصلة الآلاف.",
      "en": "Currency + the number with a thousands comma."
     }
    }
   ],
   "minutes": 120
  },
  {
   "d": 2,
   "title": {
    "ar": "الفلوس والدفع",
    "en": "Money and payment"
   },
   "goal": {
    "ar": "تتكلم عن السعر والخصم والرسوم والاشتراك والاسترداد.",
    "en": "Talk about price, discounts, fees, subscriptions and refunds."
   },
   "learn": [
    {
     "h": {
      "ar": "كلام الأسعار",
      "en": "Price language"
     },
     "p": {
      "ar": "The price is… / It costs… / There's a 10% discount for annual plans. / The platform fee is 5%. / The subscription renews monthly. / We offer a full refund within 14 days.",
      "en": "The price is… / It costs… / There's a 10% discount for annual plans. / The platform fee is 5%. / The subscription renews monthly. / We offer a full refund within 14 days."
     },
     "ex": "The total is USD 540, including a 10% discount.\nPayment is due within 14 days of the invoice date."
    },
    {
     "h": {
      "ar": "price وcost وfee",
      "en": "price, cost and fee"
     },
     "p": {
      "ar": "price = السعر اللي بتطلبه، cost = اللي بتدفعه أو التكلفة عليك، fee = رسوم خدمة. وcheap ممكن تبان «رخيص وحش»: قول affordable.",
      "en": "price = what you ask for, cost = what it costs you, fee = a service charge. cheap can sound \"low quality\": say affordable."
     },
     "ex": "Our price is affordable, but the hosting costs are extra."
    },
    {
     "h": {
      "ar": "ترتيب الصفات",
      "en": "Order of adjectives"
     },
     "p": {
      "ar": "لما يبقى في كذا صفة: الرأي ← الحجم ← العمر ← الشكل ← اللون ← الأصل ← المادة ← الغرض، وبعدين الاسم.",
      "en": "With several adjectives: opinion → size → age → shape → colour → origin → material → purpose, then the noun."
     },
     "ex": "✗ a black new small laptop\n✓ a small new black laptop"
    }
   ],
   "practice": [
    {
     "ar": "اكتب جدول أسعار لخدمة (3 باقات) بجملة لكل باقة.",
     "en": "Write a price table for a service (3 packages) with a sentence for each."
    },
    {
     "ar": "اكتب شروط دفع (payment terms) في 4 جمل.",
     "en": "Write payment terms in 4 sentences."
    },
    {
     "ar": "اكتب إيميل رد على عميل عايز refund.",
     "en": "Write an email replying to a client who wants a refund."
    },
    {
     "ar": "رتّب الصفات: `a (new, small, Python) script`، `a (red, big, old) button`.",
     "en": "Order the adjectives: `a (new, small, Python) script`, `a (red, big, old) button`."
    }
   ],
   "words": [
    {
     "t": "price / cost",
     "m": {
      "ar": "السعر / التكلفة",
      "en": "how much something costs"
     },
     "ex": "What's the price of the monthly plan?"
    },
    {
     "t": "discount",
     "m": {
      "ar": "خصم",
      "en": "a lower price"
     },
     "ex": "Students get a 20% discount."
    },
    {
     "t": "fee",
     "m": {
      "ar": "رسوم",
      "en": "money paid for a service"
     },
     "ex": "There's a small fee for card payments."
    },
    {
     "t": "subscription",
     "m": {
      "ar": "اشتراك",
      "en": "regular payment for a service"
     },
     "ex": "Cancel the subscription before it renews."
    },
    {
     "t": "pay (by card)",
     "m": {
      "ar": "يدفع",
      "en": "to give money for something"
     },
     "ex": "Can I pay by card?"
    },
    {
     "t": "refund",
     "m": {
      "ar": "استرداد فلوس",
      "en": "money given back"
     },
     "ex": "The customer asked for a refund."
    },
    {
     "t": "receipt",
     "m": {
      "ar": "إيصال",
      "en": "proof that you paid"
     },
     "ex": "Keep the receipt for the new laptop."
    }
   ],
   "read": [
    {
     "t": "Breaking News English",
     "url": "https://breakingnewsenglish.com/",
     "what": {
      "ar": "اختار خبر عن الاقتصاد أو الأسعار في مستوى 3 أو 4 واقراه.",
      "en": "Pick an economy or prices story at level 3 or 4 and read it."
     }
    }
   ],
   "challenge": {
    "ar": "اكتب صفحة Pricing لخدمة أتمتة بتقدمها: 3 باقات، وخصم سنوي، وسياسة refund.",
    "en": "Write a Pricing page for an automation service you offer: 3 packages, an annual discount and a refund policy."
   },
   "quiz": [
    {
     "q": {
      "ar": "refund معناها:",
      "en": "refund means:"
     },
     "o": [
      {
       "ar": "رجوع الفلوس",
       "en": "money given back"
      },
      {
       "ar": "خصم",
       "en": "a discount"
      },
      {
       "ar": "فاتورة",
       "en": "an invoice"
      }
     ],
     "a": 0,
     "why": {
      "ar": "استرداد.",
      "en": "Getting your money back."
     }
    },
    {
     "q": {
      "ar": "كلمة أحسن من cheap في عرض:",
      "en": "A better word than cheap in an offer:"
     },
     "o": [
      "affordable",
      "poor",
      "low"
     ],
     "a": 0,
     "why": {
      "ar": "affordable = في المتناول، من غير إيحاء سلبي.",
      "en": "affordable = within reach, without a negative feel."
     }
    },
    {
     "q": {
      "ar": "اختار الترتيب الصح:",
      "en": "Choose the correct order:"
     },
     "o": [
      "a Python small new script",
      "a small new Python script",
      "a new Python small script"
     ],
     "a": 1,
     "why": {
      "ar": "حجم ← عمر ← أصل/نوع.",
      "en": "size → age → origin/type."
     }
    }
   ],
   "minutes": 120
  },
  {
   "d": 3,
   "title": {
    "ar": "التفاوض",
    "en": "Negotiating"
   },
   "goal": {
    "ar": "تفاوض على السعر والمدة: تقترح، وتتنازل مقابل حاجة، وتتكلم عن الأرقام الشهرية والسنوية.",
    "en": "Negotiate price and time: propose, concede in exchange for something, and talk about monthly and annual figures."
   },
   "learn": [
    {
     "h": {
      "ar": "جمل التفاوض",
      "en": "Negotiation phrases"
     },
     "p": {
      "ar": "Would you be open to…? / If you can…, we can… / That's a bit above our budget. / What if we reduce the scope to…? / Let's meet in the middle. / That works for us.",
      "en": "Would you be open to…? / If you can…, we can… / That's a bit above our budget. / What if we reduce the scope to…? / Let's meet in the middle. / That works for us."
     },
     "ex": "If you can pay 50% upfront, we can start next Monday.\nWhat if we drop the dashboard and keep the price at USD 500?"
    },
    {
     "h": {
      "ar": "متتنازلش ببلاش",
      "en": "Don't give things away"
     },
     "p": {
      "ar": "أي تنازل مقابل حاجة: خصم مقابل عقد أطول، أو تسليم أسرع مقابل سعر أعلى. استخدم «if… then…».",
      "en": "Every concession for something in return: a discount for a longer contract, or faster delivery for a higher price. Use \"if… then…\"."
     },
     "ex": "We can offer 10% off if you sign for 12 months."
    },
    {
     "h": {
      "ar": "الأمريكي والبريطاني",
      "en": "American and British spelling"
     },
     "p": {
      "ar": "اختار واحد والتزم بيه: color/colour، organize/organise، center/centre. التوثيق التقني غالبًا أمريكي.",
      "en": "Choose one and stay consistent: color/colour, organize/organise, center/centre. Tech docs are usually American."
     },
     "ex": "✗ Organise the colors in the center.\n✓ Organize the colors in the center."
    }
   ],
   "practice": [
    {
     "ar": "اكتب حوار تفاوض (10 سطور) بين فريلانسر وعميل على السعر.",
     "en": "Write a 10-line negotiation dialogue between a freelancer and a client about price."
    },
    {
     "ar": "اكتب 5 جمل «If you…, we can…».",
     "en": "Write 5 \"If you…, we can…\" sentences."
    },
    {
     "ar": "احسب واكتب تكلفة شهرية وسنوية لاشتراك بخصم، في 4 جمل.",
     "en": "Calculate and write the monthly and annual cost of a subscription with a discount, in 4 sentences."
    },
    {
     "ar": "اكتب 5 كلمات بالأمريكي والبريطاني (color / colour…).",
     "en": "Write 5 words in American and British spelling (color / colour…)."
    }
   ],
   "words": [
    {
     "t": "supplier / vendor",
     "m": {
      "ar": "مورّد",
      "en": "a company that sells to you"
     },
     "ex": "Our cloud vendor raised the prices."
    },
    {
     "t": "revenue",
     "m": {
      "ar": "الإيرادات",
      "en": "money a company earns"
     },
     "ex": "The new feature increased revenue by 10%."
    },
    {
     "t": "profit / loss",
     "m": {
      "ar": "ربح / خسارة",
      "en": "money gained / money lost"
     },
     "ex": "We made a profit this quarter."
    },
    {
     "t": "quarter (Q1, Q2…)",
     "m": {
      "ar": "ربع سنة",
      "en": "three months of a business year"
     },
     "ex": "We plan to launch in Q3."
    },
    {
     "t": "annual / monthly / weekly",
     "m": {
      "ar": "سنوي / شهري / أسبوعي",
      "en": "every year / month / week"
     },
     "ex": "We send a weekly report and an annual summary."
    },
    {
     "t": "cheap / expensive",
     "m": {
      "ar": "رخيص / غالي",
      "en": "low price / high price"
     },
     "ex": "This laptop is expensive but fast."
    },
    {
     "t": "transfer (money)",
     "m": {
      "ar": "يحوّل فلوس",
      "en": "to send money to another account"
     },
     "ex": "I'll transfer the money today."
    }
   ],
   "read": [
    {
     "t": "All Ears English",
     "url": "https://www.allearsenglish.com/",
     "what": {
      "ar": "دوّر على حلقة عن «negotiation» واسمعها.",
      "en": "Find an episode about \"negotiation\" and listen to it."
     }
    }
   ],
   "challenge": {
    "ar": "مثّل تفاوض مع صاحب (5 دقايق) بالإنجليزي على مشروع متخيّل، وسجّله، واكتب 3 جمل كان ممكن تقولها أحسن.",
    "en": "Role-play a 5-minute English negotiation with a friend about an imagined project, record it, and write 3 sentences you could have said better."
   },
   "quiz": [
    {
     "q": {
      "ar": "تنازل مقابل حاجة:",
      "en": "A concession in exchange for something:"
     },
     "o": [
      "OK, 30% off.",
      "We can offer 10% off if you sign for a year.",
      "Fine, it's free."
     ],
     "a": 1,
     "why": {
      "ar": "if = مقابل.",
      "en": "if = in return."
     }
    },
    {
     "q": {
      "ar": "«That's a bit above our budget» معناها:",
      "en": "\"That's a bit above our budget\" means:"
     },
     "o": [
      {
       "ar": "السعر أعلى من ميزانيتنا شوية",
       "en": "the price is a little over our budget"
      },
      {
       "ar": "موافقين",
       "en": "we agree"
      },
      {
       "ar": "معندناش فلوس خالص",
       "en": "we have no money"
      }
     ],
     "a": 0,
     "why": {
      "ar": "طريقة مهذبة للتفاوض.",
      "en": "A polite way to negotiate."
     }
    },
    {
     "q": {
      "ar": "Q3 معناها:",
      "en": "Q3 means:"
     },
     "o": [
      {
       "ar": "الربع التالت من السنة",
       "en": "the third quarter of the year"
      },
      {
       "ar": "سؤال 3",
       "en": "question 3"
      },
      {
       "ar": "3 أسابيع",
       "en": "3 weeks"
      }
     ],
     "a": 0,
     "why": {
      "ar": "يوليو–سبتمبر غالبًا.",
      "en": "Usually July–September."
     }
    }
   ],
   "minutes": 120
  },
  {
   "d": 4,
   "title": {
    "ar": "المواعيد والرفض بأدب",
    "en": "Deadlines and saying no"
   },
   "goal": {
    "ar": "تتكلم عن المواعيد والتسليم، وتقول لأ أو «مش في الموعد ده» من غير ما تخسر العميل.",
    "en": "Talk about deadlines and delivery, and say no or \"not by then\" without losing the client."
   },
   "learn": [
    {
     "h": {
      "ar": "الموعد الواقعي",
      "en": "A realistic deadline"
     },
     "p": {
      "ar": "We can deliver by… / To meet this deadline, we'd need to… / Realistically, it will take about two weeks. / I'd rather promise less and deliver on time.",
      "en": "We can deliver by… / To meet this deadline, we'd need to… / Realistically, it will take about two weeks. / I'd rather promise less and deliver on time."
     },
     "ex": "To meet the 1 October deadline, we'd need the API access by this Friday."
    },
    {
     "h": {
      "ar": "«لأ» بأدب",
      "en": "Saying no politely"
     },
     "p": {
      "ar": "Unfortunately, we can't… / I'm afraid that won't be possible by Monday, but we could… / I'd love to help, but my schedule is full until…",
      "en": "Unfortunately, we can't… / I'm afraid that won't be possible by Monday, but we could… / I'd love to help, but my schedule is full until…"
     },
     "ex": "I'm afraid we can't add both features by Friday. We could deliver the export first and the dashboard next week."
    },
    {
     "h": {
      "ar": "who و whom",
      "en": "Who and whom"
     },
     "p": {
      "ar": "who فاعل (who wrote this?)، whom مفعول (to whom did you send it?). في الكلام العادي who مقبولة في الحالتين.",
      "en": "who is the subject (who wrote this?), whom is the object (to whom did you send it?). In speech, who is fine for both."
     },
     "ex": "✗ Whom is responsible for the release?\n✓ Who is responsible for the release?"
    }
   ],
   "practice": [
    {
     "ar": "اكتب 4 ردود بتقول فيها موعد واقعي بدل الموعد اللي العميل عايزه.",
     "en": "Write 4 replies giving a realistic date instead of the one the client wants."
    },
    {
     "ar": "اكتب 3 طرق تقول لأ بأدب ومعاها بديل.",
     "en": "Write 3 polite ways to say no, each with an alternative."
    },
    {
     "ar": "اكتب 7 جمل بالأفعال بتاعة النهارده عن مشروع.",
     "en": "Write 7 sentences with today's verbs about a project."
    },
    {
     "ar": "اختار who ولا whom في 4 جمل رسمية.",
     "en": "Choose who or whom in 4 formal sentences."
    }
   ],
   "words": [
    {
     "t": "meet a deadline",
     "m": {
      "ar": "يلحق الميعاد النهائي",
      "en": "to finish on time"
     },
     "ex": "We met the deadline with one day to spare."
    },
    {
     "t": "delegate",
     "m": {
      "ar": "يفوّض حد يعمل مهمة",
      "en": "to give a task to someone else"
     },
     "ex": "Delegate the testing to the QA team."
    },
    {
     "t": "leverage",
     "m": {
      "ar": "يستفيد من / يستغل",
      "en": "to use something to get a result"
     },
     "ex": "We leverage AI to sort support emails."
    },
    {
     "t": "facilitate",
     "m": {
      "ar": "يسهّل",
      "en": "to make easier"
     },
     "ex": "The new tool facilitates code reviews."
    },
    {
     "t": "utilize",
     "m": {
      "ar": "يستخدم (رسمي)",
      "en": "to use (formal)"
     },
     "ex": "Utilize the existing API instead of a new one."
    },
    {
     "t": "depict",
     "m": {
      "ar": "يوضّح بالرسم / يصوّر",
      "en": "to show in a picture"
     },
     "ex": "The diagram depicts the data flow."
    },
    {
     "t": "manipulate (data)",
     "m": {
      "ar": "يعدّل ويتحكم في البيانات",
      "en": "to change or process data"
     },
     "ex": "Use pandas to manipulate the data."
    }
   ],
   "read": [
    {
     "t": "Plain Language Guidelines",
     "url": "https://www.plainlanguage.gov/guidelines/",
     "what": {
      "ar": "اقرا صفحة عن «Use simple words and phrases» ولاحظ ليه utilize وleverage تقيلة.",
      "en": "Read a page about \"Use simple words and phrases\" and notice why utilize and leverage sound heavy."
     }
    }
   ],
   "challenge": {
    "ar": "اكتب إيميل لعميل بيطلب تسليم بدري: ترفض بأدب، وتشرح السبب في جملة، وتقترح خطة من مرحلتين.",
    "en": "Write an email to a client asking for early delivery: say no politely, give the reason in one sentence, and propose a two-phase plan."
   },
   "quiz": [
    {
     "q": {
      "ar": "أحسن رد على موعد مستحيل:",
      "en": "The best reply to an impossible deadline:"
     },
     "o": [
      "Sure!",
      "Realistically, it will take two weeks. We could deliver part one by Friday.",
      "Impossible."
     ],
     "a": 1,
     "why": {
      "ar": "صادق ومعاه بديل.",
      "en": "Honest, with an alternative."
     }
    },
    {
     "q": {
      "ar": "meet a deadline معناها:",
      "en": "meet a deadline means:"
     },
     "o": [
      {
       "ar": "تسلّم في الموعد",
       "en": "deliver on time"
      },
      {
       "ar": "تقابل حد",
       "en": "meet someone"
      },
      {
       "ar": "تلغي الموعد",
       "en": "cancel the deadline"
      }
     ],
     "a": 0,
     "why": {
      "ar": "تلحق الميعاد.",
      "en": "Finish by the date."
     }
    },
    {
     "q": {
      "ar": "بدل utilize في كتابة بسيطة:",
      "en": "Instead of utilize in plain writing:"
     },
     "o": [
      "use",
      "employment",
      "utility"
     ],
     "a": 0,
     "why": {
      "ar": "use أبسط وأوضح.",
      "en": "use is simpler and clearer."
     }
    }
   ],
   "minutes": 120
  },
  {
   "d": 5,
   "title": {
    "ar": "الاتفاق وشروط الدفع",
    "en": "The agreement and payment terms"
   },
   "goal": {
    "ar": "تقفل الاتفاق كتابةً: اللي اتفقنا عليه، والدفع، والخطوة الجاية، وتتكلم عن الفلوس اليومية.",
    "en": "Close the deal in writing — what we agreed, the payment and the next step — and talk about everyday money."
   },
   "learn": [
    {
     "h": {
      "ar": "إيميل تأكيد الاتفاق",
      "en": "The agreement confirmation email"
     },
     "p": {
      "ar": "Just to confirm what we agreed: Scope… Price… Payment: 50% upfront, 50% on delivery, by bank transfer. Timeline… Please reply to confirm, and I'll send the first invoice.",
      "en": "Just to confirm what we agreed: Scope… Price… Payment: 50% upfront, 50% on delivery, by bank transfer. Timeline… Please reply to confirm, and I'll send the first invoice."
     },
     "ex": "Payment terms: 50% upfront, 50% within 7 days of delivery.\nAccepted methods: bank transfer or card."
    },
    {
     "h": {
      "ar": "فلوس كل يوم",
      "en": "Everyday money"
     },
     "p": {
      "ar": "Can I pay by card? / Keep the change. / Could I have the receipt? / The bill, please. / I'm trying to save money this month.",
      "en": "Can I pay by card? / Keep the change. / Could I have the receipt? / The bill, please. / I'm trying to save money this month."
     },
     "ex": "Is service included, or should I leave a tip?"
    },
    {
     "h": {
      "ar": "كتابة التاريخ والوقت",
      "en": "Writing dates and times"
     },
     "p": {
      "ar": "الأمريكي: May 3, 2026 (شهر/يوم). البريطاني: 3 May 2026. وفي الشغل الأوضح ISO: 2026-05-03. والوقت: 3:30 PM.",
      "en": "US: May 3, 2026. UK: 3 May 2026. At work ISO is clearest: 2026-05-03. Time: 3:30 PM."
     },
     "ex": "✗ The meeting is on 03/05 at 15.30pm.\n✓ The meeting is on 2026-05-03 at 3:30 PM."
    }
   ],
   "practice": [
    {
     "ar": "اكتب إيميل تأكيد اتفاق كامل لمشروع متخيّل.",
     "en": "Write a complete agreement confirmation email for an imagined project."
    },
    {
     "ar": "اكتب شروط دفع بـ 3 طرق مختلفة (milestones، شهري، مرة واحدة).",
     "en": "Write payment terms three different ways (milestones, monthly, one-off)."
    },
    {
     "ar": "اكتب حوار دفع في كافيه أو محل (6 سطور).",
     "en": "Write a 6-line dialogue about paying in a café or a shop."
    },
    {
     "ar": "اكتب 5 جمل عن ميزانيتك الشخصية (save / spend / account).",
     "en": "Write 5 sentences about your personal budget (save / spend / account)."
    }
   ],
   "words": [
    {
     "t": "account (bank)",
     "m": {
      "ar": "حساب (في البنك)",
      "en": "where the bank keeps your money"
     },
     "ex": "I opened a new bank account."
    },
    {
     "t": "bill / check",
     "m": {
      "ar": "الحساب / الفاتورة",
      "en": "the paper that shows what you owe"
     },
     "ex": "Can we have the bill, please?"
    },
    {
     "t": "cash / card",
     "m": {
      "ar": "كاش / كارت",
      "en": "money notes / bank card"
     },
     "ex": "Do you take card or only cash?"
    },
    {
     "t": "change (money)",
     "m": {
      "ar": "الباقي / فكّة",
      "en": "money you get back"
     },
     "ex": "Keep the change."
    },
    {
     "t": "wallet / purse",
     "m": {
      "ar": "محفظة",
      "en": "a small case for money"
     },
     "ex": "I left my wallet at home."
    },
    {
     "t": "save / spend",
     "m": {
      "ar": "يحوّش / يصرف",
      "en": "to keep money / to use money"
     },
     "ex": "I save 10% of my salary."
    },
    {
     "t": "tip",
     "m": {
      "ar": "بقشيش",
      "en": "extra money for good service"
     },
     "ex": "We left a tip for the waiter."
    }
   ],
   "read": [
    {
     "t": "News in Levels",
     "url": "https://www.newsinlevels.com/",
     "what": {
      "ar": "اقرا خبر level 2 عن الفلوس أو الشغل واسمعه.",
      "en": "Read and listen to a level-2 story about money or work."
     }
    }
   ],
   "challenge": {
    "ar": "اعمل «freelance kit» بالإنجليزي: قالب proposal، وقالب تأكيد اتفاق، وقالب invoice، وقالب تذكير بالدفع.",
    "en": "Build an English \"freelance kit\": a proposal template, an agreement confirmation, an invoice template and a payment reminder."
   },
   "quiz": [
    {
     "q": {
      "ar": "«50% upfront» معناها:",
      "en": "\"50% upfront\" means:"
     },
     "o": [
      {
       "ar": "نص المبلغ قبل البداية",
       "en": "half the amount before starting"
      },
      {
       "ar": "نص المبلغ في الآخر",
       "en": "half at the end"
      },
      {
       "ar": "خصم 50%",
       "en": "a 50% discount"
      }
     ],
     "a": 0,
     "why": {
      "ar": "upfront = مقدّمًا.",
      "en": "upfront = in advance."
     }
    },
    {
     "q": {
      "ar": "«Keep the change» معناها:",
      "en": "\"Keep the change\" means:"
     },
     "o": [
      {
       "ar": "خلّي الباقي",
       "en": "keep the rest of the money"
      },
      {
       "ar": "متغيّرش حاجة",
       "en": "don't change anything"
      },
      {
       "ar": "رجّع الفلوس",
       "en": "give the money back"
      }
     ],
     "a": 0,
     "why": {
      "ar": "change = الفكة / الباقي.",
      "en": "change = the money you get back."
     }
    },
    {
     "q": {
      "ar": "أول جملة في إيميل تأكيد:",
      "en": "The first line of a confirmation email:"
     },
     "o": [
      "Just to confirm what we agreed:",
      "Hey you,",
      "Why so expensive?"
     ],
     "a": 0,
     "why": {
      "ar": "بتلخص الاتفاق.",
      "en": "It sums up the agreement."
     }
    }
   ],
   "minutes": 120
  },
  {
   "d": 6,
   "title": {
    "ar": "مراجعة الشهر الرابع والاختبار",
    "en": "Month 4 review and test"
   },
   "goal": {
    "ar": "راجع الأسبوع والشهر كله، وسلّم مشروع الشهر، وخد الاختبار. الأسبوع 17 بيفتح لما تجيب 70% أو أكتر.",
    "en": "Review the week and the whole month, hand in the month project, and take the test. Week 17 opens when you score 70% or more."
   },
   "review": [
    {
     "ar": "الشات: اختصارات، ونبرة، وطلب مساعدة كامل.",
     "en": "Chat: abbreviations, tone, and a complete help request."
    },
    {
     "ar": "الاجتماعات: agenda، stand-up، مكالمات الفيديو، action items، reported speech.",
     "en": "Meetings: agenda, stand-up, video calls, action items, reported speech."
    },
    {
     "ar": "الريفيو: ملاحظة + سبب + اقتراح، وBig O، والرد بثقة.",
     "en": "Review: observation + reason + suggestion, Big O, and confident replies."
    },
    {
     "ar": "العميل: proposal، وout of scope، وتفاوض بـ if، ورفض بأدب.",
     "en": "Clients: proposals, out of scope, negotiating with if, and saying no politely."
    },
    {
     "ar": "الفلوس: price / cost / fee، والدفع، وتأكيد الاتفاق.",
     "en": "Money: price / cost / fee, payment, and confirming the agreement."
    }
   ],
   "project": {
    "ar": "مشروع الشهر: «من أول رسالة لحد الاتفاق»: اكتب كل المراسلات مع عميل متخيّل لمشروع أتمتة: رد على أول رسالة، وأسئلة توضيح، وproposal كامل، ورد على طلب خصم بتفاوض، ورفض بأدب لطلب بره النطاق، وإيميل تأكيد اتفاق فيه شروط الدفع، وأول invoice. وبعدين مثّل مكالمة التفاوض بصوتك.",
    "en": "Month project: \"from the first message to the deal\": write all the correspondence with an imagined client for an automation project — a reply to the first message, clarifying questions, a full proposal, a negotiating reply to a discount request, a polite no to an out-of-scope request, an agreement confirmation with payment terms, and the first invoice. Then act out the negotiation call in your own voice."
   },
   "test": [
    {
     "q": {
      "ar": "FYI معناها:",
      "en": "FYI means:"
     },
     "o": [
      "for your information",
      "fix your issue",
      "from yesterday"
     ],
     "a": 0,
     "why": {
      "ar": "للعلم.",
      "en": "for your information."
     }
    },
    {
     "q": {
      "ar": "اختار الصح:",
      "en": "Choose the correct one:"
     },
     "o": [
      "Please log in to your account.",
      "Please login to your account.",
      "Please log-in to your account."
     ],
     "a": 0,
     "why": {
      "ar": "فعل = log in.",
      "en": "Verb = log in."
     }
    },
    {
     "q": {
      "ar": "في الـ stand-up بتقول:",
      "en": "In the stand-up you say:"
     },
     "o": [
      {
       "ar": "امبارح، والنهارده، والعوائق",
       "en": "yesterday, today and blockers"
      },
      {
       "ar": "حياتك الشخصية",
       "en": "your personal life"
      },
      {
       "ar": "كل الكود",
       "en": "all the code"
      }
     ],
     "a": 0,
     "why": {
      "ar": "التلات أسئلة.",
      "en": "The three questions."
     }
    },
    {
     "q": {
      "ar": "اختار الصح:",
      "en": "Choose the correct one:"
     },
     "o": [
      "She told me the demo went well.",
      "She said me the demo went well.",
      "She told that me the demo went well."
     ],
     "a": 0,
     "why": {
      "ar": "tell + شخص.",
      "en": "tell + person."
     }
    },
    {
     "q": {
      "ar": "أحسن تعليق ريفيو:",
      "en": "The best review comment:"
     },
     "o": [
      "This is terrible.",
      "Could we move this query outside the loop? It runs 100 times now.",
      "Fix it."
     ],
     "a": 1,
     "why": {
      "ar": "اقتراح + سبب.",
      "en": "A suggestion + a reason."
     }
    },
    {
     "q": {
      "ar": "O(n) معناها:",
      "en": "O(n) means:"
     },
     "o": [
      "linear time",
      "constant time",
      "no time"
     ],
     "a": 0,
     "why": {
      "ar": "الوقت بيزيد مع حجم البيانات.",
      "en": "Time grows with the data size."
     }
    },
    {
     "q": {
      "ar": "Out of scope معناها:",
      "en": "Out of scope means:"
     },
     "o": [
      {
       "ar": "مش ضمن الشغل المتفق عليه",
       "en": "not part of the agreed work"
      },
      {
       "ar": "مش شغال",
       "en": "not working"
      },
      {
       "ar": "بره المكتب",
       "en": "out of the office"
      }
     ],
     "a": 0,
     "why": {
      "ar": "بره النطاق.",
      "en": "Outside the agreed scope."
     }
    },
    {
     "q": {
      "ar": "تنازل ذكي في التفاوض:",
      "en": "A smart concession:"
     },
     "o": [
      "OK, half price.",
      "If you sign for 12 months, we can offer 10% off.",
      "Fine, free."
     ],
     "a": 1,
     "why": {
      "ar": "مقابل حاجة.",
      "en": "In exchange for something."
     }
    },
    {
     "q": {
      "ar": "أحسن رفض لموعد:",
      "en": "The best way to decline a deadline:"
     },
     "o": [
      "No way.",
      "I'm afraid Friday isn't realistic, but we could deliver the first part then.",
      "Maybe."
     ],
     "a": 1,
     "why": {
      "ar": "صادق وبديل.",
      "en": "Honest, with an alternative."
     }
    },
    {
     "q": {
      "ar": "fee معناها:",
      "en": "fee means:"
     },
     "o": [
      {
       "ar": "رسوم خدمة",
       "en": "a service charge"
      },
      {
       "ar": "مجاني",
       "en": "free"
      },
      {
       "ar": "خصم",
       "en": "a discount"
      }
     ],
     "a": 0,
     "why": {
      "ar": "platform fee، bank fee.",
      "en": "platform fee, bank fee."
     }
    },
    {
     "q": {
      "ar": "اختار الصح:",
      "en": "Choose the correct one:"
     },
     "o": [
      "The price is USD 500, including a 10% discount.",
      "The price is 500$USD include discount.",
      "Price 500 including."
     ],
     "a": 0,
     "why": {
      "ar": "جملة كاملة ومبلغ مكتوب صح.",
      "en": "A full sentence and a correctly written amount."
     }
    },
    {
     "q": {
      "ar": "«Just to confirm what we agreed» بتستخدمها في:",
      "en": "\"Just to confirm what we agreed\" is used in:"
     },
     "o": [
      {
       "ar": "إيميل تأكيد اتفاق",
       "en": "an agreement confirmation email"
      },
      {
       "ar": "شكوى",
       "en": "a complaint"
      },
      {
       "ar": "اعتذار",
       "en": "an apology"
      }
     ],
     "a": 0,
     "why": {
      "ar": "بتلخص الاتفاق كتابة.",
      "en": "It records the agreement in writing."
     }
    }
   ],
   "minutes": 120
  }
 ]
});
