// Week 21 — generated by tools/build_weeks.js from content/english/src/w21.js. Edit the source, not this file.
JOURNEY.week({
 "track": "english",
 "n": 21,
 "month": 6,
 "level": "B2 → C1",
 "title": {
  "ar": "المقابلات التقنية",
  "en": "Technical interviews"
 },
 "goal": {
  "ar": "تجهّز CV وcover letter بالإنجليزي، وتعدّي مقابلة: تعريف نفسك، وأسئلة السلوك بطريقة STAR، والجزء التقني وانت بتفكر بصوت عالي، وتسأل أسئلتك في الآخر.",
  "en": "Prepare an English CV and cover letter, and get through an interview: introducing yourself, behavioural questions with STAR, the technical round while thinking aloud, and your own questions at the end."
 },
 "days": [
  {
   "d": 1,
   "title": {
    "ar": "الـ CV",
    "en": "The CV"
   },
   "goal": {
    "ar": "تكتب CV تقني بإنجليزي قوي: أفعال إنجاز، وأرقام، وسطر واحد لكل إنجاز.",
    "en": "Write a technical CV in strong English: achievement verbs, numbers, one line per achievement."
   },
   "learn": [
    {
     "h": {
      "ar": "سطر الإنجاز",
      "en": "The achievement line"
     },
     "p": {
      "ar": "فعل ماضي قوي + اللي عملته + النتيجة بالأرقام. من غير I ومن غير «Responsible for». Built، Automated، Reduced، Led، Migrated، Improved.",
      "en": "A strong past verb + what you did + the result in numbers. No \"I\", no \"Responsible for\". Built, Automated, Reduced, Led, Migrated, Improved."
     },
     "ex": "✗ Responsible for reports.\n✓ Automated weekly sales reports with n8n, saving 5 hours a week.\n✓ Reduced API errors by 60% by adding retries and alerts."
    },
    {
     "h": {
      "ar": "أقسام الـ CV",
      "en": "CV sections"
     },
     "p": {
      "ar": "Name + job title + links، Summary (سطرين)، Skills، Experience (الأحدث الأول)، Projects، Education. صفحة واحدة لو خبرتك أقل من 5 سنين.",
      "en": "Name + job title + links, Summary (two lines), Skills, Experience (newest first), Projects, Education. One page if you have under 5 years of experience."
     },
     "ex": "Automation Developer | n8n · Python · SQL\nSummary: Developer who builds reliable automations for small businesses."
    },
    {
     "h": {
      "ar": "Present perfect ولا past simple",
      "en": "Present perfect or past simple"
     },
     "p": {
      "ar": "لو ذكرت وقت محدد خلص (yesterday, last week, in 2024) استخدم past simple. من غير وقت أو لحد دلوقتي استخدم present perfect.",
      "en": "With a finished time (yesterday, last week, in 2024) use the past simple. With no time, or up to now, use the present perfect."
     },
     "ex": "✗ I have fixed it yesterday.\n✓ I fixed it yesterday."
    }
   ],
   "practice": [
    {
     "ar": "اكتب 6 سطور إنجاز لشغلك أو مشاريعك بالقالب وبأرقام.",
     "en": "Write 6 achievement lines for your work or projects with the template and numbers."
    },
    {
     "ar": "اكتب Summary من سطرين بالإنجليزي.",
     "en": "Write a two-line summary in English."
    },
    {
     "ar": "حوّل 4 سطور «Responsible for…» لسطور إنجاز.",
     "en": "Turn 4 \"Responsible for…\" lines into achievement lines."
    },
    {
     "ar": "اكتب cover letter من 3 فقرات لوظيفة حقيقية شايفها.",
     "en": "Write a three-paragraph cover letter for a real job ad you have seen."
    }
   ],
   "words": [
    {
     "t": "resume / CV",
     "m": {
      "ar": "السيرة الذاتية",
      "en": "a document about your work history"
     },
     "ex": "Keep your CV to one or two pages."
    },
    {
     "t": "cover letter",
     "m": {
      "ar": "خطاب التقديم",
      "en": "a letter sent with your CV"
     },
     "ex": "Write a short cover letter for each job."
    },
    {
     "t": "job title",
     "m": {
      "ar": "المسمّى الوظيفي",
      "en": "the name of your position"
     },
     "ex": "My job title is automation developer."
    },
    {
     "t": "position / role",
     "m": {
      "ar": "وظيفة / دور",
      "en": "a job"
     },
     "ex": "I'm applying for the backend role."
    },
    {
     "t": "vacancy / opening",
     "m": {
      "ar": "وظيفة فاضية",
      "en": "a job that is available"
     },
     "ex": "There is an opening for a junior developer."
    },
    {
     "t": "apply / applicant",
     "m": {
      "ar": "يقدّم / المتقدّم",
      "en": "to ask for a job / a person who asks"
     },
     "ex": "Over 200 applicants applied for the job."
    },
    {
     "t": "candidate",
     "m": {
      "ar": "مرشّح",
      "en": "a person being considered for a job"
     },
     "ex": "She is the best candidate for the role."
    }
   ],
   "read": [
    {
     "t": "Tech Interview Handbook",
     "url": "https://www.techinterviewhandbook.org/",
     "what": {
      "ar": "اقرا قسم «Resume» وطبّق 3 نصايح على الـ CV بتاعك.",
      "en": "Read the \"Resume\" section and apply 3 tips to your CV."
     }
    }
   ],
   "challenge": {
    "ar": "اكتب CV كامل بالإنجليزي من صفحة واحدة، وخلّي حد يقراه 30 ثانية ويقولك فاكر إيه.",
    "en": "Write a complete one-page English CV and ask someone to read it for 30 seconds and tell you what they remember."
   },
   "quiz": [
    {
     "q": {
      "ar": "أحسن سطر CV:",
      "en": "The best CV line:"
     },
     "o": [
      "Responsible for the database.",
      "Migrated the database to Postgres, cutting query time by 40%.",
      "I did database stuff."
     ],
     "a": 1,
     "why": {
      "ar": "فعل + عمل + نتيجة بالأرقام.",
      "en": "Verb + work + a result in numbers."
     }
    },
    {
     "q": {
      "ar": "cover letter هو:",
      "en": "A cover letter is:"
     },
     "o": [
      {
       "ar": "رسالة بتشرح ليه انت مناسب للوظيفة",
       "en": "a letter explaining why you fit the job"
      },
      {
       "ar": "غلاف الـ CV",
       "en": "the CV cover page"
      },
      {
       "ar": "عقد",
       "en": "a contract"
      }
     ],
     "a": 0,
     "why": {
      "ar": "بيتبعت مع الـ CV.",
      "en": "It goes with the CV."
     }
    },
    {
     "q": {
      "ar": "في الـ CV، الخبرة بتترتب:",
      "en": "In a CV, experience is ordered:"
     },
     "o": [
      {
       "ar": "الأحدث الأول",
       "en": "newest first"
      },
      {
       "ar": "الأقدم الأول",
       "en": "oldest first"
      },
      {
       "ar": "عشوائي",
       "en": "randomly"
      }
     ],
     "a": 0,
     "why": {
      "ar": "reverse chronological.",
      "en": "reverse chronological."
     }
    }
   ],
   "minutes": 120
  },
  {
   "d": 2,
   "title": {
    "ar": "مراحل التوظيف",
    "en": "The hiring process"
   },
   "goal": {
    "ar": "تفهم مراحل التوظيف وكلامها، وتكتب رسايل للـ recruiter.",
    "en": "Understand the stages of hiring and their language, and write messages to recruiters."
   },
   "learn": [
    {
     "h": {
      "ar": "المراحل",
      "en": "The stages"
     },
     "p": {
      "ar": "Application ← HR screen (مكالمة قصيرة) ← technical round (كود أو تصميم) ← take-home task (مهمة في البيت) ← final round ← offer.",
      "en": "Application → HR screen (a short call) → technical round (coding or design) → take-home task → final round → offer."
     },
     "ex": "I've passed the HR screen, and the technical round is next Tuesday."
    },
    {
     "h": {
      "ar": "رسالة لـ recruiter",
      "en": "A message to a recruiter"
     },
     "p": {
      "ar": "قصيرة ومحددة: الوظيفة، وليه مناسب في جملة، ولينك الـ CV. Hi Omar, I saw the Junior Automation Developer opening. I've built 10+ n8n workflows for small businesses. Could we have a short call?",
      "en": "Short and specific: the role, why you fit in one sentence, and your CV link. Hi Omar, I saw the Junior Automation Developer opening. I've built 10+ n8n workflows for small businesses. Could we have a short call?"
     },
     "ex": "Thank you for the update. I'm available on Monday or Wednesday afternoon."
    },
    {
     "h": {
      "ar": "أنواع الشغل",
      "en": "Types of work"
     },
     "p": {
      "ar": "full-time، part-time، freelance، internship، entry-level (بداية)، contract (مدة محددة)، remote.",
      "en": "full-time, part-time, freelance, internship, entry-level, contract (fixed term), remote."
     },
     "ex": "I'm looking for an entry-level, full-time role, but I'm open to a paid internship."
    }
   ],
   "practice": [
    {
     "ar": "اكتب رسالة LinkedIn لـ recruiter عن وظيفة حقيقية.",
     "en": "Write a LinkedIn message to a recruiter about a real opening."
    },
    {
     "ar": "اكتب رد على دعوة مقابلة فيه ميعادين متاحين.",
     "en": "Write a reply to an interview invitation with two available times."
    },
    {
     "ar": "اكتب 5 جمل عن نوع الشغل اللي بتدوّر عليه.",
     "en": "Write 5 sentences about the kind of work you are looking for."
    },
    {
     "ar": "اقرا 3 إعلانات وظايف واكتب Qualifications كل واحدة في 3 سطور.",
     "en": "Read 3 job ads and write each one's qualifications in 3 lines."
    }
   ],
   "words": [
    {
     "t": "recruiter / HR",
     "m": {
      "ar": "مسؤول التوظيف / الموارد البشرية",
      "en": "a person who finds people for jobs"
     },
     "ex": "The recruiter called me for a first interview."
    },
    {
     "t": "fresher / entry-level",
     "m": {
      "ar": "خريج جديد / مستوى مبتدئ",
      "en": "a new graduate / the first level"
     },
     "ex": "This is an entry-level role for freshers."
    },
    {
     "t": "internship",
     "m": {
      "ar": "تدريب",
      "en": "a short training job"
     },
     "ex": "I did a three-month internship."
    },
    {
     "t": "full-time / part-time",
     "m": {
      "ar": "دوام كامل / دوام جزئي",
      "en": "a whole working week / some hours only"
     },
     "ex": "The job is part-time, 20 hours a week."
    },
    {
     "t": "freelance",
     "m": {
      "ar": "شغل حر",
      "en": "working for yourself for different clients"
     },
     "ex": "I work freelance on automation projects."
    },
    {
     "t": "qualifications",
     "m": {
      "ar": "المؤهلات",
      "en": "degrees, courses and certificates"
     },
     "ex": "List your qualifications and certificates."
    },
    {
     "t": "degree",
     "m": {
      "ar": "شهادة جامعية",
      "en": "a university qualification"
     },
     "ex": "I have a degree in computer science."
    }
   ],
   "read": [
    {
     "t": "LinkedIn Jobs",
     "url": "https://www.linkedin.com/jobs/",
     "what": {
      "ar": "دوّر على وظيفة بمهاراتك واقرا الإعلان كله، وعلّم الكلمات الجديدة.",
      "en": "Search for a job with your skills, read the whole ad and mark the new words."
     }
    }
   ],
   "challenge": {
    "ar": "قدّم فعلًا على وظيفة واحدة بالإنجليزي (CV + cover letter أو رسالة).",
    "en": "Actually apply for one job in English (a CV + cover letter or a message)."
   },
   "quiz": [
    {
     "q": {
      "ar": "HR screen هو:",
      "en": "An HR screen is:"
     },
     "o": [
      {
       "ar": "مكالمة أولى قصيرة مع الـ HR",
       "en": "a short first call with HR"
      },
      {
       "ar": "شاشة كمبيوتر",
       "en": "a computer screen"
      },
      {
       "ar": "اختبار كود",
       "en": "a coding test"
      }
     ],
     "a": 0,
     "why": {
      "ar": "أول مرحلة غالبًا.",
      "en": "Usually the first stage."
     }
    },
    {
     "q": {
      "ar": "entry-level يعني:",
      "en": "entry-level means:"
     },
     "o": [
      {
       "ar": "وظيفة للمبتدئين",
       "en": "a job for beginners"
      },
      {
       "ar": "وظيفة مدير",
       "en": "a manager role"
      },
      {
       "ar": "باب الدخول",
       "en": "an entrance"
      }
     ],
     "a": 0,
     "why": {
      "ar": "خبرة قليلة.",
      "en": "Little experience needed."
     }
    },
    {
     "q": {
      "ar": "take-home task هي:",
      "en": "A take-home task is:"
     },
     "o": [
      {
       "ar": "مهمة بتعملها في البيت وتسلّمها",
       "en": "a task you do at home and submit"
      },
      {
       "ar": "أكل تيك أواي",
       "en": "takeaway food"
      },
      {
       "ar": "أجازة",
       "en": "a holiday"
      }
     ],
     "a": 0,
     "why": {
      "ar": "جزء من المقابلة التقنية.",
      "en": "Part of the technical process."
     }
    }
   ],
   "minutes": 120
  },
  {
   "d": 3,
   "title": {
    "ar": "أسئلة السلوك بطريقة STAR",
    "en": "Behavioural questions with STAR"
   },
   "goal": {
    "ar": "ترد على «Tell me about a time…» بقصة STAR قصيرة ومرتبة.",
    "en": "Answer \"Tell me about a time…\" with a short, well-ordered STAR story."
   },
   "learn": [
    {
     "h": {
      "ar": "STAR",
      "en": "STAR"
     },
     "p": {
      "ar": "Situation (الموقف، جملة)، Task (المطلوب منك)، Action (عملت إيه انت، أطول جزء)، Result (النتيجة بالأرقام + اتعلمت إيه). بالماضي البسيط، وبـ I مش we.",
      "en": "Situation (one sentence), Task (what you had to do), Action (what YOU did — the longest part), Result (the outcome in numbers + what you learned). Past simple, and \"I\", not \"we\"."
     },
     "ex": "S: Our daily report failed silently for a week.\nT: I had to find the cause and stop it happening again.\nA: I read the logs, found an expired token, and added an error workflow with Telegram alerts.\nR: We haven't missed a report since, and I now add alerts to every workflow."
    },
    {
     "h": {
      "ar": "تعريف نفسك",
      "en": "\"Tell me about yourself\""
     },
     "p": {
      "ar": "60–90 ثانية: الحاضر (بتعمل إيه)، الماضي (إزاي وصلت)، المستقبل (ليه الوظيفة دي). مش قصة حياتك.",
      "en": "60–90 seconds: present (what you do), past (how you got here), future (why this role). Not your life story."
     },
     "ex": "I'm an automation developer. I started with Python scripts for my family's shop, then moved to n8n. I'd like to join a team where I can automate at a larger scale."
    },
    {
     "h": {
      "ar": "نقاط القوة والضعف",
      "en": "Strengths and weaknesses"
     },
     "p": {
      "ar": "القوة بمثال: I'm good at breaking big problems down — for example… والضعف حقيقي ومعاه خطة: I used to take on too much; now I estimate tasks and say no earlier.",
      "en": "A strength with an example: I'm good at breaking big problems down — for example… A real weakness with a plan: I used to take on too much; now I estimate tasks and say no earlier."
     },
     "ex": "My English writing was weak, so I've been writing all my commits and docs in English for six months."
    }
   ],
   "practice": [
    {
     "ar": "اكتب 3 قصص STAR: مشكلة صعبة، وخلاف مع زميل، وحاجة فشلت.",
     "en": "Write 3 STAR stories: a hard problem, a disagreement with a colleague, and something that failed."
    },
    {
     "ar": "اكتب وسجّل «Tell me about yourself» في 90 ثانية.",
     "en": "Write and record \"Tell me about yourself\" in 90 seconds."
    },
    {
     "ar": "اكتب نقطة قوة ونقطة ضعف بأمثلة.",
     "en": "Write a strength and a weakness with examples."
    },
    {
     "ar": "اكتب 7 جمل بكلمات النهارده عن خبرتك.",
     "en": "Write 7 sentences about your experience with today's words."
    }
   ],
   "words": [
    {
     "t": "background",
     "m": {
      "ar": "خلفيتك (تعليم وخبرة)",
      "en": "Your background (education and experience)"
     },
     "ex": "My background is in accounting and automation."
    },
    {
     "t": "responsible for",
     "m": {
      "ar": "مسؤول عن",
      "en": "In charge of"
     },
     "ex": "I was responsible for the database design."
    },
    {
     "t": "achieve",
     "m": {
      "ar": "يحقق",
      "en": "To accomplish"
     },
     "ex": "We achieved a 40% faster response time."
    },
    {
     "t": "improve",
     "m": {
      "ar": "يحسّن",
      "en": "To make better"
     },
     "ex": "I improved the report so it runs in 2 minutes."
    },
    {
     "t": "challenge",
     "m": {
      "ar": "تحدي / صعوبة",
      "en": "A difficulty"
     },
     "ex": "The biggest challenge was messy data."
    },
    {
     "t": "strength / weakness",
     "m": {
      "ar": "نقطة قوة / نقطة ضعف",
      "en": "A strong point / a weak point"
     },
     "ex": "My strength is solving problems step by step."
    },
    {
     "t": "collaborate",
     "m": {
      "ar": "يتعاون",
      "en": "To work together"
     },
     "ex": "I collaborated with the sales team."
    }
   ],
   "read": [
    {
     "t": "Tech Interview Handbook",
     "url": "https://www.techinterviewhandbook.org/",
     "what": {
      "ar": "اقرا قسم «Behavioral interviews» والأسئلة الشائعة.",
      "en": "Read the \"Behavioral interviews\" section and the common questions."
     }
    }
   ],
   "challenge": {
    "ar": "خلّي حد يسألك 3 أسئلة سلوك عشوائي، ورد بـ STAR من غير ورقة، وسجّل.",
    "en": "Have someone ask you 3 random behavioural questions; answer with STAR without notes, and record it."
   },
   "quiz": [
    {
     "q": {
      "ar": "أطول جزء في STAR:",
      "en": "The longest part of STAR:"
     },
     "o": [
      "Situation",
      "Action",
      "Result"
     ],
     "a": 1,
     "why": {
      "ar": "عملت إيه انت.",
      "en": "What you did."
     }
    },
    {
     "q": {
      "ar": "في قصة STAR، الأحسن تقول:",
      "en": "In a STAR story, it is better to say:"
     },
     "o": [
      "We did everything.",
      "I found the cause and added alerts.",
      "The team maybe did it."
     ],
     "a": 1,
     "why": {
      "ar": "دورك انت.",
      "en": "Your own role."
     }
    },
    {
     "q": {
      "ar": "«Tell me about yourself» مدته المناسبة:",
      "en": "A good length for \"Tell me about yourself\":"
     },
     "o": [
      {
       "ar": "دقيقة لدقيقة ونص",
       "en": "60–90 seconds"
      },
      {
       "ar": "10 دقايق",
       "en": "10 minutes"
      },
      {
       "ar": "جملة واحدة",
       "en": "one sentence"
      }
     ],
     "a": 0,
     "why": {
      "ar": "مختصر ومرتب.",
      "en": "Short and structured."
     }
    }
   ],
   "minutes": 120
  },
  {
   "d": 4,
   "title": {
    "ar": "الجزء التقني",
    "en": "The technical round"
   },
   "goal": {
    "ar": "تفكر بصوت عالي بالإنجليزي وانت بتحل: تفهم السؤال، وتقول الفكرة، وتكتب، وتختبر، وتتكلم عن الـ complexity.",
    "en": "Think aloud in English while solving: understand the question, state the idea, code, test, and discuss complexity."
   },
   "learn": [
    {
     "h": {
      "ar": "فكّر بصوت عالي",
      "en": "Think out loud"
     },
     "p": {
      "ar": "1) Let me make sure I understand… (تعيد السؤال). 2) Can I assume…? (افتراضات). 3) My first idea is… (الفكرة). 4) Let me code it. 5) Let me test it with… 6) The time complexity is…",
      "en": "1) Let me make sure I understand… (restate). 2) Can I assume…? (assumptions). 3) My first idea is… (approach). 4) Let me code it. 5) Let me test it with… 6) The time complexity is…"
     },
     "ex": "So the input is a sorted list and a target. Can I assume there are no duplicates?\nMy first idea is binary search, which is O(log n)."
    },
    {
     "h": {
      "ar": "لو اتزنقت",
      "en": "If you get stuck"
     },
     "p": {
      "ar": "I'm stuck on… Could I get a hint? / Let me try a simpler case first. / A brute-force solution would be…, then I'll optimise. السكوت أسوأ من «مش عارف».",
      "en": "I'm stuck on… Could I get a hint? / Let me try a simpler case first. / A brute-force solution would be…, then I'll optimise. Silence is worse than saying you're stuck."
     },
     "ex": "A brute-force solution is O(n²). I think a set can make it O(n)."
    },
    {
     "h": {
      "ar": "مصطلحات تقنية شائعة",
      "en": "Common technical terms"
     },
     "p": {
      "ar": "binary search، sorting algorithm، tree / binary tree، graph، matrix، vector، DBMS / RDBMS.",
      "en": "binary search, sorting algorithm, tree / binary tree, graph, matrix, vector, DBMS / RDBMS."
     },
     "ex": "I'd store the rows in a relational database and index the email column."
    }
   ],
   "practice": [
    {
     "ar": "حل مسألة سهلة (two sum) وسجّل نفسك بتفكر بصوت عالي بالـ 6 خطوات.",
     "en": "Solve an easy problem (two sum) and record yourself thinking aloud through the 6 steps."
    },
    {
     "ar": "اكتب 5 افتراضات ممكن تسأل عنها في مسألة.",
     "en": "Write 5 assumptions you might ask about in a problem."
    },
    {
     "ar": "اشرح binary search في 4 جمل.",
     "en": "Explain binary search in 4 sentences."
    },
    {
     "ar": "اكتب 3 جمل «لو اتزنقت» وقولها.",
     "en": "Write 3 \"if I'm stuck\" sentences and say them."
    }
   ],
   "words": [
    {
     "t": "tree / binary tree",
     "m": {
      "ar": "شجرة / شجرة ثنائية",
      "en": "a hierarchy of nodes"
     },
     "ex": "Folders form a tree."
    },
    {
     "t": "graph (data structure)",
     "m": {
      "ar": "رسم بياني (عقد ووصلات)",
      "en": "nodes connected by edges"
     },
     "ex": "A map app uses a graph of roads."
    },
    {
     "t": "binary search",
     "m": {
      "ar": "بحث ثنائي",
      "en": "searching by halving a sorted list"
     },
     "ex": "Binary search only works on sorted data."
    },
    {
     "t": "sorting algorithm",
     "m": {
      "ar": "خوارزمية ترتيب",
      "en": "a method to order data"
     },
     "ex": "Merge sort is a fast sorting algorithm."
    },
    {
     "t": "matrix",
     "m": {
      "ar": "مصفوفة ثنائية (صفوف وأعمدة)",
      "en": "a grid of rows and columns"
     },
     "ex": "A spreadsheet is like a matrix."
    },
    {
     "t": "vector",
     "m": {
      "ar": "متجه / مصفوفة ديناميكية",
      "en": "a list of numbers"
     },
     "ex": "Embeddings are stored as vectors."
    },
    {
     "t": "DBMS / RDBMS",
     "m": {
      "ar": "نظام إدارة قواعد البيانات",
      "en": "database management system"
     },
     "ex": "PostgreSQL is an RDBMS."
    }
   ],
   "read": [
    {
     "t": "Exercism",
     "url": "https://exercism.org/",
     "what": {
      "ar": "حل تمرين واحد وانت بتكتب تعليق إنجليزي بتفكيرك قبل الكود.",
      "en": "Solve one exercise, writing an English comment with your thinking before the code."
     }
    }
   ],
   "challenge": {
    "ar": "اعمل mock interview تقني (25 دقيقة) مع صاحب أو لوحدك بتايمر، وسجّل الصوت، واكتب 3 حاجات تحسّنها.",
    "en": "Do a 25-minute mock technical interview with a friend or alone with a timer, record the audio, and write 3 things to improve."
   },
   "quiz": [
    {
     "q": {
      "ar": "أول خطوة في مسألة المقابلة:",
      "en": "The first step in an interview problem:"
     },
     "o": [
      {
       "ar": "تتأكد إنك فاهم السؤال",
       "en": "make sure you understand the question"
      },
      {
       "ar": "تكتب كود على طول",
       "en": "start coding at once"
      },
      {
       "ar": "تسكت",
       "en": "stay silent"
      }
     ],
     "a": 0,
     "why": {
      "ar": "restate + assumptions.",
      "en": "restate + assumptions."
     }
    },
    {
     "q": {
      "ar": "لو اتزنقت:",
      "en": "If you get stuck:"
     },
     "o": [
      "Stay silent for 5 minutes.",
      "Say what you're stuck on and try a simpler case.",
      "Give up."
     ],
     "a": 1,
     "why": {
      "ar": "خلّي تفكيرك مسموع.",
      "en": "Keep your thinking audible."
     }
    },
    {
     "q": {
      "ar": "binary search بتشتغل على:",
      "en": "Binary search works on:"
     },
     "o": [
      {
       "ar": "قايمة مرتبة",
       "en": "a sorted list"
      },
      {
       "ar": "أي قايمة",
       "en": "any list"
      },
      {
       "ar": "نص",
       "en": "a string only"
      }
     ],
     "a": 0,
     "why": {
      "ar": "بتقسم النص كل مرة.",
      "en": "It halves the search space each time."
     }
    }
   ],
   "minutes": 120
  },
  {
   "d": 5,
   "title": {
    "ar": "يوم المقابلة",
    "en": "Interview day"
   },
   "goal": {
    "ar": "تبدأ المقابلة بـ small talk، وترد على أسئلة الخبرة، وتسأل أسئلتك، وتبعت شكر بعدها.",
    "en": "Start with small talk, answer experience questions, ask your own questions, and send a thank-you afterwards."
   },
   "learn": [
    {
     "h": {
      "ar": "أسئلتك في الآخر",
      "en": "Your questions at the end"
     },
     "p": {
      "ar": "What does a typical day look like? / How do you measure success in this role? / What's the biggest challenge for the team right now? / What are the next steps? ومتسألش عن المرتب في أول مقابلة.",
      "en": "What does a typical day look like? / How do you measure success in this role? / What's the biggest challenge for the team right now? / What are the next steps? Don't ask about salary in the first interview."
     },
     "ex": "How does the team review code? / How is on-call organised?"
    },
    {
     "h": {
      "ar": "إيميل الشكر",
      "en": "The thank-you email"
     },
     "p": {
      "ar": "في نفس اليوم: شكر، وحاجة معينة عجبتك في الكلام، وجملة إنك متحمس. 4 سطور.",
      "en": "The same day: thanks, one specific thing you liked in the conversation, and a sentence saying you're excited. Four lines."
     },
     "ex": "Thank you for your time today. I enjoyed hearing about how you use n8n for customer onboarding. I'm excited about the role and look forward to the next steps."
    },
    {
     "h": "look forward to + ing",
     "p": {
      "ar": "to هنا حرف جر، فبعدها ing مش المصدر.",
      "en": "to here is a preposition, so it is followed by -ing."
     },
     "ex": "✗ I look forward to hear from you.\n✓ I look forward to hearing from you."
    }
   ],
   "practice": [
    {
     "ar": "اكتب 6 أسئلة هتسألها في آخر مقابلة.",
     "en": "Write 6 questions to ask at the end of an interview."
    },
    {
     "ar": "اكتب إيميل شكر بعد مقابلة (حقيقية أو متخيّلة).",
     "en": "Write a thank-you email after an interview (real or imagined)."
    },
    {
     "ar": "اكتب 4 جمل small talk لأول دقيقة في المقابلة.",
     "en": "Write 4 small-talk sentences for the first minute of an interview."
    },
    {
     "ar": "اكتب «competencies» بتاعتك: 5 soft skills بمثال لكل واحدة.",
     "en": "Write your competencies: 5 soft skills with an example each."
    }
   ],
   "words": [
    {
     "t": "work experience",
     "m": {
      "ar": "الخبرة العملية",
      "en": "the jobs you have done"
     },
     "ex": "Put your work experience first on your CV."
    },
    {
     "t": "achievement",
     "m": {
      "ar": "إنجاز",
      "en": "something you did well"
     },
     "ex": "Mention one achievement with a number."
    },
    {
     "t": "competencies / soft skills",
     "m": {
      "ar": "الكفاءات / المهارات الشخصية",
      "en": "personal skills for working with others"
     },
     "ex": "Teamwork and communication are soft skills."
    },
    {
     "t": "aptitude test",
     "m": {
      "ar": "اختبار قدرات",
      "en": "a test of logic and ability"
     },
     "ex": "The first round is an online aptitude test."
    },
    {
     "t": "technical round / HR round",
     "m": {
      "ar": "مقابلة فنية / مقابلة الموارد البشرية",
      "en": "the interview about skills / about you and the company"
     },
     "ex": "The technical round has coding questions."
    },
    {
     "t": "group discussion",
     "m": {
      "ar": "نقاش جماعي",
      "en": "a task where candidates discuss a topic"
     },
     "ex": "Speak clearly in the group discussion."
    },
    {
     "t": "interviewer",
     "m": {
      "ar": "اللي بيعمل المقابلة",
      "en": "the person who asks the questions"
     },
     "ex": "Ask the interviewer about the team."
    }
   ],
   "read": [
    {
     "t": "Microsoft Learn: Career paths",
     "url": "https://learn.microsoft.com/en-us/training/career-paths/",
     "what": {
      "ar": "اختار career path قريب منك واقرا المهارات المطلوبة.",
      "en": "Pick a career path close to yours and read the required skills."
     }
    }
   ],
   "challenge": {
    "ar": "اعمل mock interview كاملة 30 دقيقة (تعريف + STAR + تقني + أسئلتك) وسجّلها، واكتب إيميل الشكر.",
    "en": "Do a full 30-minute mock interview (introduction + STAR + technical + your questions), record it, and write the thank-you email."
   },
   "quiz": [
    {
     "q": {
      "ar": "سؤال كويس في آخر المقابلة:",
      "en": "A good question at the end of an interview:"
     },
     "o": [
      "How much vacation do I get?",
      "What does success look like in this role after six months?",
      "No questions."
     ],
     "a": 1,
     "why": {
      "ar": "بيوري اهتمامك بالشغل.",
      "en": "It shows interest in the work."
     }
    },
    {
     "q": {
      "ar": "إيميل الشكر بيتبعت:",
      "en": "The thank-you email is sent:"
     },
     "o": [
      {
       "ar": "نفس اليوم",
       "en": "the same day"
      },
      {
       "ar": "بعد شهر",
       "en": "a month later"
      },
      {
       "ar": "مبيتبعتش",
       "en": "never"
      }
     ],
     "a": 0,
     "why": {
      "ar": "وانت لسه في دماغهم.",
      "en": "While you're still fresh in their minds."
     }
    },
    {
     "q": {
      "ar": "soft skills زي:",
      "en": "Soft skills include:"
     },
     "o": [
      {
       "ar": "التواصل والشغل في فريق",
       "en": "communication and teamwork"
      },
      {
       "ar": "Python",
       "en": "Python"
      },
      {
       "ar": "SQL",
       "en": "SQL"
      }
     ],
     "a": 0,
     "why": {
      "ar": "مهارات شخصية.",
      "en": "Personal skills."
     }
    }
   ],
   "minutes": 120
  },
  {
   "d": 6,
   "title": {
    "ar": "مراجعة الأسبوع والاختبار",
    "en": "Week review and test"
   },
   "goal": {
    "ar": "راجع الخمس أيام، وسلّم مشروع الأسبوع، وخد الاختبار الأسبوعي. الأسبوع 22 بيفتح لما تجيب 70% أو أكتر.",
    "en": "Review the five days, hand in the weekly project, and take the weekly test. Week 22 opens when you score 70% or more."
   },
   "review": [
    {
     "ar": "CV: فعل قوي + عمل + نتيجة بالأرقام.",
     "en": "CV: strong verb + work + a result in numbers."
    },
    {
     "ar": "مراحل التوظيف، ورسالة الـ recruiter.",
     "en": "The hiring stages, and the recruiter message."
    },
    {
     "ar": "STAR، وTell me about yourself، والقوة والضعف.",
     "en": "STAR, Tell me about yourself, and strengths and weaknesses."
    },
    {
     "ar": "التفكير بصوت عالي بالـ 6 خطوات، ولو اتزنقت.",
     "en": "Thinking aloud in 6 steps, and what to say when stuck."
    },
    {
     "ar": "أسئلتك في الآخر، وإيميل الشكر.",
     "en": "Your questions at the end, and the thank-you email."
    }
   ],
   "project": {
    "ar": "جهّز «interview kit» كامل بالإنجليزي: CV صفحة، وcover letter لوظيفة حقيقية، و«Tell me about yourself» مكتوب ومسجّل، و5 قصص STAR، و5 أسئلة تسألها، وإيميل شكر. واعمل mock interview مسجّلة 30 دقيقة واكتب تقييمك لنفسك.",
    "en": "Build a complete English interview kit: a one-page CV, a cover letter for a real job, \"Tell me about yourself\" written and recorded, 5 STAR stories, 5 questions to ask, and a thank-you email. Do a recorded 30-minute mock interview and write your own evaluation."
   },
   "test": [
    {
     "q": {
      "ar": "أحسن سطر CV:",
      "en": "The best CV line:"
     },
     "o": [
      "I was responsible for testing.",
      "Added 120 unit tests, raising coverage from 40% to 85%.",
      "Testing things."
     ],
     "a": 1,
     "why": {
      "ar": "فعل ونتيجة بأرقام.",
      "en": "A verb and a result with numbers."
     }
    },
    {
     "q": {
      "ar": "في الـ CV متكتبش:",
      "en": "In a CV, avoid:"
     },
     "o": [
      {
       "ar": "I في أول كل سطر",
       "en": "\"I\" at the start of every line"
      },
      {
       "ar": "أرقام",
       "en": "numbers"
      },
      {
       "ar": "أفعال ماضي",
       "en": "past verbs"
      }
     ],
     "a": 0,
     "why": {
      "ar": "الأسلوب المختصر.",
      "en": "The concise style."
     }
    },
    {
     "q": {
      "ar": "internship هي:",
      "en": "An internship is:"
     },
     "o": [
      {
       "ar": "تدريب في شركة",
       "en": "a training period at a company"
      },
      {
       "ar": "وظيفة مدير",
       "en": "a manager job"
      },
      {
       "ar": "امتحان",
       "en": "an exam"
      }
     ],
     "a": 0,
     "why": {
      "ar": "غالبًا للطلبة والمبتدئين.",
      "en": "Usually for students and beginners."
     }
    },
    {
     "q": {
      "ar": "ترتيب STAR:",
      "en": "The STAR order:"
     },
     "o": [
      "Situation, Task, Action, Result",
      "Start, Test, Answer, Repeat",
      "Story, Time, Action, Reason"
     ],
     "a": 0,
     "why": {
      "ar": "S-T-A-R.",
      "en": "S-T-A-R."
     }
    },
    {
     "q": {
      "ar": "نقطة ضعف كويسة في المقابلة:",
      "en": "A good weakness answer:"
     },
     "o": [
      "I have no weaknesses.",
      "I used to underestimate tasks; now I break them down and add a buffer.",
      "I'm lazy."
     ],
     "a": 1,
     "why": {
      "ar": "حقيقية ومعاها تحسين.",
      "en": "Real, with improvement."
     }
    },
    {
     "q": {
      "ar": "أول جملة في المسألة التقنية:",
      "en": "The first sentence in a technical problem:"
     },
     "o": [
      "Let me make sure I understand the input and output.",
      "Here is the code.",
      "I don't know."
     ],
     "a": 0,
     "why": {
      "ar": "تتأكد من السؤال.",
      "en": "Check the question."
     }
    },
    {
     "q": {
      "ar": "«Can I assume the list is sorted?» ده:",
      "en": "\"Can I assume the list is sorted?\" is:"
     },
     "o": [
      {
       "ar": "سؤال عن افتراض",
       "en": "a question about an assumption"
      },
      {
       "ar": "غلط",
       "en": "a mistake"
      },
      {
       "ar": "إجابة",
       "en": "an answer"
      }
     ],
     "a": 0,
     "why": {
      "ar": "مهم تسأله.",
      "en": "Worth asking."
     }
    },
    {
     "q": {
      "ar": "brute-force solution هو:",
      "en": "A brute-force solution is:"
     },
     "o": [
      {
       "ar": "حل بسيط بيجرب كل حاجة",
       "en": "a simple solution that tries everything"
      },
      {
       "ar": "حل مثالي",
       "en": "the perfect solution"
      },
      {
       "ar": "خطأ",
       "en": "an error"
      }
     ],
     "a": 0,
     "why": {
      "ar": "بعدين تحسّنه.",
      "en": "Then you optimise."
     }
    },
    {
     "q": {
      "ar": "في أول مقابلة متسألش عن:",
      "en": "In a first interview, don't ask about:"
     },
     "o": [
      {
       "ar": "المرتب",
       "en": "salary"
      },
      {
       "ar": "طريقة شغل الفريق",
       "en": "how the team works"
      },
      {
       "ar": "الخطوات الجاية",
       "en": "next steps"
      }
     ],
     "a": 0,
     "why": {
      "ar": "بيتناقش في مرحلة الـ offer.",
      "en": "It is discussed at the offer stage."
     }
    },
    {
     "q": {
      "ar": "اختار الصح:",
      "en": "Choose the correct one:"
     },
     "o": [
      "I look forward to hear from you.",
      "I look forward to hearing from you.",
      "I looking forward to hear you."
     ],
     "a": 1,
     "why": {
      "ar": "to + ing.",
      "en": "to + -ing."
     }
    },
    {
     "q": {
      "ar": "achievement هو:",
      "en": "An achievement is:"
     },
     "o": [
      {
       "ar": "إنجاز",
       "en": "something you accomplished"
      },
      {
       "ar": "مهمة يومية",
       "en": "a daily task"
      },
      {
       "ar": "شهادة",
       "en": "a certificate"
      }
     ],
     "a": 0,
     "why": {
      "ar": "نتيجة ملموسة.",
      "en": "A tangible result."
     }
    },
    {
     "q": {
      "ar": "«Tell me about yourself» ترتيبه:",
      "en": "The order for \"Tell me about yourself\":"
     },
     "o": [
      {
       "ar": "الحاضر ← الماضي ← المستقبل",
       "en": "present → past → future"
      },
      {
       "ar": "الطفولة ← الجامعة",
       "en": "childhood → university"
      },
      {
       "ar": "الهوايات بس",
       "en": "hobbies only"
      }
     ],
     "a": 0,
     "why": {
      "ar": "مركز على الشغل.",
      "en": "Focused on work."
     }
    }
   ],
   "minutes": 120
  }
 ]
});
