// Week 43 — generated by tools/build_weeks.js from content/english/src/w43.js. Edit the source, not this file.
JOURNEY.week({
 "track": "english",
 "n": 43,
 "month": 11,
 "level": "C1 → C2",
 "title": {
  "ar": "قواعد متقدمة للدقة",
  "en": "Advanced grammar for precision"
 },
 "goal": {
  "ar": "تستخدم القواعد اللي بتفرّق الكاتب المتمكن: الشرط المختلط والمقلوب، التوكيد بالـ cleft والقلب، الجمل المختصرة، التخلص من الغموض، والإيجاز — عشان تقول اللي تقصده بالظبط في سطور أقل.",
  "en": "Use the grammar that marks a skilled writer: mixed and inverted conditionals, emphasis with cleft sentences and inversion, reduced clauses, removing ambiguity, and concision — so you say exactly what you mean in fewer lines."
 },
 "days": [
  {
   "d": 1,
   "title": {
    "ar": "الشرط المتقدم",
    "en": "Advanced conditionals"
   },
   "goal": {
    "ar": "تتكلم عن اللي كان ممكن يحصل ونتايجه.",
    "en": "Talk about what could have happened and its results."
   },
   "learn": [
    {
     "h": {
      "ar": "الشرط التالت والمختلط",
      "en": "Third and mixed conditionals"
     },
     "p": {
      "ar": "**third conditional** = ماضي مختلف تمامًا ونتيجته في الماضي: If + had done, would have done. **mixed conditional** = ماضي مختلف ونتيجته دلوقتي: If + had done, would do. مفيد جدًا في الـ postmortems.",
      "en": "The **third conditional** = an unreal past with a past result: If + had done, would have done. A **mixed conditional** = an unreal past with a present result: If + had done, would do. Very useful in postmortems."
     },
     "ex": "third: If we had tested the tax codes, the invoices wouldn’t have failed.\nmixed: If we had added monitoring last year, we would know about failures immediately now.\nmixed: If I were more experienced with Kubernetes, I would have chosen it. (present → past)"
    },
    {
     "h": {
      "ar": "الشرط المقلوب",
      "en": "Inverted conditionals"
     },
     "p": {
      "ar": "في الكتابة الرسمية بتشيل «if» وتقلب: «**should you need**…» = If you need (مؤدب جدًا في آخر الإيميلات). «**had we known**…» = If we had known. «**were it not for**…» = If it weren’t for (لولا). ده **inverted conditional** — رسمي وأنيق.",
      "en": "In formal writing you drop «if» and invert: «**should you need**…» = If you need (very polite at the end of emails). «**had we known**…» = If we had known. «**were it not for**…» = If it weren’t for. This is an **inverted conditional** — formal and elegant."
     },
     "ex": "Should you need any further information, please let me know.\nHad we known about the API limit, we would have planned a queue.\nWere it not for the daily backups, we would have lost a week of data."
    },
    {
     "h": {
      "ar": "اختار الصيغة",
      "en": "Choosing the form"
     },
     "p": {
      "ar": "في السلاك والكلام: if العادية. في العقود والتقارير الرسمية والإيميلات الرسمية: المقلوبة بتدّي وزن. ومتخلطش الأزمنة غلط: ✗ «If we would have tested…» (غلط شائع جدًا).",
      "en": "On Slack and in speech: plain if. In contracts, formal reports and formal emails: the inverted form adds weight. And do not mix tenses wrongly: ✗ «If we would have tested…» (a very common error)."
     },
     "ex": "✗ If we would have tested it, it wouldn’t fail.\n✓ If we had tested it, it wouldn’t have failed.\n✓ Had we tested it, it wouldn’t have failed."
    }
   ],
   "practice": [
    {
     "ar": "اكتب 5 جمل third conditional عن مشروع فات.",
     "en": "Write 5 third-conditional sentences about a past project."
    },
    {
     "ar": "اكتب 3 mixed conditionals عن قرارات قديمة وأثرها النهارده.",
     "en": "Write 3 mixed conditionals about old decisions and their effect today."
    },
    {
     "ar": "حوّل 5 جمل if لصيغة مقلوبة.",
     "en": "Turn 5 if-sentences into inverted forms."
    },
    {
     "ar": "صحّح 5 جمل فيها «if … would have».",
     "en": "Correct 5 sentences containing «if … would have»."
    }
   ],
   "words": [
    {
     "t": "third conditional",
     "m": {
      "ar": "الشرط التالت (ماضي غير حقيقي)",
      "en": "an unreal past condition"
     },
     "ex": "Postmortems often use the third conditional."
    },
    {
     "t": "mixed conditional",
     "m": {
      "ar": "الشرط المختلط",
      "en": "a past condition with a present result"
     },
     "ex": "Use a mixed conditional for lasting effects."
    },
    {
     "t": "inverted conditional",
     "m": {
      "ar": "شرط مقلوب من غير if",
      "en": "a condition without «if» using inversion"
     },
     "ex": "«Should you need help» is an inverted conditional."
    },
    {
     "t": "should you need",
     "m": {
      "ar": "لو احتجت (رسمي)",
      "en": "if you need (formal)"
     },
     "ex": "Should you need anything, let me know."
    },
    {
     "t": "had we known",
     "m": {
      "ar": "لو كنا عرفنا",
      "en": "if we had known"
     },
     "ex": "Had we known, we would have waited."
    },
    {
     "t": "were it not for",
     "m": {
      "ar": "لولا",
      "en": "if it weren’t for"
     },
     "ex": "Were it not for backups, we’d have lost data."
    }
   ],
   "read": [
    {
     "t": "Perfect English Grammar",
     "url": "https://www.perfect-english-grammar.com/",
     "what": {
      "ar": "اقرا «mixed conditionals».",
      "en": "Read «mixed conditionals»."
     }
    }
   ],
   "challenge": {
    "ar": "اكتب postmortem بالإنجليزي (150 كلمة) لمشكلة حقيقية فيه 3 third conditionals، 2 mixed، و2 inverted — وراجع إن مفيش «if … would have».",
    "en": "Write an English postmortem (150 words) about a real problem with 3 third conditionals, 2 mixed and 2 inverted — and check that there is no «if … would have»."
   },
   "quiz": [
    {
     "q": {
      "ar": "الصح:",
      "en": "Correct:"
     },
     "o": [
      "If we had tested it, it wouldn’t have failed.",
      "If we would have tested it, it wouldn’t fail.",
      "If we tested it, it wouldn’t have fail."
     ],
     "a": 0,
     "why": {
      "ar": "had + would have.",
      "en": "had + would have."
     }
    },
    {
     "q": {
      "ar": "«Should you need help» يعني:",
      "en": "«Should you need help» means:"
     },
     "o": [
      "If you need help",
      "You must need help",
      "You should help"
     ],
     "a": 0,
     "why": {
      "ar": "مقلوب.",
      "en": "Inverted."
     }
    },
    {
     "q": {
      "ar": "mixed conditional:",
      "en": "A mixed conditional:"
     },
     "o": [
      "If we had added monitoring, we would know now.",
      "If it rains, we stay.",
      "If I go, I will call."
     ],
     "a": 0,
     "why": {
      "ar": "ماضي ← حاضر.",
      "en": "Past → present."
     }
    }
   ],
   "minutes": 120
  },
  {
   "d": 2,
   "title": {
    "ar": "التوكيد",
    "en": "Emphasis"
   },
   "goal": {
    "ar": "تبرز المعلومة المهمة بالقواعد مش بالخط العريض.",
    "en": "Highlight key information with grammar, not bold text."
   },
   "learn": [
    {
     "h": {
      "ar": "جمل الـ cleft",
      "en": "Cleft sentences"
     },
     "p": {
      "ar": "**cleft sentence** بتقسّم الجملة عشان تركّز على جزء: «It was the date format that broke the import» (مش حاجة تانية). «What we need is a queue» (ده بالظبط المطلوب). مفيدة لتصحيح سوء فهم.",
      "en": "A **cleft sentence** splits a sentence to focus on one part: «It was the date format that broke the import» (not something else). «What we need is a queue» (exactly that). Useful for correcting a misunderstanding."
     },
     "ex": "neutral:  The date format broke the import.\nit-cleft: It was the date format that broke the import, not the API.\nwhat-cleft: What we need isn’t more servers — what we need is a queue.\nall-cleft: All I’m asking for is a test environment."
    },
    {
     "h": {
      "ar": "القلب بعد النفي",
      "en": "Inversion after negatives"
     },
     "p": {
      "ar": "**inversion** بعد ظرف نفي أو تقييد في أول الجملة (رسمي وقوي): «**not only** … but also»، «**under no circumstances**»، «**no sooner** … than»، «**seldom**/rarely». الفعل المساعد بييجي قبل الفاعل زي السؤال.",
      "en": "**inversion** after a negative or limiting adverbial at the start of a sentence (formal and strong): «**not only** … but also», «**under no circumstances**», «**no sooner** … than», «**seldom**/rarely». The auxiliary comes before the subject, as in a question."
     },
     "ex": "Not only does the workflow save time, but it also reduces errors.\nUnder no circumstances should API keys be stored in the workflow.\nNo sooner had we launched than the first order arrived.\nSeldom have we seen such a clean migration."
    },
    {
     "h": {
      "ar": "do التوكيدية",
      "en": "The emphatic do"
     },
     "p": {
      "ar": "**emphatic do** = do/does/did قبل الفعل الأساسي في جملة مثبتة عشان تأكد أو ترد على شك: «I did test it» (فعلًا اختبرته)، «We do support Arabic». بتتنطق بضغط على do.",
      "en": "The **emphatic do** = do/does/did before the main verb in a positive sentence to insist or answer a doubt: «I did test it» (I really tested it), «We do support Arabic». It is spoken with stress on do."
     },
     "ex": "Client: \"Did you even test the import?\"\nYou:    \"I did test it — with 200 sample rows. The issue only appears with dates before 2000.\"\n\"We don’t offer phone support, but we do reply to emails within four hours.\""
    }
   ],
   "practice": [
    {
     "ar": "حوّل 5 جمل عادية لـ it-cleft وwhat-cleft.",
     "en": "Turn 5 plain sentences into it-clefts and what-clefts."
    },
    {
     "ar": "اكتب 4 جمل inversion رسمية.",
     "en": "Write 4 formal inversion sentences."
    },
    {
     "ar": "رد على 3 شكوك بـ emphatic do.",
     "en": "Answer 3 doubts with the emphatic do."
    },
    {
     "ar": "قول جمل الـ emphatic do بصوت عالي بالضغط الصح.",
     "en": "Say the emphatic-do sentences aloud with the right stress."
    }
   ],
   "words": [
    {
     "t": "cleft sentence",
     "m": {
      "ar": "جملة توكيد مقسومة",
      "en": "a sentence split to focus one part"
     },
     "ex": "«It was X that…» is a cleft sentence."
    },
    {
     "t": "inversion",
     "m": {
      "ar": "قلب ترتيب الفاعل والفعل",
      "en": "putting the verb before the subject"
     },
     "ex": "Inversion makes the warning stronger."
    },
    {
     "t": "not only",
     "m": {
      "ar": "مش بس",
      "en": "not just"
     },
     "ex": "Not only is it faster, it’s cheaper."
    },
    {
     "t": "under no circumstances",
     "m": {
      "ar": "تحت أي ظرف لأ",
      "en": "never, in any situation"
     },
     "ex": "Under no circumstances share the key."
    },
    {
     "t": "no sooner",
     "m": {
      "ar": "ما إن",
      "en": "immediately after"
     },
     "ex": "No sooner had we launched than it broke."
    },
    {
     "t": "seldom",
     "m": {
      "ar": "نادرًا",
      "en": "rarely"
     },
     "ex": "Seldom do clients read the terms."
    },
    {
     "t": "emphatic do",
     "m": {
      "ar": "do للتوكيد",
      "en": "do used to stress a verb"
     },
     "ex": "«I did send it» uses the emphatic do."
    }
   ],
   "read": [
    {
     "t": "British Council LearnEnglish",
     "url": "https://learnenglish.britishcouncil.org/",
     "what": {
      "ar": "دوّر على «cleft sentences» و«inversion».",
      "en": "Search for «cleft sentences» and «inversion»."
     }
    }
   ],
   "challenge": {
    "ar": "اكتب «سياسة أمان» قصيرة بالإنجليزي (8 قواعد) بالـ inversion والـ cleft — وإيميل بيصحح سوء فهم عميل بـ it-cleft وemphatic do.",
    "en": "Write a short English «security policy» (8 rules) using inversion and clefts — and an email correcting a client’s misunderstanding with an it-cleft and the emphatic do."
   },
   "quiz": [
    {
     "q": {
      "ar": "الصح:",
      "en": "Correct:"
     },
     "o": [
      "Under no circumstances should keys be shared.",
      "Under no circumstances keys should be shared.",
      "Under no circumstances shared keys."
     ],
     "a": 0,
     "why": {
      "ar": "قلب.",
      "en": "Inversion."
     }
    },
    {
     "q": {
      "ar": "it-cleft:",
      "en": "An it-cleft:"
     },
     "o": [
      "It was the date format that broke it.",
      "The date format broke it.",
      "Date format, broken."
     ],
     "a": 0,
     "why": {
      "ar": "تركيز.",
      "en": "Focus."
     }
    },
    {
     "q": {
      "ar": "emphatic do:",
      "en": "Emphatic do:"
     },
     "o": [
      "I did test it.",
      "I tested it.",
      "I do testing."
     ],
     "a": 0,
     "why": {
      "ar": "تأكيد.",
      "en": "Insistence."
     }
    }
   ],
   "minutes": 120
  },
  {
   "d": 3,
   "title": {
    "ar": "جمل أقصر وأدق",
    "en": "Shorter, tighter clauses"
   },
   "goal": {
    "ar": "تختصر الجمل من غير ما تخسر المعنى.",
    "en": "Shorten sentences without losing meaning."
   },
   "learn": [
    {
     "h": {
      "ar": "الـ participle clauses",
      "en": "Participle clauses"
     },
     "p": {
      "ar": "**participle clause** بتختصر جملتين بفاعل واحد: «After we checked the logs, we found…» ← «Having checked the logs, we found…». «-ing» لنفس الوقت أو السبب، «having + p.p.» لحاجة خلصت قبل، و«p.p.» للمبني للمجهول.",
      "en": "A **participle clause** shortens two clauses with the same subject: «After we checked the logs, we found…» → «Having checked the logs, we found…». «-ing» for the same time or a reason, «having + past participle» for something completed before, and a «past participle» for passive meaning."
     },
     "ex": "Using a queue, the workflow handles 500 orders a minute.\nHaving reviewed the contract, we suggest two changes.\nWritten in TypeScript, the node is easy to maintain."
    },
    {
     "h": {
      "ar": "اختصار الـ relative clause",
      "en": "Reduced relative clauses"
     },
     "p": {
      "ar": "**reduced relative clause** = تشيل who/which/that + be: «the orders that were created yesterday» ← «the orders created yesterday»، «the client who is waiting» ← «the client waiting». أقصر وأنضف في التقارير.",
      "en": "A **reduced relative clause** = drop who/which/that + be: «the orders that were created yesterday» → «the orders created yesterday», «the client who is waiting» → «the client waiting». Shorter and cleaner in reports."
     },
     "ex": "the files which are stored in Drive  → the files stored in Drive\nthe workflow that is running now       → the workflow running now\nusers who have admin rights             → users with admin rights"
    },
    {
     "h": {
      "ar": "المقيّدة وغير المقيّدة",
      "en": "Restrictive and non-restrictive"
     },
     "p": {
      "ar": "**restrictive clause** بتحدد أنهي واحد (من غير فواصل، و that مقبولة): «The workflows that failed were retried» (بس اللي فشلوا). **non-restrictive clause** معلومة زيادة (بفواصل، وwhich مش that): «The workflows, which failed, were retried» (كلهم فشلوا). الفاصلة بتغيّر المعنى! و**ellipsis** = تشيل كلام مفهوم: «Some tests passed; others didn’t.»",
      "en": "A **restrictive clause** identifies which one (no commas, that is fine): «The workflows that failed were retried» (only the failed ones). A **non-restrictive clause** adds extra information (commas, which not that): «The workflows, which failed, were retried» (all of them failed). The comma changes the meaning! And **ellipsis** = leaving out understood words: «Some tests passed; others didn’t.»"
     },
     "ex": "restrictive:     Clients who pay annually get a discount. (only those)\nnon-restrictive: Our clients, who pay annually, get a discount. (all clients pay annually)\nellipsis:        Omar can deploy on Sunday, and Sara on Monday."
    }
   ],
   "practice": [
    {
     "ar": "اختصر 5 أزواج جمل بـ participle clauses.",
     "en": "Combine 5 pairs of sentences with participle clauses."
    },
    {
     "ar": "اختصر 5 relative clauses.",
     "en": "Reduce 5 relative clauses."
    },
    {
     "ar": "اكتب نفس الجملة restrictive وnon-restrictive واشرح الفرق.",
     "en": "Write the same sentence as restrictive and non-restrictive and explain the difference."
    },
    {
     "ar": "اختصر فقرة من تقرير بالـ ellipsis.",
     "en": "Shorten a report paragraph with ellipsis."
    }
   ],
   "words": [
    {
     "t": "participle clause",
     "m": {
      "ar": "جملة بالـ participle",
      "en": "a clause built on -ing or -ed forms"
     },
     "ex": "Start with a participle clause: Having tested it, …"
    },
    {
     "t": "reduced relative clause",
     "m": {
      "ar": "جملة وصل مختصرة",
      "en": "a relative clause without who/which + be"
     },
     "ex": "«The files stored in Drive» is a reduced relative clause."
    },
    {
     "t": "restrictive clause",
     "m": {
      "ar": "جملة وصل بتحدد",
      "en": "a clause identifying which one"
     },
     "ex": "A restrictive clause takes no commas."
    },
    {
     "t": "non-restrictive clause",
     "m": {
      "ar": "جملة وصل لمعلومة زيادة",
      "en": "a clause adding extra information"
     },
     "ex": "Use commas around a non-restrictive clause."
    },
    {
     "t": "ellipsis",
     "m": {
      "ar": "حذف كلام مفهوم",
      "en": "leaving out understood words"
     },
     "ex": "Ellipsis makes lists shorter."
    }
   ],
   "read": [
    {
     "t": "Grammar Monster",
     "url": "https://www.grammar-monster.com/",
     "what": {
      "ar": "دوّر على «restrictive and non-restrictive clauses».",
      "en": "Search for «restrictive and non-restrictive clauses»."
     }
    }
   ],
   "challenge": {
    "ar": "خد تقرير أو README كتبته بالإنجليزي واختصره 25% بالأدوات دي من غير ما يضيع معنى — واحسب عدد الكلمات قبل وبعد.",
    "en": "Take a report or README you wrote in English and shorten it by 25% with these tools without losing meaning — and count the words before and after."
   },
   "quiz": [
    {
     "q": {
      "ar": "اختصار صح:",
      "en": "A correct reduction:"
     },
     "o": [
      "the orders created yesterday",
      "the orders were created yesterday",
      "the orders which created yesterday"
     ],
     "a": 0,
     "why": {
      "ar": "شيل which were.",
      "en": "Drop «which were»."
     }
    },
    {
     "q": {
      "ar": "«Our clients, who pay annually, get a discount»:",
      "en": "«Our clients, who pay annually, get a discount»:"
     },
     "o": [
      "all clients pay annually",
      "only some clients",
      "no clients"
     ],
     "a": 0,
     "why": {
      "ar": "الفاصلة.",
      "en": "The commas."
     }
    },
    {
     "q": {
      "ar": "participle clause صح:",
      "en": "A correct participle clause:"
     },
     "o": [
      "Having reviewed the contract, we suggest two changes.",
      "Having reviewed the contract, two changes are suggested by us.",
      "Reviewed the contract, we suggest."
     ],
     "a": 0,
     "why": {
      "ar": "نفس الفاعل.",
      "en": "Same subject."
     }
    }
   ],
   "minutes": 120
  },
  {
   "d": 4,
   "title": {
    "ar": "التخلص من الغموض",
    "en": "Removing ambiguity"
   },
   "goal": {
    "ar": "جمل ليها معنى واحد بس.",
    "en": "Sentences with only one meaning."
   },
   "learn": [
    {
     "h": {
      "ar": "الوصف في المكان الغلط",
      "en": "Misplaced and dangling modifiers"
     },
     "p": {
      "ar": "**misplaced modifier** = وصف بعيد عن اللي بيوصفه: «We only tested the import» (اختبرنا بس؟) ↔ «We tested only the import». **dangling modifier** = participle مالوش فاعل في الجملة: ✗ «Having finished the update, the server restarted» (السيرفر خلّص؟).",
      "en": "A **misplaced modifier** = a description far from what it describes: «We only tested the import» (we just tested?) ↔ «We tested only the import». A **dangling modifier** = a participle with no subject in the sentence: ✗ «Having finished the update, the server restarted» (the server finished?)."
     },
     "ex": "✗ Having finished the update, the server restarted.\n✓ Having finished the update, I restarted the server.\n✗ The client sent a file to the developer with errors. (who had errors?)\n✓ The client sent a file with errors to the developer."
    },
    {
     "h": {
      "ar": "الضماير الغامضة",
      "en": "Unclear pronouns"
     },
     "p": {
      "ar": "**ambiguity** كتير بييجي من ضمير مش واضح بيرجع لمين: الـ **antecedent** (الاسم اللي الضمير بيرجعله) لازم يبقى واضح. «When the workflow calls the API, it fails» — مين اللي فشل؟ كرر الاسم.",
      "en": "**ambiguity** often comes from a pronoun whose reference is unclear: the **antecedent** (the noun a pronoun refers to) must be clear. «When the workflow calls the API, it fails» — which one fails? Repeat the noun."
     },
     "ex": "✗ When the workflow calls the API, it fails.\n✓ When the workflow calls the API, the API returns an error.\n✗ Omar told Karim that his invoice was wrong.\n✓ Omar told Karim, “Your invoice is wrong.”"
    },
    {
     "h": {
      "ar": "التوازي",
      "en": "Parallelism"
     },
     "p": {
      "ar": "**parallelism** = العناصر في القايمة أو المقارنة تبقى بنفس الشكل النحوي. ✗ «The workflow validates data, sending emails, and logs errors». ✓ «validates data, sends emails, and logs errors». مهم جدًا في القوايم النقطية والـ requirements.",
      "en": "**parallelism** = items in a list or comparison take the same grammatical form. ✗ «The workflow validates data, sending emails, and logs errors». ✓ «validates data, sends emails, and logs errors». Very important in bullet lists and requirements."
     },
     "ex": "✗ Responsibilities:\n  - Building workflows\n  - Client communication\n  - To write documentation\n✓ Responsibilities:\n  - Building workflows\n  - Communicating with clients\n  - Writing documentation"
    }
   ],
   "practice": [
    {
     "ar": "صحّح 5 misplaced/dangling modifiers.",
     "en": "Fix 5 misplaced/dangling modifiers."
    },
    {
     "ar": "صحّح 5 جمل بضماير غامضة.",
     "en": "Fix 5 sentences with unclear pronouns."
    },
    {
     "ar": "ظبّط التوازي في 3 قوايم.",
     "en": "Fix the parallelism in 3 lists."
    },
    {
     "ar": "راجع CV أو README بتاعك للتوازي.",
     "en": "Check your CV or README for parallelism."
    }
   ],
   "words": [
    {
     "t": "ambiguity",
     "m": {
      "ar": "غموض / أكتر من معنى",
      "en": "having more than one meaning"
     },
     "ex": "Remove ambiguity from requirements."
    },
    {
     "t": "antecedent",
     "m": {
      "ar": "الاسم اللي الضمير بيرجعله",
      "en": "the noun a pronoun refers to"
     },
     "ex": "«It» has an unclear antecedent here."
    },
    {
     "t": "misplaced modifier",
     "m": {
      "ar": "وصف في مكان غلط",
      "en": "a description in the wrong place"
     },
     "ex": "«Only» is often a misplaced modifier."
    },
    {
     "t": "dangling modifier",
     "m": {
      "ar": "وصف مالوش صاحب",
      "en": "a modifier with no clear subject"
     },
     "ex": "Fix the dangling modifier in line 3."
    },
    {
     "t": "parallelism",
     "m": {
      "ar": "التوازي النحوي",
      "en": "using the same grammatical form"
     },
     "ex": "Bullet lists need parallelism."
    }
   ],
   "read": [
    {
     "t": "Purdue OWL",
     "url": "https://owl.purdue.edu/",
     "what": {
      "ar": "دوّر على «dangling modifiers» و«parallel structure».",
      "en": "Search for «dangling modifiers» and «parallel structure»."
     }
    }
   ],
   "challenge": {
    "ar": "اكتب 10 requirements بالإنجليزي لمشروع automation: من غير ضمير غامض، ولا modifier في مكان غلط، وبتوازي كامل — وادّيهم لحد يحاول يلاقي أي جملة ليها معنيين.",
    "en": "Write 10 English requirements for an automation project: no unclear pronouns, no misplaced modifiers, and full parallelism — and give them to someone to find any sentence with two meanings."
   },
   "quiz": [
    {
     "q": {
      "ar": "dangling modifier:",
      "en": "A dangling modifier:"
     },
     "o": [
      "Having finished the update, the server restarted.",
      "Having finished the update, I restarted the server.",
      "After the update, I restarted it."
     ],
     "a": 0,
     "why": {
      "ar": "مين خلّص؟",
      "en": "Who finished?"
     }
    },
    {
     "q": {
      "ar": "توازي صح:",
      "en": "Correct parallelism:"
     },
     "o": [
      "validates data, sends emails, and logs errors",
      "validates data, sending emails, and to log errors",
      "validation, sends, logging"
     ],
     "a": 0,
     "why": {
      "ar": "نفس الشكل.",
      "en": "Same form."
     }
    },
    {
     "q": {
      "ar": "antecedent:",
      "en": "An antecedent:"
     },
     "o": [
      "the noun a pronoun refers to",
      "an old rule",
      "a verb"
     ],
     "a": 0,
     "why": {
      "ar": "مرجع.",
      "en": "Reference."
     }
    }
   ],
   "minutes": 120
  },
  {
   "d": 5,
   "title": {
    "ar": "الربط الدقيق والإيجاز",
    "en": "Precise linking and concision"
   },
   "goal": {
    "ar": "روابط رسمية دقيقة وجمل من غير حشو.",
    "en": "Precise formal linkers and sentences without padding."
   },
   "learn": [
    {
     "h": {
      "ar": "روابط دقيقة",
      "en": "Precise linkers"
     },
     "p": {
      "ar": "«**albeit**» = وإن كان (مع صفة أو عبارة قصيرة): «a faster, albeit more expensive, option». «**insofar as**» = بقدر ما: «insofar as the data allows». «**in that**» = من حيث إن: «The plan is risky in that it depends on one supplier».",
      "en": "«**albeit**» = although (with an adjective or short phrase): «a faster, albeit more expensive, option». «**insofar as**» = to the extent that: «insofar as the data allows». «**in that**» = because, in the sense that: «The plan is risky in that it depends on one supplier»."
     },
     "ex": "Option B is faster, albeit more expensive.\nWe can guarantee uptime only insofar as the hosting provider meets its SLA.\nThe migration is complex in that both systems must run in parallel for a month."
    },
    {
     "h": {
      "ar": "الـ subjunctive",
      "en": "The subjunctive"
     },
     "p": {
      "ar": "**subjunctive** بعد recommend/suggest/insist/require/essential that: الفعل في صيغته الأصلية من غير s ولا to: «We recommend that the client **enable** two-factor authentication». «It is essential that every key **be** rotated». رسمي جدًا وشائع في التقارير والعقود الأمريكية.",
      "en": "The **subjunctive** after recommend/suggest/insist/require/essential that: the base verb, with no s and no to: «We recommend that the client **enable** two-factor authentication». «It is essential that every key **be** rotated». Very formal and common in American reports and contracts."
     },
     "ex": "✓ We recommend that the client enable 2FA.\n✓ It is essential that each environment be isolated.\n✗ We recommend that the client enables 2FA. (common in British English, less formal)\n✗ We recommend the client to enable 2FA."
    },
    {
     "h": {
      "ar": "الإيجاز",
      "en": "Concision"
     },
     "p": {
      "ar": "**concision** = تقول المعنى بأقل كلمات. شيل **redundancy** (تكرار: «past history»، «end result»، «completely finished») و**wordiness** (حشو: «due to the fact that» ← because، «at this point in time» ← now، «in order to» ← to).",
      "en": "**concision** = expressing the meaning in the fewest words. Remove **redundancy** (repetition: «past history», «end result», «completely finished») and **wordiness** (padding: «due to the fact that» → because, «at this point in time» → now, «in order to» → to)."
     },
     "ex": "wordy → concise\ndue to the fact that           → because\nat this point in time           → now\nin order to                     → to\nmake a decision regarding       → decide on\nthe end result                  → the result\nit is important to note that…   → (delete)"
    }
   ],
   "practice": [
    {
     "ar": "اكتب جملة بكل رابط: albeit, insofar as, in that.",
     "en": "Write a sentence with each linker: albeit, insofar as, in that."
    },
    {
     "ar": "اكتب 5 توصيات بالـ subjunctive.",
     "en": "Write 5 recommendations using the subjunctive."
    },
    {
     "ar": "شيل الحشو من 10 عبارات.",
     "en": "Remove the padding from 10 phrases."
    },
    {
     "ar": "اختصر إيميل طويل للنص.",
     "en": "Cut a long email in half."
    }
   ],
   "words": [
    {
     "t": "albeit",
     "m": {
      "ar": "وإن كان",
      "en": "although"
     },
     "ex": "A faster, albeit costlier, option."
    },
    {
     "t": "insofar as",
     "m": {
      "ar": "بقدر ما",
      "en": "to the extent that"
     },
     "ex": "Insofar as the data allows, we will report weekly."
    },
    {
     "t": "in that",
     "m": {
      "ar": "من حيث إن",
      "en": "because, in the sense that"
     },
     "ex": "It is risky in that it has one supplier."
    },
    {
     "t": "subjunctive",
     "m": {
      "ar": "صيغة الطلب الرسمي",
      "en": "the base verb after «recommend that» etc."
     },
     "ex": "Use the subjunctive: we recommend that he be told."
    },
    {
     "t": "concision",
     "m": {
      "ar": "الإيجاز",
      "en": "saying things in few words"
     },
     "ex": "Concision respects the reader’s time."
    },
    {
     "t": "redundancy",
     "m": {
      "ar": "تكرار زيادة",
      "en": "unnecessary repetition"
     },
     "ex": "«End result» is a redundancy."
    },
    {
     "t": "wordiness",
     "m": {
      "ar": "حشو",
      "en": "using too many words"
     },
     "ex": "Cut the wordiness from the introduction."
    }
   ],
   "read": [
    {
     "t": "Plain Language Guidelines",
     "url": "https://www.plainlanguage.gov/guidelines/",
     "what": {
      "ar": "دوّر على «omit unnecessary words».",
      "en": "Search for «omit unnecessary words»."
     }
    }
   ],
   "challenge": {
    "ar": "اكتب «تقرير توصيات» رسمي بالإنجليزي (200 كلمة) لعميل: 4 توصيات بالـ subjunctive، روابط دقيقة (albeit, insofar as, in that)، ومن غير ولا عبارة حشو — وبعدين اختصره لـ 120 كلمة.",
    "en": "Write a formal English «recommendations report» (200 words) for a client: 4 recommendations using the subjunctive, precise linkers (albeit, insofar as, in that), and no padding phrases — then cut it to 120 words."
   },
   "quiz": [
    {
     "q": {
      "ar": "subjunctive صح:",
      "en": "A correct subjunctive:"
     },
     "o": [
      "We recommend that the client enable 2FA.",
      "We recommend the client to enable 2FA.",
      "We recommend that the client enabling 2FA."
     ],
     "a": 0,
     "why": {
      "ar": "الصيغة الأصلية.",
      "en": "The base form."
     }
    },
    {
     "q": {
      "ar": "albeit:",
      "en": "Albeit:"
     },
     "o": [
      "although",
      "because",
      "therefore"
     ],
     "a": 0,
     "why": {
      "ar": "وإن كان.",
      "en": "Although."
     }
    },
    {
     "q": {
      "ar": "مختصر «due to the fact that»:",
      "en": "A concise form of «due to the fact that»:"
     },
     "o": [
      "because",
      "owing to the reason that",
      "for the purpose of"
     ],
     "a": 0,
     "why": {
      "ar": "إيجاز.",
      "en": "Concision."
     }
    }
   ],
   "minutes": 120
  },
  {
   "d": 6,
   "title": {
    "ar": "مراجعة الأسبوع واختباره",
    "en": "Week review and test"
   },
   "goal": {
    "ar": "القواعد بقت أداة دقة مش خوف.",
    "en": "Grammar is now a precision tool, not a fear."
   },
   "review": [
    {
     "ar": "الشرط التالت والمختلط والمقلوب.",
     "en": "Third, mixed and inverted conditionals."
    },
    {
     "ar": "التوكيد: cleft والقلب بعد النفي وdo التوكيدية.",
     "en": "Emphasis: clefts, inversion after negatives and the emphatic do."
    },
    {
     "ar": "participle clauses والـ relative clauses المختصرة والمقيدة وغير المقيدة.",
     "en": "Participle clauses, reduced relative clauses, restrictive and non-restrictive."
    },
    {
     "ar": "الغموض: modifiers والضماير والتوازي.",
     "en": "Ambiguity: modifiers, pronouns and parallelism."
    },
    {
     "ar": "الروابط الدقيقة والـ subjunctive والإيجاز.",
     "en": "Precise linkers, the subjunctive and concision."
    }
   ],
   "project": {
    "ar": "خد 3 مستندات إنجليزي كتبتها في الرحلة (تقرير، مقترح، README) وعدّلها «تعديل محرر»: صحّح الشرط والضماير والتوازي، ضيف توكيد في المكان الصح، اختصر 20% على الأقل، واكتب سجل تغييرات بكل قاعدة استخدمتها.",
    "en": "Take 3 English documents you wrote during the journey (a report, a proposal, a README) and give them an «editor’s edit»: fix conditionals, pronouns and parallelism, add emphasis in the right places, cut at least 20%, and write a change log naming each rule you used."
   },
   "test": [
    {
     "q": {
      "ar": "third conditional صح:",
      "en": "A correct third conditional:"
     },
     "o": [
      "If we had planned, we would have finished.",
      "If we planned, we would have finish.",
      "If we would plan, we had finished."
     ],
     "a": 0,
     "why": {
      "ar": "had + would have.",
      "en": "had + would have."
     }
    },
    {
     "q": {
      "ar": "«Had we known…» يعني:",
      "en": "«Had we known…» means:"
     },
     "o": [
      "If we had known…",
      "We knew…",
      "We have known…"
     ],
     "a": 0,
     "why": {
      "ar": "مقلوب.",
      "en": "Inverted."
     }
    },
    {
     "q": {
      "ar": "«Were it not for the backups…»:",
      "en": "«Were it not for the backups…»:"
     },
     "o": [
      "If it weren’t for the backups…",
      "The backups were not…",
      "We had no backups."
     ],
     "a": 0,
     "why": {
      "ar": "لولا.",
      "en": "If it weren’t for."
     }
    },
    {
     "q": {
      "ar": "inversion صح:",
      "en": "Correct inversion:"
     },
     "o": [
      "Not only does it save time, but it also…",
      "Not only it saves time, but…",
      "Not only saving time…"
     ],
     "a": 0,
     "why": {
      "ar": "does قبل الفاعل.",
      "en": "«does» before the subject."
     }
    },
    {
     "q": {
      "ar": "what-cleft:",
      "en": "A what-cleft:"
     },
     "o": [
      "What we need is a queue.",
      "We need a queue.",
      "A queue is needed."
     ],
     "a": 0,
     "why": {
      "ar": "تركيز.",
      "en": "Focus."
     }
    },
    {
     "q": {
      "ar": "reduced relative:",
      "en": "A reduced relative clause:"
     },
     "o": [
      "the workflow running now",
      "the workflow which running now",
      "the workflow is running now"
     ],
     "a": 0,
     "why": {
      "ar": "شيل which is.",
      "en": "Drop «which is»."
     }
    },
    {
     "q": {
      "ar": "non-restrictive:",
      "en": "A non-restrictive clause:"
     },
     "o": [
      "uses commas and «which»",
      "uses no commas",
      "uses «that» with commas"
     ],
     "a": 0,
     "why": {
      "ar": "معلومة زيادة.",
      "en": "Extra information."
     }
    },
    {
     "q": {
      "ar": "ellipsis:",
      "en": "Ellipsis:"
     },
     "o": [
      "Some passed; others didn’t.",
      "Some passed; others didn’t pass the tests at all.",
      "Some of them passed and some of them did not pass."
     ],
     "a": 0,
     "why": {
      "ar": "حذف.",
      "en": "Omission."
     }
    },
    {
     "q": {
      "ar": "ضمير غامض:",
      "en": "An unclear pronoun:"
     },
     "o": [
      "When the workflow calls the API, it fails.",
      "When the workflow calls the API, the API fails.",
      "The API fails."
     ],
     "a": 0,
     "why": {
      "ar": "مين؟",
      "en": "Which one?"
     }
    },
    {
     "q": {
      "ar": "misplaced «only»:",
      "en": "A misplaced «only»:"
     },
     "o": [
      "We only tested the import. (meaning: nothing else)",
      "We tested only the import.",
      "Only the import was tested."
     ],
     "a": 0,
     "why": {
      "ar": "مكان only.",
      "en": "The position of «only»."
     }
    },
    {
     "q": {
      "ar": "in that:",
      "en": "In that:"
     },
     "o": [
      "because / in the sense that",
      "inside that",
      "therefore"
     ],
     "a": 0,
     "why": {
      "ar": "من حيث إن.",
      "en": "In the sense that."
     }
    },
    {
     "q": {
      "ar": "redundancy:",
      "en": "A redundancy:"
     },
     "o": [
      "end result",
      "result",
      "outcome"
     ],
     "a": 0,
     "why": {
      "ar": "تكرار.",
      "en": "Repetition."
     }
    }
   ],
   "minutes": 120
  }
 ]
});
