// n8n week 1 — the intensive hour (weeks 1–12 are 3 hours a day). Merged into the week by tools/build_weeks.js.
const B = (ar, en) => ({ ar, en });
const L = (h, p, ex) => ({ h, p, ex });
const W = (t, ar, en, ex) => ({ t, m: B(ar, en), ex });
const Q = (q, o, a, why) => ({ q, o, a, why });
module.exports = { days: [
  { learn: [L(B('تثبيت البيانات (Pin data)', 'Pinning data'),
      B('لما نود بيجيب بيانات من API، تقدر **تثبّت** خرجه (📌 Pin). بعد كده كل تشغيل تجريبي بيستخدم البيانات المثبّتة من غير ما ينادي الـ API تاني: أسرع، ومن غير ما تستهلك حدود الخدمة، ونفس البيانات كل مرة فتقارن صح. التثبيت بيشتغل في التجربة بس، مش في التشغيل الحقيقي.',
        'When a node fetches data from an API you can **pin** its output (📌 Pin). From then on every test run uses the pinned data without calling the API again: faster, no use of the service’s limits, and the same data every time so you compare fairly. Pinning only affects test runs, not production runs.'),
      'HTTP Request  →  📌 Pin data\nnext test run: uses the pinned items (no API call)\nproduction run: calls the API as usual')],
    practice: [B('شغّل نود HTTP Request على `https://jsonplaceholder.typicode.com/users` وثبّت الخرج، وبعدين عدّل البيانات المثبّتة بإيدك (غيّر اسم) وشوف النودز اللي بعده.', 'Run an HTTP Request node on `https://jsonplaceholder.typicode.com/users`, pin the output, then edit the pinned data by hand (change a name) and watch the next nodes.'),
      B('افتح Executions وقارن تشغيل بالبيانات المثبّتة وتشغيل من غيرها: إيه الفرق في الوقت؟', 'Open Executions and compare a run with pinned data and one without: what is the difference in time?')],
    words: [W('pin', 'تثبيت خرج نود عشان التجارب تستخدمه', 'to fix a node’s output so test runs reuse it', 'Pin the API response while you build.'),
      W('test run', 'تشغيل تجريبي من المحرر', 'a trial run started from the editor', 'A test run uses pinned data.')],
    quiz: [Q(B('البيانات المثبّتة بتأثر على إيه؟', 'What does pinned data affect?'), [B('التشغيل التجريبي بس', 'test runs only'), B('كل التشغيلات', 'every run'), B('الـ API نفسه', 'the API itself')], 0, B('في الإنتاج النود بينادي الـ API عادي.', 'In production the node calls the API as usual.'))] },
  { learn: [L(B('عائلات أكواد الحالة (status codes)', 'Families of status codes'),
      B('الرقم الأول بيقولك الحكاية: **2xx** نجح (200 تمام، 201 اتعمل)، **3xx** اتنقل لمكان تاني، **4xx** الغلط عندك (400 طلب غلط، 401 مش مسجّل، 403 ممنوع، 404 مش موجود، 429 كتير)، **5xx** الغلط عند السيرفر. 4xx صلّح طلبك؛ 429 و5xx ممكن تعيد بعد شوية.',
        'The first digit tells the story: **2xx** success (200 OK, 201 created), **3xx** moved elsewhere, **4xx** your mistake (400 bad request, 401 not authenticated, 403 forbidden, 404 not found, 429 too many), **5xx** the server’s mistake. For 4xx fix your request; for 429 and 5xx you can retry later.'),
      '200 OK            → use the data\n401 Unauthorized  → check the credential\n404 Not Found     → check the URL / id\n429 Too Many      → wait, then retry\n503 Unavailable   → retry with a delay')],
    practice: [B('جرّب في HTTP Request: `https://httpbin.org/status/404` و`/status/429` و`/status/503` وشوف رسالة الخطأ في كل مرة.', 'Try in HTTP Request: `https://httpbin.org/status/404`, `/status/429` and `/status/503` and read the error each time.'),
      B('اعمل جدول صغير: الكود ← معناه ← تعمل إيه، لـ 8 أكواد.', 'Make a small table: code → meaning → what to do, for 8 codes.')],
    words: [W('client error', 'خطأ من ناحية الطلب نفسه (أكواد 4xx)', 'an error caused by the request itself (4xx codes)', 'A 404 is a client error: fix the URL.'),
      W('retry', 'تعيد المحاولة بعد فشل', 'to try again after a failure', 'Retry after a 503, not after a 400.')],
    quiz: [Q(B('الكود 429 معناه:', 'Status 429 means:'), [B('طلبات كتير؛ استنى وأعد', 'too many requests; wait and retry'), B('الصفحة مش موجودة', 'page not found'), B('نجح', 'success')], 0, B('Too Many Requests.', 'Too Many Requests.'))] },
  { learn: [L(B('الـ Credentials: مكان الأسرار', 'Credentials: where secrets live'),
      B('أي مفتاح أو توكن بيتحط في **Credentials** مش في خانات النود ولا في Code node. n8n بيشفّرها، ومش بتطلع لما تصدّر أو تشارك الـ workflow. ولو المفتاح اتغيّر، بتغيّره في مكان واحد وكل الـ workflows تاخده.',
        'Any key or token goes into **Credentials**, not into node fields or a Code node. n8n encrypts them, and they are not included when you export or share a workflow. When a key changes, you update it in one place and every workflow picks it up.'),
      '✗ HTTP Request → Header: Authorization: Bearer abc123…\n✓ HTTP Request → Authentication: Generic → Header Auth → (credential "My API")')],
    practice: [B('صدّر workflow فيه credential لملف JSON وافتحه: اتأكد إن السر نفسه مش موجود.', 'Export a workflow that uses a credential to a JSON file and open it: check the secret itself is not there.'),
      B('سمّي الـ credentials بنظام: `خدمة – حساب – بيئة` (مثلًا `Telegram – support bot – test`).', 'Name credentials with a pattern: `service – account – environment` (e.g. `Telegram – support bot – test`).')],
    words: [W('encrypt', 'تحوّل بيانات لشكل محدش يقراه من غير مفتاح', 'to turn data into a form nobody can read without a key', 'n8n encrypts stored credentials.'),
      W('secret', 'معلومة سرية زي مفتاح أو توكن', 'a confidential value such as a key or token', 'Never paste a secret into a node field.')],
    quiz: [Q(B('تحط الـ API key فين؟', 'Where do you put an API key?'), [B('في Credentials', 'in Credentials'), B('في Code node', 'in a Code node'), B('في اسم النود', 'in the node name')], 0, B('مشفّرة ومش بتتصدّر.', 'Encrypted and not exported.'))] },
  { learn: [L(B('وضعين للـ Code node', 'The two Code node modes'),
      B('**Run Once for All Items**: الكود بيشتغل مرة واحدة، تاخد كل العناصر بـ `$input.all()` وترجع array. **Run Once for Each Item**: الكود بيشتغل لكل عنصر، تقرا `$json` وترجع object واحد. الأول للتجميع والفرز، والتاني للتعديل البسيط على كل عنصر.',
        '**Run Once for All Items**: the code runs once; get every item with `$input.all()` and return an array. **Run Once for Each Item**: the code runs per item; read `$json` and return one object. The first is for totals and sorting, the second for simple per-item changes.'),
      '// All Items\nconst total = $input.all().reduce((s, i) => s + i.json.price, 0);\nreturn [{ json: { total } }];\n\n// Each Item\nreturn { json: { ...$json, price_egp: $json.price * 50 } };')],
    practice: [B('بنفس 5 عناصر: احسب المجموع في وضع All Items، وزوّد حقل جديد لكل عنصر في وضع Each Item.', 'With the same 5 items: compute the total in All Items mode, and add a new field to each item in Each Item mode.'),
      B('غلّط عمدًا: ارجع object في وضع All Items وشوف رسالة الخطأ.', 'Make a deliberate mistake: return an object in All Items mode and read the error.')],
    words: [W('mode', 'طريقة تشغيل محددة لنود', 'a particular way a node runs', 'Switch the Code node mode to Run Once for Each Item.'),
      W('running total', 'مجموع بيزيد مع كل عنصر', 'a sum that grows with each item', 'reduce keeps a running total.')],
    quiz: [Q(B('في وضع Each Item تقرا العنصر بـ:', 'In Each Item mode you read the item with:'), [B('`$json`', '`$json`'), B('`$input.all()`', '`$input.all()`'), B('`items[99]`', '`items[99]`')], 0, B('كل تشغيل = عنصر واحد.', 'Each run = one item.'))] },
  { learn: [L(B('Retry on Fail وOn Error', 'Retry on Fail and On Error'),
      B('في **Settings** بتاعة أي نود: **Retry On Fail** يعيد المحاولة (مثلًا 3 مرات كل 5 ثواني) — مفيد لأخطاء الشبكة و429 و5xx. و**On Error** يحدد يحصل إيه لو فشل في الآخر: يوقف الـ workflow، أو يكمّل، أو يكمّل ويطلّع الخطأ في مخرج منفصل تتعامل معاه.',
        'In any node’s **Settings**: **Retry On Fail** tries again (e.g. 3 times, 5 seconds apart) — useful for network errors, 429 and 5xx. **On Error** decides what happens if it still fails: stop the workflow, continue, or continue and send the error to a separate output you can handle.'),
      'HTTP Request → Settings\n  Retry On Fail: on   Max Tries: 3   Wait Between Tries: 5000 ms\n  On Error: Continue (using error output)\n      ├─ success → Google Sheets\n      └─ error   → Telegram alert')],
    practice: [B('على `https://httpbin.org/status/503` فعّل Retry 3 مرات وشوف في Executions إنه حاول 3 مرات.', 'On `https://httpbin.org/status/503` enable 3 retries and check in Executions that it tried 3 times.'),
      B('خلّي On Error = error output، ووصّل مخرج الخطأ بنود Edit Fields يكتب رسالة مفهومة.', 'Set On Error to the error output, and connect it to an Edit Fields node that writes a clear message.')],
    words: [W('error branch', 'الفرع اللي بتمشي فيه العناصر اللي فشلت', 'the branch the failed items follow', 'The error branch sends a Telegram alert.'),
      W('flaky', 'بيفشل أحيانًا وينجح أحيانًا من غير سبب واضح', 'failing sometimes and working other times for no clear reason', 'A flaky API needs Retry On Fail.')],
    quiz: [Q(B('Retry مفيد مع أنهي خطأ؟', 'Retry helps with which error?'), [B('503 من السيرفر', 'a 503 from the server'), B('400 طلب غلط', 'a 400 bad request'), B('401 مفتاح غلط', 'a 401 wrong key')], 0, B('الأخطاء المؤقتة بس.', 'Only temporary errors.'))] },
  { review: [B('⚡ تثبيت البيانات، وأكواد الحالة، والـ Credentials.', '⚡ Pinned data, status codes and credentials.'),
      B('⚡ وضعين الـ Code node، وRetry on Fail ومخرج الخطأ: اعمل workflow صغير يجمعهم كلهم.', '⚡ The two Code node modes, Retry on Fail and the error output: build a small workflow that uses them all.')] }
] };
