// n8n week 2 — the intensive hour (weeks 1–12 are 3 hours a day). Merged into the week by tools/build_weeks.js.
const B = (ar, en) => ({ ar, en });
const L = (h, p, ex) => ({ h, p, ex });
const W = (t, ar, en, ex) => ({ t, m: B(ar, en), ex });
const Q = (q, o, a, why) => ({ q, o, a, why });
module.exports = { days: [
  { learn: [L(B('n8n في Docker', 'n8n in Docker'),
      B('Docker بيشغّل n8n في «حاوية» معزولة فيها كل اللي محتاجه. أهم حاجة الـ **volume**: من غيره بياناتك (الـ workflows والـ credentials) بتضيع لما الحاوية تتمسح. ومفتاح التشفير `N8N_ENCRYPTION_KEY` احفظه في مكان آمن؛ من غيره الـ credentials مش هتتفك على جهاز تاني.',
        'Docker runs n8n in an isolated «container» that has everything it needs. The key part is the **volume**: without it your data (workflows and credentials) is lost when the container is removed. Keep the encryption key `N8N_ENCRYPTION_KEY` somewhere safe; without it credentials cannot be decrypted on another machine.'),
      'docker volume create n8n_data\ndocker run -it --rm -p 5678:5678 \\\n  -e GENERIC_TIMEZONE=Africa/Cairo \\\n  -v n8n_data:/home/node/.n8n \\\n  docker.n8n.io/n8nio/n8n')],
    practice: [B('لو Docker متاح عندك: شغّل n8n بالأمر ده، اعمل workflow، اقفل الحاوية وشغّلها تاني واتأكد إن الـ workflow لسه موجود.', 'If Docker is available: start n8n with this command, create a workflow, stop the container, start it again and check the workflow is still there.'),
      B('اكتب في `commands.md` الفرق بين `npx n8n` وDocker في 3 نقط (التثبيت، مكان البيانات، التحديث).', 'Write in `commands.md` the difference between `npx n8n` and Docker in 3 points (install, where data lives, updating).')],
    words: [W('docker image', 'القالب الجاهز اللي الحاوية بتتعمل منه', 'the ready template a container is created from', 'Pull the latest n8n docker image.'),
      W('persistent', 'بيفضل موجود بعد إعادة التشغيل', 'kept after a restart', 'Use persistent storage for the n8n data.')],
    quiz: [Q(B('من غير volume في Docker:', 'Without a volume in Docker:'), [B('البيانات بتضيع لما الحاوية تتمسح', 'data is lost when the container is removed'), B('n8n مش هيشتغل', 'n8n will not start'), B('الـ API هيرفض', 'the API refuses')], 0, B('الـ volume هو المخزن الدايم.', 'The volume is the lasting storage.'))] },
  { learn: [L(B('أخطاء JSON الشائعة', 'Common JSON mistakes'),
      B('أشهر 5: علامات تنصيص مفردة `\'`، فاصلة بعد آخر عنصر، مفاتيح من غير تنصيص، تعليقات `//` (JSON مفيهوش تعليقات)، و`undefined` (مش موجود في JSON؛ استخدم `null`). ولما JSON يطلع جوه نص (string) لازم تعمله `JSON.parse` الأول.',
        'The top 5: single quotes `\'`, a comma after the last item, unquoted keys, `//` comments (JSON has no comments), and `undefined` (it does not exist in JSON; use `null`). And when JSON arrives inside a string you must `JSON.parse` it first.'),
      '✗ {name: \'Sara\', tags: [\'a\',],}   // comment\n✓ {"name": "Sara", "tags": ["a"], "phone": null}')],
    practice: [B('اكتب JSON فيه الـ 5 أخطاء دول عمدًا، وحطه في jsonlint أو في نود Edit Fields (JSON) وصلّح غلطة غلطة.', 'Write JSON with these 5 mistakes on purpose, paste it into a JSON validator or an Edit Fields (JSON) node, and fix one mistake at a time.'),
      B('في Code node: `JSON.parse(\'{"a":1}\')` و`JSON.stringify({a:1}, null, 2)` واشرح الفرق بكلامك.', 'In a Code node: `JSON.parse(\'{"a":1}\')` and `JSON.stringify({a:1}, null, 2)`, and explain the difference in your own words.')],
    words: [W('parse error', 'خطأ لما البرنامج مش قادر يقرا النص كـ JSON', 'an error when a program cannot read the text as JSON', 'A single quote causes a parse error.'),
      W('serialize', 'تحوّل object لنص عشان تبعته أو تحفظه', 'to turn an object into text to send or store it', 'JSON.stringify serializes an object.')],
    quiz: [Q(B('أنهي واحد JSON صحيح؟', 'Which one is valid JSON?'), [B('`{"a": null}`', '`{"a": null}`'), B('`{a: 1}`', '`{a: 1}`'), B('`{"a": undefined}`', '`{"a": undefined}`')], 0, B('المفاتيح بين تنصيص مزدوج، وundefined مش موجود.', 'Keys need double quotes, and undefined does not exist.'))] },
  { learn: [L(B('n8n CLI: تصدير واستيراد', 'The n8n CLI: export and import'),
      B('n8n فيه أوامر للطرفية تصدّر كل الـ workflows لملفات JSON تحطها في Git، وتستوردها على جهاز تاني. ده أساس النسخ الاحتياطي والنقل بين بيئة تجربة وبيئة شغل.',
        'n8n has terminal commands that export every workflow to JSON files you can keep in Git, and import them on another machine. This is the basis of backups and of moving between a test and a live environment.'),
      'n8n export:workflow --all --separate --output=workflows/\ngit add workflows && git commit -m "backup workflows"\nn8n import:workflow --separate --input=workflows/')],
    practice: [B('صدّر الـ workflows بتاعتك لفولدر `workflows/` واعمل commit.', 'Export your workflows to a `workflows/` folder and commit them.'),
      B('عدّل workflow واحد في n8n، صدّر تاني، واعمل `git diff` وشوف التغيير بالظبط.', 'Change one workflow in n8n, export again, run `git diff` and see exactly what changed.')],
    words: [W('backup', 'نسخة احتياطية ترجع لها لو حاجة ضاعت', 'a spare copy to restore if something is lost', 'Export a backup every week.'),
      W('restore', 'ترجّع البيانات من نسخة احتياطية', 'to bring data back from a backup', 'Restore the workflows on the new server.')],
    quiz: [Q(B('ليه نصدّر الـ workflows لـ Git؟', 'Why export workflows to Git?'), [B('نسخ احتياطي وتتبّع التغييرات', 'backups and tracking changes'), B('عشان تشتغل أسرع', 'to make them run faster'), B('عشان نشارك الـ credentials', 'to share the credentials')], 0, B('والـ credentials مش بتتصدّر معاها.', 'And credentials are not exported with them.'))] },
  { learn: [L(B('قراءة رد curl بالتفصيل', 'Reading a curl response in detail'),
      B('`curl -i` بيعرض الـ **headers** مع الرد: الـ status، و`Content-Type` (JSON ولا HTML؟)، وحدود الطلبات زي `X-RateLimit-Remaining`. و`-v` بيعرض كل اللي حصل في الاتصال. لما طلب يفشل في n8n، جرّبه بـ curl الأول: لو فشل هناك كمان، المشكلة مش في n8n.',
        '`curl -i` shows the **headers** with the response: the status, `Content-Type` (JSON or HTML?), and rate limits such as `X-RateLimit-Remaining`. `-v` shows everything that happened in the connection. When a request fails in n8n, try it with curl first: if it fails there too, the problem is not n8n.'),
      'curl -i https://api.github.com/repos/n8n-io/n8n\nHTTP/2 200\ncontent-type: application/json; charset=utf-8\nx-ratelimit-limit: 60\nx-ratelimit-remaining: 59')],
    practice: [B('نفّذ `curl -i` على 3 APIs عامة واكتب لكل واحد: الـ status والـ Content-Type وفيه rate limit ولا لأ.', 'Run `curl -i` on 3 public APIs and note for each: the status, the Content-Type and whether there is a rate limit.'),
      B('حوّل أمر curl فيه header وbody لنود HTTP Request بـ Import cURL وقارن.', 'Turn a curl command with a header and a body into an HTTP Request node with Import cURL and compare.')],
    words: [W('response header', 'معلومة إضافية راجعة مع الرد', 'extra information that comes back with the response', 'Check the rate limit in the response header.'),
      W('verbose', 'بيعرض تفاصيل كتير عشان تفهم اللي حصل', 'showing lots of detail so you can see what happened', 'Run curl in verbose mode with -v.')],
    quiz: [Q(B('`curl -i` بيضيف إيه؟', 'What does `curl -i` add?'), [B('الـ headers', 'the headers'), B('تثبيت', 'an install'), B('إعادة محاولة', 'a retry')], 0, B('i = include headers.', 'i = include headers.'))] },
  { learn: [L(B('نظام تسمية للمشاريع', 'A naming system for projects'),
      B('بعد شهر هيبقى عندك 30 workflow. اتفق مع نفسك من الأول: `[عميل] فعل – موضوع` زي `[Clinic] Send – booking reminders`، والنودز بفعل واضح (`Get new orders` مش `HTTP Request3`)، و tag للحالة (`live`, `draft`) وللعميل. التسمية الكويسة توثيق ببلاش.',
        'In a month you will have 30 workflows. Agree with yourself from the start: `[Client] Verb – topic` like `[Clinic] Send – booking reminders`, nodes with a clear verb (`Get new orders`, not `HTTP Request3`), and tags for status (`live`, `draft`) and client. Good names are free documentation.'),
      '[Clinic] Send – booking reminders      tags: live, clinic\n[Shop] Sync – orders to Sheets          tags: draft, shop\nnodes: Get new orders → Keep paid only → Add row to Sheet')],
    practice: [B('غيّر أسماء كل الـ workflows والنودز اللي عندك بالنظام ده.', 'Rename all your workflows and nodes using this system.'),
      B('اكتب ملف `CONVENTIONS.md` قصير فيه قواعد التسمية والـ tags بتاعتك.', 'Write a short `CONVENTIONS.md` file with your naming and tag rules.')],
    words: [W('convention', 'قاعدة متفق عليها عشان الكل يمشي عليها', 'an agreed rule everyone follows', 'Our naming convention starts with the client.'),
      W('rename', 'تغيّر اسم حاجة', 'to change the name of something', 'Rename HTTP Request3 to Get new orders.')],
    quiz: [Q(B('أحسن اسم لنود:', 'The best node name:'), [B('Get new orders', 'Get new orders'), B('HTTP Request3', 'HTTP Request3'), B('node', 'node')], 0, B('فعل + موضوع.', 'A verb + a topic.'))] },
  { review: [B('⚡ Docker والـ volume ومفتاح التشفير، وأخطاء JSON الخمسة.', '⚡ Docker, the volume and the encryption key, and the five JSON mistakes.'),
      B('⚡ صدّر workflows لـ Git، اقرا headers بـ curl -i، وطبّق نظام التسمية على مشروعك.', '⚡ Export workflows to Git, read headers with curl -i, and apply the naming system to your project.')] }
] };
