// n8n week 3 — the intensive hour (weeks 1–12 are 3 hours a day). Merged into the week by tools/build_weeks.js.
const B = (ar, en) => ({ ar, en });
const L = (h, p, ex) => ({ h, p, ex });
const W = (t, ar, en, ex) => ({ t, m: B(ar, en), ex });
const Q = (q, o, a, why) => ({ q, o, a, why });
module.exports = { days: [
  { learn: [L(B('اختار التريجر الصح', 'Choosing the right trigger'),
      B('سؤالين: **مين بيبدأ؟** (انت يدوي، الوقت، خدمة تانية، إنسان في فورم) و**قد إيه لازم يكون سريع؟** لو الخدمة بتدعم webhook استخدمه (فوري ومن غير استهلاك). لو مش بتدعم، polling كل كام دقيقة. ولو الشغل مرة في اليوم، Schedule.',
        'Two questions: **who starts it?** (you manually, the clock, another service, a person in a form) and **how fast must it react?** If the service supports webhooks, use one (instant and cheap). If not, poll every few minutes. If the job runs once a day, use a Schedule.'),
      'needs to react in seconds + service has webhooks → Webhook / app trigger\nno webhooks                                    → polling trigger (every 5 min)\nfixed time of day                              → Schedule Trigger\na person fills data                            → Form Trigger')],
    practice: [B('اكتب 6 مواقف من شغلك أو شغل حد تعرفه، واختار لكل واحد التريجر المناسب مع السبب.', 'Write 6 situations from your work or someone you know, and pick the right trigger for each with the reason.'),
      B('دوّر في توثيق خدمتين (مثلًا Stripe وGoogle Sheets): مين فيهم بيدعم webhooks؟', 'Search the docs of two services (e.g. Stripe and Google Sheets): which one supports webhooks?')],
    words: [W('real-time', 'بيحصل في نفس اللحظة تقريبًا', 'happening almost at the same moment', 'Webhooks give real-time updates.'),
      W('latency', 'الوقت بين الحدث ورد الفعل', 'the time between an event and the reaction', 'Polling every 10 minutes adds latency.')],
    quiz: [Q(B('الخدمة مش بتدعم webhooks ومحتاج تتابعها:', 'The service has no webhooks and you need to follow it:'), [B('polling كل كام دقيقة', 'poll every few minutes'), B('Form Trigger', 'a Form Trigger'), B('مفيش حل', 'there is no way')], 0, B('اسأل كل فترة عن الجديد.', 'Ask for new data every so often.'))] },
  { learn: [L(B('الـ cron بالتفصيل', 'Cron in detail'),
      B('خمس خانات: دقيقة، ساعة، يوم في الشهر، شهر، يوم في الأسبوع. `*` يعني أي قيمة، `*/15` كل 15، `1-5` من لحد، `1,15` قايمة. الأسبوع بيبدأ من 0 = الأحد. وافتكر إن التوقيت حسب `GENERIC_TIMEZONE` أو إعداد الـ workflow.',
        'Five fields: minute, hour, day of month, month, day of week. `*` means any value, `*/15` every 15, `1-5` a range, `1,15` a list. The week starts at 0 = Sunday. Remember the time follows `GENERIC_TIMEZONE` or the workflow setting.'),
      '0 9 * * 0-4      → 9:00 Sunday to Thursday\n*/30 8-17 * * *  → every 30 min from 8:00 to 17:30\n0 0 1 * *        → midnight on the 1st of each month\n0 18 * * 5       → 18:00 every Friday')],
    practice: [B('اكتب cron لـ: 7 الصبح كل يوم، كل ساعة في أيام الشغل، أول يوم في الشهر، وآخر الأسبوع.', 'Write cron for: 7 am every day, every hour on working days, the 1st of the month, and the weekend.'),
      B('اتأكد من كل واحد في أداة زي crontab.guru، وبعدين جرّبه في Schedule Trigger.', 'Check each in a tool like crontab.guru, then try it in a Schedule Trigger.')],
    words: [W('recurring', 'بيتكرر بانتظام', 'happening again at regular times', 'A recurring job runs every Monday at 9.'),
      W('time zone', 'المنطقة الزمنية اللي المواعيد بتتحسب بيها', 'the region whose clock the times use', 'Set the time zone to Africa/Cairo.')],
    quiz: [Q(B('`0 9 * * 0-4` معناها:', '`0 9 * * 0-4` means:'), [B('9 الصبح من الأحد للخميس', '9 am Sunday to Thursday'), B('كل 9 دقايق', 'every 9 minutes'), B('يوم 9 في الشهر', 'the 9th of the month')], 0, B('دقيقة 0، ساعة 9، أيام 0 لـ 4.', 'Minute 0, hour 9, days 0 to 4.'))] },
  { learn: [L(B('منع التكرار في الـ polling', 'Avoiding duplicates when polling'),
      B('الـ polling بيسأل «إيه الجديد؟». لو مخدتش بالك هتعالج نفس العنصر مرتين. الحلول: التريجرز الجاهزة بتفتكر آخر عنصر لوحدها؛ ولو بتعمل polling بنفسك استخدم نود **Remove Duplicates** (بيفتكر الـ IDs بين التشغيلات)، أو احفظ آخر وقت/آخر ID في شيت أو في **static data**.',
        'Polling asks «what is new?». Careless polling processes the same item twice. Fixes: built-in triggers remember the last item themselves; when you poll yourself use the **Remove Duplicates** node (it remembers IDs across runs), or store the last time/ID in a sheet or in **static data**.'),
      'Schedule (5 min) → HTTP: get orders → Remove Duplicates\n  (Operation: Remove items processed in previous executions, Value: {{ $json.id }})\n→ only new orders continue')],
    practice: [B('اعمل polling كل دقيقة على API بيرجع نفس البيانات، وحط Remove Duplicates؛ شغّله مرتين واتأكد إن التانية مطلّعتش حاجة.', 'Poll an API that returns the same data every minute, add Remove Duplicates, run twice and check the second run outputs nothing.'),
      B('اكتب في ملاحظاتك: ليه الـ ID أحسن من الاسم في منع التكرار؟', 'Write in your notes: why is an ID better than a name for avoiding duplicates?')],
    words: [W('duplicate', 'نسخة مكررة من نفس الحاجة', 'a repeated copy of the same thing', 'Remove duplicates before saving.'),
      W('deduplicate', 'تشيل التكرار', 'to remove repeated copies', 'Deduplicate the orders by id.')],
    quiz: [Q(B('أحسن حقل لمنع التكرار:', 'The best field to avoid duplicates:'), [B('الـ id', 'the id'), B('الاسم', 'the name'), B('السعر', 'the price')], 0, B('الـ id ثابت ومش بيتكرر.', 'An id is stable and unique.'))] },
  { learn: [L(B('الرد على الـ webhook', 'Replying to a webhook'),
      B('في نود Webhook اختيار **Respond**: «Immediately» يرد فورًا بـ 200 وبعدين يكمّل الشغل (الأحسن لو الخدمة مستعجلة)، أو «Using Respond to Webhook node» عشان ترد بنتيجة بعد ما تحسبها. كتير من الخدمات بتلغي الطلب لو مردّتش في ثواني، وتبعته تاني، فتبقى عندك نسخ مكررة.',
        'The Webhook node has a **Respond** option: «Immediately» answers 200 at once and then keeps working (best when the service is impatient), or «Using Respond to Webhook node» to answer with a result after computing it. Many services give up if you do not answer within seconds, and send again — so you get duplicates.'),
      'Webhook (Respond: Using Respond to Webhook node)\n  → Validate input → Save to Sheet\n  → Respond to Webhook: 200 {"ok": true, "id": "{{ $json.id }}"}')],
    practice: [B('اعمل webhook يرجّع `{"ok": true}` على طول، وواحد تاني يرجّع نتيجة حساب بعد 3 نودز. جرّبهم بـ curl.', 'Make one webhook that returns `{"ok": true}` immediately, and another that returns a calculated result after 3 nodes. Test both with curl.'),
      B('ضيف نود Wait 20 ثانية قبل الرد وشوف curl بيعمل إيه — وده بيعلّمك ليه الرد السريع مهم.', 'Add a 20-second Wait before the reply and see what curl does — this shows why a quick answer matters.')],
    words: [W('acknowledge', 'ترد إنك استلمت (من غير ما تخلص الشغل)', 'to reply that you received it (before finishing the work)', 'Acknowledge the webhook with 200 first.'),
      W('timeout', 'أقصى وقت للانتظار قبل ما الطلب يتلغي', 'the longest wait before a request is cancelled', 'The service has a 10-second timeout.')],
    quiz: [Q(B('الخدمة بتلغي لو مردّتش في 5 ثواني والشغل بياخد دقيقة:', 'The service gives up after 5 s and your work takes a minute:'), [B('رد فورًا وكمّل بعدين', 'reply at once and continue after'), B('خلّي الشغل أسرع', 'make the work faster'), B('متردش خالص', 'never reply')], 0, B('Respond Immediately.', 'Respond Immediately.'))] },
  { learn: [L(B('الـ workflow اللي بيتنادي (Execute Workflow Trigger)', 'The called workflow (Execute Workflow Trigger)'),
      B('workflow بيبدأ بـ **When Executed by Another Workflow** بيبقى زي «دالة»: workflows تانية تناديه بنود Execute Workflow وتبعتله بيانات، ويرجّع نتيجة. حدّد المدخلات اللي مستنيها (اسمها ونوعها) عشان اللي بيناديه يعرف يبعت إيه.',
        'A workflow that starts with **When Executed by Another Workflow** works like a «function»: other workflows call it with an Execute Workflow node, send it data, and get a result back. Define the inputs it expects (name and type) so callers know what to send.'),
      'Workflow A: … → Execute Workflow ("Format phone") → …\nWorkflow "Format phone":\n  When Executed by Another Workflow (inputs: phone: string)\n  → Code: clean the number → return { phone_e164 }')],
    practice: [B('اعمل workflow اسمه `Format phone` بياخد رقم ويرجّعه بصيغة `+20…`، وناديه من workflow تاني.', 'Build a `Format phone` workflow that takes a number and returns it as `+20…`, and call it from another workflow.'),
      B('ناديه من workflowين مختلفين؛ صلّح فيه غلطة مرة واحدة واتأكد إن الاتنين استفادوا.', 'Call it from two different workflows; fix a bug in it once and check both benefit.')],
    words: [W('reusable', 'تقدر تستخدمه في أكتر من مكان', 'that can be used in more than one place', 'A reusable workflow formats phone numbers.'),
      W('caller', 'اللي بينادي workflow أو دالة', 'whatever calls a workflow or function', 'The caller sends the phone number.')],
    quiz: [Q(B('الـ workflow اللي بيتنادي شبه إيه في البرمجة؟', 'A called workflow is like what in programming?'), [B('دالة', 'a function'), B('متغير', 'a variable'), B('تعليق', 'a comment')], 0, B('مدخلات ← شغل ← نتيجة.', 'Inputs → work → result.'))] },
  { review: [B('⚡ اختيار التريجر، والـ cron، ومنع التكرار في الـ polling.', '⚡ Choosing the trigger, cron, and avoiding duplicates when polling.'),
      B('⚡ الرد على الـ webhook في الوقت، والـ workflows اللي بتتنادي كدوال.', '⚡ Answering webhooks in time, and called workflows as functions.')] }
] };
