// n8n week 4 — the intensive hour (weeks 1–12 are 3 hours a day). Merged into the week by tools/build_weeks.js.
const B = (ar, en) => ({ ar, en });
const L = (h, p, ex) => ({ h, p, ex });
const W = (t, ar, en, ex) => ({ t, m: B(ar, en), ex });
const Q = (q, o, a, why) => ({ q, o, a, why });
module.exports = { days: [
  { learn: [L(B('قيم افتراضية بـ ?? و?.', 'Defaults with ?? and ?.'),
      B('البيانات الحقيقية ناقصة دايمًا. `$json.phone ?? \'no phone\'` بيدّي قيمة بديلة لو الحقل `null` أو مش موجود. و`$json.customer?.email` مش هيكسر لو `customer` مش موجود. اتنين مع بعض بيمنعوا نص أخطاء الـ expressions.',
        'Real data is always incomplete. `$json.phone ?? \'no phone\'` gives a fallback when the field is `null` or missing. `$json.customer?.email` does not break when `customer` is missing. Together they prevent half of expression errors.'),
      '{{ $json.customer?.email ?? "unknown@example.com" }}\n{{ ($json.tags ?? []).join(", ") }}\n{{ $json.qty ?? 1 }}')],
    practice: [B('اعمل 3 عناصر: واحد كامل، وواحد من غير `phone`، وواحد من غير `customer` خالص؛ واكتب expressions متكسرش على أي واحد فيهم.', 'Make 3 items: one complete, one without `phone`, one without `customer` at all; write expressions that do not break on any of them.'),
      B('قارن `??` و`||` مع القيمة `0`: إيه اللي بيطلع وليه؟', 'Compare `??` and `||` with the value `0`: what comes out and why?')],
    words: [W('fallback', 'قيمة بديلة لما الأصلية مش موجودة', 'a replacement value when the original is missing', 'Use "unknown" as a fallback.'),
      W('nullish', 'قيمته null أو undefined', 'being null or undefined', '?? only replaces nullish values.')],
    quiz: [Q(B('`0 ?? 5` بتطلع:', '`0 ?? 5` gives:'), [B('0', '0'), B('5', '5'), B('خطأ', 'an error')], 0, B('?? بيستبدل null وundefined بس.', '?? only replaces null and undefined.'))] },
  { learn: [L(B('`$("Node").first()` و`.all()` و`.item`', '`$("Node").first()`, `.all()` and `.item`'),
      B('`$("Get customer").first().json` أول عنصر من النود ده. `.all()` كل العناصر (array). و`.item` العنصر **المرتبط** بالعنصر الحالي (n8n بيتتبع مين جه من مين). استخدم `.item` جوه التدفق العادي، و`.first()` لما النود ده بيطلّع عنصر واحد بس (زي إعدادات).',
        '`$("Get customer").first().json` is the first item of that node. `.all()` is every item (an array). `.item` is the item **linked** to the current one (n8n tracks which came from which). Use `.item` in a normal flow, and `.first()` when that node outputs a single item (like settings).'),
      '{{ $("Settings").first().json.currency }}\n{{ $("Get customer").item.json.name }}\n{{ $("Get orders").all().length }} orders')],
    practice: [B('اعمل workflow: Settings (عنصر واحد) ← Get users (10) ← Edit Fields يستخدم `.first()` من Settings و`.item` من Get users.', 'Build a workflow: Settings (one item) → Get users (10) → Edit Fields using `.first()` from Settings and `.item` from Get users.'),
      B('ضيف نود Code في النص يغيّر ترتيب العناصر وشوف `.item` لسه بيجيب الصح ولا لأ.', 'Add a Code node in the middle that reorders items and see whether `.item` still finds the right one.')],
    words: [W('linked item', 'العنصر المرتبط بالعنصر الحالي في نود قبله', 'the item connected to the current one in an earlier node', '.item returns the linked item.'),
      W('reference', 'إشارة لقيمة في مكان تاني', 'a pointer to a value somewhere else', 'The expression has a reference to the Settings node.')],
    quiz: [Q(B('نود Settings بيطلّع عنصر واحد. تقرا منه بـ:', 'A Settings node outputs one item. Read it with:'), [B('`.first()`', '`.first()`'), B('`.all()[5]`', '`.all()[5]`'), B('`$json`', '`$json`')], 0, B('عنصر واحد ثابت لكل العناصر.', 'One fixed item for every item.'))] },
  { learn: [L(B('Luxon: المدد والمقارنة', 'Luxon: durations and comparing'),
      B('`$now.diff(DateTime.fromISO($json.due), \'days\').days` عدد الأيام بين تاريخين. `.startOf(\'day\')` بداية اليوم عشان المقارنة متتلخبطش بالساعات. و`.setZone(\'Africa/Cairo\')` قبل العرض. وللقراءة من نص مش ISO: `DateTime.fromFormat($json.date, \'dd/MM/yyyy\')`.',
        '`$now.diff(DateTime.fromISO($json.due), \'days\').days` is the number of days between two dates. `.startOf(\'day\')` gives the start of the day so hours do not confuse the comparison. Use `.setZone(\'Africa/Cairo\')` before display. To read a non-ISO text: `DateTime.fromFormat($json.date, \'dd/MM/yyyy\')`.'),
      '{{ DateTime.fromFormat($json.date, "dd/MM/yyyy").toISODate() }}\n{{ Math.floor($now.diff(DateTime.fromISO($json.due), "days").days) }} days late\n{{ $now.startOf("day") > DateTime.fromISO($json.due) ? "late" : "on time" }}')],
    practice: [B('من قايمة فواتير فيها `due`، احسب كام يوم متأخرة كل واحدة، وعلّم المتأخر أكتر من 7 أيام.', 'From a list of invoices with `due`, compute how many days each is late, and flag those more than 7 days late.'),
      B('حوّل `25/12/2026` و`2026-12-25T10:00:00Z` لنفس الشكل `2026-12-25`.', 'Turn `25/12/2026` and `2026-12-25T10:00:00Z` into the same form `2026-12-25`.')],
    words: [W('duration', 'مدة زمنية (أيام، ساعات)', 'a length of time (days, hours)', 'Compute the duration between the two dates.'),
      W('overdue', 'متأخر عن ميعاده', 'late, past its due date', 'Send a reminder for overdue invoices.')],
    quiz: [Q(B('عشان تقرا `25/12/2026` تستخدم:', 'To read `25/12/2026` you use:'), [B('`DateTime.fromFormat`', '`DateTime.fromFormat`'), B('`DateTime.fromISO`', '`DateTime.fromISO`'), B('`JSON.parse`', '`JSON.parse`')], 0, B('مش صيغة ISO.', 'It is not ISO format.'))] },
  { learn: [L(B('دوال n8n للـ arrays', 'n8n array helpers'),
      B('n8n بيضيف دوال جاهزة على الـ arrays جوه الـ expressions: `.pluck(\'name\')` يطلّع حقل من كل object، `.sum()` و`.average()`، `.removeDuplicates()`، `.chunk(10)` يقسّم لمجموعات، و`.isEmpty()`. بتختصر سطور كتير من الكود.',
        'n8n adds ready helpers on arrays inside expressions: `.pluck(\'name\')` takes one field from each object, `.sum()` and `.average()`, `.removeDuplicates()`, `.chunk(10)` splits into groups, and `.isEmpty()`. They save many lines of code.'),
      '{{ $json.items.pluck("price").sum() }}\n{{ $json.tags.removeDuplicates().join(", ") }}\n{{ $json.emails.chunk(50).length }} batches')],
    practice: [B('بعنصر فيه `items` (array من 6 منتجات): اطلع مجموع الأسعار، ومتوسطها، والأسماء من غير تكرار.', 'With an item holding `items` (an array of 6 products): get the sum of prices, the average, and the names without duplicates.'),
      B('اعمل نفس الحساب في Code node بـ `reduce` وقارن الطول.', 'Do the same in a Code node with `reduce` and compare the length.')],
    words: [W('pluck', 'تطلّع حقل واحد من كل عنصر', 'to take one field out of every item', 'Pluck the emails from the users.'),
      W('chunk', 'تقسّم قايمة لمجموعات صغيرة', 'to split a list into small groups', 'Chunk the list into groups of 50.')],
    quiz: [Q(B('`[{"a":1},{"a":2}].pluck("a")` بتطلع:', '`[{"a":1},{"a":2}].pluck("a")` gives:'), [B('`[1, 2]`', '`[1, 2]`'), B('`3`', '`3`'), B('`"a"`', '`"a"`')], 0, B('الحقل من كل عنصر.', 'The field from each item.'))] },
  { learn: [L(B('اقرا رسالة خطأ الـ expression', 'Reading an expression error'),
      B('الأخطاء المتكررة: `Cannot read properties of undefined` (حقل قبله مش موجود → `?.`)، `… is not a function` (بتنادي دالة على نوع غلط، زي `.toUpperCase()` على رقم)، `Referenced node is unexecuted` (النود اللي بتقرا منه مااشتغلش في الفرع ده)، و`Invalid syntax` (قوس أو تنصيص ناقص). المعاينة تحت الخانة بتوريك النتيجة قبل التشغيل.',
        'Common errors: `Cannot read properties of undefined` (a field before it is missing → `?.`), `… is not a function` (calling a method on the wrong type, like `.toUpperCase()` on a number), `Referenced node is unexecuted` (the node you read from did not run on this branch), and `Invalid syntax` (a missing bracket or quote). The preview under the field shows the result before you run.'),
      '✗ {{ $json.price.toUpperCase() }}   → is not a function (price is a number)\n✓ {{ String($json.price) }}\n✗ {{ $json.user.name }}            → Cannot read properties of undefined\n✓ {{ $json.user?.name ?? "-" }}')],
    practice: [B('اعمل كل خطأ من الأربعة عمدًا، واكتب رسالته وحلّه في ملف `expression-errors.md`.', 'Cause each of the four errors on purpose, and write its message and fix in an `expression-errors.md` file.'),
      B('اسأل AI بالبرومبت «Explain this n8n expression error» من صفحة البرومبتات وقارن شرحه بشرحك.', 'Ask an AI with the «explain this error» prompt from the prompts page and compare its explanation with yours.')],
    words: [W('preview', 'معاينة النتيجة قبل التشغيل', 'a look at the result before running', 'The preview shows undefined, so check the field.'),
      W('syntax error', 'خطأ في كتابة الكود نفسه (قوس، تنصيص)', 'a mistake in how the code is written (a bracket, a quote)', 'A missing bracket causes a syntax error.')],
    quiz: [Q(B('`Cannot read properties of undefined` غالبًا معناها:', '`Cannot read properties of undefined` usually means:'), [B('حقل قبل النقطة مش موجود', 'a field before the dot is missing'), B('الإنترنت قطع', 'the internet is down'), B('الـ credential غلط', 'the credential is wrong')], 0, B('استخدم ?. و??.', 'Use ?. and ??.'))] },
  { review: [B('⚡ ?? و?. والقيم الافتراضية، و.first()/.all()/.item.', '⚡ ?? and ?. defaults, and .first()/.all()/.item.'),
      B('⚡ Luxon للمدد والصيغ، ودوال الـ arrays، وقراءة أخطاء الـ expressions: طبّقهم في مشروع الشهر.', '⚡ Luxon for durations and formats, array helpers, and reading expression errors: use them in the month project.')] }
] };
