// n8n week 5 — the intensive hour (weeks 1–12 are 3 hours a day). Merged into the week by tools/build_weeks.js.
const B = (ar, en) => ({ ar, en });
const L = (h, p, ex) => ({ h, p, ex });
const W = (t, ar, en, ex) => ({ t, m: B(ar, en), ex });
const Q = (q, o, a, why) => ({ q, o, a, why });
module.exports = { days: [
  { learn: [L(B('Append or Update: مفتاح الصف', 'Append or Update: the row key'),
      B('عملية **Append or Update Row** بتدوّر على صف بقيمة عمود معيّن (**Column to match on**، زي `order_id`): لو لقته تحدّثه، لو ملقتهوش تضيف صف جديد. كده تشغيل الـ workflow مرتين مش هيعمل صفوف مكررة. اختار عمود قيمته مش بتتكرر ومش بتتغيّر.',
        'The **Append or Update Row** operation looks for a row by one column’s value (**Column to match on**, like `order_id`): if found it updates it, if not it adds a new row. So running the workflow twice does not create duplicate rows. Pick a column whose value is unique and never changes.'),
      'Google Sheets → Append or Update Row\n  Column to match on: order_id\n  order_id = {{ $json.id }}   status = {{ $json.status }}\nrun 1: adds row 1042 · run 2: updates row 1042')],
    practice: [B('اعمل شيت `orders` وابعتله نفس 3 طلبات مرتين بـ Append، وبعدين بـ Append or Update. قارن عدد الصفوف.', 'Make an `orders` sheet and send the same 3 orders twice with Append, then with Append or Update. Compare the row counts.'),
      B('غيّر حالة طلب واحد وشغّل تاني: اتأكد إن الصف اتحدّث بس.', 'Change one order’s status and run again: check only that row was updated.')],
    words: [W('upsert', 'تحدّث لو موجود أو تضيف لو جديد', 'update if it exists, insert if it is new', 'Append or Update is an upsert.'),
      W('match column', 'العمود اللي بيتدوّر بيه على الصف', 'the column used to find the row', 'Use order_id as the match column.')],
    quiz: [Q(B('ليه Append or Update أحسن من Append لمزامنة الطلبات؟', 'Why is Append or Update better than Append for syncing orders?'), [B('مش بيكرر الصفوف', 'it does not duplicate rows'), B('أسرع دايمًا', 'it is always faster'), B('مش محتاج credential', 'it needs no credential')], 0, B('بيحدّث الموجود.', 'It updates what exists.'))] },
  { learn: [L(B('إيميلات HTML بقالب', 'HTML emails from a template'),
      B('بدل ما تكتب الإيميل جوه النود، اعمل قالب HTML بسيط فيه خانات `{{ }}`، وخليه في نود Edit Fields أو HTML. خلّي التصميم بسيط: عمود واحد، خط واضح، زر واحد، ونسخة نص عادي للبرامج اللي مش بتعرض HTML. وجرّب على نفسك الأول دايمًا.',
        'Instead of writing the email inside the node, build a simple HTML template with `{{ }}` slots, kept in an Edit Fields or HTML node. Keep the design simple: one column, a clear font, one button, and a plain-text version for apps that do not show HTML. Always send to yourself first.'),
      '<h2>Hi {{ $json.name }},</h2>\n<p>Your booking is on <b>{{ $json.date }}</b> at {{ $json.time }}.</p>\n<p><a href="{{ $json.manage_url }}">Manage booking</a></p>')],
    practice: [B('اعمل قالب تذكير بميعاد فيه الاسم والتاريخ وزر، وابعته لنفسك من Gmail.', 'Build an appointment reminder template with the name, date and a button, and send it to yourself from Gmail.'),
      B('افتح الإيميل على الموبايل والكمبيوتر: شكله مظبوط في الاتنين؟', 'Open the email on your phone and computer: does it look right on both?')],
    words: [W('merge field', 'خانة في القالب بتتملي ببيانات كل عميل', 'a slot in a template that is filled with each customer’s data', 'The name is a merge field.'),
      W('plain text', 'نص عادي من غير تنسيق', 'text with no formatting', 'Add a plain text version of the email.')],
    quiz: [Q(B('ليه تبعت الإيميل لنفسك الأول؟', 'Why send the email to yourself first?'), [B('تشوف شكله الحقيقي قبل العملاء', 'to see how it really looks before customers do'), B('عشان Gmail يطلب كده', 'because Gmail requires it'), B('عشان يبقى أسرع', 'to make it faster')], 0, B('الغلطة قدامك انت بس.', 'Only you see the mistake.'))] },
  { learn: [L(B('بحث Gmail المتقدم', 'Advanced Gmail search'),
      B('تريجر Gmail ونود Get Many بيقبلوا نفس بحث Gmail: `from:billing@shop.com`، `subject:invoice`، `has:attachment`، `is:unread`، `newer_than:2d`، `-label:processed`. وبعد ما تعالج الإيميل حطله label `processed` عشان متعالجوش تاني.',
        'The Gmail trigger and Get Many accept the same search as Gmail: `from:billing@shop.com`, `subject:invoice`, `has:attachment`, `is:unread`, `newer_than:2d`, `-label:processed`. After handling an email add a `processed` label so you do not handle it again.'),
      'Search: from:(billing@shop.com) subject:invoice has:attachment -label:processed\n→ extract the attachment → save to Drive\n→ Gmail: Add Label "processed"')],
    practice: [B('جرّب البحث ده في Gmail نفسه الأول لحد ما يجيب الإيميلات الصح، وبعدين حطه في n8n.', 'Try the search in Gmail itself until it finds the right emails, then put it in n8n.'),
      B('ضيف label `processed` بعد المعالجة وشغّل مرتين: التانية لازم متلاقيش حاجة.', 'Add a `processed` label after handling and run twice: the second run must find nothing.')],
    words: [W('search operator', 'كلمة خاصة بتحدد البحث زي from: وhas:', 'a special word that narrows a search, like from: and has:', 'Use the has:attachment search operator.'),
      W('attachment', 'ملف مرفق مع الإيميل', 'a file sent with an email', 'Save each attachment to Drive.')],
    quiz: [Q(B('`-label:processed` معناها:', '`-label:processed` means:'), [B('الإيميلات اللي مش عليها الـ label ده', 'emails without that label'), B('امسح الـ label', 'delete the label'), B('الإيميلات اللي عليها الـ label', 'emails with that label')], 0, B('العلامة - = استبعد.', 'The minus sign = exclude.'))] },
  { learn: [L(B('أوامر البوت والرد حسب الأمر', 'Bot commands and routing'),
      B('المستخدم بيكتب `/start` أو `/price` أو `/help`. بعد Telegram Trigger حط **Switch** على `{{ $json.message.text.split(" ")[0] }}` وكل أمر ليه فرع، وفرع افتراضي يرد «مش فاهم، اكتب /help». ومتنساش تسجّل الأوامر عند BotFather عشان تظهر في القايمة.',
        'The user types `/start`, `/price` or `/help`. After the Telegram Trigger add a **Switch** on `{{ $json.message.text.split(" ")[0] }}` with a branch per command, and a fallback branch that replies «I did not understand, type /help». Register the commands with BotFather so they appear in the menu.'),
      'Telegram Trigger → Switch (command)\n  /start → welcome message\n  /price → read price from Sheet → reply\n  /help  → list of commands\n  other  → "type /help"')],
    practice: [B('اعمل بوت بـ 3 أوامر وفرع افتراضي، وسجّل الأوامر عند BotFather بـ `/setcommands`.', 'Build a bot with 3 commands and a fallback branch, and register them with BotFather using `/setcommands`.'),
      B('خلّي `/price laptop` يقرا كلمة بعد الأمر ويدوّر عليها في شيت.', 'Make `/price laptop` read the word after the command and look it up in a sheet.')],
    words: [W('command', 'أمر بيبدأ بـ / للبوت', 'an instruction starting with / for a bot', 'The /help command lists the options.'),
      W('dispatch', 'توزّع كل حالة على الفرع بتاعها', 'to send each case to the part that handles it', 'The Switch dispatches each command.')],
    quiz: [Q(B('الفرع الافتراضي في Switch مهم ليه؟', 'Why does the Switch need a fallback branch?'), [B('عشان يرد على أي رسالة مش متوقعة', 'to answer any unexpected message'), B('عشان يسرّع البوت', 'to speed up the bot'), B('مش مهم', 'it does not matter')], 0, B('المستخدمين بيكتبوا أي حاجة.', 'Users type anything.'))] },
  { learn: [L(B('callback من أزرار Telegram', 'Callbacks from Telegram buttons'),
      B('الأزرار (inline keyboard) لما حد يدوس عليها بتبعت **callback_query** مش رسالة. فعّل الحدث ده في التريجر، واقرا `callback_query.data` (اللي انت حددته للزر، زي `confirm_1042`)، ورد بـ **Answer Query** عشان علامة التحميل تختفي من عند المستخدم.',
        'When someone presses an inline keyboard button, Telegram sends a **callback_query**, not a message. Enable that update in the trigger, read `callback_query.data` (the value you set on the button, like `confirm_1042`), and reply with **Answer Query** so the loading sign disappears for the user.'),
      'button: { text: "✅ Confirm", callback_data: "confirm_1042" }\nTrigger (updates: message, callback_query)\n→ IF {{ $json.callback_query?.data?.startsWith("confirm_") }}\n→ update the booking → Answer Query: "Confirmed ✅"')],
    practice: [B('ابعت رسالة فيها زرين (تأكيد / إلغاء) وخلّي كل زر يكتب في شيت.', 'Send a message with two buttons (confirm / cancel) and make each button write to a sheet.'),
      B('اتأكد إن الزر بيشتغل مرة واحدة: لو اتداس تاني يرد «اتأكد قبل كده».', 'Make the button work once: if pressed again, reply «already confirmed».')],
    words: [W('callback', 'إشارة بترجع لما المستخدم يعمل حاجة زي يدوس زر', 'a signal sent back when the user does something like press a button', 'The callback carries the booking id.'),
      W('button press', 'ضغطة المستخدم على زر في رسالة البوت', 'the user tapping a button in a bot message', 'A button press arrives as a callback query.')],
    quiz: [Q(B('دوسة زر inline بتوصل كـ:', 'A press on an inline button arrives as:'), [B('callback_query', 'a callback_query'), B('رسالة نصية', 'a text message'), B('إيميل', 'an email')], 0, B('لازم تفعّلها في التريجر.', 'You must enable it in the trigger.'))] },
  { review: [B('⚡ Append or Update بعمود مفتاح، وقوالب الإيميل HTML.', '⚡ Append or Update with a key column, and HTML email templates.'),
      B('⚡ بحث Gmail وlabel للمعالَج، وأوامر البوت، وأزرار callback: اجمعهم في بوت حجز صغير.', '⚡ Gmail search and a label for handled mail, bot commands and callback buttons: combine them in a small booking bot.')] }
] };
