// n8n week 6 — the intensive hour (weeks 1–12 are 3 hours a day). Merged into the week by tools/build_weeks.js.
const B = (ar, en) => ({ ar, en });
const L = (h, p, ex) => ({ h, p, ex });
const W = (t, ar, en, ex) => ({ t, m: B(ar, en), ex });
const Q = (q, o, a, why) => ({ q, o, a, why });
module.exports = { days: [
  { learn: [L(B('الـ pagination', 'Pagination'),
      B('أغلب الـ APIs بترجع النتايج على صفحات (مثلًا 100 في المرة). أنواع: **page/limit** (`?page=2`)، **offset** (`?offset=200`)، و**cursor** (الرد فيه `next_cursor` تبعته في الطلب الجاي). HTTP Request فيه إعداد **Pagination** بيلف لوحده لحد ما الصفحات تخلص؛ حدّدله إمتى يقف.',
        'Most APIs return results in pages (e.g. 100 at a time). Kinds: **page/limit** (`?page=2`), **offset** (`?offset=200`), and **cursor** (the response has a `next_cursor` you send in the next request). HTTP Request has a **Pagination** option that loops by itself until the pages run out; tell it when to stop.'),
      'HTTP Request → Options → Pagination\n  Mode: Update a Parameter in Each Request\n  Name: page   Value: {{ $pageCount + 1 }}\n  Complete when: response is empty')],
    practice: [B('اجلب كل الـ posts من `https://jsonplaceholder.typicode.com/posts?_page=1&_limit=10` بالـ Pagination واتأكد إن العدد 100.', 'Fetch every post from `https://jsonplaceholder.typicode.com/posts?_page=1&_limit=10` with Pagination and check the count is 100.'),
      B('اقرا توثيق API تستخدمه: نوع الـ pagination بتاعه إيه؟', 'Read the docs of an API you use: which kind of pagination does it have?')],
    words: [W('next page', 'الصفحة الجاية من النتايج', 'the following page of results', 'Request the next page until it is empty.'),
      W('cursor', 'علامة بتقول الصفحة الجاية تبدأ منين', 'a marker that says where the next page starts', 'Send the cursor from the last response.')],
    quiz: [Q(B('الـ API رجّع 100 من 950 عنصر. تعمل إيه؟', 'The API returned 100 of 950 items. What do you do?'), [B('تفعّل الـ pagination', 'enable pagination'), B('تقبل الـ 100', 'accept the 100'), B('تغيّر الـ API', 'change the API')], 0, B('اجلب كل الصفحات.', 'Fetch every page.'))] },
  { learn: [L(B('مكان المفتاح: header ولا query', 'Where the key goes: header or query'),
      B('التوثيق بيقولك المفتاح يتحط فين: header زي `Authorization: Bearer …` أو `X-API-Key: …`، أو في الرابط `?api_key=…`. الـ header أأمن لأن الروابط بتتسجل في logs كتير. في n8n استخدم **Header Auth** أو **Query Auth** credential حسب التوثيق — مش تكتبه بإيدك في الخانة.',
        'The docs tell you where the key goes: a header like `Authorization: Bearer …` or `X-API-Key: …`, or in the URL `?api_key=…`. A header is safer because URLs end up in many logs. In n8n use a **Header Auth** or **Query Auth** credential as the docs say — never type it into the field.'),
      'Docs: "Send your key in the X-API-Key header"\n→ Credential: Header Auth  Name: X-API-Key  Value: ••••••\n→ HTTP Request: Authentication = Generic → Header Auth')],
    practice: [B('اختار API مجاني بيطلب مفتاح (مثلًا طقس)، واعمل credential من النوع الصح، وجرّب طلب.', 'Pick a free API that needs a key (e.g. weather), make a credential of the right type, and try a request.'),
      B('غلّط المفتاح عمدًا وسجّل الـ status والرسالة اللي رجعت.', 'Break the key on purpose and note the status and message returned.')],
    words: [W('auth header', 'header فيه بيانات الدخول للـ API', 'a header that carries the API login details', 'Put the key in the auth header.'),
      W('query string', 'الجزء من الرابط بعد علامة ?', 'the part of a URL after the ? sign', 'Avoid keys in the query string.')],
    quiz: [Q(B('ليه الـ header أأمن من الرابط للمفتاح؟', 'Why is a header safer than the URL for a key?'), [B('الروابط بتتسجل في logs كتير', 'URLs end up in many logs'), B('الـ header أسرع', 'headers are faster'), B('مفيش فرق', 'no difference')], 0, B('سجلات السيرفر والمتصفح.', 'Server and browser logs.'))] },
  { learn: [L(B('الـ scopes في OAuth2', 'Scopes in OAuth2'),
      B('الـ **scope** بيحدد الصلاحية اللي بتطلبها: قراءة بس ولا كتابة، إيميل بس ولا Drive كمان. اطلب **أقل** scopes تكفي الشغل: العميل بيوافق أسهل، ولو التوكن اتسرّب الضرر أقل. لو غيّرت الـ scopes لازم تعيد الربط (reconnect).',
        'A **scope** sets the permission you ask for: read only or write, email only or Drive too. Ask for the **fewest** scopes that do the job: clients agree more easily, and if the token leaks the damage is smaller. If you change scopes you must reconnect.'),
      'needs: read the calendar only\n✗ https://www.googleapis.com/auth/calendar\n✓ https://www.googleapis.com/auth/calendar.readonly')],
    practice: [B('افتح صفحة الموافقة بتاعة Google لما تربط credential، واقرا الصلاحيات المطلوبة واحدة واحدة.', 'Open Google’s consent screen when you connect a credential, and read each permission requested.'),
      B('اكتب لـ 3 workflows عندك: أقل scope محتاجينه إيه؟', 'For 3 of your workflows write the smallest scope each needs.')],
    words: [W('least privilege', 'تدّي أقل صلاحية تكفي الشغل', 'giving only the access the job needs', 'Least privilege limits the damage of a leak.'),
      W('reconnect', 'تعيد ربط الحساب عشان الصلاحيات الجديدة', 'to link the account again for new permissions', 'Reconnect the credential after changing scopes.')],
    quiz: [Q(B('محتاج تقرا ملفات Drive بس:', 'You only need to read Drive files:'), [B('scope قراءة بس', 'a read-only scope'), B('صلاحية كاملة احتياطي', 'full access just in case'), B('من غير scope', 'no scope')], 0, B('أقل صلاحية تكفي.', 'The least access that works.'))] },
  { learn: [L(B('الـ batching عشان حدود الطلبات', 'Batching for rate limits'),
      B('لو الـ API بيسمح مثلًا بـ 10 طلبات في الثانية وعندك 500 عنصر، HTTP Request فيه **Batching**: عدد العناصر في كل دفعة ووقت الانتظار بين الدفعات. أو استخدم Loop Over Items مع Wait. اقرا الحد في التوثيق أو في headers زي `X-RateLimit-Remaining`.',
        'If the API allows, say, 10 requests a second and you have 500 items, HTTP Request has **Batching**: items per batch and the wait between batches. Or use Loop Over Items with a Wait. Find the limit in the docs or in headers such as `X-RateLimit-Remaining`.'),
      'HTTP Request → Options → Batching\n  Items per Batch: 10\n  Batch Interval (ms): 1100\n500 items → 50 batches → about 55 seconds, no 429')],
    practice: [B('ابعت 50 طلب لـ `https://httpbin.org/get` بدفعات 5 كل ثانية، وقيس الوقت الكلي.', 'Send 50 requests to `https://httpbin.org/get` in batches of 5 per second, and measure the total time.'),
      B('احسب: API حده 60 طلب في الدقيقة وعندك 1000 عنصر — هياخد قد إيه؟', 'Work it out: an API allows 60 requests a minute and you have 1000 items — how long will it take?')],
    words: [W('batch interval', 'وقت الانتظار بين كل دفعة والتانية', 'the wait between one batch and the next', 'Set the batch interval to 1100 ms.'),
      W('throttle', 'تبطّأ الطلبات عمدًا عشان متعديش الحد', 'to slow requests on purpose to stay under a limit', 'Throttle the calls to 10 per second.')],
    quiz: [Q(B('حد 10 طلبات/ثانية و100 عنصر: أحسن إعداد؟', 'A limit of 10 per second and 100 items: best setting?'), [B('10 في الدفعة كل ~1.1 ثانية', '10 per batch every ~1.1 s'), B('100 مرة واحدة', 'all 100 at once'), B('1 كل دقيقة', '1 per minute')], 0, B('تحت الحد بهامش صغير.', 'Under the limit with a small margin.'))] },
  { learn: [L(B('رفع الملفات: multipart/form-data', 'Uploading files: multipart/form-data'),
      B('لما الـ API يطلب ملف، الـ body بيبقى **Form-Data** مش JSON. في HTTP Request اختار Body: Form-Data، وخانة نوعها **n8n Binary File** واسم الـ binary (غالبًا `data`)، وخانات نص عادية للمعلومات التانية. الملف لازم يكون جاي من نود قبله (Read File، Google Drive، Telegram…).',
        'When an API wants a file, the body is **Form-Data**, not JSON. In HTTP Request choose Body: Form-Data, a field of type **n8n Binary File** with the binary name (often `data`), and normal text fields for other information. The file must come from an earlier node (Read File, Google Drive, Telegram…).'),
      'Google Drive: Download → (binary: data)\nHTTP Request POST /upload\n  Body: Form-Data\n    file  = n8n Binary File (data)\n    title = {{ $json.name }}')],
    practice: [B('نزّل ملف من Drive أو Read File، وارفعه لـ `https://httpbin.org/post` كـ form-data وشوف الرد.', 'Download a file from Drive or Read File and upload it to `https://httpbin.org/post` as form-data, then read the response.'),
      B('افتح تبويب Binary في النود وشوف اسم الملف ونوعه وحجمه.', 'Open the Binary tab in the node and look at the file name, type and size.')],
    words: [W('multipart', 'طلب فيه أجزاء كتير زي ملف ونص مع بعض', 'a request made of several parts, such as a file and text together', 'Upload the file as multipart form data.'),
      W('form-data', 'شكل body بيبعت ملفات وخانات مع بعض', 'a body format that sends files and fields together', 'Upload the PDF as form-data.')],
    quiz: [Q(B('عشان ترفع PDF لـ API غالبًا تستخدم:', 'To upload a PDF to an API you usually use:'), [B('Form-Data', 'Form-Data'), B('JSON', 'JSON'), B('Query parameter', 'a query parameter')], 0, B('الملفات بتتبعت multipart.', 'Files go as multipart.'))] },
  { review: [B('⚡ الـ pagination بأنواعها، ومكان المفتاح، والـ scopes.', '⚡ Kinds of pagination, where the key goes, and scopes.'),
      B('⚡ Batching تحت حد الطلبات، ورفع الملفات form-data: طبّقهم على API حقيقي.', '⚡ Batching under the rate limit and form-data uploads: use them on a real API.')] }
] };
