// n8n week 7 — the intensive hour (weeks 1–12 are 3 hours a day). Merged into the week by tools/build_weeks.js.
const B = (ar, en) => ({ ar, en });
const L = (h, p, ex) => ({ h, p, ex });
const W = (t, ar, en, ex) => ({ t, m: B(ar, en), ex });
const Q = (q, o, a, why) => ({ q, o, a, why });
module.exports = { days: [
  { learn: [L(B('مسارات بمتغيّرات', 'Paths with parameters'),
      B('نود Webhook بيقبل مسار فيه متغيّر: `orders/:id` يخلّي `/orders/1042` يوصل و`id = 1042` في `$json.params.id`. كده API واحد يخدم كل الطلبات بدل webhook لكل طلب. واستخدم الـ method (GET يقرا، POST يضيف، PATCH يعدّل جزء، DELETE يمسح) عشان المعنى يبقى واضح.',
        'The Webhook node accepts a path with a parameter: `orders/:id` lets `/orders/1042` arrive with `id = 1042` in `$json.params.id`. One API then serves every order instead of a webhook per order. Use the method (GET reads, POST adds, PATCH changes part, DELETE removes) so the meaning is clear.'),
      'GET    /webhook/orders/:id   → read one order\nPOST   /webhook/orders       → create an order\nPATCH  /webhook/orders/:id   → change the status\n{{ $json.params.id }}  →  "1042"')],
    practice: [B('اعمل `GET orders/:id` يدوّر على الطلب في شيت ويرجّعه، ويرجّع 404 لو مش موجود.', 'Build `GET orders/:id` that finds the order in a sheet and returns it, or 404 if it does not exist.'),
      B('جرّبه بـ curl على 3 أرقام: موجود، مش موجود، وحروف بدل رقم.', 'Test it with curl on 3 ids: one that exists, one that does not, and letters instead of a number.')],
    words: [W('route parameter', 'جزء متغيّر في المسار زي :id', 'a variable part of the route, like :id', 'The order id is a route parameter.'),
      W('rest api', 'API بيستخدم روابط للحاجات وmethods للأفعال', 'an API that uses URLs for things and methods for actions', 'GET /orders/1042 is typical of a REST API.')],
    quiz: [Q(B('عشان تعدّل حالة طلب بس، الـ method المناسب:', 'To change only an order’s status, the right method is:'), [B('PATCH', 'PATCH'), B('GET', 'GET'), B('DELETE', 'DELETE')], 0, B('تعديل جزئي.', 'A partial update.'))] },
  { learn: [L(B('شكل ثابت للأخطاء', 'A consistent error format'),
      B('اتفق على شكل واحد لكل الأخطاء، عشان اللي بيستخدم الـ API يتعامل معاها بكود واحد: status مناسب (400، 404، 422) و body زي `{"error": {"code": "...", "message": "...", "field": "..."}}`. الرسالة تقول المشكلة وإزاي تتصلّح، من غير تفاصيل داخلية زي اسم الشيت أو الـ stack.',
        'Agree on one shape for every error, so API users can handle them with one piece of code: a fitting status (400, 404, 422) and a body like `{"error": {"code": "...", "message": "...", "field": "..."}}`. The message says what is wrong and how to fix it, without internal details such as the sheet name or the stack.'),
      '422 {"error": {"code": "invalid_phone", "field": "phone",\n      "message": "phone must look like 01xxxxxxxxx"}}\n404 {"error": {"code": "not_found", "message": "order 1042 does not exist"}}')],
    practice: [B('اعمل sub-workflow اسمه `API error` بياخد code وmessage وstatus ويرد بالشكل الموحد، واستخدمه في كل أخطاء الـ API.', 'Build an `API error` sub-workflow that takes code, message and status and replies in the shared shape, and use it for every API error.'),
      B('راجع رسايل الخطأ: فيها أي تفاصيل داخلية مالهاش لازمة؟', 'Review your error messages: do any reveal internal details they should not?')],
    words: [W('machine-readable', 'مكتوب بشكل البرامج تفهمه بسهولة', 'written so programs can read it easily', 'Add a machine-readable code to each error.'),
      W('consistent', 'ماشي على نفس الشكل كل مرة', 'following the same pattern every time', 'Keep the error format consistent.')],
    quiz: [Q(B('رسالة الخطأ للمستخدم لازم:', 'An error message for the user should:'), [B('تقول المشكلة وإزاي تتصلّح', 'say what is wrong and how to fix it'), B('تعرض الـ stack كله', 'show the whole stack'), B('تكون فاضية', 'be empty')], 0, B('مفيدة ومن غير أسرار داخلية.', 'Helpful, without internal secrets.'))] },
  { learn: [L(B('توقيع HMAC للـ webhooks', 'HMAC signatures for webhooks'),
      B('خدمات كتير (Stripe، GitHub، Shopify) بتوقّع كل webhook: بتحسب HMAC للـ body بسر مشترك وتبعته في header. انت تحسب نفس الحساب وتقارن: لو مختلف، الطلب مزيّف أو اتعدّل. لازم تحسب على الـ **body الخام** بالظبط زي ما وصل، وتقارن بمقارنة آمنة.',
        'Many services (Stripe, GitHub, Shopify) sign every webhook: they compute an HMAC of the body with a shared secret and send it in a header. You compute the same and compare: if it differs, the request is fake or was changed. You must compute over the **raw body** exactly as received, and compare safely.'),
      "// Code node (Webhook with Raw Body on)\nconst crypto = require('crypto');\nconst sig = crypto.createHmac('sha256', $env.WEBHOOK_SECRET)\n  .update($binary.data ? Buffer.from($binary.data.data, 'base64') : '')\n  .digest('hex');\nreturn [{ json: { valid: sig === $json.headers['x-signature'] } }];")],
    practice: [B('اقرا صفحة «verify webhook signatures» في توثيق خدمة زي GitHub، واكتب الخطوات بكلامك.', 'Read the «verify webhook signatures» page of a service such as GitHub, and write the steps in your own words.'),
      B('احسب HMAC لنص بسيط في Code node بسر تجريبي، وغيّر حرف واحد في النص وشوف التوقيع اتغيّر خالص.', 'Compute an HMAC of a short text in a Code node with a test secret, change one letter and see the signature change completely.')],
    words: [W('hmac', 'توقيع بيتحسب من الرسالة وسر مشترك', 'a signature computed from a message and a shared secret', 'Check the HMAC before trusting the webhook.'),
      W('shared secret', 'سر متفق عليه بينك وبين الخدمة', 'a secret known to you and the service', 'The HMAC uses a shared secret.')],
    quiz: [Q(B('التوقيع مختلف عن اللي حسبته. يعني:', 'The signature differs from yours. It means:'), [B('الطلب مزيّف أو اتعدّل؛ ارفضه', 'the request is fake or changed; reject it'), B('عادي، كمّل', 'fine, continue'), B('الإنترنت بطيء', 'the internet is slow')], 0, B('رد 401 ومتعالجش.', 'Reply 401 and do not process it.'))] },
  { learn: [L(B('الـ idempotency: نفس الحدث مرتين', 'Idempotency: the same event twice'),
      B('الخدمات بتعيد إرسال الـ webhook لو مردّتش بسرعة أو حصل خطأ شبكة، فممكن يوصلك نفس الدفع مرتين. خلّي معالجتك **idempotent**: احفظ `event_id` اللي اتعالج، ولو وصل تاني رد 200 من غير ما تعمل حاجة. كده العميل مش هيستلم إيميلين ولا الطلب يتسجل مرتين.',
        'Services resend a webhook if you did not answer quickly or the network failed, so the same payment can reach you twice. Make your handling **idempotent**: store the handled `event_id`, and if it arrives again reply 200 and do nothing. The customer then never gets two emails and the order is never saved twice.'),
      'Webhook → Remove Duplicates (value: {{ $json.body.event_id }},\n           previous executions) → handle the event\nsecond delivery of evt_77 → removed → reply 200, nothing else')],
    practice: [B('ابعت نفس الـ webhook بنفس `event_id` 3 مرات بـ curl، واتأكد إن الصف اتسجّل مرة واحدة.', 'Send the same webhook with the same `event_id` 3 times with curl, and check the row was saved once.'),
      B('اكتب: إيه اللي ممكن يحصل في بيزنس حقيقي لو الـ webhook مش idempotent؟ (3 أمثلة)', 'Write: what could happen in a real business if the webhook is not idempotent? (3 examples)')],
    words: [W('replay attack', 'حد بيعيد إرسال طلب قديم صحيح عشان يكرر أثره', 'someone resending an old valid request to repeat its effect', 'Store event ids to stop a replay attack.'),
      W('redelivery', 'إعادة إرسال نفس الحدث من الخدمة', 'the service sending the same event again', 'Expect redelivery after a timeout.')],
    quiz: [Q(B('وصلك `evt_77` للمرة التانية:', '`evt_77` arrived a second time:'), [B('رد 200 ومتعملش حاجة', 'reply 200 and do nothing'), B('عالجه تاني', 'handle it again'), B('رد 500', 'reply 500')], 0, B('لو رديت بخطأ الخدمة هتعيد تاني.', 'An error reply makes the service retry again.'))] },
  { learn: [L(B('توثيق الـ API بمثال', 'Documenting the API with examples'),
      B('أبسط توثيق مفيد: لكل endpoint — الـ method والمسار، المدخلات (اسم، نوع، إجباري؟)، مثال طلب بـ curl، مثال رد ناجح، والأخطاء الممكنة. حطه في ملف `API.md` جنب الـ workflow في Git. ولما المشروع يكبر، ده بيتحوّل لـ OpenAPI.',
        'The simplest useful docs: for each endpoint — the method and path, the inputs (name, type, required?), a curl request example, a success response example, and the possible errors. Keep it in an `API.md` file next to the workflow in Git. When the project grows, this becomes OpenAPI.'),
      '## POST /webhook/orders\nBody: name (string, required), phone (string, required), items (array)\ncurl -X POST $URL/webhook/orders -H "Content-Type: application/json" -d \'{"name":"Sara","phone":"01012345678","items":[]}\'\n201 {"id": "1043"}   ·   422 invalid_phone')],
    practice: [B('اكتب `API.md` للـ API بتاعك (3 endpoints على الأقل) بالشكل ده.', 'Write `API.md` for your API (at least 3 endpoints) in this format.'),
      B('ادّي التوثيق لحد (أو AI) واطلب منه يستخدم الـ API من غير ما يسألك. سجّل الأسئلة اللي سألها.', 'Give the docs to someone (or an AI) and ask them to use the API without asking you. Note the questions they asked.')],
    words: [W('request example', 'مثال طلب كامل في التوثيق', 'a complete sample request in the docs', 'Every endpoint needs a request example.'),
      W('openapi', 'معيار لوصف الـ APIs في ملف', 'a standard for describing APIs in a file', 'Export an OpenAPI file for the client.')],
    quiz: [Q(B('أهم حاجة في توثيق endpoint:', 'The most useful part of endpoint docs:'), [B('مثال طلب ورد حقيقي', 'a real request and response example'), B('تاريخ الكتابة', 'the date written'), B('اسم المبرمج', 'the developer’s name')], 0, B('الأمثلة بتجاوب أغلب الأسئلة.', 'Examples answer most questions.'))] },
  { review: [B('⚡ مسارات :id والـ methods، وشكل موحّد للأخطاء.', '⚡ :id paths and methods, and one shared error format.'),
      B('⚡ توقيع HMAC، والـ idempotency، والتوثيق بأمثلة: طبّقهم على API الطلبات.', '⚡ HMAC signatures, idempotency, and docs with examples: apply them to the orders API.')] }
] };
