// n8n week 8 — the intensive hour (weeks 1–12 are 3 hours a day). Merged into the week by tools/build_weeks.js.
const B = (ar, en) => ({ ar, en });
const L = (h, p, ex) => ({ h, p, ex });
const W = (t, ar, en, ex) => ({ t, m: B(ar, en), ex });
const Q = (q, o, a, why) => ({ q, o, a, why });
module.exports = { days: [
  { learn: [L(B('Dot notation وحقول متداخلة', 'Dot notation and nested fields'),
      B('في Edit Fields لو كتبت اسم الحقل `customer.address.city` مع خيار **Support Dot Notation**، n8n بيعمل object متداخل بدل حقل اسمه فيه نقط. ده مهم لما الـ API اللي بعدك مستني شكل محدد. ومن غير الخيار ده، الاسم بيفضل نص واحد.',
        'In Edit Fields, if you name a field `customer.address.city` with **Support Dot Notation** on, n8n builds a nested object instead of a field whose name contains dots. This matters when the next API expects an exact shape. Without the option, the name stays one flat text.'),
      'Edit Fields (Support Dot Notation: on)\n  customer.name = {{ $json.name }}\n  customer.address.city = {{ $json.city }}\n→ { "customer": { "name": "Sara", "address": { "city": "Giza" } } }')],
    practice: [B('ابني الـ body اللي API بيطلبه (3 مستويات) من بيانات مسطّحة باستخدام dot notation.', 'Build the body an API expects (3 levels) from flat data using dot notation.'),
      B('قفّل الخيار وشوف الفرق في الخرج.', 'Turn the option off and see the difference in the output.')],
    words: [W('nested object', 'object جواه object', 'an object inside another object', 'The API expects a nested object for the address.'),
      W('flat', 'من غير مستويات متداخلة', 'with no nested levels', 'The sheet rows are flat.')],
    quiz: [Q(B('Support Dot Notation بيحوّل `a.b = 1` لـ:', 'Support Dot Notation turns `a.b = 1` into:'), [B('`{"a": {"b": 1}}`', '`{"a": {"b": 1}}`'), B('`{"a.b": 1}`', '`{"a.b": 1}`'), B('`[1]`', '`[1]`')], 0, B('object متداخل.', 'A nested object.'))] },
  { learn: [L(B('Merge بالـ SQL', 'Merge with SQL'),
      B('نود Merge فيه وضع **SQL Query**: المدخل الأول اسمه `input1` والتاني `input2`، وتكتب استعلام عادي: `SELECT … FROM input1 LEFT JOIN input2 ON …`. مفيد لما الدمج محتاج شروط أكتر من حقل واحد، أو تجميع (`GROUP BY`) في نفس الخطوة.',
        'The Merge node has an **SQL Query** mode: the first input is `input1` and the second `input2`, and you write a normal query: `SELECT … FROM input1 LEFT JOIN input2 ON …`. Useful when the join needs more than one field, or totals (`GROUP BY`) in the same step.'),
      'SELECT input1.id, input1.name, SUM(input2.total) AS spent\nFROM input1 LEFT JOIN input2 ON input1.id = input2.customer_id\nGROUP BY input1.id, input1.name')],
    practice: [B('ادمج عملاء وطلبات بالـ SQL واطلع لكل عميل عدد طلباته ومجموعها.', 'Merge customers and orders with SQL and get each customer’s order count and total.'),
      B('اعمل نفس النتيجة بـ Merge العادي + Summarize وقارن الطريقتين.', 'Get the same result with the normal Merge + Summarize and compare the two ways.')],
    words: [W('left join', 'دمج بيحتفظ بكل صفوف الجدول الأول', 'a join that keeps every row of the first table', 'A left join keeps customers with no orders.'),
      W('aggregate query', 'استعلام بيحسب مجاميع ومتوسطات', 'a query that computes totals and averages', 'An aggregate query gives the total per customer.')],
    quiz: [Q(B('عميل ملوش طلبات. أنهي دمج يحتفظ بيه؟', 'A customer has no orders. Which join keeps them?'), [B('LEFT JOIN', 'LEFT JOIN'), B('INNER JOIN', 'INNER JOIN'), B('ولا واحد', 'neither')], 0, B('INNER بيشيل اللي ملوش مقابل.', 'INNER drops rows with no match.'))] },
  { learn: [L(B('Destructuring وspread', 'Destructuring and spread'),
      B('`const { name, phone = \'-\' } = $json` بيطلّع حقول في متغيّرات مع قيمة افتراضية. و`{ ...$json, status: \'paid\' }` نسخة من العنصر مع تعديل حقل، من غير ما تغيّر الأصل. و`[...a, ...b]` بيدمج arrays. التلاتة دول هتشوفهم في كل Code node تقريبًا.',
        '`const { name, phone = \'-\' } = $json` pulls fields into variables with a default. `{ ...$json, status: \'paid\' }` is a copy of the item with one field changed, without changing the original. `[...a, ...b]` joins arrays. You will see these three in almost every Code node.'),
      "const { name, phone = '-', ...rest } = $json;\nreturn { json: { ...rest, contact: `${name} (${phone})`, status: 'paid' } };")],
    practice: [B('في Code node (Each Item): طلّع 3 حقول بـ destructuring وارجع object جديد بـ spread فيه حقل محسوب.', 'In a Code node (Each Item): take 3 fields with destructuring and return a new object with spread plus a computed field.'),
      B('اشرح لنفسك: ليه `{ ...$json }` أحسن من تعديل `$json` مباشرة؟', 'Explain to yourself: why is `{ ...$json }` better than changing `$json` directly?')],
    words: [W('unpack', 'تفك قيم من object في متغيّرات', 'to take values out of an object into variables', 'Unpack name and phone from $json.'),
      W('object spread', 'نسخ حقول object لـ object جديد بـ ...', 'copying an object’s fields into a new object with ...', 'Object spread keeps the original item unchanged.')],
    quiz: [Q(B('`{ ...$json, a: 1 }` بيعمل إيه؟', 'What does `{ ...$json, a: 1 }` do?'), [B('نسخة من العنصر و a = 1', 'a copy of the item with a = 1'), B('بيمسح العنصر', 'deletes the item'), B('خطأ', 'an error')], 0, B('الأصل مش بيتغيّر.', 'The original is unchanged.'))] },
  { learn: [L(B('Compare Datasets: إيه اللي اتغيّر؟', 'Compare Datasets: what changed?'),
      B('نود **Compare Datasets** بياخد قايمتين (مثلًا الشيت امبارح والـ API النهارده) ومفتاح (`id`)، ويطلّع 4 مخارج: موجود في A بس (اتمسح)، في B بس (جديد)، نفس الحاجة، ومختلف (اتعدّل). ده أساس أي مزامنة بين نظامين.',
        'The **Compare Datasets** node takes two lists (e.g. yesterday’s sheet and today’s API) and a key (`id`), and gives 4 outputs: in A only (deleted), in B only (new), same, and different (changed). This is the basis of any sync between two systems.'),
      'Compare Datasets (key: id)\n  In A only   → mark as deleted\n  In B only   → add new row\n  Same        → nothing\n  Different   → update the row')],
    practice: [B('اعمل قايمتين بـ 6 عناصر فيهم: 2 جداد، 1 اتمسح، 1 اتعدّل، و2 زي ما هم، وشوف كل مخرج.', 'Make two lists of 6 items with 2 new, 1 deleted, 1 changed and 2 unchanged, and look at each output.'),
      B('استخدم `Fields to Skip Comparing` عشان تتجاهل `updated_at`.', 'Use `Fields to Skip Comparing` to ignore `updated_at`.')],
    words: [W('dataset', 'مجموعة بيانات (قايمة سجلات)', 'a set of data (a list of records)', 'Compare the two datasets by id.'),
      W('sync', 'تخلّي نظامين فيهم نفس البيانات', 'to make two systems hold the same data', 'Sync the shop orders to the sheet every hour.')],
    quiz: [Q(B('عنصر موجود في B بس (الجديد) معناه:', 'An item only in B (the new list) means:'), [B('عنصر جديد يتضاف', 'a new item to add'), B('اتمسح', 'it was deleted'), B('مفيش تغيير', 'nothing changed')], 0, B('B هي النسخة الأحدث.', 'B is the newer copy.'))] },
  { learn: [L(B('جدول ربط القيم (lookup table)', 'A lookup table for values'),
      B('النظامين بيسمّوا نفس الحاجة بأسامي مختلفة: `paid` هنا و`PAID_OK` هناك، `Cairo` و`CAI`. متكتبش IF لكل قيمة؛ اعمل object للربط في Code node أو شيت صغير اسمه `mappings`، ولو القيمة مش موجودة طلّعها في تنبيه بدل ما تعدّي غلط.',
        'Two systems name the same thing differently: `paid` here and `PAID_OK` there, `Cairo` and `CAI`. Do not write an IF per value; build a mapping object in a Code node or a small `mappings` sheet, and if a value is missing, raise an alert instead of passing something wrong.'),
      "const STATUS = { paid: 'PAID_OK', pending: 'WAITING', refunded: 'RETURNED' };\nconst mapped = STATUS[$json.status];\nif (!mapped) throw new Error(`No mapping for status \"${$json.status}\"`);\nreturn { json: { ...$json, status: mapped } };")],
    practice: [B('اعمل شيت `mappings` (عمودين: from، to) واقراه مرة في أول الـ workflow واستخدمه لكل العناصر.', 'Make a `mappings` sheet (two columns: from, to), read it once at the start of the workflow and use it for every item.'),
      B('ابعت قيمة مش موجودة في الجدول واتأكد إن التنبيه وصل.', 'Send a value missing from the table and check the alert arrives.')],
    words: [W('lookup table', 'جدول بيربط قيمة بقيمة تانية', 'a table that links one value to another', 'Use a lookup table for city codes.'),
      W('unmapped', 'قيمة ملهاش مقابل في جدول الربط', 'a value with no match in the mapping table', 'Alert on any unmapped status.')],
    quiz: [Q(B('قيمة ملهاش مقابل في جدول الربط. أحسن تصرف:', 'A value has no match in the mapping. Best action:'), [B('تنبيه ووقف العنصر ده', 'alert and stop that item'), B('تعدّيها زي ما هي', 'pass it as it is'), B('تحط أي قيمة', 'put any value')], 0, B('الغلط الصامت أخطر.', 'Silent mistakes are worse.'))] },
  { review: [B('⚡ dot notation، وMerge بالـ SQL، وdestructuring وspread.', '⚡ Dot notation, Merge with SQL, and destructuring and spread.'),
      B('⚡ Compare Datasets للمزامنة، وجداول الربط مع تنبيه للقيم الناقصة: استخدمهم في مشروع الشهر.', '⚡ Compare Datasets for syncing, and mapping tables with alerts for missing values: use them in the month project.')] }
] };
