// n8n week 9 — the intensive hour (weeks 1–12 are 3 hours a day). Merged into the week by tools/build_weeks.js.
const B = (ar, en) => ({ ar, en });
const L = (h, p, ex) => ({ h, p, ex });
const W = (t, ar, en, ex) => ({ t, m: B(ar, en), ex });
const Q = (q, o, a, why) => ({ q, o, a, why });
module.exports = { days: [
  { learn: [L(B('شكل الرجوع الصح', 'The right return shape'),
      B('في وضع All Items لازم ترجع **array** كل عنصر فيه `{ json: {...} }` (واختياري `binary`). أخطاء شائعة: ترجع object واحد، أو array من غير `json`، أو تنسى `return` خالص. ولو عايز ترجع عناصر صفر، ارجع `[]` — الـ workflow هيقف عند النود ده بهدوء.',
        'In All Items mode you must return an **array** where each item is `{ json: {...} }` (and optionally `binary`). Common mistakes: returning one object, an array without `json`, or no `return` at all. To return zero items, return `[]` — the workflow quietly stops at that node.'),
      "// ✓\nreturn $input.all().map(i => ({ json: { id: i.json.id, total: i.json.qty * i.json.price } }));\n// ✓ nothing to do\nif (!$input.all().length) return [];")],
    practice: [B('اكتب Code node بيرجع عنصر لكل منتج سعره فوق 100، وجرّبه على قايمة مفيهاش ولا واحد.', 'Write a Code node that returns one item per product priced above 100, and test it on a list with none.'),
      B('ارجع شكل غلط كل مرة (object، array من غير json) واكتب رسالة الخطأ.', 'Return a wrong shape each time (an object, an array without json) and note the error message.')],
    words: [W('return shape', 'شكل البيانات اللي الكود لازم يرجّعها', 'the form of data the code must return', 'Check the return shape: an array of { json }.'),
      W('empty array', 'قايمة مفيهاش عناصر []', 'a list with no items: []', 'Return an empty array to stop quietly.')],
    quiz: [Q(B('في All Items ترجع:', 'In All Items mode you return:'), [B('array من `{ json }`', 'an array of `{ json }`'), B('object واحد', 'one object'), B('نص', 'a string')], 0, B('n8n بيشتغل بقوايم عناصر.', 'n8n works with lists of items.'))] },
  { learn: [L(B('flatMap وفك القوايم المتداخلة', 'flatMap and flattening nested lists'),
      B('طلب فيه `lines` (منتجات). عايز عنصر لكل منتج مع رقم الطلب؟ `flatMap` بيعمل map ويفرد النتيجة في قايمة واحدة. ده بديل لنود Split Out لما محتاج تضيف حقول من الأب.',
        'An order has `lines` (products). Want one item per product with the order number? `flatMap` maps and flattens the result into one list. It replaces the Split Out node when you need fields from the parent.'),
      "return $input.all().flatMap(o =>\n  o.json.lines.map(l => ({ json: { order: o.json.id, sku: l.sku, qty: l.qty } }))\n);")],
    practice: [B('من 3 طلبات فيهم 7 منتجات، طلّع 7 عناصر فيها رقم الطلب والمنتج.', 'From 3 orders holding 7 products, output 7 items with the order number and product.'),
      B('اعمل نفس الحاجة بـ Split Out وقارن: إمتى تختار ده وإمتى ده؟', 'Do the same with Split Out and compare: when would you choose each?')],
    words: [W('flatmap', 'map وبعدين يفرد القوايم في قايمة واحدة', 'map, then flatten the lists into one list', 'flatMap gives one item per order line.'),
      W('order line', 'سطر في الطلب: منتج وكمية', 'one row of an order: a product and quantity', 'Each order line has a sku and qty.')],
    quiz: [Q(B('`[[1,2],[3]].flat()` بتطلع:', '`[[1,2],[3]].flat()` gives:'), [B('`[1, 2, 3]`', '`[1, 2, 3]`'), B('`[[1,2],[3]]`', '`[[1,2],[3]]`'), B('`6`', '`6`')], 0, B('بتفرد مستوى واحد.', 'It flattens one level.'))] },
  { learn: [L(B('طلبات HTTP من الكود بأمان', 'HTTP requests from code, safely'),
      B('`this.helpers.httpRequest({ method, url, body, json: true })` بيعمل طلب من Code node. حط الطلبات في `try/catch`، وحدّد مهلة (`timeout`)، ومتبعتش 500 طلب مرة واحدة: قسّمهم دفعات. ولو الشغل كله طلبات، غالبًا نود HTTP Request أوضح وأسهل في التتبع.',
        '`this.helpers.httpRequest({ method, url, body, json: true })` makes a request from a Code node. Wrap requests in `try/catch`, set a `timeout`, and do not send 500 requests at once: split them into batches. If the work is all requests, the HTTP Request node is usually clearer and easier to trace.'),
      "const out = [];\nfor (const item of $input.all()) {\n  try {\n    const r = await this.helpers.httpRequest({ url: `https://api.example.com/users/${item.json.id}`, json: true, timeout: 10000 });\n    out.push({ json: { id: item.json.id, ok: true, name: r.name } });\n  } catch (e) { out.push({ json: { id: item.json.id, ok: false, error: e.message } }); }\n}\nreturn out;")],
    practice: [B('اطلب 5 مستخدمين من `jsonplaceholder` بالكود، وخلّي واحد فيهم id غلط وشوف إن الباقي كمّل.', 'Fetch 5 users from `jsonplaceholder` in code, make one id wrong, and check the rest still finish.'),
      B('اكتب سطرين: إمتى تعمل الطلب في Code ومتى في HTTP Request؟', 'Write two lines: when to make the request in Code and when in HTTP Request?')],
    words: [W('await', 'استنى النتيجة قبل ما تكمّل', 'wait for the result before continuing', 'Use await before the request.'),
      W('mixed results', 'بعض العناصر نجحت وبعضها فشل', 'some items succeeded and some failed', 'Return mixed results with an ok field.')],
    quiz: [Q(B('ليه `try/catch` حوالين كل طلب؟', 'Why `try/catch` around each request?'), [B('فشل واحد ميوقفش الكل', 'one failure does not stop all'), B('عشان يبقى أسرع', 'to be faster'), B('n8n بيطلبه', 'n8n requires it')], 0, B('تسجّل الفشل وتكمّل.', 'Record the failure and continue.'))] },
  { learn: [L(B('قراءة ملف CSV في الكود', 'Reading a CSV file in code'),
      B('الملف بيوصل كـ binary. `await this.helpers.getBinaryDataBuffer(0, \'data\')` بيجيب محتواه، و`.toString(\'utf8\')` بيحوّله نص. لملفات بسيطة تقسم السطور والأعمدة؛ للملفات الحقيقية (فواصل جوه تنصيص) استخدم نود **Extract From File** أسلم.',
        'The file arrives as binary. `await this.helpers.getBinaryDataBuffer(0, \'data\')` gets its content, and `.toString(\'utf8\')` turns it into text. For simple files split the lines and columns; for real files (commas inside quotes) the **Extract From File** node is safer.'),
      "const buf = await this.helpers.getBinaryDataBuffer(0, 'data');\nconst [head, ...rows] = buf.toString('utf8').trim().split(/\\r?\\n/);\nconst cols = head.split(',');\nreturn rows.map(r => ({ json: Object.fromEntries(r.split(',').map((v, i) => [cols[i], v])) }));")],
    practice: [B('ارفع CSV بسيط وحوّله لعناصر بالكود، وبعدين بـ Extract From File، وقارن.', 'Upload a simple CSV and turn it into items with code, then with Extract From File, and compare.'),
      B('ضيف سطر فيه فاصلة جوه تنصيص (`"Giza, Egypt"`) وشوف مين فيهم اتكسر.', 'Add a line with a comma inside quotes (`"Giza, Egypt"`) and see which one breaks.')],
    words: [W('raw bytes', 'محتوى الملف كأرقام قبل ما يتحوّل نص', 'the file content as numbers before it becomes text', 'Read the raw bytes, then decode them as UTF-8.'),
      W('delimiter', 'الحرف اللي بيفصل الأعمدة (, أو ;)', 'the character that separates columns (, or ;)', 'This CSV uses a semicolon delimiter.')],
    quiz: [Q(B('CSV فيه فواصل جوه قيم بين تنصيص. الأسلم:', 'A CSV has commas inside quoted values. Safest:'), [B('Extract From File', 'Extract From File'), B('`split(",")`', '`split(",")`'), B('تمسح الفواصل', 'delete the commas')], 0, B('split بيقسم الفاصلة اللي جوه القيمة.', 'split breaks the comma inside the value.'))] },
  { learn: [L(B('كود سهل تقراه بعد شهر', 'Code you can read in a month'),
      B('قواعد بسيطة: أسماء بتوصف (`paidOrders` مش `arr2`)، ثوابت فوق (`const VAT = 0.14`)، دالة صغيرة لكل خطوة، تعليق بيقول **ليه** مش إيه، وCode node بيعمل حاجة واحدة اسمها مكتوب في اسم النود. لو الكود عدّى 40 سطر، فكّر تقسّمه.',
        'Simple rules: descriptive names (`paidOrders`, not `arr2`), constants at the top (`const VAT = 0.14`), a small function per step, comments that say **why**, not what, and a Code node that does one thing named in the node’s title. If the code passes 40 lines, consider splitting it.'),
      "const VAT = 0.14; // Egypt VAT, change here only\nconst isPaid = o => o.status === 'paid';\nconst withVat = o => ({ ...o, total: +(o.subtotal * (1 + VAT)).toFixed(2) });\nreturn $input.all().map(i => i.json).filter(isPaid).map(withVat).map(json => ({ json }));")],
    practice: [B('خُد أطول Code node عندك ونضّفه بالقواعد دي من غير ما تغيّر نتيجته (قارن الخرج قبل وبعد).', 'Take your longest Code node and clean it with these rules without changing its result (compare output before and after).'),
      B('اطلب من AI مراجعة الكود ببرومبت «code review» من صفحة البرومبتات.', 'Ask an AI to review the code with the «code review» prompt from the prompts page.')],
    words: [W('readable', 'سهل تقراه وتفهمه', 'easy to read and understand', 'Short functions make code readable.'),
      W('constant', 'قيمة ثابتة باسم واضح', 'a fixed value with a clear name', 'Put the VAT rate in a constant.')],
    quiz: [Q(B('أحسن تعليق:', 'The best comment:'), [B('بيقول ليه الكود كده', 'says why the code is this way'), B('بيعيد اللي الكود بيقوله', 'repeats what the code says'), B('مفيش تعليقات خالص', 'no comments at all')], 0, B('الكود بيقول إيه، التعليق بيقول ليه.', 'Code says what; comments say why.'))] },
  { review: [B('⚡ شكل الرجوع، وflatMap، وطلبات HTTP من الكود بـ try/catch.', '⚡ The return shape, flatMap, and HTTP requests in code with try/catch.'),
      B('⚡ قراءة الملفات من binary، وكود نضيف بأسماء وثوابت ودوال صغيرة.', '⚡ Reading files from binary, and clean code with names, constants and small functions.')] }
] };
