// n8n week 10 — the intensive hour (weeks 1–12 are 3 hours a day). Merged into the week by tools/build_weeks.js.
const B = (ar, en) => ({ ar, en });
const L = (h, p, ex) => ({ h, p, ex });
const W = (t, ar, en, ex) => ({ t, m: B(ar, en), ex });
const Q = (q, o, a, why) => ({ q, o, a, why });
module.exports = { days: [
  { learn: [L(B('الطمع والكسل في الـ regex', 'Greedy and lazy in regex'),
      B('`.*` **طمّاع**: بياخد أكبر جزء ممكن. في `<b>1</b><b>2</b>` الـ regex `<b>.*</b>` بياخد السطر كله. `.*?` **كسلان**: بياخد أقل جزء، فيطلع `<b>1</b>` بس. لما تستخرج حاجة بين علامتين، غالبًا عايز الكسلان.',
        '`.*` is **greedy**: it takes the longest possible match. In `<b>1</b><b>2</b>` the regex `<b>.*</b>` takes the whole line. `.*?` is **lazy**: it takes the shortest, giving just `<b>1</b>`. When extracting something between two markers, you usually want lazy.'),
      "'<b>1</b><b>2</b>'.match(/<b>.*<\\/b>/)[0]   // '<b>1</b><b>2</b>'\n'<b>1</b><b>2</b>'.match(/<b>.*?<\\/b>/)[0]  // '<b>1</b>'")],
    practice: [B('استخرج كل الكلام اللي بين `[` و`]` في نص فيه 3 أقواس، بالطمّاع وبالكسلان، وقارن.', 'Extract everything between `[` and `]` in a text with 3 brackets, with greedy and lazy, and compare.'),
      B('جرّب على regex101 وشوف خطوات المطابقة.', 'Try it on regex101 and watch the matching steps.')],
    words: [W('greedy', 'بياخد أطول مطابقة ممكنة', 'taking the longest possible match', '.* is greedy by default.'),
      W('lazy quantifier', 'علامة ? بعد * أو + عشان ياخد أقصر مطابقة', 'a ? after * or + to take the shortest match', 'Use a lazy quantifier between tags.')],
    quiz: [Q(B('عشان تاخد أول `<b>…</b>` بس:', 'To take only the first `<b>…</b>`:'), [B('`<b>.*?</b>`', '`<b>.*?</b>`'), B('`<b>.*</b>`', '`<b>.*</b>`'), B('`<b>+</b>`', '`<b>+</b>`')], 0, B('الكسلان بيقف عند أول </b>.', 'Lazy stops at the first </b>.'))] },
  { learn: [L(B('Lookahead وlookbehind', 'Lookahead and lookbehind'),
      B('بيشترطوا حاجة **جنب** المطابقة من غير ما ياخدوها. `\\d+(?= EGP)` رقم وراه « EGP». `(?<=#)\\w+` كلمة قبلها #. مفيدين لما الرقم اللي عايزه متعرّف بالكلمة اللي جنبه.',
        'They require something **next to** the match without including it. `\\d+(?= EGP)` is a number followed by « EGP». `(?<=#)\\w+` is a word preceded by #. Useful when the number you want is identified by the word beside it.'),
      "'Total: 450 EGP, tax 63 EGP'.match(/\\d+(?= EGP)/g)   // ['450', '63']\n'tags: #sale #new'.match(/(?<=#)\\w+/g)              // ['sale', 'new']")],
    practice: [B('من رسالة فيها أسعار بالجنيه والدولار، طلّع الأرقام اللي بالجنيه بس.', 'From a message with prices in pounds and dollars, extract only the pound amounts.'),
      B('طلّع الـ hashtags من غير علامة #.', 'Extract hashtags without the # sign.')],
    words: [W('lookahead', 'شرط إن حاجة تيجي بعد المطابقة', 'a condition that something follows the match', 'A lookahead checks for " EGP" after the number.'),
      W('lookbehind', 'شرط إن حاجة تيجي قبل المطابقة', 'a condition that something comes before the match', 'Use a lookbehind for the # sign.')],
    quiz: [Q(B('`\\d+(?=%)` في `50% off` بتطلع:', '`\\d+(?=%)` on `50% off` gives:'), [B('`50`', '`50`'), B('`50%`', '`50%`'), B('`%`', '`%`')], 0, B('الـ % شرط ومش جزء من النتيجة.', 'The % is a condition, not part of the result.'))] },
  { learn: [L(B('تنضيف النص العربي', 'Cleaning Arabic text'),
      B('عشان البحث والمقارنة يشتغلوا: شيل التشكيل `[\\u064B-\\u0652]`، وحّد الألف `[إأآ]` → `ا`، والتاء المربوطة `ة` → `ه` لو محتاج، والـ `ى` → `ي`، وحوّل الأرقام العربية `٠-٩` لإنجليزي. خلّي النسخة الأصلية للعرض، والنسخة المنضّفة للمقارنة بس.',
        'So search and comparison work: remove diacritics `[\\u064B-\\u0652]`, unify alef `[إأآ]` → `ا`, taa marbuta `ة` → `ه` if needed, `ى` → `ي`, and turn Arabic digits `٠-٩` into Western ones. Keep the original for display and the cleaned copy for comparing only.'),
      "const clean = s => s\n  .replace(/[\\u064B-\\u0652]/g, '')\n  .replace(/[إأآ]/g, 'ا').replace(/ى/g, 'ي')\n  .replace(/[٠-٩]/g, d => '٠١٢٣٤٥٦٧٨٩'.indexOf(d));\nclean('أحمد ٠١٠')  // 'احمد 010'")],
    practice: [B('اعمل دالة `clean` وجرّبها على 5 كتابات مختلفة لنفس الاسم واتأكد إنهم بقوا زي بعض.', 'Write a `clean` function and test it on 5 spellings of the same name; check they become identical.'),
      B('استخدمها قبل Remove Duplicates على قايمة عملاء عربي.', 'Use it before Remove Duplicates on an Arabic customer list.')],
    words: [W('diacritics', 'علامات التشكيل فوق وتحت الحروف', 'marks above or below letters', 'Remove diacritics before comparing names.'),
      W('arabic block', 'مدى أكواد الحروف العربية في Unicode', 'the range of Arabic letter codes in Unicode', 'The Arabic block starts at U+0600.')],
    quiz: [Q(B('ليه تحتفظ بالنص الأصلي؟', 'Why keep the original text?'), [B('للعرض؛ المنضّف للمقارنة بس', 'for display; the clean copy is for comparing'), B('مش محتاجه', 'you do not need it'), B('عشان الحجم', 'for size')], 0, B('التنضيف بيغيّر شكل الاسم.', 'Cleaning changes how the name looks.'))] },
  { learn: [L(B('أرقام الموبايل المصرية', 'Egyptian mobile numbers'),
      B('الرقم ممكن ييجي `01012345678` أو `+201012345678` أو `00201012345678` أو بمسافات وشرط. نضّف الأول (شيل أي حاجة مش رقم)، وبعدين اتحقق: `^(?:\\+?20|0)?(1[0125]\\d{8})$`، وارجعه بصيغة موحدة `+20…` عشان واتساب والـ APIs.',
        'A number may arrive as `01012345678`, `+201012345678`, `00201012345678` or with spaces and dashes. Clean first (remove anything that is not a digit or +), then check: `^(?:\\+?20|0)?(1[0125]\\d{8})$`, and return one format `+20…` for WhatsApp and APIs.'),
      "const toE164 = raw => {\n  const s = String(raw).replace(/[^\\d+]/g, '').replace(/^00/, '+');\n  const m = s.match(/^(?:\\+?20|0)?(1[0125]\\d{8})$/);\n  return m ? '+20' + m[1] : null;\n};\ntoE164('010-1234 5678')  // '+201012345678'")],
    practice: [B('جرّب الدالة على 8 أشكال (منهم 2 غلط) واتأكد إن الغلط بيرجع `null`.', 'Test the function on 8 forms (2 of them wrong) and check the wrong ones return `null`.'),
      B('حطها في workflow: العناصر اللي رقمها `null` تروح لفرع «راجع الرقم».', 'Put it in a workflow: items whose number is `null` go to a «check the number» branch.')],
    words: [W('e.164', 'الصيغة الدولية للأرقام زي +201012345678', 'the international number format like +201012345678', 'Store phone numbers in E.164.'),
      W('country code', 'كود الدولة في أول الرقم (مصر 20)', 'the country prefix of a number (Egypt is 20)', 'Add the country code before sending.')],
    quiz: [Q(B('ليه تحفظ كل الأرقام بصيغة واحدة؟', 'Why store every number in one format?'), [B('عشان المقارنة والإرسال يشتغلوا', 'so comparing and sending work'), B('عشان تبقى أطول', 'to make them longer'), B('مش مهم', 'it does not matter')], 0, B('`010…` و`+2010…` نفس الرقم.', '`010…` and `+2010…` are the same number.'))] },
  { learn: [L(B('الأدوات الجاهزة قبل الـ regex', 'Ready tools before regex'),
      B('مش كل حاجة محتاجة regex. n8n فيه نود **Extract From File** و**HTML** (يستخرج من صفحة بـ CSS selector)، ودوال زي `.extractEmail()` و`.extractUrl()` و`.extractDomain()`. ولو النص عشوائي جدًا (إيميلات عملاء)، نود AI مع Structured Output Parser أدق من regex.',
        'Not everything needs regex. n8n has **Extract From File** and **HTML** nodes (extract from a page with a CSS selector), and helpers like `.extractEmail()`, `.extractUrl()` and `.extractDomain()`. If the text is very free-form (customer emails), an AI node with a Structured Output Parser is more accurate than regex.'),
      '{{ $json.text.extractEmail() }}\n{{ $json.text.extractUrl() }}\nHTML node → Extract HTML Content → CSS selector: .price')],
    practice: [B('من صفحة منتج، طلّع الاسم والسعر بنود HTML وCSS selector.', 'From a product page, extract the name and price with the HTML node and a CSS selector.'),
      B('اكتب جدول: نوع النص ← الأداة الأنسب (regex، دالة جاهزة، HTML، AI).', 'Write a table: kind of text → the best tool (regex, a ready helper, HTML, AI).')],
    words: [W('scrape', 'تطلّع بيانات من صفحة ويب آليًا', 'to pull data out of a web page automatically', 'Scrape only pages you are allowed to.'),
      W('free-form', 'نص من غير شكل ثابت', 'text with no fixed format', 'Free-form emails are hard for regex.')],
    quiz: [Q(B('عايز السعر من صفحة HTML:', 'You need the price from an HTML page:'), [B('نود HTML بـ CSS selector', 'the HTML node with a CSS selector'), B('regex على الصفحة كلها', 'regex on the whole page'), B('AI دايمًا', 'always AI')], 0, B('الصفحة ليها بنية، استخدمها.', 'The page has structure; use it.'))] },
  { review: [B('⚡ الطمّاع والكسلان، وlookahead/lookbehind، وتنضيف العربي.', '⚡ Greedy and lazy, lookahead/lookbehind, and cleaning Arabic.'),
      B('⚡ أرقام الموبايل بصيغة +20، والأدوات الجاهزة قبل الـ regex: اعمل workflow ينضّف قايمة عملاء.', '⚡ Mobile numbers in +20 form, and ready tools before regex: build a workflow that cleans a customer list.')] }
] };
