// n8n week 11 — the intensive hour (weeks 1–12 are 3 hours a day). Merged into the week by tools/build_weeks.js.
const B = (ar, en) => ({ ar, en });
const L = (h, p, ex) => ({ h, p, ex });
const W = (t, ar, en, ex) => ({ t, m: B(ar, en), ex });
const Q = (q, o, a, why) => ({ q, o, a, why });
module.exports = { days: [
  { learn: [L(B('Switch بقواعد ولا بـ expression', 'Switch by rules or by expression'),
      B('Switch ليه وضعين: **Rules** (شروط لكل مخرج، تقدر تخلّي العنصر يروح لأكتر من مخرج لو فعّلت «Send data to all matching outputs») و**Expression** (expression بيرجّع رقم المخرج على طول، زي `{{ ["low","normal","high"].indexOf($json.priority) }}`). الـ Expression أقصر لما القيم كتير ومرتبة.',
        'Switch has two modes: **Rules** (conditions per output; an item can go to several outputs if you enable «Send data to all matching outputs») and **Expression** (an expression that returns the output number directly, like `{{ ["low","normal","high"].indexOf($json.priority) }}`). Expression is shorter when values are many and ordered.'),
      'Mode: Expression   Number of outputs: 3\nOutput index: {{ ["low","normal","high"].indexOf($json.priority) }}\n"high" → output 2')],
    practice: [B('اعمل نفس التوزيع على 3 أولويات بالوضعين، وجرّب قيمة مش في القايمة في كل واحد.', 'Route 3 priorities with both modes, and test a value not in the list in each.'),
      B('فعّل «all matching outputs» واعمل عنصر يروح لمخرجين (مثلًا «عاجل» و«VIP»).', 'Enable «all matching outputs» and make an item go to two outputs (e.g. «urgent» and «VIP»).')],
    words: [W('output index', 'رقم المخرج اللي العنصر هيروح له', 'the number of the output an item goes to', 'The expression returns the output index.'),
      W('matching', 'مطابق للشرط', 'meeting the condition', 'Send the item to every matching output.')],
    quiz: [Q(B('`indexOf` رجّع `-1` في وضع Expression. يعني:', '`indexOf` returned `-1` in Expression mode. It means:'), [B('القيمة مش في القايمة؛ لازم تتعامل معاها', 'the value is not in the list; handle it'), B('أول مخرج', 'the first output'), B('كله تمام', 'all is well')], 0, B('اعمل fallback للقيم غير المتوقعة.', 'Add a fallback for unexpected values.'))] },
  { learn: [L(B('الفروع اللي مش بتشتغل', 'Branches that do not run'),
      B('لو IF طلّع صفر عناصر في فرع، النودز بعده **مش بتشتغل خالص** — ونود بعد Merge ممكن يستنى للأبد. لو محتاج الفرع يكمّل حتى من غير بيانات، فعّل **Always Output Data** في الإعدادات (بيطلّع عنصر فاضي)، واتعامل مع العنصر الفاضي ده بعد كده.',
        'If an IF outputs zero items on a branch, the nodes after it **do not run at all** — and a node after a Merge may wait forever. If the branch must continue even without data, enable **Always Output Data** in settings (it outputs one empty item), and handle that empty item later.'),
      'IF (has new orders?)\n  true  → 0 items → Send report  ✗ never runs\nFix: Always Output Data on the IF → 1 empty item\n  → Send report: "No new orders today"')],
    practice: [B('اعمل تقرير يومي بيتبعت حتى لو مفيش طلبات جديدة، ويقول «مفيش طلبات النهارده».', 'Build a daily report that is sent even with no new orders, saying «no orders today».'),
      B('شوف في Executions الفرق بين نود اتنفّذ بصفر عناصر ونود متنفّذش.', 'In Executions, see the difference between a node that ran with zero items and one that did not run.')],
    words: [W('empty item', 'عنصر من غير بيانات', 'an item with no data', 'Always Output Data sends one empty item.'),
      W('skipped node', 'نود متنفّذش لأن مفيش عناصر وصلته', 'a node that did not run because no items reached it', 'The report node was a skipped node.')],
    quiz: [Q(B('فرع IF طلّع 0 عناصر. النود اللي بعده:', 'An IF branch output 0 items. The next node:'), [B('مش بيشتغل', 'does not run'), B('بيشتغل مرة', 'runs once'), B('بيطلّع خطأ', 'throws an error')], 0, B('إلا لو فعّلت Always Output Data.', 'Unless Always Output Data is on.'))] },
  { learn: [L(B('Loop Over Items مع شرط خروج', 'Loop Over Items with an exit condition'),
      B('أحيانًا محتاج تلف لحد ما حاجة تحصل: مثلًا API بيجهّز تقرير، وتسأل كل 30 ثانية «خلص؟». الشكل: HTTP (اسأل) ← IF (خلص؟) ← لو لأ: Wait 30 ثانية وارجع للـ HTTP. ولازم **حد أقصى** للمحاولات (عدّاد) عشان ميلفّش للأبد.',
        'Sometimes you must loop until something happens: e.g. an API prepares a report and you ask every 30 seconds «done?». The shape: HTTP (ask) → IF (done?) → if not: Wait 30 seconds and go back to the HTTP. You need a **maximum** number of tries (a counter) so it never loops forever.'),
      'Set tries = 0 → HTTP: get report status → IF status = "ready"\n  yes → download\n  no  → IF tries < 20 → Wait 30 s → tries + 1 → back to HTTP\n        else → alert "report not ready after 10 min"')],
    practice: [B('اعمل loop بيسأل `https://httpbin.org/anything` 5 مرات بعدّاد ويقف.', 'Build a loop that calls `https://httpbin.org/anything` 5 times with a counter and stops.'),
      B('اكتب: إيه اللي يحصل لو نسيت العدّاد؟', 'Write: what happens if you forget the counter?')],
    words: [W('loop guard', 'حد بيمنع الـ loop إنه يلف للأبد', 'a limit that stops a loop from running forever', 'A counter is a simple loop guard.'),
      W('counter', 'رقم بيزيد كل لفة', 'a number that grows each time round', 'Stop when the counter reaches 20.')],
    quiz: [Q(B('ليه حد أقصى للمحاولات؟', 'Why a maximum number of tries?'), [B('عشان الـ loop ميلفّش للأبد', 'so the loop never runs forever'), B('عشان أسرع', 'to be faster'), B('n8n بيطلبه', 'n8n requires it')], 0, B('والتنبيه لما يوصل للحد.', 'And alert when it hits the limit.'))] },
  { learn: [L(B('Wait لحد ما حد يرد', 'Wait until someone answers'),
      B('نود **Wait** فيه وضع «On Webhook Call»: الـ workflow بيقف ويطلّع رابط مخصوص `$execution.resumeUrl`. تبعت الرابط ده في إيميل أو تليجرام («موافق؟»)، ولما الشخص يدوس، الـ workflow يكمّل من مكانه. حط مهلة (Limit Wait Time) عشان لو محدش رد.',
        'The **Wait** node has an «On Webhook Call» mode: the workflow pauses and gets a special link `$execution.resumeUrl`. Send that link by email or Telegram («approve?»), and when the person clicks, the workflow continues where it stopped. Set a time limit (Limit Wait Time) in case nobody answers.'),
      'Telegram: "Approve refund 350 EGP? {{ $execution.resumeUrl }}?ok=1"\n→ Wait (On Webhook Call, limit: 24 h)\n→ IF {{ $json.query.ok === "1" }} → refund · else → notify')],
    practice: [B('اعمل موافقة بسيطة: رسالة فيها رابطين (موافق / رافض) والـ workflow يكمّل حسب الاختيار.', 'Build a simple approval: a message with two links (approve / reject) and the workflow continues based on the choice.'),
      B('جرّب المهلة: خليها دقيقتين ومتدوسش، وشوف يحصل إيه.', 'Test the limit: set it to two minutes, do not click, and see what happens.')],
    words: [W('resume url', 'رابط بيكمّل workflow واقف', 'a link that continues a paused workflow', 'Send the resume URL to the manager.'),
      W('approval', 'موافقة إنسان قبل خطوة مهمة', 'a person’s OK before an important step', 'Refunds need an approval first.')],
    quiz: [Q(B('Wait بوضع On Webhook Call بيكمّل لما:', 'Wait in On Webhook Call mode continues when:'), [B('حد يفتح الـ resume URL', 'someone opens the resume URL'), B('يعدي ثانية', 'a second passes'), B('تقفل n8n', 'you close n8n')], 0, B('أو لما المهلة تخلص.', 'Or when the time limit ends.'))] },
  { learn: [L(B('فروع متوازية وترتيبها', 'Parallel branches and their order'),
      B('لما نود يطلّع لفرعين، n8n (الإصدار الحالي) بيشغّل فرع كامل لآخره وبعدين التاني، بالترتيب **من فوق لتحت** في الرسمة. ده مهم لو فرع بيعتمد على نتيجة التاني. متعتمدش على الترتيب في منطق مهم؛ لو لازم ترتيب، اربطهم ورا بعض أو استخدم Merge (Wait for both).',
        'When a node feeds two branches, n8n (current version) runs one whole branch to its end, then the other, in **top-to-bottom** order on the canvas. This matters if one branch depends on the other’s result. Do not rely on order for important logic; if order matters, chain them or use Merge (wait for both).'),
      'Get order ─┬─ (top)    Save to Sheet  → runs first\n            └─ (bottom) Email customer → runs second\nIf the email needs the row id: chain Save → Email instead')],
    practice: [B('اعمل فرعين كل واحد فيه Wait مختلف وشوف ترتيب التنفيذ في Executions. حرّك فرع لفوق وشوف اتغيّر؟', 'Build two branches with different Waits and check the run order in Executions. Move one branch up — does it change?'),
      B('حوّل workflow فيه فرعين معتمدين على بعض لسلسلة.', 'Turn a workflow with two dependent branches into a chain.')],
    words: [W('branch order', 'ترتيب تشغيل الفروع', 'the order in which branches run', 'Do not depend on branch order.'),
      W('parallel branches', 'فروع طالعة من نفس النود', 'branches that start from the same node', 'Use Merge to join parallel branches.')],
    quiz: [Q(B('فرع B محتاج نتيجة فرع A. الأسلم:', 'Branch B needs branch A’s result. Safest:'), [B('تربطهم ورا بعض', 'chain them'), B('تعتمد على ترتيب الرسمة', 'rely on canvas order'), B('تزوّد Wait', 'add a Wait')], 0, B('الاعتماد صريح بدل ضمني.', 'Make the dependency explicit.'))] },
  { review: [B('⚡ Switch بالـ expression، والفروع الفاضية وAlways Output Data.', '⚡ Switch by expression, empty branches and Always Output Data.'),
      B('⚡ loop بشرط خروج وعدّاد، وموافقة بـ resume URL، وترتيب الفروع: ابني workflow موافقة على المرتجعات.', '⚡ A loop with an exit condition and counter, approval with a resume URL, and branch order: build a refund approval workflow.')] }
] };
