// n8n week 12 — the intensive hour (weeks 1–12 are 3 hours a day). Merged into the week by tools/build_weeks.js.
const B = (ar, en) => ({ ar, en });
const L = (h, p, ex) => ({ h, p, ex });
const W = (t, ar, en, ex) => ({ t, m: B(ar, en), ex });
const Q = (q, o, a, why) => ({ q, o, a, why });
module.exports = { days: [
  { learn: [L(B('أخطاء متوقعة ولا مفاجئة؟', 'Expected or unexpected errors?'),
      B('فرّق بين نوعين: **متوقّع** (رقم موبايل غلط، عميل مش موجود) — ده مش عطل، اتعامل معاه في فرع عادي وابعت رسالة مفهومة. و**مفاجئ** (الـ API واقع، credential انتهى) — ده عطل، خلّيه يفشل بصوت عالي ويوصل لـ error workflow. الغلطة الشائعة: تخلّي كل حاجة «Continue» فالأعطال الحقيقية تعدّي ساكتة.',
        'Separate two kinds: **expected** (a wrong mobile number, a missing customer) — not a failure; handle it on a normal branch with a clear message. **Unexpected** (the API is down, a credential expired) — a failure; let it fail loudly and reach the error workflow. The common mistake: setting everything to «Continue» so real failures pass silently.'),
      'expected   → IF invalid phone → reply "please check the number"\nunexpected → HTTP 503 after retries → fail → Error Trigger → alert')],
    practice: [B('راجع workflow عندك: علّم كل نود: الأخطاء المتوقعة فيه إيه، والمفاجئة إيه، وبيتعامل معاهم إزاي.', 'Review one of your workflows: for each node mark its expected and unexpected errors, and how they are handled.'),
      B('شيل أي «Continue» مالوش لازمة وحط فرع واضح بداله.', 'Remove any needless «Continue» and add a clear branch instead.')],
    words: [W('expected error', 'خطأ عارف إنه هيحصل وليه حل عادي', 'an error you know will happen and has a normal fix', 'A wrong phone number is an expected error.'),
      W('fail loudly', 'تفشل بشكل واضح يوصل تنبيه', 'to fail in a visible way that raises an alert', 'Let credential errors fail loudly.')],
    quiz: [Q(B('الـ credential انتهى. التصرف الصح:', 'A credential expired. The right handling:'), [B('يفشل ويوصل تنبيه', 'fail and send an alert'), B('Continue ساكت', 'continue silently'), B('يعيد للأبد', 'retry forever')], 0, B('ده عطل محتاج إنسان.', 'This failure needs a person.'))] },
  { learn: [L(B('تنبيه مفيد من الـ Error Trigger', 'A useful alert from the Error Trigger'),
      B('التنبيه اللي بيقول «حصل خطأ» بس مش مفيد. الـ Error Trigger بيدّيك: اسم الـ workflow، النود اللي فشل، رسالة الخطأ، رابط التنفيذ `execution.url`، والوقت. ابعتهم كلهم في رسالة قصيرة، ورتّب: الأعطال المتكررة تتجمع بدل 100 رسالة.',
        'An alert that only says «an error happened» is useless. The Error Trigger gives you: the workflow name, the failed node, the error message, the execution link `execution.url`, and the time. Send all of them in a short message, and group repeated failures instead of 100 messages.'),
      '🔴 {{ $json.workflow.name }}\nNode: {{ $json.execution.lastNodeExecuted }}\nError: {{ $json.execution.error.message }}\nOpen: {{ $json.execution.url }}')],
    practice: [B('ابني error workflow يبعت الرسالة دي على تليجرام، واربطه بـ 3 workflows من Settings.', 'Build an error workflow that sends this message to Telegram, and link it to 3 workflows from Settings.'),
      B('اعمل خطأ عمدًا وادخل من الرابط على التنفيذ اللي فشل على طول.', 'Cause an error on purpose and open the failed execution straight from the link.')],
    words: [W('failure report', 'رسالة بتوصف عطل وفيها تفاصيله', 'a message describing a failure with its details', 'The failure report links to the execution.'),
      W('noise', 'تنبيهات كتير ملهاش لازمة بتخبّي المهم', 'many useless alerts that hide the important ones', 'Group repeated errors to cut the noise.')],
    quiz: [Q(B('أهم حاجة في رسالة التنبيه:', 'The most useful part of an alert:'), [B('رابط التنفيذ اللي فشل', 'the link to the failed execution'), B('إيموجي', 'an emoji'), B('اسمك', 'your name')], 0, B('توصل للمشكلة في ثانية.', 'Reach the problem in a second.'))] },
  { learn: [L(B('عقد الـ sub-workflow', 'The sub-workflow contract'),
      B('الـ sub-workflow زي دالة ليها **عقد**: المدخلات (أسماء وأنواع، في Execute Workflow Trigger)، والمخرجات (شكل ثابت)، والأخطاء (بيرجع `ok: false` ولا بيفشل؟). اكتب العقد ده في sticky note جوه الـ sub-workflow نفسه. ولو غيّرت العقد، كل اللي بينادوه ممكن يتكسروا.',
        'A sub-workflow is like a function with a **contract**: inputs (names and types, in the Execute Workflow Trigger), outputs (a fixed shape), and errors (does it return `ok: false` or fail?). Write the contract in a note inside the sub-workflow. If you change the contract, every caller may break.'),
      'Contract: Format phone\n  in:  phone (string)\n  out: { ok: true, phone_e164: "+20…" } | { ok: false, reason: "invalid" }\n  never throws for bad input')],
    practice: [B('اكتب العقد لـ sub-workflow عندك، وخلّيه يرجّع نفس الشكل دايمًا (نجاح أو فشل).', 'Write the contract for one of your sub-workflows, and make it always return the same shape (success or failure).'),
      B('ابحث مين بينادي الـ sub-workflow ده قبل ما تغيّر فيه حاجة.', 'Find who calls this sub-workflow before you change anything in it.')],
    words: [W('contract', 'اتفاق على المدخلات والمخرجات', 'an agreement on inputs and outputs', 'Do not break the sub-workflow contract.'),
      W('input contract', 'المدخلات اللي الـ sub-workflow متفق إنه ياخدها', 'the inputs a sub-workflow has agreed to accept', 'Renaming a field breaks the input contract.')],
    quiz: [Q(B('غيّرت اسم مدخل في sub-workflow. ده:', 'You renamed an input of a sub-workflow. That is:'), [B('breaking change', 'a breaking change'), B('تحسين صغير', 'a small improvement'), B('مش بيأثر', 'harmless')], 0, B('اللي بينادوه هيبعتوا الاسم القديم.', 'Callers still send the old name.'))] },
  { learn: [L(B('Custom Execution Data للبحث', 'Custom execution data for searching'),
      B('بعد شهر هيبقى عندك آلاف التنفيذات. نود **Execution Data** (أو `$execution.customData.set()`) بيحط معلومات على التنفيذ زي `order_id` أو `customer`. بعد كده تقدر تفلتر التنفيذات بيها وتلاقي «التنفيذ بتاع طلب 1042» في ثواني.',
        'In a month you will have thousands of executions. The **Execution Data** node (or `$execution.customData.set()`) attaches information to an execution, such as `order_id` or `customer`. You can then filter executions by it and find «the run for order 1042» in seconds.'),
      'Execution Data node: order_id = {{ $json.id }}, customer = {{ $json.email }}\nExecutions → Filter → order_id = 1042')],
    practice: [B('ضيف Execution Data بـ order_id في workflow الطلبات، وشغّله على 3 طلبات، ودوّر على واحد منهم.', 'Add Execution Data with order_id to the orders workflow, run it for 3 orders, and search for one of them.'),
      B('قرّر لكل workflow عندك: أنهي حقل هتحتاج تدوّر بيه؟', 'Decide for each of your workflows: which field will you need to search by?')],
    words: [W('custom data', 'بيانات انت بتضيفها على التنفيذ', 'data you attach to an execution yourself', 'Save the order id as custom data.'),
      W('execution log', 'سجل كل مرات تشغيل الـ workflow', 'the record of every run of a workflow', 'Search the execution log by order id.')],
    quiz: [Q(B('ليه تحط order_id كـ custom data؟', 'Why store order_id as custom data?'), [B('تلاقي التنفيذ بتاع الطلب بسرعة', 'to find the run for an order quickly'), B('عشان أسرع', 'to run faster'), B('عشان الأمان', 'for security')], 0, B('فلترة التنفيذات.', 'Filtering executions.'))] },
  { learn: [L(B('إعادة التشغيل الآمنة', 'Safe re-runs'),
      B('لما عطل يتصلّح، محتاج تعيد العناصر اللي فشلت. **Retry** من صفحة التنفيذ بيعيد من النود اللي فشل. بس اسأل الأول: لو اتعاد، فيه حاجة هتتكرر؟ (إيميل اتبعت، دفع اتسجّل). لو أيوه، خلّي الخطوات دي idempotent أو ابدأ من بعدها. وفي الحالات الكبيرة: احفظ العناصر الفاشلة في شيت «dead letter» وارجع لها.',
        'When a failure is fixed, you need to redo the failed items. **Retry** on the execution page restarts from the failed node. But ask first: if it re-runs, will something repeat? (an email sent, a payment saved). If yes, make those steps idempotent or start after them. For bigger cases: save failed items to a «dead letter» sheet and come back to them.'),
      'error branch → Google Sheets "dead_letter" (time, workflow, item, error)\nafter the fix: manual trigger → read dead_letter → reprocess → mark done')],
    practice: [B('ابني شيت dead letter وworkflow يعيد معالجة اللي فيه ويعلّمهم «اتعالج».', 'Build a dead letter sheet and a workflow that reprocesses its rows and marks them «done».'),
      B('جرّب Retry من صفحة تنفيذ فاشل بعد ما تصلّح السبب.', 'Try Retry on a failed execution after fixing the cause.')],
    words: [W('dead letter', 'مكان بتتحفظ فيه العناصر اللي فشلت عشان ترجعلها', 'a place where failed items are kept to handle later', 'Send failed orders to the dead letter sheet.'),
      W('reprocess', 'تعالج تاني بعد الإصلاح', 'to handle again after a fix', 'Reprocess the failed items tomorrow.')],
    quiz: [Q(B('قبل ما تعيد تشغيل تنفيذ فاشل تسأل:', 'Before retrying a failed execution, ask:'), [B('فيه خطوة هتتكرر؟', 'will any step repeat?'), B('الساعة كام؟', 'what time is it?'), B('مين عمله؟', 'who built it?')], 0, B('إيميل مكرر أو دفع مكرر.', 'A double email or double payment.'))] },
  { review: [B('⚡ الأخطاء المتوقعة والمفاجئة، وتنبيه مفيد فيه رابط التنفيذ.', '⚡ Expected and unexpected errors, and a useful alert with the execution link.'),
      B('⚡ عقد الـ sub-workflow، والـ custom data، والـ dead letter وإعادة التشغيل الآمنة: طبّقهم في مشروع الشهر التالت.', '⚡ The sub-workflow contract, custom data, dead letters and safe re-runs: use them in the month 3 project.')] }
] };
