// JavaScript week 11 — layout: Flexbox, Grid and responsive design.
const B = (ar, en) => ({ ar, en });
module.exports = {
  level: B('مبتدئ · مكثّف', 'Beginner · intensive'),
  title: B('التخطيط: Flexbox وGrid والتصميم المتجاوب', 'Layout: Flexbox, Grid and responsive design'),
  goal: B('ترتّب أي صفحة: صفوف وأعمدة بـ Flexbox، وشبكات بـ Grid، ومواضع بـ position، وتصميم بيشتغل من الموبايل للشاشة الكبيرة بـ media queries وmobile-first — بالعربي والإنجليزي.',
          'Lay out any page: rows and columns with Flexbox, grids with Grid, placement with position, and design that works from phone to big screen with media queries and mobile-first — in Arabic and English.'),
  days: [
    { title: B('Flexbox: صف أو عمود من العناصر', 'Flexbox: a row or column of items'),
      goal: B('ترتّب عناصر في صف أو عمود بمسافات ومحاذاة، وتخليها تلف لسطر جديد.', 'Arrange items in a row or column with gaps and alignment, and let them wrap onto new lines.'),
      learn: [
        { h: B('display: flex', 'display: flex'),
          p: B('`display: flex` على **الأب** بيخلي أبناءه المباشرين يترصّوا في **صف** (افتراضيًا). `gap: 1rem` مسافة بينهم (أحسن من margin). `flex-direction: column` يخليهم عمود. والصف بيتبع اتجاه الصفحة: في RTL بيبدأ من اليمين لوحده. ده أكتر أداة تخطيط هتستخدمها: navbar، وصف أزرار، وكارت فيه صورة ونص.',
            '`display: flex` on the **parent** lines its direct children up in a **row** (by default). `gap: 1rem` spaces them (better than margins). `flex-direction: column` makes a column. A row follows the page direction: in RTL it starts from the right by itself. It is the layout tool you will use most: a navbar, a row of buttons, a card with an image and text.'),
          ex: '<style>\n  .row { display: flex; gap: 0.75rem; padding: 8px; background: #f3f4f6; margin-bottom: 8px; }\n  .row > div { background: #10b981; color: #fff; padding: 8px 12px; border-radius: 6px; }\n  .col { flex-direction: column; }\n</style>\n<div class="row"><div>One</div><div>Two</div><div>Three</div></div>\n<div class="row" dir="rtl"><div>واحد</div><div>اتنين</div><div>تلاتة</div></div>\n<div class="row col"><div>Column 1</div><div>Column 2</div></div>', run: 'html' },
        { h: B('justify-content وalign-items', 'justify-content and align-items'),
          p: B('**justify-content** بيوزّع على **المحور الأساسي** (أفقي في الصف): `flex-start` و`center` و`space-between` (أول وآخر على الأطراف والباقي في النص — مثالي للـ header: لوجو يمين وقايمة شمال) و`space-around`. **align-items** على **المحور التاني** (رأسي في الصف): `center` (يوسّط رأسيًا — الحل الأشهر لـ «إزاي أوسّط حاجة»)، و`stretch` (الافتراضي)، و`flex-start`.',
            '**justify-content** distributes along the **main axis** (horizontal in a row): `flex-start`, `center`, `space-between` (first and last at the edges, the rest in between — perfect for a header: logo on one side, menu on the other) and `space-around`. **align-items** works on the **cross axis** (vertical in a row): `center` (vertical centring — the famous answer to «how do I centre this?»), `stretch` (the default) and `flex-start`.'),
          ex: '<style>\n  .bar { display: flex; justify-content: space-between; align-items: center; padding: 10px 14px; background: #1f2937; color: #fff; border-radius: 8px; margin-bottom: 8px; }\n  .bar nav { display: flex; gap: 12px; }\n  .center { display: flex; justify-content: center; align-items: center; height: 90px; background: #ecfdf5; border-radius: 8px; }\n</style>\n<header class="bar"><strong>Nile Store</strong><nav><span>Shop</span><span>Offers</span><span>Contact</span></nav></header>\n<div class="center"><span>Perfectly centred, both ways</span></div>', run: 'html' },
        { h: B('flex-wrap: سطر جديد لما المكان يخلص', 'flex-wrap: a new line when space runs out'),
          p: B('افتراضيًا العناصر بتتزنق في سطر واحد حتى لو مفيش مكان. `flex-wrap: wrap` بيخليها تنزل سطر جديد — وده أساس الكروت المتجاوبة البسيطة. مع `flex: 1 1 220px` على كل كارت: «ابدأ بـ 220px، وكبّر لو فيه مكان، وصغّر لو محتاج» — الكروت بتملا السطر وتلف لوحدها من غير media query.',
            'By default items squeeze into one line even when there is no room. `flex-wrap: wrap` lets them drop onto a new line — the basis of simple responsive cards. With `flex: 1 1 220px` on each card: «start at 220px, grow when there is room, shrink when needed» — cards fill the line and wrap by themselves, with no media query.'),
          ex: '<style>\n  .cards { display: flex; flex-wrap: wrap; gap: 10px; }\n  .card { flex: 1 1 160px; background: #fff; border: 1px solid #e5e7eb; border-radius: 10px; padding: 12px; }\n</style>\n<div class="cards">\n  <div class="card">Notebook · 45</div><div class="card">Pen Pro · 30</div><div class="card">Backpack · 650</div>\n  <div class="card">Ruler · 12</div><div class="card">Marker · 18</div>\n</div>\n<p>Resize the frame (or use the phone view): the cards wrap by themselves.</p>', run: 'html' },
        { h: B('flex على الأبناء: grow وshrink وbasis', 'flex on the children: grow, shrink and basis'),
          p: B('`flex-grow: 1` العنصر ياخد المكان الفاضي (خانة بحث بتملا الـ navbar). `flex-shrink: 0` ميصغرش أبدًا (أيقونة أو صورة). `flex-basis: 200px` مقاس البداية. والاختصار `flex: 1` = «خد نصيبك من المكان». و`align-self` يغيّر محاذاة عنصر واحد، و`order` يغيّر ترتيب العرض (بحساب: قارئ الشاشة بيقرا ترتيب الـ HTML).',
            '`flex-grow: 1` makes an item take the free space (a search box filling the navbar). `flex-shrink: 0` means never shrink (an icon or image). `flex-basis: 200px` is the starting size. The shorthand `flex: 1` means «take your share of the space». And `align-self` changes one item’s alignment, while `order` changes display order (carefully: screen readers follow the HTML order).'),
          ex: '<style>\n  .search { display: flex; gap: 8px; align-items: center; background: #f9fafb; padding: 8px; border-radius: 8px; }\n  .search input { flex: 1; min-width: 0; padding: 6px 8px; }\n  .search .icon { flex-shrink: 0; width: 28px; height: 28px; border-radius: 50%; background: #10b981; }\n  .search button { flex-shrink: 0; }\n</style>\n<div class="search"><span class="icon"></span><input placeholder="Search products…"><button>Search</button></div>', run: 'html' },
        { h: B('أنماط Flex اللي هتكررها', 'Flex patterns you will repeat'),
          p: B('**media object**: صورة جنبها نص (`display:flex; gap; align-items:flex-start`). **footer لازق تحت**: الـ body عمود `min-height: 100vh` والـ main بـ `flex: 1`. **زراير على الطرف**: `margin-inline-start: auto` على آخر زرار بيزقّه للطرف التاني. افتكر إن الـ flex بيشتغل على **الأبناء المباشرين بس**.',
            '**The media object**: an image beside text (`display:flex; gap; align-items:flex-start`). **A footer stuck to the bottom**: the body as a column with `min-height: 100vh` and the main with `flex: 1`. **Buttons pushed to the edge**: `margin-inline-start: auto` on the last button pushes it to the far side. Remember flex only affects **direct children**.'),
          ex: '<style>\n  .media { display: flex; gap: 12px; align-items: flex-start; border: 1px solid #e5e7eb; padding: 10px; border-radius: 10px; margin-bottom: 8px; }\n  .media img { width: 56px; height: 56px; border-radius: 8px; flex-shrink: 0; }\n  .actions { display: flex; gap: 8px; }\n  .actions .push { margin-inline-start: auto; }\n</style>\n<div class="media"><img src="https://picsum.photos/seed/m/112/112" alt="Product photo"><div><strong>Backpack</strong><br>Water-resistant, two pockets, 650 EGP.</div></div>\n<div class="actions"><button>Edit</button><button>Copy</button><button class="push">Delete</button></div>', run: 'html' }
      ],
      practice: [
        B('اعمل navbar: لوجو وروابط وزرار، بـ space-between وalign-items: center.', 'Build a navbar: logo, links and a button, with space-between and align-items: center.'),
        B('وسّط عنصر أفقي ورأسي في صندوق 200px بـ flex.', 'Centre an element horizontally and vertically in a 200px box with flex.'),
        B('اعمل 8 كروت بـ flex-wrap وflex: 1 1 200px وجرّب مقاسات الشاشة.', 'Make 8 cards with flex-wrap and flex: 1 1 200px and try different screen sizes.'),
        B('اعمل خانة بحث بتملا المكان وأيقونة متصغرش.', 'Build a search box that fills the space and an icon that never shrinks.'),
        B('اعمل media object وزرار متزقوق للطرف بـ margin-inline-start: auto.', 'Make a media object and a button pushed to the edge with margin-inline-start: auto.'),
        B('العب Flexbox Froggy لحد المرحلة 24.', 'Play Flexbox Froggy up to level 24.')
      ],
      code: [
        { u: B('هيكل صفحة بـ footer تحت', 'A page skeleton with the footer at the bottom'), p: 'body { min-height: 100vh; display: flex; flex-direction: column; margin: 0; }\nmain { flex: 1; }\n.header { display: flex; align-items: center; justify-content: space-between; gap: 1rem; padding: 0.75rem 1rem; }', lang: 'css', show: 1 }
      ],
      words: [
        { t: 'Flexbox', m: B('نظام تخطيط لصف أو عمود من العناصر', 'a layout system for a row or column of items'), ex: 'display: flex' },
        { t: 'flex container', m: B('الأب اللي عليه display: flex', 'the parent with display: flex'), ex: '.row { display: flex }' },
        { t: 'main axis', m: B('اتجاه الصف أو العمود الأساسي', 'the main direction of the row or column'), ex: 'justify-content works on it' },
        { t: 'cross axis', m: B('الاتجاه العمودي على الأساسي', 'the direction across the main one'), ex: 'align-items works on it' },
        { t: 'gap', m: B('المسافة بين العناصر في flex أو grid', 'the space between items in flex or grid'), ex: 'gap: 1rem' },
        { t: 'wrap', m: B('ينزل سطر جديد لما المكان يخلص', 'moving onto a new line when space runs out'), ex: 'flex-wrap: wrap' },
        { t: 'flex-grow', m: B('قد إيه العنصر ياخد من المكان الفاضي', 'how much free space an item takes'), ex: 'flex: 1' }
      ],
      read: [{ lib: 'CSS-Tricks: A Complete Guide to Flexbox', what: B('الصفحة كلها مع الرسومات (Properties for the parent والـ children).', 'The whole page with the drawings (properties for the parent and the children).') },
        { lib: 'Flexbox Froggy', what: B('كل المراحل الـ 24.', 'All 24 levels.') }],
      challenge: B('اعمل header كامل متجاوب بـ flex بس: لوجو، وخانة بحث بتملا المكان، و3 روابط، وزرار «سلة» بعدد — على الشاشة الواسعة في سطر، ولما تضيق الروابط تلف تحت (flex-wrap) والبحث ياخد السطر كله، ويشتغل بالعربي والإنجليزي.', 'Build a complete responsive header with flex only: a logo, a search box filling the space, 3 links and a «basket» button with a count — on one line on wide screens; when narrow, the links wrap below (flex-wrap) and search takes the full line — working in Arabic and English.'),
      quiz: [
        { q: B('display: flex بيتحط على:', 'display: flex goes on:'), o: [B('الأب', 'the parent'), B('كل ابن', 'each child'), B('الصفحة كلها', 'the whole page')], a: 0, why: B('بيأثر على الأبناء المباشرين.', 'It affects the direct children.') },
        { q: B('لوجو على طرف وقايمة على الطرف التاني:', 'A logo at one end and a menu at the other:'), o: ['justify-content: space-between', 'align-items: center', 'flex-wrap: wrap'], a: 0, why: B('بيوزّع على الأطراف.', 'It spreads to the edges.') },
        { q: B('توسيط رأسي في صف flex:', 'Vertical centring in a flex row:'), o: ['align-items: center', 'justify-content: center', 'text-align: center'], a: 0, why: B('المحور التاني.', 'The cross axis.') },
        { q: B('عنصر ياخد كل المكان الفاضي:', 'An item taking all the free space:'), o: ['flex: 1', 'flex-shrink: 0', 'order: 1'], a: 0, why: B('grow.', 'Grow.') }
      ] },

    { title: B('CSS Grid: شبكة صفوف وأعمدة', 'CSS Grid: a grid of rows and columns'),
      goal: B('تعمل تخطيط بعدين (صفوف وأعمدة) بـ Grid: أعمدة بنسب، وكروت متجاوبة من غير media query، ومناطق بأسماء.', 'Build two-dimensional layouts (rows and columns) with Grid: proportional columns, responsive cards with no media query, and named areas.'),
      learn: [
        { h: B('grid-template-columns وfr', 'grid-template-columns and fr'),
          p: B('`display: grid; grid-template-columns: 1fr 2fr 1fr;` بيعمل 3 أعمدة، النص ضعف الأطراف. **fr** = «حصة من المكان المتبقي». `repeat(4, 1fr)` = 4 أعمدة متساوية. `gap` زي flex. الفرق: Flex لـ **بعد واحد** (صف **أو** عمود)، وGrid لـ **بعدين** (صفوف **و** أعمدة مع بعض) — جدول كروت، أو هيكل صفحة.',
            '`display: grid; grid-template-columns: 1fr 2fr 1fr;` makes 3 columns, the middle twice as wide as the sides. **fr** = «a share of the remaining space». `repeat(4, 1fr)` = 4 equal columns. `gap` works as in flex. The difference: Flex is for **one dimension** (a row **or** a column), Grid for **two** (rows **and** columns together) — a card grid or a page skeleton.'),
          ex: '<style>\n  .g { display: grid; grid-template-columns: 1fr 2fr 1fr; gap: 8px; margin-bottom: 8px; }\n  .g > div, .g4 > div { background: #6366f1; color: #fff; padding: 10px; border-radius: 6px; text-align: center; }\n  .g4 { display: grid; grid-template-columns: repeat(4, 1fr); gap: 8px; }\n</style>\n<div class="g"><div>1fr</div><div>2fr</div><div>1fr</div></div>\n<div class="g4"><div>1</div><div>2</div><div>3</div><div>4</div><div>5</div><div>6</div></div>', run: 'html' },
        { h: B('الكروت المتجاوبة السحرية', 'The magic responsive cards'),
          p: B('`grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));` = «اعمل أكبر عدد أعمدة ممكن كل واحد 220px على الأقل، ووزّع الباقي بالتساوي». على الموبايل عمود، على التابلت 2 أو 3، على الشاشة الكبيرة 4 أو أكتر — **من غير ولا media query**. ده سطر هتحفظه وتستخدمه في كل مشروع (كتالوج، لوحة، معرض صور).',
            '`grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));` = «make as many columns as fit, each at least 220px, sharing the rest equally». One column on a phone, 2 or 3 on a tablet, 4 or more on a big screen — **with no media query at all**. A line you will memorise and use in every project (a catalogue, a dashboard, a gallery).'),
          ex: '<style>\n  .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr)); gap: 10px; }\n  .item { border: 1px solid #e5e7eb; border-radius: 10px; padding: 10px; background: #fff; }\n  .item img { width: 100%; height: 70px; object-fit: cover; border-radius: 6px; }\n</style>\n<div class="grid">\n  <div class="item"><img src="https://picsum.photos/seed/a1/280/140" alt="Notebook"><strong>Notebook</strong><br>45 EGP</div>\n  <div class="item"><img src="https://picsum.photos/seed/a2/280/140" alt="Pen"><strong>Pen Pro</strong><br>30 EGP</div>\n  <div class="item"><img src="https://picsum.photos/seed/a3/280/140" alt="Backpack"><strong>Backpack</strong><br>650 EGP</div>\n  <div class="item"><img src="https://picsum.photos/seed/a4/280/140" alt="Ruler"><strong>Ruler</strong><br>12 EGP</div>\n</div>', run: 'html' },
        { h: B('عنصر بياخد أكتر من خانة', 'An item spanning several cells'),
          p: B('`grid-column: span 2` العنصر ياخد عمودين، و`grid-row: span 2` صفين. أو بأرقام الخطوط: `grid-column: 1 / -1` = من أول خط لآخر خط (عرض كامل — مثالي لعنوان أو بانر جوه شبكة كروت). أرقام الخطوط بتبدأ من 1 من بداية السطر (يمين في RTL).',
            '`grid-column: span 2` makes an item take two columns, and `grid-row: span 2` two rows. Or with line numbers: `grid-column: 1 / -1` = from the first line to the last (full width — perfect for a heading or banner inside a card grid). Line numbers start at 1 from the line’s start (the right in RTL).'),
          ex: '<style>\n  .dash { display: grid; grid-template-columns: repeat(4, 1fr); gap: 8px; }\n  .dash > div { background: #ecfdf5; border: 1px solid #a7f3d0; border-radius: 8px; padding: 10px; }\n  .wide { grid-column: span 2; }\n  .tall { grid-row: span 2; }\n  .full { grid-column: 1 / -1; background: #fef3c7 !important; border-color: #fde68a !important; }\n</style>\n<div class="dash">\n  <div class="full">Full-width banner</div>\n  <div class="wide">Revenue (2 columns)</div><div class="tall">Orders (2 rows)</div><div>Customers</div>\n  <div>Refunds</div><div>Stock</div><div>Rating</div>\n</div>', run: 'html' },
        { h: B('grid-template-areas: تخطيط بالأسماء', 'grid-template-areas: layout by names'),
          p: B('أوضح طريقة لهيكل صفحة: ترسم المناطق بأسماء: `grid-template-areas: "head head" "side main" "foot foot";` وكل عنصر `grid-area: head`. وعلى الموبايل تعيد رسمها عمود واحد في media query: `"head" "main" "side" "foot"`. الكود بيبقى رسمة للصفحة بالظبط.',
            'The clearest way to build a page skeleton: draw named areas: `grid-template-areas: "head head" "side main" "foot foot";` and give each element `grid-area: head`. On phones redraw it as a single column in a media query: `"head" "main" "side" "foot"`. The code becomes a picture of the page.'),
          ex: '<style>\n  .page { display: grid; grid-template-columns: 160px 1fr; grid-template-areas: "head head" "side main" "foot foot"; gap: 8px; }\n  .page > * { padding: 10px; border-radius: 8px; background: #f3f4f6; }\n  .page header { grid-area: head; background: #1f2937; color: #fff; }\n  .page aside { grid-area: side; }\n  .page main { grid-area: main; background: #ecfdf5; min-height: 80px; }\n  .page footer { grid-area: foot; }\n  @media (max-width: 480px) { .page { grid-template-columns: 1fr; grid-template-areas: "head" "main" "side" "foot"; } }\n</style>\n<div class="page"><header>Header</header><aside>Filters</aside><main>Main content</main><footer>Footer</footer></div>', run: 'html' },
        { h: B('المحاذاة في Grid وimplicit rows', 'Alignment in Grid, and implicit rows'),
          p: B('`place-items: center` بيوسّط كل حاجة جوه خانتها. `align-items: start` يخلي الكروت متمتدش لطول أطول واحدة. `grid-auto-rows: minmax(120px, auto)` ارتفاع الصفوف اللي بتتعمل لوحدها. و`grid-auto-flow: dense` بيملا الفراغات (مفيد لمعرض صور بمقاسات مختلفة). وافتكر: Flex للمكوّنات الصغيرة، Grid لهيكل الصفحة والشبكات.',
            '`place-items: center` centres everything in its cell. `align-items: start` stops cards stretching to the tallest one. `grid-auto-rows: minmax(120px, auto)` sets the height of rows created automatically. And `grid-auto-flow: dense` fills gaps (handy for a gallery of mixed sizes). Remember: Flex for small components, Grid for page skeletons and grids.'),
          ex: '<style>\n  .tiles { display: grid; grid-template-columns: repeat(3, 1fr); grid-auto-rows: 70px; gap: 6px; place-items: center; }\n  .tiles > div { background: #e0e7ff; width: 100%; height: 100%; display: grid; place-items: center; border-radius: 6px; }\n</style>\n<div class="tiles"><div>A</div><div>B</div><div>C</div><div>D</div><div>E</div></div>', run: 'html' }
      ],
      practice: [
        B('اعمل 3 أعمدة بـ fr بنسب مختلفة.', 'Make 3 columns with different fr proportions.'),
        B('اعمل كتالوج 9 منتجات بـ auto-fit وminmax وجرّب مقاسات الشاشة.', 'Build a 9-product catalogue with auto-fit and minmax and try different screen sizes.'),
        B('اعمل لوحة فيها كارت عرضه عمودين وكارت طوله صفين وبانر 1 / -1.', 'Build a dashboard with a 2-column card, a 2-row card and a 1 / -1 banner.'),
        B('ارسم هيكل صفحة بـ grid-template-areas وأعد رسمه للموبايل.', 'Draw a page skeleton with grid-template-areas and redraw it for phones.'),
        B('قرّر لـ 6 أجزاء من صفحة: Flex ولا Grid وليه.', 'Decide for 6 parts of a page: Flex or Grid, and why.'),
        B('العب Grid Garden لحد آخر مرحلة.', 'Play Grid Garden to the last level.')
      ],
      code: [
        { u: B('السطر السحري', 'The magic line'), p: '.cards {\n  display: grid;\n  grid-template-columns: repeat(auto-fit, minmax(min(100%, 240px), 1fr));\n  gap: 1rem;\n}\n/* min(100%, 240px) keeps a single card from overflowing very small screens */', lang: 'css', show: 1 }
      ],
      words: [
        { t: 'CSS Grid', m: B('نظام تخطيط بصفوف وأعمدة مع بعض', 'a layout system with rows and columns together'), ex: 'display: grid' },
        { t: 'fr unit', m: B('حصة من المكان المتبقي في Grid', 'a share of the remaining space in Grid'), ex: '1fr 2fr' },
        { t: 'auto-fit', m: B('اعمل أكبر عدد أعمدة يناسب المكان', 'make as many columns as fit'), ex: 'repeat(auto-fit, …)' },
        { t: 'minmax', m: B('مقاس بحد أدنى وحد أقصى', 'a size with a minimum and a maximum'), ex: 'minmax(220px, 1fr)' },
        { t: 'grid area', m: B('منطقة باسم في شبكة', 'a named region of a grid'), ex: 'grid-area: main' },
        { t: 'span', m: B('العنصر ياخد أكتر من خانة', 'an item taking several cells'), ex: 'grid-column: span 2' },
        { t: 'grid line', m: B('الخطوط الفاصلة المرقّمة بين الأعمدة أو الصفوف', 'the numbered lines between columns or rows'), ex: 'grid-column: 1 / -1' }
      ],
      read: [{ lib: 'CSS-Tricks: A Complete Guide to CSS Grid', what: B('Properties for the Parent وProperties for the Children.', 'Properties for the Parent and Properties for the Children.') },
        { lib: 'Grid Garden', what: B('كل المراحل.', 'Every level.') }],
      challenge: B('اعمل «لوحة متابعة الطلبات» بـ Grid: هيكل الصفحة بـ areas (header وفلاتر جانبية وmain وfooter)، وجوه main شبكة 4 كروت أرقام (واحد منهم عرضه عمودين)، وتحتها كروت طلبات بـ auto-fit — وعلى الموبايل كله عمود واحد بالترتيب: header ثم الأرقام ثم الطلبات ثم الفلاتر.', 'Build an «order tracking dashboard» with Grid: a page skeleton with areas (header, side filters, main, footer), inside main a grid of 4 number cards (one spanning two columns), and below it order cards with auto-fit — on phones all in one column in the order: header, numbers, orders, filters.'),
      quiz: [
        { q: B('Grid أنسب من Flex لـ:', 'Grid suits better than Flex for:'), o: [B('صفوف وأعمدة مع بعض', 'rows and columns together'), B('صف أزرار', 'a row of buttons'), B('توسيط كلمة', 'centring a word')], a: 0, why: B('بعدين.', 'Two dimensions.') },
        { q: B('`1fr 1fr 2fr` العمود التالت:', '`1fr 1fr 2fr` the third column is:'), o: [B('ضعف الواحد', 'twice one of the others'), B('زيهم', 'the same'), B('نصهم', 'half')], a: 0, why: B('حصتين.', 'Two shares.') },
        { q: B('كروت متجاوبة من غير media query:', 'Responsive cards with no media query:'), o: ['repeat(auto-fit, minmax(220px, 1fr))', 'repeat(4, 220px)', 'grid-auto-flow: dense'], a: 0, why: B('السطر السحري.', 'The magic line.') },
        { q: B('`grid-column: 1 / -1`:', '`grid-column: 1 / -1`:'), o: [B('عرض كامل', 'full width'), B('عمود واحد', 'one column'), B('آخر عمود', 'the last column')], a: 0, why: B('من أول خط لآخر خط.', 'From the first line to the last.') }
      ] },

    { title: B('position وطبقات العناصر', 'position and stacking'),
      goal: B('تحط عناصر في أماكن محددة: relative وabsolute (بادج على صورة)، وsticky (header لازق)، وfixed (زرار عائم)، وتتحكم في مين فوق مين.', 'Place elements exactly: relative and absolute (a badge on an image), sticky (a stuck header), fixed (a floating button), and control what sits on top.'),
      learn: [
        { h: B('relative وabsolute', 'relative and absolute'),
          p: B('`position: absolute` بيطلّع العنصر من التخطيط العادي ويحطه بـ `top`/`inset-inline-end`... بالنسبة لأقرب أب عنده `position: relative`. النمط الأشهر: الكارت `position: relative`، والبادج («جديد» أو «-20%») جواه `position: absolute; top: 8px; inset-inline-start: 8px;`. من غير الأب الـ relative، العنصر بيروح لأول الصفحة.',
            '`position: absolute` takes the element out of the normal layout and places it with `top`/`inset-inline-end`... relative to the nearest parent with `position: relative`. The most common pattern: the card is `position: relative`, and the badge («new» or «-20%») inside it is `position: absolute; top: 8px; inset-inline-start: 8px;`. Without the relative parent, the element flies to the top of the page.'),
          ex: '<style>\n  .card { position: relative; width: 220px; border-radius: 10px; overflow: hidden; border: 1px solid #e5e7eb; }\n  .card img { width: 100%; height: 120px; object-fit: cover; display: block; }\n  .badge { position: absolute; top: 8px; inset-inline-start: 8px; background: #b91c1c; color: #fff; font: 700 12px sans-serif; padding: 3px 8px; border-radius: 999px; }\n  .card p { margin: 8px 10px; }\n</style>\n<div class="card"><span class="badge">-20%</span><img src="https://picsum.photos/seed/sale/440/240" alt="Backpack on sale"><p>Backpack · 520 EGP</p></div>', run: 'html' },
        { h: B('sticky: لازق وانت بتنزل', 'sticky: stuck while you scroll'),
          p: B('`position: sticky; top: 0;` العنصر بيتحرك عادي لحد ما يوصل لأول الشاشة، وبعدين يفضل **لازق** هناك وانت بتنزل. مثالي لـ header الصفحة، وعناوين جداول طويلة (`thead th`)، وفلاتر جانبية. خلي له background عشان المحتوى ميبانش من تحته، وبيشتغل جوه أقرب أب بيعمل scroll.',
            '`position: sticky; top: 0;` moves normally until it reaches the top of the screen, then **sticks** there as you scroll. Perfect for a page header, the headings of long tables (`thead th`) and side filters. Give it a background so content does not show through, and it works within the nearest scrolling parent.'),
          ex: '<style>\n  .scroll { height: 160px; overflow: auto; border: 1px solid #e5e7eb; border-radius: 8px; }\n  .scroll h4 { position: sticky; top: 0; margin: 0; padding: 6px 10px; background: #1f2937; color: #fff; }\n  .scroll p { margin: 0; padding: 6px 10px; border-block-end: 1px solid #f3f4f6; }\n</style>\n<div class="scroll">\n  <h4>Orders (sticky heading — scroll inside this box)</h4>\n  <p>#1001 Sara 300</p><p>#1002 Omar 1,800</p><p>#1003 Mona 1,200</p><p>#1004 Hany 650</p><p>#1005 Laila 90</p><p>#1006 Adel 2,100</p><p>#1007 Nour 340</p><p>#1008 Karim 75</p>\n</div>', run: 'html' },
        { h: B('fixed: مثبّت في الشاشة', 'fixed: pinned to the screen'),
          p: B('`position: fixed` بيثبّت العنصر بالنسبة **للشاشة** نفسها — مش بيتحرك أبدًا مع الـ scroll: زرار واتساب عائم في الركن، أو شريط «قبول الكوكيز» تحت، أو تنبيه (toast). استخدم `inset-block-end: 1rem; inset-inline-end: 1rem;` عشان يبقى في الركن الصح بالعربي والإنجليزي، وخليه صغير عشان ميغطّيش المحتوى على الموبايل.',
            '`position: fixed` pins the element to the **screen** itself — it never moves with scrolling: a floating WhatsApp button in the corner, a «cookie consent» bar at the bottom, or a notification (toast). Use `inset-block-end: 1rem; inset-inline-end: 1rem;` so it lands in the right corner in Arabic and English, and keep it small so it does not cover content on phones.'),
          ex: '<style>\n  .fab { position: fixed; inset-block-end: 12px; inset-inline-end: 12px; background: #16a34a; color: #fff; border: 0; border-radius: 999px; padding: 10px 16px; box-shadow: 0 4px 12px rgb(0 0 0 / 0.2); font: 600 14px sans-serif; }\n</style>\n<p>Scroll this preview: the green button stays in the corner.</p>\n<p style="height:400px;background:linear-gradient(#fff,#ecfdf5)">Long content…</p>\n<button class="fab">💬 Chat with us</button>', run: 'html' },
        { h: B('z-index: مين فوق مين', 'z-index: who is on top'),
          p: B('لما عنصرين positioned (relative/absolute/fixed/sticky) فوق بعض، `z-index` الأكبر بيبقى فوق. بس `z-index` بيشتغل **جوه طبقته** (stacking context): عنصر بـ z-index 9999 جوه أب بـ z-index 1 مش هيطلع فوق حاجة برّه الأب أعلى منه. اعمل مقياس صغير ثابت (1 للبادجات، 10 للـ header، 100 للنوافذ، 1000 للتنبيهات) بدل أرقام عشوائية.',
            'When two positioned elements (relative/absolute/fixed/sticky) overlap, the larger `z-index` is on top. But `z-index` only works **within its layer** (stacking context): an element with z-index 9999 inside a parent with z-index 1 cannot rise above something higher outside that parent. Keep a small fixed scale (1 for badges, 10 for headers, 100 for dialogs, 1000 for notifications) instead of random numbers.'),
          ex: '<style>\n  .stack { position: relative; height: 110px; }\n  .stack div { position: absolute; width: 120px; height: 70px; border-radius: 8px; color: #fff; padding: 6px; font: 600 13px sans-serif; }\n  .a { background: #6366f1; top: 0; inset-inline-start: 0; z-index: 1; }\n  .b { background: #10b981; top: 25px; inset-inline-start: 50px; z-index: 3; }\n  .c { background: #f59e0b; top: 40px; inset-inline-start: 100px; z-index: 2; }\n</style>\n<div class="stack"><div class="a">z 1</div><div class="b">z 3 (on top)</div><div class="c">z 2</div></div>', run: 'html' },
        { h: B('overflow وobject-fit', 'overflow and object-fit'),
          p: B('`overflow: hidden` بيقص اللي طالع برّه الصندوق (مع border-radius عشان الصورة تتدوّر)، و`overflow: auto` يعمل scroll لما المحتوى يكتر (جدول عريض، قايمة طويلة). `object-fit: cover` يخلي الصورة تملا مكانها من غير ما تتمطّ (بتتقص)، و`contain` تظهر كلها جوه المكان. ده اللي بيخلي كروت المنتجات صورها متساوية مهما كان مقاس الصورة الأصلية.',
            '`overflow: hidden` clips whatever spills out of the box (with border-radius so the image is rounded too), and `overflow: auto` scrolls when content grows (a wide table, a long list). `object-fit: cover` makes an image fill its space without stretching (it crops), and `contain` shows all of it inside. This is what keeps product card images equal whatever the original size.'),
          ex: '<style>\n  .pics { display: flex; gap: 8px; }\n  .pics img { width: 110px; height: 80px; border: 1px solid #e5e7eb; border-radius: 8px; }\n  .stretch { object-fit: fill; }\n  .cover { object-fit: cover; }\n  .contain { object-fit: contain; background: #f9fafb; }\n</style>\n<div class="pics">\n  <figure><img class="stretch" src="https://picsum.photos/seed/tall/200/400" alt="A tall photo, stretched"><figcaption>fill (stretched)</figcaption></figure>\n  <figure><img class="cover" src="https://picsum.photos/seed/tall/200/400" alt="A tall photo, covered"><figcaption>cover</figcaption></figure>\n  <figure><img class="contain" src="https://picsum.photos/seed/tall/200/400" alt="A tall photo, contained"><figcaption>contain</figcaption></figure>\n</div>', run: 'html' }
      ],
      practice: [
        B('حط بادج «جديد» على ركن صورة منتج بـ relative وabsolute، وجرّبه بالعربي.', 'Put a «new» badge on the corner of a product image with relative and absolute, and try it in Arabic.'),
        B('اعمل header لازق بـ sticky وجدول طويل بعناوين لازقة.', 'Make a sticky header and a long table with sticky headings.'),
        B('اعمل زرار تواصل عائم بـ fixed في الركن المنطقي.', 'Make a floating contact button with fixed in the logical corner.'),
        B('اعمل 3 صناديق فوق بعض وغيّر ترتيبهم بـ z-index.', 'Stack 3 boxes and change their order with z-index.'),
        B('خلي صور 6 كروت بنفس المقاس بـ object-fit: cover.', 'Make 6 card images the same size with object-fit: cover.'),
        B('اكتب مقياس z-index لمشروعك في متغيرات.', 'Write a z-index scale for your project as variables.')
      ],
      code: [
        { u: B('مقياس الطبقات', 'The layer scale'), p: ':root { --z-badge: 1; --z-sticky: 10; --z-dropdown: 50; --z-dialog: 100; --z-toast: 1000; }\n.site-header { position: sticky; top: 0; z-index: var(--z-sticky); background: var(--surface); }\n.toast { position: fixed; inset-block-end: 1rem; inset-inline: 1rem; z-index: var(--z-toast); }', lang: 'css', show: 1 }
      ],
      words: [
        { t: 'position', m: B('بيحدد إزاي العنصر بيتحط في الصفحة', 'decides how an element is placed on the page'), ex: 'position: absolute' },
        { t: 'absolute positioning', m: B('حط العنصر بالنسبة لأقرب أب relative', 'placing an element relative to the nearest relative parent'), ex: 'a badge on a card' },
        { t: 'sticky', m: B('يتحرك عادي وبعدين يلزق في مكانه', 'moves normally, then sticks in place'), ex: 'position: sticky; top: 0' },
        { t: 'fixed', m: B('مثبّت بالنسبة للشاشة', 'pinned relative to the screen'), ex: 'a floating button' },
        { t: 'z-index', m: B('ترتيب الطبقات: الأكبر فوق', 'the layer order: higher is on top'), ex: 'z-index: 10' },
        { t: 'overflow', m: B('إيه اللي يحصل للمحتوى الطالع برّه الصندوق', 'what happens to content spilling out of a box'), ex: 'overflow: auto' },
        { t: 'object-fit', m: B('إزاي الصورة تملا مكانها', 'how an image fills its space'), ex: 'object-fit: cover' }
      ],
      read: [{ lib: 'MDN: CSS layout', what: B('Positioning (كله).', 'Positioning (all of it).') },
        { lib: 'web.dev: Learn CSS', what: B('Z-index and stacking contexts وOverflow.', 'Z-index and stacking contexts, and Overflow.') }],
      challenge: B('اعمل صفحة منتج: صورة كبيرة بـ object-fit وبادجين (خصم وجديد) في ركنين مختلفين، وheader لازق، وشريط «أضف للسلة» لازق تحت على الموبايل بس (fixed جوه media query)، ونافذة «الكمية» فوق كل حاجة بـ z-index من المقياس — وكلها صح بالعربي والإنجليزي.', 'Build a product page: a big image with object-fit and two badges (discount and new) in different corners, a sticky header, an «add to basket» bar fixed to the bottom on phones only (fixed inside a media query), and a «quantity» panel above everything using a z-index from the scale — all correct in Arabic and English.'),
      quiz: [
        { q: B('بادج absolute بيتحط بالنسبة لـ:', 'An absolute badge is placed relative to:'), o: [B('أقرب أب عنده position: relative', 'the nearest parent with position: relative'), B('الصفحة دايمًا', 'always the page'), B('العنصر اللي قبله', 'the previous element')], a: 0, why: B('ولو مفيش، الصفحة.', 'Or the page, if none.') },
        { q: B('header يلزق فوق وانت بتنزل:', 'A header that sticks at the top as you scroll:'), o: ['position: sticky; top: 0', 'position: absolute', 'float: top'], a: 0, why: B('sticky.', 'sticky.') },
        { q: B('زرار ثابت في ركن الشاشة:', 'A button fixed to a screen corner:'), o: ['position: fixed', 'position: relative', 'position: static'], a: 0, why: B('بالنسبة للشاشة.', 'Relative to the screen.') },
        { q: B('صور متساوية من غير ما تتمطّ:', 'Equal images without stretching:'), o: ['object-fit: cover', 'object-fit: fill', 'width: auto'], a: 0, why: B('بتملا وتقص.', 'It fills and crops.') }
      ] },

    { title: B('التصميم المتجاوب وmedia queries', 'Responsive design and media queries'),
      goal: B('تصمم من الموبايل الأول وتكبّر، وتستخدم media queries وclamp والصور المتجاوبة، وتختبر على مقاسات حقيقية من غير سكرول جانبي.', 'Design mobile-first and scale up, use media queries, clamp and responsive images, and test on real sizes with no sideways scroll.'),
      learn: [
        { h: B('mobile-first', 'Mobile-first'),
          p: B('أغلب زوار المواقع المصرية من الموبايل. ابدأ CSS بالتصميم **للشاشة الصغيرة** (عمود واحد، حروف مريحة، أزرار كبيرة)، وبعدين زوّد للشاشات الأكبر بـ `@media (min-width: 768px) { ... }`. ده أسهل بكتير من العكس (تبدأ بشاشة كبيرة وتحاول تصغّر)، والكود بيبقى أقل. والـ viewport meta لازم يكون موجود.',
            'Most visitors to Egyptian sites are on phones. Start the CSS with the **small screen** design (one column, comfortable text, big buttons), then add for larger screens with `@media (min-width: 768px) { ... }`. Far easier than the reverse (starting big and trying to shrink), and less code. And the viewport meta must be present.'),
          ex: '<style>\n  .layout { display: grid; gap: 8px; }\n  .layout > div { background: #e0e7ff; padding: 10px; border-radius: 8px; }\n  @media (min-width: 500px) { .layout { grid-template-columns: 200px 1fr; } }\n</style>\n<div class="layout"><div>Filters (stacked on small screens)</div><div>Results (beside the filters from 500px up)</div></div>\n<p>Change the frame width (or use the phone view) to see the switch.</p>', run: 'html' },
        { h: B('media queries ونقط التحول', 'Media queries and breakpoints'),
          p: B('`@media (min-width: 768px)` بيطبّق القواعد من 768px وأكتر. متحفظش مقاسات أجهزة — خلي **المحتوى** يقرر: كبّر الشاشة لحد ما التصميم «يتكسر» أو يبان فاضي، وحط نقطة تحول هناك. 2–3 نقط كفاية غالبًا (600 و900 و1200 مثلًا). وفيه media queries تانية مفيدة: `(prefers-color-scheme: dark)` و`(prefers-reduced-motion: reduce)` و`print`.',
            '`@media (min-width: 768px)` applies its rules from 768px up. Do not memorise device sizes — let the **content** decide: widen the screen until the design «breaks» or looks empty, and put a breakpoint there. 2–3 breakpoints are usually enough (say 600, 900 and 1200). Other useful media queries: `(prefers-color-scheme: dark)`, `(prefers-reduced-motion: reduce)` and `print`.'),
          ex: '<style>\n  .tag::after { content: " · small"; }\n  @media (min-width: 400px) { .tag::after { content: " · medium (≥400px)"; } }\n  @media (min-width: 700px) { .tag::after { content: " · large (≥700px)"; } }\n  @media print { .no-print { display: none; } }\n</style>\n<p class="tag">This frame is</p>\n<p class="no-print">This line disappears when you print the page.</p>', run: 'html' },
        { h: B('مقاسات سايلة: clamp وmin وmax', 'Fluid sizes: clamp, min and max'),
          p: B('بدل ما تغيّر الحجم عند كل نقطة تحول، خليه **سايل**: `font-size: clamp(1.5rem, 4vw, 2.75rem)` (أصغر حاجة، ونسبة من الشاشة، وأكبر حاجة). `padding: clamp(1rem, 4vw, 3rem)`. `width: min(100%, 60rem)` = «لحد 60rem بس ومتعدّيش الشاشة». ده بيقلل الـ media queries جدًا.',
            'Instead of changing sizes at every breakpoint, make them **fluid**: `font-size: clamp(1.5rem, 4vw, 2.75rem)` (a minimum, a share of the screen, a maximum). `padding: clamp(1rem, 4vw, 3rem)`. `width: min(100%, 60rem)` = «up to 60rem, never wider than the screen». This cuts media queries dramatically.'),
          ex: '<style>\n  .hero { padding: clamp(0.75rem, 5vw, 2.5rem); background: #1f2937; color: #fff; border-radius: 10px; width: min(100%, 36rem); }\n  .hero h2 { font-size: clamp(1.2rem, 6vw, 2.4rem); margin: 0 0 6px; }\n</style>\n<div class="hero"><h2>Fluid heading</h2><p>Padding and size grow smoothly with the frame, between limits.</p></div>', run: 'html' },
        { h: B('مفيش سكرول جانبي', 'No sideways scroll'),
          p: B('أكتر عيب في المواقع على الموبايل: الصفحة بتتسحب جنب. الأسباب: عنصر بعرض ثابت أكبر من الشاشة (`width: 500px`)، أو صورة من غير `max-width: 100%`، أو نص طويل من غير مسافات (رابط أو كود) — حلّه `overflow-wrap: anywhere`، أو جدول عريض — حطه في div بـ `overflow-x: auto`. اختبر في DevTools بـ Ctrl+Shift+M على 360px.',
            'The commonest flaw of sites on phones: the page drags sideways. The causes: a fixed-width element wider than the screen (`width: 500px`), an image without `max-width: 100%`, long text with no spaces (a link or code) — fixed with `overflow-wrap: anywhere` — or a wide table — put it in a div with `overflow-x: auto`. Test in DevTools with Ctrl+Shift+M at 360px.'),
          ex: '<style>\n  img { max-width: 100%; height: auto; }\n  .long { overflow-wrap: anywhere; background: #fef3c7; padding: 6px; }\n  .wrap { overflow-x: auto; }\n</style>\n<p class="long">https://nile.example/orders/export?from=2026-01-01&to=2026-12-31&format=xlsx&columns=id,customer,total</p>\n<div class="wrap"><table border="1" cellpadding="4"><tr><td>Jan</td><td>Feb</td><td>Mar</td><td>Apr</td><td>May</td><td>Jun</td><td>Jul</td><td>Aug</td><td>Sep</td><td>Oct</td><td>Nov</td><td>Dec</td></tr></table></div>\n<img src="https://picsum.photos/seed/wide/1200/200" alt="A wide banner that shrinks to fit">', run: 'html' },
        { h: B('الأزرار والقراية على الموبايل', 'Buttons and reading on phones'),
          p: B('الإصبع أتخن من الماوس: خلي الأزرار والروابط المهمة **44px على الأقل** وبينها مسافة. الخط 16px أو أكبر (أقل من كده iOS بيعمل zoom في الحقول). متعتمدش على hover (مفيش ماوس). حط الحاجات المهمة في متناول الإبهام (تحت). واختبر على موبايل حقيقي مرة على الأقل قبل ما تسلّم.',
            'A finger is thicker than a mouse pointer: make important buttons and links **at least 44px** with space between them. Text 16px or more (below that iOS zooms into fields). Do not rely on hover (there is no mouse). Put important things within thumb reach (at the bottom). And test on a real phone at least once before delivering.'),
          ex: '<style>\n  .actions { display: flex; flex-wrap: wrap; gap: 10px; }\n  .actions button { min-height: 44px; min-width: 44px; padding: 0 16px; font-size: 16px; border-radius: 10px; border: 1px solid #d1d5db; background: #fff; }\n  .actions .primary { background: #1f6f4a; color: #fff; border-color: #1f6f4a; flex: 1 1 100%; }\n  @media (min-width: 480px) { .actions .primary { flex: 0 1 auto; } }\n</style>\n<div class="actions"><button class="primary">Confirm order</button><button>Edit</button><button aria-label="Share">⤴</button></div>', run: 'html' }
      ],
      practice: [
        B('اكتب CSS صفحة mobile-first: عمود واحد، وبعدين عمودين من 768px.', 'Write a mobile-first page CSS: one column, then two columns from 768px.'),
        B('لاقي نقط التحول لتصميمك بتكبير الشاشة لحد ما يتكسر.', 'Find your design’s breakpoints by widening the screen until it breaks.'),
        B('حوّل 3 أحجام ثابتة لـ clamp وأحجام عرض لـ min().', 'Turn 3 fixed sizes into clamp and widths into min().'),
        B('لاقي وصلّح 3 أسباب سكرول جانبي في صفحة.', 'Find and fix 3 causes of sideways scroll on a page.'),
        B('خلي كل الأزرار المهمة 44px والخط 16px.', 'Make every important button 44px and the text 16px.'),
        B('اختبر صفحتك على 360 و768 و1280 في DevTools وعلى موبايل حقيقي.', 'Test your page at 360, 768 and 1280 in DevTools and on a real phone.')
      ],
      code: [
        { u: B('نقط تحول mobile-first', 'Mobile-first breakpoints'), p: '/* base: phones */\n.grid { display: grid; gap: 1rem; }\n/* tablets */\n@media (min-width: 40rem) { .grid { grid-template-columns: 1fr 1fr; } }\n/* laptops */\n@media (min-width: 64rem) { .grid { grid-template-columns: 220px 1fr 1fr; } }\n@media (prefers-reduced-motion: reduce) { * { animation: none !important; transition: none !important; } }', lang: 'css', show: 1 }
      ],
      words: [
        { t: 'responsive design', m: B('تصميم بيتظبط على كل مقاسات الشاشات', 'design adapting to every screen size'), ex: 'from phone to desktop' },
        { t: 'mobile-first', m: B('تبدأ تصمم للموبايل وبعدين تكبّر', 'designing for phones first, then scaling up'), ex: '@media (min-width: …)' },
        { t: 'media query', m: B('شرط في CSS حسب الشاشة أو الإعدادات', 'a CSS condition on the screen or settings'), ex: '@media (min-width: 768px)' },
        { t: 'responsive breakpoint', m: B('المقاس اللي التصميم بيتغيّر عنده', 'the size at which the design changes'), ex: '768px' },
        { t: 'fluid', m: B('بيكبر ويصغر بسلاسة مع الشاشة', 'growing and shrinking smoothly with the screen'), ex: 'clamp(1rem, 4vw, 2rem)' },
        { t: 'tap target', m: B('المساحة اللي الإصبع بيدوس عليها', 'the area a finger presses'), ex: 'at least 44px' },
        { t: 'horizontal scroll', m: B('سحب الصفحة جنب (عيب على الموبايل)', 'dragging the page sideways (a flaw on phones)'), ex: 'overflow-x' }
      ],
      read: [{ lib: 'MDN: CSS layout', what: B('Responsive design وMedia query fundamentals.', 'Responsive design and Media query fundamentals.') },
        { lib: 'web.dev: Learn CSS', what: B('Media queries وSizing units (clamp وmin وmax).', 'Media queries and Sizing units (clamp, min and max).') }],
      challenge: B('خد صفحة الهبوط بتاعتك وخليها متجاوبة بالكامل mobile-first: نقطتين تحول بس، وعناوين ومسافات بـ clamp، وكروت بـ auto-fit، وجدول بيتسحب جوه صندوقه، وأزرار 44px، وصفر سكرول جانبي على 360px — وصوّرها على 3 مقاسات.', 'Make your landing page fully responsive, mobile-first: only two breakpoints, headings and spacing with clamp, cards with auto-fit, a table that scrolls inside its box, 44px buttons and zero sideways scroll at 360px — with screenshots at 3 sizes.'),
      quiz: [
        { q: B('mobile-first يعني media queries بـ:', 'Mobile-first means media queries with:'), o: ['min-width', 'max-width', 'device-name'], a: 0, why: B('بتزوّد للشاشات الأكبر.', 'You add for larger screens.') },
        { q: B('نقط التحول تتحدد حسب:', 'Breakpoints are set by:'), o: [B('المحتوى لما يتكسر', 'where the content breaks'), B('أسماء الأجهزة', 'device names'), B('رقم عشوائي', 'a random number')], a: 0, why: B('الأجهزة بتتغيّر.', 'Devices keep changing.') },
        { q: B('`clamp(1rem, 4vw, 2rem)`:', '`clamp(1rem, 4vw, 2rem)`:'), o: [B('بين 1rem و2rem حسب الشاشة', 'between 1rem and 2rem depending on the screen'), B('دايمًا 4vw', 'always 4vw'), B('دايمًا 1rem', 'always 1rem')], a: 0, why: B('حد أدنى وأقصى.', 'A minimum and maximum.') },
        { q: B('رابط طويل بيعمل سكرول جانبي، الحل:', 'A long link causing sideways scroll — the fix:'), o: ['overflow-wrap: anywhere', 'font-size: 0', 'position: fixed'], a: 0, why: B('بيكسر السطر.', 'It lets the line break.') }
      ] },

    { title: B('مشروع: لوحة متجاوبة كاملة', 'A project: a complete responsive dashboard'),
      goal: B('تجمع Flex وGrid وposition وmedia queries في لوحة حقيقية بتشتغل على كل الشاشات وبالعربي والإنجليزي ووضعين ألوان.', 'Combine Flex, Grid, position and media queries into a real dashboard working on every screen, in Arabic and English, in two colour modes.'),
      learn: [
        { h: B('ارسم الأول بالمربعات', 'Sketch it in boxes first'),
          p: B('قبل الكود، ارسم على ورقة (أو في تعليق) التخطيط على **الموبايل** والشاشة الكبيرة كمربعات بأسماء: header، أرقام، رسم، جدول، فلاتر. ده بيقولك على طول: هيكل الصفحة Grid بـ areas، وكل مربع جواه Flex لعناصره. القرار ده بياخد 5 دقايق وبيوفّر ساعة.',
            'Before the code, sketch on paper (or in a comment) the layout on **phone** and big screen as named boxes: header, numbers, chart, table, filters. That tells you at once: the page skeleton is Grid with areas, and each box uses Flex for its items. A five-minute decision that saves an hour.'),
          ex: '/* phone                 desktop\n   ┌──────────┐          ┌──────────────────────┐\n   │ header   │          │ header               │\n   ├──────────┤          ├──────┬───────────────┤\n   │ numbers  │          │      │ numbers       │\n   ├──────────┤          │ side ├───────────────┤\n   │ table    │          │      │ table         │\n   ├──────────┤          ├──────┴───────────────┤\n   │ filters  │          │ footer               │\n   └──────────┘          └──────────────────────┘ */', show: 1, lang: 'text' },
        { h: B('الهيكل بـ Grid areas', 'The skeleton with Grid areas'),
          p: B('على الموبايل عمود واحد بالترتيب المهم للمستخدم (الأرقام قبل الفلاتر)، ومن 900px عمودين بـ `grid-template-areas`. خلي الـ header جواه flex بـ space-between، والفلاتر الجانبية sticky على الشاشة الكبيرة. كل الألوان من متغيرات، وكل المسافات منطقية.',
            'On phones one column in the order that matters to the user (numbers before filters), and from 900px two columns with `grid-template-areas`. Give the header an inner flex with space-between, and make the side filters sticky on big screens. All colours from variables, all spacing logical.'),
          ex: '<style>\n  :root { --bg: #f8fafc; --surface: #fff; --border: #e5e7eb; --brand: #1f6f4a; --text: #1f2937; }\n  .dash { display: grid; gap: 10px; grid-template-areas: "head" "nums" "table" "side"; color: var(--text); }\n  @media (min-width: 560px) { .dash { grid-template-columns: 150px 1fr; grid-template-areas: "head head" "side nums" "side table"; } }\n  .dash > * { background: var(--surface); border: 1px solid var(--border); border-radius: 10px; padding: 10px; }\n  .head { grid-area: head; display: flex; justify-content: space-between; align-items: center; }\n  .side { grid-area: side; align-self: start; }\n  .nums { grid-area: nums; }\n  .table { grid-area: table; }\n</style>\n<div class="dash"><header class="head"><strong>Orders</strong><button>Export</button></header><aside class="side">Filters</aside><section class="nums">Numbers</section><section class="table">Table</section></div>', run: 'html' },
        { h: B('كروت الأرقام', 'The number cards'),
          p: B('شبكة جوه شبكة: `repeat(auto-fit, minmax(130px, 1fr))` لـ 4 كروت (الإيراد، الطلبات، المتوسط، المرتجع). كل كارت: عنوان صغير رمادي، ورقم كبير بـ clamp، وسهم التغيير بلون **وأيقونة** (↑ أخضر، ↓ أحمر). الأرقام بـ `font-variant-numeric: tabular-nums` عشان الخانات تتساوى.',
            'A grid inside the grid: `repeat(auto-fit, minmax(130px, 1fr))` for 4 cards (revenue, orders, average, refunds). Each card: a small grey label, a big number with clamp, and the change arrow in colour **and icon** (↑ green, ↓ red). Numbers use `font-variant-numeric: tabular-nums` so the digits line up.'),
          ex: '<style>\n  .nums { display: grid; grid-template-columns: repeat(auto-fit, minmax(120px, 1fr)); gap: 8px; }\n  .kpi { border: 1px solid #e5e7eb; border-radius: 10px; padding: 10px; background: #fff; }\n  .kpi small { color: #4b5563; display: block; }\n  .kpi b { font-size: clamp(1.2rem, 4vw, 1.7rem); font-variant-numeric: tabular-nums; }\n  .up { color: #047857; } .down { color: #b91c1c; }\n</style>\n<div class="nums">\n  <div class="kpi"><small>Revenue</small><b>205,800</b><div class="up">↑ 12%</div></div>\n  <div class="kpi"><small>Orders</small><b>67</b><div class="up">↑ 5%</div></div>\n  <div class="kpi"><small>Average</small><b>3,072</b><div class="down">↓ 3%</div></div>\n  <div class="kpi"><small>Refunds</small><b>2</b><div class="up">↓ 1 (good)</div></div>\n</div>', run: 'html' },
        { h: B('الجدول على الموبايل', 'The table on phones'),
          p: B('الجدول العريض على الموبايل حلّين: (1) صندوق `overflow-x: auto` بـ عنوان لازق (أبسط)، أو (2) يتحوّل **كروت**: كل صف كارت وكل خانة سطر «العنوان: القيمة» بـ `display: block` وCSS `content: attr(data-label)`. الحل التاني أحلى للعميل بس محتاج data-label على كل خانة.',
            'A wide table on phones has two solutions: (1) an `overflow-x: auto` box with a sticky heading (simplest), or (2) turning it into **cards**: each row a card and each cell a «label: value» line, using `display: block` and CSS `content: attr(data-label)`. The second looks nicer to the customer but needs a data-label on every cell.'),
          ex: '<style>\n  .t { width: 100%; border-collapse: collapse; }\n  .t th, .t td { padding: 6px 8px; border-block-end: 1px solid #e5e7eb; text-align: start; }\n  @media (max-width: 520px) {\n    .t thead { display: none; }\n    .t tr { display: block; border: 1px solid #e5e7eb; border-radius: 8px; margin-block-end: 8px; padding: 4px; }\n    .t td { display: flex; justify-content: space-between; border: 0; }\n    .t td::before { content: attr(data-label); font-weight: 600; color: #4b5563; }\n  }\n</style>\n<table class="t">\n  <thead><tr><th>#</th><th>Customer</th><th>City</th><th>Total</th></tr></thead>\n  <tbody>\n    <tr><td data-label="#">1001</td><td data-label="Customer">Sara</td><td data-label="City">Cairo</td><td data-label="Total">300</td></tr>\n    <tr><td data-label="#">1002</td><td data-label="Customer">Omar</td><td data-label="City">Giza</td><td data-label="Total">1,800</td></tr>\n  </tbody>\n</table>\n<p>Narrow the frame below 520px: rows become cards.</p>', run: 'html' },
        { h: B('اختبر قبل ما تسلّم', 'Test before you deliver'),
          p: B('قايمة الفحص: (1) 360px و768px و1280px من غير سكرول جانبي، (2) `dir="rtl"` و`dir="ltr"` من غير ما حاجة تتقلب غلط، (3) الوضع الليلي، (4) الكيبورد بس (Tab)، (5) Lighthouse Accessibility، (6) تكبير الخط 200% في المتصفح والصفحة لسه بتتقري. اكتب النتيجة جنب كل بند — ده اللي بيفرّق شغل المحترف.',
            'The checklist: (1) 360px, 768px and 1280px with no sideways scroll, (2) `dir="rtl"` and `dir="ltr"` without anything flipping wrongly, (3) dark mode, (4) keyboard only (Tab), (5) Lighthouse Accessibility, (6) browser zoom at 200% with the page still readable. Write the result next to each item — that is what sets professional work apart.'),
          ex: '☐ 360px · 768px · 1280px — no sideways scroll\n☐ dir="rtl" and dir="ltr" — nothing flipped wrongly\n☐ dark mode — every text ≥ 4.5 : 1\n☐ keyboard only — every control reachable, focus visible\n☐ Lighthouse Accessibility ≥ 95\n☐ browser zoom 200% — still readable', show: 1, lang: 'text' }
      ],
      practice: [
        B('ارسم تخطيط لوحتك للموبايل والشاشة الكبيرة كمربعات.', 'Sketch your dashboard layout for phone and big screen as boxes.'),
        B('اكتب الهيكل بـ grid-template-areas بترتيبين.', 'Write the skeleton with grid-template-areas in two arrangements.'),
        B('اعمل 4 كروت أرقام بـ auto-fit وأيقونات تغيير.', 'Make 4 number cards with auto-fit and change icons.'),
        B('حوّل جدول لكروت على الموبايل بـ data-label.', 'Turn a table into cards on phones with data-label.'),
        B('اعمل الوضع الليلي بالمتغيرات وجرّبه.', 'Build dark mode with the variables and try it.'),
        B('عدّي على قايمة الفحص الست واكتب النتيجة.', 'Go through the six-item checklist and write down the results.')
      ],
      code: [
        { u: B('هيكل اللوحة', 'The dashboard skeleton'), p: '.dash { display: grid; gap: 1rem; padding: 1rem; grid-template-areas: "head" "nums" "chart" "table" "side"; }\n@media (min-width: 56rem) {\n  .dash { grid-template-columns: 15rem 1fr; grid-template-areas: "head head" "side nums" "side chart" "side table"; }\n  .side { position: sticky; top: 1rem; align-self: start; }\n}', lang: 'css', show: 1 }
      ],
      words: [
        { t: 'wireframe', m: B('رسم مبسّط للتخطيط بالمربعات', 'a simple box sketch of a layout'), ex: 'sketch the wireframe first' },
        { t: 'KPI', m: B('مؤشر أداء رئيسي: رقم مهم في لوحة', 'a key performance indicator: an important number on a dashboard'), ex: 'revenue, orders' },
        { t: 'tabular numbers', m: B('أرقام بعرض متساوي عشان الخانات تتساوى', 'equal-width digits so columns line up'), ex: 'font-variant-numeric: tabular-nums' },
        { t: 'data attribute', m: B('خاصية data-* تخزّن معلومة في عنصر', 'a data-* attribute storing information on an element'), ex: 'data-label="Total"' },
        { t: 'dark mode', m: B('ألوان غامقة حسب إعداد المستخدم', 'dark colours following the user’s setting'), ex: 'prefers-color-scheme: dark' },
        { t: 'checklist', m: B('قايمة بنود تتأكد منها قبل التسليم', 'a list of items to check before delivery'), ex: 'the release checklist' },
        { t: 'zoom', m: B('تكبير الصفحة أو الخط', 'enlarging the page or text'), ex: 'browser zoom 200%' }
      ],
      read: [{ lib: 'Every Layout', what: B('اقرا المقالات المجانية في Rudiments (Boxes وComposition).', 'Read the free Rudiments articles (Boxes and Composition).') },
        { lib: 'Frontend Mentor', what: B('اختار تحدي مجاني Newbie فيه تخطيط واعمله.', 'Pick a free Newbie challenge with a layout and build it.') }],
      challenge: B('اعمل نسخة كاملة من «لوحة متابعة الطلبات»: header لازق، وفلاتر جانبية sticky، و4 كروت أرقام، ومكان رسم بياني (صندوق بنسبة 16:9 بـ aspect-ratio)، وجدول بيتحوّل كروت على الموبايل، وزرار تصدير عائم على الموبايل بس — وتعدّي قايمة الفحص الست كلها، ومن غير ولا سطر JavaScript.', 'Build a complete «order tracking dashboard»: a sticky header, sticky side filters, 4 number cards, a chart area (a 16:9 box using aspect-ratio), a table turning into cards on phones, and a floating export button on phones only — passing all six checklist items, with not a single line of JavaScript.'),
      quiz: [
        { q: B('هيكل اللوحة الأنسب:', 'The best fit for the dashboard skeleton:'), o: [B('Grid بـ areas', 'Grid with areas'), B('position absolute', 'position absolute'), B('جدول', 'a table')], a: 0, why: B('بعدين ومرسوم بالأسماء.', 'Two dimensions, drawn by name.') },
        { q: B('ترتيب الموبايل يتحدد حسب:', 'The phone order is set by:'), o: [B('أهمية المحتوى للمستخدم', 'how much the content matters to the user'), B('ترتيب الكود بس', 'the code order alone'), B('الحجم', 'size')], a: 0, why: B('الأهم الأول.', 'The most important first.') },
        { q: B('سهم التغيير لازم يبقى:', 'The change arrow must be:'), o: [B('لون وأيقونة', 'colour and an icon'), B('لون بس', 'colour only'), B('مخفي', 'hidden')], a: 0, why: B('متعتمدش على اللون بس.', 'Never colour alone.') },
        { q: B('جدول عريض على الموبايل:', 'A wide table on phones:'), o: [B('scroll في صندوقه أو يتحوّل كروت', 'scroll in its box, or turn into cards'), B('صغّر الخط لـ 8px', 'shrink the text to 8px'), B('امسحه', 'delete it')], a: 0, why: B('من غير سكرول للصفحة.', 'No page scroll.') }
      ] },

    { title: B('مراجعة ومشروع واختبار الأسبوع', 'Review, project and weekly test'),
      goal: B('تراجع التخطيط كله وتسلّم صفحة متجاوبة احترافية، وتعدّي اختبار الأسبوع.', 'Review all of layout, deliver a professional responsive page, and pass the weekly test.'),
      review: [
        B('Flex لبعد واحد: gap وjustify-content (المحور الأساسي) وalign-items (التاني) وwrap.', 'Flex for one dimension: gap, justify-content (main axis), align-items (cross axis) and wrap.'),
        B('flex: 1 ياخد المكان، وflex-shrink: 0 ميصغرش، وmargin-inline-start: auto يزق للطرف.', 'flex: 1 takes the space, flex-shrink: 0 never shrinks, margin-inline-start: auto pushes to the edge.'),
        B('Grid لبعدين: fr وrepeat وgap، والسطر السحري auto-fit + minmax.', 'Grid for two dimensions: fr, repeat and gap, plus the magic auto-fit + minmax line.'),
        B('span و1 / -1 وgrid-template-areas بالأسماء.', 'span, 1 / -1 and named grid-template-areas.'),
        B('relative + absolute للبادجات، sticky للـ header، fixed للعائم، وz-index بمقياس.', 'relative + absolute for badges, sticky for headers, fixed for floating items, z-index on a scale.'),
        B('overflow وobject-fit: cover للصور المتساوية.', 'overflow, and object-fit: cover for equal images.'),
        B('mobile-first بـ min-width، ونقط تحول حسب المحتوى، وclamp وmin() للسيولة.', 'Mobile-first with min-width, breakpoints set by content, clamp and min() for fluidity.'),
        B('صفر سكرول جانبي، وأزرار 44px، وخط 16px، واختبار على مقاسات حقيقية.', 'Zero sideways scroll, 44px buttons, 16px text, and testing at real sizes.')
      ],
      project: B('**مشروع الأسبوع: موقع متجر صغير متجاوب (HTML + CSS بس).** 3 صفحات بنفس الـ header والـ footer:\n1. **الرئيسية:** header لازق بـ flex (لوجو وبحث بيملا وقايمة وسلة)، وhero بصورة وطبقة وعنوان clamp، وشبكة منتجات auto-fit بكروت (صورة object-fit وبادج absolute وسعر وزرار)، وقسم «ليه احنا» 3 أعمدة بتبقى عمود على الموبايل.\n2. **صفحة منتج:** صورة كبيرة وتفاصيل جنبها (Grid عمودين ← عمود)، ومواصفات، وزرار «أضف للسلة» لازق تحت على الموبايل بس.\n3. **صفحة الطلبات:** لوحة بـ grid areas وكروت أرقام وجدول بيتحوّل كروت.\n4. ملف CSS واحد بالطبقات، ومتغيرات ألوان بوضع ليلي، وخصايص منطقية في كل حتة.\n5. تعدّي قايمة الفحص الست، وتشتغل بالعربي، ولو غيّرت dir وlang للإنجليزي تشتغل برضه.',
        '**Weekly project: a small responsive shop site (HTML + CSS only).** 3 pages sharing the header and footer:\n1. **Home:** a sticky flex header (logo, search filling the space, menu and basket), a hero with an image, an overlay and a clamp heading, an auto-fit product grid of cards (object-fit image, absolute badge, price and button), and a «why us» section in 3 columns becoming one on phones.\n2. **Product page:** a big image with details beside it (Grid two columns → one), specs, and an «add to basket» button fixed to the bottom on phones only.\n3. **Orders page:** a dashboard with grid areas, number cards and a table turning into cards.\n4. One CSS file in layers, colour variables with dark mode, logical properties everywhere.\n5. Passing the six-item checklist, working in Arabic — and still working if you switch dir and lang to English.'),
      test: [
        { q: B('`display: flex` من غير أي حاجة تانية بيرص الأبناء:', '`display: flex` with nothing else lines the children up:'), o: [B('في صف', 'in a row'), B('في عمود', 'in a column'), B('فوق بعض', 'on top of each other')], a: 0, why: B('row افتراضي.', 'row is the default.') },
        { q: B('في صف flex، `justify-content: center`:', 'In a flex row, `justify-content: center`:'), o: [B('يوسّط أفقي', 'centres horizontally'), B('يوسّط رأسي', 'centres vertically'), B('يلف لسطر جديد', 'wraps to a new line')], a: 0, why: B('المحور الأساسي.', 'The main axis.') },
        { q: B('العناصر تنزل سطر جديد لما المكان يخلص:', 'Items drop to a new line when space runs out with:'), o: ['flex-wrap: wrap', 'flex: 1', 'gap: 1rem'], a: 0, why: B('wrap.', 'wrap.') },
        { q: B('`grid-template-columns: repeat(3, 1fr)`:', '`grid-template-columns: repeat(3, 1fr)`:'), o: [B('3 أعمدة متساوية', '3 equal columns'), B('عمود عرضه 3fr', 'one column 3fr wide'), B('3 صفوف', '3 rows')], a: 0, why: B('repeat.', 'repeat.') },
        { q: B('كارت في Grid ياخد عمودين:', 'A card spanning two Grid columns:'), o: ['grid-column: span 2', 'grid-row: span 2', 'flex: 2'], a: 0, why: B('span على الأعمدة.', 'span across columns.') },
        { q: B('بادج «جديد» على ركن الكارت:', 'A «new» badge on a card corner:'), o: [B('الكارت relative والبادج absolute', 'the card relative, the badge absolute'), B('الاتنين fixed', 'both fixed'), B('البادج sticky', 'the badge sticky')], a: 0, why: B('النمط الأشهر.', 'The classic pattern.') },
        { q: B('`position: sticky` محتاج:', '`position: sticky` needs:'), o: [B('top أو bottom', 'top or bottom'), 'z-index: 9999', B('أب fixed', 'a fixed parent')], a: 0, why: B('عشان يعرف يلزق فين.', 'So it knows where to stick.') },
        { q: B('أحسن ترتيب للـ media queries في mobile-first:', 'The best media query style for mobile-first:'), o: ['@media (min-width: 768px)', '@media (max-width: 768px)', '@media (device: iphone)'], a: 0, why: B('بتزوّد للأكبر.', 'You add for bigger.') },
        { q: B('`width: min(100%, 60rem)`:', '`width: min(100%, 60rem)`:'), o: [B('لحد 60rem ومتعدّيش الشاشة', 'up to 60rem, never wider than the screen'), B('دايمًا 60rem', 'always 60rem'), B('دايمًا 100%', 'always 100%')], a: 0, why: B('الأصغر منهم.', 'The smaller of the two.') },
        { q: B('أقل مقاس زرار مريح للإصبع:', 'The smallest comfortable button for a finger:'), o: ['44px', '20px', '12px'], a: 0, why: B('tap target.', 'A tap target.') },
        { q: B('صورة 1200px في مكان 300px من غير سكرول جانبي:', 'A 1200px image in a 300px space without sideways scroll:'), o: ['max-width: 100%', 'overflow: visible', 'width: 1200px'], a: 0, why: B('تصغر لمكانها.', 'It shrinks to fit.') },
        { q: B('Flex ولا Grid لصف أزرار؟', 'Flex or Grid for a row of buttons?'), o: ['Flex', 'Grid', B('جدول', 'a table')], a: 0, why: B('بعد واحد.', 'One dimension.') }
      ] }
  ]
};
