// JavaScript week 12 — the DOM, events and the month project.
const B = (ar, en) => ({ ar, en });
module.exports = {
  level: B('مبتدئ · مكثّف', 'Beginner · intensive'),
  title: B('الـ DOM والأحداث ومشروع الشهر', 'The DOM, events and the month project'),
  goal: B('تخلي الصفحة تتفاعل: تختار العناصر وتغيّر نصها وكلاساتها وخصايصها بأمان، وتبني عناصر جديدة، وتسمع للأحداث (click وinput وsubmit والكيبورد) بـ delegation، وتقرا الفورمز وتتحقق منها، وتحفظ في localStorage — وتسلّم مشروع الشهر التالت: أداة ويب تفاعلية كاملة بتبعت لـ n8n.',
          'Make pages interactive: select elements and change their text, classes and attributes safely, build new elements, listen to events (click, input, submit, keyboard) with delegation, read and validate forms, and save to localStorage — then deliver the third month’s project: a complete interactive web tool that sends to n8n.'),
  days: [
    { title: B('الـ DOM: الصفحة كشجرة كائنات', 'The DOM: the page as a tree of objects'),
      goal: B('تفهم الـ DOM وتختار أي عنصر بـ querySelector، وتقرا وتغيّر النص والخصايص.', 'Understand the DOM, select any element with querySelector, and read and change text and attributes.'),
      learn: [
        { h: B('الـ DOM إيه', 'What the DOM is'),
          p: B('المتصفح بيحوّل الـ HTML لـ **شجرة كائنات** اسمها الـ DOM (Document Object Model): كل عنصر كائن JS ليه خصايص (نصه، وكلاساته، وأبوه، وأبناؤه). `document` هو جذر الشجرة. لما JS يغيّر الـ DOM، الصفحة بتتحدّث على طول. ده الفرق بين صفحة HTML ثابتة وأداة بتتفاعل.',
            'The browser turns the HTML into a **tree of objects** called the DOM (Document Object Model): each element is a JS object with properties (its text, its classes, its parent, its children). `document` is the root of the tree. When JS changes the DOM, the page updates at once. That is the difference between a static HTML page and a tool that reacts.'),
          ex: 'const h = document.querySelector("h2");\nconsole.log(h.tagName, h.textContent, h.parentElement.tagName);\nconsole.log("children of the list:", document.querySelector("ul").children.length);\nh.textContent = "Changed by the DOM ✓";\nconsole.log(document.querySelector("h2").textContent);', run: 'js', html: '<h2>Original heading</h2><ul><li>One</li><li>Two</li><li>Three</li></ul>' },
        { h: B('querySelector وquerySelectorAll', 'querySelector and querySelectorAll'),
          p: B('`document.querySelector(selector)` بيرجّع **أول** عنصر مطابق لمحدد CSS (أي محدد اتعلمته الأسبوعين اللي فاتوا)، أو `null` لو ملقاش. `querySelectorAll` بيرجّع **كل** المطابقين في NodeList (تلف عليها بـ for...of أو forEach، أو تحوّلها مصفوفة بـ `[...list]` عشان map وfilter). وتقدر تدوّر جوه عنصر: `card.querySelector(".price")`.',
            '`document.querySelector(selector)` returns the **first** element matching a CSS selector (any selector from the last two weeks), or `null` when nothing matches. `querySelectorAll` returns **all** matches in a NodeList (loop with for...of or forEach, or turn it into an array with `[...list]` for map and filter). You can search inside an element: `card.querySelector(".price")`.'),
          ex: 'const first = document.querySelector(".price");\nconst all = document.querySelectorAll(".card .price");\nconsole.log(first.textContent, all.length);\nconst total = [...all].map(el => Number(el.textContent)).reduce((s, n) => s + n, 0);\nconsole.log("total", total);\nconsole.log(document.querySelector(".nothing"));', run: 'js', html: '<div class="card">Notebook <span class="price">45</span></div><div class="card">Pen <span class="price">30</span></div><div class="card">Bag <span class="price">650</span></div>' },
        { h: B('textContent وinnerHTML', 'textContent and innerHTML'),
          p: B('`el.textContent = "..."` بيحط **نص** — آمن دايمًا، حتى لو النص فيه `<script>`. `el.innerHTML = "..."` بيفسّر النص كـ **HTML** — مفيد لـ HTML انت كاتبه، بس **خطر** مع أي بيانات من برّه (اسم عميل، رسالة، رد API): ممكن يحقن كود (XSS). القاعدة: بيانات من برّه ← textContent أو esc، ودايمًا.',
            '`el.textContent = "..."` inserts **text** — always safe, even if the text contains `<script>`. `el.innerHTML = "..."` interprets the text as **HTML** — useful for HTML you wrote, but **dangerous** with any outside data (a customer’s name, a message, an API reply): it can inject code (XSS). The rule: outside data → textContent or esc, always.'),
          ex: 'const name = "<img src=x onerror=alert(1)> Sara";\ndocument.querySelector("#safe").textContent = "Hello " + name;\ndocument.querySelector("#html").innerHTML = "<strong>Bold</strong> text I wrote myself";\nconsole.log("images injected:", document.querySelectorAll("img").length);\nconsole.log(document.querySelector("#safe").textContent);', run: 'js', html: '<p id="safe"></p><p id="html"></p>' },
        { h: B('الخصايص والـ dataset', 'Attributes and dataset'),
          p: B('`el.getAttribute("href")` و`el.setAttribute("aria-expanded", "true")` و`el.removeAttribute("disabled")`. لأغلب الخصايص فيه اختصار: `input.value` و`link.href` و`img.src` و`btn.disabled = true` و`input.checked`. وخصايص `data-*` في `el.dataset`: `<button data-order-id="77">` ← `btn.dataset.orderId` (camelCase). ده المكان اللي تخزّن فيه id العنصر عشان الأحداث.',
            '`el.getAttribute("href")`, `el.setAttribute("aria-expanded", "true")` and `el.removeAttribute("disabled")`. Most attributes have shortcuts: `input.value`, `link.href`, `img.src`, `btn.disabled = true` and `input.checked`. And `data-*` attributes live in `el.dataset`: `<button data-order-id="77">` → `btn.dataset.orderId` (camelCase). That is where you keep an element’s id for events.'),
          ex: 'const btn = document.querySelector("button");\nconsole.log(btn.dataset.orderId, btn.dataset.status);\nbtn.dataset.status = "shipped";\nbtn.disabled = true;\nbtn.setAttribute("aria-label", "Order 77, shipped");\nconsole.log(btn.outerHTML);\nconst link = document.querySelector("a");\nconsole.log(link.getAttribute("href"), link.href);', run: 'js', html: '<button data-order-id="77" data-status="paid">Ship order 77</button> <a href="orders.html">Orders</a>' },
        { h: B('التنقل في الشجرة', 'Moving around the tree'),
          p: B('من أي عنصر: `el.parentElement` (الأب)، و`el.children` (الأبناء)، و`el.nextElementSibling`/`previousElementSibling` (الإخوات)، والأهم **`el.closest(".card")`**: أقرب أب (أو هو نفسه) بيطابق المحدد. هتستخدم closest كل يوم: «دوست على زرار جوه كارت، هات الكارت». و`el.matches(".danger")` بيسأل العنصر بيطابق المحدد ولا لأ.',
            'From any element: `el.parentElement` (the parent), `el.children` (the children), `el.nextElementSibling`/`previousElementSibling` (siblings), and most importantly **`el.closest(".card")`**: the nearest ancestor (or itself) matching the selector. You will use closest every day: «a button inside a card was clicked; get the card». And `el.matches(".danger")` asks whether the element matches a selector.'),
          ex: 'const btn = document.querySelector(".card .remove");\nconst card = btn.closest(".card");\nconsole.log(card.dataset.sku, card.querySelector("h3").textContent);\nconsole.log(card.nextElementSibling?.dataset.sku, card.parentElement.children.length);\nconsole.log(btn.matches(".remove"), btn.closest(".missing"));', run: 'js', html: '<div id="list"><div class="card" data-sku="NB"><h3>Notebook</h3><button class="remove">Remove</button></div><div class="card" data-sku="PN"><h3>Pen</h3><button class="remove">Remove</button></div></div>' }
      ],
      practice: [
        B('اطبع tagName وtextContent وعدد الأبناء لـ 4 عناصر.', 'Print the tagName, textContent and child count of 4 elements.'),
        B('اجمع أسعار 6 كروت من الصفحة بـ querySelectorAll وmap وreduce.', 'Total the prices of 6 cards from the page with querySelectorAll, map and reduce.'),
        B('اعرض اسم فيه وسوم HTML مرة بـ textContent ومرة بـ innerHTML وشوف الفرق (في صفحة تجربة).', 'Show a name containing HTML tags once with textContent and once with innerHTML, and see the difference (on a test page).'),
        B('اقرا وغيّر 3 خصايص data-* و2 aria.', 'Read and change 3 data-* attributes and 2 aria attributes.'),
        B('من زرار جوه كارت هات الكارت بـ closest واقرا بياناته.', 'From a button inside a card, get the card with closest and read its data.'),
        B('افتح Console على موقع حقيقي وعدّ اللينكات والصور بـ querySelectorAll.', 'Open the Console on a real site and count its links and images with querySelectorAll.')
      ],
      code: [
        { u: B('اختصار $ و$$', 'The $ and $$ shortcuts'), p: 'const $ = (sel, root = document) => root.querySelector(sel);\nconst $$ = (sel, root = document) => [...root.querySelectorAll(sel)];\n// $("#total").textContent = "…";   $$(".price").map(el => el.textContent);', lang: 'js', show: 1 }
      ],
      words: [
        { t: 'DOM', m: B('شجرة الكائنات اللي المتصفح بيعملها من الـ HTML', 'the tree of objects the browser builds from HTML'), ex: 'document.querySelector(…)' },
        { t: 'querySelector', m: B('يرجّع أول عنصر بيطابق محدد CSS', 'returns the first element matching a CSS selector'), ex: 'document.querySelector(".price")' },
        { t: 'NodeList', m: B('قايمة عناصر بترجع من querySelectorAll', 'a list of elements returned by querySelectorAll'), ex: '[...nodeList]' },
        { t: 'textContent', m: B('النص اللي جوه العنصر (آمن)', 'the text inside an element (safe)'), ex: 'el.textContent = name' },
        { t: 'innerHTML', m: B('الـ HTML اللي جوه العنصر (خطر مع بيانات برّه)', 'the HTML inside an element (dangerous with outside data)'), ex: 'el.innerHTML = "<b>hi</b>"' },
        { t: 'dataset', m: B('خصايص data-* كمتغيرات على العنصر', 'data-* attributes as properties of the element'), ex: 'btn.dataset.orderId' },
        { t: 'closest', m: B('أقرب أب بيطابق محدد', 'the nearest ancestor matching a selector'), ex: 'btn.closest(".card")' }
      ],
      read: [{ lib: 'MDN: Introduction to the DOM', what: B('الصفحة كلها.', 'The whole page.') },
        { lib: 'javascript.info: Browser: Document, Events, Interfaces', what: B('Document: DOM tree وSearching: getElement*, querySelector* وNode properties.', 'Document: DOM tree, Searching: getElement*, querySelector*, and Node properties.') }],
      challenge: B('اكتب سكربت تشغّله في Console على أي صفحة منتجات (عندك أو على books.toscrape.com) بيطلّع جدول (console.table) بكل منتج: الاسم والسعر كرقم والرابط الكامل وهل متاح — بـ querySelectorAll وclosest وdataset/getAttribute، وفي الآخر المتوسط وأغلى منتج.', 'Write a script to run in the Console on any product page (yours, or books.toscrape.com) that prints a table (console.table) of every product: name, price as a number, full link and availability — using querySelectorAll, closest and dataset/getAttribute, ending with the average and the most expensive product.'),
      quiz: [
        { q: B('`document.querySelector(".x")` لو ملقاش:', '`document.querySelector(".x")` when nothing matches:'), o: ['null', 'undefined', '[]'], a: 0, why: B('افحصه قبل الاستخدام.', 'Check it before use.') },
        { q: B('تحط اسم عميل في الصفحة بأمان:', 'Putting a customer’s name on the page safely:'), o: ['el.textContent = name', 'el.innerHTML = name', 'document.write(name)'], a: 0, why: B('نص مش HTML.', 'Text, not HTML.') },
        { q: B('`<div data-user-id="5">` تقراه بـ:', '`<div data-user-id="5">` is read with:'), o: ['el.dataset.userId', 'el.data.userId', 'el.dataset["user-id"]'], a: 0, why: B('camelCase.', 'camelCase.') },
        { q: B('من زرار جوه كارت للكارت:', 'From a button inside a card to the card:'), o: ['btn.closest(".card")', 'btn.parent(".card")', 'btn.find(".card")'], a: 0, why: B('أقرب أب.', 'The nearest ancestor.') }
      ] },

    { title: B('تغيير الصفحة: كلاسات وعناصر جديدة', 'Changing the page: classes and new elements'),
      goal: B('تغيّر الشكل بالكلاسات (مش بـ style)، وتبني عناصر جديدة وتضيفها وتشيلها، وترسم قايمة من بيانات.', 'Change the look with classes (not style), build, add and remove new elements, and render a list from data.'),
      learn: [
        { h: B('classList: الشكل في CSS والقرار في JS', 'classList: looks in CSS, decisions in JS'),
          p: B('بدل `el.style.color = "red"`، خلي CSS فيه `.error { color: red; }` وJS يقرر بس: `el.classList.add("error")` و`remove` و`toggle("open")` (يحط لو مش موجود ويشيل لو موجود) و`toggle("active", condition)` و`contains("open")`. كده الشكل كله في مكان واحد، وتقدر تغيّره من غير ما تلمس JS. `el.style` بس للقيم اللي بتتحسب (عرض شريط تقدّم بالنسبة).',
            'Instead of `el.style.color = "red"`, keep `.error { color: red; }` in CSS and let JS only decide: `el.classList.add("error")`, `remove`, `toggle("open")` (adds if missing, removes if present), `toggle("active", condition)` and `contains("open")`. That way all the looks live in one place and can change without touching JS. Use `el.style` only for computed values (a progress bar’s width as a percentage).'),
          ex: '<style>.box{padding:8px;border:1px solid #ddd;border-radius:6px;margin:4px 0}.ok{background:#ecfdf5;border-color:#10b981}.error{background:#fef2f2;border-color:#ef4444}</style>\n<div class="box" id="msg">Status</div><div style="background:#e5e7eb;border-radius:6px"><div id="bar" style="background:#10b981;height:10px;border-radius:6px;width:0"></div></div>\n<script>\n  const msg = document.querySelector("#msg");\n  msg.classList.add("ok");\n  msg.textContent = "Saved ✓";\n  console.log(msg.classList.contains("ok"));\n  msg.classList.toggle("ok"); msg.classList.toggle("error", true); msg.textContent = "Failed ✗";\n  document.querySelector("#bar").style.width = "65%";\n  console.log(msg.className);\n</script>', run: 'html' },
        { h: B('createElement: ابني عنصر', 'createElement: building an element'),
          p: B('`const li = document.createElement("li");` بيعمل عنصر جديد (لسه مش في الصفحة). اديله نص بـ `textContent` وكلاس وdataset، وبعدين حطه: `list.append(li)` (في الآخر) أو `prepend` (في الأول) أو `before`/`after`. الطريقة دي **آمنة تمامًا** مع بيانات من برّه لأن كل حاجة نص. للقوايم الكبيرة، ابني في `DocumentFragment` وحطه مرة واحدة.',
            '`const li = document.createElement("li");` makes a new element (not yet on the page). Give it text with `textContent`, a class and dataset, then insert it: `list.append(li)` (at the end), `prepend` (at the start), or `before`/`after`. This way is **completely safe** with outside data because everything is text. For big lists, build in a `DocumentFragment` and insert once.'),
          ex: 'const orders = [{ id: 101, customer: "Sara", total: 300 }, { id: 102, customer: "<b>Omar</b>", total: 1800 }];\nconst list = document.querySelector("#orders");\nconst frag = document.createDocumentFragment();\nfor (const o of orders) {\n  const li = document.createElement("li");\n  li.dataset.id = o.id;\n  li.textContent = `#${o.id} ${o.customer} — ${o.total} EGP`;\n  if (o.total > 1000) li.classList.add("big");\n  frag.append(li);\n}\nlist.append(frag);\nconsole.log(list.children.length, list.lastElementChild.textContent);', run: 'js', html: '<style>.big{font-weight:700;color:#047857}</style><ul id="orders"></ul>' },
        { h: B('remove وreplaceChildren', 'remove and replaceChildren'),
          p: B('`el.remove()` بيشيل العنصر. `list.replaceChildren()` بيفضّي القايمة، و`list.replaceChildren(...newItems)` بيبدّل كل الأبناء مرة واحدة. ده أنضف من `innerHTML = ""`. والنمط: لما البيانات تتغيّر، **ارسم القايمة من جديد** من البيانات (زي render في الأسبوع 7) بدل ما تعدّل عنصر عنصر — أبسط وأقل أخطاء.',
            '`el.remove()` removes the element. `list.replaceChildren()` empties the list, and `list.replaceChildren(...newItems)` replaces every child at once. Cleaner than `innerHTML = ""`. The pattern: when data changes, **redraw the list** from the data (like week 7’s render) rather than editing element by element — simpler and fewer bugs.'),
          ex: 'let items = ["Notebook", "Pen", "Bag"];\nconst ul = document.querySelector("ul");\nfunction render() {\n  ul.replaceChildren(...items.map(name => { const li = document.createElement("li"); li.textContent = name; return li; }));\n}\nrender();\nconsole.log(ul.children.length);\nitems = items.filter(n => n !== "Pen");\nrender();\nconsole.log([...ul.children].map(li => li.textContent));\nul.firstElementChild.remove();\nconsole.log(ul.children.length);', run: 'js', html: '<ul></ul>' },
        { h: B('القوالب: <template>', 'Templates: <template>'),
          p: B('لكارت معقد (صورة وعنوان وسعر وزرار)، createElement لكل جزء بيبقى طويل. اكتب الشكل مرة في `<template>` في الـ HTML (مش بيظهر)، وفي JS: `const node = tpl.content.cloneNode(true);` واملا الأجزاء بـ querySelector وtextContent. أمان createElement وسهولة HTML مع بعض.',
            'For a complex card (image, title, price and button), createElement for every part gets long. Write the shape once in a `<template>` in the HTML (it is not displayed), and in JS: `const node = tpl.content.cloneNode(true);` then fill the parts with querySelector and textContent. The safety of createElement with the ease of HTML.'),
          ex: 'const products = [{ sku: "NB", name: "Notebook", price: 45 }, { sku: "BG", name: "Backpack", price: 650 }];\nconst tpl = document.querySelector("#card");\nconst grid = document.querySelector("#grid");\nfor (const p of products) {\n  const node = tpl.content.cloneNode(true);\n  node.querySelector(".card").dataset.sku = p.sku;\n  node.querySelector("h3").textContent = p.name;\n  node.querySelector(".price").textContent = p.price + " EGP";\n  grid.append(node);\n}\nconsole.log(grid.querySelectorAll(".card").length, grid.textContent.replace(/\\s+/g, " ").trim());', run: 'js',
          html: '<template id="card"><article class="card" style="border:1px solid #ddd;padding:8px;border-radius:8px;margin:4px 0"><h3></h3><p class="price"></p><button>Add</button></article></template><div id="grid"></div>' },
        { h: B('insertAdjacentHTML وأمانه', 'insertAdjacentHTML and its safety'),
          p: B('هتشوف كتير `el.insertAdjacentHTML("beforeend", `<li>${name}</li>`)` و`innerHTML +=`. سريعين بس **نفس خطر innerHTML**: أي `${...}` فيه بيانات من برّه لازم يعدّي على `esc()`. وكمان `innerHTML +=` بيعيد بناء كل اللي جوه وبيضيّع الأحداث والحالة. القاعدة: HTML ثابت انت كاتبه ← innerHTML تمام؛ أي بيانات ← createElement/template أو esc.',
            'You will often see `el.insertAdjacentHTML("beforeend", `<li>${name}</li>`)` and `innerHTML +=`. They are fast but carry **innerHTML’s danger**: any `${...}` holding outside data must go through `esc()`. And `innerHTML +=` rebuilds everything inside, losing events and state. The rule: fixed HTML you wrote → innerHTML is fine; any data → createElement/template or esc.'),
          ex: 'const esc = s => String(s ?? "").replace(/[&<>"\']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\\"": "&quot;", "\'": "&#39;" }[c]));\nconst ul = document.querySelector("ul");\nconst names = ["Sara", "<img src=x onerror=alert(1)>"];\nfor (const n of names) ul.insertAdjacentHTML("beforeend", `<li>${esc(n)}</li>`);\nconsole.log(ul.querySelectorAll("img").length, "images injected");\nconsole.log([...ul.children].map(li => li.textContent));', run: 'js', html: '<ul></ul>' }
      ],
      practice: [
        B('اعمل 3 كلاسات حالة في CSS وبدّل بينهم بـ classList.', 'Make 3 status classes in CSS and switch between them with classList.'),
        B('اعمل شريط تقدّم عرضه بيتحسب بـ el.style.', 'Make a progress bar whose width is computed with el.style.'),
        B('ارسم قايمة 10 طلبات بـ createElement وDocumentFragment.', 'Render a list of 10 orders with createElement and a DocumentFragment.'),
        B('اعمل render بيرسم من مصفوفة واستخدمه بعد إضافة ومسح.', 'Write a render that draws from an array, and use it after adding and removing.'),
        B('اعمل كروت منتجات من template.', 'Build product cards from a template.'),
        B('صلّح كود بيستخدم innerHTML += ببيانات عميل.', 'Fix code using innerHTML += with customer data.')
      ],
      code: [
        { u: B('h: دالة بناء عناصر صغيرة', 'h: a tiny element builder'), p: 'function h(tag, props = {}, ...children) {\n  const el = document.createElement(tag);\n  for (const [k, v] of Object.entries(props)) {\n    if (k === "class") el.className = v;\n    else if (k === "dataset") Object.assign(el.dataset, v);\n    else if (k.startsWith("on")) el.addEventListener(k.slice(2), v);\n    else el.setAttribute(k, v);\n  }\n  el.append(...children);   // strings become safe text nodes\n  return el;\n}\n// list.append(h("li", { class: "big", dataset: { id: 7 } }, "Order 7"));', lang: 'js', show: 1 }
      ],
      words: [
        { t: 'classList', m: B('أدوات تضيف وتشيل وتبدّل كلاسات العنصر', 'tools to add, remove and toggle an element’s classes'), ex: 'el.classList.toggle("open")' },
        { t: 'createElement', m: B('يعمل عنصر HTML جديد من JS', 'makes a new HTML element from JS'), ex: 'document.createElement("li")' },
        { t: 'append', m: B('يضيف عنصر أو نص في آخر الأب', 'adds an element or text at the end of a parent'), ex: 'list.append(li)' },
        { t: 'DocumentFragment', m: B('صندوق مؤقت تبني فيه عناصر وتحطهم مرة واحدة', 'a temporary box to build elements in and insert once'), ex: 'createDocumentFragment()' },
        { t: 'template element', m: B('شكل HTML مخفي بتنسخ منه عناصر', 'a hidden HTML shape you clone elements from'), ex: '<template id="card">' },
        { t: 'clone', m: B('نسخة من عنصر', 'a copy of an element'), ex: 'tpl.content.cloneNode(true)' },
        { t: 're-render', m: B('ترسم الجزء من جديد من البيانات', 'redrawing a part from the data'), ex: 'render() after every change' }
      ],
      read: [{ lib: 'javascript.info: Browser: Document, Events, Interfaces', what: B('Modifying the document وStyles and classes.', 'Modifying the document, and Styles and classes.') },
        { lib: 'MDN: Web APIs', what: B('Element.classList وDocument.createElement() وHTMLTemplateElement.', 'Element.classList, Document.createElement() and HTMLTemplateElement.') }],
      challenge: B('اعمل «قايمة مهام» بتعرض مهام من مصفوفة بـ template: كل مهمة فيها اسم وأولوية (كلاس لون حسبها) وتاريخ، ومهام متأخرة ليها كلاس خاص، وفوقها عدّاد «فاضل X» — وكل تغيير في المصفوفة بينادي render اللي بيستخدم replaceChildren، ومفيش innerHTML ببيانات.', 'Build a «to-do list» showing tasks from an array via a template: each task with a name, a priority (a colour class from it) and a date, overdue tasks with a special class, and a «X left» counter above — every change to the array calling a render that uses replaceChildren, with no innerHTML holding data.'),
      quiz: [
        { q: B('تغيّر شكل عنصر لحالة «خطأ» الأحسن:', 'Changing an element to an «error» look is best done with:'), o: ['el.classList.add("error")', 'el.style.color = "red"', 'el.innerHTML = "<font color=red>"'], a: 0, why: B('الشكل في CSS.', 'Looks belong in CSS.') },
        { q: B('`classList.toggle("open")`:', '`classList.toggle("open")`:'), o: [B('يحط لو مش موجود ويشيل لو موجود', 'adds if missing, removes if present'), B('يحط دايمًا', 'always adds'), B('يشيل دايمًا', 'always removes')], a: 0, why: B('تبديل.', 'A toggle.') },
        { q: B('أأمن طريقة تحط بيانات عميل في عنصر جديد:', 'The safest way to put customer data in a new element:'), o: [B('createElement + textContent', 'createElement + textContent'), B('innerHTML += بالبيانات', 'innerHTML += with the data'), 'document.write'], a: 0, why: B('كله نص.', 'All of it is text.') },
        { q: B('`<template>`:', '`<template>`:'), o: [B('مخفي وبتنسخ منه', 'hidden, and you clone from it'), B('بيظهر في الصفحة', 'shows on the page'), B('بيشغّل JS', 'runs JS')], a: 0, why: B('cloneNode.', 'cloneNode.') }
      ] },

    { title: B('الأحداث: click وinput والكيبورد', 'Events: click, input and the keyboard'),
      goal: B('تسمع للأحداث بـ addEventListener، وتقرا كائن الحدث، وتستخدم event delegation لقوايم بتتغيّر، وتتحكم في الكيبورد.', 'Listen to events with addEventListener, read the event object, use event delegation for changing lists, and handle the keyboard.'),
      learn: [
        { h: B('addEventListener', 'addEventListener'),
          p: B('`btn.addEventListener("click", handler)` بينادي handler كل ما الزرار يتداس، وبيبعتله **كائن الحدث** `e`: `e.target` (العنصر اللي اتداس عليه فعلًا)، و`e.type`. أشهر الأحداث: `click` و`input` (مع كل حرف) و`change` (لما القيمة تتأكد) و`submit` و`keydown` و`focus`/`blur`. متستخدمش `onclick="..."` في HTML — افصل JS عن HTML.',
            '`btn.addEventListener("click", handler)` calls handler every time the button is clicked, passing it the **event object** `e`: `e.target` (the element actually clicked) and `e.type`. The most common events: `click`, `input` (every keystroke), `change` (when the value is committed), `submit`, `keydown` and `focus`/`blur`. Avoid `onclick="..."` in HTML — keep JS separate from HTML.'),
          ex: 'const btn = document.querySelector("#add");\nconst count = document.querySelector("#count");\nlet n = 0;\nbtn.addEventListener("click", e => {\n  n++;\n  count.textContent = n;\n  console.log("clicked", e.type, e.target.id);\n});\nbtn.click(); btn.click();\nconst q = document.querySelector("#q");\nq.addEventListener("input", e => console.log("typed:", e.target.value));\nq.value = "lap"; q.dispatchEvent(new Event("input"));', run: 'js', html: '<button id="add">Add one</button> <span id="count">0</span><p><input id="q" placeholder="Search"></p>' },
        { h: B('event delegation: مستمع واحد لعناصر كتير', 'Event delegation: one listener for many elements'),
          p: B('بدل مستمع لكل زرار في قايمة (وتنسى تحط مستمع للأزرار الجديدة)، حط **مستمع واحد على الأب** واسأل: `const btn = e.target.closest("button[data-action]"); if (!btn) return;`. الأحداث بتطلع من العنصر لأبوه لحد الـ document (**bubbling**)، فالأب بيسمع كل اللي جواه — حتى العناصر اللي اتعملت بعدين. ده النمط الأساسي لأي قايمة أو جدول.',
            'Instead of a listener per button in a list (and forgetting to add listeners to new buttons), put **one listener on the parent** and ask: `const btn = e.target.closest("button[data-action]"); if (!btn) return;`. Events rise from the element up through its parents to the document (**bubbling**), so the parent hears everything inside — even elements created later. This is the core pattern for any list or table.'),
          ex: 'const list = document.querySelector("#list");\nlist.addEventListener("click", e => {\n  const btn = e.target.closest("button[data-action]");\n  if (!btn) return;\n  const row = btn.closest("li");\n  if (btn.dataset.action === "remove") row.remove();\n  if (btn.dataset.action === "done") row.classList.toggle("done");\n  console.log(btn.dataset.action, row.dataset.id, "→ items left:", list.children.length);\n});\nconst li = document.createElement("li");\nli.dataset.id = "3"; li.append("New task ");\nconst b = document.createElement("button"); b.dataset.action = "remove"; b.textContent = "✕"; li.append(b);\nlist.append(li);\nlist.querySelector(\'[data-id="1"] [data-action="done"]\').click();\nb.click();', run: 'js',
          html: '<style>.done{text-decoration:line-through;color:#9ca3af}</style><ul id="list"><li data-id="1">Call Sara <button data-action="done">✓</button> <button data-action="remove">✕</button></li><li data-id="2">Send invoice <button data-action="done">✓</button> <button data-action="remove">✕</button></li></ul>' },
        { h: B('preventDefault وstopPropagation', 'preventDefault and stopPropagation'),
          p: B('بعض العناصر ليها سلوك افتراضي: الرابط بيفتح صفحة، والفورم بيعيد تحميل الصفحة. `e.preventDefault()` بيمنعه عشان JS يعمل الشغل (fetch بدل إعادة تحميل). و`e.stopPropagation()` بيمنع الحدث يطلع للأب — نادر تحتاجه، ولو استخدمته كتير غالبًا التصميم محتاج delegation أوضح.',
            'Some elements have default behaviour: a link opens a page, a form reloads the page. `e.preventDefault()` stops it so JS can do the work (fetch instead of reload). And `e.stopPropagation()` stops the event rising to the parent — rarely needed; if you use it a lot, the design probably needs clearer delegation.'),
          ex: 'const link = document.querySelector("a");\nlink.addEventListener("click", e => {\n  e.preventDefault();\n  console.log("would load", link.getAttribute("href"), "with fetch instead");\n});\nlink.click();\nconst outer = document.querySelector("#outer");\nouter.addEventListener("click", () => console.log("outer heard it"));\ndocument.querySelector("#inner").addEventListener("click", e => { e.stopPropagation(); console.log("inner only"); });\ndocument.querySelector("#inner").click();', run: 'js', html: '<a href="/orders?page=2">Next page</a><div id="outer" style="padding:8px;background:#f3f4f6">outer <button id="inner">inner</button></div>' },
        { h: B('الكيبورد', 'The keyboard'),
          p: B('`keydown` بيدّيك `e.key` (`"Enter"` و`"Escape"` و`"ArrowDown"` و`"a"`) و`e.ctrlKey`/`e.metaKey`/`e.shiftKey`. استخدمه لاختصارات (Ctrl+K للبحث، Escape يقفل نافذة، الأسهم في قايمة). متكسرش اختصارات المتصفح، ومتعملش اختصار بيشتغل والمستخدم بيكتب في حقل (افحص `e.target.matches("input, textarea")`). ولأي زرار حقيقي Enter وSpace شغالين لوحدهم.',
            '`keydown` gives you `e.key` (`"Enter"`, `"Escape"`, `"ArrowDown"`, `"a"`) and `e.ctrlKey`/`e.metaKey`/`e.shiftKey`. Use it for shortcuts (Ctrl+K to search, Escape to close a dialog, arrows in a list). Do not break the browser’s shortcuts, and do not fire a shortcut while the user types in a field (check `e.target.matches("input, textarea")`). Real buttons already work with Enter and Space.'),
          ex: 'const log = [];\ndocument.addEventListener("keydown", e => {\n  if (e.target.matches?.("input, textarea")) return;\n  if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === "k") { e.preventDefault(); log.push("open search"); }\n  if (e.key === "Escape") log.push("close dialog");\n});\ndocument.dispatchEvent(new KeyboardEvent("keydown", { key: "k", ctrlKey: true }));\ndocument.dispatchEvent(new KeyboardEvent("keydown", { key: "Escape" }));\nconsole.log(log);', run: 'js' },
        { h: B('input مع تأخير (debounce)', 'input with a delay (debounce)'),
          p: B('حدث `input` بيشتغل مع **كل حرف**. لو كل حرف بيعمل بحث تقيل أو طلب API، هتبعت 10 طلبات لكلمة واحدة. **debounce**: استنى لما المستخدم يبطّل كتابة 300ms وبعدين اشتغل مرة واحدة. ده closure فيها مؤقّت بيتلغي ويتعمل من جديد مع كل حرف — نفس فكرة الأسبوع 6.',
            'The `input` event fires on **every keystroke**. If each one triggers a heavy search or an API request, you send 10 requests for one word. **Debounce**: wait until the user stops typing for 300ms, then run once. It is a closure holding a timer that is cancelled and restarted on every keystroke — the idea from week 6.'),
          ex: 'function debounce(fn, ms = 300) {\n  let timer;\n  return (...args) => {\n    clearTimeout(timer);\n    timer = setTimeout(() => fn(...args), ms);\n  };\n}\nlet searches = 0;\nconst search = debounce(q => { searches++; console.log("searching for", q, "| searches:", searches); }, 100);\nfor (const q of ["l", "la", "lap", "lapt", "laptop"]) search(q);', run: 'js' }
      ],
      practice: [
        B('اعمل عدّاد بزرارين (+ و−) وزرار مسح.', 'Build a counter with two buttons (+ and −) and a reset.'),
        B('اعمل قايمة بـ delegation فيها «تم» و«مسح» وزرار يضيف عنصر جديد بيشتغل عليه.', 'Build a delegated list with «done» and «remove», plus a button adding a new item that works too.'),
        B('امنع رابط من فتح صفحة واطبع الـ href.', 'Stop a link from opening a page and print its href.'),
        B('اعمل اختصار Ctrl+K يركّز على خانة بحث وEscape يفضّيها.', 'Make a Ctrl+K shortcut that focuses a search box and Escape to clear it.'),
        B('اعمل بحث مباشر في قايمة بـ input وdebounce.', 'Build a live list search with input and debounce.'),
        B('شوف الأحداث في DevTools: Elements ← Event Listeners.', 'Inspect the events in DevTools: Elements → Event Listeners.')
      ],
      code: [
        { u: B('نمط القايمة التفاعلية', 'The interactive list pattern'), p: 'list.addEventListener("click", e => {\n  const btn = e.target.closest("[data-action]");\n  if (!btn || !list.contains(btn)) return;\n  const id = btn.closest("[data-id]")?.dataset.id;\n  actions[btn.dataset.action]?.(id);   // actions = { remove(id) {…}, done(id) {…} }\n  render();\n});', lang: 'js', show: 1 }
      ],
      words: [
        { t: 'event', m: B('حدث في الصفحة (ضغطة، كتابة، إرسال)', 'something happening on the page (a click, typing, a submit)'), ex: '"click"' },
        { t: 'addEventListener', m: B('بيربط دالة بحدث على عنصر', 'attaches a function to an event on an element'), ex: 'btn.addEventListener("click", fn)' },
        { t: 'event object', m: B('الكائن اللي فيه تفاصيل الحدث', 'the object holding the event’s details'), ex: 'e.target, e.key' },
        { t: 'event delegation', m: B('مستمع واحد على الأب لكل اللي جواه', 'one listener on the parent for everything inside'), ex: 'e.target.closest(…)' },
        { t: 'bubbling', m: B('الحدث بيطلع من العنصر لأبوه لحد الـ document', 'an event rising from the element through its parents'), ex: 'the list hears its buttons' },
        { t: 'preventDefault', m: B('يمنع سلوك المتصفح الافتراضي', 'stops the browser’s default behaviour'), ex: 'e.preventDefault()' },
        { t: 'debounce', m: B('تستنى المستخدم يبطّل وبعدين تنفّذ مرة', 'waiting for the user to stop, then running once'), ex: 'debounce(search, 300)' }
      ],
      read: [{ lib: 'MDN: Introduction to events', what: B('الصفحة كلها، وخصوصًا Event bubbling وEvent delegation.', 'The whole page, especially Event bubbling and Event delegation.') },
        { lib: 'javascript.info: Browser: Document, Events, Interfaces', what: B('Introduction to Events: Browser events وBubbling and capturing وEvent delegation.', 'Introduction to Events: Browser events, Bubbling and capturing, and Event delegation.') }],
      challenge: B('اعمل «جدول طلبات تفاعلي»: صفوف من مصفوفة، وأزرار «اشحن» و«إلغاء» و«تفاصيل» بـ delegation على الجدول، وبحث مباشر بـ debounce، وترتيب بالضغط على عنوان العمود، واختصار «/» يركّز على البحث، وEscape يقفل لوحة التفاصيل — وكل تغيير يحدّث المصفوفة وينادي render.', 'Build an «interactive orders table»: rows from an array, «ship», «cancel» and «details» buttons delegated on the table, a live debounced search, sorting by clicking a column title, a «/» shortcut focusing the search, and Escape closing the details panel — every change updating the array and calling render.'),
      quiz: [
        { q: B('العنصر اللي اتداس عليه فعلًا:', 'The element actually clicked:'), o: ['e.target', 'e.type', 'e.key'], a: 0, why: B('target.', 'target.') },
        { q: B('أزرار في قايمة بتتغيّر، الأحسن:', 'Buttons in a changing list — best:'), o: [B('مستمع واحد على الأب', 'one listener on the parent'), B('مستمع لكل زرار', 'a listener per button'), B('onclick في HTML', 'onclick in HTML')], a: 0, why: B('delegation.', 'Delegation.') },
        { q: B('تمنع الفورم من إعادة تحميل الصفحة:', 'Stopping a form from reloading the page:'), o: ['e.preventDefault()', 'e.stopPropagation()', B('return false من غير حاجة', 'return false alone')], a: 0, why: B('السلوك الافتراضي.', 'The default behaviour.') },
        { q: B('بحث بيبعت طلب مع كل حرف، الحل:', 'A search sending a request on every keystroke — the fix:'), o: ['debounce', 'setInterval', B('حدث click', 'a click event')], a: 0, why: B('مرة بعد ما يبطّل.', 'Once, after they stop.') }
      ] },

    { title: B('الفورمز في JS والتخزين في المتصفح', 'Forms in JS, and storage in the browser'),
      goal: B('تقرا الفورم كله بـ FormData، وتتحقق برسايل جنب الحقول، وتحفظ وتسترجع من localStorage بأمان.', 'Read a whole form with FormData, validate with messages beside the fields, and save and restore from localStorage safely.'),
      learn: [
        { h: B('submit وFormData', 'submit and FormData'),
          p: B('اسمع لحدث `submit` على **الفورم** (مش click على الزرار — submit بيشتغل كمان بـ Enter): `form.addEventListener("submit", e => { e.preventDefault(); ... })`. `new FormData(form)` بيقرا كل الحقول اللي ليها name، و`Object.fromEntries(new FormData(form))` بيحوّلهم كائن جاهز تبعته. الـ checkbox اللي مش متعلّم مش بيتبعت خالص — خد بالك.',
            'Listen for `submit` on the **form** (not click on the button — submit also fires on Enter): `form.addEventListener("submit", e => { e.preventDefault(); ... })`. `new FormData(form)` reads every field with a name, and `Object.fromEntries(new FormData(form))` turns them into an object ready to send. An unticked checkbox is not sent at all — watch out.'),
          ex: 'const form = document.querySelector("form");\nform.addEventListener("submit", e => {\n  e.preventDefault();\n  const data = Object.fromEntries(new FormData(form));\n  data.qty = Number(data.qty);\n  data.newsletter = form.elements.newsletter.checked;\n  console.log(JSON.stringify(data));\n});\nform.requestSubmit();', run: 'js',
          html: '<form><input name="name" value="Sara"> <input name="qty" type="number" value="3"> <select name="city"><option>Giza</option></select> <label><input type="checkbox" name="newsletter"> news</label> <button>Send</button></form>' },
        { h: B('التحقق برسايل واضحة', 'Validation with clear messages'),
          p: B('استخدم تحقق المتصفح (required وpattern) وزوّد عليه قواعدك في JS، واعرض الرسالة **جنب الحقل نفسه** بـ `aria-describedby` وكلاس خطأ، ونقّل الـ focus لأول حقل فيه مشكلة. `input.setCustomValidity("...")` بيخلي رسالتك هي رسالة المتصفح، و`form.checkValidity()` بيقول كله سليم ولا لأ. ونضّف الرسالة لما المستخدم يصلّح (حدث input).',
            'Use the browser’s validation (required and pattern) plus your own rules in JS, and show the message **next to the field itself** with `aria-describedby` and an error class, moving focus to the first problem field. `input.setCustomValidity("...")` makes your message the browser’s message, and `form.checkValidity()` says whether all is valid. Clear the message when the user fixes it (the input event).'),
          ex: 'const form = document.querySelector("form");\nconst phone = form.elements.phone, err = document.querySelector("#phone-err");\nfunction check() {\n  const digits = phone.value.replace(/\\D/g, "");\n  const msg = digits.length === 11 && digits.startsWith("01") ? "" : "Write 11 digits starting with 01";\n  phone.setCustomValidity(msg);\n  err.textContent = msg;\n  phone.classList.toggle("invalid", !!msg);\n  return !msg;\n}\nphone.addEventListener("input", check);\nform.addEventListener("submit", e => { e.preventDefault(); if (!check()) { phone.focus(); console.log("blocked:", err.textContent); return; } console.log("ok, sending", phone.value); });\nphone.value = "0101"; form.requestSubmit();\nphone.value = "010-1234-5678"; form.requestSubmit();', run: 'js',
          html: '<style>.invalid{border:2px solid #b91c1c}</style><form><label>Mobile <input name="phone" aria-describedby="phone-err"></label> <span id="phone-err" style="color:#b91c1c"></span> <button>Send</button></form>' },
        { h: B('localStorage: ذاكرة صغيرة في المتصفح', 'localStorage: a small memory in the browser'),
          p: B('`localStorage.setItem("key", text)` و`getItem("key")` و`removeItem`: بيحفظ **نصوص** في المتصفح وبتفضل بعد قفل الصفحة (حوالي 5 ميجا). للكائنات: `JSON.stringify` قبل الحفظ و`JSON.parse` بعد القراية. استخدمه لمسودة فورم، وتفضيلات (الوضع الليلي واللغة)، وسلة بسيطة. **متحطش** فيه كلمات سر أو توكنز حساسة — أي كود على الصفحة يقدر يقراه.',
            '`localStorage.setItem("key", text)`, `getItem("key")` and `removeItem` store **text** in the browser that survives closing the page (about 5 MB). For objects: `JSON.stringify` before saving and `JSON.parse` after reading. Use it for form drafts, preferences (dark mode and language) and a simple basket. **Never** store passwords or sensitive tokens in it — any code on the page can read it.'),
          ex: 'const prefs = { theme: "dark", lang: "ar" };\ntry {\n  localStorage.setItem("prefs", JSON.stringify(prefs));\n  const back = JSON.parse(localStorage.getItem("prefs") ?? "{}");\n  console.log(back.theme, back.lang, typeof localStorage.getItem("prefs"));\n  localStorage.removeItem("prefs");\n  console.log(localStorage.getItem("prefs"));\n} catch (err) {\n  console.log("failed: storage is not available here —", err.name);\n}', run: 'js' },
        { h: B('تخزين آمن ضد الأخطاء', 'Storage that survives errors'),
          p: B('localStorage ممكن **يفشل**: وضع التصفح الخاص، أو المساحة اتملت، أو البيانات القديمة اتلخبطت (JSON بايظ)، أو إطار معزول من غير صلاحية. فحط القراية والكتابة جوه try/catch بقيمة افتراضية، وزوّد **رقم نسخة** للبيانات عشان لو غيّرت الشكل بعدين تعرف تحوّل القديم. الصفحة لازم تشتغل حتى لو التخزين مش متاح.',
            'localStorage can **fail**: private browsing, a full quota, old data that got corrupted (broken JSON), or an isolated frame without permission. So wrap reading and writing in try/catch with a default, and add a **version number** to the data so you can convert old shapes if you change them later. The page must work even when storage is unavailable.'),
          ex: 'const store = {\n  get(key, fallback) {\n    try { const v = JSON.parse(localStorage.getItem(key)); return v ?? fallback; } catch { return fallback; }\n  },\n  set(key, value) {\n    try { localStorage.setItem(key, JSON.stringify(value)); return true; } catch { return false; }\n  }\n};\nconst saved = store.set("cart_v1", { v: 1, items: [{ sku: "NB", qty: 2 }] });\nconsole.log("saved?", saved);\nconsole.log(store.get("cart_v1", { v: 1, items: [] }).items.length);\nconsole.log(store.get("missing_key", "default"));', run: 'js' },
        { h: B('مسودة الفورم ومتضيعش', 'A form draft that never gets lost'),
          p: B('نمط مفيد جدًا للعملاء: احفظ اللي اتكتب في الفورم في localStorage مع كل `input` (بـ debounce)، ولما الصفحة تفتح تاني رجّعه. ولما الإرسال ينجح امسح المسودة. كده لو النت قطع أو الصفحة اتقفلت بالغلط، المستخدم مش هيكتب كل حاجة تاني. متحفظش حقول حساسة (كلمة سر، رقم كارت).',
            'A pattern customers love: save what was typed in the form to localStorage on every `input` (debounced), and restore it when the page opens again. When sending succeeds, clear the draft. That way if the connection drops or the page closes by mistake, the user does not retype everything. Never save sensitive fields (a password, a card number).'),
          ex: 'const form = document.querySelector("form"), KEY = "draft_quote";\nconst safe = { get: k => { try { return JSON.parse(localStorage.getItem(k)) ?? {}; } catch { return {}; } }, set: (k, v) => { try { localStorage.setItem(k, JSON.stringify(v)); } catch {} } };\nfor (const [k, v] of Object.entries(safe.get(KEY))) if (form.elements[k] && k !== "card") form.elements[k].value = v;\nform.addEventListener("input", () => {\n  const { card, ...draft } = Object.fromEntries(new FormData(form));\n  safe.set(KEY, draft);\n});\nform.elements.name.value = "Sara"; form.dispatchEvent(new Event("input", { bubbles: true }));\nconsole.log("draft:", JSON.stringify(safe.get(KEY)));', run: 'js',
          html: '<form><input name="name" placeholder="Name"> <input name="notes" placeholder="Notes"> <input name="card" placeholder="Card (never saved)"></form>' }
      ],
      practice: [
        B('اقرا فورم طلب كامل بـ FormData وحوّل الأرقام وال checkbox صح.', 'Read a full order form with FormData, converting numbers and the checkbox correctly.'),
        B('اعمل تحقق لـ 3 حقول برسايل جنبهم وfocus على أول غلط.', 'Validate 3 fields with messages beside them and focus on the first error.'),
        B('احفظ واسترجع تفضيل «الوضع الليلي» من localStorage.', 'Save and restore a «dark mode» preference from localStorage.'),
        B('اعمل store.get/set بـ try/catch وقيمة افتراضية.', 'Write store.get/set with try/catch and defaults.'),
        B('اعمل مسودة فورم بتتحفظ وترجع ومش بتحفظ حقل حساس.', 'Build a form draft that saves and restores, skipping a sensitive field.'),
        B('شوف localStorage في DevTools ← Application ← Local Storage.', 'Look at localStorage in DevTools → Application → Local Storage.')
      ],
      code: [
        { u: B('قراية فورم بأنواع', 'Reading a form with types'), p: 'function readForm(form) {\n  const data = {};\n  for (const el of form.elements) {\n    if (!el.name || el.disabled) continue;\n    if (el.type === "checkbox") data[el.name] = el.checked;\n    else if (el.type === "number") data[el.name] = el.value === "" ? null : Number(el.value);\n    else if (el.type === "radio") { if (el.checked) data[el.name] = el.value; }\n    else data[el.name] = el.value.trim();\n  }\n  return data;\n}', lang: 'js', show: 1 }
      ],
      words: [
        { t: 'submit event', m: B('حدث إرسال الفورم (بالزرار أو Enter)', 'the form-sending event (button or Enter)'), ex: 'form.addEventListener("submit", …)' },
        { t: 'FormData', m: B('كائن بيقرا كل حقول الفورم', 'an object reading every field of a form'), ex: 'new FormData(form)' },
        { t: 'inline validation', m: B('رسايل خطأ جنب الحقل وقت الكتابة', 'error messages beside the field while typing'), ex: 'aria-describedby' },
        { t: 'localStorage', m: B('تخزين نصوص في المتصفح بيفضل بعد القفل', 'browser text storage that survives closing'), ex: 'localStorage.setItem(k, v)' },
        { t: 'draft', m: B('مسودة محفوظة لحد ما تتبعت', 'a saved draft until it is sent'), ex: 'restore the draft' },
        { t: 'quota', m: B('الحد الأقصى للمساحة', 'the maximum space allowed'), ex: 'QuotaExceededError' },
        { t: 'schema version', m: B('رقم نسخة لشكل البيانات المحفوظة', 'a version number for the saved data’s shape'), ex: '{ v: 1, items }' }
      ],
      read: [{ lib: 'MDN: Web forms', what: B('Sending forms through JavaScript وClient-side form validation: Validating forms using JavaScript.', 'Sending forms through JavaScript, and Client-side form validation: Validating forms using JavaScript.') },
        { lib: 'MDN: Web Storage API', what: B('Using the Web Storage API.', 'Using the Web Storage API.') }],
      challenge: B('اعمل فورم «طلب عرض سعر» تفاعلي: تحقق مباشر لكل حقل برسايل جنبه، وإجمالي بيتحسب وانت بتغيّر الكمية، ومسودة بتتحفظ وترجع، وزرار إرسال بيتقفل وهو «بيبعت»، وفي الآخر بيطبع الكائن النهائي النضيف ويمسح المسودة — والصفحة تشتغل حتى لو localStorage مقفول.', 'Build an interactive «quote request» form: live validation of each field with messages beside it, a total recalculated as the quantity changes, a draft that saves and restores, a send button disabled while «sending», and finally printing the clean final object and clearing the draft — with the page still working when localStorage is blocked.'),
      quiz: [
        { q: B('تسمع لإرسال الفورم بـ:', 'You listen for a form being sent with:'), o: [B('submit على الفورم', 'submit on the form'), B('click على الزرار', 'click on the button'), B('change', 'change')], a: 0, why: B('بيشتغل بـ Enter كمان.', 'It fires on Enter too.') },
        { q: B('checkbox مش متعلّم في FormData:', 'An unticked checkbox in FormData:'), o: [B('مش موجود', 'is absent'), 'false', '"off"'], a: 0, why: B('اقراه بـ checked.', 'Read it with checked.') },
        { q: B('localStorage بيخزّن:', 'localStorage stores:'), o: [B('نصوص', 'text'), B('أي نوع', 'any type'), B('أرقام بس', 'numbers only')], a: 0, why: B('JSON للكائنات.', 'JSON for objects.') },
        { q: B('ممنوع في localStorage:', 'Never put in localStorage:'), o: [B('كلمات سر وتوكنز حساسة', 'passwords and sensitive tokens'), B('اللغة المفضلة', 'the preferred language'), B('مسودة ملاحظة', 'a note draft')], a: 0, why: B('أي كود يقراه.', 'Any code can read it.') }
      ] },

    { title: B('مشروع: فورم بيبعت لـ n8n', 'A project: a form that sends to n8n'),
      goal: B('تربط كل الشهر: صفحة HTML/CSS متجاوبة بفورم بيتحقق ويبعت JSON بـ fetch لـ webhook في n8n، بحالات التحميل والنجاح والخطأ.', 'Tie the whole month together: a responsive HTML/CSS page with a form that validates and sends JSON with fetch to an n8n webhook, with loading, success and error states.'),
      learn: [
        { h: B('الخطة من الصفحة لـ n8n', 'The plan from page to n8n'),
          p: B('**الصفحة**: فورم (HTML) شكله حلو ومتجاوب (CSS) بيتحقق ويبعت (JS). **الإرسال**: `fetch(webhookUrl, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) })`. **n8n**: Webhook node بيستقبل، وبعدها تنضيف وحفظ في شيت ورسالة Telegram. هنتعمّق في fetch الشهر الجاي — دلوقتي هنستخدمه بالشكل ده بس.',
            '**The page**: a form (HTML), good-looking and responsive (CSS), that validates and sends (JS). **Sending**: `fetch(webhookUrl, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) })`. **n8n**: a Webhook node receives it, followed by cleaning, saving to a sheet and a Telegram message. We dig into fetch next month — for now we use it in just this form.'),
          ex: '// The whole flow in one place (n8n side in comments):\n// 1. page: validate → build JSON\n// 2. page: fetch POST → https://YOUR-N8N/webhook/quote\n// 3. n8n:  Webhook → Set (clean) → Google Sheets (append) → Telegram (notify) → Respond to Webhook\nconst payload = { name: "Sara", phone: "01012345678", product: "NB", qty: 10, source: "landing-page" };\nconsole.log(JSON.stringify(payload));', run: 'js' },
        { h: B('الإرسال بـ fetch والحالات', 'Sending with fetch, and the states'),
          p: B('الفورم ليه 4 حالات لازم تبان للمستخدم: **فاضي/بيتكتب**، و**بيبعت** (زرار مقفول وكلمة «جاري الإرسال…»)، و**نجح** (رسالة شكر وفضّي الفورم)، و**فشل** (رسالة بتقول يعمل إيه، والبيانات **متتمسحش**). افحص `r.ok` — fetch مش بيرمي خطأ لـ 404 أو 500. ومتنساش finally ترجّع الزرار.',
            'The form has 4 states the user must see: **empty/typing**, **sending** (a disabled button and «Sending…»), **success** (a thank-you message, then clear the form) and **failure** (a message saying what to do, with the data **not** cleared). Check `r.ok` — fetch does not throw on 404 or 500. And remember finally to restore the button.'),
          ex: 'async function send(url, data, ui) {\n  ui.state("sending");\n  try {\n    const r = await fetch(url, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) });\n    if (!r.ok) throw new Error("HTTP " + r.status);\n    ui.state("success");\n  } catch (err) {\n    ui.state("error", err.message);\n  } finally {\n    ui.done();\n  }\n}\nconst ui = { state: (s, m) => console.log("state:", s, m ?? ""), done: () => console.log("button enabled again") };\nsend("https://httpbin.org/status/500", { a: 1 }, ui);', run: 'js' },
        { h: B('الواجهة اللي بتتغيّر مع الحالة', 'The interface that follows the state'),
          p: B('اعمل دالة `setState(state, message)` واحدة بتغيّر كل حاجة: كلاس على الفورم (`is-sending` و`is-success` و`is-error`)، ونص الزرار، و`disabled`، ورسالة بـ `aria-live="polite"` عشان قارئ الشاشة يقولها. CSS يتولى الشكل لكل كلاس. كده متلاقيش حالة الزرار مقفول والرسالة بتقول «نجح».',
            'Write one `setState(state, message)` function that changes everything: a class on the form (`is-sending`, `is-success`, `is-error`), the button’s text, `disabled`, and a message with `aria-live="polite"` so screen readers announce it. CSS handles the look of each class. That way you never get a disabled button with a «success» message.'),
          ex: 'const form = document.querySelector("form"), btn = form.querySelector("button"), msg = document.querySelector("#msg");\nconst TEXT = { idle: "Send request", sending: "Sending…", success: "Sent ✓", error: "Try again" };\nfunction setState(state, message = "") {\n  form.classList.remove("is-sending", "is-success", "is-error");\n  if (state !== "idle") form.classList.add("is-" + state);\n  btn.textContent = TEXT[state];\n  btn.disabled = state === "sending";\n  msg.textContent = message;\n}\nfor (const [s, m] of [["sending"], ["error", "No connection. Your data is kept — try again."], ["success", "Thanks! We will call you within a day."]]) {\n  setState(s, m);\n  console.log(s, "|", btn.textContent, "| disabled:", btn.disabled, "|", msg.textContent);\n}', run: 'js',
          html: '<style>form.is-error #msg{color:#b91c1c}form.is-success #msg{color:#047857}</style><form><button>Send request</button><p id="msg" aria-live="polite"></p></form>' },
        { h: B('الأمان على الطرفين', 'Security on both sides'),
          p: B('عنوان الـ webhook بيبان لأي حد يفتح الصفحة — **مش سر**. فاتعامل: (1) في n8n اتحقق من كل حقل تاني (التحقق في الصفحة سهل يتخطى)، (2) حط حد للحجم وللعدد (rate limit) أو header سري بسيط ضد الـ spam، (3) استخدم honeypot: حقل مخفي البشر مش بيملوه والبوتات بتملاه — لو اتملا ارفض، (4) متحطش أبدًا مفاتيح API في JS الصفحة.',
            'The webhook address is visible to anyone who opens the page — **it is not a secret**. So: (1) validate every field again in n8n (page validation is easy to bypass), (2) limit size and frequency (rate limit) or add a simple secret header against spam, (3) use a honeypot: a hidden field humans never fill but bots do — reject if it is filled, (4) never put API keys in the page’s JS.'),
          ex: 'function looksLikeSpam(data) {\n  if (data.website) return "honeypot filled";        // hidden field: humans leave it empty\n  if (String(data.notes ?? "").length > 2000) return "notes too long";\n  if ((String(data.notes ?? "").match(/https?:\\/\\//g) ?? []).length > 2) return "too many links";\n  return "";\n}\nconsole.log(looksLikeSpam({ name: "Sara", website: "" }) || "ok");\nconsole.log(looksLikeSpam({ name: "bot", website: "http://spam.example" }));\nconsole.log(looksLikeSpam({ notes: "see http://a.x http://b.x http://c.x" }));', run: 'js' },
        { h: B('جرّب من غير n8n', 'Testing without n8n'),
          p: B('قبل ما توصّل n8n، ابعت لـ **httpbin.org/post** (بيرجّعلك اللي بعته بالظبط) عشان تتأكد من شكل الـ JSON والـ headers. وجرّب الفشل: `httpbin.org/status/500` و`/status/429` وعنوان غلط، وافصل النت (DevTools ← Network ← Offline). لما الأربع حالات يشتغلوا صح، بدّل العنوان بعنوان الـ webhook بتاعك.',
            'Before connecting n8n, send to **httpbin.org/post** (it echoes exactly what you sent) to check the JSON’s shape and headers. And try failure: `httpbin.org/status/500`, `/status/429`, a wrong address, and going offline (DevTools → Network → Offline). Once all four states behave, swap in your webhook address.'),
          ex: 'fetch("https://httpbin.org/post", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: "Sara", qty: 3 }) })\n  .then(r => r.json())\n  .then(echo => console.log("server saw:", echo.json, echo.headers["Content-Type"]))\n  .catch(err => console.log("failed:", err.message));', run: 'js' }
      ],
      practice: [
        B('اكتب الخطة من الصفحة لـ n8n كتعليقات (5 خطوات).', 'Write the page-to-n8n plan as comments (5 steps).'),
        B('اعمل send بـ fetch بيفحص r.ok وبيستخدم finally.', 'Write send with fetch, checking r.ok and using finally.'),
        B('اعمل setState بـ 4 حالات وCSS لكل حالة.', 'Write setState with 4 states and CSS for each.'),
        B('ضيف honeypot وفحص spam بسيط.', 'Add a honeypot and a simple spam check.'),
        B('جرّب الإرسال لـ httpbin.org/post و/status/500 وOffline.', 'Try sending to httpbin.org/post, /status/500 and offline.'),
        B('لو عندك n8n: اعمل Webhook وابعتله وشوف الـ execution.', 'If you have n8n: create a Webhook, send to it and look at the execution.')
      ],
      code: [
        { u: B('n8n: ارجع رد للصفحة', 'n8n: reply to the page'), p: '// n8n workflow\n// Webhook (POST /quote, Respond: "Using Respond to Webhook node")\n//   → Code: validate again, reject honeypot / bad phone\n//   → Google Sheets: append row\n//   → Telegram: "New quote from {{ $json.name }}"\n//   → Respond to Webhook: { "ok": true } (status 200)  /  { "ok": false, "error": "…" } (400)', lang: 'text', show: 1 }
      ],
      words: [
        { t: 'webhook', m: B('عنوان بيستقبل طلبات ويبدأ workflow', 'an address that receives requests and starts a workflow'), ex: 'POST /webhook/quote' },
        { t: 'fetch', m: B('دالة المتصفح لإرسال واستقبال طلبات HTTP', 'the browser’s function for HTTP requests'), ex: 'fetch(url, { method: "POST" })' },
        { t: 'request body', m: B('البيانات اللي بتتبعت جوه الطلب', 'the data sent inside a request'), ex: 'JSON.stringify(data)' },
        { t: 'loading state', m: B('حالة «جاري…» والمستخدم مستني', 'the «working…» state while the user waits'), ex: 'btn.disabled = true' },
        { t: 'honeypot', m: B('حقل مخفي بيمسك البوتات', 'a hidden field that catches bots'), ex: '<input name="website" hidden>' },
        { t: 'spam', m: B('رسايل مزعجة أو أوتوماتيك مش مطلوبة', 'unwanted or automated junk messages'), ex: 'block spam' },
        { t: 'echo server', m: B('سيرفر بيرجّعلك اللي بعته عشان تجرّب', 'a server returning what you sent, for testing'), ex: 'httpbin.org/post' }
      ],
      read: [{ lib: 'MDN: Using the Fetch API', what: B('Making a request وSetting a body وChecking that the fetch was successful.', 'Making a request, Setting a body, and Checking that the fetch was successful.') },
        { lib: 'n8n Docs: Code node', what: B('اقرا صفحة الـ Webhook node من نفس التوثيق: Workflow development وResponse.', 'Read the Webhook node page in the same docs: Workflow development and Response.') }],
      challenge: B('وصّل فورم «عرض السعر» بتاع الأسبوع ده بـ n8n حقيقي (أو httpbin لو مفيش): Webhook ← Code بيتحقق تاني ← Google Sheets ← Telegram ← Respond to Webhook، والصفحة بتعرض رسالة n8n الراجعة. صوّر execution ناجح وواحد مرفوض بسبب honeypot.', 'Connect this week’s «quote request» form to a real n8n (or httpbin if you have none): Webhook → Code validating again → Google Sheets → Telegram → Respond to Webhook, with the page showing the message n8n returns. Screenshot a successful execution and one rejected by the honeypot.'),
      quiz: [
        { q: B('fetch بيرمي خطأ لما السيرفر يرد 500؟', 'Does fetch throw when the server replies 500?'), o: [B('لأ، افحص r.ok', 'No — check r.ok'), B('أيوه', 'Yes'), B('ساعات', 'Sometimes')], a: 0, why: B('بيرمي لمشاكل الشبكة بس.', 'It throws only for network failures.') },
        { q: B('لما الإرسال يفشل، بيانات الفورم:', 'When sending fails, the form’s data:'), o: [B('تفضل زي ما هي', 'stays as it is'), B('تتمسح', 'is cleared'), B('تتبعت تاني لوحدها', 'is resent by itself')], a: 0, why: B('المستخدم ميكتبش تاني.', 'The user should not retype.') },
        { q: B('عنوان الـ webhook في الصفحة:', 'The webhook address on the page:'), o: [B('مش سر، فاتحقق تاني في n8n', 'is not secret, so validate again in n8n'), B('سري تمامًا', 'is completely secret'), B('محدش يقدر يشوفه', 'nobody can see it')], a: 0, why: B('أي حد يفتح المصدر.', 'Anyone can view the source.') },
        { q: B('الـ honeypot حقل:', 'A honeypot is a field:'), o: [B('مخفي البشر مش بيملوه', 'hidden that humans never fill'), B('مطلوب', 'required'), B('لكلمة السر', 'for the password')], a: 0, why: B('البوتات بتملاه.', 'Bots fill it in.') }
      ] },

    { title: B('مراجعة الشهر التالت ومشروعه والاختبار', 'Month 3 review, project and test'),
      goal: B('تراجع HTML وCSS والـ DOM، وتسلّم مشروع الشهر التالت (أداة ويب تفاعلية كاملة)، وتعدّي اختبار الأسبوع وبعده امتحان الشهر — ختام المرحلة المكثّفة.', 'Review HTML, CSS and the DOM, deliver the third month’s project (a complete interactive web tool), and pass the weekly test and then the month exam — the end of the intensive stage.'),
      review: [
        B('HTML دلالي: هيكل كامل، وh1 واحد، وعناصر بمعنى، وفورمز بـ label وname وتحقق.', 'Semantic HTML: a full skeleton, one h1, meaningful elements, forms with label, name and validation.'),
        B('CSS: كلاسات، وcascade وspecificity، وborder-box، وrem، ومتغيرات بأدوار، ووضع ليلي، وتباين.', 'CSS: classes, cascade and specificity, border-box, rem, role-based variables, dark mode, contrast.'),
        B('Flex لبعد واحد، وGrid لبعدين (auto-fit + minmax)، وposition للبادجات واللازق.', 'Flex for one dimension, Grid for two (auto-fit + minmax), position for badges and sticky things.'),
        B('mobile-first وclamp ومن غير سكرول جانبي وأزرار 44px.', 'Mobile-first, clamp, no sideways scroll and 44px buttons.'),
        B('الـ DOM: querySelector وclosest وdataset، وtextContent للبيانات دايمًا.', 'The DOM: querySelector, closest and dataset, and textContent for data, always.'),
        B('classList للشكل، وcreateElement/template للبناء، وrender من البيانات.', 'classList for looks, createElement/template for building, render from data.'),
        B('الأحداث: addEventListener وdelegation وpreventDefault والكيبورد وdebounce.', 'Events: addEventListener, delegation, preventDefault, the keyboard and debounce.'),
        B('الفورم: submit وFormData وتحقق جنب الحقل، وlocalStorage بـ try/catch، وfetch بـ 4 حالات.', 'Forms: submit, FormData, validation beside fields, localStorage with try/catch, and fetch with 4 states.')
      ],
      project: B('**مشروع الشهر التالت: «بوابة طلبات العملاء» — أداة ويب كاملة بـ HTML وCSS وJS.**\n1. **صفحة الطلب** (عربي، متجاوبة، mobile-first): header لازق، وكتالوج منتجات من مصفوفة JS بـ template وauto-fit، وزرار «أضف» على كل كارت بـ delegation.\n2. **السلة**: لوحة جانبية (sticky على الكمبيوتر، تحت على الموبايل) بتعرض المنتجات والكمية (+/−) والإجمالي والشحن حسب المدينة، ومتحفظة في localStorage بأمان.\n3. **الفورم**: بيانات العميل بتحقق مباشر برسايل جنب الحقول وhoneypot، ومسودة متحفظة.\n4. **الإرسال**: fetch لـ webhook (n8n أو httpbin) بالـ 4 حالات، والسلة تتفضّى بعد النجاح بس.\n5. **لوحة الطلبات** (صفحة تانية): تقرا الطلبات المبعوتة (من localStorage كمحاكاة) وتعرضها بجدول بيتحوّل كروت على الموبايل، ببحث بـ debounce وفلتر حالة.\n6. **الجودة**: validator من غير أخطاء، وLighthouse Accessibility 95+، وصفر سكرول جانبي على 360px، ومفيش innerHTML ببيانات، ووضع ليلي، واختصار «/» للبحث.',
        '**The third month’s project: a «customer orders portal» — a complete web tool in HTML, CSS and JS.**\n1. **The order page** (Arabic, responsive, mobile-first): a sticky header, a product catalogue from a JS array using a template and auto-fit, and an «add» button on each card via delegation.\n2. **The basket**: a side panel (sticky on desktop, below on phones) showing products, quantity (+/−), the total and shipping by city, saved safely in localStorage.\n3. **The form**: customer details with live validation, messages beside the fields and a honeypot, plus a saved draft.\n4. **Sending**: fetch to a webhook (n8n or httpbin) with the 4 states, the basket cleared only on success.\n5. **The orders board** (a second page): reads the sent orders (from localStorage as a simulation) and shows them in a table that turns into cards on phones, with a debounced search and a status filter.\n6. **Quality**: zero validator errors, Lighthouse Accessibility 95+, zero sideways scroll at 360px, no innerHTML holding data, dark mode, and a «/» shortcut for search.'),
      test: [
        { q: B('`document.querySelectorAll(".x")` بيرجّع:', '`document.querySelectorAll(".x")` returns:'), o: ['NodeList', 'Array', B('أول عنصر', 'the first element')], a: 0, why: B('حوّلها بـ [...].', 'Convert with [...].') },
        { q: B('`el.textContent = "<b>hi</b>"` بيظهر:', '`el.textContent = "<b>hi</b>"` shows:'), o: [B('النص زي ما هو بالوسوم', 'the text as is, tags included'), B('hi عريض', 'bold hi'), B('ولا حاجة', 'nothing')], a: 0, why: B('نص مش HTML.', 'Text, not HTML.') },
        { q: B('`<li data-order-id="9">` في JS:', '`<li data-order-id="9">` in JS:'), o: ['li.dataset.orderId', 'li.dataset.order-id', 'li.orderId'], a: 0, why: B('camelCase.', 'camelCase.') },
        { q: B('`btn.closest(".row")` لو btn نفسه عليه كلاس row:', '`btn.closest(".row")` when btn itself has the class row:'), o: [B('بيرجّع btn', 'returns btn'), 'null', B('أبوه', 'its parent')], a: 0, why: B('بيبدأ بنفسه.', 'It starts with itself.') },
        { q: B('تغيّر الشكل لحالة «مفتوح»:', 'Switching to an «open» look:'), o: ['el.classList.toggle("open")', 'el.style = "open"', 'el.open()'], a: 0, why: B('كلاس.', 'A class.') },
        { q: B('تبني صف من بيانات عميل بأمان:', 'Building a row from customer data safely:'), o: [B('createElement وtextContent', 'createElement and textContent'), B('innerHTML += `${name}`', 'innerHTML += `${name}`'), 'eval'], a: 0, why: B('XSS.', 'XSS.') },
        { q: B('حدث بيطلع من الزرار للأب اسمه:', 'An event rising from the button to the parent is called:'), o: ['bubbling', 'hoisting', 'chaining'], a: 0, why: B('بيخلّي delegation ممكن.', 'It makes delegation possible.') },
        { q: B('عشان الرابط ميفتحش الصفحة:', 'To stop a link opening its page:'), o: ['e.preventDefault()', 'e.stopPropagation()', 'link.remove()'], a: 0, why: B('السلوك الافتراضي.', 'The default behaviour.') },
        { q: B('اختصار ميشتغلش والمستخدم بيكتب:', 'A shortcut must not fire while the user types, so check:'), o: ['e.target.matches("input, textarea")', 'e.key === "Enter"', 'e.ctrlKey'], a: 0, why: B('متسرقش الكتابة.', 'Do not steal typing.') },
        { q: B('`Object.fromEntries(new FormData(form))`:', '`Object.fromEntries(new FormData(form))`:'), o: [B('كائن بكل الحقول اللي ليها name', 'an object of every named field'), B('مصفوفة', 'an array'), B('نص JSON', 'JSON text')], a: 0, why: B('جاهز تبعته.', 'Ready to send.') },
        { q: B('قراية localStorage آمنة:', 'Reading localStorage safely:'), o: [B('JSON.parse جوه try/catch بقيمة افتراضية', 'JSON.parse inside try/catch with a default'), B('JSON.parse على طول', 'JSON.parse directly'), B('من غير parse', 'without parse')], a: 0, why: B('ممكن يكون بايظ أو مقفول.', 'It may be broken or blocked.') },
        { q: B('وهو بيبعت، الزرار:', 'While sending, the button:'), o: [B('مقفول ومكتوب عليه «جاري…»', 'is disabled and says «Sending…»'), B('شغال عادي', 'works as normal'), B('مخفي', 'is hidden')], a: 0, why: B('يمنع الإرسال مرتين.', 'It prevents double sends.') },
        { q: B('بعد ما الإرسال يفشل:', 'After sending fails:'), o: [B('رسالة واضحة والبيانات تفضل', 'a clear message, and the data stays'), B('امسح الفورم', 'clear the form'), B('أعد تحميل الصفحة', 'reload the page')], a: 0, why: B('المستخدم يحاول تاني.', 'The user can try again.') }
      ] }
  ]
};
