// Python week 1 — the intensive hour (weeks 1–12 are 3 hours a day). Merged into the week by tools/build_weeks.js.
// Every code sample has run: 1, so tools/test_python_examples.js runs it.
const B = (ar, en) => ({ ar, en });
const L = (h, p, ex) => ({ h, p, ex });
const C = (u, p) => ({ u, p, run: 1 });
const W = (t, ar, en, ex) => ({ t, m: B(ar, en), ex });
const Q = (q, o, a, why) => ({ q, o, a, why });
module.exports = { days: [
  { learn: [L(B('print من جوه', 'print from the inside'),
      B('`print` بياخد أكتر من قيمة ويحط بينهم مسافة (`sep`)، وفي الآخر سطر جديد (`end`). تقدر تغيّرهم: `sep=", "` أو `end=""`. والرسايل العادية بتروح لـ **stdout**، ورسايل الخطأ لـ **stderr** — مهم لما سكربتك يشتغل في n8n أو جدولة وتقرا الخرج.',
        '`print` takes several values and puts a space between them (`sep`), and a new line at the end (`end`). You can change them: `sep=", "` or `end=""`. Normal output goes to **stdout**, error messages to **stderr** — this matters when your script runs from n8n or a scheduler and you read its output.'),
      'print("a", "b", "c")            # a b c\nprint("a", "b", sep=" | ")      # a | b\nprint("loading", end="...")      # no new line')],
    code: [C(B('خرج مرتب بـ sep وend', 'Tidy output with sep and end'),
      'import sys\nprint("order", 1042, "paid", sep=" | ")\nfor step in ["read", "check", "save"]:\n    print(step, end=" -> ")\nprint("done")\nprint("this goes to stderr", file=sys.stderr)')],
    practice: [B('اطبع جدول من 3 أعمدة (اسم | سعر | كمية) لـ 4 منتجات بـ `sep`.', 'Print a 3-column table (name | price | qty) for 4 products using `sep`.'),
      B('اطبع شريط تحميل من 10 نقط على نفس السطر بـ `end`.', 'Print a loading bar of 10 dots on one line using `end`.')],
    words: [W('stdout', 'الخرج العادي للبرنامج', 'a program’s normal output', 'print writes to stdout.'),
      W('stderr', 'خرج رسايل الخطأ', 'the output for error messages', 'Write warnings to stderr.')],
    quiz: [Q(B('`print("a", "b", sep="-")` بيطبع:', '`print("a", "b", sep="-")` prints:'), ['a-b', 'a b', 'a - b'], 0, B('sep بين القيم.', 'sep goes between values.'))] },
  { learn: [L(B('تسمية المتغيرات وإعادة الإسناد', 'Naming variables and reassigning'),
      B('بايثون بتستخدم **snake_case**: حروف صغيرة و`_` بين الكلمات (`total_price`). الاسم يوصف القيمة. وتقدر تعيد إسناد متغيّر لقيمة جديدة (حتى من نوع تاني)، بس ده بيلخبط: خلّي كل متغيّر لحاجة واحدة. وتبديل قيمتين في سطر: `a, b = b, a`.',
        'Python uses **snake_case**: lowercase with `_` between words (`total_price`). The name describes the value. You can reassign a variable to a new value (even of another type), but that confuses readers: keep each variable for one thing. Swap two values in one line: `a, b = b, a`.'),
      'total_price = 120      # ✓ snake_case\nTotalPrice = 120       # ✗ (that style is for classes)\nx = 5; x = "five"      # legal, but confusing')],
    code: [C(B('تبديل وإعادة إسناد', 'Swapping and reassigning'),
      'first_name = "Sara"\nlast_name = "Adel"\nfirst_name, last_name = last_name, first_name\nprint(first_name, last_name)\ncount = 0\ncount = count + 1\ncount += 1\nprint("count:", count)')],
    practice: [B('صلّح أسماء 8 متغيّرات سيئة (`x1`, `Data`, `tp`…) لأسماء snake_case واضحة.', 'Fix 8 bad variable names (`x1`, `Data`, `tp`…) into clear snake_case names.'),
      B('بدّل 3 قيم بشكل دائري (`a, b, c = b, c, a`) واطبعهم.', 'Rotate 3 values (`a, b, c = b, c, a`) and print them.')],
    words: [W('snake_case', 'كتابة الأسماء بحروف صغيرة و_ بين الكلمات', 'writing names in lowercase with _ between words', 'Python variables use snake_case.'),
      W('reassign', 'تدّي متغيّر قيمة جديدة', 'to give a variable a new value', 'Reassign count after each order.')],
    quiz: [Q(B('اسم متغيّر حسب PEP 8:', 'A variable name following PEP 8:'), ['order_total', 'OrderTotal', 'ordertotal!'], 0, B('snake_case.', 'snake_case.'))] },
  { learn: [L(B('ترتيب العمليات والكسور العشرية', 'Operator precedence and floating point'),
      B('الترتيب: `**` ثم `* / // %` ثم `+ -` ثم المقارنات ثم `not` ثم `and` ثم `or`. لو شاكك، حط أقواس. والكسور العشرية في الكمبيوتر تقريبية: `0.1 + 0.2` مش بالظبط `0.3`. للمقارنة استخدم `math.isclose`، وللفلوس `round` أو `Decimal`.',
        'The order: `**`, then `* / // %`, then `+ -`, then comparisons, then `not`, then `and`, then `or`. When unsure, add brackets. Decimals in computers are approximate: `0.1 + 0.2` is not exactly `0.3`. Compare with `math.isclose`, and use `round` or `Decimal` for money.'),
      '2 + 3 * 4      # 14, not 20\n(2 + 3) * 4    # 20\n0.1 + 0.2      # 0.30000000000000004')],
    code: [C(B('أقواس ومقارنة كسور', 'Brackets and comparing decimals'),
      'import math\nprice, qty, discount = 50, 3, 10\nprint(price * qty - discount)\nprint(price * (qty - 1))\nprint(0.1 + 0.2 == 0.3)\nprint(math.isclose(0.1 + 0.2, 0.3))\nprint(round(0.1 + 0.2, 2))')],
    practice: [B('احسب 6 تعبيرات في دماغك الأول، وبعدين شغّلها وقارن.', 'Work out 6 expressions in your head first, then run them and compare.'),
      B('احسب سعر طلب فيه ضريبة 14% وخصم 5% بأقواس واضحة.', 'Compute an order price with 14% tax and 5% discount using clear brackets.')],
    words: [W('operator precedence', 'ترتيب تنفيذ العمليات في التعبير', 'the order operations run in an expression', 'Operator precedence puts * before +.'),
      W('floating point', 'طريقة تخزين الكسور العشرية (تقريبية)', 'the way decimals are stored (approximate)', 'Floating point makes 0.1 + 0.2 slightly off.')],
    quiz: [Q(B('`2 + 3 * 4` =', '`2 + 3 * 4` ='), ['14', '20', '24'], 0, B('الضرب الأول.', 'Multiplication first.'))] },
  { learn: [L(B('التحويل الآمن بين الأنواع', 'Safe type conversion'),
      B('`int("42")` بيشتغل، بس `int("42.5")` و`int(" 42 ")`؟ التاني شغال (بيتجاهل المسافات)، والأول خطأ. اعمل `.strip()` للمسافات، وجرّب `float` للكسور، واستخدم `str.isdigit()` قبل التحويل، أو `try/except ValueError` (هتتعلمها بالتفصيل في أسبوع 8).',
        '`int("42")` works, but `int("42.5")` and `int(" 42 ")`? The second works (it ignores spaces); the first fails. Use `.strip()` for spaces, `float` for decimals, and check with `str.isdigit()` before converting, or use `try/except ValueError` (covered in detail in week 8).'),
      'int(" 42 ")      # 42\nint("42.5")      # ValueError\nint(float("42.5"))  # 42\n"42".isdigit()   # True')],
    code: [C(B('تحويل مدخلات متنوعة', 'Converting mixed inputs'),
      'raw_values = ["12", " 7 ", "3.5", "abc", ""]\nfor raw in raw_values:\n    text = raw.strip()\n    if text.isdigit():\n        print(repr(raw), "-> int", int(text))\n    elif text.replace(".", "", 1).isdigit():\n        print(repr(raw), "-> float", float(text))\n    else:\n        print(repr(raw), "-> not a number")')],
    practice: [B('اكتب برنامج بياخد سعر كنص (فيه مسافات أو فاصلة عشرية) ويحوّله رقم ويطبع السعر بعد الضريبة.', 'Write a program that takes a price as text (with spaces or a decimal point), converts it and prints the price after tax.'),
      B('جرّب `bool("False")` واشرح النتيجة الغريبة.', 'Try `bool("False")` and explain the surprising result.')],
    words: [W('type casting', 'تحويل قيمة من نوع لنوع', 'turning a value from one type into another', 'int("5") is type casting.'),
      W('whitespace', 'مسافات وtab وسطور جديدة', 'spaces, tabs and new lines', 'strip() removes whitespace at both ends.')],
    quiz: [Q(B('`int("3.7")` بيطلع:', '`int("3.7")` gives:'), ['ValueError', '3', '4'], 0, B('int من نص مش بيقبل كسر.', 'int from text does not accept a decimal.'))] },
  { learn: [L(B('PEP 8 وقراءة رسالة الخطأ', 'PEP 8 and reading the error message'),
      B('**PEP 8** دليل شكل الكود في بايثون: 4 مسافات للـ indent، سطر أقل من ~79–99 حرف، مسافة حوالين `=` و`+`، سطرين فاضيين قبل الدوال. VS Code بيعمله لوحده بـ Format Document (مع Ruff أو Black). ورسالة الخطأ: اقرا **آخر سطر** الأول (النوع والسبب)، وبعدين رقم السطر فوقه.',
        '**PEP 8** is Python’s style guide: 4 spaces per indent, lines under ~79–99 characters, spaces around `=` and `+`, two blank lines before functions. VS Code applies it with Format Document (using Ruff or Black). And error messages: read the **last line** first (the type and reason), then the line number above it.'),
      'Traceback (most recent call last):\n  File "shop.py", line 3, in <module>\n    total = price + qty\nTypeError: can only concatenate str (not "int") to str   ← read this first')],
    code: [C(B('خطأ نوع وإصلاحه', 'A type error and its fix'),
      'price = "50"\nqty = 2\ntry:\n    print(price + qty)\nexcept TypeError as e:\n    print("Error:", e)\nprint("Fixed:", int(price) * qty)')],
    practice: [B('اعمل Format Document لملف كتبته واشوف إيه اللي اتغيّر.', 'Run Format Document on a file you wrote and see what changed.'),
      B('اعمل 3 أخطاء مختلفة عمدًا (TypeError، NameError، SyntaxError) واكتب آخر سطر لكل واحد ومعناه.', 'Cause 3 different errors on purpose (TypeError, NameError, SyntaxError) and write the last line of each and what it means.')],
    words: [W('pep 8', 'دليل الشكل الرسمي لكود بايثون', 'the official style guide for Python code', 'Follow PEP 8 so others can read your code.'),
      W('type error', 'خطأ لما تستخدم قيمة من نوع غلط', 'an error when a value has the wrong type', 'Adding text to a number causes a type error.')],
    quiz: [Q(B('في الـ traceback تقرا الأول:', 'In a traceback you read first:'), ['the last line', 'the first line', 'the file name'], 0, B('النوع والسبب في الآخر.', 'The type and reason are at the end.'))] },
  { review: [B('⚡ print بـ sep وend وstdout/stderr، وsnake_case وإعادة الإسناد.', '⚡ print with sep and end, stdout/stderr, snake_case and reassigning.'),
      B('⚡ ترتيب العمليات والكسور، والتحويل الآمن، وPEP 8 وقراءة الخطأ: طبّقهم في مشروع الأسبوع.', '⚡ Precedence and decimals, safe conversion, PEP 8 and reading errors: use them in the week project.')] }
] };
