// Python week 2 — the intensive hour (weeks 1–12 are 3 hours a day). Merged into the week by tools/build_weeks.js.
// Every code sample has run: 1, so tools/test_python_examples.js runs it.
const B = (ar, en) => ({ ar, en });
const L = (h, p, ex) => ({ h, p, ex });
const C = (u, p) => ({ u, p, run: 1 });
const W = (t, ar, en, ex) => ({ t, m: B(ar, en), ex });
const Q = (q, o, a, why) => ({ q, o, a, why });
module.exports = { days: [
  { learn: [L(B('علامات الهروب والنصوص متعددة السطور', 'Escape sequences and multi-line strings'),
      B('جوه النص، `\\n` سطر جديد، `\\t` tab، `\\\\` شرطة مايلة، `\\"` تنصيص. النص بين `"""` تلات تنصيصات بيكمّل على كذا سطر — مفيد لقوالب الرسايل. ولمسارات ويندوز استخدم `r"C:\\new"` (raw) عشان `\\n` متتفهمش سطر جديد.',
        'Inside a string, `\\n` is a new line, `\\t` a tab, `\\\\` a backslash, `\\"` a quote. Text between `"""` triple quotes spans several lines — handy for message templates. For Windows paths use `r"C:\\new"` (raw) so `\\n` is not read as a new line.'),
      'print("Name:\\tSara\\nCity:\\tGiza")\nmsg = """Hi Sara,\nYour order is ready.\n"""')],
    code: [C(B('قالب رسالة على كذا سطر', 'A multi-line message template'),
      'name, order_id, total = "Sara", 1042, 350\nmessage = f"""Hi {name},\n\nYour order #{order_id} is ready.\nTotal:\\t{total} EGP\n\nThanks!"""\nprint(message)\nprint(len(message.splitlines()), "lines")')],
    practice: [B('اعمل قالب إيصال على 6 سطور فيه tab بين الاسم والقيمة.', 'Build a 6-line receipt template with a tab between each label and value.'),
      B('اطبع مسار ويندوز فيه `\\n` مرة عادي ومرة raw وقارن.', 'Print a Windows path containing `\\n` once normally and once raw, and compare.')],
    words: [W('escape sequence', 'حرف خاص بيبدأ بـ \\ زي \\n', 'a special character starting with \\ like \\n', '\\t is the escape sequence for a tab.'),
      W('multiline string', 'نص بين تلات تنصيصات على كذا سطر', 'text between triple quotes over several lines', 'Use a multiline string for the email body.')],
    quiz: [Q(B('`len("a\\nb")` =', '`len("a\\nb")` ='), ['3', '4', '2'], 0, B('\\n حرف واحد.', '\\n is one character.'))] },
  { learn: [L(B('الـ slice بالخطوة والعكس', 'Slicing with a step and in reverse'),
      B('`s[start:stop:step]`: `s[::2]` كل حرف التاني، `s[::-1]` النص معكوس، `s[-4:]` آخر 4. الـ slice مش بيكسر لو تعدّى الطول (`"abc"[0:100]` = `"abc"`). مفيد لآخر 4 أرقام من كارت أو رقم، أو لإخفاء جزء.',
        '`s[start:stop:step]`: `s[::2]` every second character, `s[::-1]` the string reversed, `s[-4:]` the last 4. A slice never fails when it passes the length (`"abc"[0:100]` = `"abc"`). Useful for the last 4 digits of a number, or for masking part of it.'),
      '"01012345678"[-4:]    # "5678"\n"python"[::-1]        # "nohtyp"\n"abcdef"[::2]         # "ace"')],
    code: [C(B('إخفاء رقم موبايل', 'Masking a mobile number'),
      'phone = "01012345678"\nmasked = phone[:3] + "*" * (len(phone) - 7) + phone[-4:]\nprint(masked)\nword = "level"\nprint(word, "is a palindrome:", word == word[::-1])')],
    practice: [B('اكتب دالة تخفي الإيميل: `s***@gmail.com`.', 'Write code that masks an email: `s***@gmail.com`.'),
      B('اطبع كل كلمة في جملة معكوسة (مع الحفاظ على ترتيب الكلمات).', 'Print each word of a sentence reversed (keeping the word order).')],
    words: [W('slice object', 'الجزء start:stop:step جوه الأقواس', 'the start:stop:step part inside brackets', 'The slice object [::-1] reverses a list.'),
      W('reverse order', 'الترتيب المعكوس', 'backwards order', 'Print the list in reverse order.')],
    quiz: [Q(B('`"hello"[1:4]` =', '`"hello"[1:4]` ='), ['"ell"', '"hell"', '"ello"'], 0, B('من 1 لحد قبل 4.', 'From 1 up to before 4.'))] },
  { learn: [L(B('المقارنة من غير حساسية للحروف', 'Case-insensitive comparison'),
      B('`.lower()` بيكفي غالبًا، بس `.casefold()` أقوى للمقارنة (بيتعامل مع حروف لغات تانية). قبل ما تقارن مدخلات المستخدم: `.strip()` للمسافات، وبعدين `.casefold()`. ولتنضيف حروف معيّنة من الأطراف: `.strip(".,!")`.',
        '`.lower()` is usually enough, but `.casefold()` is stronger for comparing (it handles letters of other languages). Before comparing user input: `.strip()` the spaces, then `.casefold()`. To remove certain characters from the ends: `.strip(".,!")`.'),
      '"  YES ".strip().casefold() == "yes"    # True\n"Hello!!".strip("!")                     # "Hello"')],
    code: [C(B('تنضيف إجابات المستخدمين', 'Cleaning user answers'),
      'answers = ["  Yes", "YES!", "yes.", "Nope", " y "]\nfor a in answers:\n    clean = a.strip().strip(".!").casefold()\n    agreed = clean in ("yes", "y")\n    print(repr(a), "->", repr(clean), "agreed" if agreed else "not agreed")')],
    practice: [B('اعمل قايمة أوامر بوت (`/start`، `/Help`، ` /PRICE `) ونضّفها قبل المقارنة.', 'Make a list of bot commands (`/start`, `/Help`, ` /PRICE `) and clean them before comparing.'),
      B('شيل علامات الترقيم من أطراف 5 كلمات بـ `strip`.', 'Remove punctuation from the ends of 5 words with `strip`.')],
    words: [W('strip', 'تشيل مسافات أو حروف من الأطراف', 'to remove spaces or characters from both ends', 'Strip the input before checking it.'),
      W('casefold', 'تحويل للحروف الصغيرة بشكل أقوى للمقارنة', 'a stronger lowercase conversion for comparing', 'Casefold both strings before comparing.')],
    quiz: [Q(B('`" Hi! ".strip()` =', '`" Hi! ".strip()` ='), ['"Hi!"', '"Hi"', '" Hi!"'], 0, B('بيشيل المسافات بس.', 'It removes spaces only.'))] },
  { learn: [L(B('textwrap وشريط التقدم', 'textwrap and a progress bar'),
      B('`textwrap.fill(text, width=40)` بيقسّم نص طويل على سطور بعرض محدد — مفيد للتقارير في الطرفية أو رسايل تليجرام. وشريط تقدم بسيط: `"█" * done + "░" * (total - done)` مع النسبة بـ f-string `{p:.0%}`.',
        '`textwrap.fill(text, width=40)` wraps long text into lines of a set width — handy for terminal reports or Telegram messages. A simple progress bar: `"█" * done + "░" * (total - done)` with the percentage via an f-string `{p:.0%}`.'),
      'import textwrap\nprint(textwrap.fill(long_text, width=40))\nprint(f"[{\'█\' * 3}{\'░\' * 7}] {0.3:.0%}")')],
    code: [C(B('تقرير ملفوف وشريط تقدم', 'A wrapped report and a progress bar'),
      'import textwrap\nnote = "The nightly sync copied all paid orders from the shop to the sheet and sent a summary to the team on Telegram."\nprint(textwrap.fill(note, width=36))\ntotal = 10\nfor done in (3, 7, 10):\n    bar = "█" * done + "░" * (total - done)\n    print(f"[{bar}] {done / total:.0%}")')],
    practice: [B('اعمل تقرير ملخص لـ 5 طلبات بعرض 40 حرف.', 'Make a summary report of 5 orders at 40 characters wide.'),
      B('اعمل شريط تقدم بـ 20 خانة لعملية من 57 عنصر.', 'Make a 20-cell progress bar for a job of 57 items.')],
    words: [W('textwrap', 'مكتبة بتقسّم النص على سطور بعرض محدد', 'a module that wraps text to a set width', 'Use textwrap to fit the message on a phone.'),
      W('progress bar', 'شريط بيبيّن نسبة الشغل اللي خلص', 'a bar showing how much of the work is done', 'Show a progress bar while files are copied.')],
    quiz: [Q(B('`f"{0.256:.0%}"` =', '`f"{0.256:.0%}"` ='), ['"26%"', '"0.26%"', '"25.6"'], 0, B('% بيضرب في 100.', '% multiplies by 100.'))] },
  { learn: [L(B('التقريب: round والتقريب البنكي', 'Rounding: round and banker’s rounding'),
      B('`round(2.5)` = `2` مش `3`! بايثون بتستخدم **التقريب البنكي**: النص بيروح للرقم الزوجي (عشان الأخطاء متتراكمش في الحسابات الكتير). للفلوس استخدم `Decimal` مع `ROUND_HALF_UP` لو محتاج التقريب المدرسي.',
        '`round(2.5)` is `2`, not `3`! Python uses **banker’s rounding**: halves go to the even number (so errors do not pile up over many sums). For money use `Decimal` with `ROUND_HALF_UP` when you need school-style rounding.'),
      'round(2.5), round(3.5)   # (2, 4)\nDecimal("2.5").quantize(Decimal("1"), rounding=ROUND_HALF_UP)   # 3')],
    code: [C(B('round مقابل Decimal', 'round versus Decimal'),
      'from decimal import Decimal, ROUND_HALF_UP\nfor x in ["0.5", "1.5", "2.5", "2.675"]:\n    school = Decimal(x).quantize(Decimal("1"), rounding=ROUND_HALF_UP)\n    print(x, "round():", round(float(x)), "half-up:", school)\nprint(round(2.675, 2), Decimal("2.675").quantize(Decimal("0.01"), rounding=ROUND_HALF_UP))')],
    practice: [B('احسب فاتورة فيها 7 أسعار بكسور وقرّب الإجمالي بالطريقتين وقارن.', 'Compute an invoice of 7 prices with decimals and round the total both ways; compare.'),
      B('اشرح لنفسك ليه `round(2.675, 2)` بيطلع `2.67`.', 'Explain to yourself why `round(2.675, 2)` gives `2.67`.')],
    words: [W('rounding mode', 'قاعدة التقريب (لفوق، للزوجي…)', 'the rule for rounding (up, to even…)', 'Set the rounding mode to half-up for invoices.'),
      W('banker\'s rounding', 'تقريب النص للرقم الزوجي', 'rounding halves to the even number', 'round() uses banker\'s rounding.')],
    quiz: [Q(B('`round(4.5)` في بايثون =', '`round(4.5)` in Python ='), ['4', '5', '4.5'], 0, B('للزوجي.', 'To even.'))] },
  { review: [B('⚡ escape والنصوص متعددة السطور، والـ slice بالخطوة، وstrip وcasefold.', '⚡ Escapes and multi-line strings, slicing with a step, strip and casefold.'),
      B('⚡ textwrap وشريط التقدم، والتقريب البنكي وDecimal: اعمل إيصال كامل منسّق.', '⚡ textwrap and progress bars, banker’s rounding and Decimal: build a fully formatted receipt.')] }
] };
