// Python week 3 — the intensive hour (weeks 1–12 are 3 hours a day). Merged into the week by tools/build_weeks.js.
// Every code sample has run: 1, so tools/test_python_examples.js runs it.
const B = (ar, en) => ({ ar, en });
const L = (h, p, ex) => ({ h, p, ex });
const C = (u, p) => ({ u, p, run: 1 });
const W = (t, ar, en, ex) => ({ t, m: B(ar, en), ex });
const Q = (q, o, a, why) => ({ q, o, a, why });
module.exports = { days: [
  { learn: [L(B('الشرط في سطر وguard clauses', 'One-line conditions and guard clauses'),
      B('**ternary**: `label = "VIP" if total > 1000 else "normal"` — لما الاختيار بسيط بين قيمتين. و**guard clause**: بدل if جوه if جوه if، اطلع بدري من الحالات الغلط: `if not items: return`. الكود بيبقى مسطّح وأسهل في القراية.',
        '**Ternary**: `label = "VIP" if total > 1000 else "normal"` — for a simple choice between two values. A **guard clause**: instead of if inside if inside if, exit early on the bad cases: `if not items: return`. The code stays flat and easier to read.'),
      'status = "late" if days > 7 else "on time"\n\ndef ship(order):\n    if not order["paid"]:\n        return "not paid"     # guard\n    if not order["address"]:\n        return "no address"   # guard\n    return "shipped"')],
    code: [C(B('guard clauses مقابل ifs متداخلة', 'Guard clauses versus nested ifs'),
      'def check(order):\n    if not order.get("paid"):\n        return "wait for payment"\n    if not order.get("address"):\n        return "ask for address"\n    return "ready to ship"\n\nfor o in [{"paid": True, "address": "Giza"}, {"paid": False}, {"paid": True}]:\n    label = "VIP" if o.get("paid") and o.get("address") else "check"\n    print(check(o), "|", label)')],
    practice: [B('حوّل دالة فيها 3 ifs متداخلة لـ guard clauses.', 'Turn a function with 3 nested ifs into guard clauses.'),
      B('اكتب 4 ternaries لتصنيف (سعر، عمر، درجة، حالة).', 'Write 4 ternaries for labels (price, age, grade, status).')],
    words: [W('ternary', 'شرط في سطر: قيمة if شرط else قيمة', 'a one-line condition: value if test else value', 'Use a ternary for a simple label.'),
      W('guard clause', 'شرط في أول الدالة بيخرج بدري من الحالة الغلط', 'a check at the start of a function that exits early', 'A guard clause avoids deep nesting.')],
    quiz: [Q(B('`"a" if 0 else "b"` =', '`"a" if 0 else "b"` ='), ['"b"', '"a"', '0'], 0, B('0 قيمة false.', '0 is falsy.'))] },
  { learn: [L(B('الـ walrus والخروج بدري', 'The walrus operator and early exit'),
      B('`:=` بيعيّن ويرجّع القيمة في نفس الوقت: `if (n := len(items)) > 10: print(n)`. مفيد في while والـ comprehensions. ولما تلاقي اللي بتدوّر عليه في loop، `break` يخرج بدري بدل ما تكمّل على الفاضي — وفيه `for … else` اللي بيشتغل لو مفيش break.',
        '`:=` assigns and returns a value at once: `if (n := len(items)) > 10: print(n)`. Useful in while loops and comprehensions. When you find what you were looking for in a loop, `break` exits early instead of continuing for nothing — and `for … else` runs only when there was no break.'),
      'if (count := len(orders)) > 100:\n    print("busy day:", count)\n\nfor o in orders:\n    if o["id"] == 1042:\n        print("found"); break\nelse:\n    print("not found")')],
    code: [C(B('دوّر واخرج بدري', 'Search and exit early'),
      'orders = [{"id": 1040}, {"id": 1042}, {"id": 1050}]\nwanted = 1042\nfor o in orders:\n    if o["id"] == wanted:\n        print("found", wanted)\n        break\nelse:\n    print("not found")\nif (n := len(orders)) >= 3:\n    print("orders today:", n)')],
    practice: [B('دوّر على أول رقم سالب في قايمة، واطبع «مفيش» بـ `for … else` لو مالقيتش.', 'Find the first negative number in a list, and print «none» with `for … else` if there is none.'),
      B('استخدم `:=` في while بيقرا عناصر من قايمة لحد ما تخلص.', 'Use `:=` in a while loop that reads items from a list until it is empty.')],
    words: [W('walrus operator', 'العلامة := اللي بتعيّن وترجّع القيمة', 'the := operator that assigns and returns a value', 'The walrus operator saves one line.'),
      W('early exit', 'الخروج من loop أو دالة قبل آخرها', 'leaving a loop or function before its end', 'break gives an early exit.')],
    quiz: [Q(B('`else` بعد `for` بيشتغل لما:', '`else` after `for` runs when:'), ['the loop ends without break', 'break happens', 'always'], 0, B('مفيش break.', 'No break happened.'))] },
  { learn: [L(B('الـ sentinel والمجموع الجاري', 'Sentinels and running sums'),
      B('**sentinel** قيمة خاصة بتقول «خلاص»: زي `"done"` أو سطر فاضي، والـ while بتقف عندها. و**running sum** متغيّر بيتجمع فيه مع كل لفة (`total += x`). مع بعض: اقرا لحد الـ sentinel واجمع.',
        'A **sentinel** is a special value meaning «stop»: like `"done"` or an empty line, and the while loop stops on it. A **running sum** is a variable that grows each time round (`total += x`). Together: read until the sentinel and add up.'),
      'total = 0\nwhile (line := next_line()) != "done":\n    total += float(line)\nprint(total)')],
    code: [C(B('اجمع لحد كلمة done', 'Add up until the word done'),
      'lines = iter(["120", "80.5", "45", "done", "999"])\ntotal = 0\ncount = 0\nwhile (line := next(lines)) != "done":\n    total += float(line)\n    count += 1\n    print(f"after {count}: {total:.2f}")\nprint("final:", total)')],
    practice: [B('اقرا درجات لحد ما تيجي `-1` واطبع المتوسط وأعلى درجة.', 'Read scores until `-1` and print the average and the highest score.'),
      B('اطبع المجموع الجاري لمبيعات أسبوع يوم بيوم.', 'Print the running sum of a week’s sales day by day.')],
    words: [W('sentinel', 'قيمة خاصة بتقول للـ loop يقف', 'a special value that tells a loop to stop', '"done" is the sentinel here.'),
      W('running sum', 'مجموع بيتحدّث مع كل عنصر', 'a total updated with each item', 'Print the running sum after each day.')],
    quiz: [Q(B('في المثال، الرقم 999 بعد done:', 'In the example, 999 after done:'), ['is never read', 'is added', 'causes an error'], 0, B('الـ loop وقفت.', 'The loop stopped.'))] },
  { learn: [L(B('enumerate وzip', 'enumerate and zip'),
      B('`enumerate(items, start=1)` بيدّيك رقم وعنصر مع بعض (بدل `range(len(...))`). و`zip(names, prices)` بيمشي على قايمتين جنب بعض. `zip(..., strict=True)` (بايثون 3.10+) بيطلع خطأ لو الطولين مختلفين بدل ما يسكت.',
        '`enumerate(items, start=1)` gives you a number and an item together (instead of `range(len(...))`). `zip(names, prices)` walks two lists side by side. `zip(..., strict=True)` (Python 3.10+) raises an error if the lengths differ instead of staying silent.'),
      'for i, name in enumerate(names, start=1):\n    print(i, name)\nfor name, price in zip(names, prices, strict=True):\n    print(name, price)')],
    code: [C(B('قايمة مرقّمة من قايمتين', 'A numbered list from two lists'),
      'names = ["Tea", "Coffee", "Juice"]\nprices = [15, 25, 30]\nfor i, (name, price) in enumerate(zip(names, prices, strict=True), start=1):\n    print(f"{i}. {name:<8}{price:>4} EGP")\ntry:\n    list(zip(names, [1, 2], strict=True))\nexcept ValueError as e:\n    print("Error:", e)')],
    practice: [B('اطبع قايمة طلاب ودرجاتهم مرقّمة من 1 بـ enumerate وzip.', 'Print a numbered list of students and their scores from 1 with enumerate and zip.'),
      B('حوّل loop بـ `range(len(x))` عندك لـ enumerate.', 'Turn one of your `range(len(x))` loops into enumerate.')],
    words: [W('enumerate', 'بيدّي رقم مع كل عنصر في loop', 'gives a number with each item in a loop', 'enumerate starts at 0 unless you set start.'),
      W('zip', 'بيمشي على كذا قايمة مع بعض', 'walks several lists together', 'zip pairs names with prices.')],
    quiz: [Q(B('`list(enumerate("ab", 1))` =', '`list(enumerate("ab", 1))` ='), ['[(1, "a"), (2, "b")]', '[(0, "a"), (1, "b")]', '["a", "b"]'], 0, B('start=1.', 'start=1.'))] },
  { learn: [L(B('match بأنماط', 'match with patterns'),
      B('`match` مش بس قيم ثابتة: `case ["add", item]` بيطابق قايمة من كلمتين ويحط التانية في `item`. `case {"type": "order", "id": oid}` بيطابق dict. `case _` الحالة الافتراضية. ده مثالي لأوامر بوت أو أحداث webhook.',
        '`match` is not only for fixed values: `case ["add", item]` matches a two-word list and puts the second word in `item`. `case {"type": "order", "id": oid}` matches a dict. `case _` is the default case. Perfect for bot commands or webhook events.'),
      'match command.split():\n    case ["add", item]: print("adding", item)\n    case ["remove", item]: print("removing", item)\n    case _: print("unknown")')],
    code: [C(B('توزيع أحداث webhook', 'Routing webhook events'),
      'events = [\n    {"type": "order", "id": 7, "total": 300},\n    {"type": "refund", "id": 7},\n    {"type": "ping"},\n]\nfor e in events:\n    match e:\n        case {"type": "order", "id": oid, "total": t}:\n            print(f"new order {oid}: {t} EGP")\n        case {"type": "refund", "id": oid}:\n            print(f"refund for {oid}")\n        case _:\n            print("ignored:", e["type"])')],
    practice: [B('اعمل منيو أوامر نصية (`add tea`، `remove tea`، `list`، `quit`) بـ match.', 'Build a text command menu (`add tea`, `remove tea`, `list`, `quit`) with match.'),
      B('ضيف `case` لحدث جديد واختبره.', 'Add a `case` for a new event and test it.')],
    words: [W('pattern matching', 'مطابقة شكل البيانات وتطلّع أجزاءها', 'matching the shape of data and pulling out its parts', 'Use pattern matching for webhook events.'),
      W('fallback case', 'الحالة اللي بتمسك أي حاجة تانية', 'the case that catches everything else', 'case _ is the fallback case.')],
    quiz: [Q(B('`case _:` معناها:', '`case _:` means:'), ['any other value', 'an empty string', 'an error'], 0, B('الحالة الافتراضية.', 'The default case.'))] },
  { review: [B('⚡ ternary وguard clauses، والـ walrus وfor…else.', '⚡ Ternaries and guard clauses, the walrus and for…else.'),
      B('⚡ sentinel والمجموع الجاري، وenumerate/zip(strict)، وmatch بأنماط: اعمل منيو بوت كامل.', '⚡ Sentinels and running sums, enumerate/zip(strict), and match with patterns: build a full bot menu.')] }
] };
