// Python week 4 — the intensive hour (weeks 1–12 are 3 hours a day). Merged into the week by tools/build_weeks.js.
// Every code sample has run: 1, so tools/test_python_examples.js runs it.
const B = (ar, en) => ({ ar, en });
const L = (h, p, ex) => ({ h, p, ex });
const C = (u, p) => ({ u, p, run: 1 });
const W = (t, ar, en, ex) => ({ t, m: B(ar, en), ex });
const Q = (q, o, a, why) => ({ q, o, a, why });
module.exports = { days: [
  { learn: [L(B('append وextend وbisect', 'append, extend and bisect'),
      B('`append(x)` بيضيف عنصر واحد (حتى لو قايمة → قايمة جوه قايمة). `extend(xs)` بيضيف كل عناصر قايمة تانية. ولو القايمة مترتبة وعايز تضيف وتفضل مترتبة: `bisect.insort(lst, x)` — أسرع من append وsort كل مرة.',
        '`append(x)` adds one item (even a list → a list inside the list). `extend(xs)` adds every item of another list. If the list is sorted and must stay sorted: `bisect.insort(lst, x)` — faster than append then sort every time.'),
      'a = [1, 2]; a.append([3, 4])   # [1, 2, [3, 4]]\nb = [1, 2]; b.extend([3, 4])   # [1, 2, 3, 4]\nbisect.insort(prices, 45)       # stays sorted')],
    code: [C(B('الفرق بين append وextend وinsort', 'append versus extend and insort'),
      'import bisect\na = [1, 2]\na.append([3, 4])\nb = [1, 2]\nb.extend([3, 4])\nprint(a, b)\nprices = [10, 20, 40, 80]\nbisect.insort(prices, 45)\nprint(prices)\nprint("45 is at index", bisect.bisect_left(prices, 45))')],
    practice: [B('ادمج 3 قوايم طلبات في قايمة واحدة بـ extend.', 'Merge 3 order lists into one with extend.'),
      B('حافظ على قايمة أسعار مترتبة وانت بتضيف 6 أسعار بـ insort.', 'Keep a price list sorted while adding 6 prices with insort.')],
    words: [W('append', 'تضيف عنصر واحد في آخر القايمة', 'to add one item to the end of a list', 'Append each new order to the list.'),
      W('bisect', 'مكتبة بتدوّر وتضيف في قايمة مترتبة بسرعة', 'a module for fast search and insert in a sorted list', 'Use bisect to keep the list sorted.')],
    quiz: [Q(B('`[1].append([2])` بيخلي القايمة:', '`[1].append([2])` makes the list:'), ['[1, [2]]', '[1, 2]', '[[1, 2]]'], 0, B('append بيضيف عنصر واحد زي ما هو.', 'append adds one item as it is.'))] },
  { learn: [L(B('الترتيب بأكتر من مفتاح', 'Sorting by several keys'),
      B('`sorted(orders, key=lambda o: (o["city"], -o["total"]))` بيرتّب بالمدينة وبعدين بالإجمالي تنازلي (الـ `-` للأرقام). والترتيب في بايثون **stable**: العناصر المتساوية بتحافظ على ترتيبها الأصلي — فتقدر ترتّب على مرحلتين: بالمفتاح الأقل أهمية الأول.',
        '`sorted(orders, key=lambda o: (o["city"], -o["total"]))` sorts by city, then by total descending (the `-` works for numbers). Python’s sort is **stable**: equal items keep their original order — so you can sort in two passes: the less important key first.'),
      'by_city_then_total = sorted(orders, key=lambda o: (o["city"], -o["total"]))\norders.sort(key=lambda o: o["total"], reverse=True)\norders.sort(key=lambda o: o["city"])   # stable: totals stay ordered within each city')],
    code: [C(B('ترتيب بالمدينة ثم الإجمالي', 'Sort by city, then total'),
      'orders = [\n    {"id": 1, "city": "Giza", "total": 300},\n    {"id": 2, "city": "Cairo", "total": 150},\n    {"id": 3, "city": "Giza", "total": 500},\n    {"id": 4, "city": "Cairo", "total": 900},\n]\nfor o in sorted(orders, key=lambda o: (o["city"], -o["total"])):\n    print(o["city"], o["total"], o["id"])')],
    practice: [B('رتّب طلاب بالدرجة تنازلي وبعدين بالاسم أبجدي للي درجاتهم زي بعض.', 'Sort students by score descending, then by name for equal scores.'),
      B('اعمل نفس الترتيب على مرحلتين باستغلال الـ stability.', 'Do the same sort in two passes using stability.')],
    words: [W('sorted', 'بترجّع نسخة مترتبة من غير ما تغيّر الأصل', 'returns a sorted copy without changing the original', 'sorted keeps the original list as it was.'),
      W('sort stability', 'العناصر المتساوية بتفضل بترتيبها', 'equal items keep their order', 'Sort stability lets you sort in two passes.')],
    quiz: [Q(B('الفرق بين `sorted(x)` و`x.sort()`:', 'The difference between `sorted(x)` and `x.sort()`:'), ['sorted returns a new list; sort changes x', 'none', 'sort returns a new list'], 0, B('sort بيرجّع None.', 'sort returns None.'))] },
  { learn: [L(B('comprehension بشرط وجدول تكرار', 'Comprehensions with conditions, and frequency tables'),
      B('`[x for x in items if cond]` فلترة، و`[a if cond else b for x in items]` تحويل حسب شرط (لاحظ المكان). و**جدول التكرار** بـ dict comprehension: `{w: words.count(w) for w in set(words)}` — بسيط للقوايم الصغيرة (وفي أسبوع 5 هتشوف Counter الأسرع).',
        '`[x for x in items if cond]` filters, and `[a if cond else b for x in items]` transforms by a condition (note the position). A **frequency table** with a dict comprehension: `{w: words.count(w) for w in set(words)}` — fine for small lists (week 5 shows the faster Counter).'),
      'paid = [o for o in orders if o["paid"]]\nlabels = ["big" if t > 500 else "small" for t in totals]\nfreq = {w: words.count(w) for w in set(words)}')],
    code: [C(B('فلترة وتصنيف وتكرار', 'Filter, label and count'),
      'totals = [120, 800, 45, 650, 300]\nbig = [t for t in totals if t > 500]\nlabels = ["big" if t > 500 else "small" for t in totals]\nprint(big)\nprint(labels)\ncities = ["Giza", "Cairo", "Giza", "Alex", "Giza"]\nfreq = {c: cities.count(c) for c in sorted(set(cities))}\nprint(freq)')],
    practice: [B('من قايمة إيميلات طلّع اللي على gmail بس، وحوّلهم لحروف صغيرة في نفس الـ comprehension.', 'From a list of emails keep only gmail ones, lowercased, in one comprehension.'),
      B('اعمل جدول تكرار لحروف كلمة.', 'Make a frequency table of the letters in a word.')],
    words: [W('comprehension', 'طريقة مختصرة تبني بيها قايمة أو dict', 'a short way to build a list or dict', 'A list comprehension replaced the loop.'),
      W('frequency table', 'جدول بعدد مرات ظهور كل قيمة', 'a table of how often each value appears', 'Build a frequency table of cities.')],
    quiz: [Q(B('الصح:', 'Correct:'), ['[x if x > 0 else 0 for x in xs]', '[x for x in xs if x > 0 else 0]', '[if x > 0: x for x in xs]'], 0, B('if/else قبل for.', 'if/else goes before for.'))] },
  { learn: [L(B('النسخة العميقة وفك القوايم بـ *', 'Deep copies and unpacking with *'),
      B('`copy.deepcopy(data)` بينسخ كل المستويات — لازم لما عندك قوايم جوه قوايم. و`*` في الفك: `first, *rest = items` و`*middle, last = items`. وفي الاستدعاء: `print(*items)` بيبعت كل عنصر كقيمة منفصلة.',
        '`copy.deepcopy(data)` copies every level — needed when you have lists inside lists. And `*` in unpacking: `first, *rest = items` and `*middle, last = items`. In a call: `print(*items)` passes each item as a separate value.'),
      'import copy\nbackup = copy.deepcopy(table)\nfirst, *rest = [1, 2, 3, 4]   # 1, [2, 3, 4]\nprint(*["a", "b"], sep=", ")')],
    code: [C(B('نسخة سطحية مقابل عميقة', 'Shallow versus deep copy'),
      'import copy\ntable = [["Tea", 15], ["Coffee", 25]]\nshallow = table.copy()\ndeep = copy.deepcopy(table)\ntable[0][1] = 99\nprint("shallow:", shallow)\nprint("deep:", deep)\nhead, *others = ["id", "name", "phone", "city"]\nprint(head, others)\nprint(*others, sep=" | ")')],
    practice: [B('خُد نسخة احتياطية من جدول قبل ما تعدّله، واتأكد إن الأصل اتغيّر والنسخة لأ.', 'Back up a table before editing it, and check the original changed but the backup did not.'),
      B('افصل أول سطر في CSV (العناوين) عن الباقي بـ `head, *rows = lines`.', 'Split the first CSV line (the headers) from the rest with `head, *rows = lines`.')],
    words: [W('deep copy', 'نسخة كاملة لكل المستويات', 'a full copy of every level', 'Make a deep copy before changing nested lists.'),
      W('unpacking operator', 'العلامة * اللي بتفك قايمة', 'the * sign that unpacks a list', 'print(*items) uses the unpacking operator.')],
    quiz: [Q(B('`a, *b = [1, 2, 3]` → b =', '`a, *b = [1, 2, 3]` → b ='), ['[2, 3]', '2', '(2, 3)'], 0, B('* بتجمع الباقي في قايمة.', '* gathers the rest into a list.'))] },
  { learn: [L(B('جداول: عمود، صف، ومجموع', 'Tables: columns, rows and totals'),
      B('جدول = قايمة صفوف (**row-major**). عمود: `[row[1] for row in table]`. مجموع كل صف: `[sum(r) for r in table]`. ومجموع الأعمدة: `[sum(col) for col in zip(*table)]` — الـ `zip(*table)` بيقلب الجدول. ده أساس أي تقرير قبل ما تستخدم pandas.',
        'A table = a list of rows (**row-major**). A column: `[row[1] for row in table]`. Each row’s total: `[sum(r) for r in table]`. Column totals: `[sum(col) for col in zip(*table)]` — `zip(*table)` flips the table. This is the basis of any report before you use pandas.'),
      'sales = [[10, 20, 30], [5, 15, 25]]\nrow_totals = [sum(r) for r in sales]          # [60, 45]\ncol_totals = [sum(c) for c in zip(*sales)]    # [15, 35, 55]')],
    code: [C(B('تقرير مبيعات أسبوع', 'A week’s sales report'),
      'days = ["Sat", "Sun", "Mon"]\nsales = [\n    ["Tea", 10, 12, 8],\n    ["Coffee", 20, 18, 25],\n    ["Juice", 5, 9, 4],\n]\nprint(f"{\'item\':<8}" + "".join(f"{d:>6}" for d in days) + f"{\'total\':>7}")\nfor name, *nums in sales:\n    print(f"{name:<8}" + "".join(f"{n:>6}" for n in nums) + f"{sum(nums):>7}")\ncols = [sum(c) for c in zip(*[r[1:] for r in sales])]\nprint(f"{\'total\':<8}" + "".join(f"{n:>6}" for n in cols) + f"{sum(cols):>7}")')],
    practice: [B('ضيف عمود «متوسط» وصف «أعلى يوم» للتقرير.', 'Add an «average» column and a «best day» row to the report.'),
      B('اقلب جدول 3×4 بـ `zip(*table)` واطبعه.', 'Flip a 3×4 table with `zip(*table)` and print it.')],
    words: [W('matrix', 'جدول أرقام صفوف وأعمدة', 'a table of numbers in rows and columns', 'Store the sales as a matrix.'),
      W('row-major', 'تخزين الجدول صف ورا صف', 'storing a table row after row', 'A list of rows is row-major.')],
    quiz: [Q(B('`list(zip(*[[1, 2], [3, 4]]))` =', '`list(zip(*[[1, 2], [3, 4]]))` ='), ['[(1, 3), (2, 4)]', '[(1, 2), (3, 4)]', '[1, 2, 3, 4]'], 0, B('الأعمدة بقت صفوف.', 'Columns became rows.'))] },
  { review: [B('⚡ append/extend/insort، والترتيب بأكتر من مفتاح والـ stability.', '⚡ append/extend/insort, sorting by several keys and stability.'),
      B('⚡ comprehensions بشرط، وdeepcopy و*، والجداول بـ zip(*): استخدمهم في مشروع الشهر.', '⚡ Comprehensions with conditions, deepcopy and *, and tables with zip(*): use them in the month project.')] }
] };
