// Python week 5 — the intensive hour (weeks 1–12 are 3 hours a day). Merged into the week by tools/build_weeks.js.
// Every code sample has run: 1, so tools/test_python_examples.js runs it.
const B = (ar, en) => ({ ar, en });
const L = (h, p, ex) => ({ h, p, ex });
const C = (u, p) => ({ u, p, run: 1 });
const W = (t, ar, en, ex) => ({ t, m: B(ar, en), ex });
const Q = (q, o, a, why) => ({ q, o, a, why });
module.exports = { days: [
  { learn: [L(B('get وsetdefault ودمج الـ dicts', 'get, setdefault and merging dicts'),
      B('`d.get("phone", "-")` بيرجّع قيمة بديلة لو المفتاح مش موجود بدل KeyError. `d.setdefault("tags", [])` بيحط قيمة لو مش موجودة ويرجّعها. ودمج dict بـ `|`: `settings = defaults | user_settings` (اللي على اليمين بيكسب).',
        '`d.get("phone", "-")` returns a fallback when the key is missing instead of a KeyError. `d.setdefault("tags", [])` sets a value if missing and returns it. Merge dicts with `|`: `settings = defaults | user_settings` (the right side wins).'),
      'phone = customer.get("phone", "-")\ncustomer.setdefault("tags", []).append("vip")\nsettings = {"lang": "ar", "tz": "Africa/Cairo"} | {"lang": "en"}')],
    code: [C(B('إعدادات افتراضية وdict ناقص', 'Default settings and a partial dict'),
      'defaults = {"lang": "ar", "currency": "EGP", "tz": "Africa/Cairo"}\nuser = {"lang": "en"}\nsettings = defaults | user\nprint(settings)\ncustomer = {"name": "Sara"}\nprint(customer.get("phone", "no phone"))\ncustomer.setdefault("tags", []).append("vip")\ncustomer.setdefault("tags", []).append("new")\nprint(customer)')],
    practice: [B('ادمج 3 مستويات إعدادات (افتراضي، شركة، مستخدم) بـ `|`.', 'Merge 3 levels of settings (default, company, user) with `|`.'),
      B('اعمل فهرس أسماء حسب أول حرف بـ setdefault.', 'Build an index of names by first letter with setdefault.')],
    words: [W('get method', 'dict.get: قراءة مفتاح بقيمة بديلة', 'dict.get: reading a key with a fallback', 'Use the get method for optional fields.'),
      W('setdefault', 'تحط قيمة للمفتاح لو مش موجود وترجّعها', 'sets a key’s value if missing and returns it', 'setdefault creates the list on first use.')],
    quiz: [Q(B('`{"a": 1} | {"a": 2}` =', '`{"a": 1} | {"a": 2}` ='), ['{"a": 2}', '{"a": 1}', '{"a": [1, 2]}'], 0, B('اليمين بيكسب.', 'The right side wins.'))] },
  { learn: [L(B('التجميع بمفتاح', 'Grouping by a key'),
      B('عايز الطلبات متجمعة حسب المدينة؟ `groups.setdefault(o["city"], []).append(o)`، أو `defaultdict(list)`. المفتاح ممكن يكون **tuple** لو التجميع بأكتر من حاجة: `(city, month)`. وبعدين احسب لكل مجموعة: العدد والمجموع.',
        'Want orders grouped by city? `groups.setdefault(o["city"], []).append(o)`, or `defaultdict(list)`. The key can be a **tuple** to group by more than one thing: `(city, month)`. Then compute per group: the count and the sum.'),
      'groups = {}\nfor o in orders:\n    key = (o["city"], o["date"][:7])\n    groups.setdefault(key, []).append(o["total"])')],
    code: [C(B('مبيعات حسب المدينة والشهر', 'Sales by city and month'),
      'orders = [\n    {"city": "Giza", "date": "2026-09-03", "total": 300},\n    {"city": "Giza", "date": "2026-09-20", "total": 200},\n    {"city": "Cairo", "date": "2026-09-11", "total": 450},\n    {"city": "Giza", "date": "2026-10-01", "total": 120},\n]\ngroups = {}\nfor o in orders:\n    key = (o["city"], o["date"][:7])\n    groups.setdefault(key, []).append(o["total"])\nfor (city, month), totals in sorted(groups.items()):\n    print(f"{city:<6} {month}  orders: {len(totals)}  sum: {sum(totals)}")')],
    practice: [B('جمّع رسايل دعم حسب (القناة، الأولوية) واطبع العدد.', 'Group support messages by (channel, priority) and print the counts.'),
      B('لكل مجموعة اطبع أكبر وأصغر قيمة.', 'For each group print the largest and smallest value.')],
    words: [W('lookup', 'البحث عن قيمة بمفتاحها', 'finding a value by its key', 'A dict lookup is very fast.'),
      W('group key', 'القيمة اللي بتجمّع بيها العناصر', 'the value you group items by', 'Use (city, month) as the group key.')],
    quiz: [Q(B('مفتاح dict ممكن يكون:', 'A dict key can be:'), ['a tuple', 'a list', 'a dict'], 0, B('لازم يكون immutable.', 'It must be immutable.'))] },
  { learn: [L(B('تسطيح البيانات المتداخلة', 'Flattening nested data'),
      B('ردود الـ APIs متداخلة: `{"customer": {"name": ..., "address": {"city": ...}}}`. للشيت محتاج صف مسطّح: `customer.name`، `customer.address.city`. دالة صغيرة recursive بتمشي على كل مستوى وتجمع الأسماء بالنقط.',
        'API responses are nested: `{"customer": {"name": ..., "address": {"city": ...}}}`. A sheet needs a flat row: `customer.name`, `customer.address.city`. A small recursive function walks each level and joins the names with dots.'),
      'flatten({"a": {"b": 1, "c": {"d": 2}}})\n# {"a.b": 1, "a.c.d": 2}')],
    code: [C(B('دالة flatten', 'A flatten function'),
      'def flatten(d, prefix=""):\n    row = {}\n    for key, value in d.items():\n        name = f"{prefix}.{key}" if prefix else key\n        if isinstance(value, dict):\n            row |= flatten(value, name)\n        else:\n            row[name] = value\n    return row\n\norder = {"id": 7, "customer": {"name": "Sara", "address": {"city": "Giza", "zip": "12511"}}, "total": 300}\nfor k, v in flatten(order).items():\n    print(f"{k:<24} {v}")')],
    practice: [B('جرّب flatten على رد API حقيقي (من jsonplaceholder) واطبع الأعمدة.', 'Try flatten on a real API response (from jsonplaceholder) and print the columns.'),
      B('عدّلها عشان القوايم تتحوّل لنص مفصول بفاصلة.', 'Change it so lists become comma-joined text.')],
    words: [W('nested dict', 'dict جواه dict', 'a dict inside a dict', 'The address is a nested dict.'),
      W('flatten', 'تحوّل بيانات متداخلة لمستوى واحد', 'to turn nested data into one level', 'Flatten the response before saving it to the sheet.')],
    quiz: [Q(B('`flatten({"a": {"b": 1}})` =', '`flatten({"a": {"b": 1}})` ='), ['{"a.b": 1}', '{"a": 1}', '{"b": 1}'], 0, B('الأسماء بتتجمع بالنقط.', 'Names are joined with dots.'))] },
  { learn: [L(B('عمليات الـ sets وfrozenset', 'Set operations and frozenset'),
      B('`a | b` الاتحاد (الكل)، `a & b` التقاطع (المشترك)، `a - b` الفرق (في a بس)، `a ^ b` في واحد بس منهم. مثال: عملاء الشهر ده `-` عملاء الشهر اللي فات = العملاء الجداد. و**frozenset** set مش بيتغيّر، فينفع يبقى مفتاح في dict.',
        '`a | b` union (all), `a & b` intersection (shared), `a - b` difference (only in a), `a ^ b` in exactly one. Example: this month’s customers `-` last month’s = new customers. A **frozenset** is a set that cannot change, so it can be a dict key.'),
      'new_customers = this_month - last_month\nreturning = this_month & last_month\nlost = last_month - this_month')],
    code: [C(B('عملاء جداد ورجعوا وضاعوا', 'New, returning and lost customers'),
      'last_month = {"sara", "omar", "mona", "ali"}\nthis_month = {"sara", "mona", "hany", "nour"}\nprint("new:", sorted(this_month - last_month))\nprint("returning:", sorted(this_month & last_month))\nprint("lost:", sorted(last_month - this_month))\nprint("all:", len(this_month | last_month))\npairs = {frozenset({"tea", "cake"}): 12}\nprint(pairs[frozenset({"cake", "tea"})])')],
    practice: [B('قارن قايمتين إيميلات (المشتركين، اللي فتحوا الرسالة) واطلع اللي مفتحوش.', 'Compare two email lists (subscribers, openers) and find who did not open.'),
      B('اعمل dict مفتاحه frozenset لعدد مرات شراء منتجين مع بعض.', 'Make a dict keyed by frozenset counting how often two products are bought together.')],
    words: [W('set union', 'كل العناصر في setين من غير تكرار', 'all items in two sets without repeats', 'The set union gives every customer.'),
      W('frozenset', 'set مش بيتغيّر ينفع يبقى مفتاح', 'an unchangeable set that can be a key', 'Use a frozenset as a dict key.')],
    quiz: [Q(B('العملاء الجداد =', 'New customers ='), ['this_month - last_month', 'this_month & last_month', 'last_month - this_month'], 0, B('موجودين دلوقتي بس.', 'Only in the current month.'))] },
  { learn: [L(B('JSON: أنواع مش مدعومة وindent', 'JSON: unsupported types and indent'),
      B('`json.dumps` مش بيعرف `datetime` ولا `Decimal` ولا `set`. الحل: `default=str` (يحوّلهم نص) أو تحوّلهم بنفسك. و`indent=2` للقراية، و`ensure_ascii=False` عشان العربي يظهر حروف مش `\\u0633`. و`sort_keys=True` يخلّي الملفات ثابتة في Git.',
        '`json.dumps` does not know `datetime`, `Decimal` or `set`. Fix: `default=str` (turns them into text) or convert them yourself. Use `indent=2` for reading, and `ensure_ascii=False` so Arabic shows as letters, not `\\u0633`. `sort_keys=True` keeps files stable in Git.'),
      'json.dumps(data, default=str, ensure_ascii=False, indent=2, sort_keys=True)')],
    code: [C(B('JSON فيه تاريخ وعربي', 'JSON with a date and Arabic'),
      'import json\nfrom datetime import date\nfrom decimal import Decimal\norder = {"name": "سارة", "total": Decimal("350.50"), "day": date(2026, 10, 3), "tags": {"vip"}}\ntry:\n    json.dumps(order)\nexcept TypeError as e:\n    print("Error:", e)\norder["tags"] = sorted(order["tags"])\nprint(json.dumps(order, default=str, ensure_ascii=False, indent=2, sort_keys=True))')],
    practice: [B('احفظ قايمة عملاء عربي في JSON مقروء، وافتحه في VS Code.', 'Save a list of Arabic customer names as readable JSON and open it in VS Code.'),
      B('اكتب دالة `to_json_safe` بتحوّل Decimal لـ float وdate لـ ISO.', 'Write a `to_json_safe` function that turns Decimal into float and date into ISO.')],
    words: [W('serialization', 'تحويل بيانات لنص زي JSON عشان تتحفظ أو تتبعت', 'turning data into text such as JSON to store or send', 'datetime needs help during serialization.'),
      W('indent', 'المسافة في أول السطر عشان التنسيق', 'the space at the start of a line for layout', 'Use indent=2 for readable JSON.')],
    quiz: [Q(B('عشان العربي يظهر حروف في JSON:', 'To show Arabic as letters in JSON:'), ['ensure_ascii=False', 'indent=2', 'sort_keys=True'], 0, B('من غيرها بيبقى \\u….', 'Without it you get \\u….'))] },
  { review: [B('⚡ get/setdefault و|، والتجميع بمفتاح tuple، وflatten.', '⚡ get/setdefault and |, grouping by a tuple key, and flatten.'),
      B('⚡ عمليات الـ sets وfrozenset، وJSON مع التواريخ والعربي: حلّل بيانات طلبات شهرين.', '⚡ Set operations and frozenset, and JSON with dates and Arabic: analyse two months of orders.')] }
] };
