// Python week 6 — the intensive hour (weeks 1–12 are 3 hours a day). Merged into the week by tools/build_weeks.js.
// Every code sample has run: 1, so tools/test_python_examples.js runs it.
const B = (ar, en) => ({ ar, en });
const L = (h, p, ex) => ({ h, p, ex });
const C = (u, p) => ({ u, p, run: 1 });
const W = (t, ar, en, ex) => ({ t, m: B(ar, en), ex });
const Q = (q, o, a, why) => ({ q, o, a, why });
module.exports = { days: [
  { learn: [L(B('الـ recursion', 'Recursion'),
      B('دالة بتنادي نفسها على جزء أصغر من المشكلة. لازم **base case** (حالة بتقف فيها) وإلا هتلف لحد `RecursionError`. مثالي للبيانات المتداخلة (فولدرات جوه فولدرات، JSON جوه JSON). لو المشكلة مسطّحة، loop عادي أوضح.',
        'A function that calls itself on a smaller part of the problem. It needs a **base case** (where it stops) or it runs until `RecursionError`. Ideal for nested data (folders in folders, JSON in JSON). If the problem is flat, a plain loop is clearer.'),
      'def count_items(node):\n    if not isinstance(node, list):   # base case\n        return 1\n    return sum(count_items(x) for x in node)')],
    code: [C(B('عدّ العناصر في قوايم متداخلة', 'Counting items in nested lists'),
      'def depth(node):\n    if not isinstance(node, (list, dict)):\n        return 0\n    children = node.values() if isinstance(node, dict) else node\n    return 1 + max((depth(c) for c in children), default=0)\n\ndata = {"orders": [{"lines": [{"sku": "A"}, {"sku": "B"}]}]}\nprint("depth:", depth(data))\n\ndef total(node):\n    if isinstance(node, (int, float)):\n        return node\n    return sum(total(x) for x in node)\nprint(total([1, [2, 3], [4, [5]]]))')],
    practice: [B('اكتب دالة recursive تطلع كل المفاتيح في JSON متداخل.', 'Write a recursive function that lists every key in nested JSON.'),
      B('شيل الـ base case وشوف الخطأ اللي بيطلع.', 'Remove the base case and see the error you get.')],
    words: [W('recursion', 'دالة بتنادي نفسها', 'a function calling itself', 'Recursion suits nested folders.'),
      W('base case', 'الحالة اللي الـ recursion بتقف عندها', 'the case where recursion stops', 'Without a base case it never stops.')],
    quiz: [Q(B('من غير base case:', 'Without a base case:'), ['RecursionError', 'it returns 0', 'it runs once'], 0, B('بتلف لحد ما المكدس يتملي.', 'It loops until the stack is full.'))] },
  { learn: [L(B('معاملات keyword-only وpartial', 'Keyword-only parameters and partial'),
      B('أي parameter بعد `*` لازم يتبعت بالاسم: `def send(to, *, dry_run=False)` — فمحدش يكتب `send("x", True)` ويبقى مش فاهم True دي إيه. و`functools.partial(send, dry_run=True)` بيعمل نسخة من الدالة بقيمة متثبّتة.',
        'Any parameter after `*` must be passed by name: `def send(to, *, dry_run=False)` — so nobody writes `send("x", True)` without knowing what True means. And `functools.partial(send, dry_run=True)` makes a copy of the function with that value fixed.'),
      'def send(to, *, dry_run=False): ...\nsend("sara@x.com", dry_run=True)   # ✓\nsend("sara@x.com", True)           # TypeError\ntest_send = partial(send, dry_run=True)')],
    code: [C(B('keyword-only وpartial', 'Keyword-only and partial'),
      'from functools import partial\n\ndef send(to, subject, *, dry_run=False):\n    action = "WOULD SEND" if dry_run else "SENT"\n    return f"{action} to {to}: {subject}"\n\nprint(send("sara@example.com", "Hi", dry_run=True))\ntry:\n    send("sara@example.com", "Hi", True)\nexcept TypeError as e:\n    print("Error:", e)\ntest_send = partial(send, dry_run=True)\nprint(test_send("omar@example.com", "Report"))')],
    practice: [B('خلّي flag مهم في دالة عندك keyword-only.', 'Make an important flag in one of your functions keyword-only.'),
      B('اعمل بـ partial دالة `to_cairo` من دالة تحويل توقيت عامة.', 'Use partial to make a `to_cairo` function from a general time zone converter.')],
    words: [W('keyword-only', 'معامل لازم يتبعت باسمه', 'a parameter that must be passed by name', 'dry_run is keyword-only.'),
      W('partial', 'نسخة من دالة بقيم متثبّتة', 'a copy of a function with some values fixed', 'partial(send, dry_run=True) is safe for tests.')],
    quiz: [Q(B('`def f(a, *, b)` → `f(1, 2)`:', '`def f(a, *, b)` → `f(1, 2)`:'), ['TypeError', 'works', 'b = None'], 0, B('b لازم بالاسم.', 'b must be named.'))] },
  { learn: [L(B('global ودوال نضيفة', 'global and clean functions'),
      B('`global x` بيخلّي الدالة تغيّر متغيّر بره — ده بيصعّب التتبع والاختبار. الأحسن: الدالة تاخد اللي محتاجاه كمعاملات وترجّع النتيجة (**pure**: نفس المدخلات = نفس المخرجات، ومن غير أثر جانبي). خلّي الطباعة والملفات في طرف البرنامج، والحساب في دوال pure.',
        '`global x` lets a function change an outside variable — this makes tracing and testing hard. Better: the function takes what it needs as parameters and returns the result (**pure**: same inputs = same outputs, no side effects). Keep printing and files at the edges of the program, and calculations in pure functions.'),
      '# ✗\ntotal = 0\ndef add(x):\n    global total\n    total += x\n# ✓\ndef add(total, x):\n    return total + x')],
    code: [C(B('من global لدالة pure', 'From global to a pure function'),
      'def apply_discount(prices, percent):\n    return [round(p * (1 - percent / 100), 2) for p in prices]\n\nprices = [100, 250, 80]\nprint(apply_discount(prices, 10))\nprint(apply_discount(prices, 10))  # same inputs, same result\nprint(prices)  # the original is unchanged')],
    practice: [B('دوّر على أي `global` في كودك وشيله بإنك ترجّع القيمة.', 'Find any `global` in your code and remove it by returning the value.'),
      B('قسّم سكربت لـ: قراءة (طرف)، حساب (pure)، كتابة (طرف).', 'Split a script into: reading (edge), calculating (pure), writing (edge).')],
    words: [W('global', 'متغيّر معرّف بره كل الدوال', 'a variable defined outside every function', 'Avoid changing a global inside functions.'),
      W('pure', 'دالة نتيجتها بتعتمد على مدخلاتها بس ومن غير أثر', 'a function whose result depends only on its inputs, with no side effects', 'Pure functions are easy to test.')],
    quiz: [Q(B('دالة pure:', 'A pure function:'), ['returns the same result for the same inputs', 'prints to the screen', 'changes a global'], 0, B('ومن غير أثر جانبي.', 'And has no side effects.'))] },
  { learn: [L(B('الـ generators وyield', 'Generators and yield'),
      B('`yield` بيرجّع قيمة ويوقف الدالة لحد ما تطلب اللي بعدها. الـ generator مش بيحمّل كل البيانات في الذاكرة — مثالي لملفات كبيرة أو صفحات API. و`(x * 2 for x in items)` generator expression (أقواس عادية بدل []).',
        '`yield` returns a value and pauses the function until you ask for the next. A generator does not load all the data into memory — ideal for big files or API pages. And `(x * 2 for x in items)` is a generator expression (round brackets instead of []).'),
      'def pages():\n    page = 1\n    while page <= 3:\n        yield fetch(page)\n        page += 1\nfor batch in pages(): ...')],
    code: [C(B('generator لصفحات', 'A generator for pages'),
      'def fake_pages(total_items, page_size):\n    for start in range(0, total_items, page_size):\n        print(f"  (fetching items {start}..{min(start + page_size, total_items) - 1})")\n        yield list(range(start, min(start + page_size, total_items)))\n\nfor page in fake_pages(7, 3):\n    print("got", page)\nsquares = (n * n for n in range(5))\nprint(sum(squares))')],
    practice: [B('اكتب generator بيرجّع سطور ملف نضيفة (من غير فاضي ولا تعليقات).', 'Write a generator that yields clean file lines (no blanks, no comments).'),
      B('قارن `sum([x for x in range(10**6)])` و`sum(x for x in range(10**6))`.', 'Compare `sum([x for x in range(10**6)])` and `sum(x for x in range(10**6))`.')],
    words: [W('generator', 'دالة بترجّع قيم واحدة واحدة بـ yield', 'a function that gives values one at a time with yield', 'A generator saves memory.'),
      W('yield', 'ترجّع قيمة وتوقف مؤقتًا', 'to return a value and pause', 'yield the next page.')],
    quiz: [Q(B('الـ generator ميزته الأساسية:', 'A generator’s main advantage:'), ['low memory use', 'faster typing', 'no loops'], 0, B('مش بيحمّل كله مرة واحدة.', 'It does not load everything at once.'))] },
  { learn: [L(B('doctest: أمثلة بتختبر نفسها', 'doctest: examples that test themselves'),
      B('اكتب مثال في الـ docstring بالشكل اللي بيظهر في الطرفية (`>>>`)، و`doctest.testmod()` بيشغّله ويقارن الناتج. كده التوثيق والاختبار حاجة واحدة، ولو حد غيّر الدالة غلط، المثال هيفشل. والـ `assert` جوه الكود للشروط اللي «مستحيل» تتكسر.',
        'Write an example in the docstring as it appears in the terminal (`>>>`), and `doctest.testmod()` runs it and compares the output. Docs and tests become one thing, and if someone breaks the function, the example fails. Use `assert` in code for conditions that «can never» break.'),
      'def vat(x):\n    """\n    >>> vat(100)\n    114.0\n    """\n    return x * 1.14')],
    code: [C(B('doctest يشتغل', 'A doctest running'),
      'import doctest\n\ndef egp(amount):\n    """Format an amount in Egyptian pounds.\n\n    >>> egp(1500)\n    \'1,500.00 EGP\'\n    >>> egp(0.5)\n    \'0.50 EGP\'\n    """\n    assert amount >= 0, "amount must not be negative"\n    return f"{amount:,.2f} EGP"\n\nresult = doctest.testmod()\nprint(result)')],
    practice: [B('ضيف doctest لـ 3 دوال عندك وشغّلهم.', 'Add doctests to 3 of your functions and run them.'),
      B('غيّر دالة عمدًا وشوف الـ doctest بيفشل إزاي.', 'Break a function on purpose and see how the doctest fails.')],
    words: [W('doctest', 'مثال في التوثيق بيتشغّل كاختبار', 'an example in docs that runs as a test', 'The doctest checks the format.'),
      W('assertion', 'شرط لازم يكون صح وإلا البرنامج يقف', 'a condition that must be true or the program stops', 'The assertion catches negative amounts.')],
    quiz: [Q(B('`doctest` بيقارن:', '`doctest` compares:'), ['the printed result with the example', 'two files', 'two functions'], 0, B('اللي بعد >>> بالناتج.', 'What follows >>> with the output.'))] },
  { review: [B('⚡ الـ recursion والـ base case، وkeyword-only وpartial.', '⚡ Recursion and the base case, keyword-only and partial.'),
      B('⚡ دوال pure بدل global، والـ generators، وdoctest: اكتب مكتبة دوال صغيرة باختباراتها.', '⚡ Pure functions instead of global, generators, and doctest: write a small library of functions with their tests.')] }
] };
