// Python week 7 — the intensive hour (weeks 1–12 are 3 hours a day). Merged into the week by tools/build_weeks.js.
// Every code sample has run: 1, so tools/test_python_examples.js runs it.
const B = (ar, en) => ({ ar, en });
const L = (h, p, ex) => ({ h, p, ex });
const C = (u, p) => ({ u, p, run: 1 });
const W = (t, ar, en, ex) => ({ t, m: B(ar, en), ex });
const Q = (q, o, a, why) => ({ q, o, a, why });
module.exports = { days: [
  { learn: [L(B('نقطة البداية: if __name__ == "__main__"', 'The entry point: if __name__ == "__main__"'),
      B('الكود اللي تحت `if __name__ == "__main__":` بيشتغل لما تشغّل الملف مباشرة بس، مش لما ملف تاني يعمله import. كده ملفك ينفع **سكربت** و**مكتبة** في نفس الوقت. وحط الشغل في دالة `main()` وناديها من هناك.',
        'Code under `if __name__ == "__main__":` runs only when you run the file directly, not when another file imports it. Your file then works as both a **script** and a **library**. Put the work in a `main()` function and call it from there.'),
      'def clean_phone(p): ...\n\ndef main():\n    print(clean_phone(" 010 1234 5678 "))\n\nif __name__ == "__main__":\n    main()')],
    code: [C(B('ملف سكربت ومكتبة', 'A file that is a script and a library'),
      'def clean_phone(raw):\n    digits = "".join(ch for ch in raw if ch.isdigit())\n    return "+20" + digits[1:] if digits.startswith("0") else "+" + digits\n\ndef main():\n    for p in [" 010 1234 5678 ", "201112223334"]:\n        print(repr(p), "->", clean_phone(p))\n\nprint("__name__ is", repr(__name__))\nif __name__ == "__main__":\n    main()')],
    practice: [B('اعمل ملف `tools.py` فيه دالتين و`main()`، واعمله import من ملف تاني واتأكد إن main مااشتغلتش.', 'Make a `tools.py` with two functions and `main()`, import it from another file and check main did not run.'),
      B('حوّل سكربت قديم عندك للشكل ده.', 'Convert an old script of yours to this shape.')],
    words: [W('entry point', 'المكان اللي البرنامج بيبدأ منه', 'the place where a program starts', 'main() is the entry point.'),
      W('shebang', 'أول سطر #! بيقول النظام يشغّل الملف بإيه', 'the first #! line telling the system what runs the file', '#!/usr/bin/env python3 is a shebang.')],
    quiz: [Q(B('لما ملف يتعمله import، `__name__` بيساوي:', 'When a file is imported, `__name__` equals:'), ['the module name', '"__main__"', 'None'], 0, B('"__main__" لما يتشغّل مباشرة بس.', '"__main__" only when run directly.'))] },
  { learn: [L(B('مكتبات جاهزة مفيدة: datetime وbase64 وhashlib', 'Useful built-ins: datetime, base64 and hashlib'),
      B('`datetime` للتواريخ والمدد (`timedelta(days=7)`). `base64` لتحويل بيانات لنص آمن في JSON أو headers (مش تشفير!). `hashlib.sha256` لبصمة ثابتة لبيانات — تعرف بيها لو ملف اتغيّر أو تعمل مفتاح منع تكرار.',
        '`datetime` for dates and durations (`timedelta(days=7)`). `base64` to turn data into text safe for JSON or headers (not encryption!). `hashlib.sha256` for a fixed fingerprint of data — to tell if a file changed or to make a de-duplication key.'),
      'due = date.today() + timedelta(days=14)\nbase64.b64encode(b"user:pass")     # b\'dXNlcjpwYXNz\'\nhashlib.sha256(b"hello").hexdigest()[:12]')],
    code: [C(B('تاريخ استحقاق وبصمة', 'A due date and a fingerprint'),
      'import base64, hashlib\nfrom datetime import date, timedelta\ninvoice_day = date(2026, 10, 3)\ndue = invoice_day + timedelta(days=14)\nprint("due:", due.isoformat(), due.strftime("%A"))\ntoken = base64.b64encode("sara:demo".encode()).decode()\nprint("base64:", token, "->", base64.b64decode(token).decode())\nrow = "1042|Sara|350"\nprint("fingerprint:", hashlib.sha256(row.encode()).hexdigest()[:16])')],
    practice: [B('احسب لـ 5 فواتير تاريخ الاستحقاق وعدد الأيام المتبقية.', 'Compute the due date and days left for 5 invoices.'),
      B('اعمل بصمة sha256 لكل سطر في قايمة واستخدمها لاكتشاف السطور المكررة.', 'Make a sha256 fingerprint of each line in a list and use it to find duplicate lines.')],
    words: [W('datetime', 'مكتبة التواريخ والأوقات', 'the dates and times module', 'Use datetime for due dates.'),
      W('base64 encode', 'تحويل bytes لنص آمن (مش تشفير)', 'turning bytes into safe text (not encryption)', 'Base64 encode the file before sending it as JSON.')],
    quiz: [Q(B('base64 هو:', 'base64 is:'), ['an encoding, not encryption', 'strong encryption', 'a hash'], 0, B('أي حد يقدر يفكّه.', 'Anyone can decode it.'))] },
  { learn: [L(B('ملف requirements وتثبيت الإصدارات', 'The requirements file and pinning versions'),
      B('`requirements.txt` فيه المكتبات اللي مشروعك محتاجها: `requests==2.32.3` (إصدار متثبّت بالظبط) أو `requests>=2.31,<3` (مدى). التثبيت الدقيق بيخلّي السكربت يشتغل نفس الشكل على جهاز العميل بعد سنة. `pip freeze > requirements.txt` بيكتب اللي متثبّت عندك.',
        '`requirements.txt` lists the libraries your project needs: `requests==2.32.3` (an exact pinned version) or `requests>=2.31,<3` (a range). Exact pins make the script behave the same on the client’s machine a year later. `pip freeze > requirements.txt` writes what you have installed.'),
      'requests==2.32.3\nopenpyxl>=3.1,<4\npython-dotenv==1.0.1\n\npip install -r requirements.txt')],
    code: [C(B('قراءة ملف requirements', 'Reading a requirements file'),
      'text = """requests==2.32.3\nopenpyxl>=3.1,<4\n# dev tools\npytest\n"""\nfor line in text.splitlines():\n    line = line.strip()\n    if not line or line.startswith("#"):\n        continue\n    for op in ("==", ">=", "<=", "~="):\n        if op in line:\n            name, rest = line.split(op, 1)\n            print(f"{name:<10} {op}{rest}")\n            break\n    else:\n        print(f"{line:<10} (not pinned)")')],
    practice: [B('اعمل `requirements.txt` لمشروعك وثبّت كل إصدار.', 'Create a `requirements.txt` for your project and pin every version.'),
      B('في venv جديد، ثبّت منه واتأكد إن السكربت شغال.', 'In a fresh venv, install from it and check the script runs.')],
    words: [W('requirements file', 'ملف بقايمة المكتبات المطلوبة', 'a file listing the libraries needed', 'Commit the requirements file to Git.'),
      W('version pin', 'تحديد إصدار مكتبة بالظبط', 'fixing a library to an exact version', 'A version pin avoids surprise updates.')],
    quiz: [Q(B('`requests==2.32.3` معناها:', '`requests==2.32.3` means:'), ['exactly this version', 'any version', 'at least this version'], 0, B('== تثبيت.', '== pins it.'))] },
  { learn: [L(B('بيئة معزولة قابلة للتكرار', 'An isolated, repeatable environment'),
      B('كل مشروع ليه venv لوحده عشان مكتبات مشروع ميتلخبطوش مع التاني. اتأكد إنك جوه البيئة: `sys.prefix != sys.base_prefix`. وأدوات زي **uv** بتعمل ملف قفل `uv.lock` بكل الإصدارات (حتى مكتبات المكتبات) عشان التثبيت يتكرر بالظبط.',
        'Each project gets its own venv so one project’s libraries do not clash with another’s. Check you are inside it: `sys.prefix != sys.base_prefix`. Tools like **uv** write a lock file `uv.lock` with every version (even libraries of libraries) so installs repeat exactly.'),
      'python -m venv .venv\n.venv\\Scripts\\activate      # Windows\nsource .venv/bin/activate   # macOS/Linux\nuv init && uv add requests  # writes pyproject.toml + uv.lock')],
    code: [C(B('أنا جوه venv؟', 'Am I inside a venv?'),
      'import sys\ninside = sys.prefix != sys.base_prefix\nprint("Python", sys.version.split()[0])\nprint("inside a virtual environment:", inside)\nprint("packages go to:", "the project venv" if inside else "the system Python")')],
    practice: [B('اعمل venv لمشروعين وثبّت إصدارين مختلفين من نفس المكتبة في كل واحد.', 'Create venvs for two projects and install different versions of the same library in each.'),
      B('جرّب uv: `uv init` و`uv add` وافتح الـ lock file.', 'Try uv: `uv init` and `uv add`, then open the lock file.')],
    words: [W('isolated', 'معزول عن الباقي', 'kept apart from the rest', 'Each project has an isolated environment.'),
      W('reproducible install', 'تثبيت بيطلع نفس النتيجة على أي جهاز', 'an install that gives the same result on any machine', 'A lock file gives a reproducible install.')],
    quiz: [Q(B('ليه venv لكل مشروع؟', 'Why a venv per project?'), ['so library versions do not clash', 'to make Python faster', 'to hide the code'], 0, B('كل مشروع ومكتباته.', 'Each project with its own libraries.'))] },
  { learn: [L(B('الأسرار في .env وGit', 'Secrets in .env and Git'),
      B('المفاتيح في ملف `.env` (`API_KEY=...`) وبتتقرا بـ `os.environ` أو `python-dotenv`. والـ `.env` **لازم** في `.gitignore`. وحط `.env.example` فيه الأسماء من غير القيم عشان اللي ياخد المشروع يعرف محتاج إيه. ولو مفتاح اتعمله commit بالغلط: اعتبره اتسرّب وغيّره.',
        'Keys live in a `.env` file (`API_KEY=...`) and are read with `os.environ` or `python-dotenv`. `.env` **must** be in `.gitignore`. Add a `.env.example` with the names but no values so whoever gets the project knows what is needed. If a key was committed by mistake: treat it as leaked and replace it.'),
      '# .gitignore\n.env\n.venv/\n__pycache__/\n\n# .env.example\nAPI_KEY=\nTELEGRAM_CHAT_ID=')],
    code: [C(B('قراءة إعداد من البيئة بأمان', 'Reading a setting from the environment safely'),
      'import os\n\ndef setting(name, default=None, required=False):\n    value = os.environ.get(name, default)\n    if required and not value:\n        raise SystemExit(f"Missing setting {name}: add it to your .env file")\n    return value\n\nprint("timezone:", setting("APP_TZ", "Africa/Cairo"))\nkey = setting("DEMO_API_KEY", "")\nprint("API key set:", bool(key))  # never print the key itself')],
    practice: [B('اعمل `.env.example` و`.gitignore` لمشروعك واتأكد بـ `git status` إن .env مش ظاهر.', 'Create `.env.example` and `.gitignore` for your project and check with `git status` that .env is not listed.'),
      B('خلّي السكربت يقف برسالة واضحة لو مفتاح ناقص.', 'Make the script stop with a clear message if a key is missing.')],
    words: [W('dotenv', 'ملف .env والمكتبة اللي بتقراه', 'the .env file and the library that reads it', 'Load the keys with dotenv.'),
      W('gitignore', 'ملف بيقول لـ Git يتجاهل ملفات معيّنة', 'a file telling Git to ignore certain files', 'Add .env to the gitignore.')],
    quiz: [Q(B('مفتاح اتعمله commit بالغلط:', 'A key was committed by mistake:'), ['replace the key', 'delete the commit and keep the key', 'make the repo private only'], 0, B('اعتبره اتسرّب.', 'Treat it as leaked.'))] },
  { review: [B('⚡ __main__ ونقطة البداية، وdatetime وbase64 وhashlib.', '⚡ __main__ and the entry point, datetime, base64 and hashlib.'),
      B('⚡ requirements والتثبيت الدقيق، والبيئة المعزولة، و.env و.gitignore: جهّز مشروعك عشان يشتغل على جهاز عميل.', '⚡ Requirements and pinning, isolated environments, .env and .gitignore: prepare your project to run on a client’s machine.')] }
] };
