// Python week 8 — the intensive hour (weeks 1–12 are 3 hours a day). Merged into the week by tools/build_weeks.js.
// Every code sample has run: 1, so tools/test_python_examples.js runs it.
const B = (ar, en) => ({ ar, en });
const L = (h, p, ex) => ({ h, p, ex });
const C = (u, p) => ({ u, p, run: 1 });
const W = (t, ar, en, ex) => ({ t, m: B(ar, en), ex });
const Q = (q, o, a, why) => ({ q, o, a, why });
module.exports = { days: [
  { learn: [L(B('raise from: احتفظ بالسبب الأصلي', 'raise from: keep the original cause'),
      B('لما تمسك خطأ تقني وترمي خطأ أوضح، اكتب `raise OrderError("…") from e`. كده الـ traceback بيعرض الاتنين: الخطأ بتاعك والسبب الأصلي (`__cause__`). من غير `from`، اللي بيصلّح هيضيع وقت يدوّر على السبب.',
        'When you catch a technical error and raise a clearer one, write `raise OrderError("…") from e`. The traceback then shows both: your error and the original cause (`__cause__`). Without `from`, whoever fixes it wastes time looking for the cause.'),
      'try:\n    total = float(row["total"])\nexcept (KeyError, ValueError) as e:\n    raise OrderError(f"bad total in row {n}") from e')],
    code: [C(B('خطأ أوضح مع السبب', 'A clearer error with its cause'),
      'class OrderError(Exception):\n    pass\n\ndef read_total(row, n):\n    try:\n        return float(row["total"])\n    except (KeyError, ValueError) as e:\n        raise OrderError(f"row {n}: bad total") from e\n\nfor n, row in enumerate([{"total": "300"}, {"total": "abc"}, {}], start=1):\n    try:\n        print(n, read_total(row, n))\n    except OrderError as err:\n        print(n, "->", err, "| cause:", type(err.__cause__).__name__, err.__cause__)')],
    practice: [B('لف دالة قراءة ملف بـ try وارمي خطأ خاص بيك `from` الخطأ الأصلي.', 'Wrap a file-reading function in try and raise your own error `from` the original.'),
      B('شغّل من غير `from` وقارن شكل الـ traceback.', 'Run it without `from` and compare the traceback.')],
    words: [W('raise from', 'ترمي خطأ جديد وتربطه بالسبب الأصلي', 'to raise a new error linked to its original cause', 'Use raise from to keep the cause.'),
      W('error context', 'المعلومات اللي حوالين الخطأ (الصف، الملف)', 'the information around an error (the row, the file)', 'Add error context like the row number.')],
    quiz: [Q(B('`err.__cause__` بيرجّع:', '`err.__cause__` returns:'), ['the original exception', 'the line number', 'None always'], 0, B('اللي بعد from.', 'Whatever followed from.'))] },
  { learn: [L(B('افشل بدري: تحقق من المدخلات', 'Fail fast: check inputs early'),
      B('تحقق من الشروط في **أول** الدالة (preconditions) وارمي `ValueError` برسالة واضحة، بدل ما الغلط يمشي لحد ما يكسر حاجة بعيدة ومش مفهومة. «Fail fast»: الخطأ يطلع قريب من سببه.',
        'Check conditions at the **start** of a function (preconditions) and raise a `ValueError` with a clear message, instead of letting a mistake travel until it breaks something far away and confusing. «Fail fast»: the error appears close to its cause.'),
      'def refund(amount, order_total):\n    if amount <= 0:\n        raise ValueError("amount must be positive")\n    if amount > order_total:\n        raise ValueError("refund is larger than the order")')],
    code: [C(B('preconditions لعملية استرجاع', 'Preconditions for a refund'),
      'def refund(amount, order_total):\n    if not isinstance(amount, (int, float)):\n        raise TypeError("amount must be a number")\n    if amount <= 0:\n        raise ValueError("amount must be positive")\n    if amount > order_total:\n        raise ValueError(f"refund {amount} is larger than the order {order_total}")\n    return order_total - amount\n\nfor amount in [50, -5, 900, "10"]:\n    try:\n        print(amount, "-> left:", refund(amount, 300))\n    except (TypeError, ValueError) as e:\n        print(amount, "->", type(e).__name__, e)')],
    practice: [B('ضيف preconditions لـ 3 دوال عندك.', 'Add preconditions to 3 of your functions.'),
      B('اكتب رسالة خطأ لكل شرط تقول المشكلة والقيمة اللي وصلت.', 'Write an error message for each check saying the problem and the value received.')],
    words: [W('fail fast', 'تطلّع الخطأ أول ما تكتشفه', 'to raise an error as soon as you detect it', 'Fail fast on a negative amount.'),
      W('precondition', 'شرط لازم يكون صح قبل ما الدالة تشتغل', 'a condition that must be true before a function runs', 'The precondition checks the amount.')],
    quiz: [Q(B('ليه تتحقق في أول الدالة؟', 'Why check at the start of the function?'), ['the error appears near its cause', 'it is faster to type', 'Python requires it'], 0, B('Fail fast.', 'Fail fast.'))] },
  { learn: [L(B('أصغر مثال بيعيد المشكلة', 'The smallest example that shows the bug'),
      B('قبل ما تسأل أو تصلّح: قلّل الكود والبيانات لحد **أصغر مثال** لسه بيعمل نفس الغلط. شيل نص الكود — لسه الغلط موجود؟ كمّل. غالبًا هتلاقي السبب في الطريق. ولما تطبع للتشخيص استخدم `print(f"{x=}")` (بيطبع الاسم والقيمة).',
        'Before asking or fixing: shrink the code and data to the **smallest example** that still shows the same bug. Remove half the code — still broken? Keep going. You will often find the cause on the way. When printing to diagnose, use `print(f"{x=}")` (it prints the name and value).'),
      'total = 0\nfor price in ["10", "20"]:\n    total += int(price)\n    print(f"{price=} {total=}")')],
    code: [C(B('طباعة تشخيصية بـ =', 'Diagnostic printing with ='),
      'def average(nums):\n    total = sum(nums)\n    count = len(nums)\n    print(f"{total=} {count=}")\n    return total / count if count else 0\n\nprint(average([10, 20, 30]))\nprint(average([]))')],
    practice: [B('خُد bug قديم عندك وقلّله لأصغر مثال (أقل من 10 سطور).', 'Take an old bug of yours and shrink it to the smallest example (under 10 lines).'),
      B('استبدل كل print تشخيصي عندك بصيغة `f"{x=}"`.', 'Replace your diagnostic prints with the `f"{x=}"` form.')],
    words: [W('minimal example', 'أصغر كود بيعيد المشكلة', 'the smallest code that shows the problem', 'Post a minimal example when you ask for help.'),
      W('print debugging', 'تطبع قيم عشان تفهم اللي بيحصل', 'printing values to see what happens', 'Print debugging with f"{x=}" is quick.')],
    quiz: [Q(B('`x = 5; print(f"{x=}")` بيطبع:', '`x = 5; print(f"{x=}")` prints:'), ['x=5', '5', '{x=}'], 0, B('الاسم والقيمة.', 'The name and the value.'))] },
  { learn: [L(B('شكل السجل وملف دوّار', 'Log format and a rotating file'),
      B('`logging.basicConfig(format="%(asctime)s %(levelname)s %(name)s: %(message)s")` بيخلّي كل سطر فيه الوقت والمستوى. ولملف سجل ميكبرش للأبد: `RotatingFileHandler(maxBytes=1_000_000, backupCount=3)` بيعمل ملف جديد لما يتملي ويحتفظ بآخر 3.',
        '`logging.basicConfig(format="%(asctime)s %(levelname)s %(name)s: %(message)s")` puts the time and level on every line. For a log file that does not grow forever: `RotatingFileHandler(maxBytes=1_000_000, backupCount=3)` starts a new file when full and keeps the last 3.'),
      'from logging.handlers import RotatingFileHandler\nhandler = RotatingFileHandler("bot.log", maxBytes=1_000_000, backupCount=3)')],
    code: [C(B('سجل منسّق وملف دوّار', 'A formatted log and a rotating file'),
      'import logging, os\nfrom logging.handlers import RotatingFileHandler\nlog = logging.getLogger("sync")\nlog.setLevel(logging.INFO)\nfmt = logging.Formatter("%(levelname)-7s %(name)s: %(message)s")\nfile_handler = RotatingFileHandler("sync.log", maxBytes=200, backupCount=2)\nfile_handler.setFormatter(fmt)\nlog.addHandler(file_handler)\nfor i in range(12):\n    log.info("copied order %d", 1000 + i)\nlog.warning("3 orders had no phone")\nfor name in sorted(f for f in os.listdir(".") if f.startswith("sync.log")):\n    with open(name) as fh:\n        lines = fh.read().splitlines()\n    print(f"{name:<11} {len(lines)} lines, last: {lines[-1]}")')],
    practice: [B('ضيف logging بملف دوّار لسكربت عندك بيشتغل كل يوم.', 'Add logging with a rotating file to a script of yours that runs daily.'),
      B('خلّي المستوى INFO للملف وWARNING للشاشة.', 'Use INFO for the file and WARNING for the screen.')],
    words: [W('rotating log', 'ملف سجل بيتقسم لما يكبر', 'a log file that is split when it gets big', 'A rotating log keeps the disk from filling up.'),
      W('log format', 'شكل كل سطر في السجل', 'the layout of each log line', 'Add the time to the log format.')],
    quiz: [Q(B('`backupCount=3` معناها:', '`backupCount=3` means:'), ['keep the last 3 old files', 'log 3 lines', 'retry 3 times'], 0, B('الأقدم بيتمسح.', 'The oldest is deleted.'))] },
  { learn: [L(B('سكربت متين: حالة الخروج وإعادة المحاولة', 'A robust script: exit status and retries'),
      B('السكربت اللي بيشتغل من n8n أو cron لازم يرجّع **exit status**: `0` نجح، أي رقم تاني فشل — `sys.exit(1)`. كده اللي شغّله يعرف. وللعمليات اللي ممكن تفشل مؤقتًا: retry loop بعدد محاولات وانتظار بيزيد.',
        'A script run from n8n or cron must return an **exit status**: `0` success, any other number failure — `sys.exit(1)`. That way whatever ran it knows. For operations that can fail temporarily: a retry loop with a number of tries and a growing wait.'),
      'for attempt in range(1, 4):\n    try:\n        send(); break\n    except ConnectionError:\n        time.sleep(2 ** attempt)\nelse:\n    sys.exit(1)')],
    code: [C(B('إعادة محاولة وحالة خروج', 'Retry and exit status'),
      'import random, sys, time\nrandom.seed(7)\n\ndef flaky_send():\n    if random.random() < 0.6:\n        raise ConnectionError("network hiccup")\n    return "sent"\n\nfor attempt in range(1, 5):\n    try:\n        print("attempt", attempt, "->", flaky_send())\n        break\n    except ConnectionError as e:\n        wait = 0.01 * 2 ** attempt\n        print("attempt", attempt, "failed:", e, f"(waiting {wait:.2f}s)")\n        time.sleep(wait)\nelse:\n    print("giving up")\n    sys.exit(1)\nprint("exit status 0")')],
    practice: [B('خلّي سكربت عندك يرجّع 1 لو فيه أي خطأ، وجرّبه من n8n (Execute Command).', 'Make a script of yours return 1 on any error, and test it from n8n (Execute Command).'),
      B('اعمل retry loop بـ 3 محاولات وانتظار 1 ثم 2 ثم 4 ثواني.', 'Build a retry loop with 3 tries and waits of 1, 2 and 4 seconds.')],
    words: [W('exit status', 'رقم السكربت بيرجّعه (0 = نجح)', 'the number a script returns (0 = success)', 'n8n reads the exit status.'),
      W('retry loop', 'loop بتعيد العملية لما تفشل', 'a loop that repeats an operation when it fails', 'Use a retry loop for network calls.')],
    quiz: [Q(B('السكربت فشل. المفروض يرجّع:', 'The script failed. It should return:'), ['a non-zero exit status', '0', 'nothing'], 0, B('0 = نجاح بس.', '0 means success only.'))] },
  { review: [B('⚡ raise from، وfail fast والـ preconditions، وأصغر مثال وf"{x=}".', '⚡ raise from, fail fast and preconditions, the minimal example and f"{x=}".'),
      B('⚡ سجل منسّق ودوّار، وحالة الخروج وإعادة المحاولة: خلّي سكربت الأسبوع جاهز للتشغيل الآلي.', '⚡ Formatted rotating logs, exit status and retries: make the week’s script ready for automatic runs.')] }
] };
