// Python week 9 — the intensive hour (weeks 1–12 are 3 hours a day). Merged into the week by tools/build_weeks.js.
// Every code sample has run: 1, so tools/test_python_examples.js runs it.
const B = (ar, en) => ({ ar, en });
const L = (h, p, ex) => ({ h, p, ex });
const C = (u, p) => ({ u, p, run: 1 });
const W = (t, ar, en, ex) => ({ t, m: B(ar, en), ex });
const Q = (q, o, a, why) => ({ q, o, a, why });
module.exports = { days: [
  { learn: [L(B('الكتابة الآمنة (atomic write)', 'Safe writing (atomic write)'),
      B('لو السكربت وقف وهو بيكتب ملف مهم، الملف ممكن يبقى نصه مكتوب ونصه ضايع. الحل: اكتب في **ملف مؤقت** جنبه، وبعدين `os.replace(tmp, path)` — دي عملية واحدة: يا الملف القديم كامل يا الجديد كامل.',
        'If a script stops while writing an important file, the file can end up half written. The fix: write to a **temporary file** next to it, then `os.replace(tmp, path)` — one operation: either the old file stays complete or the new one is complete.'),
      'tmp = path.with_suffix(".tmp")\ntmp.write_text(data, encoding="utf-8")\nos.replace(tmp, path)   # all or nothing')],
    code: [C(B('حفظ JSON بأمان', 'Saving JSON safely'),
      'import json, os\nfrom pathlib import Path\n\ndef save_json_atomic(path, data):\n    path = Path(path)\n    tmp = path.with_suffix(path.suffix + ".tmp")\n    tmp.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")\n    os.replace(tmp, path)\n\nsave_json_atomic("state.json", {"last_id": 1042, "ok": True})\nsave_json_atomic("state.json", {"last_id": 1043, "ok": True})\nprint(Path("state.json").read_text(encoding="utf-8"))\nprint("temp left behind:", Path("state.json.tmp").exists())')],
    practice: [B('استخدم الكتابة الآمنة في سكربت بيحفظ آخر ID اتعالج.', 'Use safe writing in a script that saves the last processed ID.'),
      B('اقرا عن `tempfile.NamedTemporaryFile` واكتب سطرين عن إمتى تستخدمه.', 'Read about `tempfile.NamedTemporaryFile` and write two lines on when to use it.')],
    words: [W('atomic write', 'كتابة يا تكمل كلها يا متحصلش خالص', 'a write that either completes fully or not at all', 'Use an atomic write for the state file.'),
      W('temp file', 'ملف مؤقت بيتمسح بعد الاستخدام', 'a temporary file deleted after use', 'Write to a temp file first.')],
    quiz: [Q(B('`os.replace(tmp, path)` ميزته:', 'The benefit of `os.replace(tmp, path)`:'), ['the file is never half written', 'it compresses the file', 'it makes a backup'], 0, B('عملية واحدة.', 'One step.'))] },
  { learn: [L(B('glob وrglob ودمج المسارات', 'glob, rglob and joining paths'),
      B('`Path("in").glob("*.csv")` الملفات في الفولدر ده بس، و`rglob("*.csv")` في كل الفولدرات اللي جواه. ودمج المسارات بـ `/`: `Path("data") / "2026" / "orders.csv"` — بيشتغل على ويندوز ولينكس من غير ما تفكّر في `\\` أو `/`.',
        '`Path("in").glob("*.csv")` finds files in that folder only, and `rglob("*.csv")` in every folder inside it. Join paths with `/`: `Path("data") / "2026" / "orders.csv"` — works on Windows and Linux without thinking about `\\` or `/`.'),
      'for f in Path("reports").rglob("*.xlsx"):\n    print(f.relative_to("reports"))\nout = Path("out") / f"{day}.csv"')],
    code: [C(B('دوّر على ملفات في فولدرات', 'Finding files in folders'),
      'from pathlib import Path\nfor p in ["data/top.csv", "data/2026/09/a.csv", "data/2026/10/b.csv", "data/notes.txt", "data/2026/c.csv"]:\n    Path(p).parent.mkdir(parents=True, exist_ok=True)\n    Path(p).write_text("x")\nroot = Path("data")\nprint("glob:", sorted(f.name for f in root.glob("*.csv")))\nprint("rglob:", sorted(str(f.relative_to(root)).replace("\\\\", "/") for f in root.rglob("*.csv")))\nprint((Path("out") / "2026" / "report.csv").as_posix())')],
    practice: [B('اطبع كل ملفات PDF في فولدر التنزيلات وفولدراته بحجم كل واحد.', 'Print every PDF in your downloads folder and its subfolders with each size.'),
      B('ابني مسارات إخراج بـ `/` بدل جمع النصوص.', 'Build output paths with `/` instead of joining strings.')],
    words: [W('glob', 'نمط بأسماء الملفات زي *.csv', 'a file name pattern like *.csv', 'glob("*.csv") finds the CSV files.'),
      W('path join', 'ربط أجزاء مسار مع بعض', 'joining the parts of a path', 'Use / for a path join with pathlib.')],
    quiz: [Q(B('عشان تلاقي ملفات في الفولدرات الفرعية كمان:', 'To find files in subfolders too:'), ['rglob', 'glob', 'listdir'], 0, B('r = recursive.', 'r = recursive.'))] },
  { learn: [L(B('نسخة احتياطية قبل أي تعديل', 'A backup before any change'),
      B('قبل ما سكربت ينقل أو يعدّل ملفات: انسخها لفولدر `backup/<التاريخ>` بـ `shutil.copy2` (بيحافظ على التاريخ). واعمل **checksum** للنسخة والأصل عشان تتأكد إنهم زي بعض. لو حاجة باظت، ترجّع منها.',
        'Before a script moves or edits files: copy them to a `backup/<date>` folder with `shutil.copy2` (it keeps the dates). Compute a **checksum** of the copy and the original to be sure they match. If something breaks, restore from it.'),
      'backup = Path("backup") / date.today().isoformat()\nbackup.mkdir(parents=True, exist_ok=True)\nshutil.copy2(src, backup / src.name)')],
    code: [C(B('نسخة احتياطية مع checksum', 'A backup with a checksum'),
      'import hashlib, shutil\nfrom pathlib import Path\n\ndef checksum(path):\n    return hashlib.sha256(Path(path).read_bytes()).hexdigest()[:16]\n\nsrc = Path("prices.csv")\nsrc.write_text("tea,15\\ncoffee,25\\n")\nbackup_dir = Path("backup") / "2026-10-03"\nbackup_dir.mkdir(parents=True, exist_ok=True)\ncopy = Path(shutil.copy2(src, backup_dir / src.name))\nprint(copy.as_posix())\nprint("same content:", checksum(src) == checksum(copy))')],
    practice: [B('ضيف نسخة احتياطية قبل سكربت تنظيم الفولدر بتاعك.', 'Add a backup step before your folder-organising script.'),
      B('اكتب دالة `restore(day)` بترجّع الملفات من نسخة يوم معيّن.', 'Write a `restore(day)` function that brings files back from a given day’s backup.')],
    words: [W('checksum', 'رقم بيتحسب من محتوى الملف عشان تتأكد إنه متغيّرش', 'a value computed from a file’s content to check it did not change', 'Compare the checksum after copying.'),
      W('backup copy', 'نسخة احتياطية من ملف', 'a spare copy of a file', 'Make a backup copy before renaming.')],
    quiz: [Q(B('`shutil.copy2` بيختلف عن `copy` في:', '`shutil.copy2` differs from `copy` by:'), ['keeping file dates', 'being faster', 'compressing'], 0, B('بيحافظ على الـ metadata.', 'It keeps the metadata.'))] },
  { learn: [L(B('اكتشاف الملفات المكررة بذكاء', 'Finding duplicate files smartly'),
      B('مقارنة كل ملف بكل ملف بطيئة. الأسرع: جمّع الملفات حسب **الحجم** الأول (ملفين بحجم مختلف مستحيل يكونوا زي بعض)، وبعدين احسب **sha256** للمجموعات اللي فيها أكتر من ملف بس.',
        'Comparing every file with every other is slow. Faster: group files by **size** first (two files of different sizes cannot be the same), then compute **sha256** only for groups with more than one file.'),
      'by_size = defaultdict(list)\nfor f in files: by_size[f.stat().st_size].append(f)\ncandidates = [g for g in by_size.values() if len(g) > 1]')],
    code: [C(B('مكتشف ملفات مكررة', 'A duplicate finder'),
      'import hashlib\nfrom collections import defaultdict\nfrom pathlib import Path\nfiles = {"a.txt": "hello", "b.txt": "hello", "c.txt": "world", "d.txt": "hellp"}\nfor name, text in files.items():\n    Path(name).write_text(text)\nby_size = defaultdict(list)\nfor f in map(Path, files):\n    by_size[f.stat().st_size].append(f)\nby_hash = defaultdict(list)\nfor group in by_size.values():\n    if len(group) > 1:\n        for f in group:\n            by_hash[hashlib.sha256(f.read_bytes()).hexdigest()].append(f.name)\nprint([names for names in by_hash.values() if len(names) > 1])')],
    practice: [B('شغّله على فولدر صور عندك (من غير مسح!) واطبع المكرر.', 'Run it on one of your photo folders (without deleting!) and print the duplicates.'),
      B('ضيف حساب المساحة اللي ممكن توفّرها.', 'Add the space you could save.')],
    words: [W('sha256', 'خوارزمية بصمة 256 بت', 'a 256-bit fingerprint algorithm', 'Equal sha256 means equal content.'),
      W('duplicate finder', 'برنامج بيلاقي الملفات المكررة', 'a program that finds repeated files', 'The duplicate finder groups by size first.')],
    quiz: [Q(B('ليه نجمّع بالحجم الأول؟', 'Why group by size first?'), ['different sizes cannot be duplicates', 'size is more accurate', 'hashes are wrong'], 0, B('بيوفّر حساب البصمات.', 'It saves computing hashes.'))] },
  { learn: [L(B('الترميز والـ BOM وملفات zip', 'Encodings, the BOM and zip files'),
      B('ملفات من Excel أحيانًا بتبدأ بـ **BOM** (حروف خفية) فأول عمود اسمه `\\ufeffname`. افتحها بـ `encoding="utf-8-sig"` عشان يتشال. ولو الملف عربي قديم ومش UTF-8 جرّب `cp1256`. ولضغط تقرير: `zipfile.ZipFile("out.zip", "w", zipfile.ZIP_DEFLATED)`.',
        'Files from Excel sometimes start with a **BOM** (hidden characters), so the first column is named `\\ufeffname`. Open them with `encoding="utf-8-sig"` to remove it. For old Arabic files that are not UTF-8, try `cp1256`. To compress a report: `zipfile.ZipFile("out.zip", "w", zipfile.ZIP_DEFLATED)`.'),
      'text = path.read_text(encoding="utf-8-sig")\nwith zipfile.ZipFile("reports.zip", "w", zipfile.ZIP_DEFLATED) as z:\n    z.write("report.csv")')],
    code: [C(B('ملف بـ BOM وأرشيف zip', 'A file with a BOM and a zip archive'),
      'import zipfile\nfrom pathlib import Path\nPath("names.csv").write_text("name,city\\nسارة,Giza\\n", encoding="utf-8-sig")\nprint(repr(Path("names.csv").read_text(encoding="utf-8").splitlines()[0]))\nprint(repr(Path("names.csv").read_text(encoding="utf-8-sig").splitlines()[0]))\nwith zipfile.ZipFile("archive.zip", "w", zipfile.ZIP_DEFLATED) as z:\n    z.write("names.csv")\nwith zipfile.ZipFile("archive.zip") as z:\n    print(z.namelist(), z.read("names.csv").decode("utf-8-sig").splitlines()[1])')],
    practice: [B('صدّر شيت من Excel كـ CSV UTF-8 واقراه بالطريقتين وشوف الفرق.', 'Export a sheet from Excel as CSV UTF-8 and read it both ways to see the difference.'),
      B('اضغط كل تقارير الشهر في zip واحد باسم الشهر.', 'Zip all of the month’s reports into one archive named after the month.')],
    words: [W('utf-8 bom', 'حروف خفية في أول ملف بتقول إنه UTF-8', 'hidden characters at the start of a file marking it as UTF-8', 'Use utf-8-sig to drop the UTF-8 BOM.'),
      W('archive', 'ملف واحد فيه ملفات كتير مضغوطة', 'one file holding many compressed files', 'Send the reports as one archive.')],
    quiz: [Q(B('أول عمود اسمه `\\ufeffname`. الحل:', 'The first column is `\\ufeffname`. Fix:'), ['open with utf-8-sig', 'rename the column by hand', 'use cp1256'], 0, B('ده BOM.', 'That is a BOM.'))] },
  { review: [B('⚡ الكتابة الآمنة، وglob/rglob و/، والنسخ الاحتياطي بـ checksum.', '⚡ Safe writing, glob/rglob and /, and backups with checksums.'),
      B('⚡ اكتشاف المكرر بالحجم ثم البصمة، والـ BOM وzip: ابني أداة تنظيم فولدرات آمنة.', '⚡ Finding duplicates by size then hash, the BOM and zip: build a safe folder-organising tool.')] }
] };
