// Python week 10 — the intensive hour (weeks 1–12 are 3 hours a day). Merged into the week by tools/build_weeks.js.
// Every code sample has run: 1, so tools/test_python_examples.js runs it.
const B = (ar, en) => ({ ar, en });
const L = (h, p, ex) => ({ h, p, ex });
const C = (u, p) => ({ u, p, run: 1 });
const W = (t, ar, en, ex) => ({ t, m: B(ar, en), ex });
const Q = (q, o, a, why) => ({ q, o, a, why });
module.exports = { days: [
  { learn: [L(B('regex مقروء: re.VERBOSE وcompile', 'Readable regex: re.VERBOSE and compile'),
      B('الـ regex الطويل بيبقى لغز. `re.VERBOSE` بيسمحلك تكتبه على كذا سطر بمسافات وتعليقات `#`. و`re.compile(pattern)` بيجهّزه مرة واحدة وتستخدمه كتير (أسرع وأوضح في الكود). حط الأنماط المهمة كثوابت فوق الملف.',
        'A long regex becomes a puzzle. `re.VERBOSE` lets you write it over several lines with spaces and `#` comments. `re.compile(pattern)` prepares it once to use many times (faster and clearer in code). Keep important patterns as constants at the top of the file.'),
      'PHONE = re.compile(r"""\n    (?:\\+?20|0)?   # country code or leading 0\n    (1[0125])       # operator\n    (\\d{8})         # number\n""", re.VERBOSE)')],
    code: [C(B('نمط موبايل مقروء', 'A readable mobile pattern'),
      'import re\nPHONE = re.compile(r"""\n    ^(?:\\+?20|0)?   # optional country code or leading zero\n    (1[0125])        # operator prefix\n    (\\d{8})$        # the remaining eight digits\n""", re.VERBOSE)\nfor raw in ["01012345678", "+201512345678", "0123", "01312345678"]:\n    m = PHONE.match(raw)\n    print(f"{raw:<15}", "+20" + m.group(1) + m.group(2) if m else "invalid")')],
    practice: [B('حوّل regex طويل عندك لـ VERBOSE بتعليق لكل جزء.', 'Rewrite one of your long regexes with VERBOSE and a comment per part.'),
      B('اعمل compile لـ 3 أنماط تستخدمها كتير وحطهم كثوابت.', 'Compile 3 patterns you use often and keep them as constants.')],
    words: [W('verbose regex', 'regex مكتوب على سطور بتعليقات', 'a regex written over lines with comments', 'A verbose regex is easier to review.'),
      W('compile', 'تجهّز نمط مرة عشان تستخدمه كتير', 'to prepare a pattern once to reuse it', 'Compile the pattern at the top of the file.')],
    quiz: [Q(B('في re.VERBOSE المسافات العادية:', 'In re.VERBOSE, normal spaces:'), ['are ignored', 'must match', 'cause an error'], 0, B('استخدم \\s أو [ ] للمسافة الحقيقية.', 'Use \\s or [ ] for a real space.'))] },
  { learn: [L(B('مجموعات بأسماء وfindall', 'Named groups and findall'),
      B('`(?P<amount>\\d+)` مجموعة باسم: `m["amount"]` أو `m.groupdict()` بدل أرقام المجموعات اللي بتتلخبط. و`re.findall` بيرجّع كل النتايج: لو فيه مجموعة واحدة بيرجّع قايمة نصوص، ولو أكتر من واحدة بيرجّع قايمة tuples. ولو عايز التفاصيل، `re.finditer`.',
        '`(?P<amount>\\d+)` is a named group: `m["amount"]` or `m.groupdict()` instead of group numbers that get mixed up. `re.findall` returns every result: with one group, a list of strings; with several, a list of tuples. For details, use `re.finditer`.'),
      're.findall(r"(\\d+) EGP", text)            # ["120", "45"]\nfor m in re.finditer(r"(?P<qty>\\d+)x (?P<item>\\w+)", text):\n    print(m.groupdict())')],
    code: [C(B('استخراج سطور طلب', 'Extracting order lines'),
      'import re\ntext = "2x tea 30 EGP, 1x cake 45 EGP, 3x juice 90 EGP"\nprint(re.findall(r"(\\d+) EGP", text))\nLINE = re.compile(r"(?P<qty>\\d+)x (?P<item>\\w+) (?P<price>\\d+) EGP")\nrows = [m.groupdict() for m in LINE.finditer(text)]\nfor r in rows:\n    print(r)\nprint("total:", sum(int(r["price"]) for r in rows))')],
    practice: [B('من رسالة واتساب فيها طلب، طلّع الكمية والصنف بمجموعات بأسماء.', 'From a WhatsApp order message, extract quantity and item with named groups.'),
      B('قارن findall بمجموعة واحدة ومجموعتين على نفس النص.', 'Compare findall with one group and with two groups on the same text.')],
    words: [W('capture group', 'جزء بين أقواس في الـ regex بيتحفظ', 'a bracketed part of a regex that is saved', 'The capture group holds the price.'),
      W('findall', 'بترجّع كل المطابقات في النص', 'returns every match in a text', 'findall gives all the prices at once.')],
    quiz: [Q(B('`re.findall(r"(a)(b)", "abab")` =', '`re.findall(r"(a)(b)", "abab")` ='), ['[("a", "b"), ("a", "b")]', '["ab", "ab"]', '["a", "b"]'], 0, B('أكتر من مجموعة → tuples.', 'Several groups → tuples.'))] },
  { learn: [L(B('re.sub بدالة ومجموعات مش محفوظة', 're.sub with a function, and non-capturing groups'),
      B('`re.sub` ممكن ياخد **دالة** بدل نص: بتستقبل الـ match وترجّع البديل — مثلًا تخفي كل رقم موبايل أو تحوّل كل سعر. و`(?:...)` مجموعة **مش بتتحفظ**: للتجميع بس (زي `(?:EGP|LE)`) من غير ما تلخبط أرقام المجموعات.',
        '`re.sub` can take a **function** instead of text: it receives the match and returns the replacement — for example to mask every mobile number or convert every price. `(?:...)` is a **non-capturing** group: for grouping only (like `(?:EGP|LE)`) without disturbing the group numbers.'),
      're.sub(r"\\d{11}", lambda m: m[0][:3] + "*****" + m[0][-3:], text)\nre.findall(r"(\\d+) (?:EGP|LE)", text)')],
    code: [C(B('إخفاء الأرقام وتوحيد العملة', 'Masking numbers and unifying the currency'),
      'import re\ntext = "Call 01012345678 or 01198765432. Price 120 LE, delivery 30 EGP."\nmasked = re.sub(r"\\b01\\d{9}\\b", lambda m: m[0][:3] + "*****" + m[0][-3:], text)\nprint(masked)\nprices = re.findall(r"(\\d+) (?:EGP|LE)\\b", text)\nprint(prices)\nprint(re.sub(r"(\\d+) (?:EGP|LE)\\b", lambda m: f"{int(m[1]):,} EGP", text))')],
    practice: [B('اخفي كل الإيميلات في نص بدالة (`s***@domain.com`).', 'Mask every email in a text with a function (`s***@domain.com`).'),
      B('حوّل كل تواريخ `dd/mm/yyyy` لـ `yyyy-mm-dd` بـ re.sub.', 'Turn every `dd/mm/yyyy` date into `yyyy-mm-dd` with re.sub.')],
    words: [W('re.sub', 'استبدال كل المطابقات في نص', 'replacing every match in a text', 're.sub can call a function per match.'),
      W('non-capturing group', 'مجموعة (?:...) للتجميع بس من غير حفظ', 'a (?:...) group for grouping only, not saving', 'Use a non-capturing group for the currency.')],
    quiz: [Q(B('`(?:EGP|LE)` بتعمل إيه؟', 'What does `(?:EGP|LE)` do?'), ['groups without saving', 'saves the currency', 'matches a question mark'], 0, B('تجميع بس.', 'Grouping only.'))] },
  { learn: [L(B('unicodedata وتطبيع النص', 'unicodedata and normalising text'),
      B('نفس الحرف ممكن يتكتب بأكتر من شكل في Unicode (`é` حرف واحد أو e + علامة). `unicodedata.normalize("NFKC", s)` بيوحّد الأشكال — وبيحوّل كمان حروف «عرض كامل» زي `１２３` لـ `123`. و`unicodedata.category(ch)` بيقولك نوع الحرف (`Mn` = علامة تشكيل) فتشيل التشكيل من أي لغة.',
        'The same character can be written in more than one way in Unicode (`é` as one character or e + a mark). `unicodedata.normalize("NFKC", s)` unifies the forms — it also turns «full-width» characters like `１２３` into `123`. And `unicodedata.category(ch)` tells you the kind of character (`Mn` = a combining mark), so you can remove diacritics in any language.'),
      'unicodedata.normalize("NFKC", "１２３")   # "123"\n"".join(c for c in s if unicodedata.category(c) != "Mn")')],
    code: [C(B('تطبيع أسماء ومقارنتها', 'Normalising and comparing names'),
      'import unicodedata\n\ndef normal(s):\n    s = unicodedata.normalize("NFKC", s)\n    s = "".join(c for c in unicodedata.normalize("NFD", s) if unicodedata.category(c) != "Mn")\n    return s.casefold().strip()\n\nnames = ["Café", "CAFE\\u0301", "café ", "مُحَمَّد", "محمد", "１２３"]\nfor n in names:\n    print(repr(n), "->", repr(normal(n)))\nprint(normal(names[0]) == normal(names[1]))')],
    practice: [B('استخدم الدالة دي قبل البحث في قايمة منتجات عربي وإنجليزي.', 'Use this function before searching a list of Arabic and English products.'),
      B('اطبع الـ category لكل حرف في كلمة مشكّلة.', 'Print the category of each character in a word with diacritics.')],
    words: [W('unicodedata', 'مكتبة معلومات حروف Unicode', 'the module with Unicode character information', 'unicodedata finds combining marks.'),
      W('normalisation', 'توحيد أشكال الحروف المختلفة', 'unifying different forms of characters', 'Apply normalisation before comparing text.')],
    quiz: [Q(B('`unicodedata.normalize("NFKC", "１")` =', '`unicodedata.normalize("NFKC", "１")` ='), ['"1"', '"１"', '1'], 0, B('الشكل العريض بيتوحّد.', 'The full-width form is unified.'))] },
  { learn: [L(B('تحليل نص لقطع (tokenize)', 'Tokenising text'),
      B('لنص شبه منظّم (أوامر، معادلات، سطور log) أحسن من regex واحد عملاق: قسّمه لـ **tokens** بـ regex بمجموعات بأسماء لكل نوع، وامشي عليها. وlookbehind `(?<=…)` بيشترط حاجة قبل المطابقة من غير ما ياخدها.',
        'For semi-structured text (commands, formulas, log lines), better than one giant regex: split it into **tokens** with a regex of named groups per kind, then walk through them. A lookbehind `(?<=…)` requires something before the match without including it.'),
      'TOKEN = re.compile(r"(?P<num>\\d+)|(?P<word>[a-z]+)|(?P<op>[+*-])|(?P<space>\\s+)")\nfor m in TOKEN.finditer("add 2 + 3"):\n    print(m.lastgroup, m[0])')],
    code: [C(B('tokenizer صغير', 'A small tokenizer'),
      'import re\nTOKEN = re.compile(r"(?P<NUM>\\d+(?:\\.\\d+)?)|(?P<WORD>[a-z_]+)|(?P<OP>[=+*/-])|(?P<SKIP>\\s+)|(?P<BAD>.)")\nline = "total = price * 1.14 + fee"\nfor m in TOKEN.finditer(line):\n    if m.lastgroup != "SKIP":\n        print(f"{m.lastgroup:<5} {m[0]}")\nprint(re.findall(r"(?<=#)\\w+", "tags: #sale #new #eid"))')],
    practice: [B('اعمل tokenizer لأوامر بوت (`/price tea 2`).', 'Write a tokenizer for bot commands (`/price tea 2`).'),
      B('طلّع كل اللي بعد `@` في نص بـ lookbehind.', 'Extract everything after `@` in a text with a lookbehind.')],
    words: [W('tokenize', 'تقسّم نص لقطع صغيرة ليها نوع', 'to split text into small typed pieces', 'Tokenize the command before checking it.'),
      W('lookbehind', 'شرط إن حاجة تيجي قبل المطابقة', 'a condition that something comes before the match', 'The lookbehind skips the # sign.')],
    quiz: [Q(B('`m.lastgroup` بيرجّع:', '`m.lastgroup` returns:'), ['the name of the group that matched', 'the last character', 'the group number'], 0, B('نوع الـ token.', 'The token type.'))] },
  { review: [B('⚡ re.VERBOSE وcompile، والمجموعات بأسماء وfindall/finditer.', '⚡ re.VERBOSE and compile, named groups and findall/finditer.'),
      B('⚡ re.sub بدالة و(?:)، وunicodedata والتطبيع، والـ tokenizer: نضّف ملف رسايل عملاء كامل.', '⚡ re.sub with a function and (?:), unicodedata and normalising, and tokenizers: clean a whole file of customer messages.')] }
] };
