// Python week 11 — the intensive hour (weeks 1–12 are 3 hours a day). Merged into the week by tools/build_weeks.js.
// Every code sample has run: 1 and uses only the standard library, so it also runs in the browser.
const B = (ar, en) => ({ ar, en });
const L = (h, p, ex) => ({ h, p, ex });
const C = (u, p) => ({ u, p, run: 1 });
const W = (t, ar, en, ex) => ({ t, m: B(ar, en), ex });
const Q = (q, o, a, why) => ({ q, o, a, why });
module.exports = { days: [
  { learn: [L(B('CSV بفاصلة منقوطة: Sniffer', 'CSV with semicolons: the Sniffer'),
      B('Excel في إعدادات عربي أو أوروبي بيحفظ CSV بـ `;` بدل `,`. `csv.Sniffer().sniff(sample)` بيخمّن الفاصل (الـ **dialect**) من أول كام سطر، و`has_header` بيخمّن فيه سطر عناوين ولا لأ. اقرا بعدها بـ `csv.DictReader(f, dialect=d)`.',
        'Excel with Arabic or European settings saves CSV with `;` instead of `,`. `csv.Sniffer().sniff(sample)` guesses the separator (the **dialect**) from the first lines, and `has_header` guesses whether there is a header row. Then read with `csv.DictReader(f, dialect=d)`.'),
      'sample = f.read(2048); f.seek(0)\ndialect = csv.Sniffer().sniff(sample, delimiters=",;\\t")\nrows = list(csv.DictReader(f, dialect=dialect))')],
    code: [C(B('اقرا CSV مهما كان الفاصل', 'Read a CSV whatever the separator'),
      'import csv, io\nfiles = {\n    "comma.csv": "name,city,total\\nSara,Giza,300\\nOmar,Cairo,150\\n",\n    "semicolon.csv": "name;city;total\\nMona;Alex;90\\nAli;Giza;400\\n",\n}\nfor name, text in files.items():\n    dialect = csv.Sniffer().sniff(text[:1024], delimiters=",;\\t")\n    rows = list(csv.DictReader(io.StringIO(text), dialect=dialect))\n    print(name, repr(dialect.delimiter), rows[0])')],
    practice: [B('صدّر شيت بإعدادات مختلفة واقراه بالـ Sniffer.', 'Export a sheet with different settings and read it with the Sniffer.'),
      B('اكتب CSV بـ `;` بـ `csv.writer(f, delimiter=";")`.', 'Write a CSV with `;` using `csv.writer(f, delimiter=";")`.')],
    words: [W('dialect', 'إعدادات شكل الـ CSV (الفاصل، التنصيص)', 'the CSV format settings (separator, quoting)', 'The sniffer detects the dialect.'),
      W('csv sniffer', 'أداة بتخمّن شكل ملف CSV', 'a tool that guesses a CSV file’s format', 'Use the csv sniffer for files from clients.')],
    quiz: [Q(B('CSV من Excel عربي فيه `;`. الأسهل:', 'A CSV from Arabic Excel uses `;`. Easiest:'), ['csv.Sniffer or delimiter=";"', 'replace every ; by hand', 'open it as JSON'], 0, B('حدّد الفاصل.', 'Set the separator.'))] },
  { learn: [L(B('حروف الأعمدة وأسماء الشيتات', 'Column letters and sheet names'),
      B('Excel بيسمّي الأعمدة A..Z ثم AA..AZ… لما تكتب معادلة أو تحدد عرض عمود في openpyxl محتاج تحوّل الرقم لحروف: `openpyxl.utils.get_column_letter(28)` = `AB`. والفكرة نفسها نظام عدّ بـ 26 حرف. وأسماء الشيتات: أقل من 31 حرف ومن غير `/ \\ ? * [ ] :`.',
        'Excel names columns A..Z, then AA..AZ… When you write a formula or set a column width in openpyxl you need to turn a number into letters: `openpyxl.utils.get_column_letter(28)` = `AB`. The idea is a base-26 counting system. Sheet names: under 31 characters and without `/ \\ ? * [ ] :`.'),
      'from openpyxl.utils import get_column_letter, column_index_from_string\nget_column_letter(28)            # "AB"\ncolumn_index_from_string("AB")   # 28')],
    code: [C(B('رقم ↔ حرف عمود (من غير مكتبات)', 'Number ↔ column letter (no libraries)'),
      'import re\n\ndef col_letter(n):\n    s = ""\n    while n:\n        n, r = divmod(n - 1, 26)\n        s = chr(65 + r) + s\n    return s\n\ndef col_number(s):\n    n = 0\n    for ch in s.upper():\n        n = n * 26 + ord(ch) - 64\n    return n\n\nfor n in [1, 26, 27, 28, 52, 703]:\n    print(n, col_letter(n), col_number(col_letter(n)))\nsafe = re.sub(r"[/\\\\?*\\[\\]:]", "-", "Sales 2026/10: Giza")[:31]\nprint(safe)')],
    practice: [B('اكتب معادلة `=SUM(B2:B50)` لكل عمود من B لـ M بالدالة.', 'Write a `=SUM(B2:B50)` formula for every column from B to M using the function.'),
      B('نضّف 5 أسماء شيتات فيها حروف ممنوعة.', 'Clean 5 sheet names that contain forbidden characters.')],
    words: [W('column letter', 'اسم العمود بالحروف في Excel (A، AB)', 'an Excel column’s name in letters (A, AB)', 'Convert 28 to the column letter AB.'),
      W('sheet name', 'اسم ورقة العمل في ملف Excel', 'the name of a worksheet in an Excel file', 'A sheet name cannot contain a slash.')],
    quiz: [Q(B('العمود رقم 27 =', 'Column number 27 ='), ['AA', 'Z', 'AB'], 0, B('بعد Z بيبدأ AA.', 'After Z comes AA.'))] },
  { learn: [L(B('تقرير فيه صف إجمالي', 'A report with a totals row'),
      B('التقرير المحترف: سطر عناوين واضح، أرقام بفاصل الآلاف وخانتين عشريتين، و**صف إجمالي** في الآخر. في openpyxl: `cell.number_format = "#,##0.00"` والعناوين `Font(bold=True)`. وقبل Excel، اتأكد من الحسابات في CSV بسيط.',
        'A professional report: a clear header row, numbers with thousands separators and two decimals, and a **totals row** at the end. In openpyxl: `cell.number_format = "#,##0.00"` and headers with `Font(bold=True)`. Before Excel, check the maths in a simple CSV.'),
      'ws.append(["Total", "", f"=SUM(C2:C{ws.max_row})"])\nfor cell in ws[1]: cell.font = Font(bold=True)\nws["C2"].number_format = "#,##0.00"')],
    code: [C(B('CSV تقرير بإجمالي', 'A CSV report with a total'),
      'import csv, io\norders = [("Sara", "Giza", 1250.5), ("Omar", "Cairo", 980), ("Mona", "Alex", 15300.25)]\nout = io.StringIO()\nw = csv.writer(out, lineterminator="\\n")\nw.writerow(["Customer", "City", "Total (EGP)"])\nfor name, city, total in orders:\n    w.writerow([name, city, f"{total:,.2f}"])\nw.writerow(["Total", "", f"{sum(t for *_, t in orders):,.2f}"])\nprint(out.getvalue())')],
    practice: [B('ضيف صف «متوسط» وعمود «نسبة من الإجمالي».', 'Add an «average» row and a «share of total» column.'),
      B('اعمل نفس التقرير في Excel بـ openpyxl (لو متثبتة عندك) بعناوين bold.', 'Build the same report in Excel with openpyxl (if installed) with bold headers.')],
    words: [W('header style', 'شكل سطر العناوين (bold، لون)', 'the look of the header row (bold, colour)', 'Set a header style for the first row.'),
      W('totals row', 'صف المجموع في آخر الجدول', 'the row of sums at the end of a table', 'Add a totals row with SUM.')],
    quiz: [Q(B('`f"{1250.5:,.2f}"` =', '`f"{1250.5:,.2f}"` ='), ['"1,250.50"', '"1250.5"', '"1.250,50"'], 0, B(', للآلاف و.2 لخانتين.', ', for thousands and .2 for two decimals.'))] },
  { learn: [L(B('تواريخ Excel كأرقام', 'Excel dates as numbers'),
      B('Excel بيخزّن التاريخ **رقم أيام** من 1899-12-30 (`46298` = 2026-10-03)، والكسر هو الوقت. لو قريت ملف ولقيت أرقام بدل تواريخ، حوّلها: `datetime(1899, 12, 30) + timedelta(days=n)`. وللفلوس من Excel: `Decimal(str(x)).quantize(Decimal("0.01"))`.',
        'Excel stores a date as a **number of days** since 1899-12-30 (`46298` = 2026-10-03), and the fraction is the time. If you read a file and get numbers instead of dates, convert them: `datetime(1899, 12, 30) + timedelta(days=n)`. For money from Excel: `Decimal(str(x)).quantize(Decimal("0.01"))`.'),
      'datetime(1899, 12, 30) + timedelta(days=46298.5)   # 2026-10-03 12:00')],
    code: [C(B('تحويل أرقام Excel لتواريخ', 'Converting Excel numbers to dates'),
      'from datetime import datetime, timedelta\nfrom decimal import Decimal\nEPOCH = datetime(1899, 12, 30)\nfor serial in [46298, 46298.5, 46298.75]:\n    print(serial, "->", (EPOCH + timedelta(days=serial)).strftime("%Y-%m-%d %H:%M"))\nprint("back:", (datetime(2026, 10, 3) - EPOCH).days)\nprice = 19.999999\nprint(Decimal(str(price)).quantize(Decimal("0.01")))')],
    practice: [B('اقرا عمود تواريخ طالع أرقام وحوّله لـ ISO.', 'Read a date column that came out as numbers and convert it to ISO.'),
      B('حوّل تاريخ ميلادك لرقم Excel وتأكد في Excel.', 'Turn your birthday into an Excel number and check it in Excel.')],
    words: [W('serial date', 'تاريخ متخزّن كعدد أيام', 'a date stored as a count of days', 'Excel keeps a serial date like 46298.'),
      W('quantize', 'تقرّب Decimal لعدد خانات محدد', 'to round a Decimal to a set number of places', 'Quantize the price to two decimals.')],
    quiz: [Q(B('الجزء العشري في رقم تاريخ Excel:', 'The decimal part of an Excel date number:'), ['the time of day', 'the year', 'nothing'], 0, B('0.5 = الضهر.', '0.5 = noon.'))] },
  { learn: [L(B('تقسيم ودمج الملفات بمفتاح', 'Splitting and merging files by a key'),
      B('**تقسيم**: ملف كبير لملف لكل فرع/مندوب — جمّع الصفوف بالمفتاح واكتب كل مجموعة لوحدها. **دمج**: ملفين (طلبات وعملاء) بعمود مشترك — اعمل dict من الملف الصغير بالمفتاح، وامشي على الكبير. ده نفس فكرة VLOOKUP بس أسرع وأدق.',
        '**Split**: one big file into a file per branch/rep — group rows by the key and write each group separately. **Merge**: two files (orders and customers) by a shared column — build a dict from the small file by key, then walk the big one. Same idea as VLOOKUP, but faster and exact.'),
      'customers = {r["id"]: r for r in csv.DictReader(open("customers.csv"))}\nfor o in csv.DictReader(open("orders.csv")):\n    c = customers.get(o["customer_id"])')],
    code: [C(B('دمج بمفتاح وتقسيم بمدينة', 'Merge by key and split by city'),
      'import csv, io\nfrom collections import defaultdict\ncustomers = {"c1": {"name": "Sara", "city": "Giza"}, "c2": {"name": "Omar", "city": "Cairo"}}\norders_csv = "order,customer_id,total\\n1,c1,300\\n2,c2,150\\n3,c1,90\\n4,c9,40\\n"\nby_city = defaultdict(list)\nfor o in csv.DictReader(io.StringIO(orders_csv)):\n    c = customers.get(o["customer_id"])\n    if not c:\n        print("no customer for order", o["order"])\n        continue\n    by_city[c["city"]].append({**o, "name": c["name"]})\nfor city, rows in by_city.items():\n    print(f"{city}.csv:", [(r[\'order\'], r[\'name\'], r[\'total\']) for r in rows])')],
    practice: [B('قسّم ملف مبيعات لملف لكل شهر.', 'Split a sales file into one file per month.'),
      B('ادمج ملف طلبات مع ملف أسعار بالـ SKU، واطبع الطلبات اللي ملهاش سعر.', 'Merge an orders file with a price list by SKU, and print orders with no price.')],
    words: [W('split file', 'ملف كبير اتقسم لملفات أصغر', 'a big file divided into smaller files', 'Send each branch its split file.'),
      W('merge key', 'العمود المشترك اللي بتدمج بيه', 'the shared column you merge on', 'customer_id is the merge key.')],
    quiz: [Q(B('ليه نعمل dict من الملف الصغير؟', 'Why build a dict from the small file?'), ['fast lookups by key', 'to sort it', 'to save space'], 0, B('بحث فوري بدل loop جوه loop.', 'Instant lookup instead of a loop inside a loop.'))] },
  { review: [B('⚡ Sniffer والـ dialects، وحروف الأعمدة، وتقرير بصف إجمالي.', '⚡ The Sniffer and dialects, column letters, and a report with a totals row.'),
      B('⚡ تواريخ Excel كأرقام وquantize، والتقسيم والدمج بمفتاح: ابني تقرير شهري لكل فرع.', '⚡ Excel dates as numbers and quantize, splitting and merging by key: build a monthly report per branch.')] }
] };
