// Python week 12 — the intensive hour (weeks 1–12 are 3 hours a day). Merged into the week by tools/build_weeks.js.
// Every code sample has run: 1 and uses only the standard library, so it also runs in the browser.
const B = (ar, en) => ({ ar, en });
const L = (h, p, ex) => ({ h, p, ex });
const C = (u, p) => ({ u, p, run: 1 });
const W = (t, ar, en, ex) => ({ t, m: B(ar, en), ex });
const Q = (q, o, a, why) => ({ q, o, a, why });
module.exports = { days: [
  { learn: [L(B('مدى الصفحات «1-3,7»', 'Page ranges «1-3,7»'),
      B('لما المستخدم يطلب «اطبع صفحات 1-3 و7» في أداة PDF، حوّل النص لقايمة أرقام صفحات صالحة قبل ما تفتح الملف (`pypdf` بيعد الصفحات من 0). اتحقق من الحدود، وشيل التكرار، ورتّب.',
        'When a user asks for «pages 1-3 and 7» in a PDF tool, turn the text into a list of valid page numbers before opening the file (`pypdf` counts pages from 0). Check the limits, remove repeats, and sort.'),
      'from pypdf import PdfReader, PdfWriter\nreader = PdfReader("in.pdf"); writer = PdfWriter()\nfor n in parse_pages("1-3,7", len(reader.pages)):\n    writer.add_page(reader.pages[n - 1])')],
    code: [C(B('تحليل مدى صفحات', 'Parsing a page range'),
      'def parse_pages(spec, page_count):\n    pages = set()\n    for part in spec.replace(" ", "").split(","):\n        if not part:\n            continue\n        start, _, end = part.partition("-")\n        a, b = int(start), int(end or start)\n        if a > b:\n            a, b = b, a\n        if a < 1 or b > page_count:\n            raise ValueError(f"{part}: pages must be between 1 and {page_count}")\n        pages.update(range(a, b + 1))\n    return sorted(pages)\n\nprint(parse_pages("1-3, 7, 2", 10))\nprint(parse_pages("9-8", 10))\ntry:\n    parse_pages("5-12", 10)\nexcept ValueError as e:\n    print("Error:", e)')],
    practice: [B('ضيف دعم `last` (آخر صفحة) و`odd` (الفردي).', 'Add support for `last` (the final page) and `odd` (odd pages).'),
      B('لو pypdf متثبتة: قسّم PDF حسب مدى بيدخله المستخدم.', 'If pypdf is installed: split a PDF by a range the user enters.')],
    words: [W('page range', 'مجموعة صفحات زي 1-3,7', 'a set of pages like 1-3,7', 'Validate the page range first.'),
      W('extract text', 'تطلّع النص من ملف زي PDF', 'to pull the text out of a file such as a PDF', 'Extract text from each page.')],
    quiz: [Q(B('`parse_pages("2,2,1", 5)` =', '`parse_pages("2,2,1", 5)` ='), ['[1, 2]', '[2, 2, 1]', '[2, 1]'], 0, B('set ثم sorted.', 'A set, then sorted.'))] },
  { learn: [L(B('قوالب بخانات: string.Template', 'Templates with placeholders: string.Template'),
      B('لعقود أو خطابات Word: القالب فيه خانات زي `$name` و`${date}`، وتملاها لكل عميل. `string.Template` آمن (مفيهوش تنفيذ كود) و`safe_substitute` بيسيب الخانة الناقصة زي ما هي بدل ما يكسر — تقدر بعدها تدوّر على `$` باقية. نفس الفكرة مع docx: تبدّل نص الخانة في كل paragraph.',
        'For Word contracts or letters: the template has placeholders like `$name` and `${date}`, filled per client. `string.Template` is safe (no code runs) and `safe_substitute` leaves a missing placeholder as it is instead of failing — then you can search for leftover `$`. The same idea works with docx: replace the placeholder text in each paragraph.'),
      'from string import Template\nTemplate("Dear $name, your invoice ${number} is due.").substitute(name="Sara", number="INV-7")')],
    code: [C(B('ملء قالب خطاب', 'Filling a letter template'),
      'from string import Template\nimport re\nletter = Template("""Dear $name,\nThank you for choosing $company. Your plan "$plan" starts on ${start}.\nTotal: $total EGP.""")\nclients = [\n    {"name": "Sara Adel", "company": "Nile Tech", "plan": "Automation Pro", "start": "2026-11-01", "total": "4,500"},\n    {"name": "Omar Ali", "company": "Nile Tech", "plan": "Starter"},\n]\nfor c in clients:\n    text = letter.safe_substitute(c)\n    missing = re.findall(r"\\$\\{?(\\w+)", text)\n    print(text)\n    print("missing:", missing or "none", "\\n")')],
    practice: [B('اعمل قالب عرض سعر بـ 6 خانات واملاه لـ 3 عملاء.', 'Build a quotation template with 6 placeholders and fill it for 3 clients.'),
      B('لو python-docx متثبتة: بدّل الخانات في ملف docx.', 'If python-docx is installed: replace the placeholders in a docx file.')],
    words: [W('placeholder tag', 'علامة في القالب بتتبدل بقيمة زي $name', 'a marker in a template replaced by a value, like $name', 'Every placeholder tag must be filled.'),
      W('paragraph style', 'شكل فقرة في Word (عنوان، نص عادي)', 'the look of a paragraph in Word (heading, normal)', 'Keep the paragraph style when you replace text.')],
    quiz: [Q(B('`safe_substitute` لو خانة ناقصة:', '`safe_substitute` with a missing value:'), ['leaves the placeholder', 'raises KeyError', 'deletes the line'], 0, B('substitute العادية هي اللي بتكسر.', 'Plain substitute is the one that fails.'))] },
  { learn: [L(B('حساب المقاسات قبل التصغير', 'Working out sizes before resizing'),
      B('قبل ما تصغّر صور بالجملة بـ Pillow، احسب المقاس الجديد اللي **بيحافظ على النسبة**: `scale = min(max_w / w, max_h / h, 1)` (الـ 1 عشان متكبّرش صورة صغيرة). Pillow عنده `img.thumbnail((800, 800))` بيعمل ده لوحده، بس لازم تفهمه عشان التقارير وقواعد التسمية.',
        'Before batch-resizing images with Pillow, compute the new size that **keeps the ratio**: `scale = min(max_w / w, max_h / h, 1)` (the 1 stops small images being enlarged). Pillow’s `img.thumbnail((800, 800))` does this for you, but understand it for reports and naming rules.'),
      'from PIL import Image\nwith Image.open(path) as img:\n    img.thumbnail((800, 800))\n    img.save(out / f"{path.stem}_800.jpg", quality=85)')],
    code: [C(B('مقاسات جديدة بنفس النسبة', 'New sizes with the same ratio'),
      'def fit(w, h, max_w=800, max_h=800):\n    scale = min(max_w / w, max_h / h, 1)\n    return round(w * scale), round(h * scale)\n\nphotos = {"shop.jpg": (4000, 3000), "logo.png": (500, 200), "banner.jpg": (1920, 480), "tall.jpg": (1080, 1920)}\nfor name, (w, h) in photos.items():\n    nw, nh = fit(w, h)\n    print(f"{name:<11} {w}x{h} -> {nw}x{nh}  ratio kept: {abs(w / h - nw / nh) < 0.01}")')],
    practice: [B('احسب مقاسات صورة لـ 3 أحجام (thumbnail، موبايل، ويب).', 'Compute an image’s sizes for 3 targets (thumbnail, mobile, web).'),
      B('لو Pillow متثبتة: صغّر فولدر صور واحفظ بلاحقة `_800`.', 'If Pillow is installed: resize a folder of images and save them with a `_800` suffix.')],
    words: [W('resize', 'تغيّر مقاس صورة', 'to change an image’s size', 'Resize the photos before uploading.'),
      W('batch resize', 'تصغير صور كتير مرة واحدة', 'resizing many images at once', 'A batch resize saves hours.')],
    quiz: [Q(B('صورة 500×200 والحد 800×800:', 'A 500×200 image with an 800×800 limit:'), ['stays 500×200', 'becomes 800×320', 'becomes 800×800'], 0, B('الـ 1 بيمنع التكبير.', 'The 1 prevents enlarging.'))] },
  { learn: [L(B('بناء إيميل بمرفق (من غير إرسال)', 'Building an email with an attachment (without sending)'),
      B('`email.message.EmailMessage` بيبني الرسالة: الموضوع، المرسل، المستقبل، نص عادي ونسخة HTML (`add_alternative`)، ومرفقات (`add_attachment` مع نوع **MIME** زي `application/pdf`). ابنيها واطبع الـ headers للمراجعة، وبعدين ابعتها بـ `smtplib` في السكربت الحقيقي (باسورد التطبيق من `.env`).',
        '`email.message.EmailMessage` builds the message: subject, sender, recipient, plain text and an HTML version (`add_alternative`), and attachments (`add_attachment` with a **MIME** type like `application/pdf`). Build it and print the headers to review, then send it with `smtplib` in the real script (the app password from `.env`).'),
      'msg.add_attachment(pdf_bytes, maintype="application", subtype="pdf", filename="invoice.pdf")\nwith smtplib.SMTP_SSL("smtp.gmail.com", 465) as s:\n    s.login(USER, APP_PASSWORD); s.send_message(msg)')],
    code: [C(B('رسالة بنسختين ومرفق', 'A message with two versions and an attachment'),
      'from email.message import EmailMessage\nmsg = EmailMessage()\nmsg["Subject"] = "Invoice INV-2026-0007"\nmsg["From"] = "billing@example.com"\nmsg["To"] = "sara@example.com"\nmsg.set_content("Hi Sara,\\nYour invoice is attached.\\nThanks!")\nmsg.add_alternative("<p>Hi Sara,<br>Your invoice is <b>attached</b>.</p>", subtype="html")\nmsg.add_attachment(b"%PDF-1.4 demo", maintype="application", subtype="pdf", filename="INV-2026-0007.pdf")\nfor part in msg.walk():\n    print(part.get_content_type(), part.get_filename() or "")\nprint(len(msg.as_bytes()), "bytes")')],
    practice: [B('ابني رسالة لـ 3 عملاء من قايمة، كل واحد بمرفقه، واطبع الملخص من غير إرسال.', 'Build a message for 3 customers from a list, each with its own attachment, and print a summary without sending.'),
      B('ضيف وضع `dry_run` يطبع بدل ما يبعت.', 'Add a `dry_run` mode that prints instead of sending.')],
    words: [W('mime', 'نوع المحتوى في الإيميل والويب (text/html)', 'the content type in email and the web (text/html)', 'The PDF part has the MIME type application/pdf.'),
      W('email message', 'كائن بايثون بيبني إيميل كامل', 'a Python object that builds a complete email', 'Build the email message before sending it.')],
    quiz: [Q(B('`add_alternative(html, subtype="html")` بيعمل:', '`add_alternative(html, subtype="html")` adds:'), ['an HTML version of the same text', 'an attachment', 'a second email'], 0, B('البرامج بتختار النسخة المناسبة.', 'Mail apps pick the right version.'))] },
  { learn: [L(B('أرقام فواتير برقم تحقق', 'Invoice numbers with a check digit'),
      B('رقم الفاتورة لازم يكون **فريد ومتسلسل** بشكل ثابت: `INV-2026-0007`. خزّن آخر رقم في ملف (بكتابة آمنة) أو قاعدة بيانات. وتقدر تضيف **رقم تحقق** (خوارزمية Luhn) عشان أي غلطة كتابة في الرقم تتكشف فورًا — نفس فكرة أرقام الكروت.',
        'An invoice number must be **unique and sequential** with a fixed format: `INV-2026-0007`. Store the last number in a file (with a safe write) or a database. You can add a **check digit** (the Luhn algorithm) so any typing mistake in the number is caught at once — the same idea as card numbers.'),
      'def next_number(last, year):\n    return f"INV-{year}-{last + 1:04d}"')],
    code: [C(B('ترقيم فواتير مع Luhn', 'Invoice numbering with Luhn'),
      'def luhn_digit(digits):\n    total = 0\n    for i, ch in enumerate(reversed(digits)):\n        d = int(ch)\n        if i % 2 == 0:\n            d *= 2\n            if d > 9:\n                d -= 9\n        total += d\n    return str((10 - total % 10) % 10)\n\ndef invoice_number(year, seq):\n    core = f"{year}{seq:04d}"\n    return f"INV-{year}-{seq:04d}-{luhn_digit(core)}"\n\ndef is_valid(number):\n    _, year, seq, check = number.split("-")\n    return luhn_digit(year + seq) == check\n\nlast = 6\nfor _ in range(3):\n    last += 1\n    n = invoice_number(2026, last)\n    print(n, is_valid(n))\nprint("typo:", is_valid("INV-2026-0070-" + invoice_number(2026, 7)[-1]))')],
    practice: [B('احفظ آخر رقم في `state.json` بالكتابة الآمنة من أسبوع 9.', 'Store the last number in `state.json` with the safe write from week 9.'),
      B('لو qrcode متثبتة: اعمل QR فيه رقم الفاتورة والإجمالي.', 'If qrcode is installed: make a QR code holding the invoice number and total.')],
    words: [W('invoice number', 'رقم فريد لكل فاتورة', 'a unique number for each invoice', 'Never reuse an invoice number.'),
      W('check digit', 'رقم إضافي بيكشف أخطاء الكتابة', 'an extra digit that detects typing errors', 'The check digit caught the typo.')],
    quiz: [Q(B('فايدة رقم التحقق:', 'The purpose of a check digit:'), ['catching typing mistakes', 'making the number secret', 'sorting invoices'], 0, B('مش تشفير.', 'It is not encryption.'))] },
  { review: [B('⚡ مدى الصفحات، وقوالب string.Template، وحساب مقاسات الصور.', '⚡ Page ranges, string.Template templates, and computing image sizes.'),
      B('⚡ EmailMessage بمرفق، وأرقام الفواتير برقم تحقق: اجمعهم في مشروع الشهر التالت (فاتورة + إيميل).', '⚡ EmailMessage with attachments, and invoice numbers with a check digit: combine them in the month 3 project (invoice + email).')] }
] };
