// Week 8 — The passive voice in documentation (end of month 2).
const B = (ar, en) => ({ ar, en });
module.exports = {
  level: 'A2 → B1',
  title: B('المبني للمجهول (Passive) في التوثيق', 'The passive voice in documentation'),
  goal: B('تقرا وتكتب جمل الـ passive اللي مليانة في التوثيق (The data is stored…)، وتعرف إمتى المبني للمعلوم أوضح، وتوصف سيستم كامل.',
          'Read and write the passive sentences that fill documentation (The data is stored…), know when the active voice is clearer, and describe a whole system.'),
  days: [
    { title: B('is + التصريف التالت', 'is + past participle'),
      goal: B('تبني جملة passive بسيطة وتفهم ليه التوثيق بيستخدمها.', 'Build a simple passive sentence and understand why documentation uses it.'),
      learn: [
        'g:Passive voice في التوثيق',
        { h: B('ليه التوثيق بيحب الـ passive', 'Why docs love the passive'),
          p: B('لأن المهم هو الحاجة نفسها مش مين عملها: The password is hashed. The file is saved in /data. مين اللي عمل الـ hash؟ السيستم، ومش مهم نقوله.', 'Because what matters is the thing, not who does it: The password is hashed. The file is saved in /data. Who hashes it? The system, and we don\'t need to say so.'),
          ex: 'Each order is stored in the orders table.\nThe ID is generated automatically.\nEmails are sent every hour.' },
        { h: B('by لما الفاعل مهم', 'by when the doer matters'),
          p: B('لو عايز تقول مين: The report is generated by a cron job. The request is handled by the auth service.', 'If you want to say who: The report is generated by a cron job. The request is handled by the auth service.'),
          ex: 'The queue is processed by three workers.' }
      ],
      practice: [
        B('اكتب 8 جمل passive عن قاعدة بيانات مشروعك (is stored، is created، are deleted…).', 'Write 8 passive sentences about your project\'s database (is stored, is created, are deleted…).'),
        B('حوّل 5 جمل active لـ passive: `The script creates a backup.` ← `A backup is created by the script.`', 'Turn 5 active sentences into passive: `The script creates a backup.` → `A backup is created by the script.`'),
        B('اقرا صفحة توثيق ولوّن كل جملة passive (be + participle).', 'Read a docs page and highlight every passive sentence (be + participle).'),
        B('اوصف جدول واحد من قاعدة بياناتك في 5 جمل: الأعمدة، والمفتاح، والعلاقات.', 'Describe one table from your database in 5 sentences: columns, key and relations.')
      ],
      words: ['database', 'table', 'row', 'column', 'query', 'primary key', 'foreign key'],
      read: [{ lib: 'Google Developer Documentation Style Guide', what: B('دوّر على «Active voice» واقرا إمتى بيقترحوا الـ passive.', 'Search for "Active voice" and read when they accept the passive.') }],
      challenge: B('اكتب قسم «Data model» لمشروعك: جدول لكل table، وتحته 3 جمل passive بتشرح البيانات بتتخزن وتتمسح إزاي.', 'Write a "Data model" section for your project: a table per database table, with 3 passive sentences under each explaining how the data is stored and deleted.'),
      quiz: [
        { q: B('أنهي جملة passive؟', 'Which sentence is passive?'), o: ['The system hashes the password.', 'The password is hashed.', 'The password hashes.'], a: 1, why: B('be + التصريف التالت.', 'be + past participle.') },
        { q: B('اختار الصح:', 'Choose the correct one:'), o: ['The logs are store in /var/log.', 'The logs are stored in /var/log.', 'The logs stored in /var/log.'], a: 1, why: B('are + stored.', 'are + stored.') },
        { q: B('primary key هو:', 'A primary key is:'), o: [B('عمود بيميّز كل صف', 'a column that identifies each row'), B('باسورد القاعدة', 'the database password'), B('أول جدول', 'the first table')], a: 0, why: B('قيمة فريدة لكل صف.', 'A unique value for each row.') }
      ] },

    { title: B('الـ passive في الأزمنة التانية', 'The passive in other tenses'),
      goal: B('تستخدم الـ passive في الماضي والمستقبل والـ present perfect ومع can/must.', 'Use the passive in the past, the future, the present perfect, and with can/must.'),
      learn: [
        'g:المبني للمجهول في الأزمنة التانية',
        { h: B('passive مع can وmust وshould', 'The passive with can, must and should'),
          p: B('modal + be + التصريف التالت: The key must be kept secret. This value can be changed in settings. Old logs should be deleted.', 'modal + be + past participle: The key must be kept secret. This value can be changed in settings. Old logs should be deleted.'),
          ex: 'The token must be sent in the header.\nThis field cannot be empty.\nThe cache will be cleared at midnight.' },
        { h: B('في رسايل الأخطاء', 'In error messages'),
          p: B('رسايل كتير passive: Access is denied. The resource has been deleted. The request was rejected. The connection was refused.', 'Many messages are passive: Access is denied. The resource has been deleted. The request was rejected. The connection was refused.'),
          ex: 'Error: This version has been deprecated.\nWarning: The file was not found and will be created.' }
      ],
      practice: [
        B('اكتب جملة passive واحدة لكل زمن: was، has been، will be، is being، must be.', 'Write one passive sentence in each form: was, has been, will be, is being, must be.'),
        B('اكتب 5 قواعد لـ API بـ must be / can be / cannot be.', 'Write 5 rules for an API with must be / can be / cannot be.'),
        B('اشرح 4 رسايل أخطاء passive حقيقية بجملة لكل واحدة.', 'Explain 4 real passive error messages in one sentence each.'),
        B('اكتب ترحيل (migration) لقاعدة بيانات في 5 خطوات passive (The table was renamed…).', 'Write a database migration in 5 passive steps (The table was renamed…).')
      ],
      words: ['insert / update / delete', 'transaction', 'index (database)', 'constraint', 'relational database', 'normalization', 'stored procedure'],
      read: [{ lib: 'Perfect English Grammar', what: B('اقرا «The Passive Voice» وحل التمرين اللي فيه أزمنة مختلفة.', 'Read "The Passive Voice" and do the exercise with different tenses.') }],
      challenge: B('اكتب «migration notes» لتغيير في قاعدة بيانات: اللي اتغيّر (past)، واللي هيتغيّر (future)، واللي لازم يتعمل (must be).', 'Write migration notes for a database change: what was changed (past), what will be changed (future), and what must be done (must be).'),
      quiz: [
        { q: B('اختار الصح:', 'Choose the correct one:'), o: ['The key must kept secret.', 'The key must be kept secret.', 'The key must be keep secret.'], a: 1, why: B('must + be + kept.', 'must + be + kept.') },
        { q: B('اختار الصح:', 'Choose the correct one:'), o: ['The user has been deleted.', 'The user has deleted.', 'The user has be deleted.'], a: 0, why: B('has + been + deleted.', 'has + been + deleted.') },
        { q: B('transaction في قاعدة البيانات:', 'A database transaction is:'), o: [B('مجموعة عمليات بتتنفذ كلها أو ولا واحدة', 'a group of operations that all succeed or none do'), B('تحويل فلوس', 'a money transfer'), B('نسخة احتياطية', 'a backup')], a: 0, why: B('all or nothing.', 'all or nothing.') }
      ] },

    { title: B('إمتى المعلوم أوضح', 'When the active voice is clearer'),
      goal: B('تختار بين active وpassive: التعليمات والخطوات active، ووصف السيستم ممكن passive.', 'Choose between active and passive: instructions and steps are active; system descriptions can be passive.'),
      learn: [
        'g:المبني للمعلوم أوضح',
        { h: B('القاعدة العملية', 'The practical rule'),
          p: B('لو القارئ هو اللي هيعمل الحاجة، كلّمه مباشرة: Click Save. لو السيستم هو اللي بيعمل، ممكن passive. ولو الجملة بقت غامضة (مين؟)، رجّعها active.', 'If the reader does the action, speak to them directly: Click Save. If the system does it, the passive is fine. If the sentence becomes vague (who?), make it active.'),
          ex: '✗ The file should be uploaded by you.\n✓ Upload the file.\n✓ The file is scanned for viruses.' },
        { h: B('وصف الواجهة', 'Describing the front end'),
          p: B('The button triggers an event. The event listener calls a function. The component updates its state and re-renders.', 'The button triggers an event. The event listener calls a function. The component updates its state and re-renders.'),
          ex: 'When the user clicks Submit, the form sends a request.\nThe response is shown in a toast message.' }
      ],
      practice: [
        B('حوّل 6 جمل passive غامضة لـ active واضحة.', 'Turn 6 vague passive sentences into clear active ones.'),
        B('اكتب 5 خطوات استخدام لتطبيق بالأمر (Click…, Enter…, Choose…).', 'Write 5 usage steps for an app in the imperative (Click…, Enter…, Choose…).'),
        B('اوصف اللي بيحصل لما تدوس زرار في صفحة ويب: event، callback، request، response، في 6 جمل.', 'Describe what happens when you click a button on a web page — event, callback, request, response — in 6 sentences.'),
        B('اكتب 3 جمل بـ async / await تشرح كود بيستنى API.', 'Write 3 sentences with async / await explaining code that waits for an API.')
      ],
      words: ['DOM', 'event listener', 'callback', 'promise', 'async / await', 'component', 'state'],
      read: [{ lib: 'Google Technical Writing Courses', what: B('افتح Technical Writing One واقرا وحدة «Active voice versus passive voice».', 'Open Technical Writing One and read the "Active voice versus passive voice" unit.') }],
      challenge: B('خد صفحة توثيق كتبتها قبل كده (أو README) وأعد كتابة كل جملة passive غامضة، واكتب قبل وبعد.', 'Take a docs page you wrote before (or a README) and rewrite every vague passive sentence, showing before and after.'),
      quiz: [
        { q: B('أوضح خطوة للمستخدم:', 'The clearest step for the user:'), o: ['The Save button should be clicked.', 'Click Save.', 'Save is clicked by the user.'], a: 1, why: B('التعليمات = أمر مباشر.', 'Instructions = a direct command.') },
        { q: B('أنهي جملة الـ passive فيها مناسب؟', 'In which sentence is the passive fine?'), o: ['The data is encrypted at rest.', 'The form must be filled by you.', 'It was decided that you should click.'], a: 0, why: B('السيستم هو اللي بيشفّر، ومش مهم نقول مين.', 'The system encrypts it; who does it doesn\'t matter.') },
        { q: B('event listener هو:', 'An event listener is:'), o: [B('كود بيستنى حدث زي click', 'code that waits for an event like a click'), B('ملف صوت', 'an audio file'), B('سيرفر', 'a server')], a: 0, why: B('بيسمع للحدث وينفذ دالة.', 'It listens for the event and runs a function.') }
      ] },

    { title: B('let وallow والصلاحيات', 'let, allow and permissions'),
      goal: B('تستخدم let/allow/enable صح، وتكتب عن الأمان والصلاحيات.', 'Use let/allow/enable correctly and write about security and permissions.'),
      learn: [
        'g:let و allow',
        { h: B('enable وprevent', 'enable and prevent'),
          p: B('enable someone to do something، وprevent someone from doing something. The firewall prevents attackers from accessing the database.', 'enable someone to do something, and prevent someone from doing something. The firewall prevents attackers from accessing the database.'),
          ex: 'This role allows users to edit posts.\nThe setting lets admins export data.\nRate limiting prevents clients from sending too many requests.' },
        { h: B('least privilege', 'Least privilege'),
          p: B('ادي كل حد أقل صلاحية محتاجها: Each service only has the permissions it needs. ولو مفتاح اتسرّب: Rotate the key immediately.', 'Give everyone the least access they need: Each service only has the permissions it needs. If a key leaks: Rotate the key immediately.'),
          ex: 'The read-only user cannot delete tables.\nIf a key is leaked, it must be rotated.' }
      ],
      practice: [
        B('اكتب 6 جمل عن أدوار (roles) في تطبيق بـ allows… to / lets… / cannot.', 'Write 6 sentences about roles in an app with allows… to / lets… / cannot.'),
        B('صلّح: `It allows to export.` و`Let me to check.` و`It prevents users to delete.`', 'Fix: `It allows to export.`, `Let me to check.` and `It prevents users to delete.`'),
        B('اكتب «Security checklist» من 6 بنود للمشروع (sanitize input، hash passwords…).', 'Write a 6-item security checklist for your project (sanitize input, hash passwords…).'),
        B('اشرح SQL injection في 4 جمل بسيطة، وإزاي تمنعها.', 'Explain SQL injection in 4 simple sentences, and how to prevent it.')
      ],
      words: ['vulnerability', 'hash', 'sanitize', 'SQL injection', 'leak', 'rotate (a key)', 'least privilege'],
      read: [{ lib: 'OWASP Top 10', what: B('اقرا أسماء الـ 10 مخاطر، وافتح «Injection» واقرا الملخص.', 'Read the names of the 10 risks, then open "Injection" and read the summary.') }],
      challenge: B('اكتب قسم «Security» في README مشروعك: الصلاحيات، وتخزين الأسرار، ولو في مشكلة أمان يبلّغ إزاي.', 'Write a "Security" section in your project README: permissions, storing secrets, and how to report a security issue.'),
      quiz: [
        { q: B('اختار الصح:', 'Choose the correct one:'), o: ['This role allows to edit posts.', 'This role allows users to edit posts.', 'This role lets users to edit posts.'], a: 1, why: B('allow + شخص + to.', 'allow + someone + to.') },
        { q: B('اختار الصح:', 'Choose the correct one:'), o: ['Let me check the logs.', 'Let me to check the logs.', 'Let me checking the logs.'], a: 0, why: B('let + شخص + الفعل من غير to.', 'let + someone + the verb without to.') },
        { q: B('لو مفتاح API اتسرّب، أول حاجة:', 'If an API key leaks, the first thing to do is:'), o: [B('rotate the key', 'rotate the key'), B('تكتب إيميل', 'write an email'), B('تستنى', 'wait')], a: 0, why: B('غيّر المفتاح فورًا.', 'Change the key immediately.') }
      ] },

    { title: B('وصف السيستم كامل', 'Describing a whole system'),
      goal: B('توصف معمارية سيستم (architecture) في فقرة: الأجزاء، وبتتكلم مع بعض إزاي، والبيانات بتتخزن فين.', 'Describe a system\'s architecture in a paragraph: the parts, how they talk to each other, and where data is stored.'),
      learn: [
        { h: B('فقرة المعمارية', 'The architecture paragraph'),
          p: B('ابدأ بالصورة الكبيرة، وبعدين كل جزء، وبعدين رحلة الطلب: The system consists of… The frontend sends requests to… The data is stored in…', 'Start with the big picture, then each part, then the path of a request: The system consists of… The frontend sends requests to… The data is stored in…'),
          ex: 'The app consists of a React frontend, a Node.js API and a PostgreSQL database.\nRequests go through a load balancer to two API servers.\nFiles are stored in S3, and emails are sent by a worker.' },
        'g:أدوات الربط',
        'g:التوازي في القوايم'
      ],
      practice: [
        B('ارسم معمارية مشروعك (أو تطبيق تعرفه) واكتب تحتها فقرة 8 جمل.', 'Draw the architecture of your project (or an app you know) and write an 8-sentence paragraph under it.'),
        B('اكتب «رحلة طلب» من المتصفح لقاعدة البيانات ورجوع، في 6 خطوات.', 'Write the "journey of a request" from the browser to the database and back, in 6 steps.'),
        B('اكتب 5 جمل بأدوات الربط: however، therefore، because، so، although.', 'Write 5 sentences with linking words: however, therefore, because, so, although.'),
        B('صلّح التوازي: `The app lets you create posts, editing them and to delete them.`', 'Fix the parallelism: `The app lets you create posts, editing them and to delete them.`')
      ],
      words: ['frontend / backend', 'microservices / monolith', 'protocol', 'router', 'network', 'firewall', 'process'],
      read: [{ lib: 'roadmap.sh', what: B('افتح roadmap الـ Backend واقرا عناوين أول 10 مواضيع وافهم الكلمات.', 'Open the Backend roadmap and read the titles of the first 10 topics, understanding the words.') }],
      challenge: B('سجّل نفسك وانت بتشرح معمارية مشروعك في دقيقتين، كأنك في أول يوم مع زميل جديد.', 'Record yourself explaining your project\'s architecture in two minutes, as if on a new teammate\'s first day.'),
      quiz: [
        { q: B('اختار الصح:', 'Choose the correct one:'), o: ['The system consists of three services.', 'The system consists from three services.', 'The system is consist of three services.'], a: 0, why: B('consist of، ومن غير is.', 'consist of, without is.') },
        { q: B('اختار الجملة المتوازية:', 'Choose the parallel sentence:'), o: ['You can create, edit and delete posts.', 'You can create, editing and to delete posts.', 'You can creating, edit and deletion posts.'], a: 0, why: B('نفس الشكل لكل بند.', 'The same form for every item.') },
        { q: B('monolith هو:', 'A monolith is:'), o: [B('تطبيق واحد كبير فيه كل حاجة', 'one big application with everything in it'), B('خدمات صغيرة كتير', 'many small services'), B('قاعدة بيانات', 'a database')], a: 0, why: B('عكس microservices.', 'The opposite of microservices.') }
      ] },

    { title: B('مراجعة الشهر التاني والاختبار', 'Month 2 review and test'),
      goal: B('راجع الأسبوع والشهر كله، وسلّم مشروع الشهر، وخد الاختبار. الأسبوع 9 بيفتح لما تجيب 70% أو أكتر.', 'Review the week and the whole month, hand in the month project, and take the test. Week 9 opens when you score 70% or more.'),
      review: [
        B('قراءة التوثيق: أنواعه، وصفحة endpoint، والباراميترز، والـ auth.', 'Reading docs: the kinds, an endpoint page, parameters and auth.'),
        B('التسمية: الدالة فعل، والمتغيّر اسم، والتعليق يقول «ليه».', 'Naming: functions are verbs, variables are nouns, and comments say "why".'),
        B('present perfect للنتايج، وpast simple للوقت المحدد.', 'The present perfect for results, the past simple for a specific time.'),
        B('passive: be + التصريف التالت، ومع must be / has been / will be.', 'The passive: be + participle, and must be / has been / will be.'),
        B('التعليمات active، ووصف السيستم ممكن passive.', 'Instructions are active; system descriptions can be passive.'),
        B('let + الفعل، وallow/enable + to، وprevent from + ing.', 'let + verb, allow/enable + to, prevent from + -ing.')
      ],
      project: B('مشروع الشهر: اكتب «Technical overview» لمشروعك في صفحتين بالإنجليزي: Overview (فقرة)، وArchitecture (رسمة + فقرة passive)، وData model (جداول + جمل)، وAPI (3 endpoints بجدول باراميترز)، وSecurity، وChangelog لآخر إصدار. ابعته لحد يقراه ويسألك 3 أسئلة، وجاوبهم كتابة.',
                 'Month project: write a two-page English "Technical overview" of your project: Overview (a paragraph), Architecture (a diagram + a passive paragraph), Data model (tables + sentences), API (3 endpoints with parameter tables), Security, and a Changelog for the latest version. Send it to someone to read and ask you 3 questions, and answer them in writing.'),
      test: [
        { q: B('أنهي جملة passive صح؟', 'Which passive sentence is correct?'), o: ['The emails are send every hour.', 'The emails are sent every hour.', 'The emails sent every hour are.'], a: 1, why: B('are + sent.', 'are + sent.') },
        { q: B('اختار الصح:', 'Choose the correct one:'), o: ['The report is generated by a cron job.', 'The report is generated from a cron job by.', 'The report generates by a cron job.'], a: 0, why: B('by قبل الفاعل.', 'by before the doer.') },
        { q: B('اختار الصح:', 'Choose the correct one:'), o: ['The old API will be removed next month.', 'The old API will removed next month.', 'The old API will be remove next month.'], a: 0, why: B('will + be + removed.', 'will + be + removed.') },
        { q: B('«The connection was refused» معناها:', '"The connection was refused" means:'), o: [B('السيرفر رفض الاتصال', 'the server rejected the connection'), B('الاتصال نجح', 'the connection succeeded'), B('الاتصال بطيء', 'the connection is slow')], a: 0, why: B('refused = اترفض.', 'refused = rejected.') },
        { q: B('أوضح تعليمات:', 'The clearest instruction:'), o: ['The API key should be copied by you.', 'Copy the API key.', 'The API key is copied.'], a: 1, why: B('أمر مباشر للقارئ.', 'A direct command to the reader.') },
        { q: B('اختار الصح:', 'Choose the correct one:'), o: ['The setting lets admins export data.', 'The setting lets admins to export data.', 'The setting allows admins export data.'], a: 0, why: B('let + الفعل من غير to.', 'let + verb without to.') },
        { q: B('اختار الصح:', 'Choose the correct one:'), o: ['It prevents users to delete tables.', 'It prevents users from deleting tables.', 'It prevents users delete tables.'], a: 1, why: B('prevent from + ing.', 'prevent from + -ing.') },
        { q: B('foreign key هو:', 'A foreign key is:'), o: [B('عمود بيشاور على صف في جدول تاني', 'a column that points to a row in another table'), B('مفتاح من بلد تانية', 'a key from another country'), B('باسورد', 'a password')], a: 0, why: B('بيربط الجداول ببعض.', 'It links tables together.') },
        { q: B('SQL injection بيحصل لما:', 'SQL injection happens when:'), o: [B('مدخلات المستخدم بتتحط في الـ query من غير تنضيف', 'user input goes into a query without being sanitized'), B('القاعدة بطيئة', 'the database is slow'), B('الجدول كبير', 'the table is big')], a: 0, why: B('استخدم parameterized queries.', 'Use parameterized queries.') },
        { q: B('اختار الصح:', 'Choose the correct one:'), o: ['The app consists of a frontend and an API.', 'The app is consisted of a frontend and an API.', 'The app consists from a frontend and an API.'], a: 0, why: B('consist of في الـ active.', 'consist of, in the active.') },
        { q: B('أداة الربط المناسبة: `The test passed; ___, the bug is still there.`', 'The right linking word: `The test passed; ___, the bug is still there.`'), o: ['however', 'therefore', 'because'], a: 0, why: B('however = ومع ذلك (عكس المتوقع).', 'however = even so (contrast).') },
        { q: B('async / await بيستخدم لـ:', 'async / await is used to:'), o: [B('تستنى عملية بتاخد وقت من غير ما توقف كل حاجة', 'wait for a slow operation without blocking everything'), B('تسرّع الكمبيوتر', 'speed up the computer'), B('تحذف بيانات', 'delete data')], a: 0, why: B('للعمليات غير المتزامنة زي طلبات الشبكة.', 'For asynchronous work such as network requests.') }
      ] }
  ]
};
