// More prompts for the library on prompts.html: data, research, career and studying.
// Added with SECTIONS.extend; written for this site.
SECTIONS.extend('prompts', 'library', {
  cats: [
    { id: 'career', t: { ar: 'المسار المهني', en: 'Career' } },
    { id: 'think', t: { ar: 'التفكير والبحث', en: 'Thinking and research' } }
  ],
  items: [
    // ---------------- data (more) ----------------
    { id: 'data-sql-from-question', cat: 'data', lvl: 'b', t: { ar: 'سؤال → استعلام SQL', en: 'A question → an SQL query' },
      body: { ar: 'تكتب سؤالك بالعربي والجداول، وتاخد استعلام مشروح.', en: 'Write your question and tables; get an explained query.' },
      vars: { tables: { ar: 'الجداول وأعمدتها', en: 'Tables and columns' }, question: { ar: 'السؤال', en: 'The question' }, db: { ar: 'نوع قاعدة البيانات', en: 'Database type' } },
      code: 'Database: {{db}}. Tables:\n<tables>\n{{tables}}\n</tables>\n\nWrite a query that answers: {{question}}\nThen explain it clause by clause, list assumptions about the data (nulls, duplicates, time zones), and give one query I can run first to check those assumptions. Read-only queries only.' },
    { id: 'data-sheet-formula', cat: 'data', lvl: 'b', t: { ar: 'معادلة Google Sheets/Excel', en: 'A Google Sheets/Excel formula' },
      body: { ar: 'توصف اللي عايزه وتاخد المعادلة وشرحها.', en: 'Describe what you want; get the formula and how it works.' },
      vars: { goal: { ar: 'عايز المعادلة تعمل إيه', en: 'What the formula should do' }, sample: { ar: 'شكل الأعمدة وأمثلة', en: 'Column layout and examples' } },
      code: 'I need a spreadsheet formula (give both Google Sheets and Excel if they differ).\nGoal: {{goal}}\nMy sheet:\n<sample>\n{{sample}}\n</sample>\n\nGive the formula, explain each part, show the result for my sample rows, and mention what happens with empty cells or errors.' },
    { id: 'data-dashboard-plan', cat: 'data', lvl: 'i', t: { ar: 'تخطيط لوحة أرقام (dashboard)', en: 'Planning a dashboard' },
      body: { ar: 'إيه الأرقام اللي تهم صاحب الشغل فعلًا وإزاي تتعرض.', en: 'Which numbers really matter to the owner and how to show them.' },
      vars: { business: { ar: 'البيزنس', en: 'The business' }, data: { ar: 'البيانات المتاحة', en: 'The data available' } },
      code: 'Plan a simple dashboard for {{business}}. Data available:\n<data>\n{{data}}\n</data>\n\nGive: the 3 decisions the owner makes with it, 6–8 metrics (definition, formula, how often it updates), the best chart for each, the layout from top to bottom, and which numbers need an alert. Mark metrics the data cannot support yet.' },
    { id: 'data-anomaly', cat: 'data', lvl: 'i', t: { ar: 'ليه الرقم ده اتغيّر؟', en: 'Why did this number change?' },
      body: { ar: 'المبيعات وقعت فجأة: خطة تحقيق بدل التخمين.', en: 'Sales suddenly dropped: an investigation plan instead of guessing.' },
      vars: { metric: { ar: 'الرقم والتغيير', en: 'The metric and the change' }, data: { ar: 'البيانات المتاحة', en: 'Data available' } },
      code: 'Metric change: {{metric}}\nData I have:\n<data>\n{{data}}\n</data>\n\nGive a step-by-step investigation: first check if the data itself is broken (tracking, missing days, duplicates), then segment by time, channel, product and region, then compare with known events. For each step: what to check and the exact query or sheet filter. End with how to present the conclusion.' },
    { id: 'data-csv-clean-plan', cat: 'data', lvl: 'b', t: { ar: 'خطة تنضيف ملف CSV', en: 'A plan to clean a CSV file' },
      body: { ar: 'عينة من ملفك → قايمة مشاكل وكود pandas ينضّفها.', en: 'A sample of your file → a list of problems and pandas code that fixes them.' },
      vars: { sample: { ar: 'أول 20 سطر', en: 'The first 20 rows' } },
      code: 'Here are the first rows of a CSV:\n<sample>\n{{sample}}\n</sample>\n\n1. List every data quality problem you see (types, formats, duplicates, empty values, inconsistent spelling, Arabic/English digits).\n2. Write pandas code that fixes each problem, one step per comment.\n3. Add checks (asserts) that prove the cleaned data is right.\n4. Say what cannot be fixed without asking the owner.' },
    { id: 'data-chart-pick', cat: 'data', lvl: 'b', t: { ar: 'أنهي رسم بياني أنسب؟', en: 'Which chart fits best?' },
      body: { ar: 'الرسم الصح للرسالة الصح، وكود matplotlib أو Chart.js.', en: 'The right chart for the right message, with matplotlib or Chart.js code.' },
      vars: { message: { ar: 'عايز الرسم يقول إيه', en: 'What the chart should say' }, data: { ar: 'البيانات', en: 'The data' }, tool: { ar: 'الأداة', en: 'The tool' } },
      code: 'I want a chart that shows: {{message}}\nData:\n<data>\n{{data}}\n</data>\n\nRecommend the best chart type and explain why in 2 sentences, list 2 types to avoid and why, then write {{tool}} code with a clear title that states the conclusion, labelled axes, and no unnecessary decoration.' },
    { id: 'data-api-to-table', cat: 'data', lvl: 'i', t: { ar: 'رد API → جدول', en: 'An API response → a table' },
      body: { ar: 'JSON متداخل محتاج يتحوّل لصفوف في شيت أو قاعدة بيانات.', en: 'Nested JSON that must become rows in a sheet or database.' },
      vars: { json: { ar: 'عينة من الرد', en: 'A sample response' }, tool: { ar: 'هتعمله في إيه (n8n، Python، JS)', en: 'Where (n8n, Python, JS)' } },
      code: 'Turn this API response into flat table rows using {{tool}}:\n<json>\n{{json}}\n</json>\n\nPropose the columns (with types), decide what one row represents, handle nested arrays (one row per item or joined text — explain the choice), missing fields and dates. Give the code and the expected rows for the sample.' },
    { id: 'data-privacy-check', cat: 'data', lvl: 'i', t: { ar: 'مراجعة خصوصية البيانات', en: 'A data privacy review' },
      body: { ar: 'قبل ما تبعت بيانات عملاء لـ AI أو خدمة: إيه الحساس وإزاي تخفيه.', en: 'Before sending customer data to an AI or service: what is sensitive and how to hide it.' },
      vars: { flow: { ar: 'البيانات بتمشي إزاي', en: 'How the data flows' } },
      code: 'Review the privacy of this data flow:\n<flow>\n{{flow}}\n</flow>\n\nList: personal data fields involved, where each one goes (including AI providers and logs), what is not needed and can be dropped, what to mask or replace with an ID, retention (how long to keep), who has access, and what to tell customers. Give a short checklist I can repeat for every new workflow.' },
    // ---------------- thinking and research ----------------
    { id: 'think-compare-tools', cat: 'think', lvl: 'b', t: { ar: 'قارن بين أداتين', en: 'Compare two tools' },
      body: { ar: 'n8n ولا Make؟ Python ولا JS؟ مقارنة على أساس احتياجك انت.', en: 'n8n or Make? Python or JS? A comparison based on your needs.' },
      vars: { options: { ar: 'الاختيارات', en: 'The options' }, needs: { ar: 'احتياجاتك', en: 'Your needs' } },
      code: 'Compare {{options}} for my needs:\n<needs>\n{{needs}}\n</needs>\n\nMake a table with criteria that matter for MY needs (cost at my volume, learning curve, hosting, limits, community, lock-in). Then give a recommendation, the main risk of that choice, and what would make me choose differently. Say clearly where your information may be out of date and what to verify on the official site.' },
    { id: 'think-first-principles', cat: 'think', lvl: 'i', t: { ar: 'فكّر من الأساس', en: 'Think from first principles' },
      body: { ar: 'تفكّك المشكلة لأجزائها الأساسية قبل ما تختار حل.', en: 'Break the problem into its basic parts before you choose a solution.' },
      vars: { problem: { ar: 'المشكلة', en: 'The problem' } },
      code: 'Help me think about this problem from first principles: {{problem}}\n1. What is the real goal behind it?\n2. What facts are certainly true? What am I only assuming?\n3. What are the smallest parts of the problem?\n4. Three very different ways to solve it, including "do nothing" and "do it manually".\n5. The simplest test I can run this week to learn which way is right.\nAsk me questions where my description is vague.' },
    { id: 'think-devils-advocate', cat: 'think', lvl: 'i', t: { ar: 'انقد فكرتي', en: 'Criticise my idea' },
      body: { ar: 'اطلب من الـ AI يدوّر على الثغرات بدل ما يوافقك.', en: 'Ask the AI to look for holes instead of agreeing with you.' },
      vars: { idea: { ar: 'الفكرة أو الخطة', en: 'The idea or plan' } },
      code: 'Act as a sharp but fair critic. Here is my plan:\n<plan>\n{{idea}}\n</plan>\n\nGive the 5 strongest reasons it could fail, ordered by likelihood × impact. For each: the warning sign to watch for and a cheap way to reduce the risk. Do not soften your points, and do not invent facts about my situation — ask if you need them.' },
    { id: 'think-decision', cat: 'think', lvl: 'b', t: { ar: 'ساعدني آخد قرار', en: 'Help me make a decision' },
      body: { ar: 'جدول قرار بالمعايير والأوزان، وبعدين سؤال «هتندم على إيه؟».', en: 'A decision table with criteria and weights, then «what would you regret?».' },
      vars: { options: { ar: 'الاختيارات', en: 'The options' }, context: { ar: 'ظروفك', en: 'Your situation' } },
      code: 'Help me decide between: {{options}}\nMy situation: {{context}}\n\n1. Ask me up to 5 questions first, one at a time.\n2. Then build a weighted decision table (criteria I care about, weights that add to 100, a 1–5 score per option).\n3. Show the result, then test it: which choice would I regret most in a year, and is the decision reversible?' },
    { id: 'think-research-plan', cat: 'think', lvl: 'i', t: { ar: 'خطة بحث في موضوع جديد', en: 'A research plan for a new topic' },
      body: { ar: 'تتعلم موضوع جديد بسرعة: الأسئلة الصح والمصادر الرسمية.', en: 'Learn a new topic quickly: the right questions and official sources.' },
      vars: { topic: { ar: 'الموضوع', en: 'The topic' }, why: { ar: 'محتاجه ليه', en: 'Why you need it' } },
      code: 'I need to understand {{topic}} because {{why}}.\nGive me: the 10 key questions to answer, the core vocabulary (15 terms with one-line definitions), the kinds of official or primary sources to read (docs, specs, standards) and what to look for in each, a 5-day reading plan, and a way to test myself at the end. Do not make up URLs; describe where to look.' },
    { id: 'think-summarise-paper', cat: 'think', lvl: 'i', t: { ar: 'لخّص مقال أو ورقة تقنية', en: 'Summarise an article or technical paper' },
      body: { ar: 'الفكرة والدليل والحدود، وإزاي تستفيد منها في شغلك.', en: 'The idea, the evidence and the limits, and how to use it in your work.' },
      vars: { text: { ar: 'النص', en: 'The text' } },
      code: 'Summarise this text for a practitioner:\n<text>\n{{text}}\n</text>\n\nGive: the main claim in one sentence, the method or evidence, the 3 most important findings, the limitations (what it does NOT show), and 3 practical ways I could use it. Quote short phrases from the text to support each point, and say "not in the text" when something is missing.' },
    { id: 'think-fact-check', cat: 'think', lvl: 'b', t: { ar: 'راجع المعلومة دي', en: 'Check this claim' },
      body: { ar: 'قبل ما تصدّق أو تنشر: إيه اللي محتاج دليل وتدوّر فين.', en: 'Before you believe or share it: what needs evidence and where to look.' },
      vars: { text: { ar: 'المعلومة', en: 'The claim' } },
      code: 'Help me check this claim before I share it:\n<claim>\n{{text}}\n</claim>\n\nSplit it into separate factual statements. For each: is it checkable, what kind of primary source would confirm it, what would make it misleading even if technically true, and how confident you are from your own knowledge (and why that may be out of date). Do not present guesses as facts.' },
    { id: 'think-explain-levels', cat: 'think', lvl: 'b', t: { ar: 'اشرحها على 3 مستويات', en: 'Explain it at 3 levels' },
      body: { ar: 'نفس الفكرة لمبتدئ ولمتوسط ولخبير — تعرف انت فاهم لحد فين.', en: 'The same idea for a beginner, an intermediate and an expert — see how far you understand.' },
      vars: { topic: { ar: 'الفكرة', en: 'The idea' } },
      code: 'Explain {{topic}} three times:\n1. For a complete beginner (no jargon, one everyday analogy).\n2. For an intermediate developer (correct terms, a small code or diagram example).\n3. For an expert (trade-offs, edge cases, when it breaks).\nThen ask me 3 questions, one per level, to check which level I really understand.' },
    // ---------------- studying (more) ----------------
    { id: 'learn-week-review', cat: 'learn', lvl: 'b', t: { ar: 'مراجعة الأسبوع', en: 'A weekly review' },
      body: { ar: 'آخر الأسبوع: إيه اللي اتعلمته، وإيه اللي لسه مهزوز، وخطة الأسبوع الجاي.', en: 'End of the week: what you learnt, what is still shaky and next week’s plan.' },
      vars: { notes: { ar: 'اللي ذاكرته الأسبوع ده', en: 'What you studied this week' } },
      code: 'Here is what I studied this week:\n<notes>\n{{notes}}\n</notes>\n\nQuiz me with 10 questions mixing all topics (one at a time; include 2 "write a small piece of code" tasks). After I finish: list what I know well, what is shaky, 3 things to review on the first day of next week, and one small project idea that uses this week’s skills.' },
    { id: 'learn-spaced-plan', cat: 'learn', lvl: 'b', t: { ar: 'جدول مراجعة متباعدة', en: 'A spaced repetition schedule' },
      body: { ar: 'إمتى تراجع كل موضوع عشان ميتنسيش (يوم، 3 أيام، أسبوع، شهر).', en: 'When to review each topic so it sticks (1 day, 3 days, 1 week, 1 month).' },
      vars: { topics: { ar: 'المواضيع وتاريخ كل واحد', en: 'Topics and when you learnt each' } },
      code: 'Build a spaced repetition schedule for these topics:\n<topics>\n{{topics}}\n</topics>\n\nUse review gaps of 1, 3, 7, 14 and 30 days. Return a table by date with what to review and a 10-minute review activity for each (recall questions, rewrite code from memory, explain aloud). Keep each day under 30 minutes of review.' },
    { id: 'learn-project-steps', cat: 'learn', lvl: 'i', t: { ar: 'قسّم مشروع لخطوات صغيرة', en: 'Break a project into small steps' },
      body: { ar: 'مشروع كبير بيخوّف؟ خطوات كل واحدة ساعة وبتشتغل لوحدها.', en: 'A big project feels scary? Steps of an hour each that work on their own.' },
      vars: { project: { ar: 'المشروع', en: 'The project' }, level: { ar: 'مستواك', en: 'Your level' } },
      code: 'Break this project into small milestones for a {{level}} learner: {{project}}\nEach milestone: takes about 1 hour, ends with something I can run and see, and lists the one new concept it needs. Start with the simplest version that works end to end, then add features. Do not write the code for me — give a hint per step that I can open only if stuck.' },
    { id: 'learn-hint-ladder', cat: 'learn', lvl: 'b', t: { ar: 'تلميحات بدل الحل', en: 'Hints instead of the answer' },
      body: { ar: 'عشان تتعلم فعلًا: الـ AI يديك تلميح ورا تلميح، مش الحل.', en: 'To really learn: the AI gives you hint after hint, not the solution.' },
      vars: { task: { ar: 'التمرين', en: 'The exercise' }, code: { ar: 'محاولتك', en: 'Your attempt' } },
      code: 'I am stuck on this exercise:\n<task>\n{{task}}\n</task>\nMy attempt:\n<code>\n{{code}}\n</code>\n\nDo NOT give me the solution. Give me hint 1 only (the smallest nudge). When I say "next", give a stronger hint, up to 4 hints. Only show the solution if I type "solution", and then explain it line by line.' },
    { id: 'learn-mistake-log', cat: 'learn', lvl: 'b', t: { ar: 'سجل أخطائي', en: 'My mistakes log' },
      body: { ar: 'تجمع أخطاءك المتكررة وتعرف النمط اللي وراها.', en: 'Collect your repeated mistakes and find the pattern behind them.' },
      vars: { notes: { ar: 'أخطاء الفترة اللي فاتت', en: 'Recent mistakes' } },
      code: 'Here are mistakes I made recently (code errors, quiz answers, English mistakes):\n<notes>\n{{notes}}\n</notes>\n\nGroup them by root cause (not by topic), say which group costs me most, and for each group give: one rule to remember, a 5-minute drill, and a check I can add to my routine so I catch it earlier.' },
    { id: 'learn-teach-back', cat: 'learn', lvl: 'i', t: { ar: 'علّم الـ AI اللي اتعلمته', en: 'Teach the AI what you learnt' },
      body: { ar: 'الـ AI يمثّل إنه طالب، وانت تشرح؛ أسئلته بتكشف الفجوات.', en: 'The AI plays a student and you explain; its questions reveal the gaps.' },
      vars: { topic: { ar: 'الموضوع', en: 'The topic' } },
      code: 'Pretend you are a curious beginner student. I will teach you {{topic}}.\nAfter each of my explanations, ask one honest question a beginner would ask — including "why?" and "what if…?" questions. If I say something wrong or unclear, act confused about exactly that part. After 8 turns, step out of the role and tell me which parts I explained well and which I should study again.' },
    // ---------------- career ----------------
    { id: 'career-roadmap', cat: 'career', lvl: 'b', t: { ar: 'خريطة طريق لوظيفة', en: 'A roadmap to a job' },
      body: { ar: 'من مستواك الحالي لوظيفة محددة، بمهارات ومشاريع ووقت.', en: 'From your current level to a specific job, with skills, projects and time.' },
      vars: { role: { ar: 'الوظيفة', en: 'The role' }, now: { ar: 'مستواك الحالي', en: 'Where you are now' }, hours: { ar: 'ساعات أسبوعيًا', en: 'Hours per week' } },
      code: 'I want to become a {{role}}. Where I am now: {{now}}. I can study {{hours}} hours a week.\nGive: the core skills in priority order, 4 portfolio projects that prove them, a month-by-month plan, the signs I am ready to apply, and the 3 most common mistakes people make on this path. Be realistic about time.' },
    { id: 'career-job-match', cat: 'career', lvl: 'b', t: { ar: 'أنا مناسب للوظيفة دي؟', en: 'Do I fit this job?' },
      body: { ar: 'قارن إعلان الوظيفة بخبرتك: نقط القوة والفجوات وإزاي تقدّم.', en: 'Compare the job ad with your experience: strengths, gaps and how to apply.' },
      vars: { text: { ar: 'إعلان الوظيفة', en: 'The job ad' }, notes: { ar: 'خبرتك', en: 'Your experience' } },
      code: 'Job ad:\n<job>\n{{text}}\n</job>\nMy experience:\n<me>\n{{notes}}\n</me>\n\nGive: a match score with reasons, requirements I clearly meet (with evidence from my experience), gaps and whether each is a must-have, how to address each gap honestly in my application, and the 3 points my cover letter must make.' },
    { id: 'career-cover-letter', cat: 'career', lvl: 'b', t: { ar: 'خطاب تقديم (cover letter)', en: 'A cover letter' },
      body: { ar: 'خطاب قصير مخصص للشركة، بأمثلة من شغلك.', en: 'A short letter tailored to the company, with examples from your work.' },
      vars: { text: { ar: 'إعلان الوظيفة', en: 'The job ad' }, notes: { ar: 'أهم إنجازاتك', en: 'Your best achievements' } },
      code: 'Write a cover letter for this job:\n<job>\n{{text}}\n</job>\nMy achievements:\n<me>\n{{notes}}\n</me>\n\nUnder 250 words. Open with why this company and role specifically, then 2 short stories that prove I can do the main requirements, then a confident close. Plain, human English; no clichés like "I am writing to apply". Do not invent experience.' },
    { id: 'career-interview-tech', cat: 'career', lvl: 'i', t: { ar: 'مقابلة تقنية تجريبية', en: 'A practice technical interview' },
      body: { ar: 'أسئلة Python/JS/n8n حقيقية، وتقييم لإجاباتك.', en: 'Real Python/JS/n8n questions, and feedback on your answers.' },
      vars: { role: { ar: 'الوظيفة', en: 'The role' }, stack: { ar: 'التقنيات', en: 'The tech stack' } },
      code: 'Run a technical interview for a {{role}} role using {{stack}}.\nAsk one question at a time: 2 concept questions, 1 small coding task, 1 debugging task (show me broken code), 1 system design question about an automation, and 1 question about a past project. Wait for my answer each time. At the end, score each answer 1–5 with what a strong answer would include.' },
    { id: 'career-star-stories', cat: 'career', lvl: 'b', t: { ar: 'قصص STAR للمقابلات', en: 'STAR stories for interviews' },
      body: { ar: 'تجهّز قصص من شغلك (موقف، مهمة، تصرف، نتيجة) قبل المقابلة.', en: 'Prepare stories from your work (situation, task, action, result) before the interview.' },
      vars: { notes: { ar: 'مواقف من شغلك', en: 'Situations from your work' } },
      code: 'Turn these experiences into interview stories using STAR (Situation, Task, Action, Result):\n<notes>\n{{notes}}\n</notes>\n\nEach story under 150 words in English, focused on what I did, with a number in the result where possible ([X] if missing). Then map each story to the common questions it can answer (a conflict, a failure, a tight deadline, learning fast, a technical challenge).' },
    { id: 'career-salary', cat: 'career', lvl: 'a', t: { ar: 'التفاوض على المرتب', en: 'Negotiating salary' },
      body: { ar: 'تحضير للكلام عن المرتب: الرقم، الحجة، والرد على «ده أقصى حاجة».', en: 'Preparing to talk about salary: the number, the case and answering «that’s our max».' },
      vars: { offer: { ar: 'العرض', en: 'The offer' }, value: { ar: 'اللي بتقدّمه', en: 'What you bring' } },
      code: 'I received this offer: {{offer}}. What I bring: {{value}}.\nHelp me prepare: how to research a fair range (what sources to check), my target and walk-away numbers, a short script to ask for more, answers to "this is our maximum" and "what are you earning now?", and non-salary items I can negotiate. Then role-play the recruiter for 4 turns.' },
    { id: 'career-github-profile', cat: 'career', lvl: 'b', t: { ar: 'بروفايل GitHub يقنع', en: 'A convincing GitHub profile' },
      body: { ar: 'README للبروفايل ولكل مشروع، بحيث صاحب الشغل يفهمك في دقيقة.', en: 'A profile README and one per project, so an employer understands you in a minute.' },
      vars: { notes: { ar: 'مشاريعك ومهاراتك', en: 'Your projects and skills' } },
      code: 'Help me improve my GitHub profile. My projects and skills:\n<notes>\n{{notes}}\n</notes>\n\nGive: a short profile README (who I am, what I build, 3 pinned projects with one line each), a README template for each project (problem, demo screenshot/GIF, how to run, what I learnt), which repos to pin and why, and 5 small cleanups that make repos look professional.' }
  ]
});
