// More prompts for the library on prompts.html: learning English and professional writing.
// Added with SECTIONS.extend; written for this site.
SECTIONS.extend('prompts', 'library', {
  cats: [
    { id: 'write', t: { ar: 'الكتابة المهنية', en: 'Professional writing' } }
  ],
  items: [
    // ---------------- learning English (more) ----------------
    { id: 'en-level-test', cat: 'english', lvl: 'b', t: { ar: 'حدد مستوايا في الإنجليزي', en: 'Find my English level' },
      body: { ar: 'اختبار قصير بيتغيّر حسب إجاباتك ويقولك مستواك وتشتغل على إيه.', en: 'A short adaptive test that tells you your level and what to work on.' },
      vars: { field: { ar: 'مجال شغلك', en: 'Your field' } },
      code: 'Give me a short adaptive English placement test (CEFR A1–C1) for someone who works in {{field}}.\nAsk ONE question at a time and wait for my answer. Mix: grammar, vocabulary from my field, reading a short technical text, and writing one sentence. Get harder after correct answers and easier after mistakes.\nAfter 12 questions, give my estimated level, 3 strengths, 3 weaknesses, and a 4-week plan.' },
    { id: 'en-daily-words', cat: 'english', lvl: 'b', t: { ar: '10 كلمات شغل كل يوم', en: '10 work words a day' },
      body: { ar: 'كلمات من مجالك بالمعنى والنطق وجملة من الشغل، وبعدين اختبار.', en: 'Words from your field with meaning, pronunciation and a work sentence, then a quiz.' },
      vars: { field: { ar: 'المجال', en: 'The field' }, level: { ar: 'مستواك', en: 'Your level' } },
      code: 'Teach me 10 English words I will really use in {{field}} at level {{level}}.\nFor each: the word, part of speech, simple meaning in English, Arabic meaning, pronunciation hint (stress in CAPITALS), a realistic work sentence, and a common collocation.\nThen quiz me: 10 gap-fill sentences, one at a time, and correct my answers.' },
    { id: 'en-pronounce', cat: 'english', lvl: 'b', t: { ar: 'النطق الصح لكلمات تقنية', en: 'Pronouncing technical words correctly' },
      body: { ar: 'كلمات زي cache وqueue وdeploy وAPI: النطق والنبر والغلطة الشائعة عند العرب.', en: 'Words like cache, queue, deploy and API: pronunciation, stress and the usual mistake for Arabic speakers.' },
      vars: { words: { ar: 'الكلمات', en: 'The words' } },
      code: 'For each of these technical words: {{words}}\ngive: the IPA, a simple respelling (like "KASH"), the stressed syllable, the common mistake Arabic speakers make, and a short sentence to practise. Group words that people often confuse.' },
    { id: 'en-phrasal-verbs', cat: 'english', lvl: 'i', t: { ar: 'Phrasal verbs بتاعة الشغل', en: 'Phrasal verbs at work' },
      body: { ar: 'set up وroll back وfollow up وsign off: معناها في سياق الشغل التقني.', en: 'set up, roll back, follow up, sign off: their meaning in technical work.' },
      vars: { level: { ar: 'مستواك', en: 'Your level' } },
      code: 'Teach me 12 phrasal verbs used in software and automation work, at {{level}} level.\nFor each: meaning, an example from a real work situation (Slack, a meeting, a ticket), whether it is separable, and a similar formal verb (e.g. set up → configure).\nThen give me 6 sentences to complete with the right phrasal verb, one at a time.' },
    { id: 'en-listening', cat: 'english', lvl: 'i', t: { ar: 'فهم فيديو تقني', en: 'Understanding a technical video' },
      body: { ar: 'الصق نص فيديو (transcript) واطلب كلمات وأسئلة فهم.', en: 'Paste a video transcript and ask for vocabulary and comprehension questions.' },
      vars: { text: { ar: 'النص (transcript)', en: 'The transcript' } },
      code: 'Here is the transcript of a technical video I watched:\n<transcript>\n{{text}}\n</transcript>\n\n1. Summarise it in 5 simple English sentences.\n2. List 10 useful words or phrases from it with meanings.\n3. Ask me 5 comprehension questions, one at a time, and check my answers.\n4. Pick 3 sentences for shadowing practice and mark the stress and linking.' },
    { id: 'en-speaking-partner', cat: 'english', lvl: 'i', t: { ar: 'شريك كلام بالإنجليزي', en: 'An English speaking partner' },
      body: { ar: 'محادثة يومية عن شغلك، والتصحيح في الآخر بس عشان متتقطعش.', en: 'A daily conversation about your work, with corrections only at the end so you keep going.' },
      vars: { topic: { ar: 'الموضوع', en: 'The topic' }, level: { ar: 'مستواك', en: 'Your level' } },
      code: 'Be my English conversation partner. Topic: {{topic}}. My level: {{level}}.\nAsk me one question at a time, keep your turns short (2–3 sentences), and react naturally to what I say. Do not correct me during the chat.\nWhen I type "feedback", give: my 5 most important mistakes with corrections, 5 better phrases I could have used, and one thing I did well.' },
    { id: 'en-tenses-work', cat: 'english', lvl: 'b', t: { ar: 'الأزمنة في مواقف الشغل', en: 'Tenses in work situations' },
      body: { ar: 'تقرير stand-up: عملت إيه (ماضي)، بعمل إيه (مستمر)، هعمل إيه (مستقبل)، وخلّصت إيه (present perfect).', en: 'A stand-up report: what you did (past), are doing (continuous), will do (future) and have finished (present perfect).' },
      vars: { notes: { ar: 'ملاحظاتك بالعربي عن شغلك', en: 'Your notes on your work, in Arabic' } },
      code: 'Here are my notes about my work this week, in Arabic:\n<notes>\n{{notes}}\n</notes>\n\nWrite them as a short stand-up update in natural English. Then explain why each tense was used (past simple, present perfect, present continuous, future with will/going to) with the rule in one line. Finally give me 5 similar sentences to translate myself.' },
    { id: 'en-mistakes-arabic', cat: 'english', lvl: 'b', t: { ar: 'أخطاء العرب الشائعة', en: 'Common mistakes of Arabic speakers' },
      body: { ar: 'الأخطاء اللي بتيجي من الترجمة الحرفية من العربي، في نصك انت.', en: 'Mistakes caused by translating literally from Arabic — in your own text.' },
      vars: { text: { ar: 'نص كتبته بالإنجليزي', en: 'A text you wrote in English' } },
      code: 'I am an Arabic speaker. Find mistakes in my English that come from Arabic (articles a/the, verb "to be", word order, prepositions, plural forms, false friends, literal translations):\n<text>\n{{text}}\n</text>\n\nFor each: my phrase → correct phrase → why (one line, mention the Arabic pattern behind it). Then give the full corrected text.' },
    { id: 'en-read-error', cat: 'english', lvl: 'b', t: { ar: 'افهم رسالة خطأ بالإنجليزي', en: 'Understand an English error message' },
      body: { ar: 'تمرين لغة وبرمجة مع بعض: الكلمات والقواعد في رسالة الخطأ.', en: 'Language and programming practice at once: the words and grammar in an error message.' },
      vars: { text: { ar: 'رسالة الخطأ', en: 'The error message' } },
      code: 'Help me read this error message as an English learner:\n<error>\n{{text}}\n</error>\n\n1. Translate it to simple Arabic.\n2. Explain each technical word.\n3. Explain the grammar (e.g. passive voice, "cannot be", "is not defined").\n4. Give 3 similar error messages I may meet and their meanings.' },
    { id: 'en-vocab-from-doc', cat: 'english', lvl: 'i', t: { ar: 'كلمات من توثيق بتقراه', en: 'Words from documentation you are reading' },
      body: { ar: 'خد صفحة توثيق وطلّع منها بطاقات مراجعة بالكلمات المهمة.', en: 'Take a documentation page and turn its key words into review cards.' },
      vars: { text: { ar: 'جزء من التوثيق', en: 'A part of the docs' } },
      code: 'From this documentation text, pick the 15 words or phrases most useful for a developer learning English:\n<docs>\n{{text}}\n</docs>\n\nFor each make a flashcard: front = the word in a sentence from the text, back = simple English meaning + Arabic meaning + one new example. Return as a table with columns Front | Back, ready to paste into a spreadsheet.' },
    { id: 'en-writing-coach', cat: 'english', lvl: 'i', t: { ar: 'مدرب كتابة لفقرة', en: 'A writing coach for a paragraph' },
      body: { ar: 'مش بس تصحيح: إزاي الفقرة تبقى أوضح وأقوى، وانت بتتعلم.', en: 'Not just correction: how the paragraph becomes clearer and stronger, while you learn.' },
      vars: { text: { ar: 'الفقرة', en: 'The paragraph' }, purpose: { ar: 'الغرض والجمهور', en: 'Purpose and audience' } },
      code: 'Coach me on this paragraph (purpose and reader: {{purpose}}):\n<text>\n{{text}}\n</text>\n\nDo not rewrite it all at once. First: 3 questions that would make my point clearer. Then: grammar fixes, then word choice, then structure — each as a short list with reasons. Finally show your improved version and highlight the 3 changes that matter most.' },
    { id: 'en-meeting-prep', cat: 'english', lvl: 'i', t: { ar: 'تحضير اجتماع بالإنجليزي', en: 'Preparing for a meeting in English' },
      body: { ar: 'الجمل اللي هتحتاجها: تعرض رأيك، تختلف بأدب، تطلب توضيح، تلخّص.', en: 'The sentences you will need: giving your view, disagreeing politely, asking for clarification, summarising.' },
      vars: { meeting: { ar: 'الاجتماع عن إيه', en: 'What the meeting is about' }, points: { ar: 'نقطك', en: 'Your points' } },
      code: 'I have a meeting in English about {{meeting}}. My points: {{points}}.\nPrepare me:\n1. How to say each of my points clearly (2 versions: simple and more formal).\n2. 10 useful phrases: interrupting politely, disagreeing, asking for clarification, buying time, summarising, agreeing on next steps.\n3. 5 questions others may ask me and short model answers.\nThen role-play the meeting with me, one turn at a time.' },
    { id: 'en-presentation', cat: 'english', lvl: 'i', t: { ar: 'عرض تقديمي بالإنجليزي', en: 'A presentation in English' },
      body: { ar: 'سكربت عرض لمشروعك بجمل بسيطة ونطق وانتقالات بين الأجزاء.', en: 'A presentation script for your project with simple sentences, pronunciation help and transitions.' },
      vars: { project: { ar: 'المشروع', en: 'The project' }, minutes: { ar: 'المدة بالدقايق', en: 'Length in minutes' } },
      code: 'Write a {{minutes}}-minute presentation script about my project: {{project}}.\nStructure: hook, problem, solution (demo steps), results with numbers, next steps, thank-you.\nUse short sentences I can say comfortably, mark pauses with "/", and stress on key words in CAPITALS. Add signposting phrases between parts. Then list 5 likely questions with short answers.' },
    { id: 'en-negotiation', cat: 'english', lvl: 'a', t: { ar: 'تفاوض على سعر بالإنجليزي', en: 'Negotiating a price in English' },
      body: { ar: 'عميل أجنبي عايز خصم؛ ترد بأدب وتحافظ على قيمة شغلك.', en: 'A foreign client wants a discount; reply politely while keeping the value of your work.' },
      vars: { situation: { ar: 'الموقف', en: 'The situation' }, limits: { ar: 'حدودك (أقل سعر، اللي ممكن تتنازل عنه)', en: 'Your limits (lowest price, what you can trade)' } },
      code: 'Situation: {{situation}}\nMy limits: {{limits}}\n\n1. Write my reply in polite, confident English (max 120 words) that protects my price by trading scope or terms instead of dropping it.\n2. Give 8 useful negotiation phrases with when to use each.\n3. Role-play the client with me for 4 turns, then give me feedback on my English and my negotiating.' },
    // ---------------- professional writing ----------------
    { id: 'write-email-client', cat: 'write', lvl: 'b', t: { ar: 'إيميل لعميل', en: 'An email to a client' },
      body: { ar: 'إيميل واضح ومهذب بموضوع مناسب، بالعربي أو الإنجليزي.', en: 'A clear, polite email with a fitting subject line, in Arabic or English.' },
      vars: { goal: { ar: 'هدف الإيميل', en: 'The email’s goal' }, facts: { ar: 'المعلومات اللي لازم تتقال', en: 'The facts to include' }, lang: { ar: 'اللغة', en: 'Language' } },
      code: 'Write a client email in {{lang}}.\nGoal: {{goal}}\nFacts to include:\n<facts>\n{{facts}}\n</facts>\n\n- A clear subject line.\n- First line says why I am writing; one idea per short paragraph.\n- A specific request or next step with a date.\n- Warm but professional; under 150 words.\nGive 2 versions: friendly and more formal.' },
    { id: 'write-status-update', cat: 'write', lvl: 'b', t: { ar: 'تحديث حالة مشروع', en: 'A project status update' },
      body: { ar: 'العميل بيسأل «وصلنا لفين؟»: تحديث مرتب فيه اللي خلص واللي جاي والمخاطر.', en: 'The client asks «where are we?»: a tidy update with what is done, what is next and the risks.' },
      vars: { notes: { ar: 'ملاحظاتك', en: 'Your notes' } },
      code: 'Turn my notes into a short project status update for the client:\n<notes>\n{{notes}}\n</notes>\n\nFormat: status in one word (on track / at risk / blocked) + one sentence why; Done this week; Next week; Risks and what I need from the client (with dates). Plain language, no jargon, under 180 words.' },
    { id: 'write-sop', cat: 'write', lvl: 'i', t: { ar: 'دليل خطوات (SOP) لعملية', en: 'A step-by-step guide (SOP) for a process' },
      body: { ar: 'تكتب العملية بحيث أي موظف جديد يعملها لوحده — وده أول خطوة قبل أتمتتها.', en: 'Write the process so any new employee can do it alone — the first step before automating it.' },
      vars: { process: { ar: 'العملية', en: 'The process' }, notes: { ar: 'إزاي بتتعمل دلوقتي', en: 'How it is done now' } },
      code: 'Write a standard operating procedure for: {{process}}\nHow it is done today:\n<notes>\n{{notes}}\n</notes>\n\nInclude: purpose, who does it and when, tools and access needed, numbered steps (one action each), checks and what "done" looks like, common problems and fixes. Then mark which steps could be automated and how.' },
    { id: 'write-release-notes', cat: 'write', lvl: 'b', t: { ar: 'ملاحظات إصدار جديد', en: 'Release notes' },
      body: { ar: 'من قايمة commits أو تذاكر لملاحظات المستخدم يفهمها.', en: 'From a list of commits or tickets to notes users understand.' },
      vars: { text: { ar: 'التغييرات', en: 'The changes' }, audience: { ar: 'مين القارئ', en: 'Who reads it' } },
      code: 'Write release notes for {{audience}} from these changes:\n<changes>\n{{text}}\n</changes>\n\nGroup into New, Improved and Fixed. Describe each change by its benefit to the user in one sentence, not by the code change. Leave out internal-only changes. Add "What you need to do" if any action is required.' },
    { id: 'write-proposal-sections', cat: 'write', lvl: 'i', t: { ar: 'أجزاء عرض فني', en: 'Sections of a technical proposal' },
      body: { ar: 'نطاق الشغل والمخرجات والجدول والافتراضات اللي بتحميك.', en: 'Scope, deliverables, timeline and the assumptions that protect you.' },
      vars: { project: { ar: 'المشروع', en: 'The project' }, budget: { ar: 'الميزانية التقريبية', en: 'Rough budget' } },
      code: 'Draft the scope section of a proposal for: {{project}} (budget around {{budget}}).\nInclude: objectives, in scope, out of scope (be explicit), deliverables with acceptance criteria, timeline in phases, assumptions and what the client must provide, change-request process, and support after delivery. Clear, plain language a non-technical owner can sign.' },
    { id: 'write-postmortem', cat: 'write', lvl: 'a', t: { ar: 'تقرير بعد عطل (postmortem)', en: 'A report after an outage (postmortem)' },
      body: { ar: 'من غير لوم: إيه حصل، وأثره، وليه، وإزاي ميتكررش.', en: 'Blameless: what happened, its impact, why, and how it will not happen again.' },
      vars: { notes: { ar: 'ملاحظات العطل والجدول الزمني', en: 'Incident notes and timeline' } },
      code: 'Write a blameless postmortem from these notes:\n<notes>\n{{notes}}\n</notes>\n\nSections: summary (3 sentences), impact (who, how long, numbers), timeline (times in Africa/Cairo), root cause and contributing factors (5 whys), what went well, what went badly, action items (owner and date each). Do not invent details missing from the notes; mark them as "to confirm".' },
    { id: 'write-linkedin', cat: 'write', lvl: 'b', t: { ar: 'بوست لينكدإن عن مشروع', en: 'A LinkedIn post about a project' },
      body: { ar: 'تحكي مشروع عملته بأرقام ونتيجة، من غير مبالغة.', en: 'Tell the story of a project you built, with numbers and results, without exaggeration.' },
      vars: { project: { ar: 'المشروع والنتيجة', en: 'The project and its result' }, lang: { ar: 'اللغة', en: 'Language' } },
      code: 'Write a LinkedIn post in {{lang}} about this project: {{project}}.\nStructure: a one-line hook with the result, the problem, what I built (tools in one line), the measurable result, one lesson learned, a soft call to action. Short lines, no buzzwords, no emojis beyond 2, at most 3 hashtags. Keep every claim true to what I wrote.' },
    { id: 'write-cv-bullets', cat: 'write', lvl: 'b', t: { ar: 'نقط CV قوية', en: 'Strong CV bullet points' },
      body: { ar: 'من «عملت أتمتة» لـ «وفّرت 15 ساعة أسبوعيًا بأتمتة…».', en: 'From «did automation» to «saved 15 hours a week by automating…».' },
      vars: { notes: { ar: 'اللي عملته في شغلك', en: 'What you did at work' } },
      code: 'Turn these notes into 6 CV bullet points:\n<notes>\n{{notes}}\n</notes>\n\nEach bullet: action verb + what I built or did + tools + measurable result. If a number is missing, put [X] for me to fill — do not invent numbers. Give an English version and an Arabic version.' },
    { id: 'write-user-guide', cat: 'write', lvl: 'i', t: { ar: 'دليل استخدام لعميل', en: 'A user guide for a client' },
      body: { ar: 'العميل استلم الأتمتة: إزاي يستخدمها ويتصرف لو حاجة وقفت.', en: 'The client has received the automation: how to use it and what to do if something stops.' },
      vars: { system: { ar: 'النظام اللي سلّمته', en: 'The system you delivered' } },
      code: 'Write a short user guide for a non-technical client for this system: {{system}}.\nSections: what it does (3 bullets), daily use (numbered steps), what they will receive (emails/messages and what they mean), what to do if something looks wrong (checklist), who to contact and what to include in the message. Plain words, short sentences, Egyptian Arabic.' },
    { id: 'write-tone-fix', cat: 'write', lvl: 'b', t: { ar: 'غيّر نبرة رسالة', en: 'Change a message’s tone' },
      body: { ar: 'رسالة خرجت حادة أو ضعيفة: نفس المعنى بنبرة أحسن.', en: 'A message came out harsh or weak: the same meaning in a better tone.' },
      vars: { text: { ar: 'الرسالة', en: 'The message' }, tone: { ar: 'النبرة المطلوبة', en: 'The tone you want' } },
      code: 'Rewrite this message in a {{tone}} tone, keeping every fact and request the same:\n<text>\n{{text}}\n</text>\n\nGive the new version, then list the 3 changes that changed the tone most (word choice, softeners, structure).' },
    { id: 'write-ticket', cat: 'write', lvl: 'b', t: { ar: 'تذكرة bug واضحة', en: 'A clear bug ticket' },
      body: { ar: 'تذكرة المطوّر يقدر يشتغل عليها على طول: الخطوات والمتوقع والفعلي.', en: 'A ticket a developer can act on at once: steps, expected and actual.' },
      vars: { notes: { ar: 'اللي حصل', en: 'What happened' } },
      code: 'Turn this into a bug report:\n<notes>\n{{notes}}\n</notes>\n\nFormat: Title (short and specific), Environment, Steps to reproduce (numbered), Expected result, Actual result, Frequency, Impact, Attachments needed (screenshot, logs). Mark anything I did not provide as "unknown".' },
    { id: 'write-faq', cat: 'write', lvl: 'b', t: { ar: 'أسئلة شائعة من رسايل العملاء', en: 'An FAQ from customer messages' },
      body: { ar: 'تجمع أسئلة العملاء المتكررة في صفحة بإجابات واضحة — وتستخدمها كمان لمساعد AI.', en: 'Gather customers’ repeated questions into a page with clear answers — and reuse it for an AI assistant.' },
      vars: { messages: { ar: 'رسايل العملاء', en: 'Customer messages' }, facts: { ar: 'المعلومات الصح', en: 'The correct facts' } },
      code: 'From these customer messages, find the 10 most common questions:\n<messages>\n{{messages}}\n</messages>\n\nWrite an FAQ answering them using ONLY these facts:\n<facts>\n{{facts}}\n</facts>\n\nShort answers, Egyptian Arabic, grouped by topic. If a question cannot be answered from the facts, list it separately as "needs an answer from the owner".' },
    { id: 'write-shorten', cat: 'write', lvl: 'b', t: { ar: 'اختصر النص ده', en: 'Shorten this text' },
      body: { ar: 'نفس الرسالة في نص الطول من غير ما يضيع معنى.', en: 'The same message at half the length without losing meaning.' },
      vars: { text: { ar: 'النص', en: 'The text' }, words: { ar: 'أقصى عدد كلمات', en: 'Maximum words' } },
      code: 'Shorten this to at most {{words}} words without losing any fact, number, date or request:\n<text>\n{{text}}\n</text>\n\nCut repetition, filler and hedging first. Return the short version, then list anything you had to drop (if any).' }
  ]
});
