// More prompts for the library on prompts.html: coding, web and quality/security (SECTIONS.extend adds them to
// the «library» section in content/sections/prompts.js). Same card format; every prompt is written for this site.
SECTIONS.extend('prompts', 'library', {
  cats: [
    { id: 'web', t: { ar: 'الويب وجافاسكريبت', en: 'Web and JavaScript' } },
    { id: 'sec', t: { ar: 'الجودة والأمان', en: 'Quality and security' } }
  ],
  items: [
    // ---------------- coding (more) ----------------
    { id: 'py-script', cat: 'code', lvl: 'b', t: { ar: 'اكتبلي سكربت Python لمهمة', en: 'Write a Python script for a task' },
      body: { ar: 'لما عندك مهمة متكررة (ملفات، Excel، إيميل) وعايز سكربت نضيف تقدر تفهمه وتعدّله.', en: 'When you have a repeated task (files, Excel, email) and want a clean script you can understand and change.' },
      vars: { task: { ar: 'المهمة', en: 'The task' }, input: { ar: 'المدخلات وشكلها', en: 'The input and its shape' }, output: { ar: 'الناتج المطلوب', en: 'The output you want' } },
      code: 'Write a Python 3.12 script that does this task:\n{{task}}\n\nInput (with a small example):\n{{input}}\n\nExpected output:\n{{output}}\n\nRequirements:\n- Standard library first; name any third-party package and why it is needed.\n- Small functions with clear names, type hints and a main() guard.\n- Handle bad input with clear error messages (file not found, wrong columns, empty rows).\n- A --dry-run flag that prints what would happen without changing anything.\n- Log progress with the logging module, not print.\n\nAfter the code, explain how to run it and list 3 edge cases you handled.',
      tip: { ar: 'اديله مثال صغير حقيقي للمدخلات (من غير بيانات عملاء حقيقية)، الكود بيطلع أدق بكتير.', en: 'Give a small real example of the input (without real customer data); the code comes out far more accurate.' },
      bad: 'write a python script to process my excel', badWhy: { ar: 'مفيش شكل المدخلات ولا الناتج: هيخمّن الأعمدة.', en: 'No input shape or output: it will guess the columns.' } },
    { id: 'js-function', cat: 'code', lvl: 'b', t: { ar: 'دالة JavaScript بمواصفات', en: 'A JavaScript function to a spec' },
      body: { ar: 'تحدد اسم الدالة ومدخلاتها ومخرجاتها وحالاتها، وتاخد كود واختبارات مع بعض.', en: 'You set the function’s name, inputs, outputs and cases, and get the code plus tests together.' },
      vars: { name: { ar: 'اسم الدالة', en: 'Function name' }, spec: { ar: 'المطلوب بالتفصيل', en: 'What it must do' }, example: { ar: 'أمثلة مدخل ← مخرج', en: 'Input → output examples' } },
      code: 'Write a modern JavaScript (ES2022) function named {{name}}.\n\nWhat it must do:\n{{spec}}\n\nExamples (input → output):\n{{example}}\n\nRules:\n- Pure function: no global state, do not mutate the inputs.\n- Validate inputs and throw an Error with a clear message on bad input.\n- JSDoc comment with parameter and return types.\n- Then write 8 test cases with node:test and node:assert/strict, including empty, null and boundary inputs.',
      bad: 'write a js function for discounts', badWhy: { ar: 'من غير قواعد ولا أمثلة: هيخترع قواعد الخصم.', en: 'No rules or examples: it invents the discount rules.' } },
    { id: 'translate-code', cat: 'code', lvl: 'i', t: { ar: 'حوّل كود من لغة للغة', en: 'Translate code between languages' },
      body: { ar: 'من Python لـ JavaScript (عشان Code node) أو العكس، مع الحفاظ على السلوك بالظبط.', en: 'From Python to JavaScript (for a Code node) or back, keeping the behaviour exactly.' },
      vars: { from: { ar: 'من لغة', en: 'From language' }, to: { ar: 'للغة', en: 'To language' }, code: { ar: 'الكود', en: 'The code' } },
      code: 'Translate this {{from}} code to idiomatic {{to}}.\n\n<code>\n{{code}}\n</code>\n\n- Keep the behaviour identical, including edge cases (empty input, None/null, rounding, dates and time zones).\n- Use the target language’s usual style and standard library, not a word-for-word copy.\n- After the code, list every place where the two languages behave differently and how you handled it.',
      tip: { ar: 'اطلب منه يكتب نفس الاختبارات في اللغتين عشان تتأكد إن الاتنين بيدّوا نفس النتيجة.', en: 'Ask for the same tests in both languages so you can confirm they give the same results.' } },
    { id: 'explain-error-stack', cat: 'code', lvl: 'b', t: { ar: 'اقرالي الـ stack trace', en: 'Read this stack trace for me' },
      body: { ar: 'لما يطلعلك خطأ طويل ومش عارف تبدأ منين.', en: 'When you get a long error and do not know where to start.' },
      vars: { text: { ar: 'الخطأ كامل', en: 'The full error' }, context: { ar: 'كنت بتعمل إيه', en: 'What you were doing' } },
      code: 'I was {{context}} and got this error:\n\n<error>\n{{text}}\n</error>\n\n1. Which line is the real starting point in MY code (not a library)? Quote it.\n2. What does the error mean in plain words?\n3. What are the 3 most likely causes, and one quick check for each?\nDo not rewrite my whole program.' },
    { id: 'naming', cat: 'code', lvl: 'b', t: { ar: 'أسماء أحسن لمتغيرات ودوال', en: 'Better names for variables and functions' },
      body: { ar: 'الأسماء الواضحة نص جودة الكود. خليه يقترح أسماء ويشرح ليه.', en: 'Clear names are half of code quality. Let it suggest names and explain why.' },
      vars: { code: { ar: 'الكود', en: 'The code' } },
      code: 'Suggest clearer names for the variables, functions and parameters in this code.\n\n<code>\n{{code}}\n</code>\n\nFor each one: current name → suggested name → one short reason. Follow the language’s conventions (camelCase in JS, snake_case in Python). Do not change any logic. Then show the code with the new names.' },
    { id: 'big-o', cat: 'code', lvl: 'i', t: { ar: 'الكود ده بطيء ليه؟', en: 'Why is this code slow?' },
      body: { ar: 'لما سكربت بيخلص في ثانية على 100 صف وفي ساعة على 100 ألف.', en: 'When a script finishes in a second on 100 rows and an hour on 100,000.' },
      vars: { code: { ar: 'الكود', en: 'The code' }, size: { ar: 'حجم البيانات', en: 'Data size' } },
      code: 'This code is too slow with about {{size}} records.\n\n<code>\n{{code}}\n</code>\n\n1. Find the slow parts and give their time complexity (Big-O) in simple words.\n2. Suggest faster versions (sets/maps for lookups, batching, streaming, fewer passes), smallest change first.\n3. Estimate the speed-up for each change, and tell me how to measure it before and after.' },
    { id: 'git-help', cat: 'code', lvl: 'b', t: { ar: 'ساعدني في مشكلة Git', en: 'Help me with a Git problem' },
      body: { ar: 'لما تتلخبط في Git (commit غلط، فرع، تعارض) ومحتاج الأوامر الصح بالترتيب من غير ما تبوّظ حاجة.', en: 'When Git gets confusing (a wrong commit, a branch, a conflict) and you need the right commands in order without breaking anything.' },
      vars: { situation: { ar: 'إيه اللي حصل', en: 'What happened' }, goal: { ar: 'عايز توصل لإيه', en: 'What you want' }, output: { ar: 'ناتج git status وgit log --oneline -5', en: 'Output of git status and git log --oneline -5' } },
      code: 'Git situation: {{situation}}\nWhat I want: {{goal}}\n\n<output>\n{{output}}\n</output>\n\nGive me the exact commands in order, one per line, with a short comment on each. Prefer safe commands; if a step can lose work (reset --hard, push --force), warn me and show how to make a backup branch first.' },
    { id: 'sql-explain', cat: 'code', lvl: 'i', t: { ar: 'اشرح الاستعلام ده وحسّنه', en: 'Explain and improve this query' },
      body: { ar: 'استعلام SQL حد كتبه ومش فاهمه، أو بطيء.', en: 'A SQL query someone else wrote that you do not understand, or that is slow.' },
      vars: { db: { ar: 'نوع قاعدة البيانات', en: 'Database type' }, tables: { ar: 'الجداول وأعمدتها', en: 'Tables and columns' }, code: { ar: 'الاستعلام', en: 'The query' } },
      code: 'Database: {{db}}\nTables:\n{{tables}}\n\nQuery:\n<code>\n{{code}}\n</code>\n\n1. Explain step by step what it returns.\n2. Point out bugs or traps (NULLs, duplicates from joins, time zones).\n3. Suggest a faster or clearer version and the indexes that would help.\n4. Give one small sample dataset I can use to test both versions.' },
    { id: 'architecture', cat: 'code', lvl: 'a', t: { ar: 'صمملي هيكل مشروع', en: 'Design a project structure' },
      body: { ar: 'قبل ما تبدأ مشروع متوسط: الفولدرات والملفات والطبقات وإيه بيكلّم إيه.', en: 'Before starting a medium project: folders, files, layers and what talks to what.' },
      vars: { idea: { ar: 'فكرة المشروع', en: 'Project idea' }, stack: { ar: 'اللغات والأدوات', en: 'Languages and tools' }, scale: { ar: 'الحجم المتوقع', en: 'Expected scale' } },
      code: 'Design a simple, maintainable structure for this project.\nIdea: {{idea}}\nStack: {{stack}}\nExpected scale: {{scale}}\n\nGive me:\n1. A folder/file tree with a one-line purpose for each.\n2. The main modules and how data flows between them (a short list, then an ASCII diagram).\n3. Where config, secrets, logs and tests live.\n4. What NOT to build yet (keep it small), and what would make me split it later.' },
    { id: 'pseudocode', cat: 'code', lvl: 'b', t: { ar: 'من فكرة لخطوات قبل الكود', en: 'From an idea to steps before the code' },
      body: { ar: 'لما الفكرة في دماغك بس مش عارف تبدأ الكود منين.', en: 'When the idea is in your head but you do not know where to start the code.' },
      vars: { idea: { ar: 'الفكرة', en: 'The idea' } },
      code: 'Help me plan this before I write any code:\n{{idea}}\n\n1. Inputs and outputs, with one concrete example.\n2. Step-by-step pseudocode (numbered, plain English, no real code).\n3. The tricky cases I must handle.\n4. Which step I should write and test first.\nAsk me up to 3 questions if something is unclear, before answering.' },
    { id: 'docstring', cat: 'code', lvl: 'b', t: { ar: 'تعليقات وتوثيق للكود', en: 'Comments and docs for the code' },
      body: { ar: 'تعليقات بتقول «ليه» مش «إيه»، وdocstrings للدوال.', en: 'Comments that say «why», not «what», and docstrings for functions.' },
      vars: { code: { ar: 'الكود', en: 'The code' } },
      code: 'Add documentation to this code without changing any logic.\n\n<code>\n{{code}}\n</code>\n\n- A docstring/JSDoc for each function: purpose, parameters, return value, errors raised.\n- Inline comments only where the reason is not obvious (explain WHY, never repeat WHAT the code says).\n- Remove comments that are wrong or just repeat the code.\nReturn the full updated code.' },
    { id: 'cli-tool', cat: 'code', lvl: 'i', t: { ar: 'أداة سطر أوامر', en: 'A command-line tool' },
      body: { ar: 'تحوّل سكربت لأداة بخيارات وhelp ورسائل خطأ، تشغّلها من n8n أو cron.', en: 'Turn a script into a tool with options, help and error messages, runnable from n8n or cron.' },
      vars: { language: { ar: 'Python ولا Node', en: 'Python or Node' }, purpose: { ar: 'الأداة بتعمل إيه', en: 'What the tool does' }, options: { ar: 'الخيارات', en: 'The options' } },
      code: 'Write a {{language}} command-line tool that {{purpose}}.\nOptions: {{options}}\n\n- --help output with examples.\n- Clear exit codes: 0 success, 1 failure, 2 bad usage.\n- Read secrets from environment variables, never from arguments.\n- Print a one-line summary at the end; detailed logs only with --verbose.\n- Show how to call it from an n8n Execute Command node.' },
    { id: 'from-error-to-test', cat: 'code', lvl: 'i', t: { ar: 'من bug لاختبار يمسكه', en: 'From a bug to a test that catches it' },
      body: { ar: 'لقيت bug؟ اكتب الاختبار اللي يفشل بسببه الأول، وبعدين الإصلاح.', en: 'Found a bug? Write the test that fails because of it first, then the fix.' },
      vars: { bug: { ar: 'وصف الـ bug', en: 'The bug' }, code: { ar: 'الكود', en: 'The code' }, framework: { ar: 'أداة الاختبار', en: 'Test framework' } },
      code: 'Bug: {{bug}}\n\n<code>\n{{code}}\n</code>\n\n1. Write a failing {{framework}} test that reproduces the bug (it must fail on the current code).\n2. Write the smallest fix.\n3. Add 2 more tests for nearby cases the same mistake could break.\nShow the test first, then the fix.' },
    // ---------------- web and JavaScript ----------------
    { id: 'landing-page', cat: 'web', lvl: 'b', t: { ar: 'صفحة هبوط HTML وCSS', en: 'An HTML and CSS landing page' },
      body: { ar: 'صفحة عرض بسيطة متجاوبة وعربي، من غير مكتبات.', en: 'A simple responsive Arabic offer page, with no libraries.' },
      vars: { business: { ar: 'النشاط والعرض', en: 'The business and the offer' }, sections: { ar: 'الأقسام', en: 'The sections' }, colors: { ar: 'الألوان', en: 'Colours' } },
      code: 'Build a single-page landing page in semantic HTML and plain CSS (no frameworks) for: {{business}}.\nSections: {{sections}}\nBrand colours: {{colors}}\n\n- Arabic, lang="ar" dir="rtl", mobile-first, CSS Grid/Flexbox, logical properties (margin-inline...).\n- Colour variables in :root plus a dark mode with prefers-color-scheme.\n- Accessible: one h1, labels on every field, alt text, visible focus, contrast ≥ 4.5:1.\n- A contact form with name, phone (pattern for an Egyptian mobile) and message.\n- Title, meta description and Open Graph tags.\nReturn index.html and style.css separately.' },
    { id: 'css-fix', cat: 'web', lvl: 'b', t: { ar: 'التصميم مش مظبوط في CSS', en: 'My CSS layout is broken' },
      body: { ar: 'عنصر مش في مكانه، أو الصفحة بتتسحب جنب على الموبايل.', en: 'An element is out of place, or the page scrolls sideways on phones.' },
      vars: { problem: { ar: 'إيه اللي غلط', en: 'What is wrong' }, code: { ar: 'الـ HTML والـ CSS', en: 'The HTML and CSS' } },
      code: 'Layout problem: {{problem}}\n\n<code>\n{{code}}\n</code>\n\nExplain the cause (box model, flex/grid behaviour, overflow, specificity...), then give the smallest CSS change that fixes it. Keep it working in RTL and LTR and at 360px wide. Tell me which DevTools panel would have shown me the cause.' },
    { id: 'dom-feature', cat: 'web', lvl: 'i', t: { ar: 'خاصية تفاعلية في الصفحة', en: 'An interactive feature on the page' },
      body: { ar: 'بحث مباشر، فلتر، تبويبات، نافذة… بـ JavaScript عادي وآمن.', en: 'A live search, a filter, tabs, a dialog… in plain, safe JavaScript.' },
      vars: { feature: { ar: 'الخاصية', en: 'The feature' }, html: { ar: 'الـ HTML الحالي', en: 'The current HTML' } },
      code: 'Add this feature with plain JavaScript (no libraries): {{feature}}\n\nCurrent HTML:\n<code>\n{{html}}\n</code>\n\n- Event delegation, data-* attributes, classList for state (styles stay in CSS).\n- Never put user or API data into innerHTML; use textContent or createElement.\n- Keyboard accessible (Enter/Escape/arrows where it makes sense) with the right aria attributes.\n- Show the JS, any CSS it needs, and the small HTML changes.' },
    { id: 'form-to-n8n', cat: 'web', lvl: 'i', t: { ar: 'فورم يبعت لـ webhook في n8n', en: 'A form that posts to an n8n webhook' },
      body: { ar: 'فورم بيتحقق ويبعت JSON بـ fetch، بحالات التحميل والنجاح والخطأ.', en: 'A form that validates and sends JSON with fetch, with loading, success and error states.' },
      vars: { fields: { ar: 'الحقول', en: 'The fields' }, url: { ar: 'عنوان الـ webhook', en: 'Webhook URL' } },
      code: 'Write the JavaScript for a form with these fields: {{fields}}\nOn submit, send the data as JSON with fetch (POST) to {{url}}.\n\n- Validate each field and show the message next to it (aria-describedby).\n- Four visible states: idle, sending (button disabled), success (clear the form), error (keep the data, say what to do).\n- Check response.ok; time out after 15 seconds with AbortSignal.timeout.\n- Add a hidden honeypot field against bots.\n- Then describe the n8n side: Webhook → validate again in a Code node → Respond to Webhook.' },
    { id: 'node-script', cat: 'web', lvl: 'i', t: { ar: 'سكربت Node.js للأتمتة', en: 'A Node.js automation script' },
      body: { ar: 'قراية ملفات وطلبات API وتقارير من Node بدل Python.', en: 'Reading files, calling APIs and building reports from Node instead of Python.' },
      vars: { task: { ar: 'المهمة', en: 'The task' } },
      code: 'Write a Node.js 22 ES-module script (main.mjs) that does: {{task}}\n\n- Use only node: built-ins and fetch unless a package is clearly worth it (say which and why).\n- async/await with try/catch around every network and file step.\n- Secrets from process.env (load with node --env-file=.env).\n- Retries with exponential backoff for HTTP 429/5xx (max 3).\n- process.exitCode = 1 on failure and a one-line summary at the end.' },
    { id: 'ts-types', cat: 'web', lvl: 'i', t: { ar: 'أنواع TypeScript لبيانات API', en: 'TypeScript types for API data' },
      body: { ar: 'من مثال JSON لأنواع TypeScript وتحقق Zod وقت التشغيل.', en: 'From a JSON example to TypeScript types and run-time Zod validation.' },
      vars: { json: { ar: 'مثال JSON', en: 'A JSON example' } },
      code: 'From this JSON example, write:\n1. TypeScript interfaces (mark optional fields, use union types for known string values).\n2. A Zod schema that validates the same shape at run time, and the type inferred from it.\n3. A parse function returning { ok: true, data } or { ok: false, errors } without throwing.\n\n<json>\n{{json}}\n</json>' },
    { id: 'playwright-script', cat: 'web', lvl: 'a', t: { ar: 'أتمتة متصفح بـ Playwright', en: 'Browser automation with Playwright' },
      body: { ar: 'لموقع ملوش API: تفتح وتملا وتدوس وتسحب بيانات، باحترام شروط الموقع.', en: 'For a site with no API: open, fill, click and collect data, respecting the site’s terms.' },
      vars: { site: { ar: 'الموقع (عندك صلاحية عليه)', en: 'The site (you are allowed to use)' }, steps: { ar: 'الخطوات', en: 'The steps' }, data: { ar: 'البيانات المطلوبة', en: 'The data you need' } },
      code: 'Write a Playwright (Node) script for {{site}}, which I am allowed to automate.\nSteps: {{steps}}\nData to collect: {{data}}\n\n- Locate elements with getByRole/getByLabel, not fragile CSS paths.\n- Wait for real conditions, never fixed sleeps (except a polite delay between pages).\n- Save results as JSON and a screenshot on any failure.\n- Credentials from environment variables; never log them.\n- Explain how to run it headless on a server.' },
    { id: 'apps-script', cat: 'web', lvl: 'i', t: { ar: 'أتمتة Google Sheets بـ Apps Script', en: 'Automating Google Sheets with Apps Script' },
      body: { ar: 'تقرير يومي، أو إيميل تلقائي، أو تنضيف شيت — من جوه Google.', en: 'A daily report, an automatic email or sheet cleaning — from inside Google.' },
      vars: { sheet: { ar: 'شكل الشيت (الأعمدة)', en: 'The sheet’s shape (columns)' }, task: { ar: 'المطلوب', en: 'The task' }, schedule: { ar: 'إمتى يشتغل', en: 'When it runs' } },
      code: 'Write a Google Apps Script for a sheet with these columns: {{sheet}}\nTask: {{task}}\nRun: {{schedule}} (with an installable time-driven trigger).\n\n- Read all values in one getValues() call and write back in one setValues() call.\n- Skip empty rows; log problems to a "Problems" sheet instead of stopping.\n- Use Session.getScriptTimeZone() for dates.\n- Explain how to install the trigger and grant permissions safely.' },
    { id: 'web-perf', cat: 'web', lvl: 'a', t: { ar: 'خلّي صفحتي أسرع', en: 'Make my page faster' },
      body: { ar: 'من نتيجة Lighthouse لخطة تحسين مرتّبة بالأثر.', en: 'From a Lighthouse result to an improvement plan ordered by impact.' },
      vars: { notes: { ar: 'ملاحظات Lighthouse', en: 'Lighthouse notes' }, html: { ar: 'الـ head وأهم أجزاء الصفحة', en: 'The head and key parts of the page' } },
      code: 'My page is slow. Lighthouse says:\n<notes>\n{{notes}}\n</notes>\n\nPage head and key parts:\n<code>\n{{html}}\n</code>\n\nGive a plan ordered by impact: images (size, format, lazy loading), fonts (subset, display=swap, preconnect), scripts (defer, remove unused), CSS and caching. For each step: the exact change and how to verify it.' },
    { id: 'a11y-audit', cat: 'web', lvl: 'i', t: { ar: 'راجع إمكانية الوصول', en: 'Review accessibility' },
      body: { ar: 'هل الصفحة شغالة بالكيبورد وقارئ الشاشة؟', en: 'Does the page work with a keyboard and a screen reader?' },
      vars: { html: { ar: 'الـ HTML', en: 'The HTML' } },
      code: 'Review this HTML for accessibility (WCAG 2.2 AA):\n<code>\n{{html}}\n</code>\n\nList each problem with: the element, why it matters (who it affects), and the fixed code. Check headings, labels, alt text, buttons vs links, focus order and visibility, colour contrast, aria use (prefer native HTML), language and direction. Most important first.' },
    { id: 'chrome-extension', cat: 'web', lvl: 'a', t: { ar: 'إضافة متصفح صغيرة', en: 'A small browser extension' },
      body: { ar: 'إضافة Chrome بتوفّر عليك شغل يومي متكرر في موقع بتستخدمه.', en: 'A Chrome extension saving you repeated daily work on a site you use.' },
      vars: { job: { ar: 'الإضافة تعمل إيه', en: 'What it does' }, site: { ar: 'الموقع', en: 'The site' } },
      code: 'Create a minimal Manifest V3 Chrome extension that {{job}} on {{site}}.\n\n- Ask for the fewest permissions possible (activeTab/host permissions for that site only) and explain each one.\n- No remote code; everything bundled.\n- Store settings with chrome.storage.sync.\n- Give every file (manifest.json, the script, a small popup) and the steps to load it unpacked.' },
    // ---------------- quality and security ----------------
    { id: 'security-review', cat: 'sec', lvl: 'a', t: { ar: 'مراجعة أمان للكود', en: 'A security review of code' },
      body: { ar: 'قبل ما تحط حاجة على سيرفر أو تسلّمها لعميل.', en: 'Before you put something on a server or hand it to a client.' },
      vars: { context: { ar: 'الكود بيعمل إيه وفين', en: 'What the code does and where it runs' }, code: { ar: 'الكود', en: 'The code' } },
      code: 'Review this code for security problems. Context: {{context}}\n\n<code>\n{{code}}\n</code>\n\nCheck: injection (SQL, command, HTML/XSS), secrets in code or logs, input validation, authentication and authorisation, file and path handling, unsafe deserialisation, dependency risks, rate limits, error messages that leak details.\nFor each finding: severity (high/medium/low), the line, how it could be abused (one sentence, no exploit code), and the fix. Say clearly if you find nothing serious.' },
    { id: 'webhook-security', cat: 'sec', lvl: 'a', t: { ar: 'تأمين webhook', en: 'Securing a webhook' },
      body: { ar: 'webhook مفتوح على النت = أي حد يقدر يبعتله. خطة تأمين عملية.', en: 'A webhook open to the internet means anyone can send to it. A practical hardening plan.' },
      vars: { source: { ar: 'مين بيبعت', en: 'Who sends to it' }, data: { ar: 'نوع البيانات', en: 'The kind of data' } },
      code: 'I have a webhook (n8n or Node) that receives {{data}} from {{source}}.\nGive me a hardening plan:\n1. How to verify the sender (HMAC signature with timestamp, or a secret header) — with code to check it.\n2. Replay protection and idempotency (dedupe by event id).\n3. Input validation and size limits.\n4. Rate limiting and what to log (never secrets).\n5. What to return on failure without leaking details.' },
    { id: 'secrets-cleanup', cat: 'sec', lvl: 'i', t: { ar: 'سرّ اتسرّب في الكود', en: 'A secret leaked in the code' },
      body: { ar: 'مفتاح API اتعمله commit أو اتحط في رسالة. تعمل إيه بالترتيب.', en: 'An API key was committed or pasted in a message. What to do, in order.' },
      vars: { what: { ar: 'إيه اللي اتسرّب وفين', en: 'What leaked and where' } },
      code: 'This secret leaked: {{what}}.\nGive me an ordered incident checklist:\n1. Revoke/rotate it first (where, for the common providers).\n2. Check the provider’s logs for misuse.\n3. Remove it from the code and history (git filter-repo or BFG) and why rotation matters more than deleting.\n4. Move secrets to environment variables or a secret manager, and add pre-commit secret scanning.\nDo not ask me to paste the secret itself.' },
    { id: 'test-plan', cat: 'sec', lvl: 'i', t: { ar: 'خطة اختبار لمشروع', en: 'A test plan for a project' },
      body: { ar: 'إيه اللي تختبره، وبأنهي نوع اختبار، وبأنهي ترتيب.', en: 'What to test, with which kind of test, in which order.' },
      vars: { project: { ar: 'المشروع', en: 'The project' }, risks: { ar: 'أكتر حاجات خايف منها', en: 'What worries you most' } },
      code: 'Create a test plan for: {{project}}\nBiggest risks: {{risks}}\n\n- Unit, integration and end-to-end tests: what goes in each (a table).\n- 10 high-value test cases to write first, including failure and boundary cases.\n- Test data I need (fake, never real customer data).\n- What to run on every push in CI and what to run nightly.' },
    { id: 'code-smells', cat: 'sec', lvl: 'i', t: { ar: 'إيه اللي ريحته وحشة في الكود ده؟', en: 'What smells bad in this code?' },
      body: { ar: 'مراجعة جودة: تكرار، دوال طويلة، أسماء مبهمة، اعتمادات مخفية.', en: 'A quality review: duplication, long functions, vague names, hidden dependencies.' },
      vars: { code: { ar: 'الكود', en: 'The code' } },
      code: 'Find code smells in this code and rank them by how much they will hurt future changes:\n<code>\n{{code}}\n</code>\n\nFor each: the smell, where, why it matters, and a small refactoring step. Keep behaviour identical. Finish with the single most valuable change to do today.' },
    { id: 'dependency-check', cat: 'sec', lvl: 'i', t: { ar: 'أستخدم المكتبة دي ولا لأ؟', en: 'Should I use this library?' },
      body: { ar: 'قبل ما تضيف مكتبة لمشروع: الصيانة والأمان والحجم والبدائل.', en: 'Before adding a library to a project: maintenance, security, size and alternatives.' },
      vars: { pkg: { ar: 'اسم المكتبة', en: 'Package name' }, need: { ar: 'محتاجها ليه', en: 'Why you need it' } },
      code: 'I am thinking of adding {{pkg}} to do: {{need}}.\nHelp me decide:\n- Could the standard library or a few lines of my own code do it?\n- What should I check on its repository (last release, open issues, maintainers, licence, download trends, known vulnerabilities)?\n- Lighter or better-maintained alternatives.\nIf you are not sure about current facts (versions, dates), say so and tell me where to check instead of guessing.' },
    { id: 'logging-plan', cat: 'sec', lvl: 'i', t: { ar: 'لوجات ومراقبة لخدمة', en: 'Logging and monitoring for a service' },
      body: { ar: 'عشان تعرف إن حاجة وقعت قبل ما العميل يقولك.', en: 'So you know something broke before the client tells you.' },
      vars: { service: { ar: 'الخدمة', en: 'The service' } },
      code: 'Design logging and monitoring for: {{service}}\n- Which events to log, at which level, as structured JSON (the fields).\n- What must never be logged (secrets, card data, full personal data).\n- 5 alerts worth waking someone up for, and 5 that should only be a daily summary.\n- A simple health check endpoint and what it should verify.' },
    { id: 'privacy-check', cat: 'sec', lvl: 'i', t: { ar: 'مراجعة خصوصية لـ Workflow', en: 'A privacy review of a workflow' },
      body: { ar: 'بيانات عملاء بتمر في أدوات كتير: مين بيشوفها وبتتخزّن فين وقد إيه.', en: 'Customer data passes through many tools: who sees it, where it is stored, and for how long.' },
      vars: { flow: { ar: 'خطوات الـ workflow والأدوات', en: 'The workflow steps and tools' }, data: { ar: 'نوع البيانات الشخصية', en: 'The kind of personal data' } },
      code: 'Review this automation for privacy: {{flow}}\nPersonal data involved: {{data}}\n\nMap where the data goes (each tool and region), who can access it, and how long it stays. Then list improvements: data minimisation, masking before AI calls, retention and deletion, access control, and what to tell customers. Note which points may need a lawyer to confirm for my country.' },
    { id: 'review-ai-code', cat: 'sec', lvl: 'i', t: { ar: 'راجع كود كتبه AI', en: 'Review code written by AI' },
      body: { ar: 'الكود اللي بيطلع من الموديلات محتاج مراجعة: مكتبات مش موجودة، وحالات ناقصة، وأمان.', en: 'Code from models needs review: made-up packages, missing cases and security.' },
      vars: { code: { ar: 'الكود', en: 'The code' }, purpose: { ar: 'المفروض يعمل إيه', en: 'What it should do' } },
      code: 'This code was generated by an AI assistant. It should: {{purpose}}\n\n<code>\n{{code}}\n</code>\n\nCheck it carefully:\n1. APIs, functions or packages that may not exist or may be outdated — flag anything you are unsure about.\n2. Missing error handling and edge cases.\n3. Security issues.\n4. Places where it does more or less than asked.\nThen give 5 tests that would prove it works.' }
  ]
});
