// Tips for tips.html — AI assistants (cards in the «tips» section of content/sections/tips.js).
// Kept to durable habits; product menus change often, so steps name the setting rather than every click.
(function(){
function C(id, lvl, ar, en, more){
  var o = { id: id, cat: 'ai', lvl: lvl, t: { ar: ar[0], en: en[0] }, body: { ar: ar[1], en: en[1] } };
  if(ar[2]) o.tip = { ar: ar[2], en: en[2] };
  if(more) for(var k in more) o[k] = more[k];
  return o;
}
SECTIONS.extend('tips', 'tips', { items: [
  C('ai-how-to-ask', 'b',
    ["إزاي تسأل الشات بوت وتاخد إجابة مفيدة", "- **الخلفية**: انت مين وعايز إيه وليه.\n- **الشكل**: «في 5 نقط»، «جدول»، «في 100 كلمة»، «بلغة بسيطة».\n- **أمثلة** من اللي عايزه.\n- كمّل بأسئلة: «أبسط»، «اشرح النقطة 3»، «إيه اللي ممكن يكون غلط هنا؟».\n- ارفع PDF أو صورة واطلب تلخيص أو شرح.\n\nفي الموقع صفحة **البرومبتات** فيها برومبتات جاهزة بتملاها وتنسخها.", "ابدأ رسالة جديدة لموضوع جديد؛ المحادثة الطويلة جدًا بتلخبط الإجابات."],
    ["How to ask a chatbot and get a useful answer", "- **Context**: who you are, what you want and why.\n- **Format**: «in 5 bullets», «a table», «in 100 words», «in plain language».\n- **Examples** of what you want.\n- Follow up: «simpler», «explain point 3», «what could be wrong here?».\n- Upload a PDF or image and ask for a summary or explanation.\n\nThis site's **Prompts** page has ready prompts you fill in and copy.", "Start a new chat for a new topic; very long chats muddle the answers."]),
  C('ai-verify', 'b',
    ["الذكاء الاصطناعي بيغلط بثقة", "- بيخترع أرقام ومصادر ولينكات وأرقام تليفونات أحيانًا.\n- أي **صحة أو فلوس أو قانون**: اتأكد من مصدر رسمي أو متخصص.\n- اطلب المصادر وافتحها بنفسك.\n- ما تاخدش لينك تسجيل دخول أو رقم خدمة عملاء من شات بوت.\n- الحسابات (كميات، تحويلات) مفيدة بس راجع الأرقام.", "اسأله: «إيه اللي انت مش متأكد منه في الإجابة دي؟»."],
    ["AI is confidently wrong at times", "- It sometimes invents figures, sources, links and phone numbers.\n- Anything about **health, money or law**: check an official or expert source.\n- Ask for sources and open them yourself.\n- Never take a login link or support number from a chatbot.\n- Calculations (quantities, conversions) are useful, but sanity-check the numbers.", "Ask it: «what are you unsure about in this answer?»."]),
  C('ai-private', 'b',
    ["إيه اللي ما تكتبوش لأي ذكاء اصطناعي", "- باسوردات وأرقام قومية وأرقام كروت وحسابات بنك.\n- مستندات شغل سرية أو بيانات عملاء.\n- صور شخصية لأطفال أو لناس من غير إذنهم (الصور بتكشف المكان والسن والاهتمامات).\n- لو لازم: شيل الأسماء والأرقام، واستخدم **Temporary chat** وقفل «تحسين النموذج».", "الشات اللي بتعمل له رابط مشاركة عام ممكن يتفهرس؛ امسح الروابط القديمة من الإعدادات."],
    ["What never to type into any AI", "- Passwords, ID numbers, card numbers and bank details.\n- Confidential work documents or customer data.\n- Personal photos of children or people without their consent (photos reveal place, age and interests).\n- If you must: remove names and numbers, use **Temporary chat** and turn off «improve the model».", "A chat you share by public link can be indexed; delete old links in settings."]),
  C('ai-everyday', 'b',
    ["استخدامات يومية بتوفر وقت", "- جواب شكوى أو استرجاع فلوس بصيغة محترمة.\n- شرح عقد أو كتالوج أو رسالة رسمية بلغة بسيطة.\n- تدريب على لغة بالكلام (Voice mode)، أو تحضير لمقابلة.\n- خطة رحلة، أو مقارنة منتجات (واتأكد من الأسعار في المتجر).\n- تعرف حاجة من صورة (نبات، قطعة غيار، رسالة خطأ).\n- كتابة أو تصليح كود صغير.", "Copilot كويس في خطوات حل مشاكل ويندوز، وClaude في الكتابة والجداول؛ جرّب أكتر من واحد."],
    ["Everyday uses that save time", "- A polite complaint or refund letter.\n- Explaining a contract, manual or official letter in plain language.\n- Speaking practice in a language (voice mode), or interview rehearsal.\n- A trip plan, or a product comparison (check prices at the shop).\n- Identifying something from a photo (a plant, a spare part, an error message).\n- Writing or fixing small bits of code.", "Copilot is good at Windows troubleshooting steps, Claude at writing and spreadsheets; try more than one."]),
  C('ai-documents', 'b',
    ["ذاكر وافهم مستندات بالذكاء الاصطناعي", "- **NotebookLM**: حط مصادر (PDF، مواقع، فيديوهات يوتيوب، صوت) واسأل؛ الإجابات من مصادرك بس، وفيه ملخص صوتي زي البودكاست وأسئلة امتحان.\n- **وضع المذاكرة** في ChatGPT: بيشرح خطوة خطوة ويسألك.\n- ارفع محاضرة صوتية واطلب تفريغ وملخص.", "في الموقع رحلات تعليمية كاملة؛ استخدم الذكاء الاصطناعي يشرحلك اللي مش فاهمه فيها."],
    ["Study and understand documents with AI", "- **NotebookLM**: add sources (PDFs, websites, YouTube videos, audio) and ask; answers come only from your sources, with podcast-style audio summaries and quizzes.\n- ChatGPT's **study mode** explains step by step and quizzes you.\n- Upload a recorded lecture and ask for a transcript and summary.", "This site has full learning journeys; use AI to explain whatever you do not understand there."]),
  C('ai-memory', 'i',
    ["ذاكرة الشات بوت: مفيدة بس راجعها", "ChatGPT وGemini وCopilot وClaude ممكن «يفتكروا» معلومات عنك بين المحادثات:\n- راجع اللي فاكره وامسح من **Memory / Personal context**.\n- اقفل «Reference chat history» لو عايز خصوصية أكتر.\n- **Temporary/Incognito chat** مش بيتحفظ.\n- اعمل لوج أوت من الأجهزة القديمة (Active sessions)، وفعّل التحقق بخطوتين.", "تقدر تصدّر بياناتك من الإعدادات وتشوف هو عارف عنك إيه."],
    ["Chatbot memory: useful, but review it", "ChatGPT, Gemini, Copilot and Claude can «remember» things about you across chats:\n- Review and delete in **Memory / Personal context**.\n- Turn off «Reference chat history» for more privacy.\n- **Temporary/Incognito chat** is not saved.\n- Log out old devices (Active sessions) and enable two-step verification.", "You can export your data from settings to see what it knows about you."]),
  C('ai-voice-camera', 'b',
    ["كلّمه بصوتك ووريه بالكاميرا", "- **الوضع الصوتي** (Gemini Live، ChatGPT Voice، Copilot): كلام طبيعي، تقاطعه، وتطلب يبطّأ أو يسرّع.\n- **مشاركة الكاميرا أو الشاشة**: «إيه الزرار ده؟»، «الرسالة دي معناها إيه؟».\n- **ترجمة فورية**: قول «ترجم كلامي للإنجليزي».\n- Google Translate فيه Conversation وLive translate بالسماعة.", "اتمرّن على الإنجليزي بالكلام كل يوم 10 دقايق؛ وفي الموقع صفحة تدريب كلام كمان."],
    ["Talk to it and show it with the camera", "- **Voice mode** (Gemini Live, ChatGPT Voice, Copilot): natural speech, interrupt, and ask it to slow down or speed up.\n- **Share the camera or screen**: «what is this button?», «what does this message mean?».\n- **Live translation**: say «translate what I say into English».\n- Google Translate has Conversation and Live translate with earphones.", "Practise speaking English 10 minutes a day; this site has a speaking-practice page too."]),
  C('ai-images', 'b',
    ["صور بالذكاء الاصطناعي", "- تعديل بالكلام: «شيل الخلفية»، «خليها أنور»، «لوّن الصورة الأبيض وأسود».\n- **Paint والصور في ويندوز**: مسح حاجة، إزالة أو تغبيش الخلفية.\n- **Upscayl** (أوفلاين): تكبير وتوضيح.\n- **Easy Diffusion**: توليد صور على جهازك (محتاج كارت شاشة).\n- الصور المولّدة عليها علامات مخفية (SynthID وغيره)؛ وقول إنها مولّدة لو هتنشرها.", "ترميم الصور القديمة بالذكاء الاصطناعي بيخترع تفاصيل؛ احتفظ بالأصل."],
    ["AI images", "- Edit by asking: «remove the background», «make it brighter», «colourise this black-and-white photo».\n- **Windows Paint and Photos**: erase objects, remove or blur backgrounds.\n- **Upscayl** (offline): enlarge and sharpen.\n- **Easy Diffusion**: generate images on your own PC (needs a graphics card).\n- Generated images carry hidden marks (SynthID and others); say they are AI-made if you publish them.", "AI restoration of old photos invents details; keep the original."]),
  C('ai-custom', 'i',
    ["مساعد مخصص من غير برمجة", "- **Gemini Gems** و**ChatGPT GPTs/Projects** و**Claude Projects**: اكتب التعليمات مرة واحدة (أسلوبك، بلدك، مستواك)، وحط ملفات مرجعية، واستخدمه كل مرة.\n- مثال: «مساعد مراجعة إيميلات الشغل بالإنجليزي».\n- **Custom instructions / Personalization**: إجابات أقصر أو أسلوب معيّن في كل المحادثات.", "ما تحطش ملفات سرية في مساعد مشارك مع حد."],
    ["A custom assistant without coding", "- **Gemini Gems**, **ChatGPT GPTs/Projects** and **Claude Projects**: write instructions once (your style, country, level), add reference files, and reuse it.\n- Example: «an assistant that reviews my work emails in English».\n- **Custom instructions / Personalization**: shorter answers or a set tone in every chat.", "Do not put confidential files into an assistant shared with others."]),
  C('ai-private-options', 'i',
    ["ذكاء اصطناعي بخصوصية أعلى", "- **Duck.ai**: من غير حساب، المحادثات مش بتتحفظ عندهم ولا بتدرّب النماذج.\n- **Proton Lumo**: محادثات مشفّرة.\n- **أوفلاين** على جهازك: Vibe للتفريغ، Easy Diffusion للصور، ونماذج محلية لو جهازك قوي.\n- في المتصفح: اقفل قراءة التابات من غير إذنك (Edge: «Browse with Copilot» = Strict).", "الإعلانات بدأت تظهر جوه بعض الشات بوتس؛ مانع الإعلانات بيشيلها."],
    ["More private AI", "- **Duck.ai**: no account; chats are not stored by them or used for training.\n- **Proton Lumo**: encrypted chats.\n- **Offline** on your PC: Vibe for transcription, Easy Diffusion for images, and local models if your PC is strong.\n- In the browser: stop it reading tabs without asking (Edge: «Browse with Copilot» = Strict).", "Ads have started appearing in some chatbots; an ad blocker removes them."]),
  C('ai-scam-check', 'b',
    ["استخدمه رأي تاني في الرسايل المشكوك فيها", "ابعت سكرين شوت للرسالة واسأل «ده نصب؟» (فيه أدوات فحص نصب مخصصة كمان). مفيد كرأي تاني، **مش حكم نهائي**: القاعدة الذهبية تفضل «اتصل بالجهة من الرقم الرسمي».", "الذكاء الاصطناعي نفسه بيستخدمه النصابين (صوت مقلّد، صور مزيفة)؛ كلمة سر العيلة بتحميك."],
    ["Use it as a second opinion on suspicious messages", "Send a screenshot of the message and ask «is this a scam?» (dedicated scam checkers exist too). Useful as a second opinion, **not a final verdict**: the golden rule stays «call the organisation on its official number».", "Scammers use AI too (cloned voices, fake images); a family safe word protects you."]),
  C('ai-turn-off', 'b',
    ["عايز تقفل الذكاء الاصطناعي؟", "- **Copilot** في ويندوز: `Settings > Apps > Installed apps > Uninstall`، وزرار Copilot في Edge من الإعدادات.\n- **ملخصات جوجل**: تابة Web أو `&udm=14`.\n- **Firefox**: «Block AI enhancements».\n- **Gmail وأوفيس**: Smart features / Connected experiences.\n- أدوات زي O&O ShutUp10 وWinhance فيها أقسام للذكاء الاصطناعي.", "أي برنامج أو إضافة «AI» مجهولة: ممكن تكون بتجمع بياناتك وبس."],
    ["Want to turn AI off?", "- **Copilot** in Windows: Settings > Apps > Installed apps > Uninstall, and the Copilot button in Edge settings.\n- **Google summaries**: the Web tab or `&udm=14`.\n- **Firefox**: «Block AI enhancements».\n- **Gmail and Office**: Smart features / Connected experiences.\n- Tools like O&O ShutUp10 and Winhance have AI sections.", "An unknown «AI» program or extension may simply be harvesting your data."]),
  C('ai-photo-location', 'i',
    ["الذكاء الاصطناعي بيعرف الصورة اتصورت فين", "من لافتة أو نبات أو مواصلات أو اسم فندق. ده مفيد لتسمية أرشيف صور العيلة القديم، وخطر لصورك الشخصية: النصابين بيستخدموه في رسايل مخصوصة («حصل حاجة على حسابك وانت في...»). قلّل اللي بتنشره علني وأخّر نشر صور السفر لبعد الرجوع.", "شيل الموقع من بيانات الصورة قبل ما ترفعها لأي أداة."],
    ["AI can tell where a photo was taken", "From a sign, a plant, transport or a hotel name. Helpful for labelling an old family archive, risky for personal photos: scammers use it for tailored messages («activity on your account while you were in…»). Share less publicly, and post travel photos after you return.", "Remove location data from a photo before uploading it to any tool."])
] });
})();
