// Tips for tips.html — email (cards in the «tips» section of content/sections/tips.js).
(function(){
function C(id, lvl, ar, en, more){
  var o = { id: id, cat: 'mail', lvl: lvl, t: { ar: ar[0], en: en[0] }, body: { ar: ar[1], en: en[1] } };
  if(ar[2]) o.tip = { ar: ar[2], en: en[2] };
  if(more) for(var k in more) o[k] = more[k];
  return o;
}
SECTIONS.extend('tips', 'tips', { items: [
  C('mail-gmail-search', 'b',
    ["البحث في Gmail زي المحترفين", "- `from:` و`to:` و`subject:`.\n- `has:attachment`، `filename:pdf`، `larger:10M` (عشان تفضي مساحة).\n- `older_than:1y`، `after:2025/01/01 before:2025/07/01`.\n- `is:unread`، `category:promotions`.\n- اجمعهم: `from:bank has:attachment after:2026/01/01`.", "البحث بيتجاهل الفواصل والعلامات: دوّر على `17123.45` مش `17,123.45`. واحفظ لينك البحث كـ bookmark تعيده."],
    ["Search Gmail like a pro", "- `from:`, `to:`, `subject:`.\n- `has:attachment`, `filename:pdf`, `larger:10M` (to free space).\n- `older_than:1y`, `after:2025/01/01 before:2025/07/01`.\n- `is:unread`, `category:promotions`.\n- Combine: `from:bank has:attachment after:2026/01/01`.", "Search ignores punctuation: look for `17123.45`, not `17,123.45`. Bookmark a search URL to rerun it."],
    { code: "larger:10M older_than:1y" }),
  C('mail-undo-schedule', 'b',
    ["تراجع عن الإرسال وجدولته", "- Gmail: `Settings > See all settings > General` > **Undo Send = 30 ثانية**.\n- Outlook.com وProton فيهم Undo send كمان.\n- **Schedule send** (السهم جنب Send) و**Snooze** (تخفي الرسالة لحد معاد) موجودين في أغلب برامج الإيميل.", "اكتب الإيميل المهم من غير ما تحط المرسل إليه، وزوّده في الآخر."],
    ["Undo send and schedule send", "- Gmail: Settings > See all settings > General > **Undo Send = 30 seconds**.\n- Outlook.com and Proton have Undo send too.\n- **Schedule send** (the arrow next to Send) and **Snooze** (hide a message until later) exist in most mail apps.", "Write important emails without a recipient and add it last."]),
  C('mail-clean-inbox', 'b',
    ["نضّف الإيميل من النشرات والسبام", "- Gmail: القائمة > **Manage subscriptions** > Unsubscribe بضغطة (أأمن من لينكات جوه رسايل مشكوك فيها).\n- امسح كل رسايل راسل: دوّر بعنوانه > `Ctrl+A` > Delete؛ Outlook.com فيه **Sweep** يمسح ويمنع الجاي.\n- ابدأ بالنشرات اللي عمرك ما بتفتحها.\n- السبام من عناوين بتتغير: **Report spam/junk** يعلّم الفلتر أحسن من البلوك.", "ما تدوسش Unsubscribe جوه إيميل نصب؛ بيأكد إن إيميلك شغال."],
    ["Clean newsletters and spam out of your inbox", "- Gmail: menu > **Manage subscriptions** > one-click Unsubscribe (safer than links inside doubtful messages).\n- Delete everything from a sender: search their address > `Ctrl+A` > Delete; Outlook.com's **Sweep** deletes and blocks future ones.\n- Start with newsletters you never open.\n- Spam from changing addresses: **Report spam/junk** teaches the filter better than blocking.", "Never click Unsubscribe in a scam email; it confirms your address is live."]),
  C('mail-block-domain', 'i',
    ["امنع دومين كامل مش راسل واحد", "- Outlook.com/الجديد: `Settings > Mail > Junk email > Blocked senders and domains` > `domain.com`.\n- Gmail: اعمل فلتر `from:@domain.com` > Delete it.\n- قواعد على أجزاء ثابتة (كلمة في الموضوع) لما العناوين بتتغير.", "Outlook: «Report junk» للسبام العادي و«Report phishing» للنصب؛ الاتنين بيمنعوا الراسل بس بيغذّوا فلاتر مختلفة."],
    ["Block a whole domain, not one sender", "- Outlook.com/new Outlook: Settings > Mail > Junk email > Blocked senders and domains > `domain.com`.\n- Gmail: create a filter `from:@domain.com` > Delete it.\n- Rules on fixed parts (a subject word) when addresses keep changing.", "Outlook: «Report junk» for ordinary spam and «Report phishing» for scams; both block the sender but feed different filters."]),
  C('mail-send-as', 'i',
    ["كل إيميلاتك في صندوق واحد", "- Gmail **Send mail as**: `Settings > Accounts and Import > Add another email address`، وترد من عناوينك التانية.\n- حوّل الرسايل من الحسابات القديمة (Forwarding) لحسابك الأساسي.\n- **Thunderbird**: كل الحسابات مع بعض (Unified Folders)، وتقويم وجهات اتصال.", "مشاكل «sender unauthenticated»: ابعت من خادم Gmail نفسه (SMTP) مش من خادم شركة النت."],
    ["All your addresses in one inbox", "- Gmail **Send mail as**: Settings > Accounts and Import > Add another email address, and reply from your other addresses.\n- Forward old accounts to your main one.\n- **Thunderbird**: every account together (Unified Folders), with calendar and contacts.", "«Sender unauthenticated» problems: send through Gmail's own SMTP, not your ISP's server."]),
  C('mail-independent', 'b',
    ["إيميل مش مربوط بشركة النت", "إيميل شركة الإنترنت بيقفل لو غيرت الشركة أو قفلت الخدمة. للحاجات المهمة (البنك، الحكومة، الاسترجاع) استخدم إيميل مستقل: Gmail أو Outlook أو Proton أو دومين بتاعك.\n- دومين خاص؟ اللي ماسك حساب الدومين ماسك الإيميل؛ احفظ بياناته ومعاد التجديد.\n- خدمات إيميل مجانية بتقفل الحساب لو ما دخلتش من الويب سنة؛ ادخل مرة كل سنة.", "قبل ما تقفل إيميل قديم: غيّر الإيميل في كل حساب مسجّل بيه."],
    ["An email address not tied to your ISP", "An ISP address dies when you switch provider or the service closes. For important things (bank, government, recovery) use an independent address: Gmail, Outlook, Proton or your own domain.\n- Own domain? Whoever controls the domain account controls the email; keep its login and renewal date safe.\n- Some free providers close accounts not used on the web for a year; sign in yearly.", "Before closing an old address, update it on every account that uses it."]),
  C('mail-move-provider', 'i',
    ["تنقل لشركة إيميل تانية", "1. فعّل **Forwarding** من القديم للجديد.\n2. أداة **Import** في الخدمة الجديدة (رسايل وجهات اتصال وتقويم). Proton فيه Easy Switch.\n3. غيّر الإيميل في حساباتك المهمة بالتدريج.\n4. سيب القديم شغال كام شهر قبل ما تقفله.", "Gmail و googlemail.com نفس الصندوق."],
    ["Moving to another email provider", "1. Turn on **forwarding** from old to new.\n2. Use the new service's **Import** (mail, contacts, calendar). Proton has Easy Switch.\n3. Update your address on important accounts gradually.\n4. Keep the old one open a few months before closing it.", "gmail.com and googlemail.com are the same inbox."]),
  C('mail-thunderbird', 'b',
    ["Thunderbird: برنامج إيميل ببلاش وقوي", "- كذا حساب (Gmail وOutlook ودومينك) وتقويم وجهات اتصال ومهام.\n- مساحة على قد هاردك، ومن غير إعلانات الويب ميل.\n- تشفير OpenPGP مدمج.\n- المجموعات: استخدم **Mailing lists** مش دفاتر عناوين منفصلة.\n- بديل كويس لتطبيق Mail & Calendar القديم في ويندوز.", "لو بتستخدم IMAP، اختار «Do not delete on server» عشان الرسايل تفضل على السيرفر."],
    ["Thunderbird: a free, powerful mail program", "- Several accounts (Gmail, Outlook, your domain) plus calendar, contacts and tasks.\n- Storage limited only by your disk, without webmail ads.\n- Built-in OpenPGP encryption.\n- Groups: use **Mailing lists**, not separate address books.\n- A good replacement for Windows' old Mail & Calendar.", "With IMAP, choose «Do not delete on server» so mail stays on the server."]),
  C('mail-outlook-versions', 'b',
    ["أوتلوك: أنهي واحد؟", "- **Classic Outlook**: برنامج الأوفيس (Microsoft 365).\n- **New Outlook for Windows**: المجاني اللي بدل Mail & Calendar.\n- **Outlook.com**: الويب (Hotmail زمان).\n- **Outlook mobile**.\n\nممكن يشتغلوا مع بعض. اختصارات النسخة الويب غير الديسكتوب؛ وحّدهم من `Settings > General > Accessibility`.", "Outlook: `Ctrl+Q` مقروء، `Ctrl+U` مش مقروء."],
    ["Outlook: which one?", "- **Classic Outlook**: the Office program (Microsoft 365).\n- **New Outlook for Windows**: the free one that replaced Mail & Calendar.\n- **Outlook.com**: the web version (formerly Hotmail).\n- **Outlook mobile**.\n\nThey can coexist. Web and desktop shortcuts differ; align them in Settings > General > Accessibility.", "Outlook: `Ctrl+Q` mark read, `Ctrl+U` mark unread."]),
  C('mail-outlook-tricks', 'i',
    ["حيل أوتلوك", "- إيميلات «اختفت» بعد سحب وإفلات: اتحولت لملفات `.msg` على الديسكتوب أو فولدر؛ اسحبها تاني.\n- مش عارف تبعت لجروب: وسّع الجروب (+) لعناوين.\n- **Rules**: «Message body includes» > Mark importance High.\n- اكتب `@الاسم` في الرسالة يزوّده في المستلمين.\n- خلي «Mark as read» بعد 30 ثانية لو بتستخدم غير المقروء كتذكير.", "شباك الرسايل بقى صغير جدًا: Win+R > `outlook.exe /cleanviews`."],
    ["Outlook tricks", "- Emails «vanished» after drag and drop: they became `.msg` files on the desktop or a folder; drag them back.\n- Cannot send to a group: expand it (+) into addresses.\n- **Rules**: «Message body includes» > Mark importance High.\n- Type `@name` in the body to add a recipient.\n- Set «mark as read» after 30 seconds if you use unread as a reminder.", "Message windows tiny: Win+R > `outlook.exe /cleanviews`."]),
  C('mail-inspect', 'i',
    ["افحص إيميل مشكوك فيه", "**Show original** (Gmail) أو **View source**:\n- **SPF / DKIM / DMARC**: لو `fail` يبقى الراسل مزيّف.\n- سطور `Received: from` بتوريك جه منين فعلًا.\n- الراسل الظاهر ممكن يتزيّف، فده بيكشف.", "خدعة: سجّل الجهات الحقيقية (البنك) في الكونتاكتس بعلامة في الاسم؛ أي رسالة من غير العلامة تشك فيها."],
    ["Inspect a suspicious email", "**Show original** (Gmail) or **View source**:\n- **SPF / DKIM / DMARC**: `fail` means the sender is forged.\n- `Received: from` lines show where it really came from.\n- The displayed sender can be faked; this reveals it.", "Trick: save genuine senders (your bank) in contacts with a marker in the name; doubt any message without it."]),
  C('mail-notes-drafts', 'b',
    ["الإيميل كمكان للملاحظات", "- ابعت لنفسك، أو احفظ **Draft** موضوعه عنوان الملاحظة؛ بيظهر على كل أجهزتك.\n- في Gmail حط label «ملاحظات» عشان ما تختلطش بالمسودات الحقيقية.\n- ارفق ملفات صغيرة تحتاجها في أي مكان.", "التقويم في Outlook يعرض تقويم جوجل: `Google Calendar > Integrate calendar > Secret address in iCal > Outlook > Add from Internet`. خلّي العنوان ده سري."],
    ["Email as a notes app", "- Mail yourself, or keep a **Draft** whose subject is the note title; it appears on all your devices.\n- In Gmail give them a «Notes» label so they do not mix with real drafts.\n- Attach small files you need everywhere.", "Show Google Calendar in Outlook: Google Calendar > Integrate calendar > Secret address in iCal > Outlook > Add from Internet. Keep that address private."]),
  C('mail-old-server', 'a',
    ["حساب إيميل قديم مش بيتصل في برنامج الإيميل", "ضيفه يدوي (Other / Manual setup) بإعدادات IMAP وSMTP من صفحة دعم الشركة: السيرفر والبورت والتشفير (SSL/TLS).\n\nGmail مثلًا: إرسال `smtp.gmail.com` بورت 465 SSL.", "حسابات بتستخدم «App password» لو مفيش دعم للدخول الحديث."],
    ["An old email account will not connect in a mail app", "Add it manually (Other / Manual setup) with IMAP and SMTP settings from the provider's support page: server, port and encryption (SSL/TLS).\n\nGmail, for example: sending via `smtp.gmail.com`, port 465, SSL.", "Some accounts need an «app password» when modern sign-in is not supported."]),
  C('mail-gmail-misc', 'b',
    ["حاجات صغيرة في Gmail", "- **Stars**: من الإعدادات زوّد ألوان ورموز، ودوس كذا مرة تغيّر الأولوية.\n- اسحب **Spam** من «More» للقائمة الرئيسية.\n- امسح كل حاجة: All Mail > تحديد > «Select all conversations» > Delete، وفضّي الـ Bin.\n- **Copy code** على الموبايل بينسخ أكواد التحقق بضغطة.\n- اقفل «smart features» لو مش عايز جوجل يحلل رسايلك.", "مساحة جوجل اتملت؟ ابدأ بـ `larger:10M` ورسايل الـ Promotions القديمة."],
    ["Small Gmail features", "- **Stars**: add colours and symbols in settings, and click repeatedly to cycle priority.\n- Drag **Spam** from «More» into the main list.\n- Delete everything: All Mail > select > «Select all conversations» > Delete, then empty the Bin.\n- On mobile, **Copy code** copies verification codes in one tap.\n- Turn off «smart features» if you do not want Google analysing your mail.", "Google storage full? Start with `larger:10M` and old Promotions."])
] });
})();
