// Section of tips.html: a glossary of computer terms (type cards, kind t so every term is in the site search).
// Definitions are written for this site in plain words.
(function(){
function T(id, cat, term, ar, ardef, endef){
  return { id: 'tm-' + id, cat: cat, t: { ar: term + ' — ' + ar, en: term }, body: { ar: ardef, en: endef } };
}
SECTIONS.add({
  page: 'tips', id: 'terms', order: 4, kind: 't', type: 'cards',
  title: { ar: 'قاموس مصطلحات الكمبيوتر', en: 'Glossary of computer terms' },
  nav: { ar: 'القاموس', en: 'Glossary' },
  desc: {
    ar: 'كل مصطلح بشرح قصير بكلام بسيط. ابحث بالاختصار (زي `SSD` أو `VPN`) أو بالعربي.',
    en: 'Each term with a short plain-language explanation. Search by abbreviation (like `SSD` or `VPN`) or by meaning.'
  },
  searchHint: { ar: 'مثلًا: SSD، DNS، رامات…', en: 'e.g. SSD, DNS, RAM…' },
  cats: [
    { id: 'hw', t: { ar: 'الأجهزة والمكونات', en: 'Hardware' } },
    { id: 'net', t: { ar: 'الشبكات والنت', en: 'Networks' } },
    { id: 'sec', t: { ar: 'الأمان والخصوصية', en: 'Security and privacy' } },
    { id: 'files', t: { ar: 'الملفات والصيغ', en: 'Files and formats' } },
    { id: 'av', t: { ar: 'الشاشة والصوت والصورة', en: 'Screen, sound and image' } },
    { id: 'soft', t: { ar: 'البرامج والأنظمة', en: 'Software and systems' } }
  ],
  items: [
    // ---------- hardware ----------
    T('cpu', 'hw', 'CPU', 'البروسيسور', 'المعالج: «مخ» الجهاز اللي بينفّذ الأوامر. سرعته بالجيجاهرتز وعدد الأنوية (cores) بيحددوا قوته.', 'The processor: the «brain» that runs instructions. Its speed (GHz) and number of cores set its power.'),
    T('cores', 'hw', 'Cores', 'الأنوية', 'وحدات تشغيل جوه البروسيسور؛ كل نواة تشتغل على مهمة. أنوية الأداء (P) للشغل التقيل، وأنوية الكفاءة (E) لتوفير البطارية.', 'Processing units inside a CPU, each handling work. Performance (P) cores for heavy tasks, efficiency (E) cores to save battery.'),
    T('ram', 'hw', 'RAM', 'الذاكرة العشوائية (الرامات)', 'مساحة الشغل المؤقتة وانت الجهاز شغال؛ بتتمسح لما يتقفل. رامات أكتر = برامج وتابات أكتر مع بعض من غير بطء.', 'The temporary working space while the PC is on; cleared at shutdown. More RAM = more programs and tabs at once without slowing.'),
    T('ddr', 'hw', 'DDR4 / DDR5', 'أجيال الرامات', 'أجيال شرايح الرامات؛ كل جيل أسرع، ومش بيركب مكان التاني. لازم يناسب الماذربورد.', 'Generations of RAM; each is faster and they are not interchangeable. Must match the motherboard.'),
    T('storage', 'hw', 'Storage', 'التخزين', 'المكان اللي بتتحفظ فيه الملفات والبرامج دايمًا (SSD أو هارد). مختلف عن الرامات.', 'Where files and programs are kept permanently (SSD or hard disk). Different from RAM.'),
    T('ssd', 'hw', 'SSD', 'قرص الحالة الصلبة', 'تخزين من غير أجزاء متحركة، أسرع بكتير من الهارد العادي وأهدى وأقل استهلاك. أكبر تسريع لأي جهاز قديم.', 'Storage with no moving parts, far faster than a hard disk, quieter and more efficient. The biggest upgrade for an old PC.'),
    T('hdd', 'hw', 'HDD', 'الهارد ديسك العادي', 'تخزين بأسطوانات بتلف؛ أرخص للمساحات الكبيرة وأبطأ، وأحسن من SSD للأرشيف المتساب سنين.', 'Storage on spinning platters; cheaper for big capacities and slower, better than SSDs for archives left unpowered for years.'),
    T('nvme', 'hw', 'NVMe', 'إن في إم إي', 'طريقة توصيل SSD مباشرة بخطوط PCIe؛ أسرع بكتير من SSD الـ SATA.', 'A way of connecting an SSD directly over PCIe lanes; much faster than a SATA SSD.'),
    T('m2', 'hw', 'M.2', 'إم دوت 2', 'شكل SSD صغير زي الشريحة بيتركب في الماذربورد. ليه أطوال (2280، 2242) ونوعين (NVMe وSATA) لازم تطابقهم.', 'A small stick-shaped SSD that plugs into the motherboard. Comes in lengths (2280, 2242) and two types (NVMe and SATA) that must match.'),
    T('sata', 'hw', 'SATA', 'ساتا', 'التوصيلة القديمة للهاردات والـ SSD مقاس 2.5 بوصة؛ أبطأ من NVMe.', 'The older connection for hard disks and 2.5-inch SSDs; slower than NVMe.'),
    T('emmc', 'hw', 'eMMC', 'تخزين ملحوم رخيص', 'تخزين بطيء وصغير ملحوم في الأجهزة الرخيصة؛ مش بيتغيّر. ابعد عنه لويندوز 11.', 'Slow, small storage soldered into cheap devices; it cannot be upgraded. Avoid it for Windows 11.'),
    T('gpu', 'hw', 'GPU', 'كارت الشاشة', 'معالج الرسوميات: للألعاب والفيديو والذكاء الاصطناعي. ممكن يكون مدمج في البروسيسور (iGPU) أو كارت منفصل.', 'The graphics processor: for games, video and AI. Either built into the CPU (iGPU) or a separate card.'),
    T('npu', 'hw', 'NPU', 'معالج الذكاء الاصطناعي', 'شريحة مخصوصة لمهام الذكاء الاصطناعي على الجهاز (تغبيش الخلفية، الترجمة) بكهربا قليلة. قوتها بالـ TOPS.', 'A chip for on-device AI tasks (background blur, translation) with little power. Measured in TOPS.'),
    T('motherboard', 'hw', 'Motherboard', 'الماذربورد', 'اللوحة الأم اللي كل القطع بتتركب فيها؛ مقاساتها ATX وMicroATX وMini-ITX، والمقاس بيحدد عدد الفتحات.', 'The main board everything plugs into; sizes ATX, MicroATX and Mini-ITX, which set how many slots it has.'),
    T('chipset', 'hw', 'Chipset', 'الشيبست', 'شرايح على الماذربورد بتنظم الكلام بين البروسيسور والأجهزة (USB، تخزين). ليه تعريفات من موقع الشركة.', 'Chips on the motherboard that manage traffic between the CPU and devices (USB, storage). It has drivers from the maker.'),
    T('pcie', 'hw', 'PCIe', 'بي سي آي إكسبرس', 'الفتحات والخطوط السريعة اللي بيتركب فيها كارت الشاشة والـ NVMe وكروت الواي فاي.', 'The fast slots and lanes used by graphics cards, NVMe drives and Wi-Fi cards.'),
    T('psu', 'hw', 'PSU', 'باور سبلاي', 'وحدة الكهربا اللي بتغذي الكمبيوتر المكتبي؛ موديولار يعني الكابلات بتتشال.', 'The unit that powers a desktop PC; modular means the cables detach.'),
    T('bios', 'hw', 'BIOS / UEFI', 'برنامج الإقلاع', 'البرنامج اللي بيشتغل قبل الويندوز ويجهّز الأجهزة ويختار تقلع منين. UEFI هو النسخة الحديثة. بتدخله بـ Del أو F2.', 'The firmware that runs before Windows, prepares the hardware and picks the boot drive. UEFI is the modern version. Enter with Del or F2.'),
    T('cmos', 'hw', 'CMOS battery', 'بطارية الماذربورد', 'بطارية صغيرة (غالبًا CR2032) بتحفظ الساعة وإعدادات الـ BIOS. لما تخلص الساعة بترجع غلط.', 'A small battery (usually CR2032) that keeps the clock and BIOS settings. When it dies the clock resets.'),
    T('firmware', 'hw', 'Firmware', 'البرنامج الداخلي', 'برنامج جوه الجهاز نفسه (راوتر، طابعة، SSD، BIOS)؛ تحديثه بيصلّح مشاكل وثغرات.', 'Software built into a device (router, printer, SSD, BIOS); updating it fixes bugs and security holes.'),
    T('tpm', 'hw', 'TPM', 'شريحة الأمان', 'شريحة (أو جزء من البروسيسور) بتحفظ مفاتيح التشفير وبيانات الدخول بأمان. ويندوز 11 محتاج TPM 2.0.', 'A chip (or part of the CPU) that stores encryption keys and sign-in secrets safely. Windows 11 needs TPM 2.0.'),
    T('usbc', 'hw', 'USB-C', 'يو إس بي سي', 'شكل الفيشة البيضاوي اللي بيدخل بأي اتجاه. ممكن يشيل بيانات وشحن وشاشة، بس كل بورت قدراته مختلفة.', 'The oval reversible plug. It can carry data, power and video, but each port\'s abilities differ.'),
    T('usbpd', 'hw', 'USB PD', 'شحن سريع قياسي', 'معيار الشحن السريع عن طريق USB-C؛ الشاحن والجهاز بيتفقوا على أعلى سرعة يقدروا عليها.', 'The fast-charging standard over USB-C; charger and device agree the highest speed both support.'),
    T('gan', 'hw', 'GaN', 'شاحن جان', 'مادة في الشواحن الحديثة بتخليها أصغر وأبرد بنفس القوة.', 'A material in modern chargers that makes them smaller and cooler at the same power.'),
    T('mah', 'hw', 'mAh / Wh', 'سعة البطارية', 'mAh كمية الشحن، وWh الطاقة (mAh × الفولت). شركات الطيران بتحسب الـ Wh.', 'mAh is charge capacity; Wh is energy (mAh × volts). Airlines go by Wh.'),
    T('liion', 'hw', 'Lithium-ion', 'بطارية ليثيوم', 'نوع بطاريات الموبايلات واللابتوبات؛ بتتعب مع الحرارة والشحن الكامل الدايم، وخطر لو اتنفخت أو اتكسرت.', 'The battery type in phones and laptops; it ages with heat and constant full charges, and is dangerous if swollen or damaged.'),
    T('nas', 'hw', 'NAS', 'تخزين على الشبكة', 'جهاز هاردات متوصل بالراوتر، كل أجهزة البيت تحفظ عليه وتعمل نسخ احتياطية.', 'A box of drives on your router where every home device can store files and back up.'),
    T('raid', 'hw', 'RAID', 'رِيد', 'طريقة لتجميع كذا هارد. RAID 1 مرايا (لو واحد باظ التاني شغال)، RAID 0 سرعة من غير أمان. مش بديل عن النسخ الاحتياطي.', 'Combining several drives. RAID 1 mirrors (one fails, the other works); RAID 0 is speed with no safety. Not a backup.'),
    T('enclosure', 'hw', 'Enclosure', 'علبة هارد خارجية', 'علبة بتحوّل هارد أو SSD داخلي لخارجي بـ USB. لازم تطابق نوع الدرايف.', 'A case that turns an internal drive into a USB external one. Must match the drive type.'),
    T('kvm', 'hw', 'KVM switch', 'مفتاح KVM', 'زرار يشغّل جهازين على نفس الكيبورد والشاشة والماوس.', 'A switch that shares one keyboard, screen and mouse between two computers.'),
    T('dock', 'hw', 'Dock', 'محطة توصيل', 'وحدة بتتوصل باللابتوب بكابل واحد وتديله شاشات وإيثرنت وUSB وشحن.', 'A unit that connects to a laptop by one cable and adds screens, Ethernet, USB and charging.'),
    T('heatsink', 'hw', 'Heatsink', 'المشتت الحراري', 'قطعة معدن بزعانف بتسحب الحرارة من البروسيسور أو الـ SSD؛ التراب عليها = سخونة.', 'A finned metal block that draws heat from the CPU or SSD; dust on it = overheating.'),
    T('benchmark', 'hw', 'Benchmark', 'اختبار أداء', 'برنامج بيقيس سرعة الجهاز أو جزء منه برقم تقارن بيه.', 'A program that measures a device or part\'s speed as a comparable score.'),
    T('tbw', 'hw', 'TBW', 'عمر الكتابة للـ SSD', 'كمية البيانات اللي الشركة بتضمن الـ SSD يكتبها في عمره؛ الاستخدام العادي بياخد سنين.', 'The total data a maker guarantees an SSD can write; normal use takes years to reach it.'),
    T('smart', 'hw', 'S.M.A.R.T.', 'تقرير صحة الدرايف', 'معلومات الهارد أو الـ SSD عن صحته (أخطاء، ساعات تشغيل)؛ CrystalDiskInfo بيقراها.', 'A drive\'s self-reported health data (errors, power-on hours); CrystalDiskInfo reads it.'),
    T('nfc', 'hw', 'NFC', 'الاتصال قريب المدى', 'اتصال لاسلكي على مسافة سنتيمترات؛ الدفع بالموبايل والكروت اللاسلكية.', 'Wireless contact over a few centimetres; used for phone payments and contactless cards.'),
    T('imei', 'hw', 'IMEI', 'رقم الموبايل التسلسلي', 'رقم مميز لكل موبايل؛ بتطلبه بـ `*#06#` ومهم لو اتسرق.', 'A unique number for every phone; dial `*#06#` to see it, important if stolen.'),
    T('esim', 'hw', 'eSIM', 'شريحة رقمية', 'شريحة جوه الموبايل بتتنزل بكود QR بدل الشريحة البلاستيك.', 'A built-in SIM installed by QR code instead of a plastic card.'),
    T('ip-rating', 'hw', 'IP67 / IP68', 'مقاومة المية والتراب', 'الرقم الأول للتراب والتاني للمية؛ IP68 يستحمل الغطس لفترة. مش ضمان ضد كل حاجة.', 'The first digit is dust, the second water; IP68 survives immersion for a while. Not a guarantee against everything.'),
    // ---------- networks ----------
    T('ip', 'net', 'IP address', 'عنوان الآي بي', 'عنوان الجهاز على الشبكة. فيه عنوان محلي في البيت (192.168…) وعنوان عام شايفه النت.', 'A device\'s address on a network. There is a local one at home (192.168…) and a public one the internet sees.'),
    T('dns', 'net', 'DNS', 'دليل أسماء المواقع', 'الخدمة اللي بتحوّل اسم الموقع لعنوان IP. تغييرها ممكن يسرّع أو يمنع المواقع الخبيثة.', 'The service that turns a site name into an IP address. Changing it can speed up lookups or block bad sites.'),
    T('dhcp', 'net', 'DHCP', 'توزيع العناوين', 'خدمة في الراوتر بتدّي كل جهاز عنوان IP تلقائي.', 'A router service that gives each device an IP address automatically.'),
    T('mac', 'net', 'MAC address', 'عنوان الكارت', 'رقم ثابت لكل كارت شبكة؛ بتستخدمه لحجز IP أو منع جهاز من الراوتر.', 'A fixed number for each network adapter; used to reserve an IP or block a device on the router.'),
    T('router', 'net', 'Router', 'الراوتر', 'الجهاز اللي بيوصل بيتك بالنت ويوزّعه على الأجهزة بالواي فاي والكابل.', 'The box that connects your home to the internet and shares it by Wi-Fi and cable.'),
    T('ssid', 'net', 'SSID', 'اسم الواي فاي', 'الاسم اللي الشبكة بتظهر بيه في قايمة الواي فاي.', 'The name a network shows in the Wi-Fi list.'),
    T('wifi-gen', 'net', 'Wi-Fi 5 / 6 / 6E / 7', 'أجيال الواي فاي', 'أجيال الواي فاي؛ كل جيل أسرع وبيتحمل أجهزة أكتر. 6E و7 بيضيفوا موجة 6 جيجاهرتز. القديم بيشتغل مع الجديد.', 'Wi-Fi generations; each is faster and handles more devices. 6E and 7 add the 6 GHz band. Old and new work together.'),
    T('bands', 'net', 'Dual-band', 'موجتين', 'راوتر بيبث على 2.4 جيجاهرتز (مدى أبعد) و5 جيجاهرتز (أسرع).', 'A router broadcasting on 2.4 GHz (longer range) and 5 GHz (faster).'),
    T('mesh', 'net', 'Mesh', 'شبكة ميش', 'كذا وحدة واي فاي بتتكلم مع بعض وتغطي البيت كله باسم شبكة واحد.', 'Several Wi-Fi units working together to cover the whole home under one network name.'),
    T('powerline', 'net', 'Powerline', 'نت عبر الكهربا', 'محوّلات بتنقل النت في أسلاك الكهربا لأوضة بعيدة.', 'Adapters that carry the network through mains wiring to a distant room.'),
    T('ethernet', 'net', 'Ethernet', 'كابل الشبكة', 'التوصيل بالكابل؛ أثبت وأسرع من الواي فاي. Cat5e وCat6 كفاية للبيت.', 'A wired connection; steadier and faster than Wi-Fi. Cat5e or Cat6 is enough at home.'),
    T('lan', 'net', 'LAN', 'الشبكة المحلية', 'الأجهزة المتوصلة ببعض في بيت أو مكتب.', 'Devices connected together in one home or office.'),
    T('bandwidth', 'net', 'Bandwidth', 'سعة الخط', 'أقصى كمية بيانات تعدّي في الثانية (ميجابت/ث).', 'The most data that can pass per second (Mbps).'),
    T('latency', 'net', 'Latency / Ping', 'زمن الاستجابة', 'الوقت اللي البيانات بتاخده تروح وترجع بالمللي ثانية؛ أقل = أحسن للمكالمات والألعاب.', 'The round-trip time for data, in milliseconds; lower is better for calls and games.'),
    T('jitter', 'net', 'Jitter', 'التذبذب', 'تغيّر زمن الاستجابة من لحظة للتانية؛ بيقطّع الصوت في المكالمات.', 'How much latency varies moment to moment; it breaks up call audio.'),
    T('fttp', 'net', 'FTTP / FTTC', 'الفايبر', 'FTTP فايبر لحد البيت (الأسرع)، FTTC فايبر لحد الكابينة والباقي نحاس.', 'FTTP is fibre to the home (fastest); FTTC is fibre to the street cabinet, then copper.'),
    T('ont', 'net', 'ONT', 'جهاز الفايبر', 'العلبة اللي بيدخل فيها الفايبر في البيت ويتوصل منها الراوتر.', 'The box where fibre enters the home; the router connects to it.'),
    T('vpn', 'net', 'VPN', 'الشبكة الخاصة الافتراضية', 'نفق مشفّر بين جهازك وسيرفر؛ بيخفي الـ IP عن المواقع ويحمي على الشبكات العامة.', 'An encrypted tunnel between your device and a server; it hides your IP from sites and protects you on public networks.'),
    T('proxy', 'net', 'Proxy', 'بروكسي', 'جهاز وسيط بين جهازك والنت؛ زي VPN بس غالبًا للمتصفح بس ومن غير تشفير كامل.', 'A go-between for your traffic; like a VPN but often browser-only and without full encryption.'),
    T('kill-switch', 'net', 'Kill switch', 'مفتاح القطع', 'ميزة في الـ VPN بتقطع النت لو الـ VPN وقع عشان ما يتكشفش.', 'A VPN feature that cuts the internet if the VPN drops, so you are not exposed.'),
    T('wireguard', 'net', 'WireGuard / OpenVPN', 'بروتوكولات VPN', 'طرق تشغيل الـ VPN؛ WireGuard أسرع وأحدث، OpenVPN مجرّب ومتوافق مع كل حاجة.', 'Ways a VPN runs; WireGuard is newer and faster, OpenVPN well-proven and widely compatible.'),
    T('mbps', 'net', 'Mbps vs MB/s', 'ميجابت وميجابايت', 'سرعة النت بالميجابت (Mbps)؛ التحميل بيظهر بالميجابايت (MB/s). البايت = 8 بت، فـ 100 Mbps ≈ 12.5 MB/s.', 'Internet speed is in megabits (Mbps); downloads show megabytes (MB/s). A byte is 8 bits, so 100 Mbps ≈ 12.5 MB/s.'),
    T('hotspot', 'net', 'Hotspot', 'نقطة اتصال', 'جهاز (موبايل مثلًا) بيشارك النت بتاعه بالواي فاي.', 'A device (a phone, say) sharing its internet over Wi-Fi.'),
    T('wps', 'net', 'WPS', 'زرار التوصيل السريع', 'زرار يوصل الأجهزة من غير باسورد؛ مريح بس فيه ثغرات، الأحسن تقفله.', 'A button that connects devices without a password; handy but weak, best turned off.'),
    T('wpa', 'net', 'WPA2 / WPA3', 'تشفير الواي فاي', 'تشفير شبكة الواي فاي؛ WPA3 الأحدث والأقوى. ما تستخدمش WEP.', 'Wi-Fi encryption; WPA3 is newest and strongest. Never use WEP.'),
    T('port', 'net', 'Port', 'بورت', 'باب رقمي على الجهاز لخدمة معيّنة؛ فتح بورتات في الراوتر خطر لو مش فاهم.', 'A numbered doorway on a device for a service; opening router ports is risky unless you understand it.'),
    T('nat', 'net', 'Double NAT', 'راوترين ورا بعض', 'لما يكون فيه راوتر جوه راوتر؛ بيبوّظ أحيانًا الطابعات والبث.', 'A router behind another router; sometimes breaks printers and casting.'),
    T('smb', 'net', 'SMB', 'مشاركة الملفات', 'طريقة ويندوز لمشاركة الفولدرات والطابعات على الشبكة. النسخة القديمة SMB1 خطرة.', 'Windows\' way of sharing folders and printers on a network. The old SMB1 is insecure.'),
    T('voip', 'net', 'VoIP', 'مكالمات عبر النت', 'مكالمات صوتية بتعدّي من الإنترنت؛ زي واتساب والتليفون الأرضي الرقمي.', 'Voice calls carried over the internet, like WhatsApp and digital landlines.'),
    T('rcs', 'net', 'RCS', 'الرسايل الحديثة', 'بديل SMS فيه مؤشر كتابة وصور بجودة أعلى وشغال بالنت.', 'The successor to SMS with typing indicators and better photos, over data.'),
    T('mvno', 'net', 'MVNO', 'شركة اتصالات افتراضية', 'شركة بتبيع خطوط على شبكة شركة تانية، غالبًا أرخص.', 'A carrier selling plans on another company\'s network, often cheaper.'),
    T('5g', 'net', '4G / 5G', 'أجيال شبكات الموبايل', 'أجيال نت الموبايل؛ 5G أسرع وأقل تأخير لو التغطية كويسة.', 'Mobile-data generations; 5G is faster with lower delay where coverage is good.'),
    T('p2p', 'net', 'P2P', 'من جهاز لجهاز', 'نقل مباشر بين الأجهزة من غير سيرفر في النص (زي LocalSend والتورنت).', 'Direct transfer between devices with no central server (like LocalSend and torrents).'),
    T('ftp', 'net', 'FTP', 'نقل الملفات', 'طريقة قديمة لرفع وتنزيل ملفات من سيرفر؛ الآمن منها SFTP.', 'An old way to upload and download files to a server; the secure form is SFTP.'),
    T('imap', 'net', 'IMAP / POP3', 'استلام الإيميل', 'IMAP بيخلي الإيميل على السيرفر ومتزامن على كل الأجهزة؛ POP3 بينزّله لجهاز واحد.', 'IMAP keeps mail on the server, synced across devices; POP3 downloads it to one device.'),
    // ---------- security ----------
    T('2fa', 'sec', '2FA', 'التحقق بخطوتين', 'طبقة تانية بعد الباسورد (كود أو بصمة أو مفتاح)؛ الباسورد المسروق لوحده ما يكفيش.', 'A second layer after the password (a code, fingerprint or key); a stolen password alone is not enough.'),
    T('passkey', 'sec', 'Passkey', 'مفتاح المرور', 'دخول من غير باسورد بالبصمة أو الوش أو PIN؛ مربوط بالموقع الحقيقي فما ينفعش يتسرق بالخداع.', 'Sign-in without a password, by fingerprint, face or PIN; bound to the real site so it cannot be phished.'),
    T('passphrase', 'sec', 'Passphrase', 'عبارة مرور', 'باسورد طويل من كذا كلمة؛ سهل تفتكره وصعب يتكسر.', 'A long password made of several words; easy to remember, hard to crack.'),
    T('authenticator', 'sec', 'Authenticator', 'تطبيق المصادقة', 'تطبيق بيطلع كود جديد كل 30 ثانية للتحقق بخطوتين؛ أأمن من الـ SMS.', 'An app producing a new code every 30 seconds for 2FA; safer than SMS.'),
    T('phishing', 'sec', 'Phishing', 'التصيّد', 'رسايل أو مواقع بتتنكر في جهة موثوقة عشان تسرق باسوردك أو فلوسك.', 'Messages or sites posing as a trusted organisation to steal your password or money.'),
    T('smishing', 'sec', 'Smishing / Vishing / Quishing', 'تصيّد بالرسايل والمكالمات والـ QR', 'نفس التصيّد بس بالرسايل النصية (Smishing) أو المكالمات (Vishing) أو أكواد QR (Quishing).', 'Phishing by text message (smishing), phone call (vishing) or QR code (quishing).'),
    T('spoofing', 'sec', 'Spoofing', 'التزييف', 'تزييف اسم الراسل أو رقم المتصل عشان يبان إنه جهة حقيقية.', 'Faking a sender name or caller number to look like a real organisation.'),
    T('malware', 'sec', 'Malware', 'برنامج خبيث', 'أي برنامج معمول عشان يضر: فيروسات، تجسس، سرقة باسوردات، فدية.', 'Any software built to harm: viruses, spyware, password stealers, ransomware.'),
    T('ransomware', 'sec', 'Ransomware', 'فيروس الفدية', 'برنامج بيشفّر ملفاتك ويطلب فلوس؛ النسخة الاحتياطية المفصولة هي العلاج.', 'Malware that encrypts your files and demands payment; a disconnected backup is the cure.'),
    T('pup', 'sec', 'PUP', 'برنامج غير مرغوب', 'برنامج اتثبت مع برنامج تاني (تولبار، «منظّف») مش خبيث بالظبط بس مزعج.', 'A program bundled with another (a toolbar, a «cleaner») that is not quite malware but unwanted.'),
    T('scareware', 'sec', 'Scareware', 'برامج التخويف', 'رسايل أو صفحات بتقول جهازك مصاب عشان تدفع أو تنزّل حاجة.', 'Pop-ups or pages claiming your device is infected so you pay or install something.'),
    T('botnet', 'sec', 'Botnet', 'شبكة أجهزة مخترقة', 'أجهزة كتير مصابة بيتحكم فيها مجرم يبعت منها سبام أو هجمات.', 'Many infected devices controlled by a criminal to send spam or attacks.'),
    T('ddos', 'sec', 'DDoS', 'هجوم إغراق', 'إغراق موقع بطلبات من آلاف الأجهزة لحد ما يقع.', 'Flooding a site with requests from thousands of devices until it falls over.'),
    T('zero-day', 'sec', 'Zero-day', 'ثغرة جديدة', 'ثغرة بيستغلوها قبل ما الشركة تلحق تصلّحها؛ عشان كده التحديثات مهمة.', 'A flaw exploited before the maker has fixed it; that is why updates matter.'),
    T('encryption', 'sec', 'Encryption', 'التشفير', 'تحويل البيانات لشكل ما يتقراش من غير مفتاح.', 'Turning data into a form unreadable without a key.'),
    T('e2ee', 'sec', 'End-to-end encryption', 'التشفير من الطرفين', 'بس انت واللي بتكلمه تقدروا تقروا؛ حتى الشركة نفسها لأ.', 'Only you and the other person can read it; not even the company.'),
    T('aes', 'sec', 'AES-256', 'تشفير AES', 'معيار تشفير قوي جدًا بتستخدمه برامج الحماية والأرشيف.', 'A very strong encryption standard used by security and archive tools.'),
    T('hash', 'sec', 'Hash', 'البصمة الرقمية للملف', 'رقم بيتحسب من محتوى الملف؛ لو حرف اتغيّر الرقم بيتغيّر. بيستخدم للتأكد من الملفات والباسوردات.', 'A number calculated from a file\'s content; change one letter and it changes. Used to verify files and passwords.'),
    T('bruteforce', 'sec', 'Brute-force', 'هجوم التخمين', 'تجربة كل الاحتمالات لحد ما الباسورد يتفتح؛ الطول بيخليه مستحيل عمليًا.', 'Trying every combination until a password works; length makes it impractical.'),
    T('credential-stuffing', 'sec', 'Credential stuffing', 'تجربة الباسوردات المسربة', 'استخدام إيميل وباسورد اتسربوا من موقع لدخول مواقع تانية؛ عشان كده باسورد مختلف لكل موقع.', 'Using an email and password leaked from one site to log into others; hence a unique password per site.'),
    T('sim-swap', 'sec', 'SIM swap', 'نقل الرقم', 'نصّاب بيقنع شركة الاتصالات تنقل رقمك لشريحته عشان ياخد أكوادك.', 'A scammer persuades your carrier to move your number to their SIM to get your codes.'),
    T('deepfake', 'sec', 'Deepfake', 'التزييف العميق', 'صورة أو صوت أو فيديو معمول بالذكاء الاصطناعي لشخص حقيقي بيقول حاجة ما قالهاش.', 'An AI-made image, voice or video of a real person saying something they never said.'),
    T('firewall', 'sec', 'Firewall', 'الجدار الناري', 'برنامج أو جهاز بيتحكم مين يدخل ويخرج من الشبكة.', 'Software or hardware that controls what can enter and leave a network.'),
    T('sandbox', 'sec', 'Sandbox', 'البيئة المعزولة', 'مكان معزول بتشغّل فيه برنامج مشكوك فيه من غير ما يلمس جهازك الحقيقي.', 'An isolated space to run a doubtful program without touching your real system.'),
    T('secure-boot', 'sec', 'Secure Boot', 'الإقلاع الآمن', 'ميزة بتمنع برامج خبيثة تشتغل قبل الويندوز.', 'A feature that stops malware loading before Windows.'),
    T('bitlocker', 'sec', 'BitLocker', 'تشفير الدرايف', 'تشفير ويندوز للهارد؛ لازم تحتفظ بمفتاح الاسترجاع.', 'Windows drive encryption; you must keep the recovery key.'),
    T('recovery-key', 'sec', 'Recovery key', 'مفتاح الاسترجاع', 'كود طويل بيرجّعلك الدخول لو نسيت الباسورد أو اتقفل الجهاز؛ احفظه بعيد عن الجهاز.', 'A long code that restores access if you forget a password or a device locks; keep it away from the device.'),
    T('cookie', 'sec', 'Cookie', 'الكوكي', 'ملف صغير بيحفظه الموقع في المتصفح؛ بيفتكر دخولك وممكن يستخدم في التتبّع.', 'A small file a site saves in your browser; it remembers logins and can be used for tracking.'),
    T('fingerprinting', 'sec', 'Fingerprinting', 'البصمة الرقمية للمتصفح', 'التعرّف عليك من مزيج إعدادات متصفحك وجهازك من غير كوكيز.', 'Recognising you from your browser and device settings without cookies.'),
    T('tracking-pixel', 'sec', 'Tracking pixel', 'بكسل التتبّع', 'صورة صغيرة مخفية في الإيميل بتقول للراسل إنك فتحته.', 'A tiny hidden image in an email that tells the sender you opened it.'),
    T('metadata', 'sec', 'Metadata / EXIF', 'البيانات الوصفية', 'معلومات جوه الملف عن الملف: تاريخ ومكان التصوير ونوع الكاميرا والمؤلف.', 'Information inside a file about the file: date and place taken, camera, author.'),
    T('digital-signature', 'sec', 'Digital signature', 'التوقيع الرقمي', 'إثبات إن البرنامج أو المستند من الجهة اللي بتقول إنها عملته وما اتعدلش.', 'Proof that a program or document comes from who it claims and has not been altered.'),
    T('captcha', 'sec', 'CAPTCHA', 'اختبار «أنا مش روبوت»', 'اختبار يفرّق بين البشر والبرامج؛ عمره ما يطلب تلصق أوامر.', 'A test that tells humans from bots; it never asks you to paste commands.'),
    // ---------- files ----------
    T('extension', 'files', 'File extension', 'امتداد الملف', 'الحروف بعد النقطة في اسم الملف (.pdf، .docx) اللي بتقول نوعه. اظهرها دايمًا.', 'The letters after the dot in a file name (.pdf, .docx) showing its type. Always show them.'),
    T('exe', 'files', 'EXE', 'ملف تنفيذي', 'برنامج بيشتغل لما تفتحه؛ ما تفتحش EXE جالك في إيميل.', 'A program that runs when opened; never open an EXE that arrived by email.'),
    T('zip', 'files', 'ZIP / 7z / RAR', 'ملفات مضغوطة', 'صيغ بتجمع ملفات كتير في ملف أصغر؛ ممكن بباسورد.', 'Formats that pack many files into one smaller file, optionally with a password.'),
    T('iso', 'files', 'ISO', 'صورة قرص', 'ملف فيه نسخة كاملة من أسطوانة؛ بتكتبه على فلاشة عشان تثبّت نظام.', 'A file holding a complete copy of a disc; written to a stick to install a system.'),
    T('pdf', 'files', 'PDF / PDF/A', 'بي دي إف', 'مستند شكله ثابت على أي جهاز. PDF/A نسخة للأرشفة الطويلة.', 'A document that looks the same on any device. PDF/A is the version for long-term archiving.'),
    T('docx', 'files', 'DOCX / XLSX', 'صيغ أوفيس', 'صيغ وورد وإكسيل الحديثة؛ بتتفتح في LibreOffice وGoogle Docs كمان.', 'Modern Word and Excel formats; LibreOffice and Google Docs open them too.'),
    T('odf', 'files', 'ODF', 'الصيغة المفتوحة', 'صيغ مستندات مفتوحة (.odt، .ods) بتاعة LibreOffice.', 'Open document formats (.odt, .ods) used by LibreOffice.'),
    T('csv', 'files', 'CSV', 'جدول نصي', 'جدول في ملف نص، القيم بينها فواصل؛ أي برنامج جداول بيفتحه.', 'A table in a text file with values separated by commas; any spreadsheet opens it.'),
    T('json', 'files', 'JSON', 'جيسون', 'صيغة نصية لتبادل البيانات بين البرامج والمواقع.', 'A text format for exchanging data between programs and websites.'),
    T('markdown', 'files', 'Markdown', 'ماركداون', 'نص عادي بعلامات بسيطة (`#` للعنوان و`**` للبولد) بيتحوّل لتنسيق.', 'Plain text with simple marks (`#` for headings, `**` for bold) that becomes formatting.'),
    T('jpeg', 'files', 'JPEG / PNG', 'صيغ الصور', 'JPEG للصور الفوتوغرافية بحجم صغير (بيضغط مع فقد)، PNG للرسومات والشفافية من غير فقد.', 'JPEG for photos at small sizes (lossy), PNG for graphics and transparency (lossless).'),
    T('heic', 'files', 'HEIC / WebP / AVIF', 'صيغ صور حديثة', 'صيغ أحدث أصغر بنفس الجودة؛ HEIC من الآيفون، WebP وAVIF على النت. برامج قديمة ممكن ما تفتحهاش.', 'Newer formats, smaller at the same quality; HEIC from iPhones, WebP and AVIF on the web. Old programs may not open them.'),
    T('raw', 'files', 'RAW', 'صورة خام', 'صورة الكاميرا من غير معالجة؛ أكبر حجم وأحسن للتعديل.', 'Unprocessed camera data; larger and best for editing.'),
    T('svg', 'files', 'SVG / Vector', 'صور متجهة', 'صور بالأشكال مش بالبكسل؛ بتكبر لأي حجم من غير ما تبوظ.', 'Images made of shapes, not pixels; they scale to any size without breaking up.'),
    T('mp4', 'files', 'MP4 / MKV', 'حاويات الفيديو', 'ملفات بتشيل فيديو وصوت وترجمة. MP4 الأكتر توافق.', 'Files holding video, audio and subtitles. MP4 is the most compatible.'),
    T('codec', 'files', 'Codec', 'الترميز', 'طريقة ضغط الصوت أو الفيديو (H.264، H.265، AV1)؛ لو ناقص الملف ما يشتغلش.', 'How audio or video is compressed (H.264, H.265, AV1); if missing, the file will not play.'),
    T('hevc', 'files', 'H.264 / H.265 (HEVC) / AV1', 'ترميز الفيديو', 'أجيال ضغط الفيديو؛ الأحدث نفس الجودة بنص الحجم تقريبًا بس محتاج أجهزة أحدث.', 'Video compression generations; newer ones give similar quality at about half the size but need newer hardware.'),
    T('mp3', 'files', 'MP3 / AAC / FLAC', 'صيغ الصوت', 'MP3 وAAC مضغوطين مع فقد بسيط وشغالين في كل حتة؛ FLAC من غير فقد.', 'MP3 and AAC are lossy but play everywhere; FLAC is lossless.'),
    T('lossless', 'files', 'Lossless / Lossy', 'من غير فقد / مع فقد', 'الضغط من غير فقد بيحتفظ بكل التفاصيل؛ مع فقد بيشيل حاجات صغيرة عشان الحجم.', 'Lossless compression keeps every detail; lossy drops small details to save space.'),
    T('epub', 'files', 'EPUB', 'كتاب إلكتروني', 'صيغة الكتب الإلكترونية المفتوحة؛ النص بيتظبط على حجم الشاشة.', 'The open ebook format; text reflows to fit the screen.'),
    T('drm', 'files', 'DRM', 'حماية الحقوق الرقمية', 'قفل على الكتب والأفلام والمزيكا بيحدد تشغلها فين.', 'A lock on books, films and music that controls where they can play.'),
    T('gedcom', 'files', 'GEDCOM', 'ملف شجرة العيلة', 'الصيغة القياسية لنقل شجرة العيلة بين البرامج.', 'The standard format for moving family trees between programs.'),
    T('pst', 'files', 'PST', 'ملف أوتلوك', 'ملف بيحفظ إيميلات وتقويم أوتلوك على الجهاز.', 'A file storing Outlook email and calendar on the PC.'),
    T('fat32', 'files', 'FAT32 / exFAT / NTFS', 'أنظمة الملفات', 'طرق تنظيم الملفات على الدرايف. FAT32 حد الملف 4 جيجا، exFAT للفلاشات، NTFS لويندوز.', 'Ways of organising files on a drive. FAT32 limits files to 4 GB, exFAT suits sticks, NTFS is for Windows.'),
    T('partition', 'files', 'Partition', 'قسم من الهارد', 'جزء من الدرايف بيظهر كأنه درايف لوحده (C وD).', 'A section of a drive that appears as its own drive (C and D).'),
    T('cache', 'files', 'Cache', 'الكاش', 'نسخ مؤقتة بتسرّع فتح الحاجات تاني؛ مسحها ممكن يحل مشاكل غريبة.', 'Temporary copies that speed up reopening things; clearing them can fix odd problems.'),
    T('cloud', 'files', 'Cloud storage', 'التخزين السحابي', 'ملفاتك على سيرفرات شركة على النت (Drive، OneDrive)؛ مفيد بس مش لوحده نسخة احتياطية.', 'Your files on a company\'s internet servers (Drive, OneDrive); useful, but not a backup on its own.'),
    T('sync', 'files', 'Sync', 'المزامنة', 'نفس الملفات على كذا جهاز؛ أي تغيير (حتى المسح) بيتنقل للكل.', 'The same files on several devices; any change, even deletion, spreads to all.'),
    T('incremental', 'files', 'Incremental backup', 'نسخ تزايدي', 'نسخة بتحفظ اللي اتغير بس من آخر مرة؛ أسرع وأصغر.', 'A backup saving only what changed since last time; faster and smaller.'),
    T('clone', 'files', 'Clone', 'نسخة طبق الأصل', 'نسخ درايف بالكامل لدرايف تاني تقدر تقلع منه على طول.', 'Copying a whole drive to another you can boot from directly.'),
    T('system-image', 'files', 'System image', 'صورة النظام', 'نسخة من الويندوز والبرامج والإعدادات في ملف ترجّع منه الجهاز كله.', 'A copy of Windows, programs and settings in one file to restore the whole PC.'),
    T('ocr', 'files', 'OCR', 'التعرّف على النصوص', 'تحويل صورة فيها كلام لنص تقدر تنسخه وتدوّر فيه.', 'Turning an image of text into text you can copy and search.'),
    // ---------- screen, sound, image ----------
    T('resolution', 'av', '720p / 1080p / 4K', 'الدقة', 'عدد البكسلات: 1080p هي Full HD، و4K أربع أضعافها.', 'The number of pixels: 1080p is Full HD; 4K has four times as many.'),
    T('refresh', 'av', 'Refresh rate (Hz)', 'معدل التحديث', 'الشاشة بتترسم كام مرة في الثانية؛ 120 هرتز أنعم من 60.', 'How many times per second the screen redraws; 120 Hz feels smoother than 60.'),
    T('ips-oled', 'av', 'IPS / OLED / Mini-LED', 'أنواع الشاشات', 'IPS ألوان كويسة وزوايا واسعة؛ OLED أسود حقيقي وتباين عالي؛ Mini-LED إضاءة أدق وأسطع.', 'IPS has good colour and wide angles; OLED gives true black and high contrast; Mini-LED gives finer, brighter backlighting.'),
    T('hdr', 'av', 'HDR', 'المدى الديناميكي العالي', 'صورة فيها تفاصيل أكتر في الفاتح والغامق مع بعض.', 'Images with more detail in bright and dark areas at the same time.'),
    T('srgb', 'av', 'sRGB / DCI-P3', 'نطاق الألوان', 'كمية الألوان اللي الشاشة تعرضها؛ 100% sRGB كفاية للاستخدام العادي.', 'The range of colours a screen can show; 100% sRGB is enough for everyday use.'),
    T('nits', 'av', 'Nits (cd/m²)', 'السطوع', 'وحدة سطوع الشاشة؛ أعلى = أوضح في الشمس.', 'The unit of screen brightness; higher = more readable in sunlight.'),
    T('burn-in', 'av', 'Burn-in', 'حرق الشاشة', 'صورة ثابتة بتسيب أثر دايم على شاشات OLED.', 'A static image leaving a permanent mark on OLED screens.'),
    T('hdmi', 'av', 'HDMI / DisplayPort', 'كابلات الشاشة', 'توصيلات صورة وصوت للشاشات والتلفزيونات؛ DisplayPort شائع في شاشات الكمبيوتر.', 'Video and audio connections for monitors and TVs; DisplayPort is common on PC monitors.'),
    T('cec', 'av', 'HDMI-CEC', 'تحكّم عبر HDMI', 'ريموت جهاز يتحكم في التلفزيون عن طريق كابل HDMI.', 'One device\'s remote controls the TV over the HDMI cable.'),
    T('arc', 'av', 'ARC / eARC', 'رجوع الصوت عبر HDMI', 'بيبعت صوت التلفزيون للساوند بار بنفس كابل HDMI.', 'Sends TV sound to a soundbar over the same HDMI cable.'),
    T('dac', 'av', 'DAC', 'محوّل الصوت الرقمي', 'قطعة بتحوّل الصوت الرقمي لإشارة للسماعة؛ واحد أحسن = صوت أنضف.', 'Converts digital audio into a signal for headphones; a better one = cleaner sound.'),
    T('bitrate', 'av', 'Bitrate', 'معدل البيانات', 'كمية البيانات لكل ثانية صوت أو فيديو؛ أعلى = جودة وحجم أكبر.', 'Data per second of audio or video; higher = better quality and bigger files.'),
    T('fps', 'av', 'FPS', 'إطارات في الثانية', 'عدد الصور في الثانية في الفيديو أو اللعبة؛ 30 عادي و60 أنعم.', 'Pictures per second in video or games; 30 is normal, 60 smoother.'),
    T('aspect-ratio', 'av', 'Aspect ratio', 'نسبة العرض للطول', 'شكل الصورة أو الشاشة (16:9، 4:3).', 'The shape of an image or screen (16:9, 4:3).'),
    T('dpi', 'av', 'DPI', 'نقطة في البوصة', 'دقة الطباعة أو السكان؛ 300 للمستندات و600 للصور القديمة.', 'Print or scan resolution; 300 for documents, 600 for old photos.'),
    T('stabilisation', 'av', 'Image stabilisation', 'تثبيت الصورة', 'تقليل الاهتزاز في الصور والفيديو، بالعدسة (Optical) أو بالبرنامج.', 'Reducing shake in photos and video, optically or in software.'),
    T('eink', 'av', 'E Ink', 'الحبر الإلكتروني', 'شاشة القارئات اللي شبه الورق؛ مريحة للعين وبطاريتها طويلة.', 'The paper-like screen on e-readers; easy on the eyes with long battery life.'),
    T('bluetooth-le', 'av', 'Bluetooth LE / Auracast', 'بلوتوث منخفض الطاقة', 'نسخة بلوتوث بتستهلك أقل؛ LE Audio وAuracast بيسمحوا بصوت أحسن ولسماعات كتير مع بعض.', 'A low-energy Bluetooth; LE Audio and Auracast bring better sound and many listeners at once.'),
    T('latency-audio', 'av', 'Audio latency', 'تأخير الصوت', 'التأخير بين الصورة والصوت في سماعات البلوتوث؛ وضع الألعاب بيقلله.', 'The delay between picture and sound with Bluetooth headphones; game mode reduces it.'),
    // ---------- software ----------
    T('os', 'soft', 'Operating system', 'نظام التشغيل', 'البرنامج الأساسي اللي بيشغّل الجهاز (ويندوز، أندرويد، iOS، لينكس).', 'The core software that runs the device (Windows, Android, iOS, Linux).'),
    T('32-64', 'soft', '32-bit / 64-bit', '32 و64 بت', 'نوع النظام والبرامج؛ أغلب الأجهزة الحديثة 64 بت، وبرنامج 64 ما يشتغلش على نظام 32.', 'The type of system and programs; most modern PCs are 64-bit, and a 64-bit program cannot run on a 32-bit system.'),
    T('driver', 'soft', 'Driver', 'التعريف', 'برنامج صغير بيعرّف الويندوز إزاي يكلّم جهاز (طابعة، كارت شاشة).', 'A small program that tells Windows how to talk to a device (printer, graphics card).'),
    T('update', 'soft', 'Feature / security update', 'تحديث مزايا / أمان', 'تحديث المزايا بيضيف حاجات جديدة؛ الأمني بيقفل ثغرات وده الأهم.', 'Feature updates add new things; security updates close holes and matter most.'),
    T('eol', 'soft', 'End of support', 'انتهاء الدعم', 'الشركة بتبطّل تبعت تحديثات أمان؛ البرنامج بيشتغل بس بيبقى أخطر مع الوقت.', 'The maker stops sending security fixes; the software still runs but grows riskier.'),
    T('clean-install', 'soft', 'Clean install', 'تثبيت نضيف', 'تثبيت الويندوز من الأول على درايف ممسوح.', 'Installing Windows from scratch on a wiped drive.'),
    T('factory-reset', 'soft', 'Factory reset', 'إعادة ضبط المصنع', 'رجوع الجهاز لحالته يوم ما اشتريته ومسح كل حاجة.', 'Returning a device to its out-of-the-box state, erasing everything.'),
    T('safe-mode', 'soft', 'Safe Mode', 'الوضع الآمن', 'تشغيل الويندوز بأقل حاجة عشان تصلّح مشكلة.', 'Starting Windows with the bare minimum to fix a problem.'),
    T('registry', 'soft', 'Registry', 'الريجستري', 'قاعدة بيانات إعدادات الويندوز والبرامج؛ تعديلها غلط ممكن يبوّظ الجهاز.', 'Windows\' database of settings; wrong edits can break the PC.'),
    T('restore-point', 'soft', 'Restore point', 'نقطة استرجاع', 'لقطة لإعدادات النظام ترجعلها لو حاجة باظت.', 'A snapshot of system settings to return to if something breaks.'),
    T('bootable', 'soft', 'Bootable USB', 'فلاشة إقلاع', 'فلاشة الجهاز يقدر يشتغل منها (لتثبيت نظام أو إصلاح).', 'A stick the PC can start from (to install or repair a system).'),
    T('vm', 'soft', 'Virtual machine', 'جهاز افتراضي', 'كمبيوتر كامل بيشتغل جوه برنامج في شباك.', 'A whole computer running inside a program, in a window.'),
    T('emulator', 'soft', 'Emulator', 'المحاكي', 'برنامج بيقلّد جهاز تاني عشان يشغّل برامجه (ألعاب قديمة، أندرويد).', 'A program imitating another device to run its software (old games, Android).'),
    T('open-source', 'soft', 'Open source', 'مفتوح المصدر', 'برنامج الكود بتاعه متاح للكل يشوفه ويعدّله.', 'Software whose code anyone can read and change.'),
    T('freemium', 'soft', 'Freemium', 'مجاني بمزايا مدفوعة', 'نسخة ببلاش محدودة وحاجات مقفولة بالدفع.', 'A free version with limits and paid extras.'),
    T('portable', 'soft', 'Portable app', 'برنامج محمول', 'برنامج بيشتغل من غير تثبيت، من فولدر أو فلاشة.', 'A program that runs without installing, from a folder or stick.'),
    T('package-manager', 'soft', 'Package manager', 'مدير الحزم', 'أداة بتثبّت وتحدّث البرامج بالأوامر (زي winget).', 'A tool that installs and updates programs by command (like winget).'),
    T('extension-addon', 'soft', 'Extension / Add-on', 'إضافة', 'برنامج صغير بيزوّد مزايا للمتصفح أو برنامج؛ ممكن تبقى خطر.', 'A small program adding features to a browser or app; can be risky.'),
    T('pwa', 'soft', 'PWA', 'تطبيق ويب', 'موقع بيتثبت ويشتغل في شباك لوحده زي التطبيق.', 'A website installed to run in its own window like an app.'),
    T('apk', 'soft', 'APK', 'ملف تطبيق أندرويد', 'ملف تثبيت تطبيق أندرويد؛ من برّه المتجر فيه خطر.', 'An Android app installer file; from outside the store it carries risk.'),
    T('sideload', 'soft', 'Sideloading', 'التثبيت من برّه المتجر', 'تثبيت تطبيق من ملف مش من المتجر الرسمي.', 'Installing an app from a file rather than the official store.'),
    T('root', 'soft', 'Root / Jailbreak', 'كسر قيود الموبايل', 'فك قيود الشركة على الموبايل؛ بيكسر الحماية ونادرًا يستاهل.', 'Removing the maker\'s restrictions on a phone; it breaks protections and is rarely worth it.'),
    T('cli', 'soft', 'Command line', 'سطر الأوامر', 'تتعامل مع الجهاز بكتابة أوامر (Terminal، PowerShell).', 'Working with the computer by typing commands (Terminal, PowerShell).'),
    T('script-macro', 'soft', 'Script / Macro', 'سكريبت / ماكرو', 'خطوات مكتوبة بتتنفذ لوحدها؛ ما تشغّلش سكريبت ما تعرفش مصدره.', 'Written steps that run automatically; never run one from an unknown source.'),
    T('api', 'soft', 'API', 'واجهة برمجة', 'طريقة برنامج يكلّم برنامج تاني ويتبادلوا بيانات.', 'How one program talks to another to exchange data.'),
    T('beta', 'soft', 'Beta', 'نسخة تجريبية', 'نسخة قبل النهائية فيها مشاكل محتملة.', 'A pre-release version that may have bugs.'),
    T('llm', 'soft', 'LLM', 'نموذج لغوي كبير', 'نوع الذكاء الاصطناعي اللي ورا الشات بوتس؛ اتدرّب على نصوص كتير ويتوقع الكلام.', 'The AI behind chatbots; trained on vast text to predict language.'),
    T('agentic', 'soft', 'AI agent', 'وكيل ذكاء اصطناعي', 'ذكاء اصطناعي بينفّذ خطوات عنك (يتصفح، يملا فورم)، مش بس يرد.', 'AI that carries out steps for you (browses, fills forms), not just answers.'),
    T('copilot-pc', 'soft', 'Copilot+ PC', 'أجهزة كوبايلوت بلس', 'أجهزة ويندوز فيها NPU قوي لمزايا ذكاء اصطناعي على الجهاز.', 'Windows PCs with a powerful NPU for on-device AI features.'),
    T('distro', 'soft', 'Linux distro', 'توزيعة لينكس', 'نسخة من لينكس بشكل وبرامج معيّنة (Mint، Ubuntu، Zorin).', 'A version of Linux with its own look and apps (Mint, Ubuntu, Zorin).'),
    T('kernel', 'soft', 'Kernel', 'النواة', 'قلب نظام التشغيل اللي بيتكلم مع الهاردوير.', 'The core of an operating system that talks to the hardware.'),
    T('hotkey', 'soft', 'Hotkey', 'اختصار كيبورد', 'زراير مع بعض بتعمل أمر على طول (زي `Ctrl+C`).', 'Keys pressed together to run a command at once (like `Ctrl+C`).'),
    T('licence', 'soft', 'Licence / Product key', 'الترخيص ومفتاح المنتج', 'إذن استخدام البرنامج، وغالبًا كود بتكتبه عشان تفعّله.', 'Permission to use software, often with a code you type to activate it.'),
    T('dism-sfc', 'soft', 'SFC / DISM', 'أدوات إصلاح ويندوز', 'أوامر بتفحص ملفات الويندوز وتصلّح البايظ منها.', 'Commands that check Windows files and repair damaged ones.')
  ]
});
})();
