// Tips for tips.html — passwords, passkeys and sign-in (cards in the «tips» section of content/sections/tips.js).
(function(){
function C(id, lvl, ar, en, more){
  var o = { id: id, cat: 'pass', lvl: lvl, t: { ar: ar[0], en: en[0] }, body: { ar: ar[1], en: en[1] } };
  if(ar[2]) o.tip = { ar: ar[2], en: en[2] };
  if(more) for(var k in more) o[k] = more[k];
  return o;
}
SECTIONS.extend('tips', 'tips', { items: [
  C('pw-strong', 'b',
    ["باسورد قوي يعني طويل", "- **الطول أهم من التعقيد**: 12 حرف على الأقل، والأحسن 16.\n- جملة من 4 كلمات عشوائية مش مرتبطة ببعض (مع رقم ورمز) سهلة تفتكرها وصعب تتكسر: `Kursi-Batikh7-Sahab-Lamba`.\n- ما تستخدمش اسمك، تاريخ ميلادك، اسم ولادك، ولا كلمة واحدة من القاموس.\n- **باسورد مختلف لكل موقع**؛ ده أهم من أي حاجة تانية.", "ما تطلبش من شات بوت يعملك باسورد؛ المحادثات بتتحفظ. استخدم مولّد مدير الباسوردات."],
    ["A strong password means a long one", "- **Length beats complexity**: at least 12 characters, ideally 16.\n- A phrase of 4 random unrelated words (with a digit and symbol) is easy to remember and hard to crack: `Chair-Melon7-Cloud-Lamp`.\n- No names, birthdays, children's names or single dictionary words.\n- **A different password for every site**; this matters more than anything else.", "Do not ask a chatbot to make a password; chats are stored. Use your password manager's generator."]),
  C('pw-manager', 'b',
    ["مدير الباسوردات: الحل الحقيقي", "بيعمل باسورد عشوائي قوي لكل موقع ويفتكره ويملاه، وانت تفتكر **باسورد رئيسي واحد** بس.\n- **Bitwarden** (ببلاش ومفتوح المصدر، كل الأجهزة، passkeys، مشاركة مشفّرة).\n- **Proton Pass** (ببلاش، وفيه إيميلات بديلة).\n- **KeePassXC** (ملف محلي على جهازك، من غير سحابة).\n\nأحسن من باسوردات المتصفح: تشفير كامل، شغال على كل المتصفحات والتطبيقات، وبيخزّن كروت ومستندات وملاحظات سرية.", "مدير الباسوردات بيملا الباسورد على الدومين الصح بس؛ لو ما عرضش يملا، **بص على اللينك**، ممكن موقع مقلّد."],
    ["A password manager: the real fix", "It creates a strong random password for every site, remembers and fills it; you remember **one master password**.\n- **Bitwarden** (free, open source, all devices, passkeys, encrypted sharing).\n- **Proton Pass** (free, with email aliases).\n- **KeePassXC** (a local file on your PC, no cloud).\n\nBetter than browser passwords: full encryption, works across browsers and apps, and stores cards, IDs and secure notes.", "A manager only fills on the right domain; if it does not offer to fill, **check the link**, it may be a look-alike site."]),
  C('pw-master', 'b',
    ["الباسورد الرئيسي ومفاتيح الاسترجاع", "- الباسورد الرئيسي جملة طويلة **ما استخدمتهاش في أي مكان تاني**.\n- اعمل **Recovery codes / Emergency Kit** دلوقتي قبل ما تتقفل برّه، واحفظها ورقي في مكان أمين.\n- مفيش مدير باسوردات بيبعتلك إيميل يطلب الباسورد الرئيسي، ولا «تأكيد إنك عايش».\n- فعّل القفل التلقائي بعد فترة قصيرة من عدم الاستخدام.", "فكّر في «Emergency access» عشان حد تثق فيه يقدر يوصل لو حصلك حاجة."],
    ["The master password and recovery keys", "- The master password is a long phrase **you have used nowhere else**.\n- Create the **recovery codes / Emergency Kit** now, before you are locked out, and keep them on paper somewhere safe.\n- No password manager emails you for your master password or to «confirm you are alive».\n- Turn on auto-lock after a short idle time.", "Consider «emergency access» so someone you trust can get in if something happens to you."]),
  C('pw-move', 'i',
    ["انقل باسورداتك من المتصفح لمدير باسوردات", "1. من إعدادات المتصفح: Passwords > **Export** لملف CSV.\n2. في Bitwarden: Import data > اختار المتصفح > الملف.\n3. **امسح ملف الـ CSV فورًا** (الباسوردات فيه نص مكشوف) وفضّي سلة المحذوفات.\n4. اقفل حفظ الباسوردات في المتصفح عشان ما يبقاش عندك مكانين.", "الباسوردات المستوردة بين متصفحين ما بتفضلش متزامنة؛ خلي مكان واحد هو المرجع."],
    ["Move passwords from the browser to a manager", "1. In browser settings: Passwords > **Export** to a CSV file.\n2. In Bitwarden: Import data > choose the browser > the file.\n3. **Delete the CSV at once** (passwords are in plain text) and empty the Recycle Bin.\n4. Turn off password saving in the browser so you do not have two places.", "Passwords imported between browsers do not stay in sync; keep one place as the source of truth."]),
  C('pw-leaks', 'b',
    ["اتأكد إن باسوردك ما اتسربش", "- **haveibeenpwned.com**: اكتب إيميلك تشوف التسريبات، وفعّل «Notify me». فيه صفحة لفحص الباسورد نفسه بطريقة مجهّلة.\n- **Password Checkup** في جوجل (passwords.google.com)، وSecurity Recommendations في آيفون، وتقارير Bitwarden وProton.\n- إيميلك ظهر في تسريب ≠ باسوردك اتسرب؛ بس غيّر أي باسورد متكرر.\n- امسح الحسابات اللي مش بتستخدمها.", "بعد تسريب كبير ابدأ بالإيميل والبنك، وبعدين الباقي على مهلك."],
    ["Check whether your password leaked", "- **haveibeenpwned.com**: enter your email to see breaches and turn on «Notify me». A separate page checks a password anonymously.\n- Google's **Password Checkup** (passwords.google.com), iPhone Security Recommendations, and Bitwarden or Proton reports.\n- Your email in a breach ≠ your password leaked; still change any reused password.\n- Delete accounts you no longer use.", "After a big breach start with email and banking, then the rest over time."]),
  C('pw-2fa', 'b',
    ["التحقق بخطوتين (2FA): فعّله على الأقل في الإيميل والبنك", "من إعدادات الأمان في الحساب > Two-step verification:\n- **تطبيق مصادقة** (Authenticator) أأمن من رسايل SMS.\n- **احفظ أكواد الاحتياط** (backup codes) ورقي.\n- الإيميل هو «المفتاح الرئيسي» لكل حساباتك (منه بيرجّعوا الباسوردات)، فده أول واحد تحميه.", "حساب بيطلب رقم تليفون تاني؟ غالبًا تقدر تستخدم تطبيق مصادقة بداله."],
    ["Two-step verification (2FA): at least on email and banking", "In the account's security settings > Two-step verification:\n- An **authenticator app** is safer than SMS codes.\n- **Save the backup codes** on paper.\n- Your email is the «master key» to every account (passwords are reset through it), so protect it first.", "An account demanding a second phone number? You can usually use an authenticator app instead."]),
  C('pw-authenticator', 'i',
    ["تطبيقات المصادقة: إزاي تشتغل وإزاي ما تخسرهاش", "الـ QR وقت الإعداد فيه **مفتاح سري** مشترك بينك وبين الموقع؛ الاتنين بيحسبوا نفس الكود من المفتاح والوقت كل 30 ثانية، فبيشتغل **من غير نت**.\n- تطبيقات: **Ente Auth** (موبايل وكمبيوتر بمزامنة مشفّرة)، **2FAS**، **Aegis**، Microsoft أو Google Authenticator.\n- فعّل **نسخة احتياطية** للتطبيق؛ لو ضاع الموبايل من غيرها هتعيد إعداد كل حساب.\n- اختار تطبيق فيه Export عشان لو حبيت تنقل.", "تطبيقات كتير بتمنع السكرين شوت عن قصد؛ ده طبيعي."],
    ["Authenticator apps: how they work and how not to lose them", "The setup QR holds a **secret key** shared by you and the site; both compute the same code from the key and the time every 30 seconds, so it works **offline**.\n- Apps: **Ente Auth** (phone and PC with encrypted sync), **2FAS**, **Aegis**, Microsoft or Google Authenticator.\n- Turn on the app's **backup**; without it, a lost phone means re-enrolling every account.\n- Pick an app with export so you can switch later.", "Many authenticator apps block screenshots on purpose; that is normal."]),
  C('pw-passkeys', 'b',
    ["الـ Passkeys: الدخول من غير باسورد", "بدل الباسورد بتفتح بالبصمة أو الوش أو PIN الجهاز:\n- **ما ينفعش يتسرق بالـ phishing**: الـ passkey مربوط بالموقع الحقيقي، والموقع المزيّف ما يقدرش يستخدمه.\n- الموقع عنده **المفتاح العام** بس، والمفتاح الخاص ما بيخرجش من جهازك؛ فمفيش حاجة تتسرب من الموقع.\n- فعّله من إعدادات الأمان في جوجل ومايكروسوفت وآبل وأمازون وPayPal وفيسبوك وواتساب.", "جرّب الـ passkey الجديد في نافذة خاصة قبل ما تعتمد عليه."],
    ["Passkeys: signing in without a password", "Instead of a password you unlock with your fingerprint, face or device PIN:\n- **Cannot be phished**: a passkey is bound to the real site, and a fake site cannot use it.\n- The site only holds the **public key**; the private key never leaves your device, so nothing useful leaks from the site.\n- Turn it on in the security settings of Google, Microsoft, Apple, Amazon, PayPal, Facebook and WhatsApp.", "Test a new passkey in a private window before relying on it."]),
  C('pw-passkeys-where', 'i',
    ["الـ Passkeys بتتحفظ فين؟", "- **مدير باسوردات جوجل**: بيتزامن مع Chrome وأندرويد.\n- **iCloud Keychain**: أجهزة آبل بس.\n- **Windows Hello**: على الكمبيوتر ده بس (`Settings > Accounts > Passkeys`).\n- **Bitwarden أو Proton Pass**: على كل الأنظمة.\n\nبتنقل بين أندرويد وآيفون وويندوز؟ مدير باسوردات مستقل أريح. ولو الـ passkey على جهاز تاني: «Use a phone or tablet» > QR بالموبايل (البلوتوث لازم يكون شغال).", "أندرويد: `Settings > Passwords, passkeys & accounts > Preferred service` يحدد مين يحفظها."],
    ["Where are passkeys stored?", "- **Google Password Manager**: syncs with Chrome and Android.\n- **iCloud Keychain**: Apple devices only.\n- **Windows Hello**: this PC only (`Settings > Accounts > Passkeys`).\n- **Bitwarden or Proton Pass**: every platform.\n\nSwitching between Android, iPhone and Windows? An independent manager is easier. If the passkey is on another device: «Use a phone or tablet» > scan the QR (Bluetooth must be on).", "Android: `Settings > Passwords, passkeys & accounts > Preferred service` sets where they are saved."]),
  C('pw-passkey-mistakes', 'i',
    ["أخطاء الـ Passkeys اللي تتجنبها", "- **ما تقفلش قفل الشاشة**: من غيره الـ passkeys مش هتشتغل.\n- خلي **باسورد قوي + 2FA** كبديل، وأكواد استرجاع، وpasskey تاني على جهاز تاني.\n- ضاع جهاز؟ امسح الـ passkey بتاعه من حسابك (`Google > Passkeys`).\n- إضافات المتصفح المشبوهة ممكن تستغل الـ passkeys؛ خليها قليلة.\n- أجهزة قديمة جدًا والحسابات المشتركة: استنى عليهم.", "تغيير البصمة أو الـ PIN ما بيمسحش الـ passkeys."],
    ["Passkey mistakes to avoid", "- **Do not turn off the screen lock**: passkeys stop working without it.\n- Keep a **strong password + 2FA** as fallback, recovery codes, and a second passkey on another device.\n- Lost a device? Remove its passkey from your account (Google > Passkeys).\n- Dodgy browser extensions can abuse passkeys; keep them few.\n- Very old devices and shared accounts: wait.", "Changing your fingerprint or PIN does not delete passkeys."]),
  C('pw-hello-pin', 'b',
    ["PIN ويندوز Hello أأمن من الباسورد", "الـ PIN محفوظ في شريحة الأمان (TPM) في الجهاز ده بس وعمره ما بيتبعت أونلاين؛ اللي يعرفه من غير الجهاز مش هيستفيد.\n- تقدر تخليه فيه حروف ورموز: `Sign-in options > PIN > Change PIN` > «Include letters and symbols».\n- استخدم PIN مختلف لكل جهاز.", "بصمتك ضعيفة؟ PIN أو كاميرا وش بالأشعة تحت الحمرا."],
    ["A Windows Hello PIN is safer than a password", "The PIN lives in the security chip (TPM) of this device only and is never sent online; knowing it without the device is useless.\n- It can include letters and symbols: `Sign-in options > PIN > Change PIN` > «Include letters and symbols».\n- Use a different PIN on each device.", "Worn fingerprints? Use a PIN or an infrared face camera."]),
  C('pw-recovery-info', 'b',
    ["حدّث بيانات استرجاع حساباتك كل سنة", "إيميل استرجاع قديم مقفول أو رقم قديم = مش هتعرف ترجع حسابك.\n- جوجل: `myaccount.google.com > Security` (وفيه **Recovery contacts**).\n- مايكروسوفت: `account.microsoft.com > Security > Manage how I sign in`.\n- شيل الطرق القديمة وزوّد الجديدة.", "استخدم أسماء مستخدمين مختلفة كمان؛ مدير الباسوردات فيه مولّد أسماء."],
    ["Update your account recovery details every year", "An old closed recovery email or old number = you cannot get your account back.\n- Google: myaccount.google.com > Security (including **Recovery contacts**).\n- Microsoft: account.microsoft.com > Security > Manage how I sign in.\n- Remove old methods and add new ones.", "Use different usernames too; password managers have a username generator."]),
  C('pw-share', 'i',
    ["شارك باسورد مع العيلة بأمان", "- **Google Password Manager**: Share لعضو في Family group.\n- **Bitwarden**: Send (رسالة مشفّرة بتتمسح لوحدها)، وتنظيم مجاني يتشارك فيه مع شخص.\n- خطط العيلة في مديري الباسوردات: خزنة خاصة لكل فرد + حاجات مشتركة.\n\nما تبعتش باسورد في واتساب أو SMS أو إيميل.", "لما تساعد حد من بعيد، هو اللي يوافق على الدخول من جهازه؛ عمره ما يقولك الباسورد."],
    ["Share a password with family safely", "- **Google Password Manager**: Share with a Family group member.\n- **Bitwarden**: Send (an encrypted message that self-deletes), and a free organisation shared with one person.\n- Family plans in password managers: a private vault each + shared items.\n\nNever send a password by WhatsApp, SMS or email.", "When helping someone remotely, they approve the sign-in on their own device; they never tell you the password."]),
  C('pw-email-otp', 'i',
    ["الدخول بكود على الإيميل مش أضعف", "مواقع كتير بتبعت كود على الإيميل بدل الباسورد. ده مش أضعف لأن إيميلك أصلًا هو اللي بيرجّع أي باسورد؛ المهم تحمي الإيميل نفسه بباسورد فريد وخطوتين.", "لو بتسجل في حاجة ومش عايز تدّي إيميلك الحقيقي: إيميل بديل (alias)."],
    ["Email-code sign-in is not weaker", "Many sites send a code to your email instead of a password. That is not weaker, because your email already resets any password; what matters is protecting the email itself with a unique password and 2FA.", "Signing up without giving your real address: use an email alias."])
] });
})();
